### ISSUE TITLE
Зависание EDT при вызове code assist-а в редакторе модуля

### ISSUE THREAD

**Issue by tretyakevich** [1C-Company/1c-edt-issues#1]
Нажатие Ctrl + Пробел в тексте модуля привело к зависанию EDT - весь интерфейс недоступен, в заголовке окна "(Не отвечает)".
Дамп потоков прикладываю. 2021.2.6
[threaddump.zip](https://github.com/1C-Company/1c-edt-issues/files/7386908/threaddump.zip)

**Comment by RedMammoth** [comment]
OS: ubuntu 20.04
EDT: 2021.2.8
Сценарий тот же, при нажатии ctrl+space в тексте модуля привело к зависанию.

Прикладываю threadump и memorydump:

[threaddump.zip](https://github.com/1C-Company/1c-edt-issues/files/7478119/threaddump.zip)
memorydump - https://1drv.ms/u/s!ApPB_eb3xeO2pGl5f3BQ2LOAwsQl?e=FiJUk5

**Comment by tretyakevich** [comment]
Исправлена в мастере 2021.3

**Comment by RedMammoth** [comment]
> Исправлена в мастере 2021.3

Подскажите, есть ли рекомендации как избегать этой ошибки на версии 2021.2.10?  Ловлю примерно раз в день, при разработке формы

**Comment by MaksimDzyuba** [comment]
Здравствуйте, а на какой версии EDT Вы сейчас?

**Comment by RedMammoth** [comment]
> Здравствуйте, а на какой версии EDT Вы сейчас?

Здравствуйте, OS: ubuntu, 1C: 8.3.20, edt: 2021.2.10

**Comment by MaksimDzyuba** [comment]
а можете еще раз дамп потоков снять, пожалуйста

**Comment by RedMammoth** [comment]
> а можете еще раз дамп потоков снять, пожалуйста

[threaddump.txt](https://github.com/1C-Company/1c-edt-issues/files/7605355/threaddump.txt)

**Comment by MaksimDzyuba** [comment]
В общем, еще раз посмотрел, это не то, что было изначально, то мы поправили, вот сейчас - это https://bugs.eclipse.org/bugs/show_bug.cgi?id=552459, https://bugs.eclipse.org/bugs/show_bug.cgi?id=567881, но оно похоже не двигается, какие-то особенности операционной системы, можете чуть подробнее рассказать, что у Вас за операционка, и как настроена?

**Comment by RedMammoth** [comment]
Хост ОС: Windows 10 Pro 1909, в ней установлен Hyper-V, в Hyper-V создана VM с динамическим выделением оперативной памяти [6.5-13] Гб, с динамическим диском на 120Гб, 12 ядер.
Гостевая ОС на VM: Ubuntu 21.10 (Linux 5.13.0-22-generic #22-Ubuntu SMP Fri Nov 5 13:21:36 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux).
В гостевой ОС настраивал следующее:
- postgrespro-1c-14 (у него только настроил pg_stat_tmp на tmpfs, и изменил random_page_cost)
- установил 1с 8.3.20.1613 (клиент, сервер), дополнительно ставил пакет libenchant1c2a, каталог и порты стандартные, дописал в /etc/init.d/srv1cv8.3.20.1613 флаг -http для отладки
- установил 1с 8.3.16.1973 (клиент, сервер), дополнительно ставил пакеты (unixodbc, libfontconfig1, libgsf-1-114 , libglib2.0-0 , libodbc1 , libkrb5-3 , libgssapi-krb5-2,  libwebkitgtk-3.0-0), настроил в файле /etc/init.d/srv1cv83 альтернативный каталог кластера, порты сервера, флаг -http для отладки и альтернативый порт отладки)
- настроил nethasp.ini на получение ключей по сети
- установил bellsoft_jdk11.0.127_linux_amd64_full.deb
- установил 1c_edt_distr_offline_2021.2.10_2_linux_x86_64.tar.gz (настройки 1cedt.ini не менял, установил плагины ssl-suport, v8-codestyle, LiClips, edt-editing, Language Tools), т.к. при установке не скачивается nginx (скорей всего мешает прокси), то ставлю пакет nginx самостоятельно и создаю ссылку sudo ln -s /usr/sbin/nginx /opt/1C/1CE/components/1c-edt-2021.2.10+2-x86_64/plugins/com.company1c.link.agent.publicator.linux_3.0.3/binaries/nginx/nginx (иначе будут ошибки при установке плагинов)
- установил xrdp (настройки стандартные, добавил только команду при запуске профиля
  "setxkbmap -option 'grp:alt_shift_toggle,grp:switch,grp_led:scroll,compose:menu' -layout 'us,ru'" - без нее иногда проблемы с раскладкой клавиатуры
- из прочих программ дополнительно ставил vim, git, vs code, sublime text, sublime merge

Подключаюсь к гостевой ОС по rdp, в настройках отключаю принтеры, иначе не работает буфер и не шарятся диски

**Comment by RedMammoth** [comment]
Вряд ли связано, скорее совпадение, но вдруг:
последнее время работаю в edt в полноэкранном режиме, так eclipse под ubuntu больше горячих клавиш перехватывает (например ctrl + alt + d), последние пару дней зависаний не было, еще правда закончил работать над формой, ушел больше в общие модули и модули менеджера.

**Comment by MaksimDzyuba** [comment]
да не, полноэкранный режим там вряд ли влияет. Если не установлено, но вроде должно быть, то поставте libgtk-3-0. И еще, можно попробовать в настройках, поменять браузер по умолчанию - не факт, но вроде из обсуждений, может помочь. Вообще беда тут именно вот в окне, в котором EDT отображается справку при content-assist, из-за него проблема, так как мы пользуемся стандартным, а с ним вот те проблемы в Eclipse, что уже зарегали, но не решили(. Браузер меняется, как на картинке показано.
![image](https://user-images.githubusercontent.com/77277424/144597504-f538a607-b722-4875-b8a5-571850424579.png)

**Comment by RedMammoth** [comment]
Спасибо! Да libgtk-3-0 уже был установлен, попробую с настройкой браузера
