### ISSUE TITLE
После импорта формы списка с произвольным запросом динсписка и импортом самого динамического списка не получается собрать конфигурацию.

### ISSUE THREAD

**Issue by mrshadow300373** [1C-Company/1c-edt-issues#1001]
### Описание ошибки

При попытке сбора конфигурации расширения возникает ошибка:
"Операция конфигурирования завершена неуспешно" 
Ошибка загрузки выгрузки конфигурации
![image](https://github.com/1C-Company/1c-edt-issues/assets/34220218/6b426ec7-f172-494b-bdae-18117d72292d)
Иногда помогает решить проблему очистка типов параметров СКД дин. списка кроме простых дат, число булево, если они есть у запроса, но в этот раз бесполезно:
![image](https://github.com/1C-Company/1c-edt-issues/assets/34220218/d6637431-d267-4350-ac9c-81bcb43a05fd)

### Как воспроизвести

На примере типовой конфигурации СППР текущего релиза 2.0.7.3 
1. Импортировать форму с динамическим списком и произвольным запросом в динамическом списке в расширение - ЗадачиПроцесса.ФормаСпискаПараметрическая,
2. Запустить сборку расширение - расширение соберется без ошибок
3. Далее, импортировать основной реквизит список в форму:
![image](https://github.com/1C-Company/1c-edt-issues/assets/34220218/1b7b4b48-e0d0-4f25-8e88-4a57d15bf2a1)
4. Запустить сборку конфигурации - будет ошибка как в описании. 
5. Выгрузить (экспортировать) проект в XML в какой ни будь каталог, например d:\tmp\XML_1С_EDT
6. Открыть конфигуратор и сделать шаг 3 в нём, то после запуска 1С:Предприятия расширение будет работать.
7. Выгрузить расширение в XML в другой каталог, отличный от 5, например d:\tmp\XML_1C
8. Сравнить два файла XML_1С_EDT\Catalogs\ЗадачиПроцесса\Forms\ФормаСпискаПараметрическая\Ext\Form.xml и XML_1С\Catalogs\ЗадачиПроцесса\Forms\ФормаСпискаПараметрическая\Ext\Form.xml будет примерно так, в секциях ЭФ: Table\ChildItems\LabelFIelds\DataPath, выгруженные из EDT будут отсутствовать:
![image](https://github.com/1C-Company/1c-edt-issues/assets/34220218/5b7bcd5a-26f7-4ccb-a6cf-90a554f8838c)
![image](https://github.com/1C-Company/1c-edt-issues/assets/34220218/65596e1e-4806-4930-822d-4c40dae07a58)
Оба XML приложил:
EDT: [Form.zip](https://github.com/1C-Company/1c-edt-issues/files/11472232/Form.zip)
Конфигуратор: [Form.zip](https://github.com/1C-Company/1c-edt-issues/files/11472234/Form.zip)
Импортировать изменённую в конфигураторе форму в проект, увы не возможно, EDT изменений в расширении сделанных конфигуратором не видит совсем.
![image](https://github.com/1C-Company/1c-edt-issues/assets/34220218/0f239c54-7516-4258-881c-bc704042609c)
Но это уже другая ошибка, долго искал её среди зарегистрированных, но её нет, попробую создать тест кейс и зарегистрировать.
Попробовал загрузить изменения сделанные в конфигураторе, конвертировав выгрузку расширения из XML в EDT через утилиту ring. Однако для выбранной формы, с полученным проектом что то слишком много отличий, для формы из конфигуратора, например, отсутствуют команды:
![image](https://github.com/1C-Company/1c-edt-issues/assets/34220218/50c6d8b8-8ec8-4488-b383-4503a6a46a7e)
Они же отсутствуют в основной форме:
![image](https://github.com/1C-Company/1c-edt-issues/assets/34220218/59e00493-a18f-4bc9-b844-b193ec8bdb6b)
Далее, уже в элементах формы тоже отсутствуют команды:
![image](https://github.com/1C-Company/1c-edt-issues/assets/34220218/cfb4fe5e-0182-48b3-809f-419a92bb5602)
Но каких то ожидаемых отличий, объясняющих отсутствие путей в результирующем XML в них нет. 
Файлы форм в виде проектов EDT прилагаю:
[ФормаСпискаПараметрическая_conv_by_ring_from_designer.zip](https://github.com/1C-Company/1c-edt-issues/files/11472297/_conv_by_ring_from_designer.zip)
[ФормаСпискаПараметрическая_made_in_EDT.zip](https://github.com/1C-Company/1c-edt-issues/files/11472301/_made_in_EDT.zip)

Очень буду рад, если предложите какой либо способ обхода проблемы.

### Ожидаемое поведение

Форма должна работать после импорта в расширение и импорта основного реквизита - динамического списка в расширение.

### Лог рабочей области

[Logs2.zip](https://github.com/1C-Company/1c-edt-issues/files/11472204/Logs2.zip)

### Версия 1С:EDT

2022.2.5

### Операционная система

Windows, Linux

### Дополнительная информация

Версия платформы 8.3.21.1775
Совместимость отсутствует (актуальное 8.3.21), совместимость расширения отсутствует (8.3.21)
Базовая конфигурация СППР 2.0.7.3

**Comment by mrshadow300373** [comment]
**!ВАЖНО!** В итоге всё же удалось "завести" форму. Проблема в том, что BaseForm тащится "левая" основная таблица: Перечисление.СтатусыЗадач. а должна быть справочник .ЗадачиПроцесса. В импортированной форме можно изменить интерактивно, а в базовой форме только в XML. Но если изменить, то форма работает корректно.

**Comment by vadimeg** [comment]
> Но это уже другая ошибка, долго искал её среди зарегистрированных, но её нет, попробую создать тест кейс и зарегистрировать.

@mrshadow300373 По этому кейсу лучше дождаться выхода 2023.1, там подобная ошибка была исправлена. Не 100% гарантия, т.к. возможно это другая ситуация

**Comment by vadimeg** [comment]
@mrshadow300373 В EDT 2 ошибки, связанные с этим сценарием.
1. При заимствовании дин.списка по его запросу не были автоматически заимствованы значения двух перечислений
2. В расширении у динсписка былы неправильно вычислена основная таблица.

На картинке ниже в навигаторе выделены отсутствующие реквизиты, а в редакторе запроса заимствованного реквизита списка выделена правильная главная таблица.

Попробуйте сделать следующее:
1. Заимствовать форму ЗадачиПроцесса.ФормаСпискаПараметрическая в расширение (1-й шаг в описании проблемы)
2. Вручную из основной конфигурации заимствовать недостающие значения (на картинке слева)
3. В редакторе заимствованной формы добавить основной реквизит (список) в расширение
4. В палитре открыть у этого списка редактор запроса и поменять ему основную таблицу, чтобы было как на картинке

После этого ошибок в расширении быть не должно и экспорт должен корректно отработать.
Ошибки будем исправлять.


![image](https://github.com/1C-Company/1c-edt-issues/assets/17178862/5af5dfb3-39d7-4946-a095-553d1ad4f2de)

**Comment by mrshadow300373** [comment]
> 4\. В палитре открыть у этого списка редактор запроса и поменять ему основную таблицу, чтобы было как на картинке

Я так делал, однако этого оказалось недостаточно, падать перестало только тогда, когда в хмл базовой формы руками поставил так же правильную таблицу. Интерактивно этого сделать не возможною. (я там в комментарии как раз про это писал). Или имеется в виду, что если значения перечислений предварительно правильно импортирую то и в базовой форме правильная основная таблица появится?

**Comment by vadimeg** [comment]
Да, действительно не перезаписывается основная таблица в BaseForm. И тут правда на UI это не поправишь, только в xml формы. Будем разбираться, как туда попала неправильная таблица

**Comment by vadimeg** [comment]
Исправлено в 2023.1
