### ISSUE TITLE
Таблица с именем не найдена.

### ISSUE THREAD

**Issue by leonvlas** [1C-Company/1c-edt-issues#1002]
### Описание ошибки

в СКД в поле запрос отображается ошибка, Таблица с именем 'ПланВидовРасчета.Начисления' не найден

если используется инструкция ТИП(ПланВидовРасчета.Начисления)   - ошибка есть
если используется инструкция ЗНАЧЕНИЕ(ПланВидовРасчета.Начисления.ПустаяСсылка) - ошибки нет 
На скриншотах сами ошибки

### Как воспроизвести

1. Метаданные для отчета -> Зарплата и управление персоналом КОРП, редакция 3.1  (3.1.23.656) 
2. Создать запрос отчет -> в основную схему вставить запрос.(Запрос прилагается)
3. Прокрутите вниз до `ТИП(ПланВидовРасчета.Начисления)`. (к сожалению нет номеров строк, а было бы приятно)
4. Смотрите ошибку. `Таблица с именем 'ПланВидовРасчета.Начисления' не найден`скрины прилагаю.
5. Ruby 2022.2.5

`ВЫБРАТЬ РАЗРЕШЕННЫЕ
	ФизическиеЛица.Ссылка КАК ФизическоеЛицо,
	&НачалоПериода КАК НачалоПериода,
	&ОкончаниеПериода КАК ОкончаниеПериода
ПОМЕСТИТЬ ВТПериодыНачисленныхДоходов
ИЗ
	Справочник.ФизическиеЛица КАК ФизическиеЛица
;

////////////////////////////////////////////////////////////////////////////////
ВЫБРАТЬ
	ДАТАВРЕМЯ(1, 1, 1) КАК МесяцНачисления,
	ЗНАЧЕНИЕ(Справочник.Организации.ПустаяСсылка) КАК Организация,
	ЗНАЧЕНИЕ(Справочник.ФизическиеЛица.ПустаяСсылка) КАК ФизическоеЛицо,
	ЗНАЧЕНИЕ(Справочник.Сотрудники.ПустаяСсылка) КАК Сотрудник,
	НЕОПРЕДЕЛЕНО КАК ДокументОснование,
	НЕОПРЕДЕЛЕНО КАК Начисление,
	ВЫРАЗИТЬ(0 КАК ЧИСЛО(5, 2)) КАК Начислено,
	НЕОПРЕДЕЛЕНО КАК Регистратор,
	ИСТИНА КАК ОблагаетсяНДФЛ,
	ДАТАВРЕМЯ(1, 1, 1) КАК ЗачетАванса
ПОМЕСТИТЬ Представления_НачисленныеДоходыНДФЛ
;

////////////////////////////////////////////////////////////////////////////////
ВЫБРАТЬ
	Представления_НачисленныеДоходыНДФЛ.МесяцНачисления КАК МесяцНачисления,
	Представления_НачисленныеДоходыНДФЛ.ДокументОснование КАК ДокументОснование,
	Представления_НачисленныеДоходыНДФЛ.Организация КАК Организация,
	Представления_НачисленныеДоходыНДФЛ.ФизическоеЛицо КАК ФизическоеЛицо,
	Представления_НачисленныеДоходыНДФЛ.Сотрудник КАК Сотрудник,
	Представления_НачисленныеДоходыНДФЛ.Начисление КАК Начисление,
	СУММА(Представления_НачисленныеДоходыНДФЛ.Начислено) КАК Начислено,
	Представления_НачисленныеДоходыНДФЛ.Регистратор КАК Регистратор,
	Представления_НачисленныеДоходыНДФЛ.ОблагаетсяНДФЛ КАК ОблагаетсяНДФЛ,
	Представления_НачисленныеДоходыНДФЛ.ЗачетАванса КАК ЗачетАванса
ПОМЕСТИТЬ ВТ_НачисленияЗаПериод
ИЗ
	Представления_НачисленныеДоходыНДФЛ КАК Представления_НачисленныеДоходыНДФЛ

СГРУППИРОВАТЬ ПО
	Представления_НачисленныеДоходыНДФЛ.ФизическоеЛицо,
	Представления_НачисленныеДоходыНДФЛ.ДокументОснование,
	Представления_НачисленныеДоходыНДФЛ.МесяцНачисления,
	Представления_НачисленныеДоходыНДФЛ.Организация,
	Представления_НачисленныеДоходыНДФЛ.Начисление,
	Представления_НачисленныеДоходыНДФЛ.Регистратор,
	Представления_НачисленныеДоходыНДФЛ.ОблагаетсяНДФЛ,
	Представления_НачисленныеДоходыНДФЛ.ЗачетАванса,
	Представления_НачисленныеДоходыНДФЛ.Сотрудник

ИНДЕКСИРОВАТЬ ПО
	Организация,
	ФизическоеЛицо,
	Сотрудник,
	МесяцНачисления,
	ДокументОснование,
	ЗачетАванса,
	Начисление
;

////////////////////////////////////////////////////////////////////////////////
ВЫБРАТЬ
	СведенияОДоходахНДФЛ.Регистратор КАК Регистратор,
	ВТ_НачисленияЗаПериод.Организация КАК Организация,
	ВТ_НачисленияЗаПериод.ФизическоеЛицо КАК ФизическоеЛицо,
	ВТ_НачисленияЗаПериод.Сотрудник КАК Сотрудник,
	СведенияОДоходахНДФЛ.МесяцНалоговогоПериода КАК МесяцНалоговогоПериода,
	СУММА(СведенияОДоходахНДФЛ.СуммаДохода) КАК Доход,
	ВТ_НачисленияЗаПериод.Начисление КАК Начисление,
	СведенияОДоходахНДФЛ.ДокументОснование КАК ДокументОснование,
	ВТ_НачисленияЗаПериод.МесяцНачисления КАК МесяцНачисления,
	СУММА(СведенияОДоходахНДФЛ.СуммаВычета) КАК Вычет,
	СведенияОДоходахНДФЛ.КодДохода КАК КодДохода,
	СведенияОДоходахНДФЛ.КодВычета КАК КодВычета,
	СведенияОДоходахНДФЛ.КатегорияДохода КАК КатегорияДохода,
	СведенияОДоходахНДФЛ.РегистрацияВНалоговомОргане КАК РегистрацияВНалоговомОргане
ПОМЕСТИТЬ ВТ_ПолученныеДоходы
ИЗ
	ВТ_НачисленияЗаПериод КАК ВТ_НачисленияЗаПериод
		ВНУТРЕННЕЕ СОЕДИНЕНИЕ РегистрНакопления.СведенияОДоходахНДФЛ КАК СведенияОДоходахНДФЛ
		ПО ВТ_НачисленияЗаПериод.Организация = СведенияОДоходахНДФЛ.ГоловнаяОрганизация
			И ВТ_НачисленияЗаПериод.ФизическоеЛицо = СведенияОДоходахНДФЛ.ФизическоеЛицо
			И ВТ_НачисленияЗаПериод.Сотрудник = СведенияОДоходахНДФЛ.Сотрудник
			И (ВТ_НачисленияЗаПериод.ДокументОснование = СведенияОДоходахНДФЛ.ДокументОснование
				ИЛИ ВТ_НачисленияЗаПериод.ЗачетАванса = СведенияОДоходахНДФЛ.ЗарегистрированоПриНачисленииАванса)
			И ВТ_НачисленияЗаПериод.Начисление = СведенияОДоходахНДФЛ.Начисление
			И (ВЫБОР
				КОГДА ТИПЗНАЧЕНИЯ(ВТ_НачисленияЗаПериод.Начисление) = ТИП(ПланВидовРасчета.Начисления)
					ТОГДА ВТ_НачисленияЗаПериод.МесяцНачисления = НАЧАЛОПЕРИОДА(СведенияОДоходахНДФЛ.Период, МЕСЯЦ)
				ИНАЧЕ ИСТИНА
			КОНЕЦ)
			

СГРУППИРОВАТЬ ПО
	ВТ_НачисленияЗаПериод.МесяцНачисления,
	ВТ_НачисленияЗаПериод.Организация,
	ВТ_НачисленияЗаПериод.ФизическоеЛицо,
	ВТ_НачисленияЗаПериод.Начисление,
	СведенияОДоходахНДФЛ.Регистратор,
	СведенияОДоходахНДФЛ.МесяцНалоговогоПериода,
	СведенияОДоходахНДФЛ.КодДохода,
	СведенияОДоходахНДФЛ.КодВычета,
	СведенияОДоходахНДФЛ.КатегорияДохода,
	СведенияОДоходахНДФЛ.РегистрацияВНалоговомОргане,
	СведенияОДоходахНДФЛ.ДокументОснование,
	ВТ_НачисленияЗаПериод.Сотрудник
;

////////////////////////////////////////////////////////////////////////////////
ВЫБРАТЬ
	ВТ_НачисленияЗаПериод.МесяцНачисления КАК МесяцНачисления,
	ВТ_НачисленияЗаПериод.ДокументОснование КАК ДокументОснование,
	ВТ_НачисленияЗаПериод.Организация КАК Организация,
	ВТ_НачисленияЗаПериод.ФизическоеЛицо КАК ФизическоеЛицо,
	ВТ_НачисленияЗаПериод.Сотрудник КАК Сотрудник,
	ВТ_НачисленияЗаПериод.Начисление КАК Начисление,
	ВТ_НачисленияЗаПериод.Начислено КАК Начислено,
	ВТ_НачисленияЗаПериод.Регистратор КАК Регистратор,
	NULL КАК МесяцНалоговогоПериода,
	0 КАК Доход,
	0 КАК Вычет,
	ВТ_НачисленияЗаПериод.ОблагаетсяНДФЛ КАК ОблагаетсяНДФЛ,
	NULL КАК КодДохода,
	NULL КАК КодВычета,
	NULL КАК КатегорияДохода,
	NULL КАК РегистрацияВНалоговомОргане
ПОМЕСТИТЬ ВТ_НачисленияДоходы
ИЗ
	ВТ_НачисленияЗаПериод КАК ВТ_НачисленияЗаПериод

ОБЪЕДИНИТЬ ВСЕ

ВЫБРАТЬ
	ВТ_ПолученныеДоходы.МесяцНачисления,
	ВТ_ПолученныеДоходы.ДокументОснование,
	ВТ_ПолученныеДоходы.Организация,
	ВТ_ПолученныеДоходы.ФизическоеЛицо,
	ВТ_ПолученныеДоходы.Сотрудник,
	ВТ_ПолученныеДоходы.Начисление,
	0,
	ВТ_ПолученныеДоходы.Регистратор,
	ВТ_ПолученныеДоходы.МесяцНалоговогоПериода,
	ВТ_ПолученныеДоходы.Доход,
	ВТ_ПолученныеДоходы.Вычет,
	ИСТИНА,
	ВТ_ПолученныеДоходы.КодДохода,
	ВТ_ПолученныеДоходы.КодВычета,
	ВТ_ПолученныеДоходы.КатегорияДохода,
	ВТ_ПолученныеДоходы.РегистрацияВНалоговомОргане
ИЗ
	ВТ_ПолученныеДоходы КАК ВТ_ПолученныеДоходы
;

////////////////////////////////////////////////////////////////////////////////
ВЫБРАТЬ
	ВТ_НачисленияДоходы.МесяцНачисления КАК МесяцНачисления,
	ВТ_НачисленияДоходы.ДокументОснование КАК ДокументОснование,
	ВТ_НачисленияДоходы.Организация КАК Организация,
	ВТ_НачисленияДоходы.ФизическоеЛицо КАК ФизическоеЛицо,
	ВТ_НачисленияДоходы.Сотрудник КАК Сотрудник,
	ВТ_НачисленияДоходы.Начисление КАК Начисление,
	СУММА(ВТ_НачисленияДоходы.Начислено) КАК Начислено,
	ВТ_НачисленияДоходы.Регистратор КАК Регистратор,
	ВТ_НачисленияДоходы.МесяцНалоговогоПериода КАК МесяцНалоговогоПериода,
	СУММА(ВТ_НачисленияДоходы.Доход) КАК Доход,
	СУММА(ВТ_НачисленияДоходы.Вычет) КАК Вычет,
	МИНИМУМ(ВТ_НачисленияДоходы.ОблагаетсяНДФЛ) КАК ОблагаетсяНДФЛ,
	ВТ_НачисленияДоходы.КодДохода КАК КодДохода,
	ВТ_НачисленияДоходы.КодВычета КАК КодВычета,
	ВТ_НачисленияДоходы.КатегорияДохода КАК КатегорияДохода,
	ВТ_НачисленияДоходы.РегистрацияВНалоговомОргане КАК РегистрацияВНалоговомОргане
ПОМЕСТИТЬ ВТ_НачисленияДоходыСводно
ИЗ
	ВТ_НачисленияДоходы КАК ВТ_НачисленияДоходы

СГРУППИРОВАТЬ ПО
	ВТ_НачисленияДоходы.ДокументОснование,
	ВТ_НачисленияДоходы.Организация,
	ВТ_НачисленияДоходы.ФизическоеЛицо,
	ВТ_НачисленияДоходы.Начисление,
	ВТ_НачисленияДоходы.Регистратор,
	ВТ_НачисленияДоходы.МесяцНалоговогоПериода,
	ВТ_НачисленияДоходы.МесяцНачисления,
	ВТ_НачисленияДоходы.КатегорияДохода,
	ВТ_НачисленияДоходы.КодВычета,
	ВТ_НачисленияДоходы.КодДохода,
	ВТ_НачисленияДоходы.РегистрацияВНалоговомОргане,
	ВТ_НачисленияДоходы.Сотрудник
;

////////////////////////////////////////////////////////////////////////////////
ВЫБРАТЬ
	ВТ_НачисленияДоходыСводно.МесяцНачисления КАК МесяцНачисления,
	ВТ_НачисленияДоходыСводно.Организация КАК Организация,
	ВТ_НачисленияДоходыСводно.ФизическоеЛицо КАК ФизическоеЛицо,
	ВТ_НачисленияДоходыСводно.Сотрудник КАК Сотрудник,
	ВТ_НачисленияДоходыСводно.ДокументОснование КАК ДокументОснование,
	ВТ_НачисленияДоходыСводно.Начисление КАК Начисление,
	ВТ_НачисленияДоходыСводно.Начислено КАК Начислено,
	ВТ_НачисленияДоходыСводно.Регистратор КАК Регистратор,
	ВТ_НачисленияДоходыСводно.МесяцНалоговогоПериода КАК МесяцНалоговогоПериода,
	НАЧАЛОПЕРИОДА(ВТ_НачисленияДоходыСводно.МесяцНалоговогоПериода, КВАРТАЛ) КАК КварталНалоговогоПериода,
	НАЧАЛОПЕРИОДА(ВТ_НачисленияДоходыСводно.МесяцНалоговогоПериода, ГОД) КАК НалоговыйПериод,
	ВТ_НачисленияДоходыСводно.Доход КАК Доход,
	ВТ_НачисленияДоходыСводно.Вычет КАК Вычет,
	ВТ_НачисленияДоходыСводно.ОблагаетсяНДФЛ КАК ОблагаетсяНДФЛ,
	ВТ_НачисленияДоходыСводно.КодДохода КАК КодДохода,
	ВТ_НачисленияДоходыСводно.КодВычета КАК КодВычета,
	ВТ_НачисленияДоходыСводно.КатегорияДохода КАК КатегорияДохода,
	ВТ_НачисленияДоходыСводно.РегистрацияВНалоговомОргане КАК ИФНС
ИЗ
	ВТ_НачисленияДоходыСводно КАК ВТ_НачисленияДоходыСводно

УПОРЯДОЧИТЬ ПО
	МесяцНачисления,
	Организация,
	ФизическоеЛицо,
	ДокументОснование,
	Начисление`

### Скриншоты

![image](https://github.com/1C-Company/1c-edt-issues/assets/34237452/33d923ad-9384-4b63-a8ea-2f7b5caffbf9)
![image](https://github.com/1C-Company/1c-edt-issues/assets/34237452/5c0bb861-d10a-4104-a171-f4744b8a9d48)
![image](https://github.com/1C-Company/1c-edt-issues/assets/34237452/86698aa5-22c0-43e7-8a18-964e1c00d505)

### Ожидаемое поведение

Ошибка не должна отображаться.

### Лог рабочей области

[trace.log](https://github.com/1C-Company/1c-edt-issues/files/11472778/trace.log)
[1.log](https://github.com/1C-Company/1c-edt-issues/files/11472784/1.log)

### Версия 1С:EDT

Ruby 2022.2.5

### Операционная система

Windows

**Comment by adminimusRU** [comment]
Странный момент: если то же самое проблемное выражение 
```bsl
(ВЫБОР
КОГДА ТИПЗНАЧЕНИЯ(ВТ_НачисленияЗаПериод.Начисление) = ТИП(ПланВидовРасчета.Начисления)
ТОГДА ВТ_НачисленияЗаПериод.МесяцНачисления = НАЧАЛОПЕРИОДА(СведенияОДоходахНДФЛ.Период, МЕСЯЦ)
ИНАЧЕ ИСТИНА
КОНЕЦ)
```
использовать в полях выборки, то ошибки нет, а в условиях связи ругается на тип.

**Comment by MaksimDzyuba** [comment]
решено войдет в 2023.1 в ближайший выпуск
