### ISSUE TITLE
При переключении веток с одной ИБ изменения не попадают в ИБ

### ISSUE THREAD

**Issue by KovAlexey** [1C-Company/1c-edt-issues#1005]
### Описание ошибки

При переключении с ветки на ветку попадают не все изменения в ИБ.

### Как воспроизвести

1. Синхронизируем конфигурацию
![изображение](https://github.com/1C-Company/1c-edt-issues/assets/16429518/0a4ca492-7b17-4492-8134-d6adae0d8002)

2. Создаем ветку с использованием той же ИБ
![изображение](https://github.com/1C-Company/1c-edt-issues/assets/16429518/cb1ad72e-2b06-43b9-8012-78482e3c753b)
3. Добавляем какие либо изменения для модуля менеджера
4. Обновляем ИБ
![изображение](https://github.com/1C-Company/1c-edt-issues/assets/16429518/d186c3a1-034d-4b62-a580-cd7fa340b782)
5. Переключаемся на родительскую ветку
![изображение](https://github.com/1C-Company/1c-edt-issues/assets/16429518/1cc3b524-0f84-4d78-87e4-5cc9c3d45400)
6. Обновляем ИБ
7. Рассинхрон
![изображение](https://github.com/1C-Company/1c-edt-issues/assets/16429518/587fa664-4c9f-4c32-99d8-770db79fd27b)

### Ожидаемое поведение

Измененные объекты должны дискретно загрузиться при переключении веток

### Лог рабочей области

None

### Версия 1С:EDT

2022.2.5

### Операционная система

Windows

### Установленные плагины

1C:Code style V8, 1C:SSL-support

**Comment by KovAlexey** [comment]
Если я переключаю ветку через "Переключить на", то поведение совершенно не меняется

**Comment by mrshadow300373** [comment]
В таких случаях, после переключения помогает 100% жесткий сброс на ветку где были (с которой переключились) и тут же жесткий сброс обратно - куда переключились. Главное чтобы конечно "разбег" между ветками был не очень большой иначе будет долго.

**Comment by KovAlexey** [comment]
>В таких случаях, после переключения помогает 100% жесткий сброс на ветку где были (с которой переключились) и тут же жесткий сброс обратно - куда переключились. Главное чтобы конечно "разбег" между ветками был не очень большой иначе будет долго.

Спасибо, полезно.

**Comment by Erik773** [comment]
Здравствуйте @KovAlexey 
Могли бы вы, пожалуйста, прикрепить логи рабочей области EDT и настройки пользователя git и настройки репозитория (Окно -> Параметры -> Групповая разработка -> Git -> Конфигурация -> Настройки пользователя, Настройки репозитория).

**Comment by KovAlexey** [comment]
@Erik773, конечно могу
Логи:
[logs_test_repo_releases.zip](https://github.com/1C-Company/1c-edt-issues/files/11561969/logs_test_repo_releases.zip)
Настройки
![изображение](https://github.com/1C-Company/1c-edt-issues/assets/16429518/84ccbe33-9d54-4026-be85-79a146ea98eb)
![изображение](https://github.com/1C-Company/1c-edt-issues/assets/16429518/f49e191b-061c-4544-af5c-13cedfdb732e)
![изображение](https://github.com/1C-Company/1c-edt-issues/assets/16429518/1a22b1c8-24b2-44f2-a34a-df0e540d7c1e)

**Comment by nikolay-martynov** [comment]
Здравствуйте. К сожалению, не удалось воспроизвести указанную вами проблему ни через контекстное меню навигатора, ни через перспективу Git.

https://github.com/1C-Company/1c-edt-issues/assets/13433348/bdbb28d6-5e0b-4a40-9070-095562302924

В приложенных вами файлах журнала видно, как конфигурация была загружена в информационную базу, а потом информационная база еще обновлялась. Далее вы похоже перезапустили EDT, но из-за все еще ранее открытого конфигуратора, его агент не смог установить блокировку над информационной базой, а среда синхронизироваться с ней. Если вы выполняете какие-то дополнительные шаги, являющиеся условием появление проблемы, то пожалуйста укажите их. Полный пошаговый сценарий мог бы помочь воспроизведению вашей проблемы.

**Comment by nikolay-martynov** [comment]
Здравствуйте. Если вам удастся установить точный порядок действий для стабильного воспроизведения указанного вами поведения, то я буду благодарен, если вы снова откроете данную задачу и укажете какие именно шаги следует выполнить.

**Comment by KovAlexey** [comment]
@tretyakevich я не знаю, что еще описать.
Выше описан полный повторяемый сценарий. Мне сюда больше нечего добавить

**Comment by nikolay-martynov** [comment]
Здравствуйте, Алексей. Если вы знаете как воспроизводить эту проблему, то пожалуйста помогите нам понять каковы условия и шаги. Если возможно, снимите пожалуйста видео того, что надо сделать, приложите его и переоткройте проблему.

**Comment by nikolay-martynov** [comment]
Здравствуйте, Алексей. Я не могу воспроизвести описанную вами ситуацию. После переключения на исходную ветку и обновления информационной базы там неизменно оказывается содержимое из исходной ветки. В описанном вами сценарии скорее всего пропущены какие-то шаги. Например, при переключении веток среда спрашивает, что следует сделать с изменениями. Возможно, описываемая вами ситуация зависит от того, что вы выбирали?

**Comment by KovAlexey** [comment]
Что-то обнаружилось, учитывая что задачу открыли?
Я сейчас в отпуске, поэтому пока не могу предоставить больше информации.

**Comment by nikolay-martynov** [comment]
Здравствуйте, Алексей. Да, кажется экспериментальным путём удалось найти как воспроизвести, но пока непонятна закономерность, когда проблема проявляется. Есть предположение, что дело в том, откуда запускать команды.

**Comment by nikolay-martynov** [comment]
Здравствуйте, Алексей. Проблема в том, что при восстановлении снимков вторичных данных важно не то, какие файлы изменились, а содержимое самого снимка, который хранит всё состояние, включая статус синхронизации с информационной базой. В этом весь смысл снимков. К сожалению, отключение слежения за файлами происходило и в тех случаях, когда снимок не восстанавливался. В зависимости от настроек среды и того, что пользователь отвечал ранее на запросы о снимках, какое при этом выставлял значение переключателя, как называются старая и новая ветка, каково состояние репозитория, могло происходить извлечение ветки при отключенном слежении за изменениями файлов, но при этом без восстановления снимка вторичных данных. В новой версии слежение за изменениями во время извлечения ветки отключается только для случая, когда снимок будет восстановлен, а в остальных случаях слежение за изменениями файлов остаётся включённым.
До выхода обновления вы можете обойти проблему следующими способами:
- При создании новой ветки используйте предлагаемый системой по умолчанию вариант с созданием новой информационной базы.
- Включите и используйте снимки вторичных данных, убедившись, что имена веток подпадают под шаблоны заданные в настройках. Обратите при этом внимание, что снимки могу быть отключены на уровне проекта. С подробностями можно ознакомиться по следующим ссылкам:
  - https://its.1c.ru/db/edtdoc/content/10599/hdoc
  - https://its.1c.ru/db/edtdoc/content/10598/hdoc
  - https://its.1c.ru/db/edtdoc/content/10603/hdoc

**Comment by KovAlexey** [comment]
То есть я правильно понял?
Т.к. я не использую снимки, едт при переключении должно было отслеживать файлы. Но из-за ошибки этого не делает?

**Comment by nikolay-martynov** [comment]
Здравствуйте, Алексей. Слежение отключается временно до тех пор, пока не закончится извлечение новой ветки. На самом деле там масса возможных вариантов того, что может происходить. Например, иногда слежение включается обратно как результат автоматического повторного открытия проекта либо с полным, либо с частичным его импортом. И наоборот, иногда отключение слежения не срабатывало, что могло приводить к большой длительности пересчёта вторичных данных после восстановления снимка. Теперь, если снимки не задействованы (что по умолчанию становится окончательно ясно только после того как пользователь ответит на вопрос о подтверждении создания/восстановления снимка уже после ввода параметров в помощнике создания новой ветки), то не производится даже попытка отключить слежение. Таким образом, если при извлечении новой ветки файл изменяется, то получается такой же эффект, как если бы вы руками отредактировали файл в редакторе - теперь срабатывает тот же самый механизм.
