### ISSUE TITLE
[1CEDT] Ошибка редактора запроса в конструкторе СКД (не корректное формирование текста запроса)

### ISSUE THREAD

**Issue by EChudnovsky** [1C-Company/1c-edt-issues#1007]
### Описание ошибки

При вызове редактора запроса из конструктора СКД, возникает поведение 
при котором невозможно сохранить измененный текст запроса (см. видео).

При этом в логах формируется сообщение о не корректном тексте запроса.
com._1c.g5.v8.dt.qw.ui.utils.QuerySchemaBuilder$QuerySchemaBuilderException: {(18, 1)}: Синтаксическая ошибка. Недопустимая лексема "'ВЫБРАТЬПрограммыМедСтрахованияСотрудников'" в данном контексте

Product name: 1C:Enterprise Development Tools
Product version: 1.27.5.10
Java home: C:\Program Files\BellSoft\LibericaJDK-11-Full
Java vm name: OpenJDK 64-Bit Server VM
Java vm info: mixed mode
Java version: 11.0.12
Java vendor: BellSoft
OS: win32
Total mem: 9 567
Free mem: 7 549
Cores: 16
***********************************
*	Файлы, приложенные к задаче, отправлены разработчикам. Ссылка в задаче не отображается./t*
***********************************

### Как воспроизвести

https://github.com/1C-Company/1c-edt-issues/assets/5530435/df41997e-174d-4f48-a5a8-c280f7917784

### Лог рабочей области

[log.zip](https://github.com/1C-Company/1c-edt-issues/files/11561676/log.zip)

### Проблемный отчет для типовой конфигурации ЗУП КОРП 3

[ФХС_ЖурналПрикрепленийИОткрепленийДМСКСотрудникам.zip](https://github.com/1C-Company/1c-edt-issues/files/11561691/_.zip)

**Comment by EChudnovsky** [comment]
P.S. Ошибка возникает если в конструкторе запроса на закладке "Объединения/Псевдонимы" выполнить перемещение ПЕРВОГО поля.

**Comment by MaksimDzyuba** [comment]
Удалось исправить 
![bandicam 2023-06-27 18-38-55-296](https://github.com/1C-Company/1c-edt-issues/assets/77277424/d7133eef-96c3-49b9-b180-56742f3a739b)

**Comment by MaksimDzyuba** [comment]
Решено, войдет в ближайший выпуск 2023.1
