### ISSUE TITLE
EDT считает ошибкой то что ошибкой не является

### ISSUE THREAD

**Issue by ESiluhin** [1C-Company/1c-edt-issues#101]
### Описание ошибки

Проблема с проверкой запросов в динамическом списке:
1. Запрос в динамическом списке, помещаем подзапрос в таблицу и называем ее "ВСЕ", EDT считает что это недопустимое название таблицы, конфигуратор не видит проблем и спокойно отрабатывает и открывает конфигуратор. (Если не переименовать название "ВСЕ", тогда EDT не видит реквизиты в форме.
2. В секции "ВЫБОР КОГДА" ругается на команду "ВЫРАЗИТЬ" (Пишет "Ошибочный параметр"), при том ниже в запросе команда ВЫРАЗИТЬ не считается ошибкой. 

Так же EDT ругается на методы глобального контекста например на "Предупреждение()" "ВвестиЧисло()" пытался отключить проверку пробовал подавление проверок, пробовал отключить проверку через Свойства - V8 - Валидация ничего не помогает.

### Как воспроизвести

Запрос:
ВЫБРАТЬ
	ВСЕ.Период КАК Период,
	ВСЕ.Регистратор КАК Регистратор,
	ВСЕ.Номенклатура КАК Номенклатура,
	ВСЕ.Склад КАК Склад,
	ВСЕ.ВНаличии КАК ВНаличии,
	ВСЕ.Характеристика КАК Характеристика,
	ВСЕ.ВРезервеСоСклада КАК ВРезервеСоСклада,
	ВСЕ.НомерСерии КАК НомерСерии,
	ВСЕ.Отправитель КАК Отправитель,
	СвободныеОстаткиОстатки.ВНаличииОстаток КАК Тек_остаток,
	ВСЕ.НомерВходящего КАК НомерВходящего,
	ВСЕ.Характеристика.ВИТТА_Маркированный КАК Маркированный,
	ВСЕ.Характеристика.бит_ГоденДо КАК Характеристикабит_ГоденДо
ИЗ
	(ВЫБРАТЬ
		СвободныеОстатки.Период КАК Период,
		СвободныеОстатки.Регистратор КАК Регистратор,
		ВЫБОР
			КОГДА ВЫРАЗИТЬ(СвободныеОстатки.Регистратор КАК Документ.ПеремещениеТоваров) ССЫЛКА Документ.ПеремещениеТоваров
				ТОГДА ВЫРАЗИТЬ(СвободныеОстатки.Регистратор КАК Документ.ПеремещениеТоваров).СкладОтправитель
			КОГДА ВЫРАЗИТЬ(СвободныеОстатки.Регистратор КАК Документ.ПоступлениеТоваровУслуг) ССЫЛКА Документ.ПоступлениеТоваровУслуг
				ТОГДА ВЫРАЗИТЬ(СвободныеОстатки.Регистратор КАК Документ.ПоступлениеТоваровУслуг).Контрагент
			КОГДА ВЫРАЗИТЬ(СвободныеОстатки.Регистратор КАК Документ.ВводОстатков) ССЫЛКА Документ.ВводОстатков
				ТОГДА ВЫРАЗИТЬ(СвободныеОстатки.Регистратор КАК Документ.ВводОстатков).Контрагент
		КОНЕЦ КАК Отправитель,
		ЕСТЬNULL(ВЫРАЗИТЬ(СвободныеОстатки.Регистратор КАК Документ.ПоступлениеТоваровУслуг).НомерВходящегоДокумента, "") КАК НомерВходящего,
		СвободныеОстатки.Номенклатура КАК Номенклатура,
		СвободныеОстатки.Склад КАК Склад,
		СвободныеОстатки.ВНаличии КАК ВНаличии,
		СвободныеОстатки.Характеристика КАК Характеристика,
		СвободныеОстатки.ВРезервеСоСклада КАК ВРезервеСоСклада,
		СвободныеОстатки.Характеристика.бит_НомерСерии КАК НомерСерии
	ИЗ
		РегистрНакопления.СвободныеОстатки КАК СвободныеОстатки
	ГДЕ
		СвободныеОстатки.ВидДвижения = ЗНАЧЕНИЕ(ВидДвиженияНакопления.Приход)
		И СвободныеОстатки.Номенклатура = &Номенклатура
		И СвободныеОстатки.Склад = &Склад) КАК ВСЕ
		ЛЕВОЕ СОЕДИНЕНИЕ РегистрНакопления.СвободныеОстатки.Остатки(
				,
				Склад = &Склад
					И Номенклатура = &Номенклатура) КАК СвободныеОстаткиОстатки
		ПО ВСЕ.Склад = СвободныеОстаткиОстатки.Склад
			И ВСЕ.Номенклатура = СвободныеОстаткиОстатки.Номенклатура
			И ВСЕ.Характеристика = СвободныеОстаткиОстатки.Характеристика

### Скриншоты

![Проблема запроса 1](https://user-images.githubusercontent.com/35148364/141757715-be0f49ce-8d8c-46c4-99a7-14b9bcd7fc80.jpg)
![Проблема запроса 2](https://user-images.githubusercontent.com/35148364/141757720-c8485fcb-27cd-468a-a043-09ac9edf8b1f.jpg)
![Проблема запроса 4](https://user-images.githubusercontent.com/35148364/141758228-6e9f9158-ce9c-442
![Проблема запроса 5](https://user-images.githubusercontent.com/35148364/141758258-a8c74a49-79e9-4cff-8a0a-52f0c0f9d30b.jpg)
2-b72c-e2ed65dd7adb.jpg)
![Проблема инспекци кода](https://user-images.githubusercontent.com/35148364/141759296-bb5dd8e3-ecee-4c8c-9d53-4085ce46d799.jpg)

### Ожидаемое поведение

Не должно быть ошибки по идее. (В конфигураторе все работает)

### Лог рабочей области

[log.txt](https://github.com/1C-Company/1c-edt-issues/files/7537508/log.txt)

### Версия 1С:EDT

2021.2.9

### Операционаня система

Windows

**Comment by MaksimDzyuba** [comment]
Здравствуйте, ошибку исправил, должна войти в 2022.2 (на предупреждения просьба не смотреть, нет всех Ваших объектов метаданных)

![image](https://user-images.githubusercontent.com/77277424/192292714-bed4174d-b5a3-421e-8f96-dc2bb89a4609.png)

**Comment by tretyakevich** [comment]
Исправлена в 2022.2
