### ISSUE TITLE
Не работает авторизация портала в стартере 1С

### ISSUE THREAD

**Issue by EZabelin** [1C-Company/1c-edt-issues#1012]
### Описание ошибки

При нажатии в стартере команды "Войти с помощью Портала 1С:ИТС" крутится колесо, браузер не открывается, см. скрин.

Из EDT авторизация работает. При выполнении команды "Войти через Портал 1С: ИТС", открывается браузер, где после ввода логина/пароля авторизация завершается.

### Как воспроизвести

1. Открыть стартер
2. Нажать команду "Войти с помощью Портала 1С:ИТС" 

### Скриншоты

![image](https://github.com/1C-Company/1c-edt-issues/assets/19504873/cfda9f7a-6e81-49fc-980b-5784a1e2ff03)

### Ожидаемое поведение

Авторизация работает корректно

### Лог рабочей области

Лог стартера: [1cedtstart.log](https://github.com/1C-Company/1c-edt-issues/files/11626221/1cedtstart.log)

### Версия 1С:EDT

Ruby 2022.2.5

### Операционная система

Windows

### Установленные плагины

Нет плагинов

**Comment by pchurbanov** [comment]
Судя по логу - проблема в проверке сертификатов
Почему-то у вас на локальной машине проверка наших сертификатов проходит неуспешно - вероятно какая-то проблема в настройках сети (локальной или корпоративной)

Можно либо разобраться с этими настройкам либо запретить проверку сертификатов прописав в ini-файле Стартера:
```
-De1c.dt.net.tlsSkipVerify
```
Но это небезопасный способ

**Comment by LesN1ck** [comment]
> Судя по логу - проблема в проверке сертификатов Почему-то у вас на локальной машине проверка наших сертификатов проходит неуспешно - вероятно какая-то проблема в настройках сети (локальной или корпоративной)
> 
> Можно либо разобраться с этими настройкам либо запретить проверку сертификатов прописав в ini-файле Стартера:
> 
> ```
> -De1c.dt.net.tlsSkipVerify
> ```
> 
> Но это небезопасный способ

У меня наблюдается похожая проблема в корпоративной сети. Из дома при этом подключается корректно. Есть ли правильный способ решения данной проблемы?

**Comment by pchurbanov** [comment]
> У меня наблюдается похожая проблема в корпоративной сети. Из дома при этом подключается корректно. Есть ли правильный способ решения данной проблемы?

Способ решения - разбираться с настройками сети - на вашем компьютере или на маршрутизаторах на работе
Для этого лучшего понимания проблемы можно использовать адрес https://services.1c.dev/setups/v1 - можно посмотреть сертификаты, оценить насколько ваша система (или системы компьютеров в сети) адекватно воспринимают валидность сертификатов

**Comment by EZabelin** [comment]
Сертификаты проверил, валидные. Помогло отключение проверки в ini-файле.
