### ISSUE TITLE
ПутьКДанным подвала - доступны несуществующие реквизиты

### ISSUE THREAD

**Issue by IgorPchelov** [1C-Company/1c-edt-issues#1013]
### Описание ошибки

Если в табличной части включено отображение подвала, то при интерактивной попытке указать "ПутьКДаннымПодвала" (например для реквизита "количество" вывести итоги) открывается окно, где доступно 2 реквизита с итогами "ИтогКоличество":
1. Объект.ТабличнаяЧасть.ИтогКоличество
2. Элементы.ТабличнаяЧасть.ТекущиеДанные.ИтогКоличество
Если по ошибке выбрать путь из п.2, то при сборке конфигурации выдается исключительная ошибка о неправильном пути. Если работать, через конфигуратор, то путь из п.2 не будет доступен (так и должно быть), можно будет выбрать только путь из п.1

### Как воспроизвести

1. На форме объекта, где есть табличная часть включите для нее отображение подвала.
2. Для количественного реквизита (например "сумма") из табличной части нажмите кнопку выбора "ПутьКДаннымПодвала"
4. В появившемся окне появится возможность выбора пути:
- Объект.ИмяТабличнаойЧасти.ИтогСумма
- Элементы.ИмяТабличнойЧасти.ТекущиеДанные.ИтогСумма
6. Укажите в качестве пути "Элементы.ИмяТабличнойЧасти.ТекущиеДанные.ИтогСумма"
7. Сохраните проект, нажмите "Обновить конфигурацию".
8. В процессе сборки появится окно с исключительной ошибкой

### Скриншоты

В EDT в элементах доступен выбор итога по "ИтогКоличество" И "КоличествоСтрок"
![ВыборПути_ИтогиЭлементы](https://github.com/1C-Company/1c-edt-issues/assets/110457908/982b742f-f1f3-475e-ad8d-445439548605)
в Конфигураторе недоступен выбор итога в элементах по "ИтогКоличество" (только из данных "Объект")
![ВыборПутиИтогаВКонфигураторе](https://github.com/1C-Company/1c-edt-issues/assets/110457908/9f0b9030-707e-4c85-be52-01a4a9cae4c2)
Исключительная ошибка при обновлении конфигурации
![СкринОшибки](https://github.com/1C-Company/1c-edt-issues/assets/110457908/a0751419-d7ad-43ae-9261-db2f40e57ea8)

### Ожидаемое поведение

В списке реквизитов при выборе "ПутьКДаннымПодвала" итоговые реквизиты должны быть доступны только из "Объект". В этом списке надо убрать пути к итогам из "элементы"

### Лог рабочей области

Возможность предоставить Лог отсутствует.

### Версия 1С:EDT

Ruby 2021.3.4

### Операционная система

Windows

### Установленные плагины

1C:Code style V8

**Comment by vadimeg** [comment]
Исправлено в 2023.2
