### ISSUE TITLE
Панель сравнения конфигураций показывает лишнее свойство "Режим совместимости расширения конфигурации"

### ISSUE THREAD

**Issue by tormozit** [1C-Company/1c-edt-issues#1015]
### Описание ошибки

Повторяется эта проблема у меня каждый раз при импорте конфигурации из базы 1С. База 1С файловая на платформе 8.3.22.1851 с режимом совместимости 8.3.17. А в эту базу я объединением загружал в конфигураторе изменения из CF, сохраненного на 8.3.23. Видимо какая то ошибка 8.3.23 https://www.hostedredmine.com/issues/964659

### Как воспроизвести

Есть только картинка и Configuration.xml

```
<?xml version="1.0" encoding="UTF-8"?>
<MetaDataObject ... xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" version="2.15">
	<Configuration uuid="ca506c2f-3cf6-425d-bb4a-2f2e5f9440e9">
		<Properties>
			<Name>УправлениеСкладом</Name>
			<ConfigurationExtensionCompatibilityMode>Version8_3_22</ConfigurationExtensionCompatibilityMode>
```

### Скриншоты

![изображение](https://github.com/1C-Company/1c-edt-issues/assets/11896251/7a91fffb-3c8e-4c1d-9aa1-4d65d63844ff)

### Ожидаемое поведение

отсутствие этого свойства

### Лог рабочей области

.

### Версия 1С:EDT

Ruby 2022.2.5

### Операционная система

Windows

### Установленные плагины

Нет плагинов

**Comment by Erik773** [comment]
Здравствуйте.
Проблема известная, как вы верно предположили, на стороне платформы. 
На стороне EDT, к сожалению, ничего сделать не получится.
