### ISSUE TITLE
Edt перестал видеть на клиенте функции модулей повторного использования с вызовом сервера. Ошибочно диагностирует ошибку Свойство (метод) объекта не обнаружено [Тонкий клиент, Толстый клиент (управляемое приложение), Web-клиент].

### ISSUE THREAD

**Issue by DmitryShvaika** [1C-Company/1c-edt-issues#1017]
### Описание ошибки

Edt перестал видеть на клиенте функции модулей повторного использования с вызовом сервера. 
Ошибочно диагностирует ошибку Свойство (метод) объекта не обнаружено [Тонкий клиент, Толстый клиент (управляемое приложение), Web-клиент].

![image](https://github.com/1C-Company/1c-edt-issues/assets/54451084/a603020e-aec5-4122-a876-97a410366168)

![image](https://github.com/1C-Company/1c-edt-issues/assets/54451084/c06a3619-fbe2-4063-a1e2-f86cee71630c)

### Как воспроизвести

1. Создать функцию в модуле повторного использования с вызовом сервера
2. Вызвать ее с клиента. 
3. Наблюдать ошибку

### Ожидаемое поведение

Ошибка не должна диагностироваться

### Лог рабочей области

не требуется

### Версия 1С:EDT

Ruby 2023.1.0 Light

### Операционная система

Windows

### Дополнительная информация

архив тестового проекта
[test.zip](https://github.com/1C-Company/1c-edt-issues/files/11721723/test.zip)

**Comment by REset49** [comment]
Похоже, что дело не в повторном использовании, "обычные" модули с вызовом сервера тоже не видны.

**Comment by Daabramov** [comment]
@Erik773 добрый день, а почему установили низкий приоритет? Это довольно серьезная ошибка, половина модулей горит красным, в CI повылезали ошибки, которых не должно быть.

**Comment by Erik773** [comment]
@Daabramov, здравствуйте, высокий приоритет выставляется только задачам с лейблом "critical".
Этот лейбл выставляется проблемам, которые соответствуют [критериям критичности](https://github.com/1C-Company/1c-edt-issues/blob/main/TASK_CLASSIFICATION.md#%D0%BA%D1%80%D0%B8%D1%82%D0%B8%D1%87%D0%B5%D1%81%D0%BA%D0%B0%D1%8F-%D0%BE%D1%88%D0%B8%D0%B1%D0%BA%D0%B0) .

**Comment by MaksimDzyuba** [comment]
Здравствуйте, поправили, войдет в 2023.1
