### ISSUE TITLE
Ошибки в редакторе кода 

### ISSUE THREAD

**Issue by EChudnovsky** [1C-Company/1c-edt-issues#102]
### Описание ошибки

1. При копировании сгруппированного кода, вставка осуществляется только строк верхнего уровня
![2021-11-15_22h19_29](https://user-images.githubusercontent.com/5530435/141842346-9b7b719c-71dc-4d68-b32b-b28a99bfaa9b.png)

2. При добавлении любого метода основной конфигурации в расширение, удаляются знаки переноса для первой строки кода, что приводит к слиянию кода со строкой Функция, см. рисунок
![2021-11-15_22h25_23](https://user-images.githubusercontent.com/5530435/141842870-5e2572fe-dae1-4df6-9293-62359441f99f.png)
к

### Как воспроизвести

Воспроизвести ситуации описанные в описании ошибки и приведенные на скриншотах.

### Ожидаемое поведение

Правильное поведение редакторов, без потерь строк и форматирования кода.

### Лог рабочей области

не требуется

### Версия 1С:EDT

Ruby 2021.2.10

### Операционаня система

Windows

### Установленые плагины

Нет плагинов

### Дополнительная информация

1С:Предприятие 8.3 (8.3.19.1229)

**Comment by Kellendros007** [comment]
П.2 дублирует #135
