### ISSUE TITLE
Edt повис при сохранении модуля

### ISSUE THREAD

**Issue by DmitryShvaika** [1C-Company/1c-edt-issues#1022]
### Описание ошибки

Edt повис при сохранении модуля

### Как воспроизвести

разовая ошибка

дамп процессов прилагаю
[threaddump.zip](https://github.com/1C-Company/1c-edt-issues/files/11744685/threaddump.zip)

### Скриншоты

![image](https://github.com/1C-Company/1c-edt-issues/assets/54451084/b3149022-a791-4079-a409-c2b9d5c38bbd)

### Ожидаемое поведение

edt не должен повисать

### Лог рабочей области

[логи.zip](https://github.com/1C-Company/1c-edt-issues/files/11744677/default.zip)

### Версия 1С:EDT

Ruby 2023.1.0 Light

### Операционная система

Windows

**Comment by tretyakevich** [comment]
Исправлено в 2023.1.2
