### ISSUE TITLE
Не работает команда Конструктор движений

### ISSUE THREAD

**Issue by RedMammoth** [1C-Company/1c-edt-issues#1023]
### Описание ошибки

Не работает команда Конструктор движений
В логи падает ошибка.

### Как воспроизвести

1. Создать документ
2. Создать регистр, задать регистратор
3. Вызвать команду

### Ожидаемое поведение

-

### Лог рабочей области

[.log](https://github.com/1C-Company/1c-edt-issues/files/11750404/default.log)

### Версия 1С:EDT

2023.1

### Операционная система

Windows

### Установленные плагины

1C:Code style V8, 1C:SSL-support, 1C:Language Tool

**Comment by tretyakevich** [comment]
Исправлена в 2023.1 RC2
