### ISSUE TITLE
Создает дубль сообщения об ошибке Реквизит "Комментарий" имеет недопустимый тип

### ISSUE THREAD

**Issue by DmitryShvaika** [1C-Company/1c-edt-issues#1024]
### Описание ошибки

Создает дубль сообщения об ошибке Реквизит "Комментарий" имеет недопустимый тип
Подробнее см. видео
![Комментарий имеет не тот тип](https://github.com/1C-Company/1c-edt-issues/assets/54451084/f3f597b2-c916-460c-890a-618349e395dc)

### Как воспроизвести

1. Создать реквизит документа Комментарий неограниченной длинны
2. Заменить тип реквизита Комментарий на строку длинной 1000 символов
3. Наблюдать дублирование ошибки

### Ожидаемое поведение

Ошибка не должна дублироваться

### Лог рабочей области

не требуется

### Версия 1С:EDT

Ruby 2023.1.0

### Операционная система

Windows

**Comment by VAGoncharov** [comment]
Корректней все же переоткрыть ишуз в v8-code-style с указанием, что было бы неплохо уточнить тип проблемы (Строка неограниченной длины или мультистрока). Текущее замечание вроде как не относится к самой EDT.

**Comment by DmitryShvaika** [comment]
Перенес в code-style - спасибо
https://github.com/1C-Company/v8-code-style/issues/1345
