### ISSUE TITLE
Актуализировать доступность свойств и методов объекта ДокументDOM

### ISSUE THREAD

**Issue by stolya** [1C-Company/1c-edt-issues#1026]
### Описание ошибки

Методы УстановитьАтрибут, СоздатьЭлемент, ДобавитьДочерний, УстановитьСоответствиеПространстваИмен, ПолучитьСоответствияПространствИмен и свойства ТекстовоеСодержимое, ВерсияXML доступны в тонком клиенте. Возможно список методов и свойств больше, я описал те методы и свойства с которыми работаю в тонком клиенте.
В синтаксисе-помощнике доступность клиента не описана.
При проверке EDT выходит следующая ошибка: Property (method) of object is not defined [Thin client]

### Как воспроизвести

Написать программный код с использованием вышеописанных методов и свойств.

### Скриншоты

![image](https://github.com/1C-Company/1c-edt-issues/assets/30523530/e47cc876-3746-48e3-8ac7-c6d2f3f1318f)
![image](https://github.com/1C-Company/1c-edt-issues/assets/30523530/e6ffe1f0-1457-4a8c-9374-8981a6ec514c)

### Ожидаемое поведение

Нет ошибки и актуализированы описания синтаксиса помощника или ошибка в платформе при использовании методов и свойств на клиенте.

### Лог рабочей области

[.bak_0.log](https://github.com/1C-Company/1c-edt-issues/files/11754246/default.bak_0.log)
[.bak_1.log](https://github.com/1C-Company/1c-edt-issues/files/11754247/default.bak_1.log)
[.bak_2.log](https://github.com/1C-Company/1c-edt-issues/files/11754248/default.bak_2.log)
[.bak_3.log](https://github.com/1C-Company/1c-edt-issues/files/11754249/default.bak_3.log)
[.bak_4.log](https://github.com/1C-Company/1c-edt-issues/files/11754250/default.bak_4.log)
[.bak_5.log](https://github.com/1C-Company/1c-edt-issues/files/11754251/default.bak_5.log)
[.bak_6.log](https://github.com/1C-Company/1c-edt-issues/files/11754253/default.bak_6.log)
[.bak_7.log](https://github.com/1C-Company/1c-edt-issues/files/11754255/default.bak_7.log)
[.bak_8.log](https://github.com/1C-Company/1c-edt-issues/files/11754256/default.bak_8.log)
[.bak_9.log](https://github.com/1C-Company/1c-edt-issues/files/11754257/default.bak_9.log)
[.log](https://github.com/1C-Company/1c-edt-issues/files/11754242/default.log)
[trace.log](https://github.com/1C-Company/1c-edt-issues/files/11754243/trace.log)

### Версия 1С:EDT

Ruby 2023.1.0

### Операционная система

Windows

### Установленные плагины

1C:Code style V8, 1C:SSL-support

**Comment by MaksimDzyuba** [comment]
Здравствуйте, исправление будет в 2023.2
![image](https://github.com/1C-Company/1c-edt-issues/assets/77277424/f78e62d1-a16d-40ad-a157-4cf44d9b5a7a)
