### ISSUE TITLE
Актуализировать доступность свойств и методов объекта ЗаписьDOM

### ISSUE THREAD

**Issue by stolya** [1C-Company/1c-edt-issues#1027]
### Описание ошибки

Методы Записать доступны в тонком клиенте. Возможно список методов и свойств больше, я описал метод с которым работаю в тонком клиенте.
В синтаксисе-помощнике доступность клиента не описана.
При проверке EDT выходит следующая ошибка: Property (method) of object is not defined [Thin client]

### Как воспроизвести

Написать программный код с использованием вышеописанного метода.

### Скриншоты

![image](https://github.com/1C-Company/1c-edt-issues/assets/30523530/8431dd10-f2be-474d-b358-08dbbfe01c66)

### Ожидаемое поведение

Нет ошибки и актуализированы описания синтаксиса помощника или ошибка в платформе при использовании метода на клиенте.

### Лог рабочей области

[.bak_0.log](https://github.com/1C-Company/1c-edt-issues/files/11754503/default.bak_0.log)
[.bak_1.log](https://github.com/1C-Company/1c-edt-issues/files/11754504/default.bak_1.log)
[.bak_2.log](https://github.com/1C-Company/1c-edt-issues/files/11754505/default.bak_2.log)
[.bak_3.log](https://github.com/1C-Company/1c-edt-issues/files/11754506/default.bak_3.log)
[.bak_4.log](https://github.com/1C-Company/1c-edt-issues/files/11754507/default.bak_4.log)
[.bak_5.log](https://github.com/1C-Company/1c-edt-issues/files/11754508/default.bak_5.log)
[.bak_6.log](https://github.com/1C-Company/1c-edt-issues/files/11754509/default.bak_6.log)
[.bak_7.log](https://github.com/1C-Company/1c-edt-issues/files/11754510/default.bak_7.log)
[.bak_8.log](https://github.com/1C-Company/1c-edt-issues/files/11754511/default.bak_8.log)
[.bak_9.log](https://github.com/1C-Company/1c-edt-issues/files/11754512/default.bak_9.log)
[.log](https://github.com/1C-Company/1c-edt-issues/files/11754513/default.log)
[trace.log](https://github.com/1C-Company/1c-edt-issues/files/11754514/trace.log)

### Версия 1С:EDT

Ruby 2023.1.0

### Операционная система

Windows

### Установленные плагины

1C:Code style V8, 1C:SSL-support

### Дополнительная информация

Связанная задача https://github.com/1C-Company/1c-edt-issues/issues/1026

**Comment by MaksimDzyuba** [comment]
Здравствуйте, исправление будет в 2023.2
