### ISSUE TITLE
Нет возможности работать с формами объектов, которые вводятся на основании внешних источников данных

### ISSUE THREAD

**Issue by ovcharenko-di** [1C-Company/1c-edt-issues#1028]
### Описание ошибки

В EDT 2023.1.0 не предусмотрен вариант, когда объект может вводиться на основании таблицы внешнего источника данных.

Работа с такими объектами в EDT невозможна (формы не отрисовываются, создать новую тоже не получается).
В EDT нельзя указать, что объект вводится на основании таблицы внешнего источника данных.

### Как воспроизвести

1. Импортировать присоединенную конфигурацию в EDT 2023.1.0 (платформа 8.3.21)
2. Открыть форму элемента Справочник1
3. Убедиться, что форма открывается, но элементы в редакторе не отображаются
4. Убедиться, что в логе отображается сообщение "!MESSAGE Cannot find DbViewField with "Ref" name from source "Объект""
5. (Дополнительно) Убедиться, что EDT не позволяет указать таблицу внешнего источника данных в списке "Вводится на основании"

### Ожидаемое поведение

Минимально: выдавать предупреждение об ограничениях в EDT по работе с ВИД, но отрисовывать форму и сохранять данные о вводе на основании, чтобы экспорт в cf тоже работал корректно
Оптимально: реализовать возможность полноценной работы с ВИД в EDT, в том числе с механизмом ввода на основании

### Лог рабочей области

!ENTRY com._1c.g5.v8.dt.form 4 0 2023-06-15 12:13:26.991
!MESSAGE Cannot find DbViewField with "Ref" name from source "Объект", form uri: bm://ksu-nsi/Catalog.БРД_Скважины.Form.ФормаЭлемента.Form#/
!STACK 0
java.lang.IllegalStateException: Ошибка чтения формы! Смотри лог.
	at com._1c.g5.v8.dt.internal.form.datasourceinfo.property.MdObjectPropertyInfoProvider.createPropertyInfoByDbViewField(MdObjectPropertyInfoProvider.java:115)
	at com._1c.g5.v8.dt.internal.form.datasourceinfo.property.CatalogPropertyInfoProvider.addFieldsPropertyInfos(CatalogPropertyInfoProvider.java:53)
	at com._1c.g5.v8.dt.internal.form.datasourceinfo.property.CatalogPropertyInfoProvider.getPropertyInfo(CatalogPropertyInfoProvider.java:39)
	at com._1c.g5.v8.dt.form.model.impl.PropertyInfoProviderRegistryImpl.getPropertyInfo(PropertyInfoProviderRegistryImpl.java:135)
	at com._1c.g5.v8.dt.form.model.impl.FormPropertyInfoExtension.gatherOrdinaryPropertyInfoCollection(FormPropertyInfoExtension.java:198)

### Версия 1С:EDT

2023.1.0

### Операционная система

Windows

### Установленные плагины

Нет плагинов

### Дополнительная информация

Ссылка на dt с базой, которую надо импортировать в EDT, чтобы воспроизвести проблему
https://disk.yandex.ru/d/81R7S9Hs1SB4Ig

**Comment by ovcharenko-di** [comment]
upd. 
самый критичный момент я пропустил:

если в конфигурации есть хоть один объект, который можно вводить на основании ВИД, то такая конфигурация не загружается в ИБ и не экспортируется в XML (с той же ошибкой)

**Comment by tretyakevich** [comment]
Задача перенесена на 2023.2 по причине необходимости внесения заметных изменений во внутреннюю модель данных EDT. Критический приоритет подтвержден
