### ISSUE TITLE
Перестала добавляться кнопка на командную панель при перетаскивании команды

### ISSUE THREAD

**Issue by DmitryShvaika** [1C-Company/1c-edt-issues#1031]
### Описание ошибки

Перестала добавляться кнопка на командную панель при перетаскивании команды

![ДобавлениеКнопкиНаКоманднуюПанель](https://github.com/1C-Company/1c-edt-issues/assets/54451084/a0c1ecb6-c4c9-43e3-bf7d-2a0e59a6bebd)

### Как воспроизвести

1. Создать форму обработки
2. Создать команду
3. Перетащить на командную панель
4. Наблюдать отсутствие кнопки

Причем не отображается кнопка даже если после сохранить, закрыть и открыть форму

### Ожидаемое поведение

Кнопка должна отображаться

### Лог рабочей области

не требуется

### Версия 1С:EDT

Ruby 2023.1.0 (Light)

### Операционная система

Windows

**Comment by vadimeg** [comment]
Ну, не совсем так. Кнопка на командную панель все же добавляется и ее даже можно увидеть, если установить ширину формы недефолтную, например в палитре выставить свойство формы width=30. Да, есть проблемы с отображением некоторых элементов в предварительном просмотре, баг известный, к сожалению пока нет возможности его исправить.

**Comment by DmitryShvaika** [comment]
> Ну, не совсем так. Кнопка на командную панель все же добавляется и ее даже можно увидеть, если установить ширину формы недефолтную, например в палитре выставить свойство формы width=30. Да, есть проблемы с отображением некоторых элементов в предварительном просмотре, баг известный, к сожалению пока нет возможности его исправить.

Но в предыдущей версии все работало нормально вроде

**Comment by vadimeg** [comment]
> Но в предыдущей версии все работало нормально вроде

В подсистеме предварительного просмотра форм уже давно не было исправлений. Отрисовка зависит от многих факторов. Если кратко, то: размеры формы и контролов на ней мы получаем из конфигуратора, в конфигураторе расчет размеров происходит с учетом рендеринга системных шрифтов (в частности того шрифта, который используется на кнопке Ещё).
В EDT свой рендеринг и, к сожалению, переиспользовать конфигураторный нет технической возможности. В прошлой версии было то же самое. Пытаемся решить эту проблему другим способом, но там путь очень долгий, пока прогнозов нет никаких (
Но это только предварительный просмотр EDT. В рантайме команда, добавленная на форму, будет отображаться.

**Comment by DmitryShvaika** [comment]
> > Но в предыдущей версии все работало нормально вроде
> 
> В подсистеме предварительного просмотра форм уже давно не было исправлений. Отрисовка зависит от многих факторов. Если кратко, то: размеры формы и контролов на ней мы получаем из конфигуратора, в конфигураторе расчет размеров происходит с учетом рендеринга системных шрифтов (в частности того шрифта, который используется на кнопке Ещё). В EDT свой рендеринг и, к сожалению, переиспользовать конфигураторный нет технической возможности. В прошлой версии было то же самое. Пытаемся решить эту проблему другим способом, но там путь очень долгий, пока прогнозов нет никаких ( Но это только предварительный просмотр EDT. В рантайме команда, добавленная на форму, будет отображаться.

закрыть задачу или оставить?

**Comment by vadimeg** [comment]
Можно закрыть, у нас есть открытая внутренняя
