### ISSUE TITLE
Система расчета типов сходит с ума / ломаются проверки при работе с модулями

### ISSUE THREAD

**Issue by jsteugene** [1C-Company/1c-edt-issues#1033]
### Описание ошибки

После перехода на 2023.1.0 в модулях с аннотацией //@strict-types в определенных ситуациях возникают отказы при расчете типов из-за чего валидатор красит практически все переменные в красный цвет с ошибками вида:
- Вызываемый тип выражения не пересекается с типом: "<Имя типа>" для параметра "<Имя параметра>"
- Переменная "<Имя переменной>" не имеет типа

Ошибки в модуле можно устранить, если подавить любую из возбудившихся проверок (например через добавление //@skip-check property-return-type), а затем убрать подавление. После этого модуль вновь чист, а система расчета типов корректно определяет переменные.

Очистка проекта проблему не устраняет.

### Как воспроизвести

Ошибка на моей конфигурации стабильно воспроизводится:
- есть модули, которые сразу при открытии выкрашиваются в красный
- есть модули, где нужно совершить какое-то действие (например скопировать процедуру и вставить её в этот же модуль), после чего модуль выкрашивается в красный.

При необходимости могу дать конфигурацию для воспроизведения.

### Скриншоты

![image](https://github.com/1C-Company/1c-edt-issues/assets/66112045/a71f0eed-4088-420c-b6e0-28944523aacf)

### Ожидаемое поведение

Чтобы система расчета типов не ломалась и не появлялись ложные ошибки в модулях.

### Лог рабочей области

[logs.zip](https://github.com/1C-Company/1c-edt-issues/files/11801464/logs.zip)

### Версия 1С:EDT

Ruby 2023.1.0

### Операционная система

Windows

### Установленные плагины

1C:Code style V8, 1C:SSL-support, 1C:Language Tool, Disable Editing plugin for 1C:EDT, DevStyle

**Comment by jsteugene** [comment]
Ещё один вариант проявления ошибки. Работал с модулем объекта бизнес-процесса и он был "нормальным". Затем добавлял реквизиты в справочник. Затем снова вернулся в модуль для продолжения работы с ним, а он оказался "красным". В журнале ошибок много сообщений. Логи прилагаю.
[logs.zip](https://github.com/1C-Company/1c-edt-issues/files/11844844/logs.zip)
![image](https://github.com/1C-Company/1c-edt-issues/assets/66112045/f772c4c5-500a-40d5-bd6c-474f832036f3)

**Comment by tretyakevich** [comment]
Добрый день, а какая версия LT установлена?

**Comment by tretyakevich** [comment]
Добрый день. Для повторения проблемы крайне желательно получить исходники проекта, на котором это воспроизвелось.
Повторение на синтетических примерах затруднено наличием LT, который расширяет функциональность работы с типами.

**Comment by jsteugene** [comment]
Отправил исходники в личку в телеграм.

**Comment by potoyalo** [comment]
> Добрый день. Для повторения проблемы крайне желательно получить исходники проекта, на котором это воспроизвелось.

У меня похожая проблема частенько воспроизводится при работе с расширением `yaxunit` ([исходники](https://github.com/bia-technologies/yaxunit/issues)).

Возникает внезапно, почти весь код красный с ошибкой "в модуле не найден вызываемый метод" (не помню точную формулировку). При этом контекстная подсказка работает, переход по F3 работает. Контекст слетает именно у строгой типизации.

Лечится либо само, либо после перезапуска EDT, либо по кнопке `Проверить` контекстного меню, либо редактированием подчеркнутого красным участка (например, поставить пробел в середине имени метода, затем удалить). Ещё помогает выделить кусок кода (или метод, или весь модуль), скопировать и вставить на это же место. Короче говоря, каким-то образом вызвать перерасчет типов для псевдоошибочного кода.

**Comment by tretyakevich** [comment]
Исправлено в 2023.1.2

**Comment by tretyakevich** [comment]
Ошибочный комментарий оказался пророческим, к сожалению. Дополнительная обнаруженная проблема исправлена в 2023.1.2

**Comment by RomanAgaltsev** [comment]
Проблема осталась и на 2023.1.2.

В модуле есть подавления ошибок, весь модуль красный-красный.
![image](https://github.com/1C-Company/1c-edt-issues/assets/102655647/f832686d-7a87-46aa-a036-20f7828c69e1)

Если начать убирать подавления, краснота уходит. При чем, если нажать Ctrl+Z, вернув подавление, то краснота не возвращается.
![image](https://github.com/1C-Company/1c-edt-issues/assets/102655647/6a7f2753-78e1-4013-a262-8d42e5bf9289)

Если закрыть модуль и заново открыть - краснота на месте...
