### ISSUE TITLE
Зависание EDT при редактировании модуля (проверка Xтекст)

### ISSUE THREAD

**Issue by jsteugene** [1C-Company/1c-edt-issues#1036]
### Описание ошибки

При редактировании общего модуля внезапно отключилась контекстная подсказка (автокомплит) и проверки кода "на лету", в прогресс-баре EDT в этот момент крутилась "проверка Xтекст". Где-то в течение минуты я ждал, что EDT вернётся в норму, но этого не произошло, и я нажал Ctrl+S для сохранения написанного кода. Через какое-то время после этого EDT завис намертво.

### Как воспроизвести

Проблема нерегулярная, сценария воспроизведения нет.

### Скриншоты

![image](https://github.com/1C-Company/1c-edt-issues/assets/66112045/11de0668-0a24-4dbf-ad76-9672dd018e3b)

### Ожидаемое поведение

EDT не зависает при редактировании текстов модулей.

### Лог рабочей области

[logs.zip](https://github.com/1C-Company/1c-edt-issues/files/11820047/logs.zip)
[threaddump.zip](https://github.com/1C-Company/1c-edt-issues/files/11820048/threaddump.zip)

### Версия 1С:EDT

Ruby 2023.1.0

### Операционная система

Windows

### Установленные плагины

1C:Code style V8, 1C:SSL-support, 1C:Language Tool

### Дополнительная информация

Зависанию предшествовали многочисленные поломки системы расчета типов (одна из ошибок зарегистрирована тут https://github.com/1C-Company/1c-edt-issues/issues/1033).
Проблема очень похожа на это https://github.com/1C-Company/1c-edt-issues/issues/1022, но не уверен, что это та же проблема, поэтому завел отдельный баг.

Дамп памяти при необходимости могу предоставить.

**Comment by karneichik** [comment]
Так же столкнулся с такой проблемой. Как временное решение пробуйте запускать проект не через 1с Start, а через EDT. У меня пару дней никаких зависаний не было, потом стало зависать интерфейс. 
Зависает при следующих действиях:
Если перейти в закладку Синтаксис-помощник
Настройки - общие - веб-браузер
Настройки - Справка
Наведение курсора на переменную.
При этом если переменная помечена как warning или error - текст ошибки отображается в контекстной подсказке
При отладке показывает значение переменной, но только из метода в котором находится отладка

**Comment by MaksimDzyuba** [comment]
Здравствуйте, исправили, войдет в 2023.1

**Comment by Jimmi910** [comment]
зависания продолжаются
Ruby 2023.1.2

**Comment by Jimmi910** [comment]
[threaddump.txt](https://github.com/1C-Company/1c-edt-issues/files/12504108/threaddump.txt)

**Comment by MaksimDzyuba** [comment]
Здравствуйте, по дампу он не завис, а долго выполняет проверку использования экспортных методов, что привело к тому, что при выполнении отображении справки он ждет окончания валидация. То есть он из зависания должен выйти, это не тоже, что было изначально в ошибке. Ведь он у Вас отвис или Вы не дождались?

**Comment by Jimmi910** [comment]
Да отвис. 
Но такое зависание после набирания текста и небольшой паузы в наборе, буквально на 1 сек. И он начинает эту проверку которая все вешает примерно от 30 до 300 секунд....
Это вроде как не нормально
