### ISSUE TITLE
[1CEDT] Ошибка отображения ролей в редакторе прав  EDT 2023.1.0.

### ISSUE THREAD

**Issue by EChudnovsky** [1C-Company/1c-edt-issues#1038]
```
В новом релизе EDT Ruby 2023.1.0 наблюдается ошибочное поведение редактора прав для объекта.
При множественном открытии редактора прав у объектов, информация перестает отображаться.
Текущее решение это "Очистка" проекта (пере открытие edt не исправляет ошибочного поведения).

Product name: 1C:Enterprise Development Tools
Product version: 1.28.0.289
Java home: C:\Program Files\BellSoft\LibericaJDK-11-Full
Java vm name: OpenJDK 64-Bit Server VM
Java vm info: mixed mode
Java version: 11.0.12
Java vendor: BellSoft
OS: win32
Total mem: 2 856
Free mem: 924
Cores: 16
***********************************
*	Файлы, приложенные к задаче, отправлены разработчикам. Ссылка в задаче не отображается./t*
***********************************
```
log:  [log.log](https://github.com/1C-Company/1c-edt-issues/files/11848097/log.log)

Скрин ошибки:

![изображение](https://github.com/1C-Company/1c-edt-issues/assets/5530435/ac906ca5-29b3-475c-a39d-d44dafcef3d5)

**Comment by Dumsik** [comment]
Прошу поднять приоритет. Ошибка очень мешает работать!

**Comment by LesN1ck** [comment]
Аналогичная проблема обнаружена на 2023.3.0 после обновления рабочей области с предыдущих версий.

**Comment by mralexjoin** [comment]
Если что, нашел обходное решение.
Если в EDT 2023.2.4 не отображается какая-то роль, то:
1. Нужно открыть ее универсальным редактором (Правой кнопкой - Open with - Универсальный текстовый редактор)
2. Найти объект с выключенным правом (value = false), но с заполненным ограничением RLS (restrictionByCondition), например:
```
<name>Insert</name>
<value>false</value>
<restrictionByCondition>
      <condition>ГДЕ Ссылка В(&amp;ПодразделенияТекущегоПользователя)</condition>
</restrictionByCondition>
```
3. Удалить секцию restrictionByCondition
4. Повторить для всех прав в файле
5. После этого можно открыть роль редактором EDT и удалить лишние объекты

**Comment by LesN1ck** [comment]
> Если в EDT 2023.2.4 не отображается какая-то роль

Так проблема в том, что не отображаются редакторы для всех ролей. Также не заполняется вкладка "Права" для других объектов конфигурации (справочники, документы и т.д.).

**Comment by mralexjoin** [comment]
@LesN1ck да, теперь тоже словил, видимо с отключенным правом был частный случай

**Comment by KovAlexey** [comment]
2023.2.4
Проблема очень сильно мешает работать

Обходится редактированием в xml нужной роли

**Comment by denisewitch** [comment]
2023.3.3
Ошибка проявляется.

> Обходится редактированием в xml нужной роли
Если конфигурация полностью на поддержке (например при разработке расширений), то после такого редактирования приходится делать полную загрузку конфигурации в базу, что не сильно быстрее очистки проекта.

**Comment by alxint** [comment]
Нашелся способ перечитать все права без очистки проекта, переименовываем папку src/Roles, заходи в ЕДТ, в дереве проекта нажимаем ПКМ Обновить, переименовываем папку обратно, снова жмем Обновить, все права переформируются и отображаются.

P.S. Если переименовывать из ЕДТ в панели Структура проекта, то все работает и без обновить.

**Comment by MaksimDzyuba** [comment]
@alxint, @denisewitch, @KovAlexey, @EChudnovsky  коллеги, а можете скинуть свежие логи у тех, у кого воспроизводится, никак не можем воспроизвести, к сожалению(

**Comment by EChudnovsky** [comment]
> @alxint, @denisewitch, @KovAlexey, @EChudnovsky коллеги, а можете скинуть, пожалуйста, свежие логи у тех, у кого воспроизводится, никак не можем воспроизвести, к сожалению(

выложу все логи, которые есть:
[log.zip](https://github.com/user-attachments/files/15912683/log.zip)

но в журнале нет временной отметки связанной с открытием редактора ролей (см. рисунок)

![изображение](https://github.com/1C-Company/1c-edt-issues/assets/5530435/09496752-21fe-44be-ab69-2d674a45a25f)

Конфигурация: Зарплата и управление персоналом КОРП, редакция 3.1 (3.1.27.208)
Версия проекта: 8.3.23
Используемая платформа: 8.3.23.2157

**Comment by kamaxmax** [comment]
Отловил аналогичную ситуацию.
Выкладываю логи:
[Logs.zip](https://github.com/user-attachments/files/16062773/Logs.zip)

Конфигурация: Зарплата и управление персоналом КОРП, редакция 3.1 (3.1.27.208)
Версия проекта: 8.3.23
Используемая платформа: 8.3.23.1997

**Comment by KovAlexey** [comment]
@MaksimDzyuba пока на 2023.3.4 не воспроизводилось

**Comment by MaksimDzyuba** [comment]
@KovAlexey здравствуйте, думаю, что это случайность, логи не особо помогли, теперь изнутри пытаемся поймать тех, у кого явно проявилось, чтобы отладиться, самому мне за 3 дня на ERP не удалось повторить пока

**Comment by Tavalik** [comment]
Присоединяюсь, работаем на 2023.3.6. Ошибка актуальна и довольно часто возникает, ничего кроме очистки проекта не помогает.

**Comment by craxycat** [comment]
Добрый день! Тоже поймал такую ошибку после некорректного закрытия EDT, версия 2023.3.6, помог способ @alxint , спасибо, не пришлось очищать весь проект.

**Comment by demony** [comment]
> .S. Если переименовывать из ЕДТ в панели Структура проекта, то все работает и без обновить.

Это спасение! :) Спасибо (это гораздо быстрее чем очистка проекта)!

Только будьте осторожны перед переименованием, убедитесь, что в индексе у вас никаких изменений нет, что бы в случае сбоя выполнить git reset. Если edt сбойнет в процессе, то он может часть ролей покосячить ( у меня так получилось - он вырезал рандомно в ролях теги привяки к объектам <object>).

**Comment by REset49** [comment]
Добрый день. Тоже словили ошибку. Не отображаются роли у объектов. Очистка проекта помогает.
Воспроизводится на 2023.3.5 и 2023.3.6.

**Comment by demony** [comment]
Очень долгое > 5 минут создание контента для редактора прав (1c КА)
(кину сюда, как общая проблема  - для поисковых движков)
![image](https://github.com/user-attachments/assets/cc1cca74-c4d4-4a3b-9cbb-f45ed3acc74c)

**Comment by JasonT57** [comment]
Версия 2024.1.3
Ошибка перестала проявляться.

**Comment by PerlAmutor** [comment]
К сожалению ошибка до сих пор присутствует в 2024.1.3. Вчера столкнулся.
