### ISSUE TITLE
При редактировании модуля объекта бизнес-процесса EDT не видит типы реквизитов этого бизнес-процесса

### ISSUE THREAD

**Issue by jsteugene** [1C-Company/1c-edt-issues#1039]
### Описание ошибки

При редактировании модуля объекта бизнес-процесса, содержащего аннотацию //@strict-types, редактор кода не определяет тип реквизита бизнес-процесса, а валидатор диагностирует ошибки _Переменная "Реквизит" не имеет типа_ при попытке присвоить реквизиту какое-либо значение.

### Как воспроизвести

1. Создаем новый проект.
2. Создаем новый бизнес-процесс с именем "БизнесПроцесс".
3. Добавляем реквизит бизнес-процесса с именем "Реквизит" и типом "Строка".
4. В модуле объекта бизнес-процесса пишем код:

```

// @strict-types

#Если Сервер Или ТолстыйКлиентОбычноеПриложение Или ВнешнееСоединение Тогда

#Область ПрограммныйИнтерфейс

// Тест.
Процедура Тест() Экспорт
	
	Реквизит = "Тест";
	
КонецПроцедуры

#КонецОбласти

#КонецЕсли


```

5. Получаем ситуацию на скрине:

### Скриншоты

![image](https://github.com/1C-Company/1c-edt-issues/assets/66112045/eeb57adf-03fb-4a86-aca9-279b57c85de9)

### Ожидаемое поведение

Ложного срабатывания проверки не происходит.

### Лог рабочей области

[logs.zip](https://github.com/1C-Company/1c-edt-issues/files/11848008/logs.zip)

### Версия 1С:EDT

Ruby 2023.1.0

### Операционная система

Windows

### Установленные плагины

1C:Code style V8, 1C:SSL-support, 1C:Language Tool

### Дополнительная информация

Проблема проявляется только в модуле объекта бизнес-процесса. В документах, справочниках проблемы не возникает.
Очистка проекта, подавление диагностики и отмена подавления к решению проблемы не приводят.

**Comment by MaksimDzyuba** [comment]
Здравствуйте, исправили
![image](https://github.com/1C-Company/1c-edt-issues/assets/77277424/d4d26842-a62b-4f76-a71b-b8a3d24d42c7)
