### ISSUE TITLE
EDT не видит поля Структуры, создаваемой в глобальном серверном общем модуле

### ISSUE THREAD

**Issue by VAGoncharov** [1C-Company/1c-edt-issues#1040]
### Описание ошибки

EDT не видит поля Структуры, создаваемой в глобальном серверном общем модуле. 

При этом, если через документирующий комментарий сослаться на функцию-конструктор структуры, то EDT начинает видеть все поля структуры и ее типы.

### Как воспроизвести

1. Создаем глобальный серверный общий модуль.
2. Создаем в нем функцию-конструктор, возвращающую структуру с типизированными полями, пример документирующего комментария для нее:
`
// Параметры:
//  Подразделение - СправочникСсылка.ПодразделенияОрганизаций
//  Дата - Дата
//  СообщатьОбОшибках - Булево
// 
// Возвращаемое значение:
//  Структура:
// * Филиал - СправочникСсылка.Филиалы, Неопределено - 
// * ЦФО - СправочникСсылка.ЦФО, Неопределено - 
// * ГлавныйЦФО - СправочникСсылка.ЦФО, Неопределено -
// * База - СправочникСсылка.Базы, Неопределено - 
`
3. Вызывает функцию в другом модуле (в моем случае - в модуле объекта документа), сохраняем ее результат в переменной.
4. Видим, что EDT не видит поля структры в этой переменной, только понимает, что это тип Структура. Добавление документирующего комментария для переменной с ссылкой на функцию-конструктор решает проблему.

### Ожидаемое поведение

-

### Лог рабочей области

-

### Версия 1С:EDT

2022.2.5

### Операционная система

Windows

### Установленные плагины

1C:Code style V8, 1C:SSL-support

**Comment by MaksimDzyuba** [comment]
Здравствуйте, ошибку исправили, постараемся включить в 2023.1
![image](https://github.com/1C-Company/1c-edt-issues/assets/77277424/233857ed-7fbc-488b-b604-04a4cbd56e80)
