### ISSUE TITLE
code-never-compilied - орфографическая ошибка

### ISSUE THREAD

**Issue by PerlAmutor** [1C-Company/1c-edt-issues#1041]
### Описание ошибки

Возможно в конструкции "@skip-check code-never-compilied" допущена орфографическая ошибка в слове "compilied", видимо подразумевалось слово "compiled"

### Как воспроизвести

Вставить код для подавления ошибок:

```
    #Если Сервер И Не Сервер Тогда //@skip-check code-never-compilied
        ИнформацияОбОшибке = ИнформацияОбОшибке();
    #КонецЕсли
```

### Ожидаемое поведение

```
    #Если Сервер И Не Сервер Тогда //@skip-check code-never-compiled
        ИнформацияОбОшибке = ИнформацияОбОшибке();
    #КонецЕсли
```

### Лог рабочей области

Оставил на работе

### Версия 1С:EDT

2022.2.5

### Операционная система

Windows

### Установленные плагины

Нет плагинов

**Comment by tretyakevich** [comment]
Исправлено в 2023.2
