### ISSUE TITLE
ВыбратьАсинх у ДиалогВыбораФайла не определен на web клиенте

### ISSUE THREAD

**Issue by lrRatibor** [1C-Company/1c-edt-issues#1044]
### Описание ошибки

В продолжение к багу #783 (там уже исправлено), EDT ругается, что данный метод не определен на веб клиенте.

### Как воспроизвести

1. Перейдите в Перейдите в форму
2. Создайте асинх процедуру на клиенте
3. Ввести
Диалог= Новый ДиалогВыбораФайла(РежимДиалогаВыбораФайла.Открытие);
Диалог.ВыбратьАсинх();
4. ЕДТ выдаст ошибку, что метод не определен

### Ожидаемое поведение

Метод на веб клиенте должен быть определен

### Лог рабочей области

-

### Версия 1С:EDT

Ruby 2023.1.0

### Операционная система

Windows

**Comment by MaksimDzyuba** [comment]
Здравствуйте, исправили, исправление будет в 2023.2
