### ISSUE TITLE
В расширении пропадают события форм

### ISSUE THREAD

**Issue by goodwinvu** [1C-Company/1c-edt-issues#1045]
### Описание ошибки

При переходе проекта на версию 23.1 с версии 22.2.5 в формах документа пропали события форм
При этом в файле события описаны внизу файла Form.form в секции extinfo
 ```
 <extInfo xsi:type="form:DocumentFormExtInfo">
    <handlers xsi:type="form:EventHandlerExtension">
      <event>AfterWrite</event>
      <name>фмоПослеЗаписиПосле</name>
      <callType>After</callType>
    </handlers>
    <handlers xsi:type="form:EventHandlerExtension">
      <event>AfterWriteAtServer</event>
      <name>фмоПослеЗаписиНаСервереПосле</name>
      <callType>After</callType>
    </handlers>
    <handlers xsi:type="form:EventHandlerExtension">
      <event>BeforeWriteAtServer</event>
      <name>фмоПередЗаписьюНаСервереПеред</name>
    </handlers>
    <handlers xsi:type="form:EventHandlerExtension">
      <event>OnWriteAtServer</event>
      <name>фмоПриЗаписиНаСервереПосле</name>
      <callType>After</callType>
    </handlers>
    <repostOnWrite>true</repostOnWrite>
  </extInfo>
```

вручную можно события в редакторе свойств на форме добавить, тогда секция принимает точно такой же вид, НО меняется порядок следования описания событий (handlers)

Если добавить события руками (перевыбрать) в панели свойств, то они отображаются и после перезапуска , всё ок
при этом файл по сути не меняется, меняется только порядок 

### Как воспроизвести

Открыть формы расширения, проект которого был создан в версии 22.2.5 в версии 23.1

### Ожидаемое поведение

Свойства должны находиться и отображаться корректно

### Лог рабочей области

[error.zip](https://github.com/1C-Company/1c-edt-issues/files/11904668/error.zip)

### Версия 1С:EDT

Ruby 2023.1.0

### Операционная система

Windows

### Установленные плагины

1C:Code style V8, Другие сторонние плагины `Название плагина...`

### Дополнительная информация

Версия 1С проекта 21
версия платформы 1С 8.3.21.1644

установлены плагины 
  Disable Editing plugin for 1C:EDT	0.5.0.20230411-0534
  Запуск модульных тестов	23.4.1.v20230504-2215

**Comment by goodwinvu** [comment]
похоже что влияет роль порядок следования описаний событий в xml формы

**Comment by goodwinvu** [comment]
При этом проблема в том, что сами события в файле есть, но в окне свойств не отображаются
И если пользователь что то поправит в форме и нажмёт сохранить, то события эти из формы удаляются

**Comment by goodwinvu** [comment]
порядок не влияет, проверил, видимо что-то в парсинге не так
если вручную перевыбрать события - их видно
но если они прилетают из изменения файла (а из гита они так и прилетают) их не видно
я пробовал прям тот же файл формы что получается если вручную напихать события подкинуть - не видит событий
очистки и проч. не помогают

**Comment by EChudnovsky** [comment]
У меня обработчики пропадают вот так.
https://github.com/1C-Company/1c-edt-issues/issues/1047

**Comment by EChudnovsky** [comment]
> 

По поводу, данные есть в файле, но сведения не отображаются, есть аналогичное поведение в редакторе ролей. Признали ошибкой, может это общая проблема?, По задаче почему-то установили низкий приоритет, т.е. считают нормой отображение не достоверной информации в редакторах !?

https://github.com/1C-Company/1c-edt-issues/issues/1038

**Comment by goodwinvu** [comment]
upd. Проверил этот сценарий на проекте версии 22 платформы - там всё ок
ошибка возникает в проекте на 21й версии

**Comment by EChudnovsky** [comment]
> 

Да у меня проект 21, но очистка обработчиков - это не причина взаимодействия с платформой, а поведение ide. По моим наблюдениям очистка происходила при расширенной проверки. По крайне мере из файла-источника записи исчезали, когда на экране появлялось "Расширенная проверка".

**Comment by vadimeg** [comment]
Исправлено в 2023.1 RC2
