### ISSUE TITLE
Научить ring и EDT CLI экспортировать конфигурацию в zip архив (а не только в папку с xml)

### ISSUE THREAD

**Issue by IojkinKot** [1C-Company/1c-edt-issues#1046]
### Описание проблемы

На текущий момент ring и EDT CLI умеют экспортировать конфигурацию в папку с файлами

ring edt@2023.1.0:x86_64 workspace export --project "E:\repo" --configuration-files "E:\xml" --workspace-location "E:\ws" --edt-location "C:\Program Files\1C\1CE\components\1c-edt-2023.1.0+289-x86_64"

Для "тяжелых" конфигураций это достаточно долгий процесс.

### Описание решения проблемы

Научить ring и EDT CLI экспорту конфигурации сразу в архив. Тем более сама оболочка EDT при полной загрузке конфигурации в базу так и делает

**Comment by dsavenko** [comment]
> Для "тяжелых" конфигураций это достаточно долгий процесс.

Какую именно проблему вы хотите решить экспортом в зипку? Если увеличить скорость экспорта, то она скорее уменьшится, если добавить поверх процесса архивацию. Если просто улучшить качество жизни (чтобы не нужно было отдельно потом зиповать) - это другое дело.

**Comment by IojkinKot** [comment]
> Какую именно проблему вы хотите решить экспортом в зипку?

Скорость экспорта на hdd точно должна вырасти, т.к. не будет писаться 100500 файлов. Да удаляются эти 100500 файлов тоже заметно долго как на hdd, так и на ssd.
А по факту эта выгрузка нужна только временно, чтобы потом загрузить через ibcmd файлы конфигурации в базу.
Кстати, ibcmd тоже не умеет за один этап создать базу и загрузить в нее архив выгрузки.
Нужно сначала создать базу, а потом загрузить из архива. Но это уже оффтопик.

**Comment by IojkinKot** [comment]
Вот нашел, что уже такое пожелание зарегистрировано.

https://github.com/1C-Company/1c-edt-issues/issues/901
