### ISSUE TITLE
[1CEDT] (Критическая ошибка) Очистка некоторых обработчиков  для элементов формы расширения в edt 2023.1.0  при очистке проекта.

### ISSUE THREAD

**Issue by EChudnovsky** [1C-Company/1c-edt-issues#1047]
```
В редакции edt 2023.1.0 (на ранних версиях не проверялось) с толкнулись с ситуацией
постоянной очисткой обработчиков событий в элементах формы расширения для события
"НачалоВыбора" (с операцией Вместо).

Стабильно поведение проявляется при запуске операции очистки проекта.

Product name: 1C:Enterprise Development Tools
Product version: 1.28.0.289
Java home: C:\Program Files\BellSoft\LibericaJDK-11-Full
Java vm name: OpenJDK 64-Bit Server VM
Java vm info: mixed mode
Java version: 11.0.12
Java vendor: BellSoft
OS: win32
Total mem: 17 179
Free mem: 8 153
Cores: 16
***********************************
*	Файлы, приложенные к задаче, отправлены разработчикам. Ссылка в задаче не отображается./t*
***********************************
```
Шаги для воспроизведения ниже, скриншоты до и после очистки проекта также приведены:

1. Заимствуем форму документа из основной конфигурации
2. В расширении для элемента формы назначаем обработчик "НачалоВыбора" (Вместо). Сохраняем.

![изображение](https://github.com/1C-Company/1c-edt-issues/assets/5530435/ce30c0ec-ca97-4757-8eb8-8dbd09a0a6ed)

3. Выполняем очистку проекта расширения. 

![изображение](https://github.com/1C-Company/1c-edt-issues/assets/5530435/c8731eca-1da0-4f25-81df-9a8825d64db3)

Файл лога: [log.log](https://github.com/1C-Company/1c-edt-issues/files/11914542/log.log)

**Comment by EChudnovsky** [comment]
см. переписку https://github.com/1C-Company/1c-edt-issues/issues/1045

**Comment by EChudnovsky** [comment]
Вот еще один пример потери обработчиков. 

Например ПОСТОЯННО (на всех релизах edt) теряется (очищается) обработчик ПередеЗаписьюНаСервере, что ломаем логику поведения форм.

Как воспроизвести:
1. Заимствовать форму элемента справочника.
2. Добавить обработчик события "ПередЗаписьюНаСерверПосле"
3. Выполнить очистку проекта 
4. Убедиться в ошибке.

Лог-файл:

[log.log](https://github.com/1C-Company/1c-edt-issues/files/11998542/log.log)

Результат очистки проекта. В ролике показаны три справочника, но таких объектов с очищенными обработчиками десятки:

https://github.com/1C-Company/1c-edt-issues/assets/5530435/9bc2f59d-de40-4877-9504-3f78c0edd756

**Comment by EChudnovsky** [comment]
@vadimeg, @Erik773 
Коллеги, как я понимаю вы являетесь кураторами задач, прощу обратить внимание на данную проблему (статус для нее не установлен). Такое поведение является критической ошибкой (ломаем логику форм).

**Comment by Erik773** [comment]
@EChudnovsky  здравствуйте.
Благодарим за содействие в продвижении задачи на исправление.
Для того чтобы, реагирование на баг-репорты было более оперативным, пожалуйста, не забывайте ставить задаче лейбл "bug".

**Comment by EChudnovsky** [comment]
> @EChudnovsky здравствуйте. Благодарим за содействие в продвижении задачи на исправление. Для того чтобы, реагирование на баг-репорты было более оперативным, пожалуйста, не забывайте ставить задаче лейбл "bug". Если задача соответствует критериям критичности https://github.com/1C-Company/1c-edt-issues/blob/main/TASK_CLASSIFICATION.md, то нужно установить лейбл critical, тогда она будет рассмотрена максимально оперативно.

Я был установил метку, НО при создании issues из edt (по кнопке "Сообщить о проблеме") у созданной задачи уже нет возможности управлять метками.

А возможность установки меток, через управляющие команды комментария, нужно поднимать документацию.

Не плохо бы, что бы подобная подсказка была в созданной задачи.

**Comment by EChudnovsky** [comment]
Что касается обработчиков очищаются обработчики связанные с реквизитами формы.
Обработчики самой формы сохраняются.

![изображение](https://github.com/1C-Company/1c-edt-issues/assets/5530435/cafbfd8e-e09f-4357-8fac-a9893a9a7f9d)

**Comment by vadimeg** [comment]
Причина та же, что и в https://github.com/1C-Company/1c-edt-issues/issues/1045

#1045 исправлена, должна попасть в исправительный релиз 2023.1
