### ISSUE TITLE
Порядок в Формах: реквизиты, команды, параметры

### ISSUE THREAD

**Issue by Roffild** [1C-Company/1c-edt-issues#1052]
Почему нельзя сменить порядок (вручную отсортировать) в Формах: реквизиты, команды, параметры?

Что за странное ограничение?

Я могу в XML местами поменять, но почему через интерфейс нельзя?

**Comment by adminimusRU** [comment]
Реквизиты, команды и параметры в редакторе форме всегда отсортированы по алфавиту, что в ЕДТ, что в конфигураторе, так исторически сложилось. Изменение порядка в xml вручную ни на что не влияет.

**Comment by RedMammoth** [comment]
Колонки таблицы значений кажется в порядке их добавления

**Comment by Roffild** [comment]
ёпрст... придется русский алфавит вспоминать...
