### ISSUE TITLE
Перестает обновляться индикатор прогресса и переключаться страницы диалогов во время длительных операций

### ISSUE THREAD

**Issue by adminimusRU** [1C-Company/1c-edt-issues#1053]
### Описание ошибки

При первом открытии существующей рабочей области в EDT 2023.1.0 (до этого была 2022.2.5) выполняет плановая пересборка проекта. В какой-то момент в интерфейсе EDT перестает обновляться прогресс этой операции, при этом процесс явно не зависает: есть нагрузка на CPU, работают меню, в строке состояния меняются цифры на индикаторе состояния кучи. Но прогресс в строке состояния и в панели Состояния больше не обновляется, показывает ту же операцию и % вплоть до конца сборки.
В разных воркспейсах подвисало на разных стадиях сборки, где-то на импорте файлов, где-то на "старт сервисов проекта", где-то уже на расширенной проверке модулей.
После окончания сборки (около часа) интерфейс "отлипает", далее всё работает хорошо.

### Как воспроизвести

Открыть рабочую область с существующим проектом предыдущей версии в EDT 2023.1.0.

### Скриншоты

![edt_2023 1 0-ui-progress-hang](https://github.com/1C-Company/1c-edt-issues/assets/28653631/f27583e8-747a-4ea3-be60-4d009bd3f6a9)

При зависании прогресса в процессе сборки также перестают переключаться страницы в диалогах:
![edt_2023 1 0-ui-hang](https://github.com/1C-Company/1c-edt-issues/assets/28653631/661fdd18-f313-4958-8b80-77ebb55dc3e6)

После полного окончания сборки диалоги снова начинают работать нормально.

### Ожидаемое поведение

Прогресс операций своевременно обновляется.

### Лог рабочей области

[logs.zip](https://github.com/1C-Company/1c-edt-issues/files/11939689/logs.zip)
[threaddump_2023.1.0_ws2.txt](https://github.com/1C-Company/1c-edt-issues/files/11939690/threaddump_2023.1.0_ws2.txt)

Также снял memory dump на 3.5 ГБ, могу прислать отдельно если нужен.

### Версия 1С:EDT

2023.1.0

### Операционная система

Windows

**Comment by adminimusRU** [comment]
При повторной пересборке проекта (после полного завершения конвертации воркспейса и перезапуска ЕДТ) зависание отображения прогресса так же воспроизводится.

**Comment by adminimusRU** [comment]
Аналогичное "залипание" интерфейса обнаружилось и во время другой длительной операции - получение и слияние из git при большом количестве изменений в удаленной ветке.

**Comment by tretyakevich** [comment]
Исправление перенесено в 2023.1
