### ISSUE TITLE
Строгая типизация: EDT не знает, что параметр ПроверяемыеРеквизиты в ОбработкаПроверкиЗаполнения это массив строк

### ISSUE THREAD

**Issue by VAGoncharov** [1C-Company/1c-edt-issues#1054]
### Описание ошибки

Создаем в модуле объекта событие ОбработкаПроверкиЗаполнения. Пишем там логику, добавляем в параметр ПроверяемыеРеквизиты строки с реквизитами, которые надо проверить. Включаем строгую типизацию. EDT начинает ругаться, что мы пытемся добавить типизированное значение в нетипизированную коллекцию. Помогает только док. комментарий к методу:

// Параметры:
//  Отказ - Булево - Отказ
//  ПроверяемыеРеквизиты - Массив Из Строка - 

### Как воспроизвести

-

### Ожидаемое поведение

EDT сам знает, что параметр ПроверяемыеРеквизиты есть массив строк.

### Лог рабочей области

-

### Версия 1С:EDT

2022.2.5

### Операционная система

Windows

### Установленные плагины

1C:Code style V8, 1C:SSL-support

**Comment by marmyshev** [comment]
@MaksimDzyuba обрати внимание

**Comment by adminimusRU** [comment]
дубль #985
