### ISSUE TITLE
Строгая типизация: ложное срабатывание проверки для метода ПоказатьВопрос

### ISSUE THREAD

**Issue by VAGoncharov** [1C-Company/1c-edt-issues#1055]
### Описание ошибки

Пишем код в модуле формы:

ОписаниеОповещения = Новый ОписаниеОповещения("КакойТоМетод", ЭтотОбъект);
ТекстВопроса = "Текст вопроса";
ПоказатьВопрос(ОписаниеОповещения, ТекстВопроса, РежимДиалогаВопрос.ДаНет);

Включаем строгую типизацию.

EDT выдает диагностическое сообщение:
"Вызываемый тип выражения не пересекается с типом: "ОписаниеОповещения" для параметра "ОписаниеОповещенияОЗавершении""

### Как воспроизвести

-

### Ожидаемое поведение

EDT знает, что переменная с типом ОписаниеОповещения это корректный тип параметра для метода ПоказатьВопрос.

### Лог рабочей области

-

### Версия 1С:EDT

2022.2.5

### Операционная система

Windows

### Установленные плагины

1C:Code style V8, 1C:SSL-support

**Comment by Erik773** [comment]
Здравствуйте @VAGoncharov,
могли бы вы, пожалуйста, приложить лог рабочей области 1C:EDT  (.log, .bak.log и trace.log в папке \.metadata проекта).

**Comment by Erik773** [comment]
Дубль #986
