### ISSUE TITLE
Регистры накопления: EDT позволяет проставить свойство "Индексировать с доп. упорядочиваем" на измерение, хотя платформа такое не поддерживает

### ISSUE THREAD

**Issue by VAGoncharov** [1C-Company/1c-edt-issues#1057]
### Описание ошибки

EDT позволяет выставить на измерение свойство Индексировать со значением "Индексировать с доп. упорядочиваем", хотя ни в описании платформенных индексов ([см. ИТС](https://its.1c.ru/db/metod8dev#content:1590:hdoc)) нет такого правила, ни конфигуратор не позволяет сделать такое.

### Как воспроизвести

-

### Ожидаемое поведение

EDT не позволяет поставить неправильное индексирование на измерение регистра накопления.

### Лог рабочей области

-

### Версия 1С:EDT

2022.2.5

### Операционная система

Windows

### Установленные плагины

1C:Code style V8, 1C:SSL-support

**Comment by Erik773** [comment]
Здравствуйте @VAGoncharov,
могли бы вы, пожалуйста, прикрепить лог рабочей области (.log, .bak.log и trace.log в папке \.metadata проекта) на момент возникновения проблемы.

**Comment by vadimeg** [comment]
Исправлено в 2023.2
