### ISSUE TITLE
Конструктор запроса отображает не все реквизиты для некоторых таблиц

### ISSUE THREAD

**Issue by adminimusRU** [1C-Company/1c-edt-issues#1061]
### Описание ошибки

Например для документа `КорректировкаРеализации` из ERP показывает только 2/3 реквизитов, и ни одной табличной части, хотя их 10 штук в документе.
На 2022.2.5 не воспроизводится.
В логе при разворачивании таблицы в конструкторе добавляется ошибка "Unhandled event loop exception".
Подсказка в редакторе запроса видит все поля и ТЧ этого документа.

### Как воспроизвести

На актуальной версии ERP 2.5:
1. Открыть конструктор запроса
2. Развернуть таблицу `Документы.КорректировкаРеализации`
3. Сравнить отображаемые в конструкторе реквизиты и фактические данные документа

### Скриншоты

![image](https://github.com/1C-Company/1c-edt-issues/assets/28653631/7f7f23be-f5c0-4a48-a2a3-fa0d1a729b32)

### Ожидаемое поведение

Конструктор запроса должен показывать все реквизиты и табличные части.

### Лог рабочей области

[logs.zip](https://github.com/1C-Company/1c-edt-issues/files/11968015/logs.zip)

### Версия 1С:EDT

2023.1.0

### Операционная система

Windows

**Comment by MaksimDzyuba** [comment]
Здравствуйте, спасибо, исправил. Войдет, конечно, в 2023.1
![image](https://github.com/1C-Company/1c-edt-issues/assets/77277424/0656783d-0c28-41bf-afef-9e65d9b7e8f3)
