### ISSUE TITLE
Существенное замедление редактора запросов в 2023.1.0

### ISSUE THREAD

**Issue by adminimusRU** [1C-Company/1c-edt-issues#1063]
### Описание ошибки

В версии 2023.1.0 наблюдается существенное ухудшение отзывчивости редактора запроса по сравнению с 2022.2.5. При редактировании сложных запросов происходят постоянные подвисания редактора.

### Как воспроизвести

Воспользоваться редактором запроса для правки текста большого сложного пакета запросов. Чем больше запрос, тем сильнее наблюдаются подвисания редактора.
Для примера записал процесс редактирование запроса в методе `НоменклатураСервер.ЗаполнитьДанныеВыбораУпаковками` из ERP 2.5.13.

### Скриншоты

Видео записаны в 60 кадров в секунду. Видимые подвисания не дефект записи, а реальная работа интерфейса

EDT 2023.1.0
![edt_2023 1 0-query-editor](https://github.com/1C-Company/1c-edt-issues/assets/28653631/4b163aaa-1bf6-4e1a-bd0e-084745ed7fa2)

EDT 2022.2.5
![edt_2022 2 5-query-editor](https://github.com/1C-Company/1c-edt-issues/assets/28653631/99cbbb90-4255-4668-8f74-e942ad71d876)

### Ожидаемое поведение

Редактор запроса не должен подвисать при правке текста.

### Лог рабочей области

При редактировании запроса в лог не добавляются новые сообщения.

### Версия 1С:EDT

2023.1.0

### Операционная система

Windows

**Comment by Erik773** [comment]
@adminimusRU здравствуйте.
Описанная вами проблема с "подвисаниями" в редакторе запросов на версии 2023.2 не воспроизводится. (см. [видео](https://github.com/1C-Company/1c-edt-issues/assets/93516265/dd753959-fc7c-43b6-8530-eb195a8ab8ef)
Возможно, она была уже исправлена в рамках других задач.
Могли бы вы, пожалуйста, проверить актуальность проблемы после обновления на версию 2023.2?

**Comment by NikitaMikhaylovSB** [comment]
@Erik773 а в исправительном 2023.1 не планируется?

**Comment by Erik773** [comment]
@NikitaMikhaylovSB, @adminimusRU правки должны попасть и в исправительную версию 2023.1
