### ISSUE TITLE
Строгая типизация: EDT теряет тип поля Структуры, если тип поля описан через ссылку См.

### ISSUE THREAD

**Issue by VAGoncharov** [1C-Company/1c-edt-issues#1064]
### Описание ошибки

EDT теряет тип поля структуры (1), если: 
1.  Структура (1) сама является полем структуры (2).
2. Тип поля в Структура (1) описано через ссылку См.

### Как воспроизвести

1. Описываем структуру (1). 

```
// Возвращаемое значение:
//  Структура:
// * НомерСтроки - Число -
// * Организация - СправочникСсылка.Организации -
// * Подразделение - СправочникСсылка.ПодразделенияОрганизаций -
**// * РасчетныйДокумент - См. ОпределяемыйТип.ДокументыРасчетаСПодотчетнымиЛицами**
// * Валюта - СправочникСсылка.Валюты -
// * ПодотчетноеЛицо - СправочникСсылка.ФизическиеЛица -
// * ОбъектРасчета - СправочникСсылка.ОбъектыРасчетовСПодотчетнымиЛицами -
// * Сумма - Число -
// * СуммаВалютная - Число -
// * СуммаДоОбновления - Число - 
// * ДТ - Булево -
//
Функция СтрокаРасчетовКакСтруктура() Экспорт
	
	Строка = Новый Структура();
	Строка.Вставить("НомерСтроки", 0);
	Строка.Вставить("Организация", Справочники.Организации.ПустаяСсылка());
	Строка.Вставить("Подразделение", Справочники.ПодразделенияОрганизаций.ПустаяСсылка());
	Строка.Вставить("РасчетныйДокумент", Документы.АвансовыйОтчет.ПустаяСсылка());
	Строка.Вставить("Валюта", Справочники.Валюты.ПустаяСсылка());
	Строка.Вставить("ПодотчетноеЛицо", Справочники.ФизическиеЛица.ПустаяСсылка());
	Строка.Вставить("ОбъектРасчета", Справочники.ОбъектыРасчетовСПодотчетнымиЛицами.ПустаяСсылка());
	Строка.Вставить("Сумма", 0);
	Строка.Вставить("СуммаВалютная", 0);
	Строка.Вставить("СуммаДоОбновления", 0);
	Строка.Вставить("ДТ", Ложь);
	
	Возврат Строка;
	
КонецФункции
```

2. Описываем структуру (2).
```
// Возвращаемое значение:
// 	Структура:
// 	* Отборы - См. СтандартныеОтборыОбработки
//  * ЗакрытьАвтоматически - Булево - 
// 	* СтрокаДт - Число - Номер строки в ТЧ Расчеты.
// 	* СтрокаКт - Число - Номер строки в ТЧ Расчеты.
**// 	* СтрокаРасчетДт - См. СтрокаРасчетовКакСтруктура 
// 	* СтрокаРасчетКт - См. СтрокаРасчетовКакСтруктура** 
//
Функция ПараметрыЗакрытияВстречныхОбязательств() Экспорт
	
	ПараметрыЗакрытия = Новый Структура;
	ПараметрыЗакрытия.Вставить("Отборы", СтандартныеОтборыОбработки());
	ПараметрыЗакрытия.Вставить("ЗакрытьАвтоматически", Ложь);
	ПараметрыЗакрытия.Вставить("СтрокаДт", 0);
	ПараметрыЗакрытия.Вставить("СтрокаКт", 0);
	ПараметрыЗакрытия.Вставить("СтрокаРасчетДт", СтрокаРасчетовКакСтруктура());
	ПараметрыЗакрытия.Вставить("СтрокаРасчетКт", СтрокаРасчетовКакСтруктура());
	
	Возврат ПараметрыЗакрытия;
	
КонецФункции
```

3. Создаем нужные переменные, убеждаемся, что EDT теряет тип поля **РасчетныйДокумент** в структуре (1) и выдает сообщение "свойство "Расчетный документ" не имеет типа возвращаемого значения".

### Ожидаемое поведение

-

### Лог рабочей области

-

### Версия 1С:EDT

2022.2.5

### Операционная система

Windows

### Установленные плагины

1C:Code style V8, 1C:SSL-support

**Comment by Erik773** [comment]
Здравствуйте @VAGoncharov 
Могли бы вы, пожалуйста, предоставить логи рабочей области на момент возникновения проблемы.

**Comment by VAGoncharov** [comment]
Лог [log edt.log](https://github.com/1C-Company/1c-edt-issues/files/12019071/log.edt.log)

**Comment by ukolabrother** [comment]
Добрый день.
Не воспроизводится. Возможно проблема в неправильно описании блока "Возвращаемое значение". Попробуйте убрать для поля "РасчетныйДокумент" ключевое слово "см.". "// * РасчетныйДокумент - ОпределяемыйТип.ДокументПартии". 
![изображение](https://github.com/1C-Company/1c-edt-issues/assets/71124350/c1f8b3b3-50d9-4585-81ba-302b0280a42f)

**Comment by ukolabrother** [comment]
Ошибка не подтверждена. Ответа не получено. Закрываю.

**Comment by VAGoncharov** [comment]
Не видел уведомления.

1. Если убрать См. перед определяемым типом, тогда проблема уходит, это подтверждаю.
Однако, в документации нигде не указано, как правильно описывать определяемые типы. Везде ссылка на объект метаданных описывается через См.. Почему в данном случае делается исключение? Мне это кажется нелогичным.
Поэтому предлагаю - добавить в документацию инфо, как правильно описывать определяемый тип.

2. Нашел еще странное поведение с учетом вашего замечания. Мой код из примера размещен в модуле менеджера обработки. Если я создаю переменную в модуле менеджера через функцию ПараметрыЗакрытияВстречныхОбязательств(), тогда EDT корректно считает, что СтрокаРасчетДт/СтрокаРасчетКт имеет определяемый тип. Но если я создаю переменную в модуле формы, тогда EDT считает, что эти поля имеют тип ДокументСсылка.АвансовыйОтчет + ОпределяемыйТип, т.к. в функции-конструкторе описано значение по-умолчанию ДокументСсылка.АвансовыйОтчет. Это не ошибка, просто разное поведение в разных контекстах. Для разработчика тоже кажется нелогичным.

**Comment by ukolabrother** [comment]
@VAGoncharov 
См. - ключевое слово для указания ссылки. Определяемые типы - метаданные. Никакого исключения нет. Кажется все логично.

**Comment by VAGoncharov** [comment]
> @VAGoncharov См. - ключевое слово для указания ссылки. Определяемые типы - метаданные. Никакого исключения нет. Кажется все логично.

Открыл справку, раздел 1C:Code style V8 - Проверки - Типизация кода.
Примеры ссылок на объекты метаданных через "См.":
![image](https://github.com/1C-Company/1c-edt-issues/assets/1153965/d2a10a3a-8a8d-4ede-bf82-0410eebad468)
![image](https://github.com/1C-Company/1c-edt-issues/assets/1153965/8cc6538c-c6c8-4bf2-bef0-7a9151e71327)
![image](https://github.com/1C-Company/1c-edt-issues/assets/1153965/d1ad6737-1f38-4342-9871-580d8a22f1a3)

Все это ссылки на объекты, которые есть в дереве метаданных конфигурации.

**Comment by ukolabrother** [comment]
> > @VAGoncharov См. - ключевое слово для указания ссылки. Определяемые типы - метаданные. Никакого исключения нет. Кажется все логично.
> 
> Открыл справку, раздел 1C:Code style V8 - Проверки - Типизация кода. Примеры ссылок на объекты метаданных через "См.": ![image](https://private-user-images.githubusercontent.com/1153965/289225046-d2a10a3a-8a8d-4ede-bf82-0410eebad468.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIyMjEyOTEsIm5iZiI6MTcwMjIyMDk5MSwicGF0aCI6Ii8xMTUzOTY1LzI4OTIyNTA0Ni1kMmExMGEzYS04YThkLTRlZGUtYmY4Mi0wNDEwZWViYWQ0NjgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIxMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMTBUMTUwOTUxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YjFkZWY0OGE3YjZlNzg0MTQ3MWQ4MjJhODE0MGI0OTI1N2E3ZWUyNDNlOTk4MjI4MTJhMmY3NDYxZjM0OGQ1ZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.6h5rs5oxGLQaHA1tf4I1KTS4rsKfX812vrrk7CHWjnw) ![image](https://private-user-images.githubusercontent.com/1153965/289225126-8cc6538c-c6c8-4bf2-bef0-7a9151e71327.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIyMjEyOTEsIm5iZiI6MTcwMjIyMDk5MSwicGF0aCI6Ii8xMTUzOTY1LzI4OTIyNTEyNi04Y2M2NTM4Yy1jNmM4LTRiZjItYmVmMC03YTkxNTFlNzEzMjcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIxMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMTBUMTUwOTUxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Y2U0ODJkYWU4OTdlNWU3OTU3ZDA1ZmQxZDg4NmU5M2ExMDAyNmU2Y2M2YjM5MmZiOGRmYTJkYWQxZjNkZmJmMiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.oZN7hG9VYGAV_A8BuIqJGsAJdAthXbUpYLHjRr2_SAA) ![image](https://private-user-images.githubusercontent.com/1153965/289225175-d1ad6737-1f38-4342-9871-580d8a22f1a3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIyMjEyOTEsIm5iZiI6MTcwMjIyMDk5MSwicGF0aCI6Ii8xMTUzOTY1LzI4OTIyNTE3NS1kMWFkNjczNy0xZjM4LTQzNDItOTg3MS01ODBkOGEyMmYxYTMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIxMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMTBUMTUwOTUxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YjE5MWZmNTc5NzYyNTExMzM1OTA2Y2Y3ZDBjZGFiMTYzMDI4N2RiYmM1NGE0Nzg1YzVkM2I2ODU2ODkxMTczNCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.Vy3dzHS-Ckcqlq2zHIMIjFYD_-MFiiBRfXA8dYDsBt4)
> 
> Все это ссылки на объекты, которые есть в дереве метаданных конфигурации.

![image](https://github.com/1C-Company/1c-edt-issues/assets/71124350/b73077b6-5a33-4dc8-94c1-d6a8e2915957)

https://its.1c.ru/db/v8std/content/453/hdoc

**Comment by VAGoncharov** [comment]
> > > @VAGoncharov См. - ключевое слово для указания ссылки. Определяемые типы - метаданные. Никакого исключения нет. Кажется все логично.
> > 
> > 
> > Открыл справку, раздел 1C:Code style V8 - Проверки - Типизация кода. Примеры ссылок на объекты метаданных через "См.": ![image](https://private-user-images.githubusercontent.com/1153965/289225046-d2a10a3a-8a8d-4ede-bf82-0410eebad468.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIyMjEyOTEsIm5iZiI6MTcwMjIyMDk5MSwicGF0aCI6Ii8xMTUzOTY1LzI4OTIyNTA0Ni1kMmExMGEzYS04YThkLTRlZGUtYmY4Mi0wNDEwZWViYWQ0NjgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIxMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMTBUMTUwOTUxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YjFkZWY0OGE3YjZlNzg0MTQ3MWQ4MjJhODE0MGI0OTI1N2E3ZWUyNDNlOTk4MjI4MTJhMmY3NDYxZjM0OGQ1ZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.6h5rs5oxGLQaHA1tf4I1KTS4rsKfX812vrrk7CHWjnw) ![image](https://private-user-images.githubusercontent.com/1153965/289225126-8cc6538c-c6c8-4bf2-bef0-7a9151e71327.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIyMjEyOTEsIm5iZiI6MTcwMjIyMDk5MSwicGF0aCI6Ii8xMTUzOTY1LzI4OTIyNTEyNi04Y2M2NTM4Yy1jNmM4LTRiZjItYmVmMC03YTkxNTFlNzEzMjcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIxMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMTBUMTUwOTUxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Y2U0ODJkYWU4OTdlNWU3OTU3ZDA1ZmQxZDg4NmU5M2ExMDAyNmU2Y2M2YjM5MmZiOGRmYTJkYWQxZjNkZmJmMiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.oZN7hG9VYGAV_A8BuIqJGsAJdAthXbUpYLHjRr2_SAA) ![image](https://private-user-images.githubusercontent.com/1153965/289225175-d1ad6737-1f38-4342-9871-580d8a22f1a3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIyMjEyOTEsIm5iZiI6MTcwMjIyMDk5MSwicGF0aCI6Ii8xMTUzOTY1LzI4OTIyNTE3NS1kMWFkNjczNy0xZjM4LTQzNDItOTg3MS01ODBkOGEyMmYxYTMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIxMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMTBUMTUwOTUxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YjE5MWZmNTc5NzYyNTExMzM1OTA2Y2Y3ZDBjZGFiMTYzMDI4N2RiYmM1NGE0Nzg1YzVkM2I2ODU2ODkxMTczNCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.Vy3dzHS-Ckcqlq2zHIMIjFYD_-MFiiBRfXA8dYDsBt4)
> > Все это ссылки на объекты, которые есть в дереве метаданных конфигурации.
> 
> ![image](https://private-user-images.githubusercontent.com/71124350/289367635-b73077b6-5a33-4dc8-94c1-d6a8e2915957.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIyMjUxODksIm5iZiI6MTcwMjIyNDg4OSwicGF0aCI6Ii83MTEyNDM1MC8yODkzNjc2MzUtYjczMDc3YjYtNWEzMy00ZGM4LTk0YzEtZDZhOGUyOTE1OTU3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjEwVDE2MTQ0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM5YjM3YjRhY2FjZTcxNTAyODc1MDYxNGNiYzhjMGU5ZjgxNGI1ZTgzZmVhNGY0YWNjMjdjMzA2MWViOTA3YmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.kA2ayNgLwM6NDrsoCcoz14zIFTe-UqXGYVWTMTk1ULs)
> 
> https://its.1c.ru/db/v8std/content/453/hdoc

Ок, спасибо. Тогда предлагаю добавить пример с описанием определяемого типа в справку v8codestyle, т.к. при использовании строгой типизации смотрят туда, а не на стандарты разработки 1С.
Это стоит сделать хотя бы потому, что EDT позволяет в док. комментарии описать поле через См., панель BSL док комментарий спокойно это парсит, так же срабатывает контекстная подсказка после См., что вводит в заблуждение, что так можно.
