### ISSUE TITLE
Форма.Доступность=Ложь пропускает ОсновнуюКнопку

### ISSUE THREAD

**Issue by Roffild** [1C-Company/1c-edt-issues#1068]
1С:Предприятие 8.3 (8.3.22.1923)
```
	ЭтотОбъект.Доступность = Ложь;
	Элементы.ГруппаПараметтры.Доступность = Ложь; // Баг с кнопкой по умолчанию
```
И почему предупреждение АКП
> Избыточное обращение внутри модуля через псевдоним "ЭтотОбъект"
>    (к методу, свойству или реквизиту)

А как же правило программирования "Явное лучше неявного" ?

**Comment by Roffild** [comment]
Мне надоело месяцами ждать по почте регистрацию багов в 1С. Может здешние быстрее очухаются...

Проверку АПК можно отключать. Но тут претензия к самому правилу.
Может "Доступность" - это переменная функции, реквизит, свойство формы, или всё сразу.

Я из нормального мира в 1С прибыл, поэтому чту законы типа MISRA C из-за бессонных ночей дебага.

**Comment by adminimusRU** [comment]
> Может "Доступность" - это переменная функции, реквизит, свойство формы, или всё сразу.

а у вас вся работа в коде с реквизитами формы через `ЭтотОбъект `идет? Или может быть все реквизиты с префиксами? Или наоборот, все локальные переменные?
В целом конечно существует проблема путаницы реквизитов, свойств и переменных в модуле формы, и на грабли я тоже наступал. Тут уже зарегистрировано пожелание на то, чтобы можно было их хотя бы раскрашивать по-разному в редакторе, частично поможет.
С другой стороны, стандарт распространяется на код в целом безотносительно применяемого редактора, в конфигураторе путаница никуда не денется. Возможно будет продуктивнее обсудить это с авторами стандартов где-нибудь на партнерском форуме, через багтрекер EDT точно получится не ближе.

**Comment by VAGoncharov** [comment]
Еще раз. Это не ошибка EDT, поэтому в ишузе нет смысла.

Проверку стандартна можно отключить в свойствах проекта.

Можно в том же v8-code-style зарегать ишуз с пожеланием доработать проверку, с возможностью ее отключения на излишнее обращение к самому себе в определенных типах модулях. Без эмоций, с обоснованием почему. Учитывая скриптовую сущность BSL, замечание имеет место быть, сам по невнимательности подрывался в таких ситуациях.
Недавно там так и сделали для модуля объекта, было пожелание сделать там проверку отключаемой. А там уже каждый разработчик сам настроит для себя профиль валидации, голова на плечах же дата не для того, чтобы слепо следовать стандартам 1С, верно?
