### ISSUE TITLE
В командном интерфейсе расширения не отображаются заимствованные объекты

### ISSUE THREAD

**Issue by MoVled** [1C-Company/1c-edt-issues#1069]
### Описание ошибки

Ошибка в том что нет возможности настроить видимость заимствованных объектов в подсистеме расширения, т.к. сам объект в ней не отображается

### Как воспроизвести

1. Создать пустую конфигурацию
2. Добавить новый Справочник1, его форму списка, команду
3. Добавить Подсистему1, включить в неё Справочник1
4. В командном интерфейсе подсистемы отображается как сам справочник, так и отдельно его команда.
5. Создать новое расширение
6. Заимствовать в расширение Справочник1, его форму и команду.
7. Добавить в расширение Подсистему2, включить в неё Справочник1
8. В командном интерфейсе Подсистемы2 видим только команду.
9. Если создать и запустить базу с этой конфигурацией, то видим две идентичные подсистемы.
10. Запустим конфигуратор и отключим видимость Справочника1 в Подсистеме2, оставим только команду.
11. Запустим базу - видим, что в Подсистеме2 отображается только команда, Справочника1 нет.
12. Обновим проект по данным конфигурации
13. Видим, что в командном интерфейсе появилась строка "Catalog.Справочник1.StandartCommand.OpenList" со снятым флагом видимость
14. Запустим базу - приложение требует обновления - после обновления в Подсистеме2 снова отображается и справочник и команда
15. Дальнейшее управление в EDT флагом видимости по строке "Catalog.Справочник1.StandartCommand.OpenList" не влияет на видимость справочника в Подсистеме2

### Скриншоты

![image](https://github.com/1C-Company/1c-edt-issues/assets/90936490/54086619-eaca-42fa-a635-ba4605741d6d)

### Ожидаемое поведение

В настройке командного интерфейса добавленной в расширении подсистемы должен отображаться заимствованный объект. Управление его видимостью должно осуществляться аналогично объектам основной конфигурации

### Лог рабочей области

[log.txt](https://github.com/1C-Company/1c-edt-issues/files/12016335/log.txt)
[trace.log](https://github.com/1C-Company/1c-edt-issues/files/12016338/trace.log)

### Версия 1С:EDT

Ruby 2022.2.5

### Операционная система

Windows

### Установленные плагины

1C:SSL-support

**Comment by MoVled** [comment]
[interface_bug.zip](https://github.com/1C-Company/1c-edt-issues/files/12016508/interface_bug.zip)
Приложил архив с проектом (экспорт в файл архива)

**Comment by vadimeg** [comment]
Исправлено в 2023.2
