### ISSUE TITLE
Во время выполнения операции экспорта произошло несколько ошибок

### ISSUE THREAD

**Issue by kssashurik** [1C-Company/1c-edt-issues#107]
### Описание ошибки

Ошибка в том что невозможно запустить режим 1С:Предприятие (в т.ч. отладку) из EDT.

### Как воспроизвести

Контекст:
Windows 11 (64)
Платформа 1С:Предприятие 8.3.201590 (64)
Конфигурация на базе БП 3.0.
Клиент-серверная база (PostgreSQL 13.3).

Импортировал проект из существующей клиент-серверной базы.

При попытке запустить отладку EDT пишет, что "приложение требует полной загрузки обновления", запускаешь процесс, далее получаешь сообщение: "Во время выполнения операции экспорта произошло несколько ошибок" (см. скриншот).
Логи приложил.

### Скриншоты

![image](https://user-images.githubusercontent.com/24447912/142142581-a7011839-f573-4260-adcd-d194f29708e2.png)

### Ожидаемое поведение

Должен корректно запускаться режим 1С:Предприятие (отладка).

### Лог рабочей области

[.bak_0.log](https://github.com/1C-Company/1c-edt-issues/files/7552117/default.bak_0.log)
[.log](https://github.com/1C-Company/1c-edt-issues/files/7552118/default.log)
[trace.log](https://github.com/1C-Company/1c-edt-issues/files/7552119/trace.log)

### Версия 1С:EDT

Ruby 2021.2.10

### Операционная система

Windows

### Установленные плагины

1C:Code style V8, 1C:SSL-support

**Comment by vadimeg** [comment]
@kssashurik Можете проверить на последней версии EDT 2021.3? В новой версии было исправлено много ошибок.
И сделайте полную загрузку в ИБ.
