### ISSUE TITLE
Форма настройки дин. списка: не переведены значения перечисления "Вид ключа"

### ISSUE THREAD

**Issue by VAGoncharov** [1C-Company/1c-edt-issues#1070]
### Описание ошибки

Не переведены значения перечисления "Вид ключа" на форме настройки дин.списка.

### Как воспроизвести

1. Создать форму, создать в ней реквизит типа "Динамический список".
2. Открыть его настройки, написать какой-нибудь запрос. Для примера, выборку полей из произвольного документа.
3. Очистить основную таблицу. При выборе вида ключа видим, что значения не переведены на русский язык.
![Screenshot 2023-07-11 224135](https://github.com/1C-Company/1c-edt-issues/assets/1153965/48624445-816e-4fc3-9963-3bfabc676431)

### Ожидаемое поведение

Значения переведены на русский язык.

### Лог рабочей области

-

### Версия 1С:EDT

2022.2.5

### Операционная система

Windows

### Установленные плагины

1C:Code style V8, 1C:SSL-support

**Comment by Erik773** [comment]
Здравствуйте @VAGoncharov 
Могли бы вы, пожалуйста, предоставить лог файлы рабочей области ЕДТ на момент возникновения проблемы.

**Comment by vadimeg** [comment]
Исправлено в 2023.2.1
