### ISSUE TITLE
EDT зависает на этой форме

### ISSUE THREAD

**Issue by Roffild** [1C-Company/1c-edt-issues#1071]
Ruby 2023.1.0

Если у элемента Таблица Ширина=0 и Высота=0, тогда ЕДТ зависает.

Форма в Обработке.
[FormBad.zip](https://github.com/1C-Company/1c-edt-issues/files/12030075/FormBad.zip)

**Comment by Erik773** [comment]
Проблему воспроизвел на версии 2023,2
[threaddump.txt](https://github.com/1C-Company/1c-edt-issues/files/12035903/threaddump.txt)
[trace.log](https://github.com/1C-Company/1c-edt-issues/files/12035906/trace.log)

**Comment by vadimeg** [comment]
Исправлено в 2023.1 RC2
Конфигуратор не разрешает выставлять нулевые размеры для некоторых элементов, включая табличный документ. Для подсчета координат и размеров элементов на форме используются библиотеки платформы, которые на нулевых размерах выдают непредсказуемые результаты. Форма не зависает, просто рендеринг стал занимать существенное время при ошибочно рассчитанных размерах.

В EDT теперь тоже сделано такое ограничение, нельзя ставить некоторые элементы в нулевой размер.
