### ISSUE TITLE
Строгая типизация: метод УстановитьСсылкуНового для ПланСчетовОбъектИмяПланаСчетов имеет неправильное ожидаемое значение

### ISSUE THREAD

**Issue by VAGoncharov** [1C-Company/1c-edt-issues#1073]
### Описание ошибки

Метод УстановитьСсылкуНового для ПланСчетовОбъектИмяПланаСчетов имеет неправильное ожидаемое значение

### Как воспроизвести

1. Создаем переменную через менеджер плана счетов: МенеджерОбъекта = ПланыСчетов[ИмяПланаСчетов];
2. Создаем новый элемент через менеджер: Элемент = МенеджерОбъекта.СоздатьСчет();
3. Получаем ссылку нового СсылкаПоУИД = МенеджерОбъекта.ПолучитьСсылку(Новый УникальныйИдентификатор(УИД));
4. Пытаемся установить ссылку нового: Элемент.УстановитьСсылкуНового(СсылкаПоУИД)

EDT выдает предупреждение: нет соответствия между ожидаемыми типами ('ПланСчетовОбъектИмяПланаСчетов') и полученными ('ПланСчетовСсылкаИмяПланаСчетов '), хотя метод УстановитьСсылкуНового() принимает переменную ссылочного типа, а не объектного.

Так же похоже на ошибку в справке платформы: там для ПланСчетовОбъект этот метод тоже описан, как принимающий объект, а не ссылку, хотя для других объектов метод УстановитьСсылкуНового() описан корректно.

### Ожидаемое поведение

-

### Лог рабочей области

-

### Версия 1С:EDT

2022.2.5

### Операционная система

Windows

### Установленные плагины

1C:Code style V8, 1C:SSL-support

**Comment by Erik773** [comment]
Здравствуйте @VAGoncharov.
Могли бы вы, пожалуйста, приложить логи рабочей области на момент возникновения проблемы.
