### ISSUE TITLE
Строгая типизация: EDT теряет описание метода через цепочку ссылок (См.)

### ISSUE THREAD

**Issue by VAGoncharov** [1C-Company/1c-edt-issues#1076]
### Описание ошибки

EDT теряет описание метода через цепочку ссылок (См.)

### Как воспроизвести

Опишем функцию в модуле 1:
```
// См. Модуль2.ДатаНачалаНовойЛогики
//
Функция ДатаНачалаНовойЛогики() Экспорт
	Возврат Модуль2.ДатаНачалаНовойЛогики();	
КонецФункции
```

Далее, в модуле 2:
```
// См. РегистрыСведений.НастройкиПодсистемы.ДатаНачалаНовойЛогики
// 
Функция ДатаНачалаНовойЛогики() Экспорт
	Возврат РегистрыСведений.НастройкиПодсистемы.ДатаНачалаНовойЛогики();
КонецФункции
```

И наконец в модуле менеджера регистра:
```
// Возвращаемое значение:
//  Дата - 
Функция ДатаНачалаНовойЛогики() Экспорт
    Возврат Дата(1,1,1);
КонецФункции
```

В модуле 1 EDT выдает сообщение: "Описание экспортной функции должно возвращать блок "Возвращаемое значение"".
При этом, если в модуле 2 явно описать, что она возвращает Дату, или например вернуть значение константы, то EDT понимает сигнатуру метода в модуле 1.

### Ожидаемое поведение

-

### Лог рабочей области

-

### Версия 1С:EDT

2022.2.5

### Операционная система

Windows

### Установленные плагины

1C:Code style V8, 1C:SSL-support

**Comment by Erik773** [comment]
Здравствуйте @VAGoncharov.
Могли бы вы, пожалуйста, приложить логи рабочей области на момент возникновения проблемы.
