### ISSUE TITLE
Ложное срабатывание проверки "Объект метаданных не имеет реквизит "Комментарий" (md-object-attribute-comment-not-exist)

### ISSUE THREAD

**Issue by agibalovsa** [1C-Company/1c-edt-issues#1077]
### Описание ошибки

Срабатывает ошибка на справочники без поля "Комментарий", хотя в настройках ошибки указана опция только для документов.

### Как воспроизвести

1. Создать справочник.
2. Выйдет ошибка.

### Скриншоты

![image](https://github.com/1C-Company/1c-edt-issues/assets/14235747/1f0aa824-2c4d-4672-8569-e2074ff9f839)

### Ожидаемое поведение

Это ложное срабатывание.

### Лог рабочей области

[trace.log.zip](https://github.com/1C-Company/1c-edt-issues/files/12064200/trace.log.zip)

### Версия 1С:EDT

Ruby 2023.1.0

### Операционная система

Windows

### Установленные плагины

1C:Code style V8, 1C:SSL-support

**Comment by VAGoncharov** [comment]
Дубль [#13](https://github.com/1C-Company/v8-code-style/issues/1334)
