### ISSUE TITLE
Ложное срабатывание "Возможно, строковый литерал содержит ошибку [Сервер]" (wrong-string-literal-content)

### ISSUE THREAD

**Issue by agibalovsa** [1C-Company/1c-edt-issues#1080]
### Описание ошибки

Возникает ошибка при получении значения таблицы ссылки с помощью метода "ОбщегоНазначения.ЗначениеРеквизитаОбъектов("

### Как воспроизвести

1. Определить массив
2. В комментарии указать какие типы будут содержаться в массиве
3. Предполагается, что ссылки разных типов содержат одну и ту же таблицу
4. Заполнить его методами
5. При получении таблицы из элемента массива с помощью "ОбщегоНазначения.ЗначениеРеквизитаОбъектов" возникает ложно срабатывание

### Скриншоты

![image](https://github.com/1C-Company/1c-edt-issues/assets/14235747/fc17d56e-c653-498f-85d3-78aa2da3172c)

### Ожидаемое поведение

Программа исходя из описания типов элементов массива, должна понимать, что данную таблицу можно получить из ссылки

### Лог рабочей области

[trace.log.zip](https://github.com/1C-Company/1c-edt-issues/files/12064285/trace.log.zip)

### Версия 1С:EDT

Ruby 2023.1.0

### Операционная система

Windows

### Установленные плагины

1C:Code style V8, 1C:SSL-support

**Comment by marmyshev** [comment]
Тут аж 2 ошибки в коде:
1. Функция БСП может получать реквизит только по одной единственной ссылке в массиве - поэтому для массива разнородных ссылок - вызывать как-бы можно, но глупо - так как вернется результат для всех ссылок идентичных типу первого элемента.
2. Пункты 1-2 сценария бессмысленны. Определять тип переменной стр. 466 а потом заменять эту переменную в строке 467 - это создает ложное впечатление о типе переменной и лишняя нагрузка на CPU.

Поэтому, просьба указать какой реальный тип переменной в момент передачи ее в функцию БСП.

Либо можно в строке 467 после присвоения функции указать 

// Массив из СправочникСсылка.ИмяСправочника - тут единственный тип элементов массива!

**Comment by agibalovsa** [comment]
Добрый вечер.
1 - не понял, мой текст корректен и работает. См. скриншот из кода БСП
![image](https://github.com/1C-Company/1c-edt-issues/assets/14235747/9e228085-55e2-470b-8507-756465e94eed)

2 - действительно, я замылил глаз.
В итоге работает так:
![image](https://github.com/1C-Company/1c-edt-issues/assets/14235747/6978f9e9-3116-4942-8afd-d6eee31326b3)

Только строка очень длинная. ее нельзя никак уменьшить?

**Comment by marmyshev** [comment]
1. Ок, надеюсь типизация по функции БСП тоже поддерживает проверку всех типов элементов массива.

Закрываем?

**Comment by agibalovsa** [comment]
Думаю, да.
