### ISSUE TITLE
При наведении на ошибку окошко с информацией перескакивает куда-то вверх 

### ISSUE THREAD

**Issue by agibalovsa** [1C-Company/1c-edt-issues#1081]
### Описание ошибки

При наведении на ошибку окошко с информацией перескакивает куда-то вверх 

### Как воспроизвести

1. Навожу курсором на ошибку
2. И куда-то все упрыгивает см. гиф

### Скриншоты

![Перескакивание с ошибки](https://github.com/1C-Company/1c-edt-issues/assets/14235747/f0ffed26-be6c-4143-86b7-6c60a95d1450)

### Ожидаемое поведение

При наведении на ошибку текст должен остаться на месте.

### Лог рабочей области

[trace.log.zip](https://github.com/1C-Company/1c-edt-issues/files/12064880/trace.log.zip)

### Версия 1С:EDT

Ruby 2023.1.0

### Операционная система

Windows

### Установленные плагины

1C:Code style V8, 1C:SSL-support

**Comment by Erik773** [comment]
Здравствуйте @agibalovsa.
Могли бы вы, пожалуйста, приложить лог рабочей области, файлы .log и bak.log.
Если файл .log не удается прикрепить к задаче, то надо изменить его название и расширение на log.txt

**Comment by agibalovsa** [comment]
Здравствуйте, @Erik773.
Вот, пожалуйста:
[Log.zip](https://github.com/1C-Company/1c-edt-issues/files/12226780/Log.zip)

**Comment by MaksimDzyuba** [comment]
Здравствуйте, исправили, войдет точно в 2023.3, постараюсь перенести в 2023.2, спасибо!
