### ISSUE TITLE
Отсутствует свойство "ОтборСтрок" в контекстной подсказке для элемента с типом ТаблицаФормы

### ISSUE THREAD

**Issue by Stivo182** [1C-Company/1c-edt-issues#1084]
### Описание ошибки

Отсутствует свойство "ОтборСтрок" в контекстной подсказке для элемента с типом ТаблицаФормы

### Как воспроизвести

1. Перейдите на форму объекта
2. Создать реквизит формы с типом "ТаблицаЗначений" и вывести ее на форму
3. Перейти в модуль формы
4. Создать клиентскую процедуру
5. Начать ввод кода в теле процедуры: "Элементы.Таблица." нажать Ctrl+Space для вызова контекстной подсказки

### Скриншоты

![Безымянный](https://github.com/1C-Company/1c-edt-issues/assets/24582991/651e5a0f-cb5c-423e-aa50-56463dec8008)

### Ожидаемое поведение

Отображение свойства "ОтборСтрок" в контекстной подсказке для элемента с типом ТаблицаФормы

### Лог рабочей области

-

### Версия 1С:EDT

Ruby 2022.2.5

### Операционная система

Windows

### Установленные плагины

1C:Code style V8, 1C:SSL-support, 1C:Language Tool

### Дополнительная информация

1С:Предприятие 8.3 (8.3.22.1923)

Пример кода:
```
&НаКлиенте
Процедура УстановкаОтбораТаблицыФормы(ИмяКолонки, Значение)
   ОтборСтрок = Новый Структура;
   ОтборСтрок.Вставить(ИмяКолонки, Значение);
   Элементы.Таблица.ОтборСтрок = Новый ФиксированнаяСтруктура(ОтборСтрок); 
КонецПроцедуры
```

**Comment by MaksimDzyuba** [comment]
Здравствуйте, ошибка будет исправлена в 2023.2
