### ISSUE TITLE
ЕДТ не ловит бряк, когда окно Отладка неактивна(скрыта)

### ISSUE THREAD

**Issue by Roffild** [1C-Company/1c-edt-issues#1085]
Ruby 2023.1.0

В окошке Отладка отображается вызовы. В Параметрах снять галку "Открывать панель отладка...". Мне stack-calls (Отладка) не нужны на постоянке.

ЕДТ не ловит бряк, когда окно Отладка неактивна(скрыта). При активации окна Отладка бряк сразу показывается.

**Comment by Erik773** [comment]
Здравствуйте @Roffild 
Могли бы вы, пожалуйста, приложить логи рабочей области (.log, .bak.log и trace.log в папке \.metadata проекта) и чуть подробнее описать проблему, а также указать тип операционной системы, и, если возможно, то прикрепить скриншоты, чтобы можно было точнее понять и локализовать проблему.

**Comment by Roffild** [comment]
На скрине момент, когда в файловой базе бряк уже сработал, но ЕДТ об этом узнает, когда я кликну окно Отладка.

Похоже ЕДТ нуждается в окне Отладка, игнорируя даже галку в Параметрах. Я "открепляю" Отладку, чтобы ЕДТ считал окно всегда открытым - это решает проблему.

ЕДТ может активировать автоматически окно Отладка, игнорируя даже галку в Параметрах - тогда воспроизвести баг не получится. Всё зависит от расположения окна Отладка.
![Screenshot](https://github.com/1C-Company/1c-edt-issues/assets/38705255/f5e9e74f-479e-46e4-a42a-6cb702ccbc35)

**Comment by DmitryBelov-e1c** [comment]
Данное поведение является стандартным для Eclipse-based IDE (проверено на связке Eclipse - EDT) и связано с механиками работы с UI отладки. Событийная модель устроена таким образом, что выбор внутри дерева стека обеспечивает доставку события останова отладчика редактору + видам (например, Переменные). Такое же поведение при закрытой панели "Отладка" наблюдается, например, и на 2022.2.5; является корректным, так как унаследовано без изменений.
