### ISSUE TITLE
Имя вложенной группы колонок генерируется без приставки имени таблицы

### ISSUE THREAD

**Issue by Stivo182** [1C-Company/1c-edt-issues#1087]
### Описание ошибки

Имя вложенной группы колонок генерируется без приставки имени таблицы

### Как воспроизвести

1. На форме разместить таблицу формы
2. Для таблицы формы создать группу колонок. (По умолчанию будет предложено имя группы в формате: ИмяТаблицы + "Группа" + Индекс)
3. В созданной группе колонок создать вложенную группу колонок через контекстное меню Добавить - Группа колонок
4. Предложенное имя будет уже в формате "Группа" + Индекс

### Скриншоты

![Безымянный](https://github.com/1C-Company/1c-edt-issues/assets/24582991/45884bc7-7bd9-455d-aeae-4b339626e318)

### Ожидаемое поведение

Для вложенных групп таблицы должно генерироваться имя в формате _ИмяТаблицы + "Группа" + Индекс_, а не _"Группа" + Индекс_

### Лог рабочей области

-

### Версия 1С:EDT

Ruby 2022.2.5

### Операционная система

Windows

### Установленные плагины

1C:Code style V8, 1C:SSL-support, 1C:Language Tool

**Comment by vadimeg** [comment]
Проблема воспроизводится, это ошибка генерации имени вложенных групп, в логах ничего полезного не будет

**Comment by vadimeg** [comment]
Исправлено в 2023.2
