### ISSUE TITLE
Значение свойства ДоступностьДляВыбора не совпадает со значением в расширяемой конфигурации при экспорте расширения в конфигурацию

### ISSUE THREAD

**Issue by alxint** [1C-Company/1c-edt-issues#1089]
### Описание ошибки

Если в расширение добавляется картинка с признаком ДоступностьДляВыбора, возникает ошибка при экспорте расширения в конфигурацию. Ошибка возникает в проектах для платформы 8.3.20, 8.3.21. При использование платформы 8.3.22 выгрузка проходит.

### Как воспроизвести

1. Импортировать типовую конфигурацию Розница 2.3 
2. Создать новое расширение, добавить в расширение картинку у которое есть признак ДоступностьДляВыбора, к примеру ClosingX
3. Начать обновление конфигурации
4. Возникает ошибка (!!)Retail_2_3_11_44.ТестЭкспортаКартинки: Значение контролируемого свойства ДоступностьДляВыбора у объекта ОбщаяКартинка.ClosingX не совпадает со значением в расширяемой конфигурации

### Скриншоты

![image](https://github.com/1C-Company/1c-edt-issues/assets/1776565/f421d7de-8ad9-4bce-8362-34de45bb08f1)

### Ожидаемое поведение

ЕДТ при создание платформенного XML не добавляет свойства 
  <availabilityForChoice>true</availabilityForChoice>
  <availabilityForAppearance>true</availabilityForAppearance>
платформа 8.3.22 воспринимает такой XML, а младшие платформы нет, ожидается, что ЕДТ будет формировать XML совместимый с платформой.

### Лог рабочей области

[trace.log](https://github.com/1C-Company/1c-edt-issues/files/12098094/trace.log)
[log.log](https://github.com/1C-Company/1c-edt-issues/files/12098106/log.log)

### Версия 1С:EDT

Ruby 2023.1.0

### Операционная система

Linux

### Установленные плагины

1C:Code style V8, 1C:SSL-support

### Дополнительная информация

Проверялось на чистой установке 2023.1 c удалением .p2 и новом проекте

**Comment by alxint** [comment]
В 2003.1 нет возможности в расширении изменять значения этих свойств у картинки
![image](https://github.com/1C-Company/1c-edt-issues/assets/1776565/889b9cf9-da5a-4285-bde3-97243e5c378c)

Кроме того, в XML файле эти свойства установлены в соответствие со значениями в конфигурации

![image](https://github.com/1C-Company/1c-edt-issues/assets/1776565/63bbaa68-1b5e-4f2d-8a6d-fe875f0673bb)

но в выгруженном платформенном XML их нет.

**Comment by tretyakevich** [comment]
Исправлено в следующей версии 2023.1
