### ISSUE TITLE
Во время выполнения операции экспорта произошло несколько ошибок

### ISSUE THREAD

**Issue by Zinjifrag** [1C-Company/1c-edt-issues#1090]
### Описание ошибки

Невозможно запустить отладку из EDT
Ошибка в том что невозможно запустить режим 1С:Предприятие (в т.ч. отладку) из EDT на созданной информационной базе.

### Как воспроизвести

Воспроизведение: Создал новую ветку проекта. Создал новую информационную базу, зашел в нее через конфигуратор и загрузил ранее выгруженную информационную базу .dt, запустил отладку через конфигуратор с указанием, что база является копией (не перемещена). Затем, после закрытия окна тонкого клиента и конфигуратора 1С - Запустил "отладку как  тонкий клиент" с указанием информационной базы и настройками доступа в EDT (с установленной галочкой "загрузить конфигурацию полностью")
Во время операции происходит ошибка.

### Скриншоты

![Ошибка](https://github.com/1C-Company/1c-edt-issues/assets/97701532/3a948858-f6ac-4b0b-8fe5-13e0548d610b)
![Создание приложения](https://github.com/1C-Company/1c-edt-issues/assets/97701532/ced1bd15-b1da-4d7f-96d7-de087037ef38)

### Ожидаемое поведение

Запуск отладки приложения для работы

### Лог рабочей области

[.log](https://github.com/1C-Company/1c-edt-issues/files/12121883/default.log)
[trace.log](https://github.com/1C-Company/1c-edt-issues/files/12121884/trace.log)

### Версия 1С:EDT

Ruby 2023.1.0

### Операционная система

Windows

### Установленные плагины

Нет плагинов

### Дополнительная информация

Платформа 1С:Предприятие 8.3.22.1851 (64)

**Comment by adminimusRU** [comment]
В логе ругается на форму элемента справочника `ВидыКонтактнойИнформации`. Видимо исходники проекта битые.

**Comment by Zinjifrag** [comment]
> В логе ругается на форму элемента справочника `ВидыКонтактнойИнформации`. Видимо исходники проекта битые.

Cпасибо за обратную связь. Попробую сперва подчистить руками, ибо вроде как этот справочник был переработан. Может остались какие ссылки

**Comment by Zinjifrag** [comment]
Исправлено откатом к предыдущей версии EDT (2022.2.5). На момент создания темы версия "2023.1.0" имеет много артефактов, не зависящих от целостности проекта
