### ISSUE TITLE
Ошибки при публикации базы в IIS

### ISSUE THREAD

**Issue by REset49** [1C-Company/1c-edt-issues#1091]
### Описание ошибки

При публикации базы в IIS не определяется веб-ссылка в EDT.

### Как воспроизвести

1. Публикуем базу в IIS, стандартно через конфигуратор
2. Открываем EDT, в логах начинаем получать ошибки типа:
`com._1c.g5.v8.dt.platform.services.core.publication.WebServerAccessException: java.net.MalformedURLException: Illegal character found in host: '/`' 

Ошибка воспроизводится если нажать на гиперссылку "Открыть" в окне публикации и произвольно во время обычной работы в EDT.

### Скриншоты

![image](https://github.com/1C-Company/1c-edt-issues/assets/92163852/aed67942-add8-41e5-9142-d30023c088ec)

### Ожидаемое поведение

Корректное определение URL для публикаций IIS.

### Лог рабочей области

[.log](https://github.com/1C-Company/1c-edt-issues/files/12136191/default.log)

### Версия 1С:EDT

2023.1.0

### Операционная система

Windows

### Дополнительная информация

Windows 11
Платформа 8.3.22

**Comment by DmitryBelov-e1c** [comment]
@REset49 Здравствуйте, проверяю на более новых 8.3.22.2411 и EDT 2023.2.4; Win 10, не наблюдаю подобное поведение (и для файловой, и серверной). Кроме этого, вместо гиперссылки "Открыть" в окне публикации честный адрес на локальной машине. Скажите, пожалуйста, проблема на данный момент воспроизводима?

**Comment by DmitryBelov-e1c** [comment]
Закрыто в связи с невозможностью воспроизведения и отсутствия информации он пользователя.

**Comment by REset49** [comment]
Откройте, ошибка осталась.
- Windows 11 со всеми последними обновлениями.
- Поднят IIS с настройками по умолчанию
- Опубликовано несколько тестовых баз, публикации работаю без проблем

Что делаю:
- запускаю EDT с правами администратора
- для эксперимента создал новую рабочею область (это не принципально)
- перехожу в панель веб-серверы
- жму обновить
- получаю несколько указанных мной ошибок (для каждой из публикаций видимо)
![image](https://github.com/1C-Company/1c-edt-issues/assets/92163852/389f8fa3-13fe-4e1e-8c94-8593609ea67b)

**Comment by REset49** [comment]
И не находятся публикации во вложенных каталогах. Конфигуратор их нормально съедает.
![image](https://github.com/1C-Company/1c-edt-issues/assets/92163852/8b37c930-8631-431e-a9f5-41fef3d453b0)
