### ISSUE TITLE
Форма объекта: при удалении ТЧ из объекта, из формы не удаляются ссылки на ТЧ, если в реквизитах объекта есть доп. реквизит для этой ТЧ

### ISSUE THREAD

**Issue by VAGoncharov** [1C-Company/1c-edt-issues#1093]
### Описание ошибки

При удалении ТЧ из объекта, из формы не удаляются ссылки на ТЧ, если в реквизитах объекта есть доп. реквизит для этой ТЧ. Это приводит к тому, что невозможно экспортировать проект в ИБ и сформировать комплект.

Проблема в том, что описание доп. реквизита ТЧ сохраняется в xml формы, а там сохраняется ссылка на удаленную ТЧ в tablePath - segments.
При **переименовании** ТЧ в segments обновляется имя ТЧ, т.е. проблема именно при удалении.

### Как воспроизвести

1. Берем любой объект, у которого есть ТЧ. В примере это документ.
2. Создаем форму объекта, в реквизитах формы для ТЧ Объект.%ИмяТЧ% создаем доп реквизит "ДопРеквизит1" (в редакторе формы такие реквизиты отображаются красным цветом). Сохраняем.
3. Удаляем ТЧ %ИмяТЧ%. В редакторе реквизитов ТЧ и допреквизит пропали. При попытке экспортировать изменения в ИБ получаем ошибку "Файл - /Documents/%ИмяДокумента%/Forms/ФормаДокумента/Ext/Form.xml: Неверный путь к данным "Объект.%ИмяТЧ%".

Открываем форма в редакторе xml и видим, что в реквизитах формы сохранилось описание допреквизита. Ниже привожу пример реальной xml из конфигурации, где Объект.Финансовый - имя ТЧ, которую удаляют, доп реквизиты для нее - КоличествоСубконтоДт и КоличествоСубконтоКт.
`
<attributes>
    <name>Объект</name>
    <id>1</id>
    <valueType>
      <types>DocumentObject.КорректировкаРасчетовПоОплатеТруда</types>
    </valueType>
    <view>
      <common>true</common>
    </view>
    <edit>
      <common>true</common>
    </edit>
    <notDefaultUseAlwaysAttributes xsi:type="form:DataPath">
      <segments>Объект.RegisterRecords</segments>
    </notDefaultUseAlwaysAttributes>
    <main>true</main>
    <savedData>true</savedData>
    <additionalColumns>
      <tablePath xsi:type="form:DataPath">
        <segments>Объект.Финансовый</segments>
      </tablePath>
      <columns>
        <name>КоличествоСубконтоДт</name>
        <title>
          <key>ru</key>
          <value>Количество субконто дт</value>
        </title>
        <id>1</id>
        <valueType>
          <types>Number</types>
          <numberQualifiers>
            <precision>1</precision>
          </numberQualifiers>
        </valueType>
        <view>
          <common>true</common>
        </view>
        <edit>
          <common>true</common>
        </edit>
      </columns>
      <columns>
        <name>КоличествоСубконтоКт</name>
        <title>
          <key>ru</key>
          <value>Количество субконто кт</value>
        </title>
        <id>2</id>
        <valueType>
          <types>Number</types>
          <numberQualifiers>
            <precision>1</precision>
          </numberQualifiers>
        </valueType>
        <view>
          <common>true</common>
        </view>
        <edit>
          <common>true</common>
        </edit>
      </columns>
    </additionalColumns>
  </attributes>
`

### Ожидаемое поведение

Описание доп. реквизитов удаляется из xml формы.

### Лог рабочей области

-

### Версия 1С:EDT

2022.2.5

### Операционная система

Windows

### Установленные плагины

1C:Code style V8, 1C:SSL-support

**Comment by vadimeg** [comment]
См. https://github.com/1C-Company/1c-edt-issues/issues/918
Исправлено в 2023.1

**Comment by vadimeg** [comment]
И еще один:
https://github.com/1C-Company/1c-edt-issues/issues/947
