### ISSUE TITLE
Ломается синтаксический разбор кода при разбивке метода

### ISSUE THREAD

**Issue by adminimusRU** [1C-Company/1c-edt-issues#1098]
### Описание ошибки

При ручной разбивке метода (аналогично тому, что делает команда рефакторинг - извлечь метод) парсер ломается и выдает ложные срабатывания ошибок "Процедура или функция не определена" и "Синтаксическая ошибка. Пропущена лексема". При этом ошибки не видны в панели "Ошибки конфигурации", только в редакторе кода. И второй метод не виден в панели Схема.
Повторное редактирование и сохранение модуля, запуск проверки из контекстного меню ошибки не убирают.

### Как воспроизвести

1. Ввести код
```
// @strict-types

Процедура Процедура1()
	
	а = 1;
	
	б = а + 2;
	в = б + 3;
	
КонецПроцедуры
```
2. Разбить метод путем вставки кода после строки "а=1":
```
фрагмент(а);
	
КонецПроцедуры

Процедура фрагмент(а)
```

### Скриншоты

![image](https://github.com/1C-Company/1c-edt-issues/assets/28653631/49b67f6a-1744-4159-8d06-f057d6e20571)
![image](https://github.com/1C-Company/1c-edt-issues/assets/28653631/e8def049-3b08-4e46-b38e-16ef89277ab7)
![image](https://github.com/1C-Company/1c-edt-issues/assets/28653631/296ac27e-2b18-4a10-91bc-171fc006048c)

### Ожидаемое поведение

Ложных срабатываний быть не должно.

### Лог рабочей области

[логи.zip](https://github.com/1C-Company/1c-edt-issues/files/12158218/default.zip)
в логе ошибок нет

### Версия 1С:EDT

2023.1.0

### Операционная система

Windows

### Дополнительная информация

Если разбивать метод командой рефакторинг - извлечь метод или просто сразу заменить весь текст модуля, то ошибки не возникают.

**Comment by adminimusRU** [comment]
Включение строгой типизации (`// @strict-types`) не обязательно, без неё ломается точно так же.

**Comment by MaksimDzyuba** [comment]
Здравствуйте, воспроизвел, починил, войдет в 2023.3, спасибо!
