### ISSUE TITLE
Некорректная работа форм с элементом "Диаграмма Ганта"

### ISSUE THREAD

**Issue by alina-kenzh** [1C-Company/1c-edt-issues#1100]
### Описание ошибки

1. некорректное отображение формы в EDT при значении свойства **_Положение заголовка_** "Нет" у элемента формы "Диаграмма Ганта" форма не отображается;
2. после загрузке xml файлов в EDT пропадает заголовок формы при работе в 1С:Предприятие; не отображаются стандартные кнопки **_Записать_** и _**Провести и закрыть**_.

### Как воспроизвести

По первой ошибке:
1. Перейдите в любую форму, в которой присутствует элемент формы "Диаграмма Ганта";
2. В свойстве "Положение заголовка" у элемента "Диаграмма Ганта" установить значение "Нет".
По второй ошибке необходимо конвертировать проект с формами, имеющими элемент формы "Диаграмма Ганта" из конфигурации, перейти в режим 1С:Предприятие на данные формы.

### Скриншоты

1. 
![диаграмма ганта 1](https://github.com/1C-Company/1c-edt-issues/assets/83068739/20a40d19-f587-4f93-b8fe-f26ea2622db1)
![диаграмма ганта 2](https://github.com/1C-Company/1c-edt-issues/assets/83068739/1f7d21f7-96d3-4c27-a144-2113c3676842)
2-3
![Отображение наименования и станд кнопок 1](https://github.com/1C-Company/1c-edt-issues/assets/83068739/cb0ec9c0-bdb2-40c3-9518-bae855d9bd33)
.
![Отображение наименования и станд кнопок 2](https://github.com/1C-Company/1c-edt-issues/assets/83068739/10952652-78e8-4334-8e39-71e74cd18b5d)

### Ожидаемое поведение

1. Свойство "Положение заголовка" при значении "Нет" у элемента формы "Диаграмма Ганта" не влияет на отображение формы;
2. Формы с "Диаграммой Ганта" после загрузке из конфигурации не влияют на стандартные кнопки и наименование формы в режиме 1С:Предприятие.
_Причина отсутствия кнопок- при загрузке проекта в конфигурацию id кнопок занулились.После удаления и повторного добавления данного элемента "пропавшие" кнопки и наименование появились и корректно отобразились в  режиме 1С:Предприятие._

### Лог рабочей области

В логе ошибки не выявлены:
[ATT48768.txt](https://github.com/1C-Company/1c-edt-issues/files/12176881/ATT48768.txt)
[trace.log](https://github.com/1C-Company/1c-edt-issues/files/12176882/trace.log)

### Версия 1С:EDT

Ruby 2022.2.5

### Операционная система

Windows

### Установленные плагины

Нет плагинов

**Comment by vadimeg** [comment]
Проблема была исправлена в версии EDT 2023.1
