### ISSUE TITLE
Редактор запросов: Ложное срабатывание проверки на совместимость типов поля объекта метаданных

### ISSUE THREAD

**Issue by VAGoncharov** [1C-Company/1c-edt-issues#1105]
### Описание ошибки

На выделенном участке запроса срабатывает ошибка "Несовместимый тип (далее перечисление всех типов в измерении регистра)":

ВЫБРАТЬ
	УлучшениеНМА.Ссылка,
	УлучшениеНМА.ПометкаУдаления,
	УлучшениеНМА.Номер,
	УлучшениеНМА.Дата,
...
	ВЫБОР
		КОГДА УлучшениеНМА.Ссылка В
			(ВЫБРАТЬ ПЕРВЫЕ 1
				СвязиЭлектронныйДокумент.Связь КАК Связь
			ИЗ
				РегистрСведений.СвязиЭлектронныйДокумент КАК СвязиЭлектронныйДокумент
			ГДЕ
				**СвязиЭлектронныйДокумент.Связь ССЫЛКА Документ.УлучшениеНМА**
				И СвязиЭлектронныйДокумент.Связь = УлучшениеНМА.Ссылка)
			ТОГДА 0
		ИНАЧЕ 1
	КОНЕЦ КАК ИндексКартинкиСкан
ИЗ
	Документ.УлучшениеНМА КАК УлучшениеНМА

При этом в измерении "Связь" есть нужный тип документа. Работает на самых разных примерах, в подзапросах и соединениях, когда проверяем тип измерения через ССЫЛКА.

### Как воспроизвести

-

### Ожидаемое поведение

-

### Лог рабочей области

[лог рабочей области.log](https://github.com/1C-Company/1c-edt-issues/files/12224799/default.log)

### Версия 1С:EDT

2022.2.5

### Операционная система

Windows

### Установленные плагины

1C:Code style V8, 1C:SSL-support

**Comment by LesN1ck** [comment]
А если написать условие в виде "ТИПЗНАЧЕНИЯ(СвязиЭлектронныйДокумент.Связь) = Тип(Документ.УлучшениеНМА)"?

**Comment by MaksimDzyuba** [comment]
Здравствуйте, не смог воспроизвести на 2023.2, просьба как будет время проверить. Задачу пока закрою, если Вы сможете повторить, то переоткройте, пожалуйста.
![image](https://github.com/1C-Company/1c-edt-issues/assets/77277424/c155127c-a1df-456d-88f1-7127423bc65c)
[Конфигурация.zip](https://github.com/1C-Company/1c-edt-issues/files/13070003/default.zip)

**Comment by VAGoncharov** [comment]
> Здравствуйте, не смог воспроизвести на 2023.2, просьба как будет время проверить. Задачу пока закрою, если Вы сможете повторить, то переоткройте, пожалуйста. ![image](https://private-user-images.githubusercontent.com/77277424/277334913-c155127c-a1df-456d-88f1-7127423bc65c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIwODg4MjEsIm5iZiI6MTcwMjA4ODUyMSwicGF0aCI6Ii83NzI3NzQyNC8yNzczMzQ5MTMtYzE1NTEyN2MtYTFkZi00NTZkLTg4ZjEtNzEyNzQyM2JjNjVjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA5VDAyMjIwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEzMzVkNzJmZjg4ODE3Y2QzMTZiMWRhYWY0NzgzZDM0ZWM3ODkzMTM3NjBjYzE2YmIyZmI4ODU3MmJmMzQ1N2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.2FBviBUHjma-pbsJJn4ndxLaFgW8wWYv7hrz3NA5sto) [Конфигурация.zip](https://github.com/1C-Company/1c-edt-issues/files/13070003/default.zip)

Проверил на 2023.2.2, подтверждаю - все ок.
