### ISSUE TITLE
Недоступна форма редактирования списка выбора для элементов формы типа ПланСчетовСсылка.%ИмяПланаСчетов%

### ISSUE THREAD

**Issue by VAGoncharov** [1C-Company/1c-edt-issues#1108]
### Описание ошибки

Недоступна форма редактирования списка выбора для элементов формы типа ПланСчетовСсылка.%ИмяПланаСчетов%.

### Как воспроизвести

1. Создаем форму объекта метаданных, например, форму обработки.
2. Создаем реквизит формы или реквизит объекта метаданных с типом ПланСчетовСсылка.%ИмяПланаСчетов%.
3. Выводим реквизит на форму, для элемента формы проставляем свойство "Режим выбора из списка".
4. Убеждаемся, что свойство "Список выбора", которое открывает соответствующий редактор, не появляется.

Если повторить шаги 1-4 для другого типа данных, например, для ссылки на справочник или строку, то такой проблемы не наблюдается.

### Ожидаемое поведение

-

### Лог рабочей области

[лог рабочей области.log](https://github.com/1C-Company/1c-edt-issues/files/12261209/default.log)

### Версия 1С:EDT

2022.2.5

### Операционная система

Windows

### Установленные плагины

1C:Code style V8, 1C:SSL-support

**Comment by tretyakevich** [comment]
Исправлена в 2023.2
