### ISSUE TITLE
Зависание EDT во время работы

### ISSUE THREAD

**Issue by agibalovsa** [1C-Company/1c-edt-issues#1111]
### Описание ошибки

При работе с EDT периодически происходит зависание, после которой оболочка не реагирует, процессор не грузит, просто висит.

Вроде как чаще данная ситуация наблюдается при редактировании типов в комментариях.

### Как воспроизвести

Поведение кажется спонтанным.

### Скриншоты

![Зависание](https://github.com/1C-Company/1c-edt-issues/assets/14235747/1a31e8bb-67a7-422a-9382-f01ae04b6f9f)

![Зависание 2](https://github.com/1C-Company/1c-edt-issues/assets/14235747/3aaeb701-d017-467a-a4b8-191ad081c570)

### Ожидаемое поведение

Не должно так зависать.

### Лог рабочей области

[Зависание LOG.zip](https://github.com/1C-Company/1c-edt-issues/files/12300633/LOG.zip)

[trace.log.zip](https://github.com/1C-Company/1c-edt-issues/files/12300631/trace.log.zip)
[trace.log_2.zip](https://github.com/1C-Company/1c-edt-issues/files/12300632/trace.log_2.zip)

### Версия 1С:EDT

Ruby 2023.1.0

### Операционная система

Windows

### Установленные плагины

1C:Code style V8, 1C:SSL-support

**Comment by adminimusRU** [comment]
Не наблюдаю подобного зависания на 2023.1.0, хотя со строгой типизацией активно работаем. Было только #1053, но там не жесткое зависание.
У вас в логе куча предупреждений `Critical CPU overload`, и ругается что доступной памяти всего ~130 МБ осталось. У вас размер кучи для EDT какой установлен? И сколько всего оперативной памяти на машине? Судя по симптомам память банально кончилась и система ушла в подкачку, отсюда и подвисание.

**Comment by adminimusRU** [comment]
Проверить проблему со свопом можно даже в том же process explorer, открыть вкладку performance в свойствах процесса EDT, там скорее всего будет высокое значение показателя page fault delta.

**Comment by agibalovsa** [comment]
@adminimusRU Добрый день, при зависании система процессор точно не грузит. По поводу нехватки памяти, давайте проверю при следующем зависании. Однако, при свопе наблюдается нагрузка на диск, на процессор и т.д. В моем случае, просто система переставала жить и подавать какие-либо признаки жизни.

**Comment by adminimusRU** [comment]
В целом да, судя по скриншоту физической памяти еще много доступной (хотя бывают ситуации, когда и это не гарантирует отсутствие жесткого свопинга).

Возможно EDT уперлось в заданное ограничение на размер кучи, не помешает проверить настройки и включить индикацию https://edt.1c.ru/docs/examples/nastroyka-edt-dlya-importa-bolshikh-konfiguratsiy/

**Comment by agibalovsa** [comment]
Размер кучи у меня стандартный (см. скриншот ниже).
Однако и конфигурация минимальная 1,5 Мб. )))
Не ужели 4Гб может не хватить на 1,5Мб проекта?

![image](https://github.com/1C-Company/1c-edt-issues/assets/14235747/27fa581c-9f83-428e-99fb-c4a372c36f36)

**Comment by adminimusRU** [comment]
> Не ужели 4Гб может не хватить на 1,5Мб проекта?

судя по исправленной ошибке "_Происходила перегрузка по памяти во время полной проверки на выделенных 4Гб оперативной памяти_" в релизе 2023.1.1, такие чудеса случались и ругань на нехватку ресурсов в логах была неспроста :)

**Comment by agibalovsa** [comment]
Я смотрю только сегодня выпустили. пошел обновляться :)

**Comment by agibalovsa** [comment]
После обновления.... в какой-то момент система сошла с ума. Я в это время отлаживал и переходил туда-сюда по процедурам (Ctrl + Alt + H).

![image](https://github.com/1C-Company/1c-edt-issues/assets/14235747/ebbbb6f5-f9a4-437c-a660-0c868d66cb29)

![image](https://github.com/1C-Company/1c-edt-issues/assets/14235747/4c485be8-c3e1-4570-a11b-adbb15b78363)

Напоминаю, что проект 1,5 Мб?

[metadata.zip](https://github.com/1C-Company/1c-edt-issues/files/12315732/metadata.zip)

**Comment by agibalovsa** [comment]
В общем данное поведение связано с ошибкой #1112 (https://github.com/1C-Company/1c-edt-issues/issues/1112).
При изменении параметров процедуры, модуля процедуры, информация о ней не обновляется.
Возникают ошибки: не удается найти процедуру, не верное число параметров.
И если на такой процедуре нажать ctrl + alt + H, то система сходит с ума.

![Нагрузка ctrl+alt+h](https://github.com/1C-Company/1c-edt-issues/assets/14235747/95a94b51-5499-45ef-a818-5a2c9a7e3ad6)

**Comment by Erik773** [comment]
Здравствуйте @agibalovsa 
Подскажите, пожалуйста, правильно ли я понимаю, что проблема с зависанием ЕДТ у вас не воспроизводится после обновления и текущую задачу можно закрыть, так как актуальная проблема описана в #1112 ?

**Comment by agibalovsa** [comment]
@Erik773 последние сообщения (https://github.com/1C-Company/1c-edt-issues/issues/1111#issuecomment-1673631100, https://github.com/1C-Company/1c-edt-issues/issues/1111#issuecomment-1673678234) относится уже к релизу Ruby 2023.1.1.

Только сначала зависания были без загрузки процессора и вообще мертвыми, а потом стали с загрузкой процессора, но система как-то реагировала на действия.

**Comment by Erik773** [comment]
@agibalovsa могли бы вы, пожалуйста, предоставить дамп потоков на момент зависания ЕДТ.
Подробнее о снятии дампов  https://its.1c.ru/db/edtdoc#content:153:hdoc:i153__jstack

**Comment by agibalovsa** [comment]
@Erik773 Хорошо, нужно время.

**Comment by agibalovsa** [comment]
@Erik773 добрый день. Произошло зависание на EDT 2023.1.4 по первому сценарию, когда оболочка просто висит и не реагирует ни на что и не выдает ни какой активности.

![image](https://github.com/1C-Company/1c-edt-issues/assets/14235747/bb6a675d-0465-4164-a581-26115992fc89)
![image](https://github.com/1C-Company/1c-edt-issues/assets/14235747/896ee25a-6368-477b-b699-41b492590775)

Прикладываю дампы.

https://80.252.24.240/index.php/s/8R9K5J6Qk6K3JBQ
9PkkLnpQb7

**Comment by agibalovsa** [comment]
@Erik773 еще раз возникло зависание, собрал еще дампов. Вам их переслать, или предыдущих достаточно?

**Comment by Erik773** [comment]
Здравствуйте @agibalovsa!
> Вам их переслать, или предыдущих достаточно?
Перешлите, пожалуйста.

**Comment by agibalovsa** [comment]
@Erik773 добрый день.
https://nextcloud/index.php/s/ZRyPeLKEyq6rXjb
5XH9dD5znH

**Comment by VoyagerOnLine** [comment]
Не знаю в какой ишус нести, более подошел по названию
Зависает редактор во время работы

Через какое-то время после начала редактирования редактор и в целом среда подвисает
![image](https://github.com/1C-Company/1c-edt-issues/assets/66176550/e4098435-749a-4a35-b015-06d2981a87d6)

edt 2023.2.0, 
модуль содержит 12k строк - типовая документооборот 2.1 


[log.log](https://github.com/1C-Company/1c-edt-issues/files/12817258/log.log)

[trace.log](https://github.com/1C-Company/1c-edt-issues/files/12817262/trace.log)

[threaddump.txt](https://github.com/1C-Company/1c-edt-issues/files/12817265/threaddump.txt)

**Comment by DmitryShvaika** [comment]
Аналогичная проблема. Особенно часто наблюдается при редактировании модулей от 15 до 20 тыс строк. Когда поправил / сохранил, поправил / сохранил. При этом часто отменяется сборка и растет куча. Съедаются все 8 Гб отведенные для кучи достаточно быстро. После это Edt тормозит на любых операциях. Проблема до конца так и не исправлена Ruby 2023.2

**Comment by tretyakevich** [comment]
Введены ограничения на использование потоков во время пересчетов состояния модулей.
