### ISSUE TITLE
Не срабатывает автосортировка метаданных при переименовании объекта метаданных

### ISSUE THREAD

**Issue by VAGoncharov** [1C-Company/1c-edt-issues#1114]
### Описание ошибки

При переименовании объекта метаданных не срабатывает автоматическая сортировка, из-за чего переименованный объект остается на старой позиции. Это приводит к проблемам при слиянии веток.

Обходной путь: после переименования объекта запустить автосортировку в навигаторе проекта вручную.

### Как воспроизвести

-

### Ожидаемое поведение

Автосортировка отрабатывает после переименования объекта метаданных

### Лог рабочей области

-

### Версия 1С:EDT

2022.2.5

### Операционная система

Windows

### Установленные плагины

1C:Code style V8, 1C:SSL-support

**Comment by Erik773** [comment]
Здравствуйте, @VAGoncharov 
Могли бы вы, пожалуйста, приложить логи рабочей области ЕДТ на момент возникновения проблемы.
