### ISSUE TITLE
1CEDT Start. Среды разработки не устанавливаются

### ISSUE THREAD

**Issue by a2080016** [1C-Company/1c-edt-issues#1116]
### Описание ошибки

Среды разработки не устанавливаются.
Бесконечно висит сообщение - Подготовка к установке

### Как воспроизвести

Попробовать установить среду разработки

### Скриншоты

![image](https://github.com/1C-Company/1c-edt-issues/assets/24942027/d70d21ba-ea04-47a4-906c-7a955686c805)

### Ожидаемое поведение

Среды скачиваются и устанавливаются

### Лог рабочей области

[1cedtstart.log](https://github.com/1C-Company/1c-edt-issues/files/12322721/1cedtstart.log)

### Версия 1С:EDT

2023.1.1

### Операционная система

Windows

### Установленные плагины

1C:Code style V8

**Comment by pchurbanov** [comment]
Будет исправлена в следующей исправительной версии 2023.1
