### ISSUE TITLE
Завитает EDT при попытки отобразить контекстную подсказку

### ISSUE THREAD

**Issue by karneichik** [1C-Company/1c-edt-issues#1117]
### Описание ошибки

Когда курсор наводится на любую переменную вместо контекстной подсказки происходит зависание

### Как воспроизвести

Навести курсор на любую переменную в редакторе кода

### Скриншоты

![Untitled](https://github.com/1C-Company/1c-edt-issues/assets/40263436/497ff557-2d9d-4252-91bb-11c8b261c512)

### Ожидаемое поведение

Должно отображаться окно с контекстной подсказкой 

### Лог рабочей области

[log.log](https://github.com/1C-Company/1c-edt-issues/files/12324553/log.log)

### Версия 1С:EDT

2023.1.1

### Операционная система

Windows

### Установленные плагины

1C:Code style V8, 1C:SSL-support, 1C:Language Tool

### Дополнительная информация

Зависает при следующих действиях:
Если перейти в закладку Синтаксис-помощник
Настройки - общие - веб-браузер
Настройки - Справка
При этом если переменная помечена как warning или error - текст ошибки отображается в контекстной подсказке
При отладке показывает значение переменной, но только из метода в котором находится отладка

**Comment by tretyakevich** [comment]
1. Судя по зависаниям, каким-то образом была повреждена подсистема справки EDT, либо EDT имеет проблемы с запуском системного/встроенного браузера. Не могли бы вы показать текущие настройки Настройки - общие - веб-браузер (если они вообще доступны), если доступны - переключить браузер на встроенный для теста. Если данная страница не открывается вообще - рекомендуем переустановить EDT
2. В логе видим очень необычные исключения вида org.apache.ignite.internal.util.IgniteUtils.hash(IgniteUtils.java:309), пока единственное предположение - из исходников проекта Тестовая_база каким-то образом пропали UUID-ы. Не могли бы вы предоставить текущее состояние данной конфигурации из рабочего пространства (из того места, где конфигурация была физически развернута).

**Comment by karneichik** [comment]
1. Как я писал выше данная страничка помощи не открывается. Так же данная проблема была у меня в версиях EDT 2022.2.5 и 2023.1.0. 
2. Такая проблема во всех проектах. Для теста сделал новую пустую конфигурацию через EDT, добавил переменную в модуль приложения. Сразу подсказка работала, но как только перезагрузил проект, стало всё зависать.
[ПустаяБаза.zip](https://github.com/1C-Company/1c-edt-issues/files/12339469/default.zip)

**Comment by tretyakevich** [comment]
1. Можно попросить вас попробовать снять дамп потоков (jstack <id процесса в диспетчере задач> . Пока на релизной сборке воспроизвести это зависание не удалось. Возможно существует какая-то платформенно-зависимая специфика, вызывающая ошибку
2. Вы выложили расширение СМ_Доработки, упомянутая проблема была в базовой конфигурации (в логе она называется Тестовая_база). Именно там отсутствуют UUID-ы, и как раз логика работы с предоставленным расширением дает индикацию проблемы.

**Comment by karneichik** [comment]
1. Пробовал, результат нулевой. Jstack так же зависает.
2. Прошу прощения, видимо курсор стоял на другой папке, не обратил внимание. Сейчас высылаю пустой проект с названием "УдалиМеня", в котором добавлена только одна переменная в модуле приложения. 
[УдалиМеня.zip](https://github.com/1C-Company/1c-edt-issues/files/12368638/default.zip)

**Comment by tretyakevich** [comment]
Проверили на данной конфигурации - такого зависания повторить на релизной версии не смогли. Очевидно, что существует какой-то специфичный фактор именно в вашем случае. 

То, что не работает JStack - очень странно, обычно для этого есть только два случая (тотальная перегрузка по памяти, это явно не тот случай, либо внешний останов чем-нибудь вроде профайлера). Пока из идей могу предложить только связаться лично и попробовать снять стек онлайн, возможно что-то выяснится в процессе. Если такой вариант приемлем - Telegram-контакт https://t.me/AlexanderTretyakevich

**Comment by Erik773** [comment]
Закрыто, так как не предоставлены запрошенные данные для воспроизведения проблемы.
При предоставлении данных, просьба задачу переоткрыть.

**Comment by karneichik** [comment]
весьма странная ситуация, данные переданы, решения нету, а тикет закрыли :((
