### ISSUE TITLE
Ссылка на неизвестный предопределенный элемент

### ISSUE THREAD

**Issue by REset49** [1C-Company/1c-edt-issues#1119]
### Описание ошибки

При копировании справочника из другой конфигурации сохраняется несуществующий тип у стандартного реквизита "владелец", хотя справочник не подчиненный.
В итоге при попытке обновления возникает ошибка: 
Ссылка на неизвестный предопределенный элемент

Природу ошибки невозможно определить и исправить не прибегнув к анализу файлов проекта.

### Как воспроизвести

Действия указанные в инструкции на ИТС. Воспроизводится на версии БСП 3.1.7.357.
https://its.1c.ru/db/bsp317doc#content:4:hdoc:issogl4_в_случае_отдельного_справочника_для_хранения_файлов

### Ожидаемое поведение

Могу только вариантов накидать:
- не сохранять тип владельца справочника у неподчиненных справочников
- подсвечивать как ошибку в редакторе объекта, что неверный тип именно у владельца (с возможностью очистить тип)
- возможно оставить отображение свойств реквизита "владелец" в редакторе для неподчиненных справочников, если указан тип

### Лог рабочей области

ю

### Версия 1С:EDT

2023.1.1

### Операционная система

Windows

### Дополнительная информация

Платформа: 8.3.22.2143
Версия БСП на которой воспроизводится ошибка: 3.1.7.357
Добавление отдельного справочника для хранения файлов по инструкции

**Comment by Erik773** [comment]
Здравствуйте @REset49 
Могли бы вы, пожалуйста, приложить логи рабочей области.

**Comment by REset49** [comment]
@Erik773 лог
[_.log](https://github.com/1C-Company/1c-edt-issues/files/12367071/_.log)

**Comment by wolfandw** [comment]
Здравствуйте @REset49

**Comment by wolfandw** [comment]
Здравствуйте @REset49 Не могли бы Вы описать реальный сценарий, который работает на новой чистой конфигурации, поскольку текущее описание проблемы не коррелирует со сценарием из БСП, приведенным по ссылке. Вы описываете проблемы со стандартным реквизитом "Владелец", проблемы с его типом (у него нет типа на самом деле), а так же ошибку с предопределенным элементом. В сценарии БСП - ничего подобного нет - ни справочника с владельцем, ни предопределенных элементов.

**Comment by REset49** [comment]
@wolfandw, все верно, владельца нет, но запись о его типе есть в mdo. 
Если импортируете конфигурацию БСП-Демо (3.1.7.422) в EDT, то в _ДемоПроектыПрисоединенныеФайлы.mdo будет блок указанный мной на скрине, хотя владельца у него нет. И эта же запись будет в другой конфигурации EDT при Ctrl+C|V. Соответственно обновить эту конфигурацию не получится.
![image](https://github.com/1C-Company/1c-edt-issues/assets/92163852/ecdf88a6-7883-466a-ace8-9ba928a596ae)
![image](https://github.com/1C-Company/1c-edt-issues/assets/92163852/89af4ff6-cb22-4df1-8145-015392a1c4aa)

**Comment by wolfandw** [comment]
Хорошо, спасибо. Так понятнее. Будем смотреть

**Comment by RomanLabendj** [comment]
Добрый день. Столкнулся с подобной ошибкой в типовой ДО Корп 3.0.9.18
После импорта конфигурации в проект EDT и попытке обновить конфигурацию базы данных, возникает ошибка:
"Операция конфигурирования завершена неуспешно
Ошибка загрузки/выгрузки конфигурации
Ссылка на неизвестный предопределенный элемент - Catalog.ВидыУчастниковЗадач.Ответственный
Ссылка на неизвестный предопределенный элемент - Catalog.ВидыУчастниковЗадач.Исполнитель
Ссылка на неизвестный предопределенный элемент - Catalog.ВидыУчастниковЗадач.Проверяющий"
![image](https://github.com/1C-

При этом сам справочник ВидыУчастниковЗадач не менялся

[Лог_ЕДТ.log](https://github.com/1C-Company/1c-edt-issues/files/12595419/_.log)
Company/1c-edt-issues/assets/143495557/a4f80de8-d65e-4c3b-be7b-fd71e45a18da)

**Comment by RomanLabendj** [comment]
Здравствуйте @REset49, подскажите, пожалуйста, удалось ли как-то обойти данную ошибку?

**Comment by wolfandw** [comment]
В изначальной ошибке, при копировании подчиненного справочника с настроенным значением заполнения стандартного реквизита Владелец в другой проект, не находилась пустая ссылка на справочник-владелец, т.к. его никто в другой проект не копировал. При этом, ее не видно в свойствах в поле ЗначениеЗаполнения. т.к. определен только тип значения, но конкретное значение не выбрано. Ее можно почистить нажав на кнопку очистки в свойстве (хотя оно вроде бы пустое, но не совсем). На это дело будет сделана валидация и квикфикс, поскольку очищать при копировании не вариант, т.к. следующим шагом может быть скопирован владелец - тогда ссылки разрезолвятся, а значения заполнения придется перезаполнять заново.

**Comment by wolfandw** [comment]
> Добрый день. Столкнулся с подобной ошибкой в типовой ДО Корп 3.0.9.18 После импорта конфигурации в проект EDT и А после импорта и до попытки обновления - есть эти предопределенные элементы в справочнике? Если нет - можно поискать на них ссылки в проекте - будет видно где они "залипли"

**Comment by RomanLabendj** [comment]
Да, нашёл форму, в которой в одном из элементов "залипли" этип предопределённые элементы, удалил их оттуда.
Теперь поиском по файлам EDT не находит таких элементов нигде, а ошибка осталась...

**Comment by wolfandw** [comment]
> Да, нашёл форму, в которой в одном из элементов "залипли" этип предопределённые элементы, удалил их оттуда. Теперь поиском по файлам EDT не находит таких элементов нигде, а ошибка осталась...

Тогда нужно сделать выгрузку проекта в хмл-файлы и поискать там. Если там есть - выполнить очистку проекта

**Comment by wolfandw** [comment]
Добавлена валидация в версии 2023.3

**Comment by hexhoc** [comment]
up Коллеги! Возникает данная ошибка, если я импортирую проект с git.
Если импорт происходит напрямую из БД, то проблем нет. Хотя по сути все файлы идентичны

**Comment by Erik773** [comment]
Здравствуйте @hexhoc.
Могли бы Вы, пожалуйста, создать отдельную новую задачу с описанием рабочего сценария, при котором возникает проблема, приложить актуальные логи и в ней оставить ссылку на эту задачу. 
Начиная с версии 2025.1 для сбора технической информации рекомендуем использовать автоматическое создание архива, который содержит все нужные журналы и некоторые диагностические данные. Для этого в главное меню добавлена команда Справка > Собрать журналы и диагностические данные. Она собирает всю информацию в архив и открывает временный каталог с получившимся файлом.
