### ISSUE TITLE
Ложное срабатывание проверки "Свойство (метод) объекта не обнаружено" (unknown-method-property) для методов модулей с вызовом сервера

### ISSUE THREAD

**Issue by DmitryShvaika** [1C-Company/1c-edt-issues#1121]
### Описание ошибки

Ошибка "Свойство (метод) объекта не обнаружено" (unknown-method-property) диагностируется для всех вызовов функций модуля ВызовСервера из клиентских модулей.

![image](https://github.com/1C-Company/1c-edt-issues/assets/54451084/7d5eac38-2c3a-4916-8c40-8c41f80f0619)

Ошибка появилась с версией Ruby 2023.1.0

### Как воспроизвести

1. Создать процедуру в модуле ВызовСервера
2. Вызвать процедуру из модуля КлиентСервер или Клиент
3. Наблюдать ошибку

### Ожидаемое поведение

Ошибка не должна диагностироваться, ведь функция / процедура есть и она доступна к вызову

### Лог рабочей области

не требуется

### Версия 1С:EDT

Ruby 2023.1.1

### Операционная система

Windows

### Дополнительная информация

Архив проекта с тестовым примером
[test.zip](https://github.com/1C-Company/1c-edt-issues/files/12357478/test.zip)

Архив выгрузки тестовой базы
[test.zip](https://github.com/1C-Company/1c-edt-issues/files/12357493/test.zip)

**Comment by Erik773** [comment]
Дубль #1118

**Comment by MaksimDzyuba** [comment]
Проблема реально есть, она отличается от того, что пометили как дубль.

**Comment by MaksimDzyuba** [comment]
исправил, войдет в 2023.2
