### ISSUE TITLE
Ошибки видимости использования глобальных экспортных процедур из обработчиков оповещения

### ISSUE THREAD

**Issue by agibalovsa** [1C-Company/1c-edt-issues#1122]
### Описание ошибки

Если подключить глобальную экспортную процедуру для обработчика оповещения, то возникает 2 ложных срабатывания
1) Возможно, строковый литерал содержит ошибку [Тонкий клиент, Толстый клиент (управляемое приложение), Web-клиент]
для метода ПодключитьОбработчикОповещения
2) Неиспользуемый экспортный метод для самой глобальной экспортной процедуры
3) Для метода оповестить ошибок при этом не выходит (см. скриншот 3)

### Как воспроизвести

1. Создать в глобальном модуле экспортную процедуру
2. Подключить экспортную процедуру в качестве обработчика оповещения в модуле приложения

### Скриншоты

![image](https://github.com/1C-Company/1c-edt-issues/assets/14235747/491f777b-ac31-4e70-bbc3-daee70ddc7c7)

![image](https://github.com/1C-Company/1c-edt-issues/assets/14235747/dfe356d9-a8ad-428f-86ed-03d9b142ed96)

![image](https://github.com/1C-Company/1c-edt-issues/assets/14235747/5863c8dd-43f0-4116-8a15-dce6aede16d0)

### Ожидаемое поведение

Не должно возникать ошибок:
1) Возможно, строковый литерал содержит ошибку.
2) Неиспользуемый экспортный метод

### Лог рабочей области

[metadata.zip](https://github.com/1C-Company/1c-edt-issues/files/12357982/metadata.zip)

### Версия 1С:EDT

Ruby 2023.1.1

### Операционная система

Windows

### Установленные плагины

1C:Code style V8, 1C:SSL-support

**Comment by MaksimDzyuba** [comment]
Здравствуйте, вопроизвел, поправил, войдет точно в 2023.3, возможно, будет перенос в 2023.2
