### ISSUE TITLE
Общий макет не видит измененений

### ISSUE THREAD

**Issue by unichkin** [1C-Company/1c-edt-issues#1132]
### Описание ошибки

Изменяю макет "ОписаниеИзмененийСистемы" - вношу правки, сохраняю, закрываю. При повторном открытии в EDT правки остаются. Но изменений нет в индексе, и они не уходят в базу как в результате обновления по запуску, так и по результату полной загрузки. 
Приходится запускать конфигуратор, вносить правки там, потом импортировать конфигурацию, тогда макет изменения затягивает.
Сейчас стоит Ruby 2023.1.1, на предыдущей версии работало.

### Как воспроизвести

Воспроизведение описано в шапке

### Ожидаемое поведение

Макет должен изменятся если в него вносятся правки, и транслировать изменения в ИБ

### Лог рабочей области

-

### Версия 1С:EDT

Ruby 2023.1.1

### Операционная система

Windows

**Comment by Erik773** [comment]
Здравствуйте @unichkin 
Правильно ли я понял, что проблема в том, что git не видит изменения внесенные в макет?
Могли бы вы, пожалуйста, уточнить какую используете конфигурацию и приложить лог рабочей области ЕДТ на момент возникновения проблемы.
Также если проблема связана с git, то, пожалуйста, приложите (например, скриншотом) настройки пользователя git и настройки репозитория (Окно -> Параметры -> Групповая разработка -> Git -> Конфигурация -> Настройки пользователя, Настройки репозитория).

**Comment by unichkin** [comment]
Добрый день. git не видит, потому что их EDT не видит. Т.е. изменяю макет - обновляю полностью конфу - он в ней прежний. Сейчас не могу плотнее этим заняться - думаю что позже найду время, чтобы воспроизвести на типовой и скинуть логи.

**Comment by Erik773** [comment]
Удалось воспроизвести проблему на версии  2023.1.1.65.
На версии 2023.2 проблема не воспроизводится.
