### ISSUE TITLE
Неверный путь к данным в динамическом списке (Ошибка блокирующая обновление конфигураций)

### ISSUE THREAD

**Issue by Merkalov** [1C-Company/1c-edt-issues#1133]
### Описание ошибки

При ручном внесении изменений в произвольный запрос динамического списка - появляется критическая ошибка при обновлении конфигурации.

### Как воспроизвести

1. Открыть любую форму списка
2. У динамического списка включить "произвольный запрос"
3. В запросе ВРУЧНУЮ добавить левое соединение с любым регистром (в условиях соединения можно просто указать ПО ИСТИНА)
4. Добавить в выборку любое поле из этого регистра.
5. Закрыть конструктор СКД.
6. Обновить конфигурацию.
7. Получить ошибку.

### Как исправить ошибку:
Снова зайти в конструктор СКД и открыть конструктор запроса, нажать "ОК", после этого конфигурация обновляется.

### Скриншоты

![Screenshot_3](https://github.com/1C-Company/1c-edt-issues/assets/28949451/a73c0a5c-f50c-423a-92b9-9bf465f773ac)
![Screenshot_4](https://github.com/1C-Company/1c-edt-issues/assets/28949451/c9a0b7b7-eae1-456e-b50a-640b61cb3761)

### Ожидаемое поведение

Конфигурация обновляется без ошибки.

### Лог рабочей области

[.log](https://github.com/1C-Company/1c-edt-issues/files/12424749/default.log)

### Версия 1С:EDT

Ruby 2023.1.2

### Операционная система

Windows

### Установленные плагины

Нет плагинов

### Дополнительная информация

В конфигураторе подобной ошибки нет. 
Похожая проблема (была решена): https://github.com/1C-Company/1c-edt-issues/issues/831

**Comment by vadimeg** [comment]
На 2023.2 не воспроизводится. Сделал по шагам, как в описании

![image](https://github.com/1C-Company/1c-edt-issues/assets/17178862/56af2f4d-91e7-472f-9d8d-d83788f201cb)

**Comment by vadimeg** [comment]
Проверил на релизах 2022.2.5 и 2023.1.6
Везде все работает корректно. И частичная и полная загрузка в базу после ручного изменения запроса.

@Merkalov 
Возможно дело в базе? Пробовали делать полную загрузку?

**Comment by Merkalov** [comment]
@vadimeg
Проверил на другой машине - баг не подтвердился. 
Проект у себя очищал. Создавал новую ветку + новая база. Проблема стала плавающей и к ней всегда приводит ручная правка произвольного запроса дин.списка, открытие консоли и проверка запроса не всегда решает проблему. Проявлялось и на версии EDT 2023.1.2 и 2023.1.3.
Полная загрузка конфигурации в базу привела к ещё большему количеству ошибок.
![image](https://github.com/1C-Company/1c-edt-issues/assets/28949451/b21c17f8-cfa1-4ad9-88b8-e55f0e8a7899)
Откатываю изменения в форме списка(изменялся только запрос дин.списка) - все ошибки пропадают, конфигурация файловой ИБД обновляется.

**Comment by vadimeg** [comment]
Есть подозрение, что причина та же, что и в https://github.com/1C-Company/1c-edt-issues/issues/1140

**Comment by ValentinChirikov** [comment]
Проблем воспроизводится в 2023.2.1, при выгрузке в XML EDT не добавляет тильду в DataPath и ставит неверный namespace.

В выгрузке XML EDT:

- /Form/Attributes/Attribute/Settings/Field "xmlns:d5p1" а должно быть "xmlns:dcssch"
- /Form/BaseForm/ChildItems/Table/ChildItems/LabelField/DataPath например "Список.ЕстьФайлы" а должно быть "~Список.ЕстьФайлы"

**Comment by vadimeg** [comment]
Но это ведь выгрузка другой конфигурации. Там нет тех полей, что на картинке выше.
Конфигуратор не смог разобрать запрос (какие-то ошибки) и, как результат, не смог вытащить корректные пути к данным. На выгрузке битые пути пометились ~. А вот EDT этот запрос разобрал и пути получились нормальные, но конфигуратор обратно их не принимает. Попробуем воспроизвести, но возможно потребуется конфигурация или полная выгрузка.

А изначальная проблема воспроизводится на 2023.2?

**Comment by ValentinChirikov** [comment]
> Но это ведь выгрузка другой конфигурации. Там нет тех полей, что на картинке выше. Конфигуратор не смог разобрать запрос (какие-то ошибки) и, как результат, не смог вытащить корректные пути к данным. На выгрузке битые пути пометились ~. А вот EDT этот запрос разобрал и пути получились нормальные, но конфигуратор обратно их не принимает. Попробуем воспроизвести, но возможно потребуется конфигурация или полная выгрузка.
> 
> А изначальная проблема воспроизводится на 2023.2?

Изначальная проблему не пробывал воспроизводить, но я так понимаю смысл такой же. Т.е. если руками в выгрузке EDT добавить ~ и поменять namespace  с  d5p1 на dcssch то всё загружается и работает. 
Конфигурацию думаю могу воссоздать, а можете взять конфу "управление компанией" (ранее УНФ) сделать расширение - втянуть туда справочник "Проекты" (и его зависимости) и "Форму списка", втянуть список в расширение - в запросе убрать левое соединение - проверить что в конфигураторе все ок - втянуть в EDT открыть форму списка в расширении - что-нибудь добавить - не важно куда - начать процесс обновления конфигурации - и вот и будет ошибка

**Comment by ValentinChirikov** [comment]
@vadimeg воссоздал пустое расширение сразу из EDT без конфигуратора - ошибку получается воспроизвести, подозреваю что дело в базовой конфигурации (но она на поддержке - SmallBusinessBe3 ver=3.0.1.282)

**Comment by vadimeg** [comment]
@ValentinChirikov А если снять с поддержки перед тем, как импортировать в EDT, то проблема тоже воспроизводится?

**Comment by vadimeg** [comment]
Возможно, разные проблемы с похожей диагностикой. В изначальной проблеме не было расширения.
@Merkalov А что за конфигурация у вас? Это "Управление аптечной сетью"? И какой версии?

**Comment by vadimeg** [comment]
@ValentinChirikov Если убрать левое соединение, то запрос становится невалидным, т.к. в выборе запроса есть ссылка на НаличиеФайлов. Или ВЫБОР тоже нужно удалить?

![image](https://github.com/1C-Company/1c-edt-issues/assets/17178862/2c5e3b4a-5996-40b5-821f-001aede9fa7a)

**Comment by vadimeg** [comment]
Проверил сценарий от @ValentinChirikov с конфигурацией "управление компанией" на поддержке и расширением на 2023.3. Сейчас все корректно выгружается в EDT. Тильда к пути Список.ЕстьФайлы добавляется. Если в 2023.2 такая проблема появляется, то можно попробовать поискать в списке ошибок "Ошибки конфигурации" маркер с сообщением про сломанный путь к данным. У маркера есть быстрое исправление - будет предложено удаление битого пути.

![image](https://github.com/1C-Company/1c-edt-issues/assets/17178862/5e1d9fbd-8e3a-4ac4-ac62-3c6db8fab5e8)

По изначальной проблеме будем смотреть.

**Comment by ValentinChirikov** [comment]
> @ValentinChirikov А если снять с поддержки перед тем, как импортировать в EDT, то проблема тоже воспроизводится?

не пробовал так делать, но и с поддержки снять пока не имеем возможности, хотелось бы максимально быть совместимыми с кодом вендора

**Comment by vadimeg** [comment]
А профиль состава проверок не меняли? Там все по умолчанию?

**Comment by vadimeg** [comment]
В 2023.3.1 исправлена проблема, вызывающая ошибку "Неверный путь к данным "Список.Номер"" в расширениях.
Если эта ошибка будет продолжать появляться в 2023.3.1, то просьба переоткрыть задачу.
По другим проблемам, если они связаны с другой диагностикой или поведением просьба создать отдельную задачу.

**Comment by MaestroDi** [comment]
на 2023.3.3 проблема сохраняется даже без расширений в основной конфигурации "на замке"

**Comment by vadimeg** [comment]
> на 2023.3.3 проблема сохраняется даже без расширений в основной конфигурации "на замке"

Скорее всего проблема связана с чем-то другим. Недавно осуждалась проблема, где в запросе ДС фигурировала строка "ПЕРВЫЕ 1". Конфигуратор не мог разобрать такой запрос и создавал битые пути для элементов формы, а EDT такой запрос отрабатывает без ошибок.
Посмотрите, пожалуйста, в конфигураторе у всех ли элементов формы, связанных с ДС, выставлены пути к данным.
В частности, можно проверить только те, на которые ругается платформа при обновлении базы.

**Comment by MaestroDi** [comment]
> > на 2023.3.3 проблема сохраняется даже без расширений в основной конфигурации "на замке"
> 
> Скорее всего проблема связана с чем-то другим. Недавно осуждалась проблема, где в запросе ДС фигурировала строка "ПЕРВЫЕ 1". Конфигуратор не мог разобрать такой запрос и создавал битые пути для элементов формы, а EDT такой запрос отрабатывает без ошибок. Посмотрите, пожалуйста, в конфигураторе у всех ли элементов формы, связанных с ДС, выставлены пути к данным. В частности, можно проверить только те, на которые ругается платформа при обновлении базы.

В конфигураторе действительно пути к данным не указаны, но почему тогда в едт он их заполняет


![image](https://github.com/1C-Company/1c-edt-issues/assets/148856314/0db2114f-56c0-4440-ac1f-c728c96ccf35)
![image](https://github.com/1C-Company/1c-edt-issues/assets/148856314/6908b01c-f959-404a-91ea-6997c9ff4cd8)
![image](https://github.com/1C-Company/1c-edt-issues/assets/148856314/811b9386-f2a3-4c02-bd9e-abcf994cbe5d)

**Comment by MaestroDi** [comment]
А понял, потому что в конфигураторе реквизиты пропали у динамического списка хотя в запросе они есть....

**Comment by vadimeg** [comment]
> А понял, потому что в конфигураторе реквизиты пропали у динамического списка хотя в запросе они есть....

Ага, для EDT запрос из ДС валидный, поэтому он смог восстановить пути к данным у элементов формы.
А вот почему конфигуратор не ест этот запрос, это вопрос. Ну, и соответственно не хочет принимать пути, которые приходят из EDT при обновлении базы, т.к. он не может их сопоставить с запросом.

**Comment by MaestroDi** [comment]
А почему в едт он валидный а в конфигураторе не валидный, лучше же чтобы одинаково было как в конфигураторе? или хотя бы ошибку выдавать в едт

ВЫБРАТЬ
	ВЫБОР
		КОГДА ДокументУстановкаЦенНоменклатуры.ПометкаУдаления = ИСТИНА
			ТОГДА 2
		КОГДА ДокументУстановкаЦенНоменклатуры.Проведен = ИСТИНА
			ТОГДА 1
		ИНАЧЕ 0
	КОНЕЦ КАК СостояниеДокумента,
	ДокументУстановкаЦенНоменклатуры.Ссылка,
	ДокументУстановкаЦенНоменклатуры.ПометкаУдаления,
	ДокументУстановкаЦенНоменклатуры.Номер КАК Номер,
	ДокументУстановкаЦенНоменклатуры.Дата,
	ДокументУстановкаЦенНоменклатуры.Проведен,
	ДокументУстановкаЦенНоменклатуры.ТипЦен,
	ДокументУстановкаЦенНоменклатуры.НеПроводитьНулевыеЗначения,
	ДокументУстановкаЦенНоменклатуры.Ответственный,
	ДокументУстановкаЦенНоменклатуры.Комментарий,
	ДокументУстановкаЦенНоменклатуры.Информация,
	ДокументУстановкаЦенНоменклатуры.МоментВремени
ИЗ
	Документ.УстановкаЦенНоменклатуры КАК ДокументУстановкаЦенНоменклатуры

**Comment by vadimeg** [comment]
А конфигуратор никаких ошибок не выдает по поводу запроса? Просто выполняет некорректно и все?
Возможно каки-то проблемы с основной таблицей, если, например, было переименование объекта, рефакторинг при этом исправляет далеко не все кросс-ссылки. Если в этом причина, то это исправлено в 2024.1. Вот описание такой проблемы:
https://github.com/1C-Company/1c-edt-issues/issues/1315

Но все-таки хорошо бы выяснить почему конфигуратор не выполняет запрос, а EDT считает его валидным. Ошибка может быть как на стороне конфигуратора, так и на стороне EDT. Согласен, что хорошо, если работает одинаково. Но важней, чтобы работало правильно.

**Comment by MaestroDi** [comment]
> А конфигуратор никаких ошибок не выдает по поводу запроса? Просто выполняет некорректно и все? Возможно каки-то проблемы с основной таблицей, если, например, было переименование объекта, рефакторинг при этом исправляет далеко не все кросс-ссылки. Если в этом причина, то это исправлено в 2024.1. Вот описание такой проблемы: #1315
> 
> Но все-таки хорошо бы выяснить почему конфигуратор не выполняет запрос, а EDT считает его валидным. Ошибка может быть как на стороне конфигуратора, так и на стороне EDT. Согласен, что хорошо, если работает одинаково. Но важней, чтобы работало правильно.

При открытии в режиме предприятия говорит что некорректно указана основная таблица (она пустая)
![image](https://github.com/1C-Company/1c-edt-issues/assets/148856314/4b2c1713-02bc-4f53-b10a-d51872686269)

**Comment by vadimeg** [comment]
> При открытии в режиме предприятия говорит что некорректно указана основная таблица (она пустая)

Ну, вот. Значит скорее всего было переименование или удаление объекта, на который указывала основная таблица, а ссылки не подправили. Т.е. ошибка в конфигурации.
Как я писал выше, в 2024.1 сделали так, что EDT в таких случаях тоже не будет пытаться восстановить основную таблицу и тогда пути к данным будут битыми, как в конфигураторе. И обновление будет проходить без ошибок.
