### ISSUE TITLE
Не работает отладка соответствия

### ISSUE THREAD

**Issue by unichkin** [1C-Company/1c-edt-issues#1134]
### Описание ошибки

В коде не отображаются значения соответствия:
![image](https://github.com/1C-Company/1c-edt-issues/assets/10799597/9d4fea78-27a5-4189-94e4-62cad81397c4)

Если в соответствии много элементов - они группируются, второе выделение на скриншоте выше. Но при раскрытии - пустота:
![image](https://github.com/1C-Company/1c-edt-issues/assets/10799597/c15fdf14-6f6f-4137-b7b2-62adafc6b3b8)

На скриншотах тип - фиксированное соответствие, но тоже самое происходит и с обычным.

Все это-же и в окне выражений:
![image](https://github.com/1C-Company/1c-edt-issues/assets/10799597/e8e3e5fc-007f-4147-a169-19319be56c85)

### Как воспроизвести

Воспроизведение в описании

### Ожидаемое поведение

Содержимое любой коллекции должно быть доступно к просмотру. В идеале - с возможностью вывода в табличный документ, как это реализовано через табло в конфигураторе. 

### Лог рабочей области

-

### Версия 1С:EDT

Ruby 2023.1.1

### Операционная система

Windows

**Comment by unichkin** [comment]
Через shift + F9 также не работает
![image](https://github.com/1C-Company/1c-edt-issues/assets/10799597/bd0376d6-da2b-43f5-afe4-730a85536aef)

**Comment by adminimusRU** [comment]
Тоже такое ловил, и кажется на последней версии стало даже хуже. Иногда значения показываются, но ломается достаточно стабильно, в итоге пришлось отлаживать конфигуратором.
Показалось, что чаще ломается в серверном контексте, особенно если соответствие меняется внутри вызова другого метода или общего модуля (в случае фиксированного пересоздается).

**Comment by DmitryBelov-e1c** [comment]
Добрый день, задача связи с серверным контекстом отладки не имеет, вызвана некорректной имплементацией протокола отладки на стороне Платформы (различное поведение отладчика для, например, массивов и соответствий при одинаковом запросе). Проявилась в результате имплементации в EDT отображения размеров коллекций в видах отладки. Для исправления была создана ошибка 60009711, по результатам возможно потребуются изменения со стороны EDT в том числе.

**Comment by DmitryBelov-e1c** [comment]
@unichkin , @adminimusRU 
Добрый день, на текущий момент релизы версий Платформы 22-24 позволяют работать с Соответствиями корректно. Перевыпуск версии 21 с исправлениями, к сожалению, не планируется. Ограничения по минимальным сборкам в перспективных EDT добавим.
