### ISSUE TITLE
Тип ПолнотекстовыйПоискПриВводеПоСтроке не найден.

### ISSUE THREAD

**Issue by Roffild** [1C-Company/1c-edt-issues#1136]
```bsl
&НаКлиенте
Процедура Подключаемый_АвтоПодбор(Элемент, Текст, ДанныеВыбора, ПараметрыПолученияДанных, Ожидание, СтандартнаяОбработка)
	ПараметрыПолученияДанных.Вставить("ПолнотекстовыйПоиск", //////
			ПолнотекстовыйПоискПриВводеПоСтроке.НеИспользовать);
КонецПроцедуры
```
Предупреждение:
```
Переменная 'ПолнотекстовыйПоискПриВводеПоСтроке' не определена [Тонкий клиент, Толстый клиент (управляемое приложение), Web-клиент]
```
Ruby 2023.1.1

**Comment by Erik773** [comment]
Здравствуйте @Roffild 
Могли бы вы, пожалуйста, приложить лог рабочей области ЕДТ?

**Comment by Roffild** [comment]
Лог здесь ничего не даст.
Ссылка на тип в справке:
http://127.0.0.1:52166/help/index.jsp?topic=%2Fcom._1c.g5.v8.dt.platform.doc_v8_3_22%2Fhtml%2FSyntaxHelperContext%2Fobjects%2Fcatalog2%2Fcatalog370%2FFullTextSearchOnInputByString.html&cp%3D5_0_0_0_7_42_36

**Comment by MaksimDzyuba** [comment]
Здравствуйте, исправили в 2023.3, постараемся перенести в 2023.2, но не обещаю.
![image](https://github.com/1C-Company/1c-edt-issues/assets/77277424/c0d82c43-a674-40da-9fc4-6fcdf4c884bd)
