### ISSUE TITLE
NPE на плане счетов регистра бухгалтерии при слиянии двух веток

### ISSUE THREAD

**Issue by VAGoncharov** [1C-Company/1c-edt-issues#1137]
### Описание ошибки

Происходит либо зависание процесса слияния, либо NPE при попытке слить в текущую ветку ветку с изменениями в план счетов регистра бухгалтерии. Закономерность установить пока что не удалось, лог рабочей области приложил.

### Как воспроизвести

1. В ветке "А" делаем какие-то изменения в плане счетов регистра бухгалтерии. В моем случае - менялся родитель для 4х счетов.
2. Сливаем эти изменения в тестовую ветку "Тест".
3. Пытаемся так же слить в ветку "Тест" ветку "Б", где нет изменения плана счетов. Процесс слияния длится какое-то время, и либо зависает на определенном проценте (у меня на 61%), либо сразу валится на NPE.

### Ожидаемое поведение

-

### Лог рабочей области

[wslog.log](https://github.com/1C-Company/1c-edt-issues/files/12456921/wslog.log)

### Версия 1С:EDT

2022.2.5

### Операционная система

Windows

**Comment by traggerW** [comment]
Добрый день! Не могли бы вы прикрепить репозиторий, на котором у вас воспроизводится ошибка?

**Comment by traggerW** [comment]
Еще раз добрый день! Не могли бы вы протестировать, воспроизводится ли ошибка на свежей версии (2023.3)? Мне не удается воспроизвести на этой версии на тестовом репозитории. Правильно ли я понимаю, что под изменением "родителя" вы имели в виду изменение иерархии счетов в разделе "Предопределенные" для Плана Счетов?

**Comment by VAGoncharov** [comment]
> Добрый день! Не могли бы вы прикрепить репозиторий, на котором у вас воспроизводится ошибка?

Увы, исключено. ИБ.


> Еще раз добрый день! Не могли бы вы протестировать, воспроизводится ли ошибка на свежей версии (2023.3)? Мне не удается воспроизвести на этой версии на тестовом репозитории. Правильно ли я понимаю, что под изменением "родителя" вы имели в виду изменение иерархии счетов в разделе "Предопределенные" для Плана Счетов?

Ок, проверю. Верно, смена иерархии. Было 4 счета верхнего уровня, потом добавил еще один счет и сменил этим 4м иерархию и они стали счетами второго уровня, подчиненные новому счету. Или ровно наоборот, одно из двух, уже не помню.

**Comment by VAGoncharov** [comment]
На 2024.1 не воспроизводится.
