### ISSUE TITLE
При импорте конфигурации в проект затирается наименование предопределённого элемента.

### ISSUE THREAD

**Issue by RomanLabendj** [1C-Company/1c-edt-issues#1138]
### Описание ошибки

При импорте конфигурации в проект затирается наименование предопределённого элемента. Предопределённый элемент "Автоподстановки для мероприятий" справочника "Адресная книга"

### Как воспроизвести

платформа 1С 8.3.22.2198 
версия EDT 2023.1.2
типовая конфигурация Документооборот корп. 3.0.10.20
1. Создал пустую файловую базу, загрузил в неё конфигурацию, снял с поддержки
2. Создал пустой проект edt, импортировал в него конфигурацию из базы
3. Создал ещё одну пустую файловую базу, подключил её как приложение к проекту EDT c признаком "Загрузить конфигурацию полностью"
4. Сравнил конфигурацию новой базы с исходной

### Ожидаемое поведение

Наименование предопределённых элементов не должно затираться после импорта в проект EDT.

### Лог рабочей области

[Лог_ЕДТ.log](https://github.com/1C-Company/1c-edt-issues/files/12464079/_.log)

### Версия 1С:EDT

2023.1.2

### Операционная система

Windows

**Comment by RomanLabendj** [comment]
Также много и других отличий
[Отличия после импорта.pdf](https://github.com/1C-Company/1c-edt-issues/files/12465291/default.pdf)

**Comment by beg7** [comment]
Предопределенных нет и в исходной конфигурации, можете открыть редактор и там вы их не увидите.
Сделал выгрузку из Конфигуратора в XML и загрузил его обратно, увидел 
![image](https://github.com/1C-Company/1c-edt-issues/assets/13451949/37268691-4d1d-4bcb-9eeb-6f57b4e96468)

Обработчики событий либо без имени события либо с неправильным именем события. И так же не выгружаются самим конфигуратором.

Ошибка в исходной конфигурации ДО, EDT тут не может помочь.
