### ISSUE TITLE
Не сохраняется шрифт при редактировании в условном оформлении

### ISSUE THREAD

**Issue by Stivo182** [1C-Company/1c-edt-issues#1141]
### Описание ошибки

Не сохраняется шрифт при редактировании в условном оформлении

### Как воспроизвести

1. Открыть форму.
2. Через свойства формы открыть условное оформление.
3. Добавить новый элемент и перейти в оформление.
4. У параметра "Шрифт" открыть настройки шрифта.
5. Изменить значение любого свойства КРОМЕ свойства "Стиль".
6. Нажать ОК и еще раз ОК . (При этом Чекбокс у параметра Шрифт не установится автоматически. Даже если установить вручную, ситуация не изменится).
7. Зайти снова в оформление и в настройки шрифта. Настройки шрифта будут сброшены.

Способ выхода из ситуации:
1. В настройках шрифта поменять "Стиль" на другой и нажать ОК. (Чекбокс у параметра Шрифт теперь установится автоматически).
2. Зайти снова в настройки шрифта, поменять обратно стиль и установить нужные свойства шрифта.

### Скриншоты

![image](https://github.com/1C-Company/1c-edt-issues/assets/24582991/e5c0b1c1-0ac0-4703-aa42-97e4cc7a75f7)

### Ожидаемое поведение

Настройки шрифта сохраняются

### Лог рабочей области

Лог не сформировался

### Версия 1С:EDT

Ruby 2023.1.2

### Операционная система

Windows

### Установленные плагины

1C:Code style V8, 1C:SSL-support, 1C:Language Tool

**Comment by AlexandrKonokhov** [comment]
при редактировании в условном оформлении при в настройках отчета сбрасывается жирный шрифт после запуска 1с. 
<img width="1670" alt="Снимок экрана 2023-09-20 в 12 35 05" src="https://github.com/1C-Company/1c-edt-issues/assets/94432667/a13ad4b8-0d50-4bfd-9fd2-a9776591455a">

**Comment by wolfandw** [comment]
Исправлено. Войдет в 2024.1
