### ISSUE TITLE
8.3.22 конфигурация из конфигуратора сохраняется в файл в 10 раз медленнее после ее обновления из EDT

### ISSUE THREAD

**Issue by tormozit** [1C-Company/1c-edt-issues#1142]
### Описание ошибки

Конфигурация сохраняется в файл в 10 раз медленнее после ее обновления из EDT. Если из EDT пришла конфигурация в базу, то всегда сохранение в файл CF выполняется медленно. Платформа 8.3.22. В ней как раз была ускорена выгрузка в файл CF, но почему то после загрузки из EDT скорость выгрузки падает до той что была в 8.3.21
https://dl03.1c.ru/content/Platform/8_3_23_1865/1cv8upd_8_3_23_1865.htm#63056c50-7478-11ec-aa69-0050569f678a

### Как воспроизвести

.

### Ожидаемое поведение

Быстрое сохранение файла CF

### Лог рабочей области

.

### Версия 1С:EDT

Ruby 2022.2.5

### Операционная система

Windows

### Установленные плагины

Нет плагинов

**Comment by adminimusRU** [comment]
Это по-хорошему нужно на платформу багрепорт сразу отправлять. Предположу, что и после простой загрузки конфигурации из xml файлов без участия едт конфигуратор будет первый раз долго её обрабатывать пока кэш не перестроит.
Кстати, а как именно конфигурацию в файл сохраняли? Прямо интерактивно зашли в конфигуратор и из меню запустили сохранение? Или через пакетный режим?

**Comment by tormozit** [comment]
Я сохранял интерактивно, но уверен, что разницы в с пакетным режимом не будет.

**Comment by Erik773** [comment]
Здравствуйте Сергей!
Механизм сохранения конфигурации в cf полностью относится к платформе 1С:Предприятие, поэтому рекомендуем обратиться в отдел технической поддержки [v8@1c.ru](mailto:v8@1c.ru)
Возможно, причина в добавлении новых данных и изменении размера файла cf. 
Вы не пробовали загрузить конфигурацию из XML файлов без использования 1C:EDT через конфигуратор? При таком способе загрузки, увеличивается ли время сохранения в cf?

**Comment by tormozit** [comment]
а сейчас почему то быстро сохранилась конфигурация после обновления из EDT. Видимо зависит от того сколько объектов метаданных были загружены из файлов.
