### ISSUE TITLE
Панель выражения ошибочно НЕ вычисляет Сред

### ISSUE THREAD

**Issue by theshadowco** [1C-Company/1c-edt-issues#1145]
### Описание ошибки

Для метода Сред третий параметр не обязателен для указания, но в панели выражений ожидается обязательное его указание 

### Как воспроизвести

1. Переключиться в перспективу отладки, перейти на панель выражения
2. Добавить новое выражение `Сред("ТестоваяСтрока", 5)`
3. Видим ошибку

### Скриншоты

![image](https://github.com/1C-Company/1c-edt-issues/assets/9591731/00b4fac0-7982-4219-a1b9-4cbf87dda0e9)

### Ожидаемое поведение

Должен корректно работать

### Лог рабочей области

логов нет - даже в пустом WS повторяется

### Версия 1С:EDT

Ruby 2023.1.2

### Операционная система

Windows

### Установленные плагины

1C:Code style V8, 1C:SSL-support, 1C:Language Tool, Другие сторонние плагины `Название плагина...`

### Дополнительная информация

Установлен плагин YaxUnit

**Comment by DmitryBelov-e1c** [comment]
@theshadowco Добрый день, хотелось бы уточнить воспроизводимость данного бага на текущий момент. В большинстве случаев ошибки вычисления выражений возвращаются Платформой, поэтому обязательно так же указание её версии, если до сих пор работает некорректно. Спасибо.

**Comment by DmitryBelov-e1c** [comment]
Задача закрыта в связи с отсутствием информации о воспроизведении указанного поведения и невозможности сделать это по описанному сценарию.
