### ISSUE TITLE
Сбивается форма окна "Настройка получения изменений из origin

### ISSUE THREAD

**Issue by IgorPchelov** [1C-Company/1c-edt-issues#1147]
### Описание ошибки

Если изменить размер окна (попробовать растянуть или уменьшить), то половина элементов формы уезжает за пределы окна (кнопки, поля ввода итд...)

### Как воспроизвести

1. В дереве перспективы git нажать правой кнопкой мыши - "Получить из origin"
2. В открывшемся окне выбрать кнопку "Настроить"
3. В открывшемся окне "Настройка получения изменений" попробовать растянуть форму.
4. После п.3 правая часть формы уезжает за пределы экрана (кнопки и прочие элементы)

### Скриншоты

Исходная форма до изменения размера:

![image](https://github.com/1C-Company/1c-edt-issues/assets/110457908/2e188b3b-ae0b-456f-9e7c-c9f68c5d2003)

Форма после изменения размера:

![image](https://github.com/1C-Company/1c-edt-issues/assets/110457908/d9b7b749-0c01-4405-b32a-86a96e8d52eb)

### Ожидаемое поведение

Элементы формы должны оставаться на месте, как в исходном состоянии

### Лог рабочей области

Возможность предоставить лог остуствует.

### Версия 1С:EDT

Ruby 2023.1.3

### Операционная система

Windows

### Установленные плагины

1C:Code style V8, 1C:SSL-support

**Comment by traggerW** [comment]
Добрый день, ознакомились с багом. К сожалению, мы не можем оперативно исправить ошибку, т.к. это баг эклипсового кода, не связанный с плагином 1C:EDT. Для разработчиков эклипса создали задачу на исправление ошибки https://bugs.eclipse.org/bugs/show_bug.cgi?id=582629
