### ISSUE TITLE
Игнорирование ключевых параметров формы

### ISSUE THREAD

**Issue by Roffild** [1C-Company/1c-edt-issues#1149]
Ключевой параметр доступен после ПриСозданииНаСервере()
![bug](https://github.com/1C-Company/1c-edt-issues/assets/38705255/b00ad648-2824-4c70-a119-5c37c4cbd766)
Ruby 2023.1.1

**Comment by tretyakevich** [comment]
Добрый день, проверьте, пожалуйста в версии 2023.2.1. Если воспроизведется - приложите логи из рабочего пространства

**Comment by Roffild** [comment]
В 2023.2.0 исправлено.
