### ISSUE TITLE
Удаление проекта не удаляет результатов поиска по этому проекту

### ISSUE THREAD

**Issue by DmitryShvaika** [1C-Company/1c-edt-issues#115]
### Описание ошибки

После удаления проекта остаются результаты поиска, выполненные по этому проекту. 

### Как воспроизвести

1. Сделайте поиск по любому проекту
2. Выведите панель результата поиск на экран
3. Удалите проект
4. Результаты поиска остались в панели

### Скриншоты

![image](https://user-images.githubusercontent.com/54451084/142499315-ddb445dd-ba24-4ce3-a611-129e346320dd.png)

### Ожидаемое поведение

Результаты поиска по удаленному проекту так же должны удаляться

### Лог рабочей области

[логи.zip](https://github.com/1C-Company/1c-edt-issues/files/7566124/default.zip)

### Версия 1С:EDT

Ruby 2021.2.10

### Операционная система

Windows

### Установленные плагины

1C:Code style V8, 1C:SSL-support

**Comment by tretyakevich** [comment]
Исправлено в 2022.2
