### ISSUE TITLE
Конструктор форматной строки с заблокированным Примером

### ISSUE THREAD

**Issue by Roffild** [1C-Company/1c-edt-issues#1150]
Я хочу убедится, что "42" станет "042".

Какой гений проектирования интерфейсов додумался заблокировать ввод в Примере?

Ruby 2023.1.1

![bug](https://github.com/1C-Company/1c-edt-issues/assets/38705255/8f701854-b1dc-41c5-b215-b6407b31bd4a)

**Comment by IgorPchelov** [comment]
По этой ошибке уже есть одна задача: https://github.com/1C-Company/1c-edt-issues/issues/853

**Comment by Roffild** [comment]
Они #853 даже в планы не внесли... ыыы...

Ну... не успевают 2-3 разработчика ЕДТ копировать баги из Конфигуратора. Ожидаю слом Home-End при навигации по Свойствам из 8.3.23...

**Comment by Erik773** [comment]
Дубль #853
