### ISSUE TITLE
"Переименовать..." переменную тупит с Перем

### ISSUE THREAD

**Issue by Roffild** [1C-Company/1c-edt-issues#1154]
```bsl
#Область ИмяОбласти
// Без Области не воспроизводится
Процедура ИмяПроцедуры(Параметры)
	// Начать переименовывать с Перем
	Перем Элемент, ааа, индекс;
	ббб = 0;
	индекс = 0;
	Для Каждого Элемент Из Параметры Цикл
		ааа = Элемент;
	КонецЦикла;
	Для индекс = 1 По 1 Цикл
		ббб = индекс;
	КонецЦикла;
КонецПроцедуры
#КонецОбласти
```
Только "ббб" через "Рефакторинг - Переименовать..." изменится без проблем, потому что отсутствует в Перем.

Ruby 2023.1.1

**Comment by Erik773** [comment]
Здравствуйте @Roffild 
К сожалению, не удалось воспроизвести проблему на тестовой конфигурации.

https://github.com/1C-Company/1c-edt-issues/assets/93516265/757fec25-fe2a-4ae8-b780-f5bfc04c50c1

Могли бы вы, пожалуйста, подробнее описать сценарий и приложить логи рабочей области ЕДТ?

**Comment by Roffild** [comment]
Обновил код

**Comment by DmitryShvaika** [comment]
дубль https://github.com/1C-Company/1c-edt-issues/issues/390

**Comment by Roffild** [comment]
В  [#390](https://github.com/1C-Company/1c-edt-issues/issues/390) нет уточнения про Область.

**Comment by MaksimDzyuba** [comment]
Здравствуйте, удалось исправить, постараемся включить в 2023.3
![bandicam 2024-01-19 21-16-08-724](https://github.com/1C-Company/1c-edt-issues/assets/77277424/77e453d6-c1b9-4508-aec6-33bf63e1dd2d)
