### ISSUE TITLE
[1CEDT] При переключении с ветки на ветку ошибка сортировки

### ISSUE THREAD

**Issue by TimurDD** [1C-Company/1c-edt-issues#1155]
```

Product name: 1C:Enterprise Development Tools
Product version: 1.28.4.1
Java home: C:\Program Files\BellSoft\LibericaJDK-11-Full
Java vm name: OpenJDK 64-Bit Server VM
Java vm info: mixed mode
Java version: 11.0.9
Java vendor: BellSoft
OS: win32
Total mem: 10 737
Free mem: 4 982
Cores: 24
***********************************
*	Файлы, приложенные к задаче, отправлены разработчикам. Ссылка в задаче не отображается./t*
***********************************
```

**Comment by TimurDD** [comment]
После перехода на версию 2023 начали происходит разные ошибки. Одна из критичных эта. После этой ошибки дерево проекта "не раскрывается". Т.е. раскрываю ветку Общие модули и все. Далее перезагрузка, обычно автоматом стартует очистка проекта. После работает все норм, пока не переключишься на другую ветку. Но так происходит не всегда.

**Comment by AlmazNasibullin** [comment]
@TimurDD
Добрый день.
Подскажите, пожалуйста, на последних версиях 2023.3 и 2024.1.0 проблема воспроизводилась у вас еще раз?

**Comment by vadimeg** [comment]
Исправлено в 2024.1

**Comment by TimurDD** [comment]
Добрый, подтверждаю, ошибка в крайних версиях не воспроизводиться.
Спасибо)
