### ISSUE TITLE
фантомные зависания

### ISSUE THREAD

**Issue by Jimmi910** [1C-Company/1c-edt-issues#1157]
### Описание ошибки

открыл модуль и все зависло

### Как воспроизвести

1. Не знаю. Рандомно возникает. Если закрыть EDT и открыть заного тот же модуль - то все норм.
Все логи и дампы прикладываю.

### Ожидаемое поведение

что б не зависало

### Лог рабочей области

[metadata.zip](https://github.com/1C-Company/1c-edt-issues/files/12647623/metadata.zip)
[threaddump.txt](https://github.com/1C-Company/1c-edt-issues/files/12647628/threaddump.txt)
https://disk.yandex.ru/d/h8j_MMZiOz8kgA

### Версия 1С:EDT

2023.1.2

### Операционная система

Windows

**Comment by Erik773** [comment]
Здравствуйте Артем.
Могли бы вы, пожалуйста, уточнить в какой конфигурации и в каком модуле возникает проблема? Есть ли возможность предоставить конфигурацию или модуль для воспроизведения ошибки? Непосредственно перед открытием модуля производилось ли сравнение/объединение или какая-то другая операция с данными? Достаточно ли выделено памяти для ЕДТ?

**Comment by Jimmi910** [comment]
1. Это расширение для КА 2.5
2. Да есть. могу дать расширение.
3. Непосредственно перед - нет вроде не производилась. А за сколько то минут до, да было слияние с другой веткой.
4. 16Гб

**Comment by dsavenko** [comment]
Исправлено в 2023.3.
