### ISSUE TITLE
[1CEDT] Ошибка модуля org.eclipse.jface

### ISSUE THREAD

**Issue by TimurDD** [1C-Company/1c-edt-issues#1158]
```
При переключении с\на ветки(у), начиная с ЕДТ версии 2023, происходит данная ошибка. После ЕДТ ведет себя странно. При попытке выполнить слияние видит не все изменения.
Product name: 1C:Enterprise Development Tools
Product version: 1.28.4.1
Java home: C:\Program Files\BellSoft\LibericaJDK-11-Full
Java vm name: OpenJDK 64-Bit Server VM
Java vm info: mixed mode
Java version: 11.0.9
Java vendor: BellSoft
OS: win32
Total mem: 4 143
Free mem: 2 357
Cores: 24
***********************************
*	Файлы, приложенные к задаче, отправлены разработчикам. Ссылка в задаче не отображается./t*
***********************************
```

**Comment by TimurDD** [comment]
[.metadata.zip](https://github.com/1C-Company/1c-edt-issues/files/12648075/default.metadata.zip)

**Comment by TimurDD** [comment]
Удалось выяснить, что при слиянии (если оно уже работает не корректно) проблемы возникают только с метаданными (реквизиты, объекты и пр.). Код сливается корректно.

**Comment by tretyakevich** [comment]
В логе обнаружены признаки проблемы с хранилищами данных, исправленные в рамках работ по исправлению ошибок снэпшотов конфигурации. Проблема исправлена в 2023.3, рекомендуется проверить сценарий после выхода первой версии 2023.3
