### ISSUE TITLE
Не обновляется окно "Конструктор форматной строки" при переходе на закладку Число, Дата, Булево

### ISSUE THREAD

**Issue by AlexandrKonokhov** [1C-Company/1c-edt-issues#1160]
### Описание ошибки

ошибка в том, что при нажатии на закладке Дата, не появляются данные относящиеся к Дате, по прежнему отображены данные Числа. При попытке сделать скриншот выделенной области, данные обновляются, и по этому попадают на скрин верные. обновляется окно если выбрать закладку, потом установить/снять флаг "язык(Страна)" 

### Как воспроизвести

1. создать отчет
2. создать схему компоновки данных
3. перейти на закладку макеты
4. выбрать любую ячейку и нажать в свойстве "Формат" кнопку "..." 
5. откроется окно "Конструктор форматной строки" который и не обновляется/не переходит на закладки число /дата/булево

### Скриншоты

<img width="1392" alt="Снимок экрана 2023-09-20 в 12 04 13" src="https://github.com/1C-Company/1c-edt-issues/assets/94432667/e9557e87-5b38-4cfb-ac98-a9889f64861b">

### Ожидаемое поведение

ожидается что будет открываться закладка с нужными данными

### Лог рабочей области

[1cedtstart.txt](https://github.com/1C-Company/1c-edt-issues/files/12671315/1cedtstart.txt)

### Версия 1С:EDT

ruby 2023.1.4

### Операционная система

macOS

### Дополнительная информация

macOS Monterey 12.6.9 
Retina (2880 × 1800)

**Comment by tretyakevich** [comment]
Исправлено в 2024.1
