### ISSUE TITLE
Не работает палитра свойств

### ISSUE THREAD

**Issue by unichkin** [1C-Company/1c-edt-issues#1162]
### Описание ошибки

Внезапно перестают отображаться свойства в палитре свойств. Для любых источников - объектов или элементов форм.
Окно свойств начинает выглядеть вот так:
![image](https://github.com/1C-Company/1c-edt-issues/assets/10799597/2adb8224-bc61-4b10-87b9-0e0f4662159e)

Для элементов формы отображается только "Автоотметка неазполненного":
![image](https://github.com/1C-Company/1c-edt-issues/assets/10799597/9e73a66e-c7fe-45b1-9c93-8b56add0ac97)

### Как воспроизвести

В описании

### Ожидаемое поведение

Палитра свойств должна работать

### Лог рабочей области

[Логи.zip](https://github.com/1C-Company/1c-edt-issues/files/12672376/default.zip)

### Версия 1С:EDT

Ruby 2023.1.2

### Операционная система

Windows

**Comment by Erik773** [comment]
Здравствуйте @unichkin!
Подскажите, пожалуйста, пробовали ли вы произвести очистку проекта? Перед возникновением проблемы производилась ли отладка или сравнение/объединение, может быть производились еще какие-то операции? Могли бы вы, пожалуйста, предоставить конфигурацию для воспроизведения проблемы?

**Comment by unichkin** [comment]
Добрый день, очистка не помогает. Проблема возникла спонтанно, непонятно из-за чего. Просто - открыл проект, а в нем вот так. Конфигурацию предоставить не могу, но могу продемонстрировать на экране, если свяжетесь со мной по скайпу - мой логин unichkin.

**Comment by RedMammoth** [comment]
> Добрый день, очистка не помогает. Проблема возникла спонтанно, непонятно из-за чего. Просто - открыл проект, а в нем вот так. Конфигурацию предоставить не могу, но могу продемонстрировать на экране, если свяжетесь со мной по скайпу - мой логин unichkin.

Попробуйте ввести какой-нибудь текс в поиске в панели Свойств и очистить, возможно остался какой-то старый отбор, которого не видно. Заводил на это багу
