### ISSUE TITLE
ВвестиДатуАсинх не определены на web клиенте

### ISSUE THREAD

**Issue by a2080016** [1C-Company/1c-edt-issues#1163]
### Описание ошибки

При вызове метода ВвестиДатуАсинх  ЕДТ ругается, что данный метод не определен на веб клиенте, хотя он там точно есть.
В продолжение к багу https://github.com/1C-Company/1c-edt-issues/issues/783
Возможно остались еще какие-то Асинх функции, все не проверял

### Как воспроизвести

Перейдите в форму
Создайте асинх процедуру на клиенте
Введите **ВведеннаяДата = Ждать ВвестиДатуАсинх(ОбщегоНазначенияКлиент.ДатаСеанса(), "Введите дату аттестации...", ЧастиДаты.Дата);**
ЕДТ выдаст ошибку, что метод не определен

### Скриншоты

![image](https://github.com/1C-Company/1c-edt-issues/assets/24942027/60f8d4e9-bef4-4e0c-9759-c99dcaf3b336)

### Ожидаемое поведение

Метод на клиенте должен быть определен и ошибка проверки отсутствовать

### Лог рабочей области

***

### Версия 1С:EDT

Ruby 2023.1.4

### Операционная система

Windows

### Установленные плагины

1C:Code style V8, 1C:SSL-support

**Comment by a2080016** [comment]
@MaksimDzyuba обратите внимание, был аналогичный баг https://github.com/1C-Company/1c-edt-issues/issues/783

**Comment by MaksimDzyuba** [comment]
Здравствуйте, поправили, войдет в 2023.3, постараемся перенести в 2023.2
