### ISSUE TITLE
Сбрасывается флаг "Вариант использования группировки" в СКД на закладке Настройки - Другие настройки.(вообще походу все флаги сбрасываются)

### ISSUE THREAD

**Issue by AlexandrKonokhov** [1C-Company/1c-edt-issues#1166]
### Описание ошибки

при установки флага "Вариант использования группировки" в значение "дополнительная информация" и дальшейшем запуске 1с  сбрасывается флаг.

### Как воспроизвести

создать любой отчет, в нем создать группировку на закладке настройки и далее в закладке "другие настройки" изменить "Вариант использования группировки" и запустить 1с

### Скриншоты

<img width="1341" alt="Снимок экрана 2023-09-21 в 12 06 30" src="https://github.com/1C-Company/1c-edt-issues/assets/94432667/d6412aee-9187-41bf-aaa7-5e8066378b13">

### Ожидаемое поведение

ожидается что флаг не будет сниматься после запуска 1С=)

### Лог рабочей области

нет так как стартер не работает адеватно на маке почему -то

### Версия 1С:EDT

Ruby 2023.1.4

### Операционная система

macOS

**Comment by MaksimDzyuba** [comment]
Здравствуйте, проблему воспроизвели, поправили, войдет в 2023.3, спасибо большое!
