### ISSUE TITLE
Ошибка при создании базы. (Ошибка сохранения во внутренние хранилище)

### ISSUE THREAD

**Issue by AlexandrKonokhov** [1C-Company/1c-edt-issues#1168]
### Описание ошибки

ошибка возникает когда создаешь пустую базу в edt  в окне "Информационные базы".

### Как воспроизвести

создайте пустую базу  

### Скриншоты

<img width="294" alt="Снимок экрана 2023-09-21 в 14 29 38" src="https://github.com/1C-Company/1c-edt-issues/assets/94432667/e0a9ea4f-8cdc-4b3d-a40b-037124c6e0cd">
<img width="1002" alt="Снимок экрана 2023-09-21 в 14 29 34" src="https://github.com/1C-Company/1c-edt-issues/assets/94432667/fa0e5a3f-f87c-4af1-a09c-80e8b3c3505e">

### Ожидаемое поведение

создать базу без ошибок, так как нет в этой базе ни логина ни пароля, она новая. пустая.

### Лог рабочей области

[1cedtstart.txt](https://github.com/1C-Company/1c-edt-issues/files/12683970/1cedtstart.txt)

### Версия 1С:EDT

ruby 2023.1.4

### Операционная система

macOS

**Comment by Erik773** [comment]
Здравствуйте @AlexandrKonokhov!
Могли бы вы, пожалуйста, приложить логи рабочей области ЕДТ (.log, .bak.log и trace.log в папке \.metadata проекта).
Какие параметры для создания базы были указаны, все по умолчанию? Нет ли проблем с правами доступа к хранилищу, в которое сохраняется база?

**Comment by AlexandrKonokhov** [comment]
[logs.zip](https://github.com/1C-Company/1c-edt-issues/files/12697461/logs.zip)
Добрый день @Erik773 
не знаю это то или нет, нашел тут, за архивировал и приложил к сообщению
<img width="804" alt="Снимок экрана 2023-09-22 в 09 25 31" src="https://github.com/1C-Company/1c-edt-issues/assets/94432667/c55aee8e-abd5-4a22-85a7-3dd1750c69f3">

на винде стартер работает и все найти можно на маке чего то не получается, если зайти в папку где сам проект то там только базы хранятся и логов нет.

**Comment by AlexandrKonokhov** [comment]
@Erik773  вот мои шаги: 
<img width="1298" alt="Снимок экрана 2023-09-22 в 09 05 19" src="https://github.com/1C-Company/1c-edt-issues/assets/94432667/adf517fc-bcab-4459-8072-9eb9e30252cf">
2
<img width="985" alt="Снимок экрана 2023-09-22 в 09 06 25" src="https://github.com/1C-Company/1c-edt-issues/assets/94432667/33edf8cb-7e9d-460c-8f42-0e4c4df83cf1">
3
<img width="978" alt="Снимок экрана 2023-09-22 в 09 06 43" src="https://github.com/1C-Company/1c-edt-issues/assets/94432667/ab037390-a796-4eea-8f13-a069bca6f857">

4
<img width="990" alt="Снимок экрана 2023-09-22 в 09 32 21" src="https://github.com/1C-Company/1c-edt-issues/assets/94432667/357f7f48-d5ea-4259-befd-48a9de3a455f">
5
<img width="992" alt="Снимок экрана 2023-09-22 в 09 32 26" src="https://github.com/1C-Company/1c-edt-issues/assets/94432667/bf82bfcc-61cf-4bea-b16b-e802baef4fa7">
6
<img width="991" alt="Снимок экрана 2023-09-22 в 09 32 32" src="https://github.com/1C-Company/1c-edt-issues/assets/94432667/7ad3ea27-6ce0-44bb-8a86-32b412199c8c">

**Comment by AlexandrKonokhov** [comment]
@Erik773 " Нет ли проблем с правами доступа к хранилищу, в которое сохраняется база?"
Подскажите пожалуйста, что подразумевается под "доступом к хранилищу"? Если Папка в которой создается база, то у меня личный комп, права полные, ограничений ни каких не должно быть.

**Comment by Erik773** [comment]
> не знаю это то или нет, нашел тут, за архивировал и приложил к сообщению
к сожалению, это не логи ЕДТ.  Логи ЕДТ называются ,log и trace.log

> на винде стартер работает и все найти можно на маке чего то не получается, если зайти в папку где сам проект то там только базы хранятся и логов нет.
речь идет про директорию /Applications/1C/1CE ?

>  вот мои шаги:
понятно, спасибо, похоже все по умолчанию

>  Если Папка в которой создается база, то у меня личный комп, права полные, ограничений ни каких не должно быть.
да, речь была про каталог информационной базы

**Comment by AlexandrKonokhov** [comment]
@Erik773 

[trace.log](https://github.com/1C-Company/1c-edt-issues/files/12699536/trace.log)
нашел,  смутило что не было папки metadata  )
на os если папки нет надо нажать  [cmd] + [Shift] + [.]
и папка появится 
<img width="717" alt="Снимок экрана 2023-09-22 в 13 03 52" src="https://github.com/1C-Company/1c-edt-issues/assets/94432667/bcc5e68e-8017-41a3-bdce-4f2b833353fd">

<img width="722" alt="Снимок экрана 2023-09-22 в 13 05 48" src="https://github.com/1C-Company/1c-edt-issues/assets/94432667/068e473d-ef5d-4c64-856b-3adb075f79eb">

**Comment by AlexandrKonokhov** [comment]
случайно нажал)закрыть

**Comment by AlexandrKonokhov** [comment]
@Erik773  ни как не хотел загружаться на сюда, записал в блокнот и закинул
[log.txt](https://github.com/1C-Company/1c-edt-issues/files/12699631/log.txt)

**Comment by Erik773** [comment]
Здравствуйте @AlexandrKonokhov!
Похоже проблема возникает из-за хранилища паролей. 
Вы могли бы, пожалуйста, очистить хранилище паролей и написать, осталась ли проблема?

**Comment by AlexandrKonokhov** [comment]
@Erik773 добрый день, могу, дам знать на выходных. Едт сдохла на маке не хочет открывать проекты , прост в ошибках каких то, придеться переустанавливать , тоже создам еще одну ветку с проблемкой может быть.

**Comment by Erik773** [comment]
Закрыто, так как не предоставлены запрошенные данные для уточнения статуса проблемы.
