### ISSUE TITLE
Ускорить обновление конфигурации при добавлении новых объектов в конфигурацию

### ISSUE THREAD

**Issue by LesN1ck** [1C-Company/1c-edt-issues#1169]
### Описание проблемы

При добавлении в проект новых объектов (например, константы) обновление конфигурации приложения может выполняться гораздо медленнее ожидаемого. Беглый анализ показал, что при инкрементальной выгрузке EDT выгружает гораздо больше файлов, чем указано в списке загрузки. Например, вот так выглядит файл load.lst:

```
Constants\СЛР_КоличествоПопытокОбработкиВходящегоСообщения.xml
Languages\Русский.xml
Languages\Английский.xml
Configuration.xml
CommonModules\СЛР_РегламентныеЗаданияСервер\Ext\Module.bsl
``` 

А в архиве xml.zip при этом еще и выгружается каталог Ext, в котором содержится различная информация, в основном касающаяся корневого элемента конфигурации. Проблема в том, что здесь же содержится подкаталог ParentConfigurations, в котором хранится конфигурация поставщика. И в крупных продуктах (например, ERP) конфигурация поставщика может занимать более 1 гигабайта. Вот так, например, выглядит каталог Ext для нетиповой конфигурации ERP 2.5.8.417:

![image](https://github.com/1C-Company/1c-edt-issues/assets/114978535/a358f023-2f6b-482d-8b2c-0f3badacc5e9)

И этот гигабайт будет гоняться при **каждом** инкрементальном обновлении, затрагивающем файл Configuration.xml, что замедляет процесс обновления.

### Описание решения проблемы

Поскольку файлы, расположенные в каталоге Ext, никак в рассматриваемом примере (что подтверждается версионным контролем Git'а), предлагаю не выгружать их в подобных случаях, а выгружать действительно только измененные файлы. Возможно, здесь есть какие-то ограничения со стороны платформы касательно загрузки конфигурации из файлов XML - тут не уверен, может потребоваться комментарий от тех, кто точно это знает.

**Comment by marmyshev** [comment]
Если ЕДТ не выгрузит каталог EXT - то при загрузке объекта Configuration - всё что было в EXT удалится **Платформой** в конциуграции. Это поведение задокументировано и описано на ИТС в документации платформы.

**Comment by marmyshev** [comment]
Еще можно рассмотреть варианты ведения разработки без конфигураций поставщика в репозитории (см. вебинары на ютубе)

**Comment by LesN1ck** [comment]
> Еще можно рассмотреть варианты ведения разработки без конфигураций поставщика в репозитории (см. вебинары на ютубе)

С удовольствием пользуюсь данным способом, когда не приходится толкаться локтями с тем, кто работает в конфигураторе. Данное обстоятельство накладывает ряд ограничений на организацию работы.
