### ISSUE TITLE
Пропадает кнопка "Добавить в расширение" для значения перечисления

### ISSUE THREAD

**Issue by Stivo182** [1C-Company/1c-edt-issues#1174]
### Описание ошибки

Пропадает кнопка "Добавить в расширение" для значения перечисления

### Как воспроизвести

1. Встать на первое значение перечисления в конфигурации.
2. Нажать ПКМ.
3. Нажать "Добавить в расширение". Первое значение перечисления добавится в расширение.
4. Встать на второе значение перечисления в конфигурации.
5. Нажать ПКМ. Вместо "Добавить в расширение" будет кнопка "Открыть расширяемый объект".

Кнопка "Добавить в расширение" появляется после переключения между окнами

### Скриншоты

![image](https://github.com/1C-Company/1c-edt-issues/assets/24582991/540463f4-49f3-4911-a53d-2f1ee8147107)

### Ожидаемое поведение

Вместо кнопки "Открыть расширяемый объект" должна быть "Добавить в расширение"

### Лог рабочей области

[log.log](https://github.com/1C-Company/1c-edt-issues/files/12718816/log.log)

### Версия 1С:EDT

Ruby 2023.1.4

### Операционная система

Windows

### Установленные плагины

1C:Code style V8, 1C:SSL-support, 1C:Language Tool

**Comment by vadimeg** [comment]
Исправлено в 2023.3
