### ISSUE TITLE
Не работает переключение между локальными ветками

### ISSUE THREAD

**Issue by alexei-mstb** [1C-Company/1c-edt-issues#1178]
### Описание ошибки

Не работает переключение между локальными ветками в EDT 2023.1.4

### Как воспроизвести

1. Создать новый проект EDT. Версия платформы 8.3.22;
2. Создать локальный репозиторий;
3. Сделать новый проект EDT общим (подсоединить к git);
4. Создать новую ветку от master, например dev и переключиться на неё;
5. Перелючиться на master. Должна быть ошибка;

### Скриншоты

![image](https://github.com/1C-Company/1c-edt-issues/assets/53879733/378c749b-cfb2-4fb8-88de-8f4705eec479)
![image](https://github.com/1C-Company/1c-edt-issues/assets/53879733/89a8976f-0188-4dca-9f41-03480cbb5bb9)

### Ожидаемое поведение

Переключение между локальными ветками должно работать без ошибок

### Лог рабочей области

[logEDT.log](https://github.com/1C-Company/1c-edt-issues/files/12747768/logEDT.log)

### Версия 1С:EDT

Ruby 2023.1.4

### Операционная система

Windows, Linux

### Дополнительная информация

Есть способ обхода через консоль: git switch

**Comment by Erik773** [comment]
Здравствуйте @alexei-mstb!
RED OS release MUROM (7.3.3) MINIMAL - не поддерживаемая операционная система.
Вы не пробовали использовать другую ОС? 
Тут вы можете ознакомиться с общими требованиями к программному обеспечению и поддерживаемыми ОС https://edt.1c.ru/docs/intro/requirements.php

**Comment by alexei-mstb** [comment]
Ошибку ранее фиксировали и под ОС Windows, что отражено в теге бага. В ближайшее время постараюсь её воспроизвести.

**Дополнительное описание для воспроизведения:**

Ошибка происходит при двойном нажатии левой кнопкой мышки на имени ветки (check out):
![image](https://github.com/1C-Company/1c-edt-issues/assets/53879733/2c2a546a-884d-4123-8116-e905449fbd16)

Если выбирать пункт меню "Извлечь", то переключение проиходит без ошибки:
![image](https://github.com/1C-Company/1c-edt-issues/assets/53879733/a6ee2864-b309-4945-9b11-b70982b3e299)

**Comment by Erik773** [comment]
Если получится воспроизвести на Windows, приложите, пожалуйста, логи рабочей области Windows.
И еще было бы полезно посмотреть ваши настройки пользователя git и настройки репозитория (Окно -> Параметры -> Групповая разработка -> Git -> Конфигурация -> Настройки пользователя, Настройки репозитория), их можно предоставит скриншотом.

**Comment by alexei-mstb** [comment]
Пусто:
![image](https://github.com/1C-Company/1c-edt-issues/assets/53879733/a60a7aa0-fd1b-4d69-a193-236dc2eae659)

**Comment by alexei-mstb** [comment]
Под Windows воспроизвести не удалось, воспроизвел под Ubuntu:
Operating System: Ubuntu 22.04.2 LTS              
Kernel: Linux 5.15.0-76-generic

![image](https://github.com/1C-Company/1c-edt-issues/assets/53879733/336c70cd-860a-42d1-a502-4a36adda1c27)

Возможно проблема в том, что EDT не может инициализировать системные настройки Git?
![image](https://github.com/1C-Company/1c-edt-issues/assets/53879733/953f6ddf-3085-441f-a786-37de4e6d09fc)

Установку делал через:
sudo ./1ce-installer-cli install  --ignore-signature-warnings

**Comment by alexei-mstb** [comment]
Не работает именно по двойному щелчку и в RedOS и в Ubuntu

При этом работает через меню "Переключить на" в обоих системах:
![image](https://github.com/1C-Company/1c-edt-issues/assets/53879733/f0dd7fe8-e7db-488e-9c87-dd84d5dd4ec6)

**Comment by tretyakevich** [comment]
Добрый день. Проверьте, пожалуйста, на версии EDT 2023.2.1 - в данные диалоги вносились правки.
