### ISSUE TITLE
Поиск по конфигурации не ищет в текстовых макетах

### ISSUE THREAD

**Issue by DmitryShvaika** [1C-Company/1c-edt-issues#118]
### Описание ошибки

Пытаюсь найти фразу, но поиск по конфигурации не выдает в результаты поиска текстовые макеты, в которых эта фраза присутствует.

### Как воспроизвести

[test.zip](https://github.com/1C-Company/1c-edt-issues/files/7566302/test.zip)
[EDT-test.zip](https://github.com/1C-Company/1c-edt-issues/files/7566317/EDT-test.zip)

1. Загрузите пример из test.zip (выгрузка информационной базы) или EDT-test.zip (архив проекта)
2. Попробуйте сделать поиск по конфигурации по фразе "ФразаПоиска"
3. В результатах поиска не увидите макета справочника, хотя фраза поиска в нем присутствует

### Скриншоты

![image](https://user-images.githubusercontent.com/54451084/142504413-fa5f7af5-ca4b-4817-a0f7-5e94c4a1e232.png)

### Ожидаемое поведение

Поиск по конфигурации должен выдавать в результатах поиска текстовые макеты то же.

### Лог рабочей области

[логи.zip](https://github.com/1C-Company/1c-edt-issues/files/7566327/default.zip)

### Версия 1С:EDT

Ruby 2021.2.10

### Операционная система

Windows

### Установленные плагины

1C:Code style V8, 1C:SSL-support

**Comment by tretyakevich** [comment]
Исправлено в 2022.2
