### ISSUE TITLE
Не работает переключение между закладками

### ISSUE THREAD

**Issue by shcherbakov-vadim** [1C-Company/1c-edt-issues#1182]
### Описание ошибки

Если у объекта метаданный больше 1 макета табличного документа перестает работать переключение между закладками

### Как воспроизвести

1. Создать объект метаданных Справочник
2. Добавить Форму элемента по умолчанию
3. Добавить макет табличного документа
4. Добавить макет табличного документа
5. Убедиться, что при выборе макетов или формы в дереве метаданных не происходит переключение на них

### Ожидаемое поведение

При выборе макетов или формы в дереве метаданных происходит переключение на них

### Лог рабочей области

Нет

### Версия 1С:EDT

2023.1.4

### Операционная система

Linux, Windows

### Дополнительная информация

В 2022.2.5 такой ошибки нет

**Comment by shcherbakov-vadim** [comment]
Почему низкий приоритет, тут явный регресс по сравнению с версией 2022.2.5?

**Comment by dsavenko** [comment]
Ошибка также воспроизводится в версии 2022.2.5.
