### ISSUE TITLE
Отсутсвует возможность удаления EDT через ./1ce-installer-cli uninstall в ОС Linux

### ISSUE THREAD

**Issue by alexei-mstb** [1C-Company/1c-edt-issues#1184]
### Описание ошибки

Отсутсвует возможность удаления EDT через ./1ce-installer-cli uninstall в ОС Linux (RedOS 7.3).

### Как воспроизвести

1. Проверяю установку EDT:
**ring help**
_Доступные модули:
edt@2023.1.4:x86_64 - 1C:Enterprise Development Tools Ring Cli_

**ring  edt@2023.1.4:x86_64 locations list**

/opt/1C/1CE/components/1c-edt-2023.1.4+1-x86_64 

2. Распаковываю дистрибутив 1c_edt_distr_offline_2023.1.4_1_linux_x86_64.tar.gz. 
Проверяю версию:
s**udo ./1ce-installer-cli query**

_id: 1c-edt-product-offline
version: 2023.1.4+1
arch: x86_64
components:
- 1c-enterprise-ring@0.11.10+2
- 1c-edt-start@0.7.0+180
- 1c-edt@2023.1.4+1_

3. Пытаюсь удалить:

**sudo ./1ce-installer-cli uninstall 1c-edt@2023.1.4**

Произошла ошибка при выполнении команды.
причина: Не найден установленный продукт, идентификатор продукта: "1c-edt", версия: "2023.1.4".

**sudo ./1ce-installer-cli uninstall 1c-edt@2023.1.4+1**
Произошла ошибка при выполнении команды.
причина: Не найден установленный продукт, идентификатор продукта: "1c-edt", версия: "2023.1.4+1".
 
4. Пытаюсь удалить через инсталлер в /opt

**sudo /opt/1C/1CE/components/1c-enterprise-installer-1.12.7+10-x86_64/1ce-installer-cli query**
Произошла ошибка при выполнении команды.
причина: Директория "/opt/1C/1CE/components/1c-enterprise-installer-1.12.7+10-x86_64" не является директорией дистрибутива.

**sudo /opt/1C/1CE/components/1c-enterprise-installer-1.12.7+10-x86_64/1ce-installer-cli uninstall 1c-edt@2023.1.4**
Произошла ошибка при выполнении команды.
причина: Не найден установленный продукт, идентификатор продукта: "1c-edt", версия: "2023.1.4".

**sudo /opt/1C/1CE/components/1c-enterprise-installer-1.12.7+10-x86_64/1ce-installer-cli uninstall 1c-edt@2023.1.4+1**
Произошла ошибка при выполнении команды.
причина: Не найден установленный продукт, идентификатор продукта: "1c-edt", версия: "2023.1.4+1".

### Скриншоты

нет

### Ожидаемое поведение

Удаление EDT возможно через скрипт, который установлен в системе.
Например:
/opt/1C/1CE/components/uninstaller-cli

### Лог рабочей области

нет

### Версия 1С:EDT

Ruby 2023.1.4

### Операционная система

Linux

### Дополнительная информация

Обходное решение:
Удаление неактуальных версий через rm-rf в каталогах /opt/1C/1CE/ и /etc/1C/1CE/

**Comment by alexei-mstb** [comment]
Добрый день, @Erik773!
у меня описана проблема удаления старых версий EDT, а не проблема описанная по ссылке: "Удаление установленного **Установщика**"

На примере EDT 2023.1.4:
мне нужно удалить продукты:
1c-edt-2023.1.4+1-x86_64/
1c-edt-start-0.7.0+180-x86_64/
по ссылке решенее для:
1c-enterprise-installer-1.12.7+10-x86_64

Оффтоп:
в документации ИТС опечатка в слове installer (выделил ниже):
1c-enterprise-**insteller**-<версия>-<архитектура>
https://its.1c.ru/db/inst10doc#content:10038:hdoc

**Comment by Erik773** [comment]
Здравствуйте @alexei-mstb!
Удалить можно только продукты в терминах Установщика, но не отдельные компоненты.
А так как производится попытка удалить компонент, от этого и возникает ошибка.
Вот ваш вывод списка продуктов:
```
_id: 1c-edt-product-offline
version: 2023.1.4+1
arch: x86_64
components:
- 1c-enterprise-ring@0.11.10+2
- 1c-edt-start@0.7.0+180
- 1c-edt@2023.1.4+1_
```
В этом списке:
1c-edt-product-offline - это продукт.
1c-edt-start и 1c-edt - это компоненты этого продукта (из которых состоит этот продукт).
Нельзя удалить компонент продукта отдельно от продукта, т.к. это неотъемлемая его часть.
Можно удалить только продукт целиком (1c-edt-product-offline).

**Comment by alexei-mstb** [comment]
@Erik773 спасибо!

Команда для удаления:
sudo ./1ce-installer-cli uninstall 1c-edt-product-offline@2023.1.4+1

**Comment by alexei-mstb** [comment]
@Erik773 спасибо!

Команда для удаления:
sudo ./1ce-installer-cli uninstall 1c-edt-product-offline@2023.1.4+1
