### ISSUE TITLE
В Расширении отсутствуют реквизиты объекта.

### ISSUE THREAD

**Issue by Roffild** [1C-Company/1c-edt-issues#1185]
Когда "Добавить в расширение" использовать, например, на ПередЗаписью(), тогда создаются в самом расширении копия Справочника без реквизитов. Это НОРМАЛЬНО.

Проблемы начинаются при редактировании кода, например, Обработки. ЕДТ знает только о стандартных реквизитах Справочника, а реквизиты из Конфигурации уже не видит "Свойство (метод) объекта не обнаружено [Сервер]".

Ruby 2023.1.1

**Comment by Erik773** [comment]
Здравствуйте @Roffild!

> Когда "Добавить в расширение" использовать, например, на ПередЗаписью()

Могли бы Вы, пожалуйста, подробнее описать каким образом производится заимствование объекта в расширение и что значит "на ПередЗаписью()".

> Проблемы начинаются при редактировании кода, например, Обработки. ЕДТ знает только о стандартных реквизитах Справочника, а реквизиты из Конфигурации уже не видит "Свойство (метод) объекта не обнаружено [Сервер]".

Если возможно, приложите, пожалуйста, скриншот для лучшего понимания проблемы и логи рабочей области ЕДТ.

**Comment by Roffild** [comment]
![bug](https://github.com/1C-Company/1c-edt-issues/assets/38705255/bb3aff9e-c2d3-4d8e-8855-634a301c74e1)

СантехникСервер - модуль в расширении, код которого на скрине, но ЕДТ "Переменная 'СантехникСервер' не определена [Толстый клиент (управляемое приложение)]".

Обычное переопределение события ПередЗаписью() в расширении.

**Comment by DmitryShvaika** [comment]
Все правильно вроде. Подчеркнутые реквизиты необходимо перенести в расширение просто. Конфигуратор при включенном контроле так же выдает ошибку на них.

**Comment by tretyakevich** [comment]
В данный момент проблема как таковая нерешаема без рассинхронизации с поведением платформы при работе с расширениями. Варианты работы в режиме симуляции неявного объединения с базовой конфигурацией и другими расширениями рассматриваются, но пока задача еще не запланирована.
