### ISSUE TITLE
Невозможно работать начиная с версии 2023.1.4 из-за очень сильного замедления операций по импорту изменений

### ISSUE THREAD

**Issue by Nullarity** [1C-Company/1c-edt-issues#1186]
### Описание ошибки

Импорт конфигурации в новую рабочую область, импорт изменений конфигурации, полное обновление конфигурации, все эти операции выполняются на версиях 2023.1.4+1 и 2023.2.0+436 на порядки медленнее, чем на версиях 2022.2.5+10 включительно.

### Как воспроизвести

Например, импорт конфигурации собственной разработки размером 16мб, занимает 40 секунд на компьютере i9-13900k, 64gb, ssd. В тех же условиях, в версии 2023.1.4+1 и выше, тот же импорт занимает уже около 10+ минут. Процесс успешно завершается, но все подпроцессы (в edt, в окне Progress), происходят визуально очень медленно. Учитывая, что нам часто приходится подгружать изменения, выполненные в конфигураторе, проблема для нас критичная, так как не ограничивается только замедлением первоначального импорта.

На компьютере установлена рекомендуемая жава, конфигурационные файлы 1cedt.ini одинаковые. Испытывались следующие версии платформ (и в файловом и клиент-серверном вариантах. с измененным режимом совместимости и без): 8.3.22.1923, 8.3.23.1865, 8.3.23.1912.

### Ожидаемое поведение

Приемлемая скорость работы.

### Лог рабочей области

[logs.zip](https://github.com/1C-Company/1c-edt-issues/files/12785041/logs.zip)

### Версия 1С:EDT

2023.1.4

### Операционная система

Linux

### Установленные плагины

Нет плагинов

**Comment by adminimusRU** [comment]
Судя по логу последний импорт проекта прошел примерно за минуту

**Comment by Nullarity** [comment]
Возможно тут путаница в терминологии, я имел ввиду "Импорт" как функцию среды (Import configuration and extensions from infobase), а не под-процесс. После процесса импорта, выполняется еще ряд процессов, во время которых, работать теоретически можно, а практически нет.

**Comment by Erik773** [comment]
Здравствуйте @Nullarity!
Были добавлены объемные проверки "bsl-ql-hub" и "redundant-export-method", они занимают много времени и по умолчанию они должны быть выключены. Посмотрите, пожалуйста, активны ли у вас в проекте эти проверки (Проект → Свойства → V8 → Валидация)?

**Comment by Nullarity** [comment]
@Erik773 Информация во вложениях. Не весь, но частично процесс очистки проекта записал на видео. Касательно проверок, у нас их не много, но обратите внимание, что только процедура импорта файлов занимает 1м.10с, в то время как вся очистка проекта в 2022.2.5+10 выполнялась за 40 секунд.

https://github.com/1C-Company/1c-edt-issues/assets/28710693/f5652c44-c270-4d7a-bfe2-9f05a038095d
https://github.com/1C-Company/1c-edt-issues/assets/28710693/8fc26b1d-e070-4a9e-8463-caa4af28ec4a
https://github.com/1C-Company/1c-edt-issues/assets/28710693/1bfe3e8f-0434-4094-a368-1ff925b13034
https://github.com/1C-Company/1c-edt-issues/assets/28710693/cbc611cd-3777-4b35-8c28-b633a9cd1101
[checks.cset.txt](https://github.com/1C-Company/1c-edt-issues/files/12793006/checks.cset.txt)
[process.mp4.zip](https://github.com/1C-Company/1c-edt-issues/files/12793007/process.mp4.zip)

**Comment by Erik773** [comment]
@Nullarity, Linux Mint 21.2 Victoria (victoria) не является поддерживаемой ОС, поэтому тестирование производительности на ней производилось, Вы могли бы, пожалуйста, сделать снимки увеличившихся по длительности процессов с помощью YourKit или любого другого удобного для вас инструмента профилирования.  Это поможет быстрее и точнее локализовать проблему.

**Comment by Erik773** [comment]
Могли бы вы предоставить нам конфигурацию для воспроизведения проблемы?
Похоже есть проблемы с проверками, но для более точного понимания нужно больше данных.

Также рекомендуем попробовать отключить проверку на экспортные методы (код проверки "redundant-export-method") и посмотреть изменится ли ситуация с длительностью процессов импорта.

**Comment by Nullarity** [comment]
@Erik773 Подскажите пожалуйста, вы писали:

> Linux Mint 21.2 Victoria (victoria) не является поддерживаемой ОС

Хочется уточнить, в списке поддерживаемых ОС mint есть:

![image](https://github.com/1C-Company/1c-edt-issues/assets/28710693/aa0fbc2e-0e72-416e-8123-a93b8d19c9b8)

А списке ОС для едт нет:

![image](https://github.com/1C-Company/1c-edt-issues/assets/28710693/9fe26acf-9bbc-4d13-bfce-b947cdddec07)

Я правильно понимаю, что стабильная работа едт в линуксе, гарантируется только на убунте?

> Также рекомендуем попробовать отключить проверку на экспортные методы (код проверки "redundant-export-method") и посмотреть изменится ли ситуация с длительностью процессов импорта.

Стало чуть шустрее, но ситуация существенно не изменилась.

[Конфигурация](https://github.com/1C-Company/1c-edt-issues/files/12803861/1Cv8.cf.zip)

**Comment by Erik773** [comment]
> Я правильно понимаю, что стабильная работа едт в линуксе, гарантируется только на убунте?

На ОС, не указанных на странице https://edt.1c.ru/docs/intro/requirements.php, тестирование не производилось, поэтому могут быть проблемы специфичные для этих ОС.
Но по последним данным при работе на Linux Mint проблем с производительностью не возникало, похоже, что причина не в ОС.
Благодарим за предоставленную конфигурацию, это позволит точнее и быстрее локализовать проблему. 

> Стало чуть шустрее, но ситуация существенно не изменилась.

Еще можете, пожалуйста, попробовать отключить проверку с кодом "bsl-ql-hub" и написать ускорились ли процессы сопровождающие сборку?

**Comment by Nullarity** [comment]
> Еще можете, пожалуйста, попробовать отключить проверку с кодом "bsl-ql-hub" и написать ускорились ли процессы сопровождающие сборку?

У меня вся группа проверок Query language checks, включая bsl-ql-hub, была отключена изначально (отражено на скринах первого сообщения)

**Comment by Erik773** [comment]
@Nullarity, к сожалению, не удается воспроизвести проблему с производительностью импорта и обновления на предоставленной вами конфигурации на версиях ЕДТ 2023.2.0+436 и платформы 8.3.23.1912. 

https://github.com/1C-Company/1c-edt-issues/assets/93516265/bc30d02b-3c59-483a-8170-40f20c48a235

Могли бы вы, пожалуйста, попробовать воспроизвести сценарии работы с конфигурацией на новой рабочей области и написать, останутся ли проблемы с производительностью?
Есть ли у вас возможность предоставить доступ к окружению для исследования причин возникновения проблем с производительностью в ЕДТ?

**Comment by Nullarity** [comment]
@Erik773 Смотрю ваше видео, и аж завидно.

Вот что у меня, 2023.2.0+436, со скоростью раненой улитки (видео обрезал):

https://github.com/1C-Company/1c-edt-issues/assets/28710693/b2dabc9f-626a-4829-ab51-95bb82379b92

И тоже самое на 2022.2.5:


https://github.com/1C-Company/1c-edt-issues/assets/28710693/6139f88f-0135-4602-94ff-f4f95bb1312c

**Comment by Nullarity** [comment]
@Erik773 

> Есть ли у вас возможность предоставить доступ к окружению для исследования причин возникновения проблем с производительностью в ЕДТ?

да

**Comment by Nullarity** [comment]
@Erik773 для информации: в версии 2023.2.1 всё также медленно, без изменений.

**Comment by adminimusRU** [comment]
@Nullarity 
> Вот что у меня, 2023.2.0+436, со скоростью раненой улитки (видео обрезал):

а посмотрите загрузку процессора во время импорта, такое ощущение что на 2023 у вас включено ограничение на количество используемых потоков через параметр DcoreLimit.

**Comment by Nullarity** [comment]
@adminimusRU 

> а посмотрите загрузку процессора во время импорта, такое ощущение что на 2023 у вас включено ограничение на количество используемых потоков через параметр DcoreLimit.

Я тоже обратил на это внимание. Вот что происходит в 2022:

`/usr/bin/java -Dosgi.requiredJavaVersion=11 --add-modules=ALL-SYSTEM -XX:+UseG1GC -XX:+UseStringDeduplication -Xms80m -Dlog4j.configuration=platform:/plugin/com._1c.g5.v8.dt.logging/log4j.properties -Dlog4j.formatMsgNoLookups=true -Dlog4j2.formatMsgNoLookups=true -Dorg.osgi.framework.bundle.parent=ext -Dosgi.module.lock.timeout=240 -De1c.dt.monitoring.host=https://pult.1c.ru/ -DmigrationEnabled=true -DmigrationNotificationEnabled=true -server -Dosgi.debug=.options -Xmx4096m -jar /opt/1C/1CE/components/1c-edt-2022.2.5+10-x86_64//plugins/org.eclipse.equinox.launcher_1.6.400.v20210924-0641.jar -os linux -ws gtk -arch x86_64 -showsplash /opt/1C/1CE/components/1c-edt-2022.2.5+10-x86_64//plugins/com._1c.g5.v8.dt.product.application_1.27.5.10/splash.bmp -launcher /opt/1C/1CE/components/1c-edt-2022.2.5+10-x86_64/1cedt -name 1cedt --launcher.library /opt/1C/1CE/components/1c-edt-2022.2.5+10-x86_64//plugins/org.eclipse.equinox.launcher.gtk.linux.x86_64_1.2.400.v20211117-0650/eclipse_11600.so -startup /opt/1C/1CE/components/1c-edt-2022.2.5+10-x86_64//plugins/org.eclipse.equinox.launcher_1.6.400.v20210924-0641.jar --launcher.overrideVmargs -exitdata 1e80a7 -vm /usr/bin/java -vmargs -Dosgi.requiredJavaVersion=11 --add-modules=ALL-SYSTEM -XX:+UseG1GC -XX:+UseStringDeduplication -Xms80m -Dlog4j.configuration=platform:/plugin/com._1c.g5.v8.dt.logging/log4j.properties -Dlog4j.formatMsgNoLookups=true -Dlog4j2.formatMsgNoLookups=true -Dorg.osgi.framework.bundle.parent=ext -Dosgi.module.lock.timeout=240 -De1c.dt.monitoring.host=https://pult.1c.ru/ -DmigrationEnabled=true -DmigrationNotificationEnabled=true -server -Dosgi.debug=.options -Xmx4096m -jar /opt/1C/1CE/components/1c-edt-2022.2.5+10-x86_64//plugins/org.eclipse.equinox.launcher_1.6.400.v20210924-0641.jar`

https://github.com/1C-Company/1c-edt-issues/assets/28710693/e6eadab1-e60d-4c4b-8bad-79d8d818599d

И вот что в 2023:

`/usr/bin/java -Dosgi.requiredJavaVersion=11 --add-modules=ALL-SYSTEM -XX:+UseG1GC -XX:+UseStringDeduplication -Xms80m -Dlog4j.configuration=platform:/plugin/com._1c.g5.v8.dt.logging/log4j.properties -Dlog4j.formatMsgNoLookups=true -Dlog4j2.formatMsgNoLookups=true -Dorg.osgi.framework.bundle.parent=ext -Dosgi.module.lock.timeout=240 -De1c.dt.monitoring.host=https://pult.1c.ru/ -DmigrationEnabled=true -DmigrationNotificationEnabled=true -server -Dosgi.debug=.options -Xmx4096m -jar /opt/1C/1CE/components/1c-edt-2023.2.1+11-x86_64//plugins/org.eclipse.equinox.launcher_1.6.400.v20210924-0641.jar -os linux -ws gtk -arch x86_64 -showsplash /opt/1C/1CE/components/1c-edt-2023.2.1+11-x86_64//plugins/com._1c.g5.v8.dt.product.application_1.29.1.11/splash.bmp -launcher /opt/1C/1CE/components/1c-edt-2023.2.1+11-x86_64/1cedt -name 1cedt --launcher.library /opt/1C/1CE/components/1c-edt-2023.2.1+11-x86_64//plugins/org.eclipse.equinox.launcher.gtk.linux.x86_64_1.2.400.v20211117-0650/eclipse_11600.so -startup /opt/1C/1CE/components/1c-edt-2023.2.1+11-x86_64//plugins/org.eclipse.equinox.launcher_1.6.400.v20210924-0641.jar --launcher.overrideVmargs -exitdata 268019 -vm /usr/bin/java -vmargs -Dosgi.requiredJavaVersion=11 --add-modules=ALL-SYSTEM -XX:+UseG1GC -XX:+UseStringDeduplication -Xms80m -Dlog4j.configuration=platform:/plugin/com._1c.g5.v8.dt.logging/log4j.properties -Dlog4j.formatMsgNoLookups=true -Dlog4j2.formatMsgNoLookups=true -Dorg.osgi.framework.bundle.parent=ext -Dosgi.module.lock.timeout=240 -De1c.dt.monitoring.host=https://pult.1c.ru/ -DmigrationEnabled=true -DmigrationNotificationEnabled=true -server -Dosgi.debug=.options -Xmx4096m -jar /opt/1C/1CE/components/1c-edt-2023.2.1+11-x86_64//plugins/org.eclipse.equinox.launcher_1.6.400.v20210924-0641.jar`

https://github.com/1C-Company/1c-edt-issues/assets/28710693/7c04aa0e-4c8e-4ae1-b0c7-c28ac21f80e7

Как видно, версия 2023 не загружает так процессор, как 2022. Пробовал играться с параметром DcoreLimit, без видимых изменений.

**Comment by Nullarity** [comment]
@tretyakevich подскажите пожалуйста, можно ли эту проблему как-то временно обойти?

**Comment by tretyakevich** [comment]
Пока не получается воспроизвести подобное поведение, поэтому в первую очередь под подозрением конкретная специфика хоста. Из возможных вариантов:
1. Неправильный репортинг количества доступных ядер Java-ой (в этом случае в EDT используется заглушка с мин. количеством потоков). 
2. Малый объем памяти (плюс пункт 1) - для теста можно попробовать поставить 12Гб heap-а (-Xmx12g) и проверить - увеличиться ли утилизация процессора
3. По каким-то причинам шедулер ОС решил бросить процессор EDT на энергоэффективные ядра вместо производительных (для проверки данной теории можно попробовать установить affinity на производительные ядра, они там по виду 0,2,4,.... , через taskset или аналоги
4. Какая-то особенность дисковой подсистемы, и изменившийся движок EDT по каким-то причинам тормозит на ней (ранее это были MMAP-файлы, теперь схема другая) - но это маловероятно.

**Comment by Nullarity** [comment]
Спасибо за информацию.

> Неправильный репортинг количества доступных ядер Java-ой (в этом случае в EDT используется заглушка с мин. количеством потоков).

Я написал маленькую программку:

```
public class CoreCounter {
    public static void main(String[] args) {
        Runtime runtime = Runtime.getRuntime();
        int numberOfCores = runtime.availableProcessors();
        System.out.println("Number of available cores: " + numberOfCores);
    }
}
```
Выдает 32.

> Малый объем памяти (плюс пункт 1) - для теста можно попробовать поставить 12Гб heap-а (-Xmx12g) и проверить - увеличиться ли утилизация процессора

Я игрался с этим параметром, не помогает. Да и мы говорим о конфигурации размером 16мб.
Последние два пункта кажутся совсем уж маловероятными, ведь судя по всему едт просто не утилизирует весь процессов, а не только энергонезависимые.

Я могу что-то ещё проверить? Дело в том, что на машине нет никакой экзотики или тюнинга, даже видео-карты нет. Проц, мама, память, диск, типовая установка линукс, всё. Есть vscode, clion, но оба работают нормально.

**Comment by tretyakevich** [comment]
Как вариант - снять несколько stack-trace-ов (jstack) во время импорта файлов, билда модулей и полной проверки.
Как минимум по составу потоков посмотрим, сколько активных потоков и каких работает.

Далее уже только профайлинг, но там уже не все просто

**Comment by regniws** [comment]
Подтяну к теме историю в телеграм. Такая же проблема, при очистке и пересборке проекта. 
На убунту 22.04, 23.10 с EDT 2023.*  наблюдается замедление в 4 раза по отношению к Win11 и Mint. 
В поисках проблемы, все ОС переустановлены через "далее-далее" + JRE + EDT, даже без платформы. 

https://t.me/e1c_edt/86255

**Comment by tretyakevich** [comment]
По Линуксу - есть много вопросов, и не только от EDT.  До сих пор разбираемся с одной очень интересной ситуацией, и пока все весьма неординарно, и тоже на мощном железе.
В ходе этого дела испытали Java Flight Recorder в продукционном цикле - и оно вполне подъемно, и дает много нужной информации.

Поэтому предлагаю при возникновении такой проблемы попробовать собрать результат профайлинга:

1. Разместить на агенте/по какому-то общему пути файл настроек профилирования (присоединенный к письму файл profiling-light.jfc). Стандартное размещение: <каталог установки JDK>/lib/jfr (в этом случае в параметрах запуска не нужно указывать полный путь к профилю. При размещении в другом месте - просто необходимо указать полный абсолютный путь к файлу настроек профиля).
2. Добавить в параметры запускаемого процесса (параметры Java для ring CLI, параметры Java для EDT CLI, 1cedt.ini или любыми другими средствами) настройки запуска JFR:
-XX:StartFlightRecording=settings=profiling-light.jfc,filename=X:\\resultDir\,maxsize=10g -XX:FlightRecorderOptions=stackdepth=1024,repository=X:\\resultDir\repo\
Где: 

- settings=profiling-light.jfc - это выбор файла настроек профилирования. Допускает указание абсолютного пути в формате Windows или Linux (зависит от целевой ОС)
- filename=X:\\resultDir\ - это каталог, в который будет помещен конечный результат,  в виде файла вида hotspot-pid-3128-id-1-2023_12_11_09_49_47.jfr  (где закодированы идентификатор процесса в ОС, дата и время). Данный файл записывается в случае, если произошел нормальный shutdown процесса Java. Важно: каталог должен быть создан до старта профайлинга, в противном случае вместо записи в каталог будет создан файл с именем resultDir. Также важно указания слэша (прямого или обратного, зависит от ОС) для указания того, что это каталог для размещения результатов, а не имя файла
- repository=X:\\resultDir\repo\ - это каталог для записи временных фрагментов профиля (размером по 24Мб). При нормальном завершении процесса данные файлы удаляются профайлером, и результат сохраняется в resultDir. В случае, если процесс был завершен аварийно (принудительно, например) - то эти файлы могут быть использованы для анализа ситуацию, предшествующей завершению, каждый из них является полноценным профилем. Правила указания имени - такие же, как и для filename=

**Comment by tretyakevich** [comment]
Дополнительная информация по возможным причинам данных торможений. В ходе исследования сходных ситуаций выяснили, что EDT уязвима к излишне агрессивному переключению контекстов процессов операционной системой (причина - огромное количество мелких операций чтения во время массовых расчетов, таких как проверки, сборка языковых данных и т.п.). Кроме того, эта же особенность иногда мешает операционной системе считать расчетные потоки EDT высоконагруженными, поэтому она с удовольствием перекидывает их на HT-огрызки уже занятых работой ядер, либо на энергоэффективные ядра (особенно хорошо поведение заметно на Windows 11).

В данных случаях заметно помогает поднятие приоритета процесса EDT в операционной системе. В данный момент мы рассматриваем ряд изменений в EDT для того, чтобы уменьшить количество поводов ОС для излишнего переключения контекстов.

**Comment by Nullarity** [comment]
К сожалению, повышение до максимума приоритета процесса, у меня к ускорению не приводит. Все как и раньше, загрузка цп более 2.5 процента не происходит. Очистка проекта конфигурации размером 16 мб, с выключенными проверками, всё также занимает 10+ минут.

![image](https://github.com/1C-Company/1c-edt-issues/assets/28710693/531cc785-3065-4c08-a75d-d224829223a1)

@regniws Подскажите пожалуйста, как вам удалось повысить скорость работы?

**Comment by regniws** [comment]
> @regniws Подскажите пожалуйста, как вам удалось повысить скорость работы?

Я в рамках своих способностей поресёрчил этот вопрос поле сообщения выше, но мне ничего не помогло снова. Обратно упаковался на win11, к сожалению.

**Comment by regniws** [comment]
Как минимум я попытался проверить гипотезу и отключил все Intel-E ядра, чтобы остались только полноценные куски, но никакого эффекта ровным счётом.

**Comment by tretyakevich** [comment]
Переношу задачу на 2024.1 (по времени, поскольку в 2023.3, очевидно, решения не нашли).
Пока из оставшихся предложений - все же попробовать запустить профайлинг (предложение выше), готов оказать содействие если инструкция не до конца понятна.
По результатам профайлинга, по крайней мере, можно будет определить те процессы EDT, картина выполнения которых заметно расходится с референсными прогонами.

**Comment by regniws** [comment]
> Переношу задачу на 2024.1 (по времени, поскольку в 2023.3, очевидно, решения не нашли). Пока из оставшихся предложений - все же попробовать запустить профайлинг (предложение выше), готов оказать содействие если инструкция не до конца понятна. По результатам профайлинга, по крайней мере, можно будет определить те процессы EDT, картина выполнения которых заметно расходится с референсными прогонами.

[hotspot-pid-32366-id-1-2024_02_01_17_19_25.zip](https://github.com/1C-Company/1c-edt-issues/files/14126619/hotspot-pid-32366-id-1-2024_02_01_17_19_25.zip)

Собрал профайлинг. Пишите, если что-то собрано не так, в кратчайшие сроки пересоберу.

**Comment by tretyakevich** [comment]
> > Переношу задачу на 2024.1 (по времени, поскольку в 2023.3, очевидно, решения не нашли). Пока из оставшихся предложений - все же попробовать запустить профайлинг (предложение выше), готов оказать содействие если инструкция не до конца понятна. По результатам профайлинга, по крайней мере, можно будет определить те процессы EDT, картина выполнения которых заметно расходится с референсными прогонами.
> 
> [hotspot-pid-32366-id-1-2024_02_01_17_19_25.zip](https://github.com/1C-Company/1c-edt-issues/files/14126619/hotspot-pid-32366-id-1-2024_02_01_17_19_25.zip)
> 
> Собрал профайлинг. Пишите, если что-то собрано не так, в кратчайшие сроки пересоберу. Включает запуск, собрка, очистка, сборка.


Большое спасибо, кратко пробежался по профайлу - картина действительно крайне сильно отличается от типовой, в т.ч. типовой для Linux-ов. Будем разбираться.

**Comment by Alfair** [comment]
> 1. Неправильный репортинг количества доступных ядер Java-ой (в этом случае в EDT используется заглушка с мин. количеством потоков).
Сейчас тоже занимаюсь анализом быстродействия работы EDT в разных конфигурациях сред. Уточните, пожалуйста, что за "заглушка с минимальным количеством потоков"? В каких случаях она применяется, и какое ограничение выставляет?
Вопрос возник из-за того, что возникли странности с изменением параметра DCoreLimit -- такое ощущение что его значения >8 не имеют смысла (на моём тестовом стенде), т.к. соразмерного увеличения общей загрузки процессора не наблюдается.

**Comment by grumagargler** [comment]
В моём случае, помогло отключение `split_lock_detect` в конфигурации ядра. Можно сделать через изменение параметра `GRUB_CMDLINE_LINUX_DEFAULT` в `/etc/default/grub`. Например, у меня он выглядит так:

![image](https://github.com/1C-Company/1c-edt-issues/assets/15623029/de8d0ff7-ae95-4d68-a81d-2ee854daaab0)

Нужно сделать примерно следующее:

```
sudo vim /etc/default/grub
<внести изменения>
sudo update-grub
sudo shutdown -r now
```

**Comment by regniws** [comment]
> В моём случае, помогло отключение `split_lock_detect` в конфигурации ядра. Можно сделать через изменение параметра `GRUB_CMDLINE_LINUX_DEFAULT` в `/etc/default/grub`. 

Мне помогло описанным путём, всё прям хорошо. Теперь разобраться, как этот ключ аффектит на другие приложения. Беглое описание ключа в ядре мне ничего не сказало...

**Comment by grumagargler** [comment]
> Теперь разобраться, как этот ключ аффектит на другие приложения. Беглое описание ключа в ядре мне ничего не сказало...

Никак не должно, чуть подробней тут: https://www.kernel.org/doc/html/v5.18/x86/buslock.html#
Смысл этой опции, реагировать на случаи неэффективной работы приложений, с памятью (кэшем), и кроме как разработчикам или безопастникам, это врядли кому нужно. Не все процессоры поддерживают эту опцию, команда `lscpu | grep split_lock_detect` подскажет, если вы потенциально подвержены такому эффекту.

**Comment by regniws** [comment]
> > Теперь разобраться, как этот ключ аффектит на другие приложения. Беглое описание ключа в ядре мне ничего не сказало...
> 
> Никак не должно, чуть подробней тут: https://www.kernel.org/doc/html/v5.18/x86/buslock.html# Смысл этой опции, реагировать на случаи неэффективной работы приложений, с памятью (кэшем), и кроме как разработчикам или безопастникам, это врядли кому нужно. Не все процессоры поддерживают эту опцию, команда `lscpu | grep split_lock_detect` подскажет, если вы потенциально подвержены такому эффекту.

Это я, безусловно, прочитал. Я не совсем понял, как это смогло помочь ЕДТ и как другие приложения могут на это среагировать. Говорить, что не влияет на другие сложно, потому что на ЕДТ каким-то путём ярко и явно повлияло. Не люблю, когда непонятно :)

**Comment by tretyakevich** [comment]
Добрый день. По текущему статусу проблемы:
1. Работы активно ведутся, сейчас они ведутся на версии 2024.1, в рамках перехода на Java17 + Eclipse 2023.12
2. Основная причина проблемы - активное переключение контекстов потоков ОС-ом вследствие различных факторов (блокировки, операции ввода/вывода,  различные исключения и т.п.) с заметными задержками при выделении следующего таймфрейма. В результате отдельный поток процесса EDT часто не может утилизировать какую-либо значимую долю таймфрейма, выделенный ему шедулером потоков операционной системы.
3. Ранее этот момент так же присутствовал, но был заметно менее выражен. В новых версиях ядра Linux, а также в последних сборках Windows (особенно 11) ситуация заметно усложнилась. То же самое и по железу, и по VM-платформам. 

Сейчас основное направление - это оптимизация высококонкурентных процессов, работающих с большими объемами пересекающихся данных за счет алгоритмики + оптимизация самого объектного хранилища EDT. При снижении contention в критических точках заметно улучшается общая картина утилизации процессорного времени.

Параллельно ведем исследования поведения движка объектного хранилища в области блокировок на чтение (в первую очередь) на микроуровне.

**Comment by tretyakevich** [comment]
Дополнительных профилей не запрашиваем, так как статистики набрали достаточно, и с разных платформ (VM, обычных и т.п.) - проблемное поведение выражается везде примерно одинаково.

**Comment by tretyakevich** [comment]
> Это я, безусловно, прочитал. Я не совсем понял, как это смогло помочь ЕДТ и как другие приложения могут на это среагировать. Говорить, что не влияет на другие сложно, потому что на ЕДТ каким-то путём ярко и явно повлияло. Не люблю, когда непонятно :)

1. Другие приложения - разве что быстрее работать начать, если в них частотный сценарий по атомарным операциям на данных без выравнивания по архитектуре (для x86_64 - 64 байта). Это детектор проблемы, а не оптимизиатор. Т.е. он может только замедлить, но не повлиять на работу (ну кроме выброса фатального исключения для user-процесса, если так его настроить)
2. EDT - значит там (потенциально) есть подобные операции в массовом виде, что вполне реально (движок работы с данными - низкоуровневой, с прямой аллокацией памяти и прочим, синхронизация тоже). В общем случае это неприятно, но не смертельно (единицы процентов от общего реального времени массовых операций). Но вот если вместо полного лока поднимать прерывание и писать ворнинг для user-процесса, а потом продолжать - то да, последствия могут быть очень тяжелыми

**Comment by tretyakevich** [comment]
Добрый день.
В выпущенной финальной версии 2023.3 включен ряд изменений, связанных с выравниванием адресов памяти, которые теоретически могут решить/улучшить ситуацию с проблемой, обнаруженной коммьюнити (см. выше). Если кто-то будет устанавливать новую версию - поделитесь, пожалуйста, информацией о том, улучшилась ли ситуация или нет.
Спасибо!

**Comment by regniws** [comment]
По производительности у меня всё стало практичски идеально, на сборке сильно хорошо всё с загрузкой процессора и по времени сборке. Но расход памяти вырос с 10 гб до 14 гб на не очень большом проекте.

**Comment by regniws** [comment]
> > По производительности у меня всё стало практичски идеально, на сборке сильно хорошо всё с загрузкой процессора и по времени сборке. Но расход памяти вырос с 10 гб до 14 гб на не очень большом проекте.
> 
> А какого примерно размера конфигурация (с какой типовой можно сравнить), и какие параметры выставлены по xmx? Между этими версиями с т.з. расхода памяти никаких заметных изменений не делалось, но могло что-то старое проявиться.

провёл чистые эксперименты, в воспроизводимой среде проблема не наблюдается, всё хорошо, потребление плюс минус такое же, но работает на порядок быстрее, причём на реальный порядок в десятичной системе исчисления. Спасибо.

**Comment by tretyakevich** [comment]
> провёл чистые эксперименты, в воспроизводимой среде проблема не наблюдается, всё хорошо, потребление плюс минус такое же, но работает на порядок быстрее, причём на реальный порядок в десятичной системе исчисления. Спасибо.

Получил еще пару подтверждений улучшения ситуации из других каналов. Поэтому пока завершаю задачу, при возникновении повторных проблем - переоткроем
