### ISSUE TITLE
Не открывается конструктор форматной строки, если в строке содержится экранированный апостроф

### ISSUE THREAD

**Issue by Stivo182** [1C-Company/1c-edt-issues#1187]
### Описание ошибки

Не открывается конструктор форматной строки, если в строке содержится экранированный апостроф

### Как воспроизвести

1. Вызвать конструктор для форматной строки, в которой содержится экранированный апостроф.
2. В логах появится запись об ошибке.

```
Функция Тест()
		
	ФорматнаяСтрока1 = "ДФ='MMMM ''- это месяц'''"; // НЕ открывается конструктор
	
	ФорматнаяСтрока2 = "ДФ='MMMM ""- это месяц""';"; // Открывается конструктор
	
КонецФункции
```

### Скриншоты

![image](https://github.com/1C-Company/1c-edt-issues/assets/24582991/e1ed602f-fe0b-4a07-90b5-b02f26bf8368)

### Ожидаемое поведение

Конструктор форматной строки должен позволять работать со строкой, в которой содержится апостроф

### Лог рабочей области

[log.log](https://github.com/1C-Company/1c-edt-issues/files/12792179/log.log)

### Версия 1С:EDT

Ruby 2023.1.4

### Операционная система

Windows

### Установленные плагины

1C:Code style V8, 1C:SSL-support, 1C:Language Tool

**Comment by Kudesunik** [comment]
Выполнено, войдет в 2023.3
