### ISSUE TITLE
Излишние проверки доступности во внешнем соединении

### ISSUE THREAD

**Issue by SeiOkami** [1C-Company/1c-edt-issues#1190]
### Описание ошибки

В новой версии появились излишние проверки доступности методов объектов во внешнем соединении

### Как воспроизвести

1. Открыть типовой метод БСП, например "УстановитьСвойствоЭлементаФормы"
2. Увидеть, что появилась ошибка недоступности метода 
![image](https://github.com/1C-Company/1c-edt-issues/assets/42138875/0fb8517e-220c-46d4-b341-30f206ada230)

### Ожидаемое поведение

По дефолту в БСП большинство модулей имеет флажок "Внешнее соединение". При этом, сам код, запущенный из внешнего соединения, вызывает только то, что ему нужно в этом модуле. Поэтому ошибка возникнуть не может в принципе. Внешнее соединение не может получить форму, а значит и не передаст её в наш метод. Поэтому нет смысла проверять методы на доступность во внешнем соединении тех объектов, которые и так не доступны во внешнем соединении. 

Такая же проблема наблюдается в модулях отчетов, где есть стандартные БСПшные события и разметка модуля

![image](https://github.com/1C-Company/1c-edt-issues/assets/42138875/abc5474b-7625-43a5-a66d-d522f684a02d)

### Лог рабочей области

-

### Версия 1С:EDT

Ruby 2023.2.0

### Операционная система

Windows

### Установленные плагины

1C:Code style V8, 1C:SSL-support

**Comment by NikitaMikhaylovSB** [comment]
Так тут ошибка в БСП, получается, нужно выделить методы, которые недоступны в ВС в отдельную разметку

**Comment by SeiOkami** [comment]
Это не ошибка, а стандартный подход в разработке БСП и типовых.
Данные методы не экранируются от внешнего соединения, потому что они не могут вызывать никакой ошибки. Они используют метод входящих параметров. 

Можно ли отключить новый подход ЕДТ по анализу для внешнего соединения? Какая-то отдельная галка есть? Иначе весь типовой код покрывается такими ошибками

**Comment by NikitaMikhaylovSB** [comment]
Какая может быть во внешнем соединение форма?...

**Comment by SeiOkami** [comment]
Её там быть не может, а значит и ошибки. Ошибка - это когда во внешнем соединении мы пытаемся получить форму. Такие методы и в БСП экранируются

Тут речь про то, что вводятся правила, которые заведомо не выполняются ни в БСП, ни в типовых, ни в каких-либо стандратных шаблонах модулей и так далее

**Comment by SeiOkami** [comment]
Я бы пометил эти проверки как часть строгой типизации. Потому что как проверка на уровне платформы это не имеет смысла. Ругаться нужно, если во внешнем соединении пытаемся форму получить (чтобы, например, в этот метод передать)

**Comment by SeiOkami** [comment]
Можно ли как-то отключить эти новые проверки? Потому что теоретическое программирование, конечно, очень интересно, но на практике приходится работать с БСП и его подходами

**Comment by NikitaMikhaylovSB** [comment]
Попробуйте отключить проверки для внешних соединений в целом
![изображение](https://github.com/1C-Company/1c-edt-issues/assets/37539066/bf252c86-016e-4643-816d-7750b5d5979c)

**Comment by SeiOkami** [comment]
Да, думаю, что так сработает, но не хотелось бы полностью отключать вообще все проверки внешнего соединения. Работали бы хотя бы стандратные конфигураторские)

**Comment by LesN1ck** [comment]
Описанное выше - ошибка логического построения продукта и к EDT, как к среде разработки, отношения не имеет. Более того - скорее всего, вынесение подобных методов в инструкцию вида "#Если Не ВнешнееСоединение" будет корректнее и с точки зрения производительности. Чем меньше кода предоставляется по контексту соединения, тем быстрее все работает. Поэтому наоборот - кажется, что данную проблему маскировать будет вредно в общем случае.

**Comment by tretyakevich** [comment]
Проверка работает плановым образом, дополнительных изменений не требуется.
В случае, если код решения не может быть приведен в соответствие со стандартами/требованиями платформы - используйте механизм подавлений проверок в отдельных модулях
