### ISSUE TITLE
Миграция рабочей области на версию EDT 2023.2 ломает запуск отладки уже имеющихся конфигураций

### ISSUE THREAD

**Issue by DmitryBelov-e1c** [1C-Company/1c-edt-issues#1194]
### Описание ошибки

Выдаётся ошибка с Java stack trace о невозможности запустить отладку.

### Как воспроизвести

Мигрировать рабочую область, в которой есть проект с конфигурацией отладки, на версию EDT 2023.2 и после попробовать запустить отладку уже имеющейся конфигурации.

### Скриншоты

![изображение](https://github.com/1C-Company/1c-edt-issues/assets/109139509/da973444-bd62-49d0-b4cb-61c77e7e9196)

### Ожидаемое поведение

Корректный запуск отладки

### Лог рабочей области

-

### Версия 1С:EDT

2023.2

### Операционная система

Windows, macOS, Linux

**Comment by DmitryBelov-e1c** [comment]
Ошибка вызвана исправлением давнего typo "Runime" -> "Runtime" в одном из внутренних id инструментария EDT, при этом он задействован в файле описания конфигурации отладки. Для корректной работы отладчика требуется удалить все старые конфигурации и создать новые по необходимости - новый id будет использован автоматически.

**Comment by Roffild** [comment]
Критический баг по:
> Полный временный отказ основной функции (например отвал сессии дебага и т.п.), без описывающего проблему понятного сообщения

с Низким приоритетом. Серьезно???
