### ISSUE TITLE
Ложное срабатывание "Свойство объекта не обнаружено" в форме при передаче реквизитов в внеконтекстный метод

### ISSUE THREAD

**Issue by unichkin** [1C-Company/1c-edt-issues#1198]
### Описание ошибки

Если в форме есть метод НаСервереБезКонтекста - то регистрируется ложное срабатывание ошибки на реквизиты объекта формы.

![image](https://github.com/1C-Company/1c-edt-issues/assets/10799597/784a1835-3cef-4fad-b9d0-db1566b218f6)

### Как воспроизвести

1. В форме создать метод НаСервереБезКонтекста 
2. Обратиться к этому методу с передачей реквизитов объекта

### Ожидаемое поведение

Ложное срабатывание надо убрать

### Лог рабочей области

-

### Версия 1С:EDT

Ruby 2023.1.2

### Операционная система

Windows

**Comment by MaksimDzyuba** [comment]
Здравствуйте, проверил на 2023.2, не воспроизвелось, мы чинили похожее, как перейдете на 2023.2 отпишитесь, пожалуйста
