### ISSUE TITLE
Debug 2023.2.0

### ISSUE THREAD

**Issue by Roffild** [1C-Company/1c-edt-issues#1199]
Поставил 2023.2.0
Запускаю дебаг и получаю ошибку.
[.log](https://github.com/1C-Company/1c-edt-issues/files/12878784/default.log)

```
E Произошла ошибка в течение запуска 1С:Предприятия:
Unable to provision, see the following errors:

1) [Guice/NullInjectedIntoNonNullable]: null returned by binding at IRuntimeDebugClientTargetFactory.create()
 but the 2nd parameter of ProfilingRuntimeDebugClientTarget.<init>(ProfilingRuntimeDebugClientTarget.java:52) is not @Nullable
  at IRuntimeDebugClientTargetFactory.create(IRuntimeDebugClientTargetFactory.java:1)
  at ProfilingRuntimeDebugClientTarget.<init>(ProfilingRuntimeDebugClientTarget.java:52)
      \_ for 2nd parameter
  while locating IRuntimeDebugClientTarget annotated with @UniqueAnnotations$Internal(value=1)

Learn more:
  https://github.com/google/guice/wiki/NULL_INJECTED_INTO_NON_NULLABLE

1 error
```

**Comment by RedMammoth** [comment]
дубль https://github.com/1C-Company/1c-edt-issues/issues/1194 есть обход, надо пересоздать конфигурацию

**Comment by Roffild** [comment]
Такие проблемы должны лечится удалением чего-то в .metadata\.plugins\, что запускает пересканирование.

Заставлять импортировать всю конфу заново с потерей настроек и Гит... мда... format c: ещё нужен?

ЕДТ не видит Гит, пока не ткнешь папку.

**Comment by RedMammoth** [comment]
Уточню, пересоздать конфигурацию отладки, переимпортировать проект не нужно

**Comment by Roffild** [comment]
ОК

Нужен фикс к 2023.2.1 с пересозданием настроек отладки в рамках миграции.
