### ISSUE TITLE
ИзменениеИКонтроль и формат кода

### ISSUE THREAD

**Issue by Roffild** [1C-Company/1c-edt-issues#1200]
Форматирование строк кода должно игнорировать помеченные ИзменениеИКонтроль.

После этого расширение не активно! - порчу кода можно приравнять к критическому багу. Особенно когда жмешь по привычке...
> Расширение1: Обычная: Ошибка применения модуля "Расширение1 ОбщийМодуль.ОбщийМодуль1.Модуль". Текст модуля для метода "ВозведениеВСтепень" изменился

А ещё в ЕДТ я не вижу:
> Если проверка применимости расширений выполняется в конфигураторе, то результатом проверки будет сообщение об ошибке и возможность восстановить соответствие с методом конфигурации.
https://its.1c.ru/db/v8323doc#bookmark:dev:TI000002149

2023.2.0

**Comment by MaksimDzyuba** [comment]
Здравствуйте, а не могли бы, пожалуйста, прикрепить сюда код метода, который потом в расширении не правильно себя ведет

**Comment by Roffild** [comment]
А... поведение тут причем?

Любую большую функцию запихать в расширение под ИзменениеИКонтроль.

После форматирования кода некоторые строчки будут отличаться от оригинала. И при запуске Конфы будет предупреждение.

**Comment by MaksimDzyuba** [comment]
Здравствуйте, воспроизвел, поведение исправили, войдет в 2023.3, постараемся перенести в 2023.2
