### ISSUE TITLE
"Инспектировать" не прекращает грузить процессор.

### ISSUE THREAD

**Issue by Roffild** [1C-Company/1c-edt-issues#1202]
На большом объекте (ДокументОбъект.ПриобретениеТоваровУслуг при проведении) использовать "Инспектировать" и промотать до низа, чтобы все "(ожидание)" активировать.

![bug](https://github.com/1C-Company/1c-edt-issues/assets/38705255/37edf499-a049-426b-aa6d-18b1897b1961)

Проц загружен даже после закрытия окна "Инспектировать". Курсор в редакторе ели ползёт. Нормально работать невозможно, пока уже закрытое "Инспектировать" пытается получить ВСЮ структуру объекта.

2023.1.0 - 2023.2.0

**Comment by Roffild** [comment]
Это баг не только с "Инспектировать".

При отладке функции с большим объектом тоже редактор тормозит после каждого шага, но не так долго, как после "Инспектировать".

**Comment by Erik773** [comment]
Здравствуйте @Roffild.
Какую версию java вы используете? настроена ли конфигурация запуска ЕДТ на использование серверной версии java, посмотреть можно в файле 1cedt.ini, в начале должен быть указан параметр: 
```
-vm 
<путь до BellSoft LibericaJDK-11>l\bin\javaw.exe
```
Могли бы вы, пожалуйста, предоставить логи рабочей области ЕДТ (.log и trace.log с их bak файлами), а также файл модуля, в котором производится отладка? Укажите, пожалуйста, параметры вашего ПК и тип операционной системы.

**Comment by Roffild** [comment]
2023.2.0

Решил задампить через visualvm_217 во время отладки.

Все ForkJoinPool грузят проц на 100%.
В это время окно "Инспектировать" уже закрылось, но потоки не проверяют состояние окна и продолжают в пустую получать объекты, пока не закончатся.

[visualvm_dump.txt](https://github.com/1C-Company/1c-edt-issues/files/13227968/visualvm_dump.txt)

@Erik773

**Comment by DmitryBelov-e1c** [comment]
@Roffild Добрый день, скажите, пожалуйста, не выставлена ли следующая экспериментальная настройка Eclipse (она очень сильно снижает производительность отладчика)?
![изображение](https://github.com/1C-Company/1c-edt-issues/assets/109139509/ad2df8e1-327e-4d3b-b08c-7121e3f5dad5)

**Comment by DmitryBelov-e1c** [comment]
Закрыто до предоставления обратной связи пользователем.
