### ISSUE TITLE
В строгих типах излишне диагностируется ошибка "Добавление типизированного значения в нетипизированную коллекцию" при добавлении в типизированный список значений, являющийся реквизитом формы

### ISSUE THREAD

**Issue by DmitryShvaika** [1C-Company/1c-edt-issues#1203]
### Описание ошибки

В строгих типах излишне диагностируется ошибка "Добавление типизированного значения в нетипизированную коллекцию" при добавлении в типизированный список значений, являющийся реквизитом формы

![image](https://github.com/1C-Company/1c-edt-issues/assets/54451084/9742e4df-2de4-4837-aa39-f511422a4940)

![image](https://github.com/1C-Company/1c-edt-issues/assets/54451084/8693d192-3c4d-4696-a6f1-3f696f065916)

### Как воспроизвести

1. Создать реквизит формы с типом СписокЗначений, указать тип коллекции.
2. В модуле формы попытаться добавить в этот список значение.
3. Наблюдать ошибку в строгих типах

### Ожидаемое поведение

ошибка не должна диагностироваться, если тип списка значений указан

### Лог рабочей области

не требуется

### Версия 1С:EDT

Ruby 2022.2.5

### Операционная система

Windows

**Comment by adminimusRU** [comment]
Это скорее для строгой типизации ошибка, уже заведена: https://github.com/1C-Company/v8-code-style/issues/1231

**Comment by MaksimDzyuba** [comment]
Здравствуйте, удалось все сделать, но войдет уже в 2024.1
![image](https://github.com/1C-Company/1c-edt-issues/assets/77277424/02fcbed4-9317-435e-bb68-527a77791a81)
