### ISSUE TITLE
Не работает редактор макетов табличных документов при работе с картинками

### ISSUE THREAD

**Issue by agibalovsa** [1C-Company/1c-edt-issues#1204]
### Описание ошибки

В макете табличного документа добавлено около 15 картинок с указанным именем (в режиме конфигуратора).
В режиме EDT со свойствами данных картинками редактор макетов не работает.
В журнале появляется ошибка
Exception while executing runnable in queue 'PROPERTY_PALETTE_ENGINE': Argument not valid

### Как воспроизвести

1. Зайти в редактор макета с картинками
2. Не открывает свойства картинки вообще
3. Открывается свойство одной картинки, и оно потом отображается для всех остальных картинок.
4. если открыть свойства ячеек, то при открытии свойств картинок открываются свойства ячеек.

### Скриншоты

![image](https://github.com/1C-Company/1c-edt-issues/assets/14235747/b33e7a1b-1748-4c19-8fcb-404bdc822011)

![image](https://github.com/1C-Company/1c-edt-issues/assets/14235747/fa84fee6-31da-4baa-806d-eb01e4a1e1d6)

![image](https://github.com/1C-Company/1c-edt-issues/assets/14235747/0ceddcbd-c21c-4862-b5ad-4f616aafe39e)

### Ожидаемое поведение

Редактор макета табличного документа должен корректно работать с картинками.

### Лог рабочей области

[logs.zip](https://github.com/1C-Company/1c-edt-issues/files/12914897/logs.zip)

### Версия 1С:EDT

Ruby 2023.2.1

### Операционная система

Windows

### Установленные плагины

1C:Code style V8, 1C:SSL-support

**Comment by wolfandw** [comment]
По макету - можете его выложить сюда, скопировав его напрямую из воркспейса?

**Comment by agibalovsa** [comment]
@wolfandw вот, пожалуйста.

[Template.zip](https://github.com/1C-Company/1c-edt-issues/files/13042732/Template.zip)

**Comment by wolfandw** [comment]
На присланном макете ситуация воспроизвелась. Предложенный вариант обхода выше в таком случае не работает. Будем разбираться, спасибо.
