### ISSUE TITLE
В запросе возникают ошибки синтаксис анализа, если присутствуют в полях выражения ССЫЛКА

### ISSUE THREAD

**Issue by agibalovsa** [1C-Company/1c-edt-issues#1205]
### Описание ошибки

Разработка идет в расширении.

В запросе присутствует строки вида:

```
ВЫБОР
		КОГДА ЗадачиДополнительныеРеквизитыОснование.Значение ССЫЛКА Справочник.Идеи
			ТОГДА ВЫРАЗИТЬ(ЗадачиДополнительныеРеквизитыОснование.Значение КАК Справочник.Идеи)
		КОГДА ЗадачиДополнительныеРеквизитыОснование.Значение ССЫЛКА Справочник.Ошибки
			ТОГДА ВЫРАЗИТЬ(ЗадачиДополнительныеРеквизитыОснование.Значение КАК Справочник.Ошибки)
		ИНАЧЕ НЕОПРЕДЕЛЕНО
	КОНЕЦ,
```

Данный запрос рабочий и в конфигураторе открывается. Все поля для открытия запроса расширены.
В EDT что-то происходит страшное и он формирует ошибки (рис.1):
{(0, 0)}: Error executing EValidator
{(0, 0)}: Error executing EValidator
{(162, 7630)}: Ошибочный параметр
{(164, 7798)}: Ошибочный параметр
{(0, 0)}: Error executing EValidator
{(60, 2629)}: Ошибочный параметр
{(62, 2797)}: Ошибочный параметр
{(0, 0)}: Error executing EValidator
{(0, 0)}: Error executing EValidator
Причем в ошибках конфигурации присутствуют совершено другие ошибки по данному запросу (Рис.2), но они не отображаются. И сам журнал ошибок конфигурации при открытии отчета начинает глючить (Рис.3).

### Как воспроизвести

1. Создать отчет, набрать запрос
2. В запросе должны присутствовать в полях выбора конструкции наподобие
ВЫБОР
		КОГДА ЗадачиДополнительныеРеквизитыОснование.Значение ССЫЛКА Справочник.Идеи
			ТОГДА ВЫРАЗИТЬ(ЗадачиДополнительныеРеквизитыОснование.Значение КАК Справочник.Идеи)
		КОГДА ЗадачиДополнительныеРеквизитыОснование.Значение ССЫЛКА Справочник.Ошибки
			ТОГДА ВЫРАЗИТЬ(ЗадачиДополнительныеРеквизитыОснование.Значение КАК Справочник.Ошибки)
		ИНАЧЕ НЕОПРЕДЕЛЕНО
	КОНЕЦ,
4. Начнут возникать ошибки

### Скриншоты

![image](https://github.com/1C-Company/1c-edt-issues/assets/14235747/4a1ec541-f03a-4e7c-82b4-bd2f5a7174d3)
рис.1
![image](https://github.com/1C-Company/1c-edt-issues/assets/14235747/f55d5091-a4d7-400a-b19f-dc8c1a601702)
рис.2
![image](https://github.com/1C-Company/1c-edt-issues/assets/14235747/a1f4f36b-66cb-4d90-8c33-2cf843c39488)
рис.3
![image](https://github.com/1C-Company/1c-edt-issues/assets/14235747/a0db2dc4-f9e0-439d-b191-257fb7f13d30)
рис.4

### Ожидаемое поведение

Ошибки которые возникают явно не связаны с типовыми проверками, а являются системными.

### Лог рабочей области

[logs.zip](https://github.com/1C-Company/1c-edt-issues/files/12914993/logs.zip)

### Версия 1С:EDT

Ruby 2023.2.1

### Операционная система

Windows

### Установленные плагины

1C:Code style V8, 1C:SSL-support

**Comment by tretyakevich** [comment]
Добрый день, необходима следующая информация: 
1. Расширение+конфигурация (если типовая), на которой воспроизводится проблема
2. Либо развернутый пример с конкретикой (какие объекты были созданы в основной конфигурации, какие в расширении, были ли целевые объекты для запроса заняты в расширении, или они находились в основной конфигурации. 


Просто созданный подобный запрос в макете СКД отчета расширения подобной проблемы не выдал, значит были еще какие-то моменты, которые в методе воспроизведения не были указаны.

**Comment by agibalovsa** [comment]
Здравствуйте, @tretyakevich Мой телеграм https://t.me/agibse. Напишите мне, я открою вам доступ к репозиторию.
