### ISSUE TITLE
Доступно редактирование состава плана обмена находящегося на поддержке (не редактируется)

### ISSUE THREAD

**Issue by Stivo182** [1C-Company/1c-edt-issues#1206]
### Описание ошибки

Доступно редактирование состава плана обмена находящегося на поддержке (не редактируется)

### Как воспроизвести

1. Перейти в состав плана обмена
2. Нажать кнопку "Редактировать элемент списка" 
3. Выбрать элемент и нажать ОК

### Скриншоты

![Screenshot_1](https://github.com/1C-Company/1c-edt-issues/assets/24582991/4af0106d-b004-42c6-8496-066b47e7f510)

### Ожидаемое поведение

Кнопка "Редактировать элемент списка" недоступна

### Лог рабочей области

-

### Версия 1С:EDT

Ruby 2023.2.1

### Операционная система

Windows

### Установленные плагины

1C:Code style V8, 1C:SSL-support, 1C:Language Tool

**Comment by Erik773** [comment]
Здравствуйте @Stivo182!
Могли бы вы, пожалуйста, прикрепить логи рабочей области ЕДТ  (.log, .bak.log и trace.log в папке \.metadata проекта).

**Comment by Stivo182** [comment]
> Здравствуйте @Stivo182! Могли бы вы, пожалуйста, прикрепить логи рабочей области ЕДТ (.log, .bak.log и trace.log в папке .metadata проекта).


[metadata.zip](https://github.com/1C-Company/1c-edt-issues/files/13053778/metadata.zip)
