### ISSUE TITLE
EDT молча портит схему компоновки данных, если чего-то не хватает в расширении

### ISSUE THREAD

**Issue by KovAlexey** [1C-Company/1c-edt-issues#1209]
### Описание ошибки

Ошибка в том что... в случае, если в открываемой схеме компоновки есть обращения к полям, которых нет в расширении, EDT берет и удаляет из схемы поля ресурсов.
Ошибку считаю критической, т.к. она приводит к фактически финансовым потерям программиста.

**Потеря/нарушение данных (в основной конфигурации, в расширениях), обнаруженная постфактум**

### Как воспроизвести

1. Загрузить тем или иным образом в расширение схему СКД, где в запросе есть обращение к полям конфигурации, отсутствующим в расширении (но присутствующим в конфигурации). А так же есть ресурс, использующий такое поле.
Например, загрузить такую схему из xml в пакетном режиме.
Или подменить ее внутри файлов проекта.
2. Открыть редактор СКД
3. Сохранить
4. Увидеть, что из ресурсов схемы удалена часть полей

### Скриншоты

![изображение](https://github.com/1C-Company/1c-edt-issues/assets/16429518/fb0ca093-f24a-40b2-a62f-dd104404aef0)

### Ожидаемое поведение

Не удалять ресурсы в системе не при каких условиях, даже если эти ресурсы ссылаются на уже отсутствующее поле.

Сообщать о том, что в запросе нет полей. Но **не удалять ничего самостоятельно**. Это только создает проблемы, а то и приводит к тому, что работа просто будет утеряна. Никакой помощи разработчику такое поведение не оказывает.

### Лог рабочей области

.

### Версия 1С:EDT

2022.2.5

### Операционная система

Windows

**Comment by KovAlexey** [comment]
В конце концов такие ресурсы можно как-то подсветить, указать, что они ссылаются на несуществующее поле.
Предупредить перед сохранением, что такие ресурсы есть.

Но текущее поведение - просто абсурд.

**Comment by Kudesunik** [comment]
Исправлено. Версия 2024.1

Отметка ошибки у поля при ошибке вычисления поля запроса:
![image](https://github.com/1C-Company/1c-edt-issues/assets/3079145/d8999db7-5a81-4a87-8a0b-9b05c1ffa270)

Отсутствие удаления поля при удалении ресурса (реквизита):
![image](https://github.com/1C-Company/1c-edt-issues/assets/3079145/686b0e20-f3eb-4200-a5b6-fd9fa6999d1c)
