### ISSUE TITLE
Ошибка при попытке переименовать метод или переменную

### ISSUE THREAD

**Issue by d-hurricane** [1C-Company/1c-edt-issues#1210]
### Описание ошибки

При попытке воспользоваться командой контекстного меню "Рефакторинг / Переименовать..." любого модуля возникает ошибка с текстом:

> null
> See log for details

### Как воспроизвести

Открыть любой модуль. Установить курсор в центр любого метода, клинуть правой кнопкой мыши для открытия контекстного меню. В меню выбрать из подменю "Рефакторинг" команду "Переименовать..."

### Скриншоты

![image](https://github.com/1C-Company/1c-edt-issues/assets/59051827/c5d26de3-3098-4279-91ed-c683132d33c8)

### Ожидаемое поведение

Должно открыться окно ввода нового имени метода или переменной для дальнейшего его переименования в тексте модуля.

### Лог рабочей области

[trace.log](https://github.com/1C-Company/1c-edt-issues/files/13044438/trace.log)
[log.txt](https://github.com/1C-Company/1c-edt-issues/files/13044448/log.txt)

### Версия 1С:EDT

Ruby 2023.2.0

### Операционная система

Windows

### Установленные плагины

Нет плагинов

**Comment by tretyakevich** [comment]
Исправлена в 2024.1
