### ISSUE TITLE
Ложное срабатывание ошибки передачи ПользовательскиеНастройкиКомпоновкиДанных между сервером и клиентом

### ISSUE THREAD

**Issue by matvey-seregin** [1C-Company/1c-edt-issues#1211]
### Описание ошибки

Если в процедуре на сервере формируется и передается объект типа ПользовательскиеНастройкиКомпоновкиДанных, то срабатывает диагностика "Нельзя передавать объект типа 'ПользовательскиеНастройкиКомпоновкиДанных' между клиентом и сервером".

Фактически такого ограничения нет, по данным документации тип ПользовательскиеНастройкиКомпоновкиДанных определен во всех видах клиентов, в рантайме передача выполняется.

### Как воспроизвести

https://github.com/matvey-seregin/amusement-park

Версия от 19.10.2023, общая форма МониторРуководителя, процедура ПосещенияАттракционовВыбор
![image](https://github.com/1C-Company/1c-edt-issues/assets/64977311/41d1592c-46b9-417d-aef6-5c4552347bf8)

### Ожидаемое поведение

При передаче объекта типа ПользовательскиеНастройкиКомпоновкиДанных между клиентом и сервером ошибка не выводится в панели ошибок.

### Лог рабочей области

[log.txt](https://github.com/1C-Company/1c-edt-issues/files/13046246/log.txt)

### Версия 1С:EDT

Ruby 2023.1.4

### Операционная система

Windows

### Установленные плагины

1C:Code style V8, 1C:Language Tool

**Comment by lrRatibor** [comment]
![image](https://github.com/1C-Company/1c-edt-issues/assets/125652316/e4e2eec8-2eaf-4157-bbf2-e90b25611012)
Тоже самое для объекта "Цвет", если сервера возвращать  "ЦветаСтиля[Имя]"

**Comment by MaksimDzyuba** [comment]
Здравствуйте, удалось все починить. постараюсь перенести в 2024.1
![image](https://github.com/user-attachments/assets/932ec53a-7b9b-4a0e-b6c3-fc3a8b794590)
