### ISSUE TITLE
Ломается обновление конфигурации при установке параметра динамического списка в Использование = Всегда

### ISSUE THREAD

**Issue by demony** [1C-Company/1c-edt-issues#1212]
### Описание ошибки

Если на форме в динамическом списке добавить параметр, а у этого параметра указать Использование = Всегда, то обновить конфигурацию из EDT больше не получится.

![image](https://github.com/1C-Company/1c-edt-issues/assets/1720563/bb866005-e5ae-40f1-ab23-397b45fd62c2)

![image](https://github.com/1C-Company/1c-edt-issues/assets/1720563/e0d74b95-638a-4350-b283-22405709a60b)

### Как воспроизвести

1. Перейдите в `Настройки списка` (любой динамический список на форме)
2. Кликните по вкладке `параметры`
3. Добавьте параметр 'тест'
4. Установите у параметра 'тест' свойство Использование = Всегда
5. Попробуйте обновить конфигурацию (возникнет ошибка). 

### Скриншоты

![image](https://github.com/1C-Company/1c-edt-issues/assets/1720563/bb866005-e5ae-40f1-ab23-397b45fd62c2)

![image](https://github.com/1C-Company/1c-edt-issues/assets/1720563/e0d74b95-638a-4350-b283-22405709a60b)

### Ожидаемое поведение

Конфигурация должна обновляться.

### Лог рабочей области

[trace.log](https://github.com/1C-Company/1c-edt-issues/files/13053300/trace.log)
[.log](https://github.com/1C-Company/1c-edt-issues/files/13053305/default.log)

### Версия 1С:EDT

Ruby 2023.1.4

### Операционная система

Windows

**Comment by vadimeg** [comment]
Исправлено в 2023.3
