### ISSUE TITLE
EDT 2023.2.1 Нет возможности добавить отредактировать макет табличного документа  

### ISSUE THREAD

**Issue by NekoUnreal** [1C-Company/1c-edt-issues#1216]
### Описание ошибки

При попытке открыть макет табличного документа привязанный к документу или справочнику ничего не происходит.
При попытке добавить новый табличный документ при нажатии на кнопку "Готово" так же ничего не происходит.
В основной конфигурации редактирование макетов происходит в обычном режиме.

![image](https://github.com/1C-Company/1c-edt-issues/assets/94066963/f9a4310b-2f42-41ce-bd56-0334bb8854cb)

![image](https://github.com/1C-Company/1c-edt-issues/assets/94066963/52106796-e9c7-4937-936d-fd6d335d36a5)

### Как воспроизвести

1. Добавить любую форму табличного документа из справочника или документа в расширение.
2. Открыть её в расширении.

1. Правой кнопочкой в документе - макеты -  Создать - "Табличный документ" - "Готово"

### Ожидаемое поведение

Такое же как и в 2023.1.4 возможность редактирования табличного документа.
 
![image](https://github.com/1C-Company/1c-edt-issues/assets/94066963/1bf2049f-4862-4313-b4f7-fa9d2024c925)

### Лог рабочей области

[log.txt](https://github.com/1C-Company/1c-edt-issues/files/13068126/log.txt)
[trace.log](https://github.com/1C-Company/1c-edt-issues/files/13068127/trace.log)

### Версия 1С:EDT

Ruby 2023.2.1

### Операционная система

Windows

### Установленные плагины

1C:Code style V8, 1C:SSL-support, 1C:Language Tool

### Дополнительная информация

КА 2.4.13.281, версия совместимости конфигурации и расширения 23.

**Comment by Erik773** [comment]
Дубль #1214
