### ISSUE TITLE
1c_edt_distr_offline_2023.2.0_436_windows_x86_64 - проблема с компонентами дистрибутива

### ISSUE THREAD

**Issue by dentaky** [1C-Company/1c-edt-issues#1218]
### Описание ошибки

При установке EDT из оффлайн дистрибутива в каталоге установки отсутствует файл 1cedtc.exe.

Соответственно при попытке вызвать 1cedtcli.bat - data workspace... возникает ошибка:

'"C:/Program Files/1C/1CE/components/1c-edt-2023.2.0+436-x86_64/1cedtc.exe"' is not recognized as an internal or external command, operable program or batch file.

### Как воспроизвести

1. Установить дистрибутив 1c_edt_distr_offline_2023.2.0_436_windows_x86_64.
2. Выполнить команду 1cedtcli.bat - data workspace.
3. Получить ошибку в файле workspace\\.metadata\1cedtcli.log - '"C:/Program Files/1C/1CE/components/1c-edt-2023.2.0+436-x86_64/1cedtc.exe"' is not recognized as an internal or external command, operable program or batch file.

### Скриншоты

![image](https://github.com/1C-Company/1c-edt-issues/assets/87470211/49efd500-0a45-4a05-acfc-e1a79779c2ef)

### Ожидаемое поведение

После установки файл 1cedtc.exe должен быть в наличии.

### Лог рабочей области

[1cedtcli.log](https://github.com/1C-Company/1c-edt-issues/files/13076721/1cedtcli.log)

### Версия 1С:EDT

2023.2.0+436-x86_64

### Операционная система

Windows

**Comment by Erik773** [comment]
Здравствуйте @dentaky!
Была опубликована версия 2023.2.1, в ней проблема не воспроизводится.
Могли бы вы, пожалуйста, попробовать установить 2023.2.1 и написать решилась ли ваша проблема?

**Comment by Erik773** [comment]
Закрыто, так как не предоставлен ответ по актуальности проблемы.
