### ISSUE TITLE
Не отображается "Еще" в командной панели со снятым автозаполнением

### ISSUE THREAD

**Issue by agibalovsa** [1C-Company/1c-edt-issues#1219]
### Описание ошибки

Если в конфигураторе для командной панели снять автозаполнение, то не отображается "Еще" для команд, которые "не помещаются" на основной панели.

### Как воспроизвести

1. Снять с командной панели признак "автозаполнение"
2. Разместить на командной панели побольше кнопок и пунктов меню
3. Отобразится лишь часть кнопок, остальная часть пропадет, "Еще", как в конфигураторе не отобразится.
4. Если включить автозаполнение, то "ЕЩЕ" отображается и в нем пропавшие кнопки.
5. Однако, если "Еще" не раскрыть, то при навигации по кнопкам в дереве полей формы его автоматически не раскрывает, и кнопки отображаются не корректно. если раскрыть, то начинается корректное отображение (см. mp4). (такое же поведение в конфигураторе)

### Скриншоты

![image](https://github.com/1C-Company/1c-edt-issues/assets/14235747/80f1c7fd-39b5-47a4-badc-fd0a895df09f)

![image](https://github.com/1C-Company/1c-edt-issues/assets/14235747/33d2aaeb-2ca3-4abf-a714-ca0b829eacad)

![image](https://github.com/1C-Company/1c-edt-issues/assets/14235747/fe131252-ca2c-4d9f-bfaf-6ecf47ae96e3)

https://github.com/1C-Company/1c-edt-issues/assets/14235747/f91f6f69-43a4-4ef6-b76b-1773fed7c857

### Ожидаемое поведение

При любом значении автозаполнения должен быть пункт "Еще". При переходе на кнопку в дереве элементов формы, Еще должно раскрываться автоматически.

### Лог рабочей области

[logs.zip](https://github.com/1C-Company/1c-edt-issues/files/13111377/logs.zip)

### Версия 1С:EDT

Ruby 2023.2.1

### Операционная система

Windows

### Установленные плагины

1C:Code style V8, 1C:SSL-support

**Comment by vadimeg** [comment]
Проверьте, пожалуйста, сценарий в 2024.2, когда выйдет. Если проблема останется, то просьба переоткрыть задачу

**Comment by agibalovsa** [comment]
@vadimeg Добрый день, проверил на последнем релизе 2024.2.
1) Кнопка "Еще" теперь выходит
2) Отображение пунктов меню как-то странно все равно работает (см. видео)

https://github.com/user-attachments/assets/9cba7a7d-6f58-4ba7-aef5-9030e1b0c131
(здесь я с помощью стрелочек клавиатуры передвигаюсь по дереву элементов)

2.1) При переходе на кнопку в дереве элементов формы, Еще не раскрывается автоматически. Кроме кнопок "Вывести список", "Изменить форму.
2.2) При переходе между разными подменю, предыдущие подменю не скрываются.

**Comment by agibalovsa** [comment]
@vadimeg Хорошо, спасибо.

**Comment by agibalovsa** [comment]
@vadimeg , добрый вечер. Релиз Ruby 2026.1.2.
Форма перестала вообще работать. перестали отображаться картинки. Навигация по кнопкам меню - вкривь да вкось.
Зарегил ошибку #2243 Не работает навигация по пунктам меню в форме внешней обработки .
