### ISSUE TITLE
Система определения типов отказывается работать если ниже по коду проверяется тип параметра

### ISSUE THREAD

**Issue by DmitryShvaika** [1C-Company/1c-edt-issues#1221]
### Описание ошибки

Система определения типов отказывается работать если ниже по коду проверяется тип параметра
Пример смотрите на рис ниже

![image](https://github.com/1C-Company/1c-edt-issues/assets/54451084/4e5ce20b-97ec-4712-b97a-9591ad24a4f5)

Однако если убрать условие по типу параметра - сразу все исправляется...
![image](https://github.com/1C-Company/1c-edt-issues/assets/54451084/c2d8ad96-3d27-4c8a-807d-bc0bf81cfd31)

### Как воспроизвести

1. В пустом проекте создайте документ Документ1
2. Создайте серверный общий модуль
3. Введите в него текст:

```
// @strict-types - директива для edt - проверка модуля в строгих типах (все переменные должны быть описаны)

#Область ПрограммныйИнтерфейс

// При записи документа при записи.
// 
// Параметры:
//  Источник - ДокументОбъект
//  Отказ - Булево - Отказ
//
Процедура ПриЗаписиДокументаПриЗаписи(Источник, Отказ) Экспорт
	
	Дата = Источник.Дата;
	
	
	
	
	
	Если ТипЗнч(Источник) = Тип("ДокументОбъект.Документ1") Тогда
		
		
	ИначеЕсли Дата = '00010101' Тогда
		
	КонецЕсли;
	
КонецПроцедуры

#КонецОбласти

```
4. Наблюдайте ошибку

### Ожидаемое поведение

Ошибка не должна детектироваться

### Лог рабочей области

не требуется

### Версия 1С:EDT

Ruby 2023.2.1

### Операционная система

Windows

**Comment by MaksimDzyuba** [comment]
Здравсвтуйте, поправил проблему, постараюсь включить исправления в 2024.1
![image](https://github.com/user-attachments/assets/d1a04822-0c71-46b4-a04d-43b7964f44d2)
