### ISSUE TITLE
Проект не выгружается в информационную базу.

### ISSUE THREAD

**Issue by VAGoncharov** [1C-Company/1c-edt-issues#1226]
### Описание ошибки

Пытаюсь сделать полную выгрузку проекта в инф. базу. Получаю ошибку "java.lang.IllegalArgumentException: org.eclipse.emf.ecore.impl.EClassImpl@24f1be4a (name: TaskAttribute) (instanceClassName: null) (abstract: false, interface: false) eClass has not containf feature with code equals "type"".

### Как воспроизвести

-

### Ожидаемое поведение

-

### Лог рабочей области

[лог рабочей области.txt](https://github.com/1C-Company/1c-edt-issues/files/13221120/default.txt)

### Версия 1С:EDT

2022.2.5

### Операционная система

Windows

### Установленные плагины

1C:Code style V8, 1C:SSL-support

**Comment by Erik773** [comment]
Здравствуйте @VAGoncharov!
Есть ли у вас возможность предоставить проект конфигурации, для воспроизведения проблемы?

**Comment by VAGoncharov** [comment]
> Здравствуйте @VAGoncharov! Есть ли у вас возможность предоставить проект конфигурации, для воспроизведения проблемы?

Такой возможности, к сожалению, нет.

Проблема плавающая, временно помогает очистка проекта.

**Comment by Erik773** [comment]
> Такой возможности, к сожалению, нет.
@VAGoncharov, а возможно ли предоставить доступ к окружению для воспроизведения проблемы?
Подскажите, пожалуйста, используется ли типовая конфигурация? 
Перед загрузкой производилось ли сравнение/объединение? 
Каким образом конфигурация была импортирована в ЕДТ (из гит репозитория или из информационной базы)? 
Производились ли перед загрузкой в базу изменения в формах и удаление ресурсов?
Какая версия платформы 1С:Предприятия используется при создании информационной базы?
Информационная база на момент загрузки пустая или была синхронизирована с проектом конфигурации?

**Comment by VAGoncharov** [comment]
1. Доступ к сожалению организовать не получится.
2. Самописная конфигурация.
3. Да, это тестовая ветка, куда заливаются изменения всех разработчиков.
4. Из репозитория.
5. Да, другими разработчиками в своих ветках.
6. Версия платформы - 8.3.22.1851
7. Была ранее синхронизирована с проектом. Последний раз синхронизировалась 1-2 недели назад до синхронизации.

**Comment by tretyakevich** [comment]
Проблема не воспроизводится на последних сборках 2023.3
