### ISSUE TITLE
Неправильное заполнение истории поиска панели навигатора

### ISSUE THREAD

**Issue by TimkoNZT** [1C-Company/1c-edt-issues#1229]
### Описание ошибки

Неправильно заполняется список истории в поле поиска навигатора. Видимо код сохранения истории выполняется после ввода каждого символа, хотя должен при срабатывании поиска или даже спустя пару секунд после.

До исправления бага [961](https://github.com/1C-Company/1c-edt-issues/issues/961) всё было в норме.

![image](https://github.com/1C-Company/1c-edt-issues/assets/3190574/c0b3260b-ed54-4c53-930f-2fd130a197ba)

### Как воспроизвести

1. Перейдите в поле поиска панели навигатора
2. Набирайте текст для поиска в дереве
3. Кликните по кнопки истории поиска
4. Наблюдайте не совсем то, что ожидалось (см. скриншот)

### Ожидаемое поведение

Сохранение строки поиска панели навигатора как в релизах до 2023.2

### Лог рабочей области

[.metadata.zip](https://github.com/1C-Company/1c-edt-issues/files/13238831/default.metadata.zip)

### Версия 1С:EDT

2023.2.1

### Операционная система

Windows

**Comment by dsavenko** [comment]
Исправлено в 2024.1
