### ISSUE TITLE
Для Объекта ЗаписьДанных пишет, что Асинхронные методы не обнаружены на Web-клиент

### ISSUE THREAD

**Issue by lrRatibor** [1C-Company/1c-edt-issues#1230]
### Описание ошибки

Ошибка в том что следующие методы для Объект ЗаписьДанных доступны на Web-клиенте, а EDT предупреждает что они не доступны
ЗакрытьАсинх (CloseAsync)
ЗаписатьАсинх (WriteAsync)
ЗаписатьБайтАсинх (WriteByteAsync)
ЗаписатьБуферДвоичныхДанныхАсинх (WriteBinaryDataBufferAsync)
ЗаписатьСимволыАсинх (WriteCharsAsync)
ЗаписатьСтрокуАсинх (WriteLineAsync)
ЗаписатьЦелое16Асинх (WriteInt16Async)
ЗаписатьЦелое32Асинх (WriteInt32Async)
ЗаписатьЦелое64Асинх (WriteInt64Async)
СброситьБуферыАсинх (FlushAsync)

### Как воспроизвести

1. Создать на клиенте Асинхронную процедуру
2. В процедуре создать ЗаписьДанных
3. На все Асинхронные методы будет предупреждать о недоступности на Web-клиенте

### Скриншоты

![image](https://github.com/1C-Company/1c-edt-issues/assets/125652316/adc7528a-1df6-4a86-8d59-46e96fd7c9e4)

### Ожидаемое поведение

Асинхронные методы должны быть доступны на Web-клиенте

### Лог рабочей области

*

### Версия 1С:EDT

Ruby 2023.2.1

### Операционная система

Windows

**Comment by Erik773** [comment]
Здравствуйте @lrRatibor!
Могли бы вы, пожалуйста, приложить логи рабочей области ЕДТ  (.log, .bak.log и trace.log в папке \.metadata проекта)

**Comment by lrRatibor** [comment]
Добрый день.
[trace.log](https://github.com/1C-Company/1c-edt-issues/files/13293321/trace.log)
[_.log](https://github.com/1C-Company/1c-edt-issues/files/13293326/_.log)
файла ".bak.log" нет.  ".log" переименовал в "_.log"

**Comment by MaksimDzyuba** [comment]
Здравствуйте, исправил, войдет точно в 2023.3, постараемся перенести в 2023.2, но не обещаем
![image](https://github.com/1C-Company/1c-edt-issues/assets/77277424/1107fabf-2dcc-4a55-85f1-91097fd7e0f0)
