### ISSUE TITLE
Не запускается расширенная проверка после слияния ветки с origin

### ISSUE THREAD

**Issue by adminimusRU** [1C-Company/1c-edt-issues#1231]
### Описание ошибки

На версии 2023.2.1 после выполнения команды "Получить и слить" EDT получает и применяет изменения из origin на локальную ветку, но не запускает обновление модели и расширенные проверки на изменившиеся объекты. В логах при этом множественные ошибки NPE. После перезапуска EDT проверки запускаются.

### Как воспроизвести

1. Выполнить "Получить и слить" на ветке, где много изменений в origin
2. После применения полученных изменений проверки не запустились
3. Проверки запустились после перезапуска EDT

### Ожидаемое поведение

Проверки должны запускаться сразу после применения полученных изменений.

### Лог рабочей области

[trace.log](https://github.com/1C-Company/1c-edt-issues/files/13280378/trace.log)

### Версия 1С:EDT

2023.2.1

### Операционная система

Windows

### Дополнительная информация

Обновлял ветку develop с коммита d2ddf8e на 23bc3c2

**Comment by adminimusRU** [comment]
Оставшиеся логи, гитхаб почему-то не хотел скрытые файлы прикреплять
[logs.zip](https://github.com/1C-Company/1c-edt-issues/files/13280416/logs.zip)

**Comment by tretyakevich** [comment]
В версии 2023.3 были внесены изменения в данной области. Могли бы вы проверить - повторяется ли эта проблема, или нет?

**Comment by adminimusRU** [comment]
Пока что не перевели разработку на 2023.3 версию, не пробовал на ней. На более новых версиях из 2023.2 ошибка более не проявлялась. Открою новый багрепорт на актуальной версии если снова повторится.
