### ISSUE TITLE
Не добавляется выбор основной таблицы динамического списка в форме списка задач с отбором по исполнителю

### ISSUE THREAD

**Issue by serg72u** [1C-Company/1c-edt-issues#1232]
### Описание ошибки

Ошибка в том что при создании формы списка объекта Задачи, с установленным Основным реквизитом адресации и Текущим исполнителем, в сформированной форме списка, для динамического списка "Список", не появляется основная таблица с Отбором по исполнителю. Если открыть конфигурацию в конфигураторе, то такая таблица появляется. Если ее выбрать в конфигураторе и загрузить конфигурацию в EDT Поле основная таблица становиться не доступным для выбора.

### Как воспроизвести

1. Создать объект Задачи
2. Добавить реквизит адресации Исполнитель
3. Установить основной реквизит адресации Исполнитель
4. Установить Текущий исполнитель ТекущийИсполнитель (Параметр сеанса)
5. Перейти на форму и выбрать реквизит Список (ДинамическийСписок)
6. В свойствах выбрать выпадающий список Основная таблица.

### Скриншоты

<img width="1356" alt="image" src="https://github.com/1C-Company/1c-edt-issues/assets/6323906/23d46b10-6fe2-4db3-b6c1-348dd50dcffd">

<img width="1490" alt="image" src="https://github.com/1C-Company/1c-edt-issues/assets/6323906/740e1e4c-426c-4d5c-9f39-cc021abace11">

<img width="1359" alt="image" src="https://github.com/1C-Company/1c-edt-issues/assets/6323906/04430830-222a-4e1d-8303-57ec47e1891a">

### Ожидаемое поведение

Такое же как в конфигураторе. Должен быть выбор возможности отбора списка по Исполнителю.

### Лог рабочей области

[log.txt](https://github.com/1C-Company/1c-edt-issues/files/13283718/log.txt)

### Версия 1С:EDT

Ruby 2023.2.1

### Операционная система

Windows

**Comment by vadimeg** [comment]
Исправлено в 2023.3.1
![image](https://github.com/1C-Company/1c-edt-issues/assets/17178862/d3b70773-5126-4064-abcd-ca34aab8672e)
