### ISSUE TITLE
Объединение веток не завершается

### ISSUE THREAD

**Issue by Merkalov** [1C-Company/1c-edt-issues#1233]
### Описание ошибки

При получении изменений из ветки-мастера и дальнейшем слиянии локальной и удаленной ветки процесс слияния не завершается, т.е бесконечно висит, подтянутые изменения появляются на вкладке "Индексирование GIT" в панели "Неиндексированные изменения". В ожидании провел больше часа, судя по нагрузке на ЦП вообще ничего не происходит.

### Как воспроизвести

1. Получить изменения из мастера
2. Нажать "Слить"

### Скриншоты

![Screenshot_2](https://github.com/1C-Company/1c-edt-issues/assets/28949451/ee70eb5b-63e1-4004-841e-825a5e3e7274)
![Screenshot_3](https://github.com/1C-Company/1c-edt-issues/assets/28949451/3e6404c4-9c57-4819-b76b-604fbaeb6576)

### Ожидаемое поведение

Слияние веток завершается. 

### Лог рабочей области

[EDT_merge.log](https://github.com/1C-Company/1c-edt-issues/files/13290634/EDT_merge.log)

### Версия 1С:EDT

Ruby 2023.2.1

### Операционная система

Windows

### Установленные плагины

Нет плагинов

### Дополнительная информация

Проявлялось на разных машинах у разных пользователей.

**Comment by Merkalov** [comment]
@Erik773, привет, в нашей команде почти каждый столкнулся с данной проблемой и все потратили очень много времени на исправление последствий, в группе тг так же есть сообщения о подобном баге, не могли бы вы пересмотреть приоритет?

**Comment by Erik773** [comment]
@Merkalov, рекомендуем при создании задачи, если вы считаете её критически важной и она соответствует критериям критической ошибки https://github.com/1C-Company/1c-edt-issues/blob/main/TASK_CLASSIFICATION.md, ставить лейбл critical, иначе его отсутствие может быть расценено как то, что эта проблема не является для вас критически важной.

**Comment by tretyakevich** [comment]
К сожалению, не можем воспроизвести данную проблему по описанию. Если проблема воспроизводится - пожалуйста приложите дамп потоков.

По сообщениям в логе какой-то процесс заблокировал индекс Git-а. Это может быть как процесс EDT, так и внешний процесс, поэтому необходим дамп тредов и проверка того, что снаружи в данный момент никакой другой процесс (внешний) не работает с Git-ом на данной машине
