### ISSUE TITLE
Зависла при расширении метода

### ISSUE THREAD

**Issue by Jimmo910** [1C-Company/1c-edt-issues#1235]
### Описание ошибки

Попытался расширить метод формы и все зависло.
вроде как я успел кликнуть мышкой в "Тип вызова" и все....

### Как воспроизвести

В типовой ЕРП я попытался расширить метод "ПолучитьПараметрыТовараПередДобавлениеВКорзину" - на форме обработки "ПодборТоваровВДокументПродажи".

после перезапуска - опять зависает....т

### Скриншоты

![image](https://github.com/1C-Company/1c-edt-issues/assets/122779512/a70ab149-3188-4264-9515-e9bb91e03a46)

### Ожидаемое поведение

Что бы не зависало

### Лог рабочей области

[Лог.metadata.zip](https://github.com/1C-Company/1c-edt-issues/files/13298180/metadata.zip)

### Версия 1С:EDT

2023.1.4

### Операционная система

Windows

### Дополнительная информация

Дамп потоков: 
[threaddump.txt](https://github.com/1C-Company/1c-edt-issues/files/13298200/threaddump.txt)

Дамп памяти:
https://disk.yandex.ru/d/PeJ5C2QP7XaGAQ

**Comment by EChudnovsky** [comment]
Подобное поведение наблюдается и в релизе-кандидате edt 2023.2.1 
Здесь собирал варианты зависаний #1207.
По работам - исправление намечено на [milestone 2023.3](https://github.com/1C-Company/1c-edt-issues/milestone/7) 
С таким поведением: с постоянным зависанием и пере запуском IDE, не понятно как вести разработку на релизе 2023.

**Comment by tretyakevich** [comment]
Данная причина зависания была исправлена в финальной версии 2023.2
