### ISSUE TITLE
Не импортируется макет СКД с полем типа "ЛюбаяСсылка"

### ISSUE THREAD

**Issue by ArtemB91** [1C-Company/1c-edt-issues#1236]
### Описание ошибки

При импорте конфигурации из информационной базы EDT не может импортировать макет СКД при наличия поля с типом значения “ЛюбаяСсылка” (и соответственно экспортировать обратно в конфигуратор)

Судя по всему, EDT не может распарсить из XML поле с значением d5p1:AnyIBRef, т.к. это нововведение 23ой платформы. (в режиме совместимости c 22ой платформой и ниже в XML будет выгружено d5p1:AnyRef)  

EDT 2023.2.1, Платформа 8.3.23.1912, без режима совместимости

### Как воспроизвести

Загрузить example.dt (с одним отчетом "Анализ прав" из БСП), импортировать в EDT - ошибка отразится в логе, макет отчета не откроется в EDT.
[example.zip](https://github.com/1C-Company/1c-edt-issues/files/13368544/example.zip)

### Ожидаемое поведение

Макет отчета должен импортироваться и экспортироваться корректно

### Лог рабочей области

[metadata.zip](https://github.com/1C-Company/1c-edt-issues/files/13368538/metadata.zip)

### Версия 1С:EDT

Ruby 2023.2.1

### Операционная система

Windows

### Установленные плагины

1C:Code style V8, 1C:SSL-support

**Comment by beg7** [comment]
Известная проблема. Исправление будет в ближайшей тестовой версии.

**Comment by MaksimDzyuba** [comment]
Исправление доступно в 2023.2.2
