### ISSUE TITLE
При создании команды объекта предлагается открыть форму объекта с некорректным именем

### ISSUE THREAD

**Issue by d-hurricane** [1C-Company/1c-edt-issues#1237]
### Описание ошибки

При создании новой команды для объекта конфигурации в модуле этой команды генерируется обработчик, содержащий закомментированный код с открытием формы списка объекта метаданных. Однако в пути формы вместо имени объекта метаданных ошибочно используется имя новой команды.

### Как воспроизвести

1. Создать пустую конфигурацию.
2. Добавить справочник "Номенклатура".
3. В справочнике номенклатуры на закладке "Команды" добавить новую команду "ПоказатьСписок". Размещение и параметры команды не играют роли.
4. Открыть модуль команды.
5. Убедиться, что в закомментированном коде вместо ожидаемого пути `Справочник.Номенклатура.ФормаСписка` будет написано `Справочник.ПоказатьСписок.ФормаСписка`

### Ожидаемое поведение

Должно использоваться имя объекта метаданных - владельца команды.

### Лог рабочей области

[log.txt](https://github.com/1C-Company/1c-edt-issues/files/13374350/log.txt)

### Версия 1С:EDT

Ruby 2023.2.1

### Операционная система

Windows

### Установленные плагины

1C:Code style V8, 1C:SSL-support

**Comment by tretyakevich** [comment]
Исправлено в 2024.1
