### ISSUE TITLE
Не удаляется команда объекта метаданных из командного интерфейса подсистемы

### ISSUE THREAD

**Issue by d-hurricane** [1C-Company/1c-edt-issues#1238]
### Описание ошибки

При редактировании командного интерфейса подсистемы, попытка удалить из списка "Команды раздела" какую-либо команду объекта конфигурации заканчивается ничем: ни сообщений об ошибках, ни собственно удаления команды. При этом сами объекты метаданных удаляются корректно, вместе со своими командами.

### Как воспроизвести

1. Создать новую конфигурацию.
2. Добавить справочник "Номенклатура", ему добавить команду "ПоказатьСписок" (группа "Панель действий.Сервис").
3. Добавить подсистему "Администрирование", отображаемую в интерфейсе.
4. В состав подсистемы включить справочник номенклатуры.
5. Открыть командный интерфейс подсистемы.
6. Найти в правом списке "Команды раздела" справочник "Номенклатура" и команду "Показать список".
7. Выделить строку с командой, нажать "Удалить" в меню списка. Убедиться, что ничего не произойдет.
8. Выделить строку со справочником, нажать "Удалить" в меню списка. Убедиться, что и справочник, и его команда пропадут из списка, а также из состава самой подсистемы.

### Ожидаемое поведение

В общем случае удаление команды невозможно без удаления объекта-владельца из состава подсистемы, т.к. платформа не позволяет часть команд одного объекта включать в интерфейс, часть исключить. Управлять можно только видимостью команд.

Поэтому возможны следующие пути:
- Когда пользователь нажимает "Удалить" для команды, предупреждать его, что данная операция невозможна и нужно удалять сам объект-владелец команды из списка команд раздела.
- Предупреждать пользователя, что удалять команды по одной возможности нет и предложить удалить объект со всеми командами сразу.
- Если команда одна, спокойно удалять ее вместе с объектом конфигурации из состава подсистемы. Такое поведение удобно в случае, когда у объекта отключены стандартные команды, есть только одна добавленная разработчиком. И соответственно в списке команд раздела (подсистемы) отображается только одна команда объекта.

### Лог рабочей области

[log.txt](https://github.com/1C-Company/1c-edt-issues/files/13374583/log.txt)

### Версия 1С:EDT

Ruby 2023.2.1

### Операционная система

Windows

### Установленные плагины

1C:Code style V8, 1C:SSL-support

**Comment by wolfandw** [comment]
Исправлено в 2024.1
