### ISSUE TITLE
Unhandled event loop exception при попытке изменить значение переменной с типом Неопределно в отладке

### ISSUE THREAD

**Issue by adminimusRU** [1C-Company/1c-edt-issues#1239]
### Описание ошибки

При попытке вызвать диалог изменения значения переменной с типом `Неопределено` в лог добавляется ошибка Unhandled event loop exception, окно изменения значения перестает открываться до перезапуска EDT. 

### Как воспроизвести

Для примера взял справочник Валюты из БСП, можно воспроизвести на типовой демо базе.
1. Установить точку останова в начале обработчика события `ПриСозданииНаСервере` формы элемента
2. Запустить отладку, открыть элемент справочника Валюты
3. После срабатывания точки останова попытаться изменить значение переменной `ИспользоватьНесколькоВалют`

### Скриншоты

![image](https://github.com/1C-Company/1c-edt-issues/assets/28653631/ef18267f-bb72-4913-82cd-2e7cc5d53b36)

### Ожидаемое поведение

Должно открываться окно изменения значения.

### Лог рабочей области

[logs.zip](https://github.com/1C-Company/1c-edt-issues/files/13423674/logs.zip)

### Версия 1С:EDT

2023.2.1

### Операционная система

Windows

**Comment by MaksimDzyuba** [comment]
Здравствуйте, ошибку исправили, войдет в 2024.1, спасибо!
