### ISSUE TITLE
Иногда в модуле перестает работать кнопка Del

### ISSUE THREAD

**Issue by DmitryShvaika** [1C-Company/1c-edt-issues#124]
### Описание ошибки

Иногда в модуле перестает работать кнопка Del. При нажатии ничего не происходит. Выделенный фрагмент текста не удаляется.

### Как воспроизвести

Ситуация возникает редко случайным образом. Нет сценария чтобы воспроизвести.
Обычно возникает при некотором числе открытых окон. Когда редактируешь большое число форм.
Открываешь, что-то меняешь закрываешь или оставляешь открытой.
Возможно помогут логи рабочей области
В журнале ошибок появляется много ошибок при этом.

### Ожидаемое поведение

Кнопка Del в модуле формы должна работать всегда :)

### Лог рабочей области

[логи.zip](https://github.com/1C-Company/1c-edt-issues/files/7575676/default.zip)

### Версия 1С:EDT

Ruby 2021.2.10

### Операционная система

Windows

### Установленные плагины

1C:Code style V8, 1C:SSL-support

### Дополнительная информация

Помогает либо закрытие формы и ее повторное открытие. Но в этом случае только рестарт Edt помог.
Причем если не работает кнопка del, то BackSpace продолжает работать.

**Comment by NikitaMikhaylovSB** [comment]
Добавлю, что очень часто одновременно перестает работать еще и CTRL+C и CTRL+V
Это уже лечиться только перезапуском.

**Comment by L32GIT** [comment]
> Добавлю, что очень часто одновременно перестает работать еще и CTRL+C и CTRL+V Это уже лечиться только перезапуском.

Постоянно перестает работать CTRL+C, CTRL+V при активной работе с макетами (табличными документами).
Степень ошибки разная. Иногда не работают только горячие клавиши, но при вызове мышью из контекстного меню - работает. Иногда даже в контекстном меню операции "серые" - это лечится переоткрытием макета.
Версия 2021.2.9

**Comment by Valarrus** [comment]
Поддержу. Актуально.

**Comment by DmitryShvaika** [comment]
Ошибка больше не проявляется - спасибо

**Comment by KovAlexey** [comment]
На 2022.2.4 столкнулся сегодня с аналогичной проблемой.
Так же. как и коллеги выше, сценария дать не могу.
Delete перестал работать до перезапуска

**Comment by grumagargler** [comment]
2023.2.1 - кнопа Delete опять перестала работать после того, как сделал copy/paste процедуры из открытого окна конфигуратора в общий модуль, открытый в едт.

**Comment by VAGoncharov** [comment]
Подтверждаю, проблема остается актуальной на 2022.2.5 и 2023.x. В какой-то момент перестают работать вообще все горячие клавиши, а не только Delete. Помогает перезапуск.
