### ISSUE TITLE
Зависание EDT при запуске отладки (в случае ошибки подключения к серверу отладки)

### ISSUE THREAD

**Issue by goodwinvu** [1C-Company/1c-edt-issues#1240]
### Описание ошибки

При запуске отладки (на автономном сервере версия 8.3.23.1912) ЕДТ зависает наглухо
Баг плавающий, т.е не всегда воспроизводится, причины в том, что отладчик не смог подключиться (судя по всему косяк в настройках авт. сервера и адрес сервера отладки там был указан ошибочный).
Сюда притащил, т.к это вызывает зависание, что не допустимо.

### Как воспроизвести

1. Настроить авт. сервер (отладка включена, но адрес сервера отладки на авт. сервере не указывать, либо указать ошибочный)
2. Подключить проект (с расширениями) к  иб, размещенной на авт. сервере
3. Попытаться отладить

### Ожидаемое поведение

Сообщать об ошибках подключения отладки и не зависать.

### Лог рабочей области

[DumpsLogs.zip](https://github.com/1C-Company/1c-edt-issues/files/13425959/DumpsLogs.zip)

### Версия 1С:EDT

Ruby 2023.2.1

### Операционная система

Windows

### Установленные плагины

1C:Code style V8, 1C:SSL-support, Другие сторонние плагины `Название плагина...`

**Comment by tretyakevich** [comment]
Внесено множество изменений в процедуры оркестрации сравнения/объединения + обработка ошибки запуска (по информации в предоставленных журналах)
