### ISSUE TITLE
В расширении, в подсказке для проводки балансовый ресурс показывается как не балансовый, так же поле введенное вручную считается ошибочным

### ISSUE THREAD

**Issue by JaneGlass73** [1C-Company/1c-edt-issues#1241]
### Описание ошибки

Ошибка в том что в подсказке для проводки балансовый ресурс показывается как не балансовый, так же поле введенное вручную считается ошибочным
![image](https://github.com/1C-Company/1c-edt-issues/assets/144486006/cb2ca7e6-7095-4ef8-8015-2c4b99b5f601)
Хотя на самом деле если посмотреть в полях отладчика это поле хорошо видно
![image](https://github.com/1C-Company/1c-edt-issues/assets/144486006/cf574bda-7ad4-4017-8fb2-b472c83d1316)
В модулях основной конфигурации всё работает корректно.

### Как воспроизвести

1. Импортировать ресурс "Сумма" регистра бухгалтерии Хозрасчетный из конфигурации БП КОРП или УХ в новое расширение, вместе с ресурсом импортируется и регистр
2. Добавить любой серверный модуль конфигурации БП КОРП или УХ в это же расширение и написать код:
```bsl
Процедура Тест()
	НаборПроводок = РегистрыБухгалтерии.Хозрасчетный.СоздатьНаборЗаписей();
	Для Каждого Проводка Из НаборПроводок Цикл
		А = Проводка.;
	КонецЦикла
КонецПроцедуры

```
3. В 4й строке после точки вызвать контекстную подсказку - в ней не будет поля Сумма, а будут поля СуммаДт и СуммаКт
4. Если вручную после точки в 4й строке написать Сумма, то редактор подчеркнёт это поле как не обнаруживаемое:
![image](https://github.com/1C-Company/1c-edt-issues/assets/144486006/15b941fc-dbaa-4370-a8cd-337280671c92)
Хотя это на самом деле не верно.

### Ожидаемое поведение

Для балансовых полей (отмеченный в регистре бухгалтерии) признаком:
![image](https://github.com/1C-Company/1c-edt-issues/assets/144486006/224209bd-a95c-4a42-a29e-9bcdae7d78b1)
В подсказке отображать корректный набор свойств не разделять это поле на СуммаДт и СуммаКт
_Вероятно, проблема заключается в том, что в свойствах ресурса импортированного объекта - регистра бухгалтерии свойство "Балансовый" отсутствует_

### Лог рабочей области

Не требуются

### Версия 1С:EDT

2023.2.0

### Операционная система

Windows, Linux

**Comment by LesN1ck** [comment]
А в расширении указан признак, что ресурс является балансовым?

**Comment by JaneGlass73** [comment]
> А в расширении указан признак, что ресурс является балансовым?

> _Вероятно, проблема заключается в том, что в свойствах ресурса импортированного объекта - регистра бухгалтерии свойство "Балансовый" отсутствует_

А там нет такого признака :) Я про это написала.

**Comment by LesN1ck** [comment]
Это интересно, поскольку в конфигураторе данное свойство в палитре есть:

![image](https://github.com/1C-Company/1c-edt-issues/assets/114978535/c9e336fa-34ac-49ee-8d36-145c2ccf808e)

**Comment by JaneGlass73** [comment]
@LesN1ck ну у EDT же своя вселенная 🤷‍♀️

**Comment by MaksimDzyuba** [comment]
Здравствуйте, удалось починить, спасибо большое, постараюсь перенести в 2024.1!
![image](https://github.com/user-attachments/assets/38c494e1-349f-4401-adf8-c121ff39eb15)
![image](https://github.com/user-attachments/assets/55845f5b-fbb7-47bc-b117-b1e7dd35da7d)
