### ISSUE TITLE
Зависание EDT при наведении курсора на окно панелей.

### ISSUE THREAD

**Issue by NikitaPopovsky** [1C-Company/1c-edt-issues#1243]
### Описание ошибки

Находясь в в модуле формы объекта, при перемещении курсора на панель "Схема" или на панель "Ошибки", EDT зависает намертво. 
Наблюдается постоянно.
В момент зависания не отображается никаких процессов EDT, в том числе и в панели "Состояние".
Сброс проекта делал. 
Развернул другой проект, тоже самое.

### Как воспроизвести

1. Открыть модуль формы, где около 50 процедур.
2. Открыть панель "Схема" или "Ошибки"
3. Провести курсором из редактора модуля формы по панели "Схема".
На кнопки мыши я нажимать не надо, просто провести курсором.

### Скриншоты

[scrin.zip](https://github.com/1C-Company/1c-edt-issues/files/13443911/scrin.zip)
[plagins.zip](https://github.com/1C-Company/1c-edt-issues/files/13443950/plagins.zip)

### Ожидаемое поведение

Без зависаний

### Лог рабочей области

[threaddump.zip](https://github.com/1C-Company/1c-edt-issues/files/13443907/threaddump.zip)
[log.zip](https://github.com/1C-Company/1c-edt-issues/files/13443976/log.zip)

### Версия 1С:EDT

Ruby 2022.2.5

### Операционная система

Windows

### Установленные плагины

1C:SSL-support, Другие сторонние плагины `Название плагина...`

### Дополнительная информация

[РегламентированныйОтчетСтатистикаФормаП2инв.zip](https://github.com/1C-Company/1c-edt-issues/files/13443888/2.zip)

Можно попробовать воспроизвести на этом отчете.
Я создал новый проект, импортировал туда этот отчет.
Зашёл в модуль формы ФормаОтчета2022Кв1, навел курсор на панель "Схема" и провел по панели, поймал зависание.
P.S. Странно что когда окно EDT открыто на половину, зависаний нет...

**Comment by MaksimDzyuba** [comment]
@NikitaPopovsky Здравствуйте, не могу воспроизвести, в дампе тоже не вижу, чтобы было зависание. Пока понижу приоритет, если воспроизводится у Вас все еще, можете, пожалуйста, скинуть видео, что Вы делаете. Я бы очень рекомендовал перейти на edt версии 2023.1 хотя бы

**Comment by yaroslavgrinash** [comment]
Здравствуйте. Ошибка воспроизводится со 100% вероятностью. Как на 2023.2.4, так и на 2023.3.0

**Comment by MaksimDzyuba** [comment]
Здравствуйте, а можно видео, пожалуйста

**Comment by yaroslavgrinash** [comment]
Пожалуйста
[Uploading 2024-01-31 14-15-52.zip…]()

**Comment by yaroslavgrinash** [comment]
@MaksimDzyuba 
[Screenrecord.zip](https://github.com/1C-Company/1c-edt-issues/files/14111142/Screenrecord.zip)

**Comment by MaksimDzyuba** [comment]
а можете, пожалуйста, еще раз воспроизвести и снять дампы, с обоих процессов, что у Вас на видео показаны, вообще не воспроизводится, да и в том внешнем отчете, что приложен, нет такого модуля, как на видео

**Comment by yaroslavgrinash** [comment]
@MaksimDzyuba , пожалуйста, напишите, как снять дампы

**Comment by yaroslavgrinash** [comment]
@MaksimDzyuba, проблема при открытии любого достаточно большого модуля. 
[threaddump.zip](https://github.com/1C-Company/1c-edt-issues/files/14120758/threaddump.zip)
Процесс на момент снятия дампа был только один.

**Comment by yaroslavgrinash** [comment]
Здравствуйте! Благодарю за ответ. Если стоит online-версия, какие настройки необходимо выполнить? Правки файла 1cedt.ini не дали результата.

**Comment by MaksimDzyuba** [comment]
В онлайн версии это так не поменять, как я писал выше. 
А можете попробовать установить 100% зум фактор на все мониторы в Windows, вроде пишут, что это тоже поможет.
Вот так в оригинале звучит совет "please change the zoom factor on Windows to 100% for all displays"

**Comment by yaroslavgrinash** [comment]
Спасибо большое, помогло.

**Comment by MaksimDzyuba** [comment]
я тогда закрою, мы в 2024.1 перейдем на новый eclipse, если будет нужно, попробуете там еще, обещают исправить, попробуете, если что переоткроете
