### ISSUE TITLE
При создании расширения Префикс из мастера создания не применяется

### ISSUE THREAD

**Issue by DmitryShvaika** [1C-Company/1c-edt-issues#1245]
### Описание ошибки

Создаю расширение и указываю префикс

![image](https://github.com/1C-Company/1c-edt-issues/assets/54451084/60972570-5e1c-4937-8e27-3316dabcd97c)

Однако в созданном расширении префикс остается по умолчанию:

![image](https://github.com/1C-Company/1c-edt-issues/assets/54451084/71e295f3-6494-4be4-9705-ec619ac202a7)

### Как воспроизвести

1. Создать расширение с префиксом отличным от префикса по умолчанию
2. Наблюдать ошибку

### Ожидаемое поведение

Префикс в созданном расширении должен применяться из мастера создания

### Лог рабочей области

не требуется

### Версия 1С:EDT

Ruby 2023.2.1

### Операционная система

Windows

**Comment by beg7** [comment]
Исправлено в 2023.3.0
