### ISSUE TITLE
Ошибка конструктора описания типов

### ISSUE THREAD

**Issue by AnanyevAl** [1C-Company/1c-edt-issues#1253]
### Описание ошибки

Ошибка в том что конструктор описания типов не верно устанавливает параметры длины и точности числа

### Как воспроизвести

1. Перейдите в настройки шаблонов встроенного языка
2. Добавьте шаблон такого вида ${КонструкторОписанияТипов()}
3. В любом модуле вызовите данный шаблон и настройте для Числа длиной 15 точностью 2
4. В результате работы конструктора получаем 'Новый ОписаниеТипов("Число", Новый КвалификаторыЧисла(2, 15))'
Длина и точность перепутаны местами

### Ожидаемое поведение

Новый ОписаниеТипов("Число", Новый КвалификаторыЧисла(15, 2))

### Лог рабочей области

нет

### Версия 1С:EDT

Ruby 2023.2.1

### Операционная система

Windows

### Установленные плагины

Нет плагинов

**Comment by MaksimDzyuba** [comment]
Здравствуйте, исправил, точно будет в 2024.1, возможно и в 2023.3 перенесем
![bandicam-2024-02-05-18-52-43-963](https://github.com/1C-Company/1c-edt-issues/assets/77277424/b0a49ac7-4482-4ed4-8721-f20e5713998e)
