### ISSUE TITLE
Игнорирование точек останова при отладке web-клиента

### ISSUE THREAD

**Issue by AvalorOFF** [1C-Company/1c-edt-issues#1254]
### Описание ошибки

Файловая ИБ. Ведется разработка внешней обработки. Опубликовал ИБ, запустил отладку. В браузере через Файл - Открыть запускаю обработку. После ничего не происходит, точки останова игнорируются.

### Как воспроизвести

1. В новый проект импортирую ИБ;
2. К ИБ импортирую внешнюю обработку;
3. Публикую ИБ с помощью встроенного Apache, при этом ставлю галочку "Разрешить отладку" и прописываю url;
4. Во вкладке Веб-серверы нахожу опубликованную ИБ;
5. Перехожу по ссылке и получаю такой результат;
![image](https://github.com/1C-Company/1c-edt-issues/assets/151164037/40e2b9d1-10ed-436b-b0d0-aa4901d09afb)
6. Такой же результат получается при нажатии кнопки "Запуск" (Хочу отменить, при публикации ИБ без галочки "Разрешить отладку" запуск по ссылке проходит штатно);
7. Возможно, необходимо изменить конфигурацию запуска, попробовал изменять некоторые поля, изменений не обнаружил;
8. При нажатии кнопки "Отладка" проблемы пункта 5 не наблюдается;
9. В браузере через Файл - Открыть запускаю внешнюю обработку, которая лежит ....Имя_проекта/bin;
10. После открытия внешней обработки нажимаю кнопку на форме;
11. Далее программа просто отрабатывает без остановки на точке останова.

Другой вариант развития событий:
Продолжаем с пункта 9
10. После открытия внешней обработки захожу в EDT;
11. Открываю перспективу "Отладка";
12. Нажимаю кнопку "Приостановить";
13. Возвращаюсь в браузер и нажимаю на кнопку формы;
14. Точки останова отрабатывают штатно;
15. Нажимаю F5 и наблюдаю такой результат;
![image](https://github.com/1C-Company/1c-edt-issues/assets/151164037/0e339fa4-4e70-4cb0-ae4d-33629d5c6750)
16. Эту же ошибку можно получить нажима кнопки "Шаг в", "Шаг через", "Шаг возврата".

### Ожидаемое поведение

1. Открытие web-клиента по ссылке с включенной галочкой "Разрешить отладку";
2. Отработка точек останова.

### Лог рабочей области

[.log](https://github.com/1C-Company/1c-edt-issues/files/13484474/default.log)

### Версия 1С:EDT

Ruby 2023.2.2 (Эта же проблема возникала и на предыдущих версиях)

### Операционная система

Windows

### Установленные плагины

Нет плагинов

**Comment by DmitryBelov-e1c** [comment]
Добрый день. Согласно https://its.1c.ru/db/v8325doc#bookmark:dev:TI000001607, подобный сценарий работы (внешняя обработка + веб-клиент) официально не поддерживается со стороны Конфигуратора. Произвёл проверку на 8.3.24.1646, окна с ошибками со стороны Конфигуратора, указанные в задаче, не встретил. При этом если поставить отладчик на паузу, действительно Конфигуратор останавливается в первом модуле, куда пришло исполнение - во внешней обработке, и в дальнейшем в состоянии отлаживать этот код. Тем не менее, данная возможность не документирована, потому и исполнение её в Конфигураторе может привести к неожиданным ошибкам. Конкретно в вашем случае в логах также присутствует ошибка добавления платформенной dll для работы с Apahce х86 в конфигурационном файле (система не сумела её распарсить).
