### ISSUE TITLE
Ошибка обновления конфигурации "Файл - /Documents/ЗаказКлиента/Forms/ФормаСпискаДокументов/Ext/Form.xml: Неверный путь к данным: "Список.Номер".

### ISSUE THREAD

**Issue by Valiev1c** [1C-Company/1c-edt-issues#1257]
### Описание ошибки

Похожая ошибка рассматривалась в #831. Все что описано ниже - это тестовый вариант на конфигурации "Управление торговлей 11.5". Все то же самое было в рабочем проекте в конфигурации "Комплексная автоматизация 2.5".
Итак.
EDT Ruby 2023.2.2 (ошибка воспроизводилась также на Ruby 2023.2.1)
1. Создан (импортирован) проект из типовой конфигурации УТ 11.5. 
2. В проекте создано расширение "Заказ покупателя". 
3. Форма документа "ФормаСпискаДокументов" документа вида "ЗаказКлиента" помещено в расширение. 
4. В текст запроса динамического списка "Список" внесены изменения: добавлено поле "ИспользоватьЛистУчетаВремени" (тип: Булево). 
5. В элементы формы добавлена колонка "ИспользоватьЛистУчетаВремени", где тип данных указан "Список.ИспользоватьЛистУчетаВремени" (то что добавлено в текст запроса).
6. Сохранен проект
7. Выбрана база, выбран пункт меню "Обновить конфигурацию" 
8. Выбрано конкретное расширение, установлена галочка с признаком полного обновления расширения.
9. Получена ошибка типа
!MESSAGE Операция конфигурирования завершена неуспешно
Ошибка загрузки/выгрузки конфигурации
Файл - /Documents/ЗаказКлиента/Forms/ФормаСпискаДокументов/Ext/Form.xml: Неверный путь к данным: "Список.Номер".
...
Полное описание ошибки в логе во вложении

### Как воспроизвести

1. Создайте проект на базе типовой конфигурации, например, УТ 11.5 (на автоматической поддержке). 
2. Создайте расширение
3. Поместите в расширение форму "ФормаСпискаДокументов" документа вида "ЗаказКлиента". 
4. В текст запроса динамического списка "Список" внесите изменения: например, добавьте поле "ИспользоватьЛистУчетаВремени" (тип: Булево). 
5. В элементы формы добавьте колонку "ИспользоватьЛистУчетаВремени", тип данных укажите "Список.ИспользоватьЛистУчетаВремени" (то что добавлено в текст запроса).
6. Сохранен проект
7. Обновите конфигурацию, выбрав созданное расширение, установив галочку с признаком полного обновления расширения (можно и не устанавливать, ошибка воспроизводится в любом случае)

### Скриншоты

![image](https://github.com/1C-Company/1c-edt-issues/assets/134257801/b31f5959-9e5a-44f6-a469-343d178d368c)
![image](https://github.com/1C-Company/1c-edt-issues/assets/134257801/5a07c19a-1d96-4186-b0a9-6a06691af9f2)

### Ожидаемое поведение

Обновление должно пройти без ошибок

### Лог рабочей области

[.log](https://github.com/1C-Company/1c-edt-issues/files/13534191/default.log)

### Версия 1С:EDT

EDT Ruby 2023.2.2

### Операционная система

Windows

### Установленные плагины

Нет плагинов

### Дополнительная информация

Версия платформы 1С:Предприятие 8.3 (8.3.23.1688).

При экспорте расширения в XML и дальнейшем импорте расширения в конфигураторе получем ошибки
![image](https://github.com/1C-Company/1c-edt-issues/assets/134257801/d725e90d-7a9b-4818-a56c-edab501386ea)

**Comment by Valiev1c** [comment]
[#1133](https://github.com/1C-Company/1c-edt-issues/issues/1133) похожая ошибка

**Comment by vadimeg** [comment]
В 2023.3.1 исправлена проблема, вызывающая ошибку "Неверный путь к данным "Список.Номер"" в расширениях.
Если эта ошибка будет продолжать появляться в 2023.3.1, то просьба переоткрыть задачу.
По другим проблемам, если они связаны с другой диагностикой или поведением просьба создать отдельную задачу.
