### ISSUE TITLE
Ошибка при работе с проектом Внешних инструментов.

### ISSUE THREAD

**Issue by AndreyBsSF** [1C-Company/1c-edt-issues#1259]
### Описание ошибки

При работе с отдельным проектном внешних обработок неоднозначное поведение EDT.

**_Ошибка 1 :_** 
При загрузке внешней обработки из проекта основной конфигурации при помощи команды "Скопировать в проект внешних отчетов и обработок..." основной реквизит формы копируется с типом по шаблону <types>ExternalDataProcessor.ИмяОбъекта</types>

При загрузке внешней обработки из файловой системы при помощи кнопки Импорт основной реквизит формы копируется с типом по шаблону <types>ExternalDataProcessor**Object**.ИмяОбъекта</types>

**_Ошибка 2 :_**
Если в проекте внешних обработок основной реквизит формы указан с типом по формату <types>ExternalDataProcessor**Object**.ИмяОбъекта</types> выполнять слитие изменений из 1 ветки в другую, то сольется формат типа без слова Object - <types>ExternalDataProcessor.ИмяОбъекта</types>

Обе проблемы были обнаружены в том числе на более старых версия чем используется сейчас (2022.2.5)
Также проверено что в версии 2023.2.2 проблема повторяется.

### Как воспроизвести

Ошибка 1:
1. Создай Обработку в проекте основной конфигурации.
2. Создай форму в этой обработке, оставьте её без изменений.
3. Переместите обработку в проект внешних инструментов с помощью команды "Скопировать в проект внешних отчетов и обработок..."
4. Проверьте тип основной реквизита на форме обработки (ожидаем увидеть ExternalDataProcessor)
5. Выгрузите обработку из проекта внешних инструментов в файловую систему с помощью команды "Экспорт".
6. Загрузите выгруженную ранее обработку в проект внешних инструментов с помощью команды "Импорт"
7. Проверьте тип основной реквизита на форме обработки (ожидаем увидеть ExternalDataProcessorObject)

Ошибка 2:
8. Создайте новую ветку feature/createReport из исходного состояния репозитория.
9. Зафиксируйте загруженную через команду Импорт обработку (со значением ExternalDataProcessorObject) в ветке feature/createDP. В ветке feature/createDP только 1 коммит отличающийся от исходного состояния репозитория.
10. Создайте новую ветку feature/createReport из исходного состояния репозитория с обработкой.
11. Создайте в ветке feature/createReport новый отчет и зфвиксируйте изменения. В ветке feature/createReport только 1 коммит отличающийся от исходного состояния репозитория с отчетом.
12. Запустите процесс слития изменений в ветку feature/createReport из ветки feature/createDP.
13. Проверьте тип основной реквизита на форме обработки (ожидаем увидеть ExternalDataProcessor)

### Ожидаемое поведение

1. Одинаковый формат работы с типом основного реквизита формы внешних инструментов независимо от способа загрузки из в проект EDT.
2. Отсутствие отличий в ветках исходной с изменениями и текущей разрабатываемой при слитии изменений из первой во вторую.

### Лог рабочей области

[.log](https://github.com/1C-Company/1c-edt-issues/files/13628107/default.log)

### Версия 1С:EDT

2023.2.2

### Операционная система

Windows

### Установленные плагины

Нет плагинов

### Дополнительная информация

Версия платформы 1С-  8.3.22.1851
Конфигурация - самописная

**Comment by wolfandw** [comment]
Ошибка в некорректном импорте объектного типа внешних объектов. Ошибка исправлена в 2024.1, возможно будет включена в какой-то релиз ранее.
