### ISSUE TITLE
Модуль приложения расширения не поддерживает директивы После

### ISSUE THREAD

**Issue by DmitryShvaika** [1C-Company/1c-edt-issues#1265]
### Описание ошибки

Выдается сообщение, что модуль приложения у расширения не поддерживает директивы После.
Хотя конфигуратор ошибок не выдает, точка останова в данной процедуре при исполнении срабатывает.
Версия платформы 8.3.21

![image](https://github.com/1C-Company/1c-edt-issues/assets/54451084/e1ffecdf-5690-462b-9d39-9249e8a4fc95)

### Как воспроизвести

1. Создать расширение
2. В модуле приложения ввести текст
```
// @strict-types

#Область ОбработчикиСобытий

&После("ПриНачалеРаботыСистемы")
Процедура Расш1_ПриНачалеРаботыСистемы()
	
	// 
	
КонецПроцедуры

#КонецОбласти
```

3. Наблюдать ошибку

### Ожидаемое поведение

Ошибка не должна диагностироваться

### Лог рабочей области

не требуется

### Версия 1С:EDT

Ruby 2023.2.2

### Операционная система

Windows

**Comment by MaksimDzyuba** [comment]
Здравствуйте, ошибку исправили, спасибо, войдет в 2024.1
![image](https://github.com/1C-Company/1c-edt-issues/assets/77277424/3e68f157-dda4-4e6e-92bb-9f9d5e12a23e)
