### ISSUE TITLE
Ложное срабатывание проверки "Добавление типизированного значения в нетипизированную коллекцию" для полей в событии ОбработкаПолученияПолейПредставления

### ISSUE THREAD

**Issue by adminimusRU** [1C-Company/1c-edt-issues#1267]
### Описание ошибки

Параметр `Поля` события `ОбработкаПолученияПолейПредставления` в EDT имеет тип `Массив` вместо `Массив Из Строка`, что приводит к ложному срабатыванию проверки при строгой типизации.

### Как воспроизвести

1. Создать справочник
2. Ввести код в модуле менеджера:
```bsl
// @strict-types

#Если Сервер Или ТолстыйКлиентОбычноеПриложение Или ВнешнееСоединение Тогда

#Область ОбработчикиСобытий

Процедура ОбработкаПолученияПолейПредставления(Поля, СтандартнаяОбработка)
	
	СтандартнаяОбработка = Ложь;
	Поля.Добавить("Ссылка");

КонецПроцедуры

#КонецОбласти

#КонецЕсли
```

### Скриншоты

![image](https://github.com/1C-Company/1c-edt-issues/assets/28653631/1abc7360-d9dd-43fe-8734-6243f992bf7c)

### Ожидаемое поведение

Тип параметра должен быть корректным.

### Лог рабочей области

[log.zip](https://github.com/1C-Company/1c-edt-issues/files/13764682/log.zip)

### Версия 1С:EDT

2023.2.2

### Операционная система

Windows

**Comment by MaksimDzyuba** [comment]
Здравствуйте, исправили в 2024.1, возможно будет перенос в 2023.3
![image](https://github.com/1C-Company/1c-edt-issues/assets/77277424/bfdb3d47-59e8-4ec9-84ac-f95153c63394)
