### ISSUE TITLE
Некорректно связываются объекты проектов внешних отчетов и обработок

### ISSUE THREAD

**Issue by Mezijas** [1C-Company/1c-edt-issues#1271]
### Описание ошибки

Используем удаленный локальный репозиторий. Проблема проявлялась на разных версиях Edt, в том числе и на самой актуальной 2023.2.4. Время от времени обработки локального и удаленного репозитория некорректно связываются и при попытке сделать слияние между ветками. не получается установить сопоставление с корректной обработкой. (скрин ошибки приложил). В какой конкретно момент изначально проблема проявляется непонятно. Сценарий воспроизведения распишу, но получится ли его на пустом проекте воспроизвести или нет, непонятно... При попытке установить соответствие получаем ошибку Unhandled event loop exception

### Как воспроизвести

1. Внести изменение в внешний отчет.
2. Переключится на новую локальную ветку.
3. Сделать коммит изменений.
4. Переключиться на ветку мастер.
5. При попытке слияния получаем ошибку.

### Скриншоты

![image](https://github.com/1C-Company/1c-edt-issues/assets/46806209/99662a77-a60d-4848-8d7b-3819ad026e7a)
![image](https://github.com/1C-Company/1c-edt-issues/assets/46806209/dc73bba6-f0ca-463c-92b3-5a0efb5b9cde)

### Ожидаемое поведение

Корректное соответствие объектов между ветками.

### Лог рабочей области

[log.log](https://github.com/1C-Company/1c-edt-issues/files/13775747/log.log)

### Версия 1С:EDT

2024.2.4

### Операционная система

Windows

### Установленные плагины

1C:Code style V8, 1C:SSL-support, 1C:Language Tool

**Comment by traggerW** [comment]
Добрый день! Ошибки в механизме сопоставления объектов нет. Вероятнее всего вы выбрали объединение по стратегии сопоставления "Сначала по UUID, потом по имени", и в вашем случае объекты "Анализ продаж" (слева) и "ТОП100" (справа) имеют одинаковый UUID (это значит, что объект был переименован ранее). А второй узел соответствует новосозданному объекту "Анализ продаж" с иным UUID. 
Ошибка с сообщением в свою очередь возникает из-за того, что вы с одной стороны не объединяете узел "Анализ продаж - ТОП100", с другой стороны объединяете второй узел, то есть в итоге после объединения будет два узла "Анализ продаж", что недопустимо.
Чтобы обойти проблему, вы можете использовать другие стратегии сопоставления, либо вручную расставить галки в узлах объектов, чтоб не было конфликтов (например поставить галку в первом узле) - тогда объединение произойдет корректно.

Мы со своей стороны создали задачу об изменении сообщения в ошибке на более понятное, чтобы пользователям было ясно, как разрешать подобные ошибки
