### ISSUE TITLE
Иерархия вызовов не видит использование метода в регламентном задании

### ISSUE THREAD

**Issue by DmitryShvaika** [1C-Company/1c-edt-issues#128]
### Описание ошибки

Иерархия вызовов не видит, что метод назначен регламентному заданию.

### Как воспроизвести

1. Создайте проект
2. Создайте серверный модуль
3. Создайте экспортную процедуру в серверном модуле без параметров
4. Создайте регламентное задание
5. Назначьте новому регламентному заданию созданную процедуру
6. Постройте иерархию вызовов на созданной процедуре

### Скриншоты

![image](https://user-images.githubusercontent.com/54451084/142991192-cdaa9fc6-22ce-4e10-a1be-93a247d79253.png)

### Ожидаемое поведение

В результатах поиска должно отображаться использование процедуры в регламентном задании

### Лог рабочей области

[логи.zip](https://github.com/1C-Company/1c-edt-issues/files/7586625/default.zip)

### Версия 1С:EDT

Ruby 2021.2.10

### Операционная система

Windows

### Установленные плагины

1C:Code style V8, 1C:SSL-support

### Дополнительная информация

Дополнительно прилагаю архив проекта
[test.zip](https://github.com/1C-Company/1c-edt-issues/files/7586629/test.zip)

**Comment by marmyshev** [comment]
А почему это Баг?

Это правильное поведение - например для обработчиков событий элементов формы - то что так же - внешней старт действий (пользователем или регламентным заданием) является началом вызова - выше ничего нет.

**Comment by DmitryShvaika** [comment]
Тогда это пожелание. Так не видно, что метод вообще используется. А он используется.

**Comment by DmitryShvaika** [comment]
перепишу в Пожеление

**Comment by DmitryShvaika** [comment]
Просто думал: раз называется Иерархия вызовов, то должна и показывать откуда вызывается. А раз не показывает, значит баг :)

**Comment by KovAlexey** [comment]
@marmyshev 
>А почему это Баг?

Ну, например, потому что сначала происходит событие, которое вызывает первый метод? И очень логично было бы вызывающее событие видеть в структуре
