### ISSUE TITLE
Явное добавление параметризиуемой команды на форму приводит к ошибке конфигурирования

### ISSUE THREAD

**Issue by AntonChausov** [1C-Company/1c-edt-issues#1281]
### Описание ошибки

Если в форму добавить параметризуемую команду (не автоматически, а явно, например отключить автозаполнение панели и перенести команду из раздела "Команды" - "Глобальные команды" на форму, при обновлении БД возникает ошибка:
_Операция конфигурирования завершена неуспешно_
_Ошибка загрузки/выгрузки конфигурации_
....
_Неверный путь к данным "Элементы.Список.ТекущиеДанные.Ссылка"_ 

В конфигураторе данные действия к ошибке не приводят

### Как воспроизвести

1. Для справочника создать параметризуемую команду. В типе параметра указать ссылку на этот справочник
2. Создать форму списка
3. Явно, в ручную, вынести команду на форму
4. Попытаться обновить конфигурацию

### Скриншоты

![image](https://github.com/1C-Company/1c-edt-issues/assets/57135750/00c6b1d5-e23b-4e95-a653-a900adee04c2)

### Ожидаемое поведение

Команда добавляется на форму, конфигурация обновляется без ошибок

### Лог рабочей области

[logs.zip](https://github.com/1C-Company/1c-edt-issues/files/13904310/logs.zip)

### Версия 1С:EDT

Ruby 2023.2.2

### Операционная система

Windows

### Установленные плагины

1C:SSL-support, Другие сторонние плагины `Название плагина...`

### Дополнительная информация

Установлен плагин yaxunit, но и без него ошибка наблюдается

**Comment by vadimeg** [comment]
То же, что и https://github.com/1C-Company/1c-edt-issues/issues/1320
