### ISSUE TITLE
Импорт внешней обработки при включенном автономном сервере

### ISSUE THREAD

**Issue by petypen** [1C-Company/1c-edt-issues#1282]
### Описание ошибки

Если включено использование автономного сервера, то импорт внешних обработок заканчивается ошибкой. Если переключиться на использования агента конфигуратора, то импорт работает штатно. Ошибки в журналах.

### Как воспроизвести

Включить использование автономного сервера и импортировать внешнюю обработку. 

### Ожидаемое поведение

При включенном использовании автономного сервера импорт внешних обработок проходит без ошибок

### Лог рабочей области

[metadata.zip](https://github.com/1C-Company/1c-edt-issues/files/13906192/metadata.zip)

### Версия 1С:EDT

2023.3.0

### Операционная система

Windows

### Дополнительная информация

Платформа 8.3.24

**Comment by nikolay-martynov** [comment]
Здравствуйте, Евгений. К сожалению, для устранения данной проблемы придётся подождать выпуска обновления для платформы. При необходимости обращения в службу поддержки вы можете ссылаться на эту проблему как 60012001. Пока могу порекомендовать использовать обычное приложение на информационной базе при импорте внешних отчётов и обработок.

**Comment by nikolay-martynov** [comment]
Здравствуйте, Евгений. Работа автономного сервера была исправлена в следующих версиях платформы: 8.3.23.2114 и 8.3.24.1439.
