### ISSUE TITLE
Зависает "Обновление списка языков"

### ISSUE THREAD

**Issue by Jimmo910** [1C-Company/1c-edt-issues#1283]
### Описание ошибки

Ошибка в том что, в Состоянии появляется "Обновление списка языков (Ожидание отмены)"
И программа перестает что ли бо выполнять другое.

### Как воспроизвести

1. Не знаю как это воспроизвести на пустом проекте. Могу предоставить свой проект Расширения. https://t.me/Jimmi910

### Скриншоты

![image](https://github.com/1C-Company/1c-edt-issues/assets/122779512/62dec613-4234-421d-b1b9-9c3cf075eddf)

### Ожидаемое поведение

что бы не зависало

### Лог рабочей области

[trace.log](https://github.com/1C-Company/1c-edt-issues/files/13915714/trace.log)
[log.log](https://github.com/1C-Company/1c-edt-issues/files/13915720/log.log)

### Версия 1С:EDT

2023.2.4

### Операционная система

Windows

### Дополнительная информация

Это проект расширения для Комплексной автоматизации.
Пробывал создать все с нуля и заного импартировать из базы. все равно тоже самое.

**Comment by Jimmo910** [comment]
[threaddump.txt](https://github.com/1C-Company/1c-edt-issues/files/13915824/threaddump.txt)

**Comment by Erik773** [comment]
Здравствуйте @Jimmo910 !
Подскажите, пожалуйста, что значит фраза "программа перестает что ли бо выполнять другое":
невозможно запустить другие процессы и операции?
новые операции становятся в очередь процессов?
могли бы вы, пожалуйста, записать видео для лучшего понимания проблемы?

**Comment by Jimmo910** [comment]
сейчас конкретно в том место проблема ушла.
Но появилось дальше.
[threaddump.txt](https://github.com/1C-Company/1c-edt-issues/files/13916426/threaddump.txt)

видео могу куда то в ЛС скинуть.

**Comment by Jimmo910** [comment]
@Erik773 https://disk.yandex.ru/d/IZWe9QC62qL4-w

**Comment by Jimmo910** [comment]
все висит.
![image](https://github.com/1C-Company/1c-edt-issues/assets/122779512/dcfce0f0-b671-45d8-86c4-3537c2775795)

там памяти загружаю на диск

**Comment by Jimmo910** [comment]
дам памяти.
https://disk.yandex.ru/d/h8j_MMZiOz8kgA

**Comment by Jimmo910** [comment]
[trace.log](https://github.com/1C-Company/1c-edt-issues/files/13917969/trace.log)
[log.log](https://github.com/1C-Company/1c-edt-issues/files/13917971/log.log)
[threaddump.txt](https://github.com/1C-Company/1c-edt-issues/files/13917972/threaddump.txt)


закрыл через диспетчер то окно. Открыл заного.
Добавил в форму документа 5 строк кода.
Закомитил изменения.
попытался просто открыт конфигурацию. и она не открывается. Пишет загрузка....
Программа как бы отвечает, но по факту что бы не не делал оно не исполняет...
![image](https://github.com/1C-Company/1c-edt-issues/assets/122779512/64a1a000-1a1b-440d-9e57-7654bc0a8eb3)


Если я чем то могу еще помочь скажите.

**Comment by Erik773** [comment]
Судя по логам, зависаний нет, но есть очень долгие процессы.

Подскажите, пожалуйста, в последнее время были ли какие-либо изменения в окружении: обновление ОС, драйверов, антивируса, перенос на другой диск, виртуальной машины (если она используется), терминального сервера и тому подобное.

Возможно, понять причины подобного поведения, помогло бы профилирование ЕДТ. Поэтому могли бы вы, пожалуйста, настроить сбор результатов профилирования при возникновении проблемы:
1. Разместить по какому-то общему пути файл настроек профилирования (присоединенный к письму файл profiling-light.jfc). Стандартное размещение: <каталог установки JDK>/lib/jfr (в этом случае в параметрах запуска не нужно указывать полный путь к профилю. При размещении в другом месте - просто необходимо указать полный абсолютный путь к файлу настроек профиля).
2. Добавить в параметры запускаемого процесса (параметры Java для ring CLI, параметры Java для EDT CLI, 1cedt.ini или любыми другими средствами) настройки запуска JFR:
`-XX:StartFlightRecording=settings=profiling-light.jfc,filename=X:\resultDir,maxsize=10g -XX:FlightRecorderOptions=stackdepth=1024,repository=X:\resultDir\repo`

Где:
- settings=profiling-light.jfc - это выбор файла настроек профилирования. Допускает указание абсолютного пути в формате Windows или Linux (зависит от целевой ОС)
- filename=X:\resultDir\ - это каталог, в который будет помещен конечный результат, в виде файла вида hotspot-pid-3128-id-1-2023_12_11_09_49_47.jfr (где закодированы идентификатор процесса в ОС, дата и время). Данный файл записывается в случае, если произошел нормальный shutdown процесса Java. Важно: каталог должен быть создан до старта профайлинга, в противном случае вместо записи в каталог будет создан файл с именем resultDir. Также важно указания слэша (прямого или обратного, зависит от ОС) для указания того, что это каталог для размещения результатов, а не имя файла
- repository=X:\resultDir\repo\ - это каталог для записи временных фрагментов профиля (размером по 24Мб). При нормальном завершении процесса данные файлы удаляются профайлером, и результат сохраняется в resultDir. В случае, если процесс был завершен аварийно (принудительно, например) - то эти файлы могут быть использованы для анализа ситуацию, предшествующей завершению, каждый из них является полноценным профилем. Правила указания имени - такие же, как и для filename=

[profiling-light.jfc.docx](https://github.com/1C-Company/1c-edt-issues/files/13777068/profiling-light.jfc.docx)

У приложенного файла убрать .docx в конце.
С данными настройками почти не влияет на производительность.

**Comment by Erik773** [comment]
Здравствуйте @Jimmo910 !
Подскажите, пожалуйста, удалось ли вам настроить сбор результатов профилирования при возникновении проблемы?

**Comment by demony** [comment]
А как вы боретесь с этой проблемой ?

**Comment by demony** [comment]
![image](https://github.com/1C-Company/1c-edt-issues/assets/1720563/e707f54a-75f7-4169-83a6-570c0514240c)

**Comment by Erik773** [comment]
Здравствуйте @demony!

> Висит с фразой Update language list (Cancel Request), кажется, что оно в рекурсию ушло.

Могли бы вы, пожалуйста, по этой проблеме зарегистрировать отдельную задачу и приложить к ней логи и дамп потоков.

**Comment by demony** [comment]
Может кому-то поможет.
Все отвисает если несколько раз переключиться на перспективу Git и обратно.
