### ISSUE TITLE
Не сохраняется привязка события формы ПередЗаписью к процедуре, при обновлении конфигурации

### ISSUE THREAD

**Issue by lrRatibor** [1C-Company/1c-edt-issues#1285]
### Описание ошибки

сейчас если открыть конфигурацию в конфигураторе, то событие формы "ПередЗаписью" привязано, если загрузить приложенную конфигурацию в EDT. а потом обновить конфигурацию, то привязка теряется.

### Как воспроизвести

1. Загрузить приложенную конфигурацию через конфигуратор
2. Открыть форму Документы - МатериалыОбщестройПоПроекту - Формы - ФормаКонструкция
3. Убедиться, что у события формы "ПередЗаписью" есть привязка к процедуре
4. Импортировать в EDT, версия проекта 8.3.24. В EDT событие формы ещё с привязкой.
5. Обновить конфигурацию информационной базы (загрузить полностью)
6. перейти в конфигуратор, убедиться что привязки события к процедуре больше нет.

### Скриншоты

![image](https://github.com/1C-Company/1c-edt-issues/assets/125652316/a2c46360-66df-4813-b6ce-ed256106286b)
привязка в конфигураторе есть.

![image](https://github.com/1C-Company/1c-edt-issues/assets/125652316/fb1db374-918d-4dae-bdb3-2e44b233c6e8)
после обновления из EDT привязка события слетает

### Ожидаемое поведение

Привязка к процедурам должна оставатсья

### Лог рабочей области

[Журнал_Экспорт.log.txt](https://github.com/1C-Company/1c-edt-issues/files/13950457/_.log.txt)
[trace.log](https://github.com/1C-Company/1c-edt-issues/files/13950470/trace.log)

### Версия 1С:EDT

Ruby 2023.3.0

### Операционная система

Windows

### Установленные плагины

1C:Code style V8

### Дополнительная информация

1С:Предприятие 8.3 (8.3.24.1342)

**Comment by Erik773** [comment]
Здравствуйте @lrRatibor!

> Загрузить приложенную конфигурацию через конфигуратор

Могли бы вы, пожалуйста, прислать конфигурацию для воспроизведения проблемы?

**Comment by lrRatibor** [comment]
Прошу прощения, забыл добавить 
[1Cv8_Баг.zip](https://github.com/1C-Company/1c-edt-issues/files/13960541/1Cv8_.zip)

**Comment by MaksimDzyuba** [comment]
Здравствуйте, если взять Ваш cf загрузить в пустую информационную базу, затем выгрузить xml и загрузить его обратно, то будет тоже самое, платформа теряет данный обработчик. Причина этого в том, что в выгрузке в xml есть битое значение, по сути в cf есть битые данные. Выделил строку с битыми данными в xml. попробую завести на Платформу ошибку, дополнительно скину ее номер Вам, в EDT проблем не наблюдается

![image](https://github.com/1C-Company/1c-edt-issues/assets/77277424/ff6f3c80-6f00-4066-a464-a74b232bf9cb)

**Comment by MaksimDzyuba** [comment]
Вот ошибка, что я зарегистрировал в Платформе - 60012122

**Comment by nikolay-martynov** [comment]
@lrRatibor Скажите пожалуйста, не наблюдали ли вы эту проблему на 8.3.22 и 8.3.23?

**Comment by lrRatibor** [comment]
Если не ошибаюсь, проблемная форма была создана на версии 8.3.23 и там ошибки не было, а после перехода на 8.3.24 стала слетать привязка.

**Comment by nikolay-martynov** [comment]
Здравствуйте. Исправление доступно в платформе 1С:Предприятие начиная с версий 8.3.24.1564 и 8.3.25.1301. Соответствующие сборки можно скачать на https://releases.1c.ru/project/Platform83 В EDT требования к платформе будут повышены соответствующим образом в ближайшем выпуске.
