### ISSUE TITLE
При переходе к обработчику событий из контекстного меню элемента формы, всегда взводится признак модифицированности модуля.

### ISSUE THREAD

**Issue by Dumsik** [1C-Company/1c-edt-issues#1286]
### Описание ошибки

При переходе к обработчику событий из контекстного меню элемента формы, всегда взводится признак модифицированности модуля хотя никаких изменений в модуле не сделано

### Как воспроизвести

Найдите форму в которой есть заданные обработчики событий.
Убедитесь что признак модифицированности модуля форму не взведен (нет звездочки  в заголовке окна)
В консрукторе формы ПКМ на элементе у которого есть заданный обработчик событий затем пункт контекстного меню "События" и выберите заданный обработчик событий. 
Будет осуществлен переход к существующему обработчику событий. 
Признак модифицированности модуля будет взведен, хотя каких-то реальных модификаций в модуле не производилось.

### Скриншоты

![изображение](https://github.com/1C-Company/1c-edt-issues/assets/24560572/1b0b466f-7829-4734-99d8-4cba38597535)

### Ожидаемое поведение

При переходе на существующий обработчик события элемента формы признак модифицированности не взводится.

### Лог рабочей области

.

### Версия 1С:EDT

Ruby 2023.3.0

### Операционная система

Linux

### Установленные плагины

1C:Code style V8, 1C:SSL-support, 1C:Language Tool

**Comment by nikolay-martynov** [comment]
G5V8DT-24674

**Comment by tretyakevich** [comment]
Будет исправлено в следующей исправительной версии 2023.3
