### ISSUE TITLE
Зависание при слиянии GIT с конфликтами

### ISSUE THREAD

**Issue by goodwinvu** [1C-Company/1c-edt-issues#1287]
### Описание ошибки

При слиянии веток (сливалась доработанная конфигурация с веткой вендора с обновлением) дважды происходило зависание ЕДТ. При этом процесс не умирает, а держит высокую нагрузку на процессор и есть работа с памятью.

### Как воспроизвести

Воспроизвелось дважды, но на одном и том же проекте, при этом при слиянии были конфликты.

### Ожидаемое поведение

Ожидается, что слияние должно происходить без зависаний

### Лог рабочей области

логи
[logs.zip](https://github.com/1C-Company/1c-edt-issues/files/13975934/logs.zip)

дамп тут https://disk.yandex.ru/d/qblQU7FhHlxRxg

### Версия 1С:EDT

Ruby 2023.3.0

### Операционная система

Windows

### Установленные плагины

1C:Code style V8, 1C:SSL-support, Другие сторонние плагины `Название плагина...`

### Дополнительная информация

установлены плагины 
- Dev-Style Darkest Dark theme (https://marketplace.eclipse.org/content/darkest-dark-theme-devstyle)
- Disable EDT editing (https://github.com/marmyshev/edt-editing)
- YAXUnit. Расширение для запуска тестов (https://github.com/bia-technologies/yaxunit)

**Comment by tretyakevich** [comment]
Добрый день. К сожалению, не удается извлечь memory dump из присоединенного core dump-а.
Если есть возможность - попробуйте запустить jhsdb jmap --core ./1cedt.dmp --exe <путь до EDT>/1cedt.exe --binaryheap, возможно на оригинальной машине он сможет извлечься.

**Comment by tretyakevich** [comment]
Не удается воспроизвести в текущей версии (2024.1), дамп также не удалось проанализировать.
