### ISSUE TITLE
При отладке меняется кодировка в переменных

### ISSUE THREAD

**Issue by AKazakov1C** [1C-Company/1c-edt-issues#1288]
### Описание ошибки

Когда в переменных проваливаешься в тестовоу строку меняется кодировка на 
РћС€РёР±РєР° РїСЂРё С‡С‚РµРЅРёРё РѕС‚РІРµС‚Р° Р

https://github.com/1C-Company/1c-edt-issues/assets/116161950/04a9477a-e42b-45e5-96ea-921aaddc278d

### Как воспроизвести

https://github.com/1C-Company/1c-edt-issues/assets/116161950/04a9477a-e42b-45e5-96ea-921aaddc278d

### Ожидаемое поведение

читаемый текст

### Лог рабочей области

[копия.log](https://github.com/1C-Company/1c-edt-issues/files/13978564/default.log)
[trace.log](https://github.com/1C-Company/1c-edt-issues/files/13978572/trace.log)

### Версия 1С:EDT

2023.2.4

### Операционная система

Windows

### Установленные плагины

1C:Code style V8, 1C:SSL-support, 1C:Language Tool, Другие сторонние плагины `Название плагина...`

### Дополнительная информация

1С:Предприятие 8.3 (8.3.23.1912)

**Comment by DmitryBelov-e1c** [comment]
Поведение будет исправлено в EDT 2024.1
