### ISSUE TITLE
В новом документе не исчезает ошибка Реквизит "Комментарий" имеет недопустимый тип / Многострочный режим после установки признака Многострочный режим

### ISSUE THREAD

**Issue by DmitryShvaika** [1C-Company/1c-edt-issues#1292]
### Описание ошибки

В новом документе не исчезает ошибка Реквизит "Комментарий" имеет недопустимый тип / Многострочный режим после установки признака Многострочный режим

![image](https://github.com/1C-Company/1c-edt-issues/assets/54451084/2455c357-708a-4cbc-a073-a500d6ba8868)

### Как воспроизвести

1. Создать пустой проект
2. Создать документ, заполнить его представление
3. Добавить в документ поле Комментарий
4. Установить тип поля Комментарий в Строка неограниченной длины
5. Установить у поля Комментарий Многострочный режим
6. Дождаться завершения всех проверок
7. Наблюдать, что ошибка Реквизит "Комментарий" имеет недопустимый тип / Многострочный режим осталась.

Если затем обновить информационную базу, удалить проект и заново его загрузить, то ошибка исчезнет.

### Ожидаемое поведение

ошибка должна исчезать после установки признака Многострочный режим

### Лог рабочей области

не требуется

### Версия 1С:EDT

Ruby 2023.3.0

### Операционная система

Windows

**Comment by vadimeg** [comment]
Исправлено в 2023.3 (исправительная версия)
