### ISSUE TITLE
Процесс агента конфигуратора навсегда "портится" после ошибки проверки ключа защиты

### ISSUE THREAD

**Issue by tormozit** [1C-Company/1c-edt-issues#1295]
### Описание ошибки

Выполняю импорт конфигурации из файловой базы 8.3.23 в проект EDT. 

![изображение](https://github.com/1C-Company/1c-edt-issues/assets/11896251/e830b403-06dd-4fd1-b2ef-c13609b40fc4)

Возникла ошибка проверки ключа (иногда такое случается у нас).

Ошибка взаимодействия с платформой 1С:Предприятия 8.3.22.2283:
Операция конфигурирования завершена неуспешно
Ключ защиты программы больше не доступен! Работа программы завершена.

После этого процесс агента конфигуратора навсегда "портится" и каждый раз выдает эту ошибку. Если его убить, то потом он каждый раз нормально продолжает работать.

Есть дамп процесса конфигуратора в таком состоянии.

![изображение](https://github.com/1C-Company/1c-edt-issues/assets/11896251/bc4f8d7c-48d7-4a5a-b5ae-b083fa807ea5)

### Как воспроизвести

я

### Скриншоты

я

### Ожидаемое поведение

я

### Лог рабочей области

я

### Версия 1С:EDT

2022.2.5

### Операционная система

Windows

### Установленные плагины

Нет плагинов

**Comment by tormozit** [comment]
Удалось открыть инцидент через тех. поддержку платформы? Полагаю они должны запросить файл. Можно скинуть мне параметры ftp ресурса через телеграм @tormozit

**Comment by nikolay-martynov** [comment]
Здравствуйте, Сергей. Если вам удастся собрать технологический журнал платформы и выявить какую-то закономерность как воспроизвести проблему с лицензионным ключом, то пожалуйста приложите эти данные и заново откройте эту запись. К сожалению, на настоящий момент проблему с лицензией повторить не получается.
