### ISSUE TITLE
Инструменты просмотра значений переменных не разворачивают элементы соответствия или элементы вложенного соответствия

### ISSUE THREAD

**Issue by Shmookoff** [1C-Company/1c-edt-issues#1296]
### Описание ошибки

"Корневое" соответствие `а`;  
Соответствие `б`;  
Вставить в `б` элемент `"в"`;  
Вставить в `а` элемент `"б"` со значением `б`.  

При попытке развернуть элементы соответствия `а`:
- Всплывающее окно (появляющееся при курсоре на `а`) и панель "Переменные" не показывают элементы соответствия `а`.
- Окно "Инспектировать" и панель "Выражения" корректно отображают элементы соответствия `а`, но не отображают элементы вложенного соответствия `б`.

### Как воспроизвести

```bsl
а = Новый Соответствие;
б = Новый Соответствие;
б.Вставить("в", "в");
а.Вставить("б", б);
```

В режиме отладки:
- навести курсором на `а`
- выделить переменную `а`, нажать Shift+F9

### Скриншоты

1. Всплывающее окно
![image](https://github.com/1C-Company/1c-edt-issues/assets/23117885/5bb15214-50c5-4a34-9cf8-d605c4f20b2f)
2. При попытке раскрыть элементы, стрелочка исчезает
![image](https://github.com/1C-Company/1c-edt-issues/assets/23117885/19b32706-d357-4095-a000-bc4d14d2313b)
Панель "Переменные" имеет идентичное поведение.

3. Окно "Инспектировать"
![image](https://github.com/1C-Company/1c-edt-issues/assets/23117885/6661f341-02af-4361-b5dd-a248abb92d64)
4. При попытке раскрыть элементы, стрелочка исчезает
![image](https://github.com/1C-Company/1c-edt-issues/assets/23117885/d5a28412-269a-4a97-af2b-9dc48c095502)
Панель "Выражения" имеет идентичное поведение.

### Ожидаемое поведение

Во всех инструментах просмотра значений переменных:
- При раскрытии элементов "корневого" соответствия `а`, должны отображаться элементы вышеупомянутого соответствия.
- При раскрытии элементов вложенного в `а` соответствия `б`, должны отображаться элементы вышеупомянутого соответствия.

Также, значения элементов соответствия, вложенного в другие типы данных (массив точно работает), отображаются корректно (в окне "Инспектировать" и панели "Выражения").

### Лог рабочей области

[журнал.log](https://github.com/1C-Company/1c-edt-issues/files/14048241/default.log)
[.log](https://github.com/1C-Company/1c-edt-issues/files/14048256/default.log)
[trace.log](https://github.com/1C-Company/1c-edt-issues/files/14048258/trace.log)

### Версия 1С:EDT

Ruby 2023.2.2

### Операционная система

Windows

### Установленные плагины

1C:Code style V8, 1C:SSL-support, 1C:Language Tool, Другие сторонние плагины `Название плагина...`

### Дополнительная информация

Другие сторонние плагины:
-   1C:EDT CF builder	1.3.5.v202302060557	ru.yanygin.dt.cfbuilder.plugin.ui.feature.feature.group	Yanygin Sergey (https://github.com/YanSergey)

**Comment by RedMammoth** [comment]
Возможно дубль https://github.com/1C-Company/1c-edt-issues/issues/606

**Comment by Shmookoff** [comment]
@RedMammoth действительно. обновил до последней версии платформу и edt, работает.
