### ISSUE TITLE
Редактор запроса динамического списка пропускает ошибку вида "ЗНАЧЕНИЕ(Перечисление.Перечисление.ИмяПеречисления.ЗначениеПеречисления)"

### ISSUE THREAD

**Issue by LesN1ck** [1C-Company/1c-edt-issues#1299]
### Описание ошибки

Для динамического списка с произвольным запросом не диагностируется ошибка, если в тексте запроса присутствует конструкция вида "ЗНАЧЕНИЕ(Перечисление.Перечисление.ИмяПеречисления.ЗначениеПеречисления)". При этом, если данный динамический список выведен на форму, при попытке обновить приложение будет диагностирована ошибка следующего вида:

```
Операция конфигурирования завершена неуспешно
Ошибка загрузки/выгрузки конфигурации
Файл - /DataProcessors/Обработка/Forms/Форма/Ext/Form.xml: Неверный путь к данным: "ДинСписок.Поле1".
```

При этом похоже, что данная проблема касается только перечислений - попытка добавить несуществующее выражение для других типов объектов приводит к ошибке сразу в редакторе текста запроса, что и является ожидаемым поведением среды разработки.

### Как воспроизвести

1. Создать форму
2. Добавить на форме реквизит с типом "ДинамическийСписок"
3. Включить у реквизита признак "Произвольный запрос"
4. Перейти по гиперссылке настройки списка
5. В текст запроса добавить конструкцию вида:
```
Выбрать
	Значение(Перечисление.Перечисление.Перечисление1.ЗначениеПеречисления1) КАК Поле1
```
6. Убедиться, что ошибки не возникает
7. Вывести реквизит на форму
8. Запустить обновление приложения
9. Убедиться, что выходит ошибка вида "Неверный путь к данным"

### Скриншоты

![image](https://github.com/1C-Company/1c-edt-issues/assets/114978535/a48c418d-d32a-45dc-87ba-1e88d2212d14)

![image](https://github.com/1C-Company/1c-edt-issues/assets/114978535/4fe1884d-1388-4132-8b0f-126aa43e06a1)

### Ожидаемое поведение

Необходимо диагностировать данную ошибку и выводить сразу же, в редакторе текста запроса - так, как это происходит со справочниками, например:

![image](https://github.com/1C-Company/1c-edt-issues/assets/114978535/719db34c-517c-47de-986e-d430a369ccec)

### Лог рабочей области

[log.log](https://github.com/1C-Company/1c-edt-issues/files/14081472/log.log)
[trace.log](https://github.com/1C-Company/1c-edt-issues/files/14081474/trace.log)

### Версия 1С:EDT

Ruby 2023.3.0

### Операционная система

Windows

### Установленные плагины

1C:Code style V8, 1C:SSL-support

**Comment by MaksimDzyuba** [comment]
Здравствуйте, ошибку воспроизвел, исправил в рамках 2024.1
![bandicam-2024-03-07-18-09-15-817](https://github.com/1C-Company/1c-edt-issues/assets/77277424/054f57fb-7cf4-4211-93dc-d47cf4ff0567)
