### ISSUE TITLE
Проблема при сравнении и объекдинении с базой. The project is now merging with the infobase changes. You should complete or cancel current merge session first.

### ISSUE THREAD

**Issue by DitriXNew** [1C-Company/1c-edt-issues#13]
## Опишите ошибку

В момент обновления базы - система показала что есть обновления. Я ткнул - сравнить. Система вывела окно, в котором сказала что сравнивать нечего. При повторном обновлении - система сказала что база уже находится в режиме мержа.

## Скриншоты

![image](https://user-images.githubusercontent.com/11927866/139451150-225baecc-1568-4871-8eb3-dca973765bb5.png)

## Лог рабочей области
 
[trace.log](https://github.com/1C-Company/1c-edt-issues/files/7442601/trace.log)
[1.log](https://github.com/1C-Company/1c-edt-issues/files/7442604/1.log)

## Окружение (пожалуйста укажите информацию):

 - Версия 1C:EDT [например] '2021.2.6'
 - 1С 8.3.18.1563

**Comment by AlmazNasibullin** [comment]
@DitriXNew Дмитрий, ошибка исправлена, исправление будет доступно в версии 2021.3.
