### ISSUE TITLE
Редактор запроса не выдает ошибку при использовании в запросе полей из других подзапросов, даже если таблицы нет в списке таблиц запроса

### ISSUE THREAD

**Issue by DmitryShvaika** [1C-Company/1c-edt-issues#130]
### Описание ошибки

Запрос с текстом ниже должен на выражение Таблица1.поле1 = Таблица22.Поле2 выдавать ошибку, так как таблицы Таблица1 нет в списке таблиц третьего запроса.

выбрать 
	1 КАК поле1
ПОМЕСТИТЬ Таблица1

;

ВЫБРАТЬ 
	2 КАК Поле2
ПОМЕСТИТЬ Таблица2
;

ВЫБРАТЬ
	*
ИЗ Таблица2 КАК Таблица21
	ВНУТРЕННЕЕ СОЕДИНЕНИЕ Таблица2 КАК Таблица22
	ПО Таблица1.поле1 = Таблица22.Поле2
	

### Как воспроизвести

1. Введите указанный ваше запрос в редактор запроса
2. Наблюдайте отсутствие ошибки

### Скриншоты

![image](https://user-images.githubusercontent.com/54451084/143205247-e481fdcc-5766-4b7f-8b03-210f644ff4cd.png)

### Ожидаемое поведение

Должна выдаваться ошибка "Таблица Таблица1 не найдена" или аналогичная.

### Лог рабочей области

[логи.zip](https://github.com/1C-Company/1c-edt-issues/files/7594096/default.zip)

### Версия 1С:EDT

Ruby 2021.2.10

### Операционная система

Windows

### Установленные плагины

1C:Code style V8, 1C:SSL-support

**Comment by MaksimDzyuba** [comment]
Здравствуйте, ошибку исправил, войдет в 2022.2.

Ваш пример еще не много усложнил для точности работы
![image](https://user-images.githubusercontent.com/77277424/192708201-dcae4bd4-575b-4f5b-8763-841093e895f6.png)
