### ISSUE TITLE
В диалоге выбора обработчика события регламентного задания сделать поиск.

### ISSUE THREAD

**Issue by DmitryShvaika** [1C-Company/1c-edt-issues#1310]
### Описание проблемы

В диалоге выбора обработчика события регламентного задания сделать поиск.
В больших  конфигурациях очень много модулей и "подходящих" процедур.
Поэтому список выбора бывает насчитывает десятки тысяч строк, причем не по алфавиту.
Найти в нем что-то порой нереально.

![image](https://github.com/1C-Company/1c-edt-issues/assets/54451084/e21fcab5-1ddc-4032-990a-f4622f55bb12)

### Описание решения проблемы

Предлагаю сделать сортировку по алфавиту + поиск

**Comment by adminimusRU** [comment]
Дубль #748
