### ISSUE TITLE
Разная стратегия импорта конфигурации из БД при использование автономного сервере и конфигуратора

### ISSUE THREAD

**Issue by alxint** [1C-Company/1c-edt-issues#1311]
### Описание ошибки

При использование автономного сервера выгрузка происходит с использованием команды
Sending to designer agent: config dump-files --dir="xml-import-XXXXX" --archive="xml.zip"
а при использование конфигуратора
/DumpConfigToFiles /tmp/1cedt/xml-import-XXXXX -format Hierarchical -ignoreUnresolvedReferences -Archive xml.zip

то есть добавляется ключ -ignoreUnresolvedReferences с которым не выгружаются потерянные ссылки, за счет этого результаты выгрузки различаются

### Как воспроизвести

Импортировать конфигурацию с помощью автономного сервера, затем импортировать ту же конфигурацию стандартным способом, сравнить полученные исходники.

### Ожидаемое поведение

При выгрузке автономным сервером использовать те же ключи

### Лог рабочей области

[.log](https://github.com/1C-Company/1c-edt-issues/files/14204550/default.log)

### Версия 1С:EDT

Ruby 2023.3

### Операционная система

Linux

**Comment by nikolay-martynov** [comment]
Здравствуйте. Да, действительно не всегда указывается параметр `-ignoreUnresolvedReferences` и тогда выгрузка от платформы содержит битые ссылки в виде уникальных идентификаторов. Однако, EDT эти идентификаторы вместо символьных ссылок-путей игнорирует. В итоге, что есть `-ignoreUnresolvedReferences`, что нет `-ignoreUnresolvedReferences`, после импорта платформенной выгрузки в EDT в исходниках проекта будет просто `<type/>`. Если после этого обновить информационную базу, то и в ней битая ссылка будет очищена и в дальнейшем от платформы начнёт приходить `<Type/>` вне зависимости от того, какие флажки были или не были указаны. То есть после цикла импорт/экспорт никаких новых изменений уже не будет вне зависимости от флажков.
В связи с этим, прошу вас помочь со следующими вопросами:

- Вы принимаете в сравнении/объединении все изменения после импорта конфигурации из информационной базы? В частности изменения в ссылках. Если нет, то расскажите пожалуйста почему.
- Вы фиксируете в git все изменения в исходных файлах проекта после импорта конфигурации из информационной базы? В частности изменения в ссылках. Если нет, то расскажите пожалуйста почему.
- Вы нашли какой-то пример когда битая ссылка, выгруженная из информационной базы, не сбрасывается, а присутствует в исходных текстах проекта как уникальный идентификатор? Подскажите пожалуйста на каких объектах так происходит. Буду очень благодарен, если вы поделитесь примером такой базы/конфигурации.
- Какого поведения вы ожидаете после цикла импорт из информационной базы / загрузка в информационную базу / импорт из информационной базы? Что по вашему мнению должно показать первое и второе сравнение/объединение? Какие изменения должны отобразиться в git? Какие изменения должны быть отображены при сравнении в конфигураторе?

**Comment by alxint** [comment]
Насколько я помню, при импорте в исходниках битые ссылки не очищаются, поэтому получаем такой сценарий, загружаем из конфигуратора через автономный сервер, загружаем обратно из ЕДТ в конфигурацию (я так понимаю в этот момент ссылки очищаются, то есть в платформенном xml их уже нет), затем что-то делаем в конфигураторе, пытаемся импортировать изменения из конфигуратора в ЕДТ и натыкаемся на различия во всех битых ссылках.

**Comment by alxint** [comment]
Как оказалось, есть еще один нюанс, если мы импортируем в ЕДТ конфигурацию на поддержке с помощью конфигуратора, то получаем исходник ЕДТ с битыми ссылками, выгружаем ту же конфигурацию в платформенных XML из конфигуратора, потом загружаем в ЕДТ из XML, то получим уже исходники с очищенными ссылками

**Comment by alxint** [comment]
> Вы нашли какой-то пример когда битая ссылка, выгруженная из информационной базы, не сбрасывается, а присутствует в исходных текстах проекта как уникальный идентификатор? Подскажите пожалуйста на каких объектах так происходит. Буду очень благодарен, если вы поделитесь примером такой базы/конфигурации.

В какой момент она должна сброситься? Ее не должно быть в исходниках ЕДТ? Или ее не должно быть в платформенном XML при экспорте?

> Какого поведения вы ожидаете после цикла импорт из информационной базы / загрузка в информационную базу / импорт из информационной базы? Что по вашему мнению должно показать первое и второе сравнение/объединение? Какие изменения должны отобразиться в git? Какие изменения должны быть отображены при сравнении в конфигураторе?

Логично было бы после цикла импорт-экспорт-импорт в последнем сравнение не увидеть различий

**Comment by NikitaMikhaylovSB** [comment]
Выгрузка битых ссылок управляется на стороне конфигуратора, см. https://dl03.1c.ru/content/Platform/8_3_21_1674/1cv8upd_8_3_21_1674.htm#a1778b70-a123-11ec-aa69-0050569f678a

**Comment by nikolay-martynov** [comment]
> получаем исходник ЕДТ с битыми ссылками
У вас есть готовый пример, когда так происходит или может быть сценарий как это воспроизвести? Потому как в обычном случае, когда EDT считывает выгрузку от платформы, и там сидит числовой идентификатор вместо пути к данным, то EDT такую ссылку просто игнорирует. После завершения импорта такой выгрузки в EDT мы получим пустую ссылку в исходниках проекта. Это изменение будет видно в панели "Индексирование Git". Если этого произвести обновление конфигурации информационной базы, то и там ссылка будет сброшена и при дальнейших выгрузках останется пустой. Если вы применяли изменения в сравнении/объединении во время импорта конфигурации из информационной базы и после этого фиксировали изменения в исходном тексте проекта в системе контроля версий, то изменениям взяться неоткуда.
Они могут появляться только в случае, если битая ссылка из платформенной выгрузки попадает в исходный текст проекта. Пока я не вижу как бы такое могло происходить. Если у вас есть такой пример, то пожалуйста поделитесь.

**Comment by alxint** [comment]
> У вас есть готовый пример, когда так происходит или может быть сценарий как это воспроизвести?

EDT 2023.3, платформа 22, типовая на поддержке к примеру Розница 2.3.16, загружаем в едт через через конфигуратор. Потом выгружаем в конфигураторе в XML с опцией очищать битые ссылки, грузим в новый проект ЕДТ, сравниваем проекты

**Comment by nikolay-martynov** [comment]
Здравствуйте. Подскажите пожалуйста, для чего вы сравниваете исходный текст проекта, который вы редактируете и загружаете в информационную базу, с тем, что получается после импорта вызрузки из конфигуратора с очисткой битых ссылок? И, если можно, то второй вопрос: после импорта из информационной базы после добавления очистки ссылок, эти битые ссылки пропадут и в исходном тексте проекта в EDT будет немало изменений, которые, например, будут отображаться в панели Индексирование Git. Это для вас является ожидаемым?

**Comment by alxint** [comment]
> Здравствуйте. Подскажите пожалуйста, для чего вы сравниваете исходный текст проекта, который вы редактируете и загружаете в информационную базу, с тем, что получается после импорта вызрузки из конфигуратора с очисткой битых ссылок?

Похоже вы немного не понимаете, в чем проблема, тогда немного другой сценарий, к примеру с разработкой расширений.

1. Начинаем работать с новой базой, загружаем типовую конфигурацию в EDT c использованием автономного сервера
2. Разрабатываем свое расширение
3.  Обновляем типовую конфигурацию
4. Загружаем обновленную базу, но уже без использования автономного сервера
5. Сравниваем предыдущую и обновленную конфигурацию, получаем несколько сотен фантомных различий (вот на этом этом этапе идем во внешние инструменты сравнения, чтобы понять, что поменялось, а что нет)

> И, если можно, то второй вопрос: после импорта из информационной базы после добавления очистки ссылок, эти битые ссылки пропадут и в исходном тексте проекта в EDT будет немало изменений, которые, например, будут отображаться в панели Индексирование Git. Это для вас является ожидаемым?

Да, ожидаемо, если это произойдет один раз, можно будет скинуть в отдельный коммит и понимать, что это за изменения

P.S. Изначально тема вопроса не в том, что различные ключи, а в том, что при импорте через автономный сервер и через конфигуратор одной и той же конфигурации мы получаем разные результаты, хотя оба способа описаны как идентичные по результату

**Comment by alxint** [comment]
> У вас есть готовый пример, когда так происходит или может быть сценарий как это воспроизвести? Потому как в обычном случае, когда EDT считывает выгрузку от платформы, и там сидит числовой идентификатор вместо пути к данным, то EDT такую ссылку просто игнорирует.

Вот к примеру кусок исходника типовой конфигурации с битыми ссылками:

```
<?xml version="1.0" encoding="UTF-8"?>
<mdclass:Subsystem xmlns:mdclass="http://g5.1c.ru/v8/dt/metadata/mdclass" uuid="abdb6f8e-20c1-4d6e-871b-da912b365aeb">
  <name>Налоги</name>
  <synonym>
    <key>ru</key>
    <value>Налоги</value>
  </synonym>
  <includeHelpInContents>true</includeHelpInContents>
  <includeInCommandInterface>true</includeInCommandInterface>
  <content>InformationRegister.СтавкиНалогаНаПрибыльВБюджетСубъектовРФ</content>
  <content>ab5cab32-ce67-4886-ab3b-71a811b45ee0</content>
  <content>6c2935e1-ec77-48ea-8bad-8336534a65b8</content>
  <content>0190ce0f-65ef-4ac9-a944-b87492058f67</content>
  <content>DataProcessor.ПанельТорговыйСбор</content>
  <content>Catalog.ВидыДеятельностиЕНВД</content>
  <content>CommonCommand.НалогНаПрибыль</content>
  <content>CommonCommand.НДС</content>
  <content>InformationRegister.НастройкиУчетаНДФЛ</content>
  <content>InformationRegister.НастройкиУчетаСтраховыхВзносовИП</content>
  <content>InformationRegister.НастройкиУчетаУСН</content>
  <content>InformationRegister.НастройкиУчетаСтраховыхВзносовИП_ПФР_ФФОМС</content>
  <parentSubsystem>Subsystem.Справочники</parentSubsystem>
</mdclass:Subsystem>
```

**Comment by nikolay-martynov** [comment]
Здравствуйте. Изменение будет доступно в версии 2024.1. Рекомендую внимательно ознакомиться с описанием выпуска. Процедура очистки информационной базы от неверных ссылок отличается от процедуры очистки от них проекта. Есть свои особенности. Также свои особенности есть и у командного интерфейса, внешних обработок и отчётов. Для них пока всё остаётся по старому. Надо ли с ними что-то делать и что именно - требует отдельного рассмотрения. Если у вас есть какие-то пожелания на данный счёт, то буду благодарен, если вы их выскажете в отдельной задаче.
