### ISSUE TITLE
Открываются много дублирующих окон сравнения/объединения в момент открытия настроек динамического списка из какой либо формы его содержащей

### ISSUE THREAD

**Issue by JaneGlass73** [1C-Company/1c-edt-issues#1314]
### Описание ошибки

Открываются дополнительные дублирующие окна сравнения/объединения помимо уже открытого. 
Открытие нескольких дополнительных окон происходит если открыть любую форму, а потом из неё открыть настройки динамического списка. 
Если настройки дин.списка закрыть, то дополнительно открытые она сравнения/объединения остаются. 
Если открыть настройки другого дин.списка или этого же открывается ещё столько же дополнительных окон сравнения/объединения.
_**Но самое ужасное**_, что при попытке закрыть любое из них - закрываются все, включая и основное, которое было открыто до открытия форм и настроек.

### Как воспроизвести

1. Открыть сравнение / объединение (например слить ветку в текущую)
2. Открыть форму, содержащую дин.список 
3. В форме открыть настройки дин. списка.
4. Появятся дублирующие окна сравнения/объединения
Подробнее см. на видео ниже

### Скриншоты

Видео, демонстрирующее некорректное поведение
https://youtu.be/PQUQUKykmvQ

### Ожидаемое поведение

Дополнительных окон сравнения/объединения не появляется.

### Лог рабочей области

[log.txt](https://github.com/1C-Company/1c-edt-issues/files/14222672/log.txt)

### Версия 1С:EDT

Ruby 2023.2.4

### Операционная система

Windows

### Установленные плагины

Нет плагинов

### Дополнительная информация

Платформа 8.3.23.1997
Всё не было бы так возможно печально, если бы можно было дополнительные окна вручную закрыть не закрыв основного окна сравнения/объединения.

**Comment by Erik773** [comment]
Здравствуйте Евгения!
К сожалению, не удается воспроизвести ошибку по описанному сценарию. 
https://github.com/1C-Company/1c-edt-issues/assets/93516265/fd37e361-26a0-4f70-b9cf-c3de336c7296
Есть ли у вас возможность предоставить доступ к репозиторию, на котором воспроизводится проблема?
Соответствует ли окружение системным требованиям  https://edt.1c.ru/docs/intro/requirements.php, если возможно укажите, пожалуйста, параметры ПК тип жесткого диска?
Сколько клиентов ЕДТ и платформы было запущенно одновременно?

**Comment by JaneGlass73** [comment]
@Erik773 , Здравствуйте пришло письмо уведомление от github, что не получается воспроизвести, но тут почему то сообщения уже не вижу. Уже воспроизвели?

По вопросам:

> Есть ли у вас возможность предоставить доступ к репозиторию, на котором воспроизводится проблема?

Да, могу прислать зеркальную копию (желательно не в паблик), репозиторий в закрытом хранилище, со мной можно в телеге списаться https://t.me/JaneGlass73 

> Соответствует ли окружение системным требованиям https://edt.1c.ru/docs/intro/requirements.php, если возможно укажите, пожалуйста, параметры ПК тип жесткого диска?

64Гб/i7/NVRAM Samsung EVO960
openjdk 11.0.18 2023-01-17 LTS
OpenJDK Runtime Environment (build 11.0.18+10-LTS)
OpenJDK 64-Bit Server VM (build 11.0.18+10-LTS, mixed mode)
Под кучу явы выделено 12Гб 

> Сколько клиентов ЕДТ и платформы было запущенно одновременно?
Я одна, на ПК стоит ещё виртуалка, на ней postgres и платформа 8.3.23.1997 крутится

Попробуйте тоже самое с моими настройками, возможно проблема в них:
[EDT_Configuration.zip](https://github.com/1C-Company/1c-edt-issues/files/14259003/EDT_Configuration.zip)
Или,  давайте, я попробую ту же операцию на дефолтных (за исключением кучи) настройках EDT и отпишусь.

**Comment by Erik773** [comment]
Здравствуйте Евгения!
К сожалению, не удалось воспроизвести проблему по описанному сценарию.
https://github.com/1C-Company/1c-edt-issues/assets/93516265/48f60af4-56ec-4635-b0f9-ad0f11a1e022
Могли бы вы, пожалуйста, уточнить, что именно делаете в окне настройки дин. списка, судя по видео, вы активно пользуетесь клавиатурой. Интересует, какие сочетания клавиш вы нажимаете после открытия окна настройки дин. списка?

**Comment by Erik773** [comment]
> пришло письмо уведомление от github, что не получается воспроизвести, но тут почему то сообщения уже не вижу. Уже воспроизвели?

Нет, решил перепроверить еще пару сценариев, но результат, тот же.

**Comment by JaneGlass73** [comment]
> Интересует, какие сочетания клавиш вы нажимаете после открытия окна настройки дин. списка?

Никакие не нажимала. Мышкой тыкала. Вот как только форма редактирования динсписка открылась, я вообще ничего не нажимаю, она сама так дёргается в процессе открытия окон.

**Comment by Erik773** [comment]
> По результату отпишусь, если не получится, тогда напишите куда прислать зеркальную копию хранилища.

Хорошо, спасибо, будем ждать результатов.

**Comment by JaneGlass73** [comment]
> Хорошо, спасибо, будем ждать результатов.

@Erik773 , неутешительные, всё то же самое

https://github.com/1C-Company/1c-edt-issues/assets/144486006/798c8173-7e86-4c10-81e7-0716b08e2ca5

Ссылка на репозиторий: [https://gitlab.com/JaneGlass/VD](url)

Слить ветку Vendor в dev/107
