### ISSUE TITLE
Ошибочная проверка "adoptable-method-not-annotated-as-after-around-same-time"

### ISSUE THREAD

**Issue by Jimmo910** [1C-Company/1c-edt-issues#1316]
### Описание ошибки

Ошибка в том что... EDT считает что нельзя одновременно расширить метод как с помощью &ИзменениеИКонтроль так и &После

### Как воспроизвести

Взять основную конфигурацию. с каким нибудь методом на форме.
Например "При изменении номенклатуры"
Создать расширение.
И расширить метод сначала как &ИзменениеИКонтроль потом через &После.

### Скриншоты

![image](https://github.com/1C-Company/1c-edt-issues/assets/122779512/3eb41c9b-e532-4317-9715-293a4a589911)

### Ожидаемое поведение

ошибки недолжно быть. Я проверил это отрабатывает корректно.

### Лог рабочей области

лог вроде как тут не нужен

### Версия 1С:EDT

Ruby 2023.2.4

### Операционная система

Windows

**Comment by MaksimDzyuba** [comment]
Здравствуйте, да, Вы правы, исправил, исправление войдет в 2024.1 
![image](https://github.com/1C-Company/1c-edt-issues/assets/77277424/f7cd792e-306e-44e2-acdb-cc9b5b89dcd4)
