### ISSUE TITLE
При добавлении команды процедуру обработки автоматически добавлять в область ОбработчикиСобытий

### ISSUE THREAD

**Issue by DmitryShvaika** [1C-Company/1c-edt-issues#1319]
### Описание проблемы

Сейчас при добавлении команды процедура обработки событий ОбработкаКоманды добавляется вне всякой области, что приводит к ошибке:
![image](https://github.com/1C-Company/1c-edt-issues/assets/54451084/ffcc76ab-2b8b-4ef8-95cc-ef6dec21d1ff)

### Описание решения проблемы

Предлагаю при добавлении команды в модуле команды автоматически создавать область ОбработчикиСобытий и помещать процедуру обработки команды в эту область.

**Comment by adminimusRU** [comment]
Кажется уже реализовано в плагине https://github.com/1C-Company/v8-code-style/issues/1040

**Comment by DmitryShvaika** [comment]
> Кажется уже реализовано в плагине [1C-Company/v8-code-style#1040](https://github.com/1C-Company/v8-code-style/issues/1040)

Оно реализовано только для команд формы
![image](https://github.com/1C-Company/1c-edt-issues/assets/54451084/b22038a5-9d53-4084-9bdc-b45caab93ac3)

а еще есть команды документов, справочников, обработок, отчетов, общие команды

**Comment by DmitryShvaika** [comment]
> > а еще есть команды документов, справочников, обработок, отчетов, общие команды
> 
> для самостоятельных команд это было реализовано еще раньше, нужно просто включить автоматическое создание структуры модуля в свойствах проекта. Поставляемый шаблон модуля команды в code-style уже содержит правильные области (можно переопределить при желании) https://github.com/1C-Company/v8-code-style/blob/master/docs/tools/module-structure.md

Странно, но для команд формы почему то не надо включать создание структуры модуля. Зачем мне постоянно удалять лишние области.

**Comment by adminimusRU** [comment]
> Странно, но для команд формы почему-то не надо включать создание структуры модуля. Зачем мне постоянно удалять лишние области.

Это разные механики. Команды в форме создаются динамически в уже существующей форме, для которой уже есть код модуля формы. У самостоятельных команд свой отдельный модуль, структура которого вместе с нужными областями создается в момент создания команды - эта структура задается шаблоном.
В настройках проекта можно оставить включенной только создание структуры модуля для команд и переопределить шаблон модуля, тогда ничего удалять не придется.

**Comment by DmitryShvaika** [comment]
ок, спасибо
