### ISSUE TITLE
Для команд объектов сделать вкладку "Права", "Функциональные опции", "Подсистемы", "Общие" аналогично редактору Общей команды

### ISSUE THREAD

**Issue by DmitryShvaika** [1C-Company/1c-edt-issues#1321]
### Описание проблемы

Сейчас нет возможности задать права доступа для команды объекта
![image](https://github.com/1C-Company/1c-edt-issues/assets/54451084/f966f089-2f46-43b6-92ed-8e5381222261)

Как ни странно, заголовок вкладки то же отличается от общего формата - возможно просто открывается не тот редактор

### Описание решения проблемы

Предлагаю сделать аналогично редактору общей команды. Вкладки: Права, Функциональные опции, Подсистемы и Общие

![image](https://github.com/1C-Company/1c-edt-issues/assets/54451084/3369045c-e20c-44ba-97b9-fb46d8db60d4)

**Comment by DmitryShvaika** [comment]
Пожелание стоило завести как ошибку, так как сейчас в Edt невозможно задать права для команды объекта ни через редактор команды, ни через редактор роли!

**Comment by LesN1ck** [comment]
> Пожелание стоило завести как ошибку, так как сейчас в Edt невозможно задать права для команды объекта ни через редактор команды, ни через редактор роли!

А такой вариант вас чем не устраивает?

![image](https://github.com/1C-Company/1c-edt-issues/assets/114978535/c7d08db6-3838-4940-bc4e-5e9fa95edf59)

**Comment by LesN1ck** [comment]
Аналогично в редакторе роли:

![image](https://github.com/1C-Company/1c-edt-issues/assets/114978535/51b87e56-fef3-4a83-a867-dd6ced6f1b0a)

**Comment by DmitryShvaika** [comment]
Да, спасибо не нашел просто.
