### ISSUE TITLE
[XDTO] Некорректный экспорт XML-схемы при наличии только установленного свойства "Базовый тип"

### ISSUE THREAD

**Issue by Stivo182** [1C-Company/1c-edt-issues#1323]
### Описание ошибки

Некорректный экспорт XML-схемы при наличии только установленного свойства `Базовый тип`

### Как воспроизвести

1. Импортировать XML-схему в XDTO пакет: [Правильная схема.zip](https://github.com/1C-Company/1c-edt-issues/files/14267864/default.zip)

![image](https://github.com/1C-Company/1c-edt-issues/assets/24582991/19a567e1-05cd-4a40-9c21-79e4dd9d7962)

2. Выполнить экспорт XML-схемы и убедиться, что неверно закрылся тег `xs:complexType` у основного типа

```
<xs:schema xmlns:tns="http://www.sample-package.org" xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.sample-package.org" attributeFormDefault="unqualified" elementFormDefault="qualified">
	<xs:complexType name="БазовыйТип">
		<xs:sequence>
			<xs:element name="ПолеБазовогоТипа" type="xs:string"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="ОсновнойТип"/>
		<xs:complexContent>
			<xs:extension base="tns:БазовыйТип"/>
		</xs:complexContent>
</xs:schema>
```

### Ожидаемое поведение

Ожидаемая выгрузка XML-схемы:

```
<xs:schema xmlns:tns="http://www.sample-package.org" xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.sample-package.org" attributeFormDefault="unqualified" elementFormDefault="qualified">
	<xs:complexType name="БазовыйТип">
		<xs:sequence>
			<xs:element name="ПолеБазовогоТипа" type="xs:string"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="ОсновнойТип">
		<xs:complexContent>
			<xs:extension base="tns:БазовыйТип"/>
		</xs:complexContent>
	</xs:complexType>
</xs:schema>
```

### Лог рабочей области

[logs.zip](https://github.com/1C-Company/1c-edt-issues/files/14268025/logs.zip)

### Версия 1С:EDT

Ruby 2023.3.0

### Операционная система

Windows

### Установленные плагины

1C:Code style V8, 1C:SSL-support, 1C:Language Tool

**Comment by MaksimDzyuba** [comment]
Здравствуйте, ошибку удалось исправить, войдет в 2024.1, спасибо большое!
![bandicam-2024-03-09-23-13-44-195](https://github.com/1C-Company/1c-edt-issues/assets/77277424/cb0aedf4-b192-412d-85d1-ff660d406d19)
