### ISSUE TITLE
Не видит Экспортный метод из базовой формы

### ISSUE THREAD

**Issue by Jimmo910** [1C-Company/1c-edt-issues#1324]
### Описание ошибки

В расширении, не видит Экспортный метод формы, для объекта ОписаниеОповещения.

### Как воспроизвести

0. Возьмем Розницу 2
1. Перейдите в Обработки в ПроверкаИПодборПродукцииИСМП, открыть форму "ПроверкаИПодбор"
2. Добавить В расширение метод "ПриОткрытии" (после)
3. Создать Свой клиенский Общий модуль. В нем процедуру "Текст", с входящим параметром "форма".
4. Написать в этой процедуре `ОповещениеПриЗавершении = Новый ОписаниеОповещения("РучнойВводШтрихкодаЗавершение", Форма);`
5. Сделать описание параметра `// 
// Параметры:
//  Форма - См. Обработка.ПроверкаИПодборПродукцииИСМП.Форма.ПроверкаИПодбор`
6. Наблюдать что ЕДТ не видит метод "РучнойВводШтрихкодаЗавершение" у формы. Хотя у Родительской формы он существует.

### Скриншоты

![image](https://github.com/1C-Company/1c-edt-issues/assets/122779512/7fc0c04b-9a5a-4d91-9ccd-1b635547e57c)

### Ожидаемое поведение

Я верно указал форму в типах параметрах. Поэтому ЕДТ должно видеть какие Экспортные методы там есть.

### Лог рабочей области

-

### Версия 1С:EDT

Ruby 2023.2.4

### Операционная система

Windows

**Comment by Jimmo910** [comment]
![image](https://github.com/1C-Company/1c-edt-issues/assets/122779512/0989f1ec-9872-4b31-aeb7-9df910a9c98b)

**Comment by Jimmo910** [comment]
![image](https://github.com/1C-Company/1c-edt-issues/assets/122779512/1556fc2c-abec-4352-9d29-f26e9071a466)

**Comment by marmyshev** [comment]
@MaksimDzyuba Нужно завести задачу на код-стайл для переделки проверки. Сейчас такой же хардкод на общие модули, как и в ЕДТ (для подсказки литерала в оповещении).

Было бы здорово использовать общий механизм для этого, м.б. те же индексы экспортных методов?

**Comment by MaksimDzyuba** [comment]
@marmyshev я вообще думал, что я в рамках этой и там и там поправлю, общая проблема, скорее всего на общие рельсы посажу все это

**Comment by MaksimDzyuba** [comment]
Всем привет, исправить удалось, не только в этом месте, но и в других похожих местах, буду стараться, чтобы исправление успело в 2024.1.
![image](https://github.com/1C-Company/1c-edt-issues/assets/77277424/93f20b60-1dcb-4815-b3d3-babc37e63b4d)

**Comment by Jimmo910** [comment]
@MaksimDzyuba поставил новую 2024.1.0 
Вот такая проблема не должна была тоже починиться?

![image](https://github.com/user-attachments/assets/cdc771da-31be-46a9-8e54-0ef72333e4cf)

**Comment by MaksimDzyuba** [comment]
Здравствуйте, а я что-то не пойму, на скрине, как формы нет, поэтому он и в док. комментарии ругается, но с другой стороны рядом эта форма есть, не понимаю пока, как так?

**Comment by Jimmo910** [comment]
@MaksimDzyuba  С лево Расширение. а с право основная Базовая конфигурация.

**Comment by MaksimDzyuba** [comment]
Понял, да, ошибка, но другая, тут про методы было, и правил я именно их, а это уже часть другого, но я могу и эту переоткрыть, чтобы новую не заводить

**Comment by Jimmo910** [comment]
@MaksimDzyuba Было бы супер. Если надо могу отдельное Ишью сделать

**Comment by MaksimDzyuba** [comment]
Это переоткрыл, в рамках него сделаю

**Comment by MaksimDzyuba** [comment]
Здравствуйте, вроде все получилось, но в 2024.1 или в 2024.2, еще придется решать.
![image](https://github.com/user-attachments/assets/ef72ea34-f97d-4af7-9973-d3ba7008b33a)

**Comment by Jimmo910** [comment]
@MaksimDzyuba Не работает, в случае если справочник добавлен в расширение.
![image](https://github.com/user-attachments/assets/e2e74315-5e08-4e1c-ae4c-e9dd33612f23)

Но работает в случае если справочник **не** добавлен в расширение.
![image](https://github.com/user-attachments/assets/e816b6ad-a2ca-455e-b3f3-2e74409a70f4)

**Comment by Jimmo910** [comment]
Проект прилагаю.
[test.zip](https://github.com/user-attachments/files/17649901/test.zip)

**Comment by MaksimDzyuba** [comment]
Здравствуйте, вот часть по док комментарию, я не переносил в 2024.1, она появится только в 2024.2
![image](https://github.com/user-attachments/assets/9833646d-0787-426b-acc6-11647fd634ac)

**Comment by Jimmo910** [comment]
ааа, 2024.2
а я подумал 2024.1.2

будем ждать
