### ISSUE TITLE
Ошибка запуска приложения

### ISSUE THREAD

**Issue by Zakharovzvv** [1C-Company/1c-edt-issues#1325]
### Описание ошибки

Невозможно запустить приложение после изменени конфигурации

### Как воспроизвести

Запустить любую конфигурацию запуска

### Скриншоты

<img width="1579" alt="image" src="https://github.com/1C-Company/1c-edt-issues/assets/68952793/89143a06-b4ba-43ce-9d65-a3ffdb052536">

### Ожидаемое поведение

Должна запуститься платфоома и конфигурация

### Лог рабочей области

[Untitled.log](https://github.com/1C-Company/1c-edt-issues/files/14269933/Untitled.log)

### Версия 1С:EDT

2023.3.0

### Операционная система

macOS

### Установленные плагины

Нет плагинов

### Дополнительная информация

платформа 8.3.24.1342

**Comment by Erik773** [comment]
Здравствуйте @Zakharovzvv.
Могли бы вы, пожалуйста, уточнить:
- Какие изменения производились в конфигурации? Если возможно, могли бы вы, пожалуйста, предоставить короткое видео с воспроизведением проблемы.
- Установлены ли все компоненты платформы для работы с приложениями? Приложите, пожалуйста, скриншот со списком установленных версий платформы Окно → Параметры → V8 → 1С:Предприятие → <8.3.24> → ...8.3.24.1342...

**Comment by Zakharovzvv** [comment]
<img width="1579" alt="image" src="https://github.com/1C-Company/1c-edt-issues/assets/68952793/b67a3a76-a260-409a-b595-04abd4e32952">

**Comment by Zakharovzvv** [comment]
/Users/vladimir/Documents/Projects/dev/itams/src/itams/.settings  не вижу такого файла в этой папке

**Comment by Zakharovzvv** [comment]
Логин/ пароль - верные

Ошибка вываливается при попытке запуска. Для этого не обязателдьно менять конфигурацию. При изменении конфигурации изменения записываются в иб. После записи начинается запуск и вываливается ошибка

**Comment by Erik773** [comment]
Подскажите, пожалуйста, а при нажатии на кнопку "Версии платформы..." в диалоговом окне ошибки, в открывшемся списке платформ есть ли версия платформы, которая указана указана для информационной базы и в режиме совместимости проекта конфигурации?
В конфигурации запуска приложения используются настройки доступа к информационной базе, аутентификация ОС или логин/пароль пользователя информационной базы?

**Comment by Erik773** [comment]
Для лучшего понимания контекста проблемы, могли бы вы, пожалуйста, приложить скриншоты свойств и настроек информационной базы, проекта конфигурации, списка платформ (Окно → Параметры → V8 → 1С:Предприятие → ), приложения, конфигурации запуска.

**Comment by Zakharovzvv** [comment]
<img width="1579" alt="image" src="https://github.com/1C-Company/1c-edt-issues/assets/68952793/79f44268-aa7d-43e6-88fd-78e9b046da6a">

**Comment by Zakharovzvv** [comment]
Режим совместимости - 8.3.21 Такой установленной платформы нет. Только 24я

**Comment by Zakharovzvv** [comment]
<img width="1623" alt="image" src="https://github.com/1C-Company/1c-edt-issues/assets/68952793/f1d8aba0-48c7-468d-9bc8-90614687827e">

**Comment by Zakharovzvv** [comment]
В настройках запуска используется логин/пароль

**Comment by Erik773** [comment]
Могли бы вы, пожалуйста, приложить скриншоты списка платформ (Окно → Параметры → V8 → 1С:Предприятие → Версии платформы) и свойств приложения.

> Режим совместимости - 8.3.21 Такой установленной платформы нет. Только 24я

А проект конфигурации под какую версию платформы создан?

> В настройках запуска используется логин/пароль

Вы не пробовали использовать для конфигурации запуска настройки доступа к информационной базе, предварительно задав настройки доступа в свойствах самой базы.

**Comment by Zakharovzvv** [comment]
> А проект конфигурации под какую версию платформы создан?

Конфигурация переведена на 24 платформу

> Вы не пробовали использовать для конфигурации запуска настройки доступа к информационной базе, >предварительно задав настройки доступа в свойствах самой базы.

В настройках запуска выбрал Использовать настройки доступа к ИБ. Ошибка та же

**Comment by Zakharovzvv** [comment]
<img width="1796" alt="image" src="https://github.com/1C-Company/1c-edt-issues/assets/68952793/3ceafddc-9a17-40ee-9b59-0e462dd7edf6">

**Comment by Zakharovzvv** [comment]
<img width="1840" alt="image" src="https://github.com/1C-Company/1c-edt-issues/assets/68952793/08458535-13e6-4cda-8405-b636c513ccec">

**Comment by Zakharovzvv** [comment]
у приложения окно свойств пустое

**Comment by Erik773** [comment]
> Конфигурация переведена на 24 платформу

Можете, пожалуйста, попробовать создать новую информационную базу, указав для неё версию платформы <8.3.24>, затем загрузить в неё конфигурацию и запустить приложение.

> у приложения окно свойств пустое

Чтобы открыть свойства приложения надо сделать по нему двойной щелчок мыши. 

> Могли бы вы, пожалуйста, приложить скриншоты списка платформ (Окно → Параметры → V8 → 1С:Предприятие → Версии платформы) 

Нужно раскрыть группу "1С:Предприятие" и выбрать элемент "Версии платформы", пример приведен на скриншоте ниже ↓
![platform](https://github.com/1C-Company/1c-edt-issues/assets/93516265/d8679cd0-7a57-4aa7-be59-20b5340991ef)

**Comment by Erik773** [comment]
И ещё, пожалуйста, покажите список поддерживаемых платформ в свойствах конфигурации, как на примере ниже ↓
![conf](https://github.com/1C-Company/1c-edt-issues/assets/93516265/bffbda74-d191-475a-8cbb-b5583b240bea)

**Comment by Zakharovzvv** [comment]
![image](https://github.com/1C-Company/1c-edt-issues/assets/68952793/d2f8760a-a284-4043-85e9-11cfea1e6bc8)

**Comment by Zakharovzvv** [comment]
<img width="1013" alt="image" src="https://github.com/1C-Company/1c-edt-issues/assets/68952793/afdc5e99-1334-4ddb-9251-01f1fe1d036a">

**Comment by Zakharovzvv** [comment]
<img width="1554" alt="image" src="https://github.com/1C-Company/1c-edt-issues/assets/68952793/f76bf7e4-c706-453b-b527-0255438587a8">

**Comment by Zakharovzvv** [comment]
> Можете, пожалуйста, попробовать создать новую информационную базу, указав для неё версию платформы <8.3.24>, затем загрузить в неё конфигурацию и запустить приложение.

так запустилась

**Comment by Erik773** [comment]
Закрываем задачу. Если проблема осталась актуальной, то задачу можно открыть снова.

**Comment by Zakharovzvv** [comment]
<img width="797" alt="image" src="https://github.com/1C-Company/1c-edt-issues/assets/68952793/05240d03-bddd-4123-9972-3af7c4ab3faa">
