### ISSUE TITLE
Возникает ошибка: "Файл - /Catalogs/Номенклатура/Forms/Расш1_ФормаЭлемента/Ext/Form.xml: Неверный путь к данным: "Объект.Parent""

### ISSUE THREAD

**Issue by amkar2010** [1C-Company/1c-edt-issues#1328]
### Описание ошибки

При добавлении на форму реквизита "Родитель" в расширении у иерархического справочника, то при обновлении БД возникает ошибка (см. скриншот)
Данная ошибка возникает на релизах 2023.1.2, 2023.2.0, 2023.2.4
Если убрать реквизит "Родитель" с формы, тогда обновление происходит без ошибки
Ошибка возникает конкретно только в расширении. Если заимствовать форму с реквизитом "Родитель" из основной конфигурации, то ошибки так же нет.

### Как воспроизвести

1. Создать расширение для основной конфигурации.
2. Добавить в расширение иерархический справочник заимствованием из основной конфигурации
3. Создать новую форму справочника в расширении
4. Проверить что реквизит "Родитель" есть на созданной форме
5. Попробовать обновить информационную базу (На данном этапе возникает ошибка)

### Скриншоты

![Ошибка](https://github.com/1C-Company/1c-edt-issues/assets/76473200/c3d538f5-c0ff-487c-906c-89001d1d388f)

### Ожидаемое поведение

Обновление информационной базы.

### Лог рабочей области

[журнал ошибок.log](https://github.com/1C-Company/1c-edt-issues/files/14305305/default.log)

### Версия 1С:EDT

Ruby 2023.1.2, Ruby 2023.2.0, Ruby 2023.2.4

### Операционная система

Windows

### Установленные плагины

Нет плагинов

### Дополнительная информация

Проверялось на платформах 8.3.22.2283, 8.3.22.2239, 8.3.23.1739

**Comment by LesN1ck** [comment]
Заимствован ли в расширении признак "Иерархический"?

**Comment by amkar2010** [comment]
@LesN1ck Признак "Иерархический" у справочника в расширении заимствован.
![image](https://github.com/1C-Company/1c-edt-issues/assets/76473200/d6fedc61-6e0b-401f-871b-6a615524cc00)

P.S. Если установить проверку "Проверять значение при подключении расширения", тогда ошибки нет.

**Comment by LesN1ck** [comment]
> @LesN1ck Признак "Иерархический" у справочника в расширении заимствован. ![image](https://private-user-images.githubusercontent.com/76473200/305388493-d6fedc61-6e0b-401f-871b-6a615524cc00.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgwODA3NTksIm5iZiI6MTcwODA4MDQ1OSwicGF0aCI6Ii83NjQ3MzIwMC8zMDUzODg0OTMtZDZmZWRjNjEtNmUwYi00MDFmLTg3MWItNmE2MTU1MjRjYzAwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE2VDEwNDczOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRlNDE1NWY5MzhlNDYzMjM5YzFlMzA0ZDUwNjk4YmRlNDJkZmRhNzE0NDBjNmY0YzJjMDJkOGFlMWNlMDkyYjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.jy2OQCb6Wj4G-fCuYDgDLihOsqA_89igMEDBuJza5uA)
> 

Вот как раз здесь важно, чтобы стоял флаг слева от признака. Иначе этот признак никак не контролируется при проверке применимости расширения - а значит, нет гарантии, что справочник действительно иерархический. Поэтому ошибки здесь нет, это запланированное поведение платформы. Собственно, и саму ошибку вам выдаёт не EDT, а агент конфигуратора.

**Comment by amkar2010** [comment]
@LesN1ck Услышал вас. Возможно ли в будущих версиях учесть следующий аспект: Автоматически проставлять флаг контроля слева? 
Сейчас конечно будем знать как бороться с такой ошибкой и если будет выходить, будем знать как исправить. Но согласитесь, приятнее, когда добавляешь объект в расширение и все необходимые свойства автоматически устанавливаются.

**Comment by LesN1ck** [comment]
> @LesN1ck Услышал вас. Возможно ли в будущих версиях учесть следующий аспект: Автоматически проставлять флаг контроля слева? Сейчас конечно будем знать как бороться с такой ошибкой и если будет выходить, будем знать как исправить. Но согласитесь, приятнее, когда добавляешь объект в расширение и все необходимые свойства автоматически устанавливаются.

Вопрос не ко мне, я такой же пользователь EDT, как и вы. Если хотите, можете зарегистрировать это как отдельное пожелание. В данной ошибке эту просьбу вряд ли кто-то увидит.

**Comment by vadimeg** [comment]
Исправлено в 2024.1
