### ISSUE TITLE
Вид флажка на форме

### ISSUE THREAD

**Issue by its76** [1C-Company/1c-edt-issues#133]
### Описание ошибки

исчезают все реквизиты с превью формы если в любом реквизите с типом булево этой формы установить тип флажка "выключатель"

### Как воспроизвести

1. в редакторе формы выбрать элемент с типом БУЛЕВО
2. найти свойство "Вид флажка"
3. установить значение "Выключатель"
4. визуальное отображение формы каллопсирует в квадратик

### Скриншоты

![image](https://user-images.githubusercontent.com/55942258/143244888-5f8fb478-a2eb-4237-b7f3-b8153f782b54.png)

![image](https://user-images.githubusercontent.com/55942258/143244970-90f68b97-e183-4ada-9666-808a656d8495.png)

### Ожидаемое поведение

адекватное

### Лог рабочей области

[trace.log](https://github.com/1C-Company/1c-edt-issues/files/7595883/trace.log
[111.log](https://github.com/1C-Company/1c-edt-issues/files/7595888/111.log)
)

### Версия 1С:EDT

Ruby 2021.2.10

### Операционная система

Windows

### Установленные плагины

1C:Code style V8, 1C:SSL-support

**Comment by vadimeg** [comment]
Значение "Выключатель" для флажка доступно начиная с версии платформы 8.3.15.
Для более старых платформ не должно быть этого значения для выбора в палитре свойств. Исправим.

**Comment by vadimeg** [comment]
Исправлено в 2021.3
