### ISSUE TITLE
Помогите определить причину медленного импорта конфигурации в EDT

### ISSUE THREAD

**Issue by Kirill** [1C-Company/1c-edt-issues#1332]
### Описание ошибки

Столкнувшись с проблемами производительности хранилища конфигурации, ну и запланированным переходом на git и EDT, делаем импорт конфигурации и расширений в EDT из информационной базы, подключенной к хранилищу. С небольшими конфигурациями процесс происходит быстро, а вот с ERP непонятно, почему процесс идет так долго.
По аналогии с #1186 собрал профайл и тресинг.

### Как воспроизвести

[hotspot-pid-7760-id-1-2024_02_21_05_28_27.zip](https://github.com/1C-Company/1c-edt-issues/files/14360689/hotspot-pid-7760-id-1-2024_02_21_05_28_27.zip)

### Ожидаемое поведение

Когда только начинали тестировать переход в git процесс импорта конфигурации в EDT, а потом экспорт в пустую базу на сервере занимал 3 часа. Сейчас не всегда 3х часов хватает, чтобы импортировать конфигурацию из базы.

### Лог рабочей области

[metadata.zip](https://github.com/1C-Company/1c-edt-issues/files/14360702/metadata.zip)

### Версия 1С:EDT

2023.2.4+6

### Операционная система

Windows

### Установленные плагины

Нет плагинов

### Дополнительная информация

8.3.23.2040

**Comment by tretyakevich** [comment]
Добрый день.
В выпущенной финальной версии 2023.3 включен ряд изменений, связанных с выравниванием адресов памяти, которые теоретически могут решить/улучшить ситуацию с данной проблемой. Если кто-то будет устанавливать новую версию - поделитесь, пожалуйста, информацией о том, улучшилась ли ситуация или нет.
Спасибо!

**Comment by tretyakevich** [comment]
Предположительно исправлено в 2023.3
