### ISSUE TITLE
Некорректный перенос строки после форматирования кода

### ISSUE THREAD

**Issue by VAGoncharov** [1C-Company/1c-edt-issues#1334]
### Описание ошибки

EDT форматирует код и делает перенос строк. В строке может быть обращение к предопределенному элементу, пример:
... = ПредопределенноеЗначение("ПланСчетов.Бухгалтерский.МатериалыПереданныеВПереработку");

В результате форматирования строка будет разбита на 2:
... = ПредопределенноеЗначение("ПланСчетов.Бухгалтерский.
|МатериалыПереданныеВПереработку");

Это приведет к ошибке в рантайме. 

### Как воспроизвести

См. описание

### Ожидаемое поведение

1. Либо EDT не разбивает строку в функции ПредопределенноеЗначение()
2. Либо перенос строки идет через разбивку строки на 2 части, пример:
ПредопределенноеЗначение("ПланСчетов.Бухгалтерский" 
+ ".НужныйСчет");

### Лог рабочей области

-

### Версия 1С:EDT

2022.2.5

### Операционная система

Windows

### Установленные плагины

1C:Code style V8, 1C:SSL-support

**Comment by Erik773** [comment]
Здравствуйте @VAGoncharov.
К сожалению, не удалось воспроизвести проблему.

https://github.com/1C-Company/1c-edt-issues/assets/93516265/26a68a93-f924-4023-b9e6-8b07d33bba54

Могли бы вы, пожалуйста, предоставить модуль, в котором возникла ошибка?

**Comment by Erik773** [comment]
Также, могли бы вы, пожалуйста, предоставить информацию о настройках параметров текстового редактора кода (Параметры → Общие → Редакторы → Текстовые редакторы), желательно скриншотом, и видео с воспроизведением проблемы?

**Comment by VAGoncharov** [comment]
Код, на котором возникла проблема, ПланСчетов.Финансовый.ЗатратыПоОперационнойДеятельностиОтчетногоПериода.
[Процедура ПредопределенноеЗначение.txt](https://github.com/1C-Company/1c-edt-issues/files/14491747/default.txt)

Настройки: 
[Настройки текстового редактора.zip](https://github.com/1C-Company/1c-edt-issues/files/14491820/default.zip)

Пока что сам не понимаю как она возникает, пробовал в разных ситуациях - форматирование в 9 из 10 случаев отработало корректно.
Если не удастся воспроизвести у вас еще раз, предлагаю ишуз закрыть.
