### ISSUE TITLE
Edt дублирует параметры в редакторе СКД при добавлении их в текст запроса, причем удалить дубли становится невозможным (пока не удалишь параметры из запроса снова)

### ISSUE THREAD

**Issue by DmitryShvaika** [1C-Company/1c-edt-issues#1336]
### Описание ошибки

Edt дублирует параметры в редакторе СКД при добавлении их в текст запроса, причем удалить дубли становится невозможным (пока не удалишь параметры из запроса снова).
![image](https://github.com/1C-Company/1c-edt-issues/assets/54451084/cd400e17-0bca-4c31-bc97-17a888031981)

### Как воспроизвести

1. Создайте простую СКД изображенную ниже
![image](https://github.com/1C-Company/1c-edt-issues/assets/54451084/621c860d-8db9-40fe-9fb7-f5fed238d43a)
В параметрах сделайте 3 параметра как на рис
![image](https://github.com/1C-Company/1c-edt-issues/assets/54451084/17cdaee2-472d-4df0-8c8f-fe121f8a92cb)

2. Теперь модифицируйте запрос набора как указано на рис
![image](https://github.com/1C-Company/1c-edt-issues/assets/54451084/3799ab2b-4e5a-45a0-8f9b-d0a6734dc9eb)

3. Перейдите на вкладку Параметры - наблюдайте дубли параметров. 
![image](https://github.com/1C-Company/1c-edt-issues/assets/54451084/4b83466b-66ec-4d33-a6e8-9c0808fc96e3)

### Ожидаемое поведение

Должны использоваться уже существующие одноименные параметры, а не создаваться новые

### Лог рабочей области

не требуется

### Версия 1С:EDT

Ruby 2023.3.1

### Операционная система

Windows

**Comment by tretyakevich** [comment]
Исправлено в 2024.1
