### ISSUE TITLE
[1CEDT] Изменение карты маршрута бизнес-процесса в конфигураторе

### ISSUE THREAD

**Issue by hamec** [1C-Company/1c-edt-issues#1337]
```
При изменении карты маршрута бизнес-процесса в конфигураторе, при обратной загрузке в EDT возникают следующие проблемы:
1) EDT не видит эти изменения и просит произвести полную выгрузку;
2) После импорта изменений в EDT, EDT просит сделать полную выгрузку в конфигуратор.

Пример воспроизведения:
1) Взять любую конфигурацию, к примеру БСП
2) Включить возможность изменения у всех объектов
3) Создать новый проект, импортировать в него конфигурацию
4) Сделать полную выгрузку в конфигурацию;
5) Запустить конфигуратор (я запускал из EDT)
6) Внести изменение в карту маршрута любого БП (я добавлял условие). Сохранить
7) Попытаться выгрузить изменения в EDT

Product name: 1C:Enterprise Development Tools
Product version: 1.30.0.380
Java home: C:\Program Files\BellSoft\LibericaJDK-11-Full
Java vm name: OpenJDK 64-Bit Server VM
Java vm info: mixed mode
Java version: 11.0.18
Java vendor: BellSoft
OS: win32
Total mem: 16 647
Free mem: 10 906
Cores: 24
***********************************
*	Файлы, приложенные к задаче, отправлены разработчикам. Ссылка в задаче не отображается./t*
***********************************
```
![ИзменениеКартыМаршрутаБП](https://github.com/1C-Company/1c-edt-issues/assets/25643488/0d3837c9-2120-4926-a35f-11acd3a006ad)

**Comment by nikolay-martynov** [comment]
Здравствуйте. Это особенности работы платформы с бизнес процессами.

> Если в процессе попытки обновления XML выгрузки будет обнаружено, что в конфигурации имели место переименования или удаления объектов метаданных, а также изменения внешних свойств влияющих на целостность XML выгрузки конфигурации (Предопределенные, ДиаграмаБизнесПроцесса), будет выполнена полная выгрузка конфигурации в XML. Поскольку в конфигурации могут быть ссылки на предопределенные и на точки бизнес процесса.

Полная выгрузка при точечных изменениях в конфигурации применяется платформой и в некоторых других случаях. В настоящий момент пока нет планов это изменять. Вы можете ссылаться на данную особенность как 70000295 при обращении в поддержку.
