### ISSUE TITLE
Не работает Остановка по ошибке

### ISSUE THREAD

**Issue by DmitryShvaika** [1C-Company/1c-edt-issues#1338]
### Описание ошибки

Не работает Остановка по ошибке
В версии Ruby 2023.3.1 перестала работать остановка по ошибке
В версии Ruby 2023.3.0 - работала.

![image](https://github.com/1C-Company/1c-edt-issues/assets/54451084/98c99627-2389-4aee-be79-b238b35c39c1)

1. Флажок так и не сохраняется. Ставлю флажок, нажимаю ОК. Открываю диалог сразу заново - флажок сброшен
Но это и раньше было так
При этом флажок Все исключения устанавливается (раньше то же ставился).
![image](https://github.com/1C-Company/1c-edt-issues/assets/54451084/c757a7d8-2150-4bbb-b8b4-2e9a31899013)

2. Однако раньше при ошибке отладка останавливалась в строке ошибки, сейчас - нет. 

### Как воспроизвести

1. Загрузите информационную базу тестового примера
[test.zip](https://github.com/1C-Company/1c-edt-issues/files/14432119/test.zip)
2. Загрузите проект из тестовой базы
3. Установите флажок Останавливаться по ошибке
4. Запустите отладку
5. Откройте форму списка справочника. 
6. Наблюдайте проблему: Ошибка есть, а остановки по ошибке - нет

### Ожидаемое поведение

Остановка по ошибке должна работать

### Лог рабочей области

не требуется

### Версия 1С:EDT

Ruby 2023.3.1

### Операционная система

Windows

**Comment by goodwinvu** [comment]
Версия 1С:EDT
Ruby 2023.3.1
Платформа версия 1С:Предприятие 8.3 (8.3.24.1368)

не работает ни в варианте файловой иб, ни в варианте авт.сервера

**Comment by DmitryBelov-e1c** [comment]
Исправление добавлено в следующую сборку 2023.3.1
