### ISSUE TITLE
Не работает Остановка в расширении

### ISSUE THREAD

**Issue by karneichik** [1C-Company/1c-edt-issues#1339]
### Описание ошибки

В расширении в заимствованном методе "ИзменениеИКонтроль" не останавливается на точке останова при фоновом задании :(( Но при этом в дальнейших методах, которые вызываются из расширения в основной конфигурации всё хорошо. И по шагам можно вернуться в метод расширения. Предметы остановки установлены

### Как воспроизвести

Поставить точку останова в расширении в методе вызываемом в фоновом режиме на сервере и попробовать остановить отладку на этой точке.

### Скриншоты

<img width="1445" alt="image" src="https://github.com/1C-Company/1c-edt-issues/assets/40263436/120727dc-a3e1-4407-b85d-a11b9e7bf9fd">

### Ожидаемое поведение

Отладка должна остановиться на установленной точке. 

### Лог рабочей области

В логах записи по времени отладки не появляются

### Версия 1С:EDT

2023.3.1.39

### Операционная система

Windows

### Установленные плагины

1C:Code style V8, 1C:SSL-support, 1C:Language Tool

### Дополнительная информация

Версия платформы 1С 8.3.20.2290

**Comment by Erik773** [comment]
Здравствуйте @karneichik!
Могли бы вы, пожалуйста, предоставить проект конфигурации и расширения для воспроизведения проблемы?
Для передачи конфигурации можно использовать FTP, подробнее https://partners.v8.1c.ru/topics/81, после отправки нужно прислать номер обращения, к которому были прикреплены данные.

**Comment by karneichik** [comment]
Конфигурация значения не имеет. Можно взять любую. Расширение точно так же можно создать новое. К сожалению конфигурацию клиентов я не могу сбросить.

**Comment by karneichik** [comment]
Серверный вызов так же останавливается в заимствованном методе "ИзменениеИКонтроль" в расширении

**Comment by karneichik** [comment]
Собственный объект расширения не останавливается ни на клиенте ни на сервере

**Comment by DmitryBelov-e1c** [comment]
Исправление добавлено в следующую сборку 2023.3.1
