### ISSUE TITLE
Не работает ограничение на длину числа в палитре свойств

### ISSUE THREAD

**Issue by theshadowco** [1C-Company/1c-edt-issues#1343]
### Описание ошибки

Ошибка в том что в палитре свойств можно указать для атрибута числового типа значение, превышающее поддерживаемое платформой.

Обновление базы происходит без проблем, платформа обрезает значение до максимально допустимого

### Как воспроизвести

1. Создать атрибут числового типа
2. Перейти в палитру свойств
3. Указать значение больше 38, например 202
4. Сохранить изменения
5. Обновить базу

### Скриншоты

![image](https://github.com/1C-Company/1c-edt-issues/assets/9591731/dc1ccda1-ffc1-49e4-86c2-640146630e81)

![image](https://github.com/1C-Company/1c-edt-issues/assets/9591731/cc1bd8c1-0e37-4b26-9e6f-9d0aba942434)

### Ожидаемое поведение

Нельзя ввести значение, превышающее поддерживаемое платформой

### Лог рабочей области

нет

### Версия 1С:EDT

Ruby 2023.2.4

### Операционная система

Windows, Linux

### Установленные плагины

Нет плагинов

**Comment by tretyakevich** [comment]
Исправлено в 2024.1
