### ISSUE TITLE
1cedtcli и код возврата в случае ошибки

### ISSUE THREAD

**Issue by regniws** [1C-Company/1c-edt-issues#1344]
### Описание ошибки

1cedtcli даёт нулевой код возврата даже в случае ошибки.

### Как воспроизвести

```
C:\Users\anton>"C:\Users\anton\AppData\Local\1C\1cedtstart\installations\1C_EDT 2023.3_\1cedt\1cedtcli.exe" -data "C:\wrk\edt\fs" -command export --project-name "fs" --configuration-files "C:\t\fsedt"
Could not launch 1C:EDT CLI because the associated workspace at 'C:\wrk\edt\fs' is currently in use by another application.

C:\Users\anton>echo %ERRORLEVEL%
0
```

### Ожидаемое поведение

Кажется, что в такой ситуации нужно возвращать не ноль. 

### Лог рабочей области

//

### Версия 1С:EDT

2023.3.0

### Операционная система

Windows

### Установленные плагины

1C:Code style V8, 1C:SSL-support

**Comment by dsavenko** [comment]
Исправлено в 2024.1.
