### ISSUE TITLE
Конструктор запросов не дает добавить поле в суммируемое поле группировки

### ISSUE THREAD

**Issue by VAGoncharov** [1C-Company/1c-edt-issues#1345]
### Описание ошибки

Имеем пакет запроса вида:
`
ВЫБРАТЬ РАЗЛИЧНЫЕ
	ВТПараметрыРегистрацииППА.ППА КАК ППА,
	ВТПараметрыРегистрацииППА.РУАППА КАК РУАППА,
	ВТПараметрыРегистрацииППА.РУДА КАК РУДА,
	ЕСТЬNULL(СтавкиАрендыПлощадей.ДатаОкончания, ДАТАВРЕМЯ(1, 1, 1)) КАК ДатаОкончания
ПОМЕСТИТЬ ВТСтавкиАрендыППА
ИЗ
	ВТПараметрыРегистрацииППА КАК ВТПараметрыРегистрацииППА
		ЛЕВОЕ СОЕДИНЕНИЕ РегистрСведений.СтавкиАрендыПлощадей КАК СтавкиАрендыПлощадей
		ПО ВТПараметрыРегистрацииППА.РУДА = СтавкиАрендыПлощадей.Регистратор
			И ВТПараметрыРегистрацииППА.Договор = СтавкиАрендыПлощадей.Договор
			И ВТПараметрыРегистрацииППА.Подразделение = СтавкиАрендыПлощадей.Подразделение
			И ВТПараметрыРегистрацииППА.ВидОбъекта = СтавкиАрендыПлощадей.ВидОбъекта
ГДЕ
	НЕ СтавкиАрендыПлощадей.НеДействует

ОБЪЕДИНИТЬ ВСЕ

ВЫБРАТЬ РАЗЛИЧНЫЕ
	ВТПараметрыРегистрацииППА.ППА,
	ВТПараметрыРегистрацииППА.РУАППА,
	ВТПараметрыРегистрацииППА.РУДА,
	ЕСТЬNULL(СтавкиАрендыАвтотранспорта.ДатаОкончания, ДАТАВРЕМЯ(1, 1, 1))
ИЗ
	ВТПараметрыРегистрацииППА КАК ВТПараметрыРегистрацииППА
		ЛЕВОЕ СОЕДИНЕНИЕ РегистрСведений.СтавкиАрендыАвтотранспорта КАК СтавкиАрендыАвтотранспорта
		ПО ВТПараметрыРегистрацииППА.РУДА = СтавкиАрендыАвтотранспорта.Регистратор
			И ВТПараметрыРегистрацииППА.Договор = СтавкиАрендыАвтотранспорта.Договор
			И ВТПараметрыРегистрацииППА.ТМЦ = СтавкиАрендыАвтотранспорта.Автомобиль
ГДЕ
	НЕ СтавкиАрендыАвтотранспорта.НеДействует
	
ИНДЕКСИРОВАТЬ ПО
	ППА
`

Здесь:
ППА, РУАППА, РУДА - поля ссылочных типов
ДатаОкончания - Дата

Открываю его в конструкторе запросов, убираю "РАЗЛИЧНЫЕ", добавляю поля "ППА, РУАППА, РУДА" в поля группировки, пытаюсь добавить "ДатаОкончания" в суммируемое поле. Конструктор запросов не позволяет это сделать.

В логе рабочей есть какие-то ошибки, см. приложенный файл.

### Как воспроизвести

-

### Ожидаемое поведение

-

### Лог рабочей области

[лог рабочей области.log](https://github.com/1C-Company/1c-edt-issues/files/14491675/default.log)

### Версия 1С:EDT

2022.2.5

### Операционная система

Windows

### Установленные плагины

1C:Code style V8, 1C:SSL-support

**Comment by MaksimDzyuba** [comment]
Здравствуйте, удалось воспроизвести и починить, постараюсь включить в 2024.1. 
![Uploading bandicam 2024-08-22 16-04-04-622.gif…]()
