### ISSUE TITLE
Конструктор запросов ошибочно считает запрос с ДОБАВИТЬКДАТЕ с параметром в периоде валидным

### ISSUE THREAD

**Issue by kuzyara** [1C-Company/1c-edt-issues#1346]
### Описание ошибки

Ошибка в том что в конфигураторе запрос "выбрать ДОБАВИТЬКДАТЕ(ДатаВремя(1,1,1), &Период, 1)" при открытии схемы вызывает ошибку, а в ЕДТ - нет.

### Как воспроизвести

1. Перейдите в новый конструктор запросов через ПКМ -> Query wizard -> Query
2. Вставьте текст запроса "выбрать ДОБАВИТЬКДАТЕ(ДатаВремя(2001,1,1), &Период, -1)"
3. Нажмите ОК
4. Должна возникнуть syntax error, а её нет!

### Скриншоты

скриншот результатов дымового теста из ADD https://github.com/vanessa-opensource/add/tree/develop/tests/smoke/тесты_ПроверкаМакетовСКД :
![image](https://github.com/1C-Company/1c-edt-issues/assets/2604430/6c8760f0-2667-48a2-a31e-b35cc238d8ca)

Скриншот доказывающий что конфигуратор такую конструкцию считает ошибкой:
ЕРП2, Документ ПланПродажПоКатегориям, макет СКД_ПланыПродажПоКатегориямСОтбором)
![image](https://github.com/1C-Company/1c-edt-issues/assets/2604430/f37a3645-d81a-4b3b-8bed-286dd33a8f33)

### Ожидаемое поведение

Так как запрос не имеет нативной возможности установки периодичности( СЕКУНДА | МИНУТА | ЧАС | ДЕНЬ | НЕДЕЛЯ | МЕСЯЦ | КВАРТАЛ | ГОД | ДЕКАДА | ПОЛУГОДИЕ) считать такой запрос ошибкой, как это и делается в режиме конфигуратора и в режиме предприятия.
`Запрос=НовыйЗапрос("выбрать ДОБАВИТЬКДАТЕ(ДатаВремя(2001,1,1), &Период, -1)");
ТЗ=Запрос.Выполнить().Выгрузить();`
Конструктор запроса должен выдавать синтаксическую ошибку "Неверные параметра ДОБАВИТЬКДАТЕ"

### Лог рабочей области

Лога нет

### Версия 1С:EDT

2023.2.4

### Операционная система

Windows

### Установленные плагины

1C:Language Tool

### Дополнительная информация

проверял на ERP 2.5.17

`Запрос=НовыйЗапрос("выбрать ДОБАВИТЬКДАТЕ(ДатаВремя(2001,1,1), &Период, -1)");
ТЗ=Запрос.Выполнить().Выгрузить();`
Конструктор запроса ЕДТ должен выдавать синтаксическую ошибку "Неверные параметра ДОБАВИТЬКДАТЕ"

платформа 8.3.23.2040

**Comment by MaksimDzyuba** [comment]
Здравствуйте, проблема та же самая, что и в https://github.com/1C-Company/1c-edt-issues/issues/1406, ее мы исправили, постараемся включить в 2024.1.
![image](https://github.com/user-attachments/assets/fdd45dd2-fbea-4d16-961e-61df63bc3a07)

**Comment by kuzyara** [comment]
В вашем жизненном цикле багов однозначно не хватает статуса "Проверен"

![image](https://github.com/user-attachments/assets/0730f3cb-089c-4e24-a78f-775a9eaf5bfb)
