### ISSUE TITLE
Пропадает перевод строки при добавлении метода в расширение с аннотацией &ИзменениеИКонтроль

### ISSUE THREAD

**Issue by goodwinvu** [1C-Company/1c-edt-issues#135]
### Описание ошибки

При добавлении метода в расширение с аннотацией &ИзменениеИКонтроль первый перенос строки (после описания процедуры исчезает, и  строка описания процедуры и следующая за описанием процедуры строка  сливаются в одну строку

### Как воспроизвести

1 Например в модуле объекта документа выделяем процедуру и добавляем её в расширение с аннотацией  "&ИзменениеИКонтроль"
![image](https://user-images.githubusercontent.com/32670094/143569834-294f2e0b-2855-4e0b-bfc3-f9c32fd6aae6.png)

![image](https://user-images.githubusercontent.com/32670094/143568800-0bff6317-86ac-4d32-b8ae-878635c80de4.png)

2 в получившейся процедуре в расширении будет отсутствовать перенос строки после описания процедуры
![image](https://user-images.githubusercontent.com/32670094/143568903-d0e6b30a-7c35-4b72-9d53-78ef5658cb1a.png)

### Ожидаемое поведение

После описания процедуры должен присутствовать перенос строки, как и в исходной процедуре

### Лог рабочей области

[log.log](https://github.com/1C-Company/1c-edt-issues/files/7608192/log.log)

### Версия 1С:EDT

Ruby 2021.2.10

### Операционная система

Windows

### Установленные плагины

1C:Code style V8, 1C:SSL-support

### Дополнительная информация

Версия платформы 1С:Предприятие 8.3 (8.3.20.1590)
Ошибка не зависит от версии конфигурации и  воспроизводится на разных конфигурациях стабильно
в примере конфигурация:
Аренда и управление недвижимостью для "1С:Бухгалтерия 8", редакция 3.0 (3.0.101.19/3.3.3.217) (http://solutions.1c.ru/catalog/rentestate)
Copyright (С) ООО "1C-Софт", 2009 - 2021. Все права защищены
(http://www.1c.ru)

**Comment by MaksimDzyuba** [comment]
Здравствуйте, ошибку поправили, исправление должно быть в релизе 2022.1

**Comment by goodwinvu** [comment]
Супер, ждем релиз 2022.1
