### ISSUE TITLE
Не работает "Остановка" при отдлаке расширения в версии 1CEDT (2023.3.1+39)

### ISSUE THREAD

**Issue by Valiev1c** [1C-Company/1c-edt-issues#1350]
### Описание ошибки

Не работает "Остановка" при отладке кода в расширении. В основной конфигурации (вне расширения) отладка работает корректно. Похожая ошибка в #1338 и #1339

### Как воспроизвести

1.Распаковать архив тестовой базы 1С [НеРаботаетОтладкаВРасширении.zip](https://github.com/1C-Company/1c-edt-issues/files/14522257/default.zip), загрузить в ИБ
2.Войти в режиме конфигуратора
3.Войти в модуль формы элемента справочника вида "ТестовыйСправочник1"
4.Поставить точку останова в коде процедуры "Расш1_ТестоваяПроцедура()"
5.Запустить 1С в режиме отладки
6.Перейти в список справочника "ТестовыйСправочник1", открыть форму элемента созданием нового или открытием существующего элемента справочника.
7.Наблюдать, что на точке останова нет остановки

### Скриншоты

![image](https://github.com/1C-Company/1c-edt-issues/assets/134257801/72e67d68-1d72-45a6-bd8a-87c2cd3ca264)

### Ожидаемое поведение

Ожидается остановка на точке останова

### Лог рабочей области

[log.zip](https://github.com/1C-Company/1c-edt-issues/files/14522356/log.zip)

### Версия 1С:EDT

1CEDT (2023.3.1+39)

### Операционная система

Windows

### Установленные плагины

Нет плагинов

**Comment by EChudnovsky** [comment]
Отладка в принципе не работает в расширении.
Любые точки останова игнорируются.
При  чем инструмент "замер производительности" показывает время  на точках останова.
Т.е. подключение к серверу отладки происходит и трассировка кода проходит.

**Comment by Erik773** [comment]
Дубль #1339
