### ISSUE TITLE
Некорректная работа переименования в редакторе запросов.

### ISSUE THREAD

**Issue by KovAlexey** [1C-Company/1c-edt-issues#1351]
### Описание ошибки

Ошибка в том что...
Редактор запросов что-то очень долго анализирует (к тому же в один поток) при переименовании.
Время явно не соответствует объему.

### Как воспроизвести

Создать запрос в редакторе запросов
```
ВЫБРАТЬ
	1 КАК Поле1
ПОМЕСТИТЬ ВТ
;

ВЫБРАТЬ
	ВТ.Поле1
ИЗ ВТ
```
Выделить "ВТ" в "ИЗ ВТ" во втором запросе.
Нажать ПКМ->Переименовать
Задать новое имя, нажать ОК или "Предварительный просмотр".
Ждать. Ждать. Ждать. Ждать.

Очевидно, что запрос из 4 строк не должен анализироваться минуту и более.
Необходимо оптимизировать этот момент. Судя по всему переименование анализирует явно больше, чем нужно.

### Ожидаемое поведение

Анализ запроса в редакторе, который занимает менее одной секунды времени в простых случаях

### Лог рабочей области

Не нужен

### Версия 1С:EDT

2023.2.4

### Операционная система

Windows

### Установленные плагины

1C:Code style V8, 1C:SSL-support

**Comment by MaksimDzyuba** [comment]
Здравствуйте, ошибку подтверждаю, вот результат исправление, первый пример на пустой конфигурации, второй пример уже при работе с erp. Постараюсь успеть включить в 2024.1
![bandicam 2024-07-25 20-31-44-678](https://github.com/user-attachments/assets/97518b1d-6020-4dbf-b340-cbe4a46afcbc)
![bandicam 2024-07-26 01-07-00-627](https://github.com/user-attachments/assets/affeac19-3282-40e6-b267-5fd1bd1ff3e0)
