### ISSUE TITLE
Нет возможности подавить ошибку "Необязательный параметр расположен перед обязательным"

### ISSUE THREAD

**Issue by DmitryShvaika** [1C-Company/1c-edt-issues#1354]
### Описание ошибки

Нет возможности подавить ошибку "Необязательный параметр расположен перед обязательным"

![image](https://github.com/1C-Company/1c-edt-issues/assets/54451084/a0cff64f-cdaf-47dd-9807-1019b16c855a)

### Как воспроизвести

1. Набрать текст модуля ниже

```
// @strict-types

#Область ПрограммныйИнтерфейс

// Действие с таблицей.
// 
// Параметры:
//  Пар1 - Число
//  Пар2 - Число
//
Процедура ДействиеСТаблицей(Пар1 = 0, Пар2) Экспорт
	
	Пар1 = Пар1;
	
КонецПроцедуры

#КонецОбласти

```
2. Наблюдать ошибку

### Ожидаемое поведение

Подавление ошибки должно работать

### Лог рабочей области

не требуется

### Версия 1С:EDT

Ruby 2023.3.1

### Операционная система

Windows

**Comment by vadimeg** [comment]
Не работает подавление только из всплывающего меню редактора, не сделано для низкоприоритетных ошибок (info).
Сделаем.
Из окна ошибок конфигурации работает
![image](https://github.com/1C-Company/1c-edt-issues/assets/17178862/393f49f0-219d-4921-8c4d-3f1854498817)

Добавляется //@skip-check method-optional-parameter-before-required

**Comment by vadimeg** [comment]
Исправлено в 2024.1
