### ISSUE TITLE
Появляются изменения в файлах EDT при конвертировании База -> EDT -> База -> EDT

### ISSUE THREAD

**Issue by senja006** [1C-Company/1c-edt-issues#1355]
### Описание ошибки

При последовательном конвертировании База -> EDT -> База -> EDT появляются изменения в файлах проекта EDT:

1. Перевод с английского на русский названий реквизитов - Screenshot_1
2. Перестановки - Screenshot_2
3. Удаление значений - Screenshot_3
4. Появление новых id - Screenshot_4
5. Появление новых прав - Screenshot_5

### Как воспроизвести

Все действия производились при помощи командной строки с использованием Git для отслеживания изменений.
1. Типовую конфигурацию "Система проектирования прикладных решений, версия 2.0.1.61" конвертируем в новый проект EDT.
2. Загружаем проект EDT в пустую Базу.
3. Очищаем папку проекта EDT.
4. Базу конвертируем в пустую папку проекта EDT.

### Скриншоты

Screenshot_1
![Screenshot_1](https://github.com/1C-Company/1c-edt-issues/assets/8147702/f98eeff7-9a4c-453e-845f-6b02b3c9506c)
Screenshot_2
![Screenshot_3](https://github.com/1C-Company/1c-edt-issues/assets/8147702/cabe2541-7758-4375-8c16-c8e30c50a69b)
Screenshot_3
![Screenshot_4](https://github.com/1C-Company/1c-edt-issues/assets/8147702/00411c4f-93d9-45b2-ad35-f25df291ad41)
Screenshot_4
![Screenshot_5](https://github.com/1C-Company/1c-edt-issues/assets/8147702/bf86bcad-dfe9-41e3-a7ed-8e2cac719e13)
Screenshot_5
![Screenshot_6](https://github.com/1C-Company/1c-edt-issues/assets/8147702/4d75e488-3b4e-475a-bd01-7854d5e7e5a8)

### Ожидаемое поведение

После выполнения 4 пункта действий, описанных в разделе "Как воспроизвести", изменений для коммита быть не должно - https://t.me/e1c_edt/91633?thread=90161

### Лог рабочей области

[.log](https://github.com/1C-Company/1c-edt-issues/files/14558687/default.log)
[trace.log](https://github.com/1C-Company/1c-edt-issues/files/14558688/trace.log)

### Версия 1С:EDT

Ruby 2023.3.1

### Операционная система

Windows

### Установленные плагины

Нет плагинов

### Дополнительная информация

Платформа 8.3.22.2239

**Comment by tretyakevich** [comment]
Было исправлено в 2024.1
