### ISSUE TITLE
Не верное сообщение об ошибке "Нельзя передавать объект типа 'ДокументPDF' между клиентом и сервером"

### ISSUE THREAD

**Issue by lrRatibor** [1C-Company/1c-edt-issues#1358]
### Описание ошибки

Ошибка в том что при передаче объекта типа ДокументPDF между клиентом и сервером выходит ложная ошибка.

### Как воспроизвести

создать на форме Следующие процедуры
&НаКлиенте
Процедура имяПроцедуры()
	PDF = ПолучитьPDF();
КонецПроцедуры

&НаСервереБезКонтекста
Функция ПолучитьPDF()
	PDF = Новый ДокументPDF();
	Возврат PDF;
КонецФункции

Появиться предупреждение
![image](https://github.com/1C-Company/1c-edt-issues/assets/125652316/4a7b3cd9-7785-4b41-83b5-15482f5f5a3a)

### Ожидаемое поведение

ДокументPDF Можно передавать между сервером и клиентом

### Лог рабочей области

[журнал.log](https://github.com/1C-Company/1c-edt-issues/files/14598696/default.log)

### Версия 1С:EDT

Ruby 2023.3.0

### Операционная система

Windows

### Установленные плагины

1C:Code style V8

**Comment by MaksimDzyuba** [comment]
Здравствуйте, исправил, исправление войдет в 2024.1
![image](https://github.com/1C-Company/1c-edt-issues/assets/77277424/f20f0f6c-8108-4023-a984-638b6842b98b)
