### ISSUE TITLE
В строгих типах не проверяется соответствие фактического возвращаемого значения объявленному в документирующем комментарии

### ISSUE THREAD

**Issue by DmitryShvaika** [1C-Company/1c-edt-issues#1359]
### Описание ошибки

В документирующем комментарии объявлено, что будет возращено число. На само деле возвращается ссылка.
В строгих типах должна быть проверка на соответствие и выдаваться ошибка в данном случае.

![image](https://github.com/1C-Company/1c-edt-issues/assets/54451084/b9ba1366-6153-4114-b956-091fddeddee0)

### Как воспроизвести

1. Набрать текст

```
// Новый справочник ссылка.
// 
// Возвращаемое значение:
//  Число
//
&НаСервереБезКонтекста
Функция НовыйСправочникСсылка()
	
	Возврат Справочники.Справочник1.ПустаяСсылка()
	
КонецФункции
```

Наблюдать отсутствие ошибки

### Ожидаемое поведение

В строгих типах должна быть проверка на соответствие и выдаваться ошибка в данном случае.

### Лог рабочей области

не требуется

### Версия 1С:EDT

Ruby 2023.3.1

### Операционная система

Windows

**Comment by iArtemv** [comment]
@DmitryShvaika Дмитрий, я правильно понимаю, что данной провверки ранее также не было?

**Comment by DmitryShvaika** [comment]
> @DmitryShvaika Дмитрий, я правильно понимаю, что данной провверки ранее также не было?

Да, не было... Edt просто складывает фактические типы с объявленными. Мне кажется это не совсем правильно и может приводить к тому, что объявлен один тип, а возвращается другой и ошибку при этом Edt не покажет.

**Comment by iArtemv** [comment]
Подробнее по этой задаче можно отследить статус в проекте code style:
https://github.com/1C-Company/v8-code-style/issues/951
https://github.com/1C-Company/v8-code-style/issues/975
