### ISSUE TITLE
В строгих типах Edt не понимает, что СправочникСсылка.ИмяСправочника входит в состав типа СправочникСсылка

### ISSUE THREAD

**Issue by DmitryShvaika** [1C-Company/1c-edt-issues#1360]
### Описание ошибки

В строгих типах Edt не понимает, что СправочникСсылка.Справочник1 входит в состав типа СправочникСсылка

![image](https://github.com/1C-Company/1c-edt-issues/assets/54451084/2008eb4c-031b-4317-9357-223b69f031c2)

### Как воспроизвести

1. Набрать текст

```
// @strict-types

#Область ОбработчикиКомандФормы

// Команда1.
// 
// Параметры:
//  Команда - КомандаФормы
&НаКлиенте
Процедура Команда1(Команда)
	
	Ввв = НовыеДанныеСтроки();
	Ввв = Ввв;
	
КонецПроцедуры

#КонецОбласти

#Область СлужебныеПроцедурыИФункции

// Новые данные строки.
// 
// Возвращаемое значение:
//  Структура:
//	 	* Ссылка - СправочникСсылка -
// 
&НаСервереБезКонтекста
Функция НовыеДанныеСтроки()
	
	СсылкаПустая = Справочники.Справочник1.ПустаяСсылка();
	
	ДанныеСтроки = Новый Структура;
	ДанныеСтроки.Вставить("Ссылка", СсылкаПустая);
	
	Возврат ДанныеСтроки;
	
КонецФункции

#КонецОбласти

```
2. Наблюдать ошибку

### Ожидаемое поведение

Edt должен понимать что СправочникСсылка.Справочник1 входит в состав типа СправочникСсылка для текущей конфигурации

### Лог рабочей области

не требуется

### Версия 1С:EDT

Ruby 2023.3.1

### Операционная система

Windows

### Дополнительная информация

Выгрузка информационной базы с тестовым примером
[test.zip](https://github.com/1C-Company/1c-edt-issues/files/14615098/test.zip)

**Comment by MaksimDzyuba** [comment]
Здравствуйте, исправили в 2024.1 
![image](https://github.com/1C-Company/1c-edt-issues/assets/77277424/371870dd-e329-4a0e-9cf1-8dd0358d4757)
