### ISSUE TITLE
Переключение на ветку

### ISSUE THREAD

**Issue by BizyaevAnton** [1C-Company/1c-edt-issues#1362]
### Описание ошибки

ОС Астра Линукс 1.7
EDT 2023.2.4
Возврат на ветку, с которой работал - появляется красный крест. Помогает удаление локальной ветки.
Переключение на удаленную ветку работает нормально.

### Как воспроизвести

1. Перейти на ветку
2. перейти на вторую ветку
3. Попытаться вернуться на первую - красный крест

### Ожидаемое поведение

Без красного креста

### Лог рабочей области

[Untitled.log](https://github.com/1C-Company/1c-edt-issues/files/14634751/Untitled.log)

### Версия 1С:EDT

2023.2.4

### Операционная система

Linux

**Comment by vadimeg** [comment]
Исправлено в 2024.1
