### ISSUE TITLE
При заимствовании метода в расширение, некорректно заполняются параметры

### ISSUE THREAD

**Issue by goodwinvu** [1C-Company/1c-edt-issues#1363]
### Описание ошибки

При заимствовании из исходной процедуры или функции в расширение параметры с значениями по умолчанию, передаются без таковых
Т.е если в заимствованной процедуре было к примеру
`Функция ДанныеДокументаДляПроведения(Документ, Регистры, ДопПараметры = Неопределено) Экспорт`
то при заимствовании с опцией "Изменение и контроль" в расширение передаются как 
```
&ИзменениеИКонтроль("ДанныеДокументаДляПроведения")
Функция фмоДанныеДокументаДляПроведения(Документ, Регистры, ДопПараметры) Экспорт
```
в логе никаких ошибок, просто ошибочное поведение при заимствовании

### Как воспроизвести

В конфигурации источнике сделать процедуру с установленным параметром по умолчанию
Создать расширение
Заимствовать эту процедуру в расширение (через меню ПКМ) с опцией ИзменениеИКонтроль

### Ожидаемое поведение

В параметры заимствованных методов должны передаваться также значения по умолчанию

### Лог рабочей области

[edtlog.zip](https://github.com/1C-Company/1c-edt-issues/files/14647520/edtlog.zip)

### Версия 1С:EDT

Ruby 2023.3.1

### Операционная система

Linux

### Установленные плагины

1C:Code style V8, 1C:SSL-support, 1C:Language Tool, Другие сторонние плагины `Название плагина...`

**Comment by vadimeg** [comment]
В конфигураторе дефолтные значения параметров тоже не переносятся при заимствовании.
Вот ответ платформы: 
```
дефолтные параметры нельзя "переопределить", они всегда будут как в оригинальном методе
```

**Comment by goodwinvu** [comment]
а никто их и не переопределяет
просто ошибка различия сигнатур методов
Т.к в исходном коде стоит значение по умолчанию (=Неопределено), а при заимствованиии его нет

**Comment by vadimeg** [comment]
Насколько я понимаю, это требование платформы, чтобы в заимствованные методы умолчательные значения не переносились из заимствуемого метода. EDT повторяет поведение конфигуратора.
