### ISSUE TITLE
При копировании через клипбоард табличного документа не заполняется свойство Текст, хотя сам скопированный текст отображается

### ISSUE THREAD

**Issue by JaneGlass73** [1C-Company/1c-edt-issues#1365]
### Описание ошибки

Ошибка в том что, если скопировать из 1С:Предприятия область табличного документа или одну ячейку, то скопированный текст отображается, но свойство Текст остаётся незаполненным:
![image](https://github.com/1C-Company/1c-edt-issues/assets/144486006/0d52ff2b-3c94-4d09-ab8e-7d0546620fa7)
При этом, если нажать на кнопку F2 в ячейке, потом просто нажать Enter, то происходит чудо и текст в поле появляется
При этом в структуре файла Template.mxlx происходят такие изменения:
![image](https://github.com/1C-Company/1c-edt-issues/assets/144486006/9a65718f-a9a0-486c-82d4-bac5d1e69ff4)
Язык в конфигурации один ru, но очень похоже то при копировании текст на этом языке не заполняется
Если не протыкать все ячейки, то в итоге при запуске выглядеть такой макет будет как
![image](https://github.com/1C-Company/1c-edt-issues/assets/144486006/252196a8-c209-44d0-8021-9218f57bc8f8)

### Как воспроизвести

1. Распаковать проект EDT и подключить его в рабочую область
[Конфигурация.zip](https://github.com/1C-Company/1c-edt-issues/files/14653310/default.zip)
2. Собрать в новую базу и запустив её открыть приложенный готовый XML из архива 
[TEST.zip](https://github.com/1C-Company/1c-edt-issues/files/14653333/TEST.zip)
3. Выделить весь документ (Ctrl+A) либо мышью в пересечении заголовков
4. Перейти в конфигурации в общий макет (пустой) так же выделить всё и вставить, должно получиться так:
![image](https://github.com/1C-Company/1c-edt-issues/assets/144486006/e2fd9d1e-9118-400e-bc65-f2e3dadfb7bd)
5. Обновить и запустить базу нажать на кнопку отчёт, будет так:
![image](https://github.com/1C-Company/1c-edt-issues/assets/144486006/b40d80f9-9032-4a36-83f3-eb5445ed5d93)
6. В EDT в любой ячейке нажать F2 потом Enter, заполнится свойство Текст для этой ячейки
7. Обновить и запустить базу нажать на кнопку отчёт, будет так:
![image](https://github.com/1C-Company/1c-edt-issues/assets/144486006/84a1c015-2932-4bbe-9494-f45f18f42312)
8. Открываем Template.mxlx и заменяем все # на ru
9. Сохраняем, обновляем, запускаем, результат:
![image](https://github.com/1C-Company/1c-edt-issues/assets/144486006/5fc627fe-7e65-4358-aa29-4d4252127b1d)

### Ожидаемое поведение

Ожидается что при копировании через клипбоард скопированные ячейки корректно лягут на свой язык

### Лог рабочей области

[log.txt.log](https://github.com/1C-Company/1c-edt-issues/files/14653505/log.txt.log)

### Версия 1С:EDT

Ruby 2023.2.4

### Операционная система

Windows

### Дополнительная информация

Платформа 8.3.23.1997

**Comment by wolfandw** [comment]
Исправлено. Войдет в 2025.1
