### ISSUE TITLE
При импорте профиля валидации для проекта внешних обработок запускается расширенная проверка основного проекта.

### ISSUE THREAD

**Issue by DmitryShvaika** [1C-Company/1c-edt-issues#1366]
### Описание ошибки

В рабочей области существует основной проект и проект внешних обработок с одной обработкой. Поменял профиль валидации для основного проекта (добавил пару проверок) запустилась расширенная проверка для добавленных правил - все правильно, прошло быстро. Сохранил профиль валидации и загрузил его для  проекта внешних обработок. Тут запустилась полная расширенная проверка основного проекта.

![image](https://github.com/1C-Company/1c-edt-issues/assets/54451084/651bd018-7a38-4d5b-9b12-f7521bb6981f)

### Как воспроизвести

Описано выше

### Ожидаемое поведение

В данном случае надо только одну внешнюю обработку и то на разницу правил аналогично ручному изменению профиля.

### Лог рабочей области

не требуется

### Версия 1С:EDT

Ruby 2023.3.1

### Операционная система

Windows

**Comment by tretyakevich** [comment]
Повторил эти действия/подобные действия (несколько попыток) - повторить проблему не смог.
Все перепроверки идут по целевым проектам

**Comment by DmitryShvaika** [comment]
ок, тогда закрою...
