### ISSUE TITLE
В строгих типах не видит, что у Фиксированной структуры не существует реквизит "ИмяКлюча"

### ISSUE THREAD

**Issue by DmitryShvaika** [1C-Company/1c-edt-issues#1369]
### Описание ошибки

В строгих типах не видит, что у Фиксированной структуры не существует реквизит "ИмяКлюча"

![image](https://github.com/1C-Company/1c-edt-issues/assets/54451084/be7250f3-8f42-4d0d-8c0d-d62162a497d0)

### Как воспроизвести

1. Набрать текст общего модуля

```
// @strict-types - директива для edt - проверка модуля в строгих типах

#Область ПрограммныйИнтерфейс

// Промежуточный конструктор.
// 
// Возвращаемое значение:
//  ФиксированнаяСтруктура
//
Функция МойКонструтор() Экспорт
	
	Возврат Новый ФиксированнаяСтруктура(Новый Структура);
	
КонецФункции

// Тест.
//
Процедура Тест() Экспорт
	
	МойОбъект = МойКонструтор();
	
	Если МойОбъект.ИмяКлюча Тогда
	КонецЕсли;

КонецПроцедуры

#КонецОбласти

```

2. Наблюдать ошибку

### Ожидаемое поведение

Должна выдаваться ошибка, что реквизит не существует

### Лог рабочей области

Не требуется

### Версия 1С:EDT

Ruby 2023.3.1

### Операционная система

Windows

**Comment by MaksimDzyuba** [comment]
![image](https://github.com/user-attachments/assets/2969d043-5e0e-47cf-b73a-ac53328e038a)
Здравствуйте, исправили
