### ISSUE TITLE
Теряются значения элементов при обновлении расширения

### ISSUE THREAD

**Issue by fenixnow** [1C-Company/1c-edt-issues#1370]
### Описание ошибки

При доработке расширения теряется заголовок элемента, хотя он присуствует в файле выгрузки

### Как воспроизвести

1. Перейдите в 
Берем последнюю ЕДТ 2023.3.2 Платформу 8.3.23.2137 (Ошибка воспроизводится и на ЕДТ 2023.2.4 и платформе 8.3.22.2239)

У нас есть типовая конфигурация ЗарплатаИУправлениеПерсоналомКОРП для нее сделано расширение
Расширяем Общие формы- РегламентированнаяОтчетность
в заголовке элемента меняем значение
![image](https://github.com/1C-Company/1c-edt-issues/assets/13418562/5a1ef9f0-7ff1-4f7c-aa8a-9f5c48e101db)

обновляем подключенную базу
в результате обновления у нас слетает заголовок
![image](https://github.com/1C-Company/1c-edt-issues/assets/13418562/e475017c-6014-4ba4-80a0-3d3ada546cc9)

Если получить файлик с выгрузкой, мы видим, что в xml присуствует строка 
![image](https://github.com/1C-Company/1c-edt-issues/assets/13418562/8e484a46-2213-412d-afe9-1227efa8c06a)

Если обратить внимание на форму, то перед элементом "ПанельТребований", есть элемент "Внимание" у него есть картинка
![image](https://github.com/1C-Company/1c-edt-issues/assets/13418562/2b60298e-6009-4cd6-a04a-bd41b600ab06)

но при выгрузке, она не попадает в XML
![image](https://github.com/1C-Company/1c-edt-issues/assets/13418562/3fe2b4fc-50b2-4c2e-a416-84a071e317ba)

Файл выгрузки прилагаю
[xml.zip](https://github.com/1C-Company/1c-edt-issues/files/14695458/xml.zip)

Если расширение выгружать полностью при помощь Ring то все данные на месте

Эта ошибка дает эффект, что мы в расширении видим довольно большой список отличий между тем, что формирует разработчик используя интерфейс и дальнейшую выгрузку из конфигуратора с тем, что у нас формируется при помощи ring

### Ожидаемое поведение

Ожидаем отсутствие потере данных при экспорте расширения в конфигуратор
Ожидаем отсутствие расхождение при сборке cfe 

### Лог рабочей области

[log.zip](https://github.com/1C-Company/1c-edt-issues/files/14695609/log.zip)

### Версия 1С:EDT

2023.3.2

### Операционная система

Windows

### Установленные плагины

Нет плагинов

**Comment by Erik773** [comment]
Здравствуйте @fenixnow!

> Если обратить внимание на форму, то перед элементом "ПанельТребований", есть элемент "Внимание" у него есть картинка

По поводу того, что картинка отсутствует в выгрузке, так ее там и не должно быть. Это ведь расширение, картинка есть в выгрузке формы основной конфигурации.

> обновляем подключенную базу
> в результате обновления у нас слетает заголовок

К сожалению, пока не удалось воспроизвести проблему.
Могли бы вы, пожалуйста, попробовать произвести очистку проекта и расширения, затем заново сделать полное обновление, вызвав соответствующую команду для связанной информационной базы. 
Если это не приведет к устранению ошибки, то, если возможно, предоставьте конфигурацию расширения, на которой воспроизводится проблема. 
Файлы можно отправить на edt@1c.ru или, если большой объем, то на ftp https://partners.v8.1c.ru/topics/81

Еще подскажите, пожалуйста, основная конфигурация снята с поддержки? Производились ли в ней изменения?

**Comment by fenixnow** [comment]
Добрый день, расхождения наблюдаются у нескольких человек на разных компьютерах.
На локальном, в процессе экспериментов, я поднимался от платформы 8.3.20 до 8.3.23
а также разных версий ЕДТ. Я делал это на новых проектах с пустым кешем.

Относительно основной конфигурации, она на поддержке.
![image](https://github.com/1C-Company/1c-edt-issues/assets/13418562/aaf4e317-bd85-4088-abe4-52362e08dfaa)

Информацию с расширениями отправил на почту edt@1c.ru. Тема письма - "Теряются значения элементов при обновлении расширения Ошибка 1370"

**Comment by fenixnow** [comment]
Номер обращения - DT-194 от 25.03.2024 9:33:28 (UTC+03:00).

**Comment by Erik773** [comment]
Благодарим за предоставленные материалы.
Могли бы вы, пожалуйста, проверить у себя актуальна ли проблема на версии  2023.3? возможно, проблема уже исправлена в рамках задачи #1300

**Comment by fenixnow** [comment]
> 1. ЕДТ 2023.3.2

да, эта проблема актуальна ЕДТ 2023.3.2

**Comment by MaksimDzyuba** [comment]
Здравствуйте, расширения получили, спасибо!

**Comment by fenixnow** [comment]
Коллеги привет, понятно, что 2024.1 когда то выйдет, а можно каким то патчем поправить это сейчас? Может какой то джарник можно подменить в текущей ЕДТ чтобы пофиксить багу, а то работать оч хочется :)

**Comment by tretyakevich** [comment]
Зависит от того, что именно нужно будет исправлять. Если можно будет портировать в 2023.3 - спортируем.

**Comment by fenixnow** [comment]
> Зависит от того, что именно нужно будет исправлять. Если можно будет портировать в 2023.3 - спортируем.

Ааа..... Я подумал, что вы ее пофиксили и она выйдет в 2024

**Comment by vadimeg** [comment]
@fenixnow А при обновлении базы использовался автономный сервер?

**Comment by fenixnow** [comment]
> @fenixnow А при обновлении базы использовался автономный сервер?

Нет, "старый" обычный вариант

**Comment by vadimeg** [comment]
@fenixnow А можете проверить одну вещь? Если в конфигураторе, там, где вы написали, что слетает заголовок, справа от поля Заголовок нажать кнопку с увеличительным стеклом, которая должна открыть диалог, то там внутри диалога тоже будет пусто или появится строчка?

Я воспроизвел похожую проблему конкретно с этим расширением, просто удалил заимствованную форму и заимствовал ее снова. Т.е. послетали все Заголовки декораций на этой форме, но при нажатии на кнопку заголовки были видны

**Comment by fenixnow** [comment]
> @fenixnow А можете проверить одну вещь? Если в конфигураторе, там, где вы написали, что слетает заголовок, справа от поля Заголовок нажать кнопку с увеличительным стеклом, которая должна открыть диалог, то там внутри диалога тоже будет пусто или появится строчка?
> 
> Я воспроизвел похожую проблему конкретно с этим расширением, просто удалил заимствованную форму и заимствовал ее снова. Т.е. послетали все Заголовки декораций на этой форме, но при нажатии на кнопку заголовки были видны

Да действительно
![image](https://github.com/1C-Company/1c-edt-issues/assets/13418562/8228fdad-e7cd-4ba7-a3ee-d3a4e9ac1938)

**Comment by vadimeg** [comment]
@fenixnow Какая-то проблема с UI в конфигураторе. На 2023.3 удалось воспроизвести. Данные корректно записались при экспорте, но что-то подвисло при отрисовке. Т.е. данные есть, как вы видели выше, но не показываются в палитре и на форме. Теперь если в таком состоянии в конфигураторе выгрузить расширение в XML и сразу же загрузить из этого же XML, то начинает отрисовываться корректно и дальнейшие обновления из EDT проходят нормально.

Эта форма изначально была рассинхронизована с базовой конфигурацией, может в этом дело.
![image](https://github.com/1C-Company/1c-edt-issues/assets/17178862/2865cd7f-b046-4331-9b4d-9ba0bb8b48b3)

![image](https://github.com/1C-Company/1c-edt-issues/assets/17178862/b25d5acb-9769-44ba-a858-be1ba328196e)

Если получится сделать стабильный репродьюсер, то создадим баг на платформу. В EDT механизм обновления работает корректно.
