### ISSUE TITLE
При включении проверки запросов в тексте (настройки валидации проекта) Edt повис на 99 % и не завершал процесс. При попытке закрыть Edt - повис окончательно.

### ISSUE THREAD

**Issue by DmitryShvaika** [1C-Company/1c-edt-issues#1371]
### Описание ошибки

При включении проверки запросов в тексте (настройки валидации проекта) Edt повис на 99 % и не завершал процесс. При попытке закрыть Edt - повис окончательно.

Стек вызовов тут
[threaddump.zip](https://github.com/1C-Company/1c-edt-issues/files/14726701/threaddump.zip)

### Как воспроизвести

1. -

### Ожидаемое поведение

не должен зависать

### Лог рабочей области

лог
[логи.zip](https://github.com/1C-Company/1c-edt-issues/files/14726711/default.zip)

### Версия 1С:EDT

Ruby 2023.3.3

### Операционная система

Windows

**Comment by Erik773** [comment]
Дубль #1373
