### ISSUE TITLE
Не завершается проверка проекта с полными настройками валидации (включая проверку запросов)

### ISSUE THREAD

**Issue by DmitryShvaika** [1C-Company/1c-edt-issues#1373]
### Описание ошибки

Не завершается проверка проекта с полными настройками валидации (включая проверку запросов). Зависает на 99% и не двигается уже 40 мин.

Файл с настройками валидации:
[Edt-Project-Full.zip](https://github.com/1C-Company/1c-edt-issues/files/14735197/Edt-Project-Full.zip)

Стек вызовов:
[threaddump.zip](https://github.com/1C-Company/1c-edt-issues/files/14735199/threaddump.zip)

### Как воспроизвести

Можно попытаться загрузить настройки валидации в любой большой проект, например УТ. Но в параметрах Edt должна быть включена настройка: "Включить расчет типов контента для строковых литералов"
Не факт, что получится, поэтому приложил стек вызовов

### Скриншоты

![image](https://github.com/1C-Company/1c-edt-issues/assets/54451084/e1e67406-4c4b-4370-ab85-523bb5da48dd)

При попытке закрыть Edt в таком состоянии он зависает на деактивации проектных контекстов

![image](https://github.com/1C-Company/1c-edt-issues/assets/54451084/1f044fa3-ef33-4dbc-8740-ff40eb99f598)

### Ожидаемое поведение

Расширенная проверка не должна зависать.

### Лог рабочей области

[логи.zip](https://github.com/1C-Company/1c-edt-issues/files/14735201/default.zip)

### Версия 1С:EDT

Ruby 2023.3.3

### Операционная система

Windows

**Comment by Erik773** [comment]
Здравствуйте @DmitryShvaika !
Могли бы вы, пожалуйста, предоставить конфигурацию для воспроизведения проблемы?
Файлы можно прислать письмом на edt@1c.ru или, если большой объем, то на ftp https://partners.v8.1c.ru/topics/81.
Когда файлы будут отправлены, напишите, пожалуйста, номер обращения.

**Comment by DmitryShvaika** [comment]
> Здравствуйте @DmitryShvaika ! Могли бы вы, пожалуйста, предоставить конфигурацию для воспроизведения проблемы? Файлы можно прислать письмом на [edt@1c.ru](mailto:edt@1c.ru) или, если большой объем, то на ftp https://partners.v8.1c.ru/topics/81. Когда файлы будут отправлены, напишите, пожалуйста, номер обращения.

К сожалению рабочую конфигурацию предоставить не могу ...
Попробую повторить ошибку ну другой, например типовой конфигурации.
Если не воспроизводится и не удается повторить ошибку - давайте пока закроем
Ошибка не критичная - - после снятия процесса проект нормально загружается и работает...

**Comment by DmitryShvaika** [comment]
Проверил, на БСП данный профиль нормально применяется. Ошибка не повторяется.

**Comment by Erik773** [comment]
Тогда пока закрываем.
При необходимости задачу можно переоткрыть.
Спасибо.
