### ISSUE TITLE
Ошибочно выдается сообщение "Добавление типизированного значения в нетипизированную коллекцию" при добавлении значения в типизированный список значений, который является реквизитом формы

### ISSUE THREAD

**Issue by DmitryShvaika** [1C-Company/1c-edt-issues#1375]
### Описание ошибки

Ошибочно выдается сообщение "Добавление типизированного значения в нетипизированную коллекцию" при добавлении значения в типизированный список значений, который является реквизитом формы

![image](https://github.com/1C-Company/1c-edt-issues/assets/54451084/1de50779-ed63-4506-a876-82d89b221fa2)

реквизит СписокЧисел определен как реквизит формы СписокЗначений с типом элемента - Число

![image](https://github.com/1C-Company/1c-edt-issues/assets/54451084/5bd65746-f612-414b-97b8-5d266febd4d2)

### Как воспроизвести

1. Создать произвольную форму
2. На форме создать реквизит СписокЧисел с типом СписокЗначений и типом элемента - Число как на рис
3. Набрать текст формы:

```
// @strict-types - директива для edt - проверка модуля в строгих типах

#Область ОбработчикиСобытийФормы

// При создании на сервере.
// 
// Параметры:
//  Отказ - Булево
//  СтандартнаяОбработка - Булево
//
&НаСервере
Процедура ПриСозданииНаСервере(Отказ, СтандартнаяОбработка)
	
	СписокЧисел.Добавить(1);
	
КонецПроцедуры

#КонецОбласти

```
4. Наблюдать ошибку

### Ожидаемое поведение

Ошибка не должна детектироваться, так как коллекция типизированная

### Лог рабочей области

не требуется

### Версия 1С:EDT

Ruby 2023.3.3

### Операционная система

Windows

**Comment by adminimusRU** [comment]
Дубль #1203

**Comment by DmitryShvaika** [comment]
да, спасибо... не нашел ее потому что выполнена, но еще не вышла в релиз
