### ISSUE TITLE
Повисла Edt при проверке когда добавил новый модуль и перенес одну функцию в него.

### ISSUE THREAD

**Issue by DmitryShvaika** [1C-Company/1c-edt-issues#1379]
### Описание ошибки

Повисла Edt при проверке когда добавил новый модуль и перенес одну функцию в него.

![image](https://github.com/1C-Company/1c-edt-issues/assets/54451084/eeba9d5a-c061-462f-9720-31da89c715f2)

30 мин уже в таком состоянии - счетчик ни на единицу не меняется, однако что-то работает куча регулярно заполняется и очищается...
Конфигурация небольшая - после загрузки все проверки завершаются обычно за 30 мин.

Стек вызовов:
[threaddump.zip](https://github.com/1C-Company/1c-edt-issues/files/14823987/threaddump.zip)

### Как воспроизвести

- разовая ошибка

### Ожидаемое поведение

Edt не должна зависать

### Лог рабочей области

[логи.zip](https://github.com/1C-Company/1c-edt-issues/files/14823996/default.zip)

### Версия 1С:EDT

Ruby 2023.3.3

### Операционная система

Windows

**Comment by Erik773** [comment]
Здравствуйте Дмитрий!
Для обхода проблемы можем порекомендовать попробовать пока отключить проверки QL.

**Comment by Erik773** [comment]
> А удалось установить причину?

Пока нет, нужно исследовать проблему.
