### ISSUE TITLE
Недоступность поля выбора родительской ветки git для скрытия ошибок

### ISSUE THREAD

**Issue by adminimusRU** [1C-Company/1c-edt-issues#1380]
### Описание ошибки

В настройках валидации проекта добавилась настройка, позволяющая скрывать ошибки выбранной родительской ветки git. Доступность поля выбора ветки зависит от того, как именно включается флаг скрытия ошибок.

### Как воспроизвести

1. Открыть свойства проекта - -V8 - валидация - настройки для разработчиков
2. Кликнуть по заголовку (тексту) флажка "Спрятать результаты проверок для выбранной ветки"
Флажок включается, но поле выбора ветки git остается недоступным.
Если же включать флажок кликом именно по самому квадратику флажка или с использованием клавиатуры, то поле выбора будет доступно.

### Скриншоты

Включение флажка кликом по заголовку:
![image](https://github.com/1C-Company/1c-edt-issues/assets/28653631/7e1e7b6a-8813-4582-8d67-c8ec115dd5bb)
Включение флажка кликом по самому флажку или с клавиатуры:
![image](https://github.com/1C-Company/1c-edt-issues/assets/28653631/ec91ce34-0dc9-46c8-a3f2-7086d229b7f6)

### Ожидаемое поведение

Поле выбора ветки должно быть доступно независимо от способа включения флажка.

### Лог рабочей области

[logs.zip](https://github.com/1C-Company/1c-edt-issues/files/14832286/logs.zip)

### Версия 1С:EDT

2023.3.3

### Операционная система

Windows

**Comment by LesN1ck** [comment]
Также если поставить флажок, применить и закрыть, а потом открыть свойства заново - поле будет доступно.

**Comment by vadimeg** [comment]
Исправлено в 2024.1. Также должно быть перенесено в 2023.3
