### ISSUE TITLE
Ошибка отправки изменений в удаленный репозиторий из - под РЕД ОС 7.3.4

### ISSUE THREAD

**Issue by chernayevalexey** [1C-Company/1c-edt-issues#1381]
### Описание ошибки

Ошибка в том что изменения не отправляются в удаленный репозиторий.

### Как воспроизвести

1. Перспектива git . 2 отправить в удаленный репозиторий.

### Ожидаемое поведение

Отправка успешная в удаленный репозиторий 

### Лог рабочей области

Нет лога

### Версия 1С:EDT

Ruby 2023.2.6.4

### Операционная система

Linux

**Comment by Erik773** [comment]
Здравствуйте @chernayevalexey!
Могли бы вы, пожалуйста, прислать логи рабочей области ЕДТ на момент возникновения проблемы (.log, .bak.log и trace.log можно найти в папке .metadata) и настройки пользователя/репозитория git (Окно -> Параметры -> Групповая разработка -> Git -> Конфигурация -> Настройки пользователя, Настройки репозитория)?
Путь до рабочей области можно узнать, нажав кнопку со значком папки для проекта в 1C:EDT Start, либо посмотреть в настройках ЕДТ, подробнее о рабочей области https://its.1c.ru/db/edtdoc#content:194:hdoc
Также если есть, то были бы полезны файлы формата hs_err_pid из директории с клиентом ЕДТ.

**Comment by Erik773** [comment]
Закрываем задачу из-за непредоставления данных.
В дальнейшем задачу можно переоткрыть и прикрепить запрошенные данные.
