### ISSUE TITLE
"Свойства модуля" в переменных не обновляются

### ISSUE THREAD

**Issue by KovAlexey** [1C-Company/1c-edt-issues#1382]
### Описание ошибки

Ошибка в том что...
если единожды раскрыть в любом контексте свойства модуля, то они больше не обновляются.

### Как воспроизвести

1. Запустите отладку в функции из которой есть переход в другой контекст  (Например, из модуля формы в модуль менеджера или общий модуль)
2. Раскройте Свойства модуля
![изображение](https://github.com/1C-Company/1c-edt-issues/assets/16429518/b8f5af64-248c-4257-9789-6bd4baeabccf)

3. Перейдите в новый контекст
4. Свойства модуля не обновятся
![изображение](https://github.com/1C-Company/1c-edt-issues/assets/16429518/8d56e4c1-bd40-4eee-9ab3-5e2d0a137dca)

Так же эта проблема наблюдается и при следующем коде
```

IBslStackFrame debugContext = DebugUITools.getDebugContext().getAdapter(IBslStackFrame.class);
moduleProperty = bslStackFrame.getModuleProperties();
```
При смене стека меняется все, кроме свойств модуля. 
Все остальное обновляется нормально.

### Ожидаемое поведение

Обновление списка при смене контекста.

### Лог рабочей области

[log.zip](https://github.com/1C-Company/1c-edt-issues/files/14836666/log.zip)

### Версия 1С:EDT

2023.2.4

### Операционная система

Windows

### Установленные плагины

1C:Code style V8, 1C:SSL-support, 1C:Language Tool

**Comment by DmitryBelov-e1c** [comment]
Исправлено в 2024.1.
