### ISSUE TITLE
В конструкторе печати, в макет,  не подтягиваются поля

### ISSUE THREAD

**Issue by vverja** [1C-Company/1c-edt-issues#1389]
### Описание ошибки

Ошибка в том, что в любом документе, при вызове конструктора печати, когда выбираем все необходимые поля для вставки в макет, в конце, при нажатии "Готово" выдается сообщение, что не выбраны поля для заполнения. При этом создается макет, который не открывается для редактирования. А при сборке конфигурации вылазит ошибка: "Ошибка разбора XML ...Фатальная ошибка: Extra content at the end of document..." и далее путь к  пустому XML файлу "Template.xml"

### Как воспроизвести

1. Кликните правой клавишей мыши по любому документу 
2. Выберите Конструкторы - Конструкторы печати
3. Укажите нужные поля в шапке и табличной части
4. В конце нажмите кнопку "Готово"
5. Вылезет окно с сообщением "Не выбраны поля для заполнения макета"

### Скриншоты

![Снимок экрана от 2024-04-08 18-17-24](https://github.com/1C-Company/1c-edt-issues/assets/9655095/ad3b3eb3-1f92-4f83-84d1-92b65bf76b6d)
![image](https://github.com/1C-Company/1c-edt-issues/assets/9655095/1ea85540-0e1a-4583-86ab-06f4e1578dee)
[
![Снимок экрана от 2024-04-08 18-19-19](https://github.com/1C-Company/1c-edt-issues/assets/9655095/b6a4d908-0648-497d-9c6e-d79d3d9f6be2)
](url)

### Ожидаемое поведение

Все выбранные поля добавлены в макет и отображаются, сборка проходит нормально

### Лог рабочей области

[trace.log](https://github.com/1C-Company/1c-edt-issues/files/14907604/trace.log)
[.log](https://github.com/1C-Company/1c-edt-issues/files/14907605/default.log)
[.bak_5.log](https://github.com/1C-Company/1c-edt-issues/files/14907606/default.bak_5.log)
[.bak_4.log](https://github.com/1C-Company/1c-edt-issues/files/14907607/default.bak_4.log)
[.bak_3.log](https://github.com/1C-Company/1c-edt-issues/files/14907608/default.bak_3.log)
[.bak_2.log](https://github.com/1C-Company/1c-edt-issues/files/14907609/default.bak_2.log)
[.bak_1.log](https://github.com/1C-Company/1c-edt-issues/files/14907611/default.bak_1.log)
[.bak_0.log](https://github.com/1C-Company/1c-edt-issues/files/14907612/default.bak_0.log)

### Версия 1С:EDT

Ruby 2023.2.4

### Операционная система

Windows

### Установленные плагины

Нет плагинов

**Comment by wolfandw** [comment]
На 2023.3.6 не воспроизводится
