### ISSUE TITLE
Ошибка обновления ИБ расширением с формами с отключенными типовыми командами (Сверх критическая)

### ISSUE THREAD

**Issue by agibalovsa** [1C-Company/1c-edt-issues#1395]
### Описание ошибки

Если в расширении содержится форма, в которой отключены некоторые команды (Рис. 1, 2), то при обновлении ИБ возникает ошибка (Рис. 3).
Причем если то же самое сделать в основной конфигурации, то ошибок не будет

### Как воспроизвести

1. Расширить форму
2. Отключить команду (Рис. 1)
3. Обновить ИБ (Рис. 3)
4. Если включить команды, то ошибки не будет

### Скриншоты

![image](https://github.com/1C-Company/1c-edt-issues/assets/14235747/12d71a10-beb7-4583-9d61-1a54df43adf1)
(Рис. 1.)

![image](https://github.com/1C-Company/1c-edt-issues/assets/14235747/0f97b992-ed4b-41e6-9275-b79cef030776)
(Рис. 2.)

![image](https://github.com/1C-Company/1c-edt-issues/assets/14235747/3bd3c195-a3f7-4aa2-a97f-896aba278342)
(Рис. 3.)

### Ожидаемое поведение

Это ошибка. На релизе Ruby 2023.2.4 такой ошибки нет.

### Лог рабочей области

[metadata.zip](https://github.com/1C-Company/1c-edt-issues/files/14945873/metadata.zip)

### Версия 1С:EDT

Ruby 2023.3.4

### Операционная система

Windows

### Установленные плагины

1C:Code style V8, 1C:SSL-support

**Comment by vadimeg** [comment]
Исправлено в 2024.1

**Comment by fenixnow** [comment]
коллеги, продолжаем ловит аналогичную ошибку на версии EDT Ruby 2023.3.5

Конфигурация Зарплата и управление персоналом КОРП, редакция 3.1
Платформа 

Присутствует расширение расширяющее стандартные формы, в расширяемых формах ЗУП в командных интерфейсах выключены некоторые кнопки.

![image](https://github.com/1C-Company/1c-edt-issues/assets/13418562/009f4b1d-ee7a-4983-a5ae-86b0f322dc1a)
![image](https://github.com/1C-Company/1c-edt-issues/assets/13418562/ae76e8ab-ba27-4188-ba75-46562cbef78b)


[log.txt](https://github.com/1C-Company/1c-edt-issues/files/15480293/log.txt)

**Comment by fenixnow** [comment]
@vadimeg Коллеги, обратите пожалуйста внимание на сообщение. 
Может мы делаем что то не так?

**Comment by vadimeg** [comment]
> @vadimeg Коллеги, обратите пожалуйста внимание на сообщение. Может мы делаем что то не так?

Скорее всего эти три команды не должны быть доступны для отключения, поэтому платформа их не принимает.
Для начала можно попробовать снова включить их (убрать из исключенных), сделать клин проекта и посмотреть будут ли они в списке команд.
И еще хорошо бы посмотреть в конфигураторе это расширение, есть ли там эти команды в списке.

**Comment by vadimeg** [comment]
Если очистка проекта-расширения не помогает, то зарегистрируйте, пожалуйста, баг. Это другая ситуация, чем описана в этой задаче. Здесь была проблема именно с отключением команд на заимствованных динамических списках в форме расширения

**Comment by agibalovsa** [comment]
Коллеги, добрый день.
@vadimeg на самом деле это та же ошибка, что возникала и у меня. Если в расширении присутствует список отключенных команд, то EDT выдает ошибку.
Т.е. в основной конфигурации эти команды могут быть включены, могут быть выключены - без разницы. Если в расширении возникает блок отключенных команд, то возникает ошибка.
Когда в основной конфигурации команды отключены, то при создании расширения этот блок (отключенных команд) дублируется в файл расширения, так работают расширения, как я понимаю.
И поэтому при расширении форм из конфигурации, где есть отключенные команды возникает ошибка. Этой ошибки нет на релизе 2023.2.4. А в релизе 2023.3.4 была. На последнем релизе EDT я еще не проверял. При этом я не замечал, чтобы при переходе с релиза 2.4 на 3.4, блок отключенных команд появлялся или пропадал, если предположить, что этот блок в расширении появляется ошибочно.

**Comment by vadimeg** [comment]
@agibalovsa Добрый день, посмотрите, пожалуйста, на последнем релизе. Там были исправления по отключенным командам.

**Comment by agibalovsa** [comment]
@vadimeg ошибка воспроизводится на релизе 2023.3.6.
![image](https://github.com/user-attachments/assets/ff93628b-970a-44a5-85bb-f765923a8c5f)
![image](https://github.com/user-attachments/assets/ae94c6cb-478c-468d-ad11-3bda1699496e)
![image](https://github.com/user-attachments/assets/2c733faf-9699-412f-9965-5d627cebabc8)
![image](https://github.com/user-attachments/assets/a6c6fe40-9094-4eb5-86cf-875ccc0d0c2f)

**Comment by vadimeg** [comment]
Исправлено в 2024.1

**Comment by agibalovsa** [comment]
@vadimeg Ошибка возникает на 2024.1.1

com._1c.g5.v8.dt.platform.services.core.runtimes.execution.RuntimeCoreException: Ошибка взаимодействия с платформой 1С:Предприятия 8.3.22.2557:
Ошибка загрузки/выгрузки конфигурации
Неверное имя команды элемента формы. - ReportSettings
Неверное имя команды элемента формы. - ReportSettings

**Comment by vadimeg** [comment]
> @vadimeg Ошибка возникает на 2024.1.1
> 
> com._1c.g5.v8.dt.platform.services.core.runtimes.execution.RuntimeCoreException: Ошибка взаимодействия с платформой 1С:Предприятия 8.3.22.2557: Ошибка загрузки/выгрузки конфигурации Неверное имя команды элемента формы. - ReportSettings Неверное имя команды элемента формы. - ReportSettings


Добрый день, а на каких конфигурациях воспроизводилось?
SSL (ssl_edt) сейчас на 8.3.24. У вас 8.3.22 это в проекте расширения? И, если не сложно, приложите проект расширения.

**Comment by agibalovsa** [comment]
@vadimeg Добрый день.
Ошибка возникает на 2024.1.2

![image](https://github.com/user-attachments/assets/c751fe96-b6b0-4966-b990-a7a4792504ea)

**Comment by vadimeg** [comment]
Добрый день, были ошибки с загрузкой исключенных команд на автономном сервере с 8.3.24 и на более ранних версиях платформы (8.3.22) для файловой выгрузки. Вроде их не все еще исправили. А вот в более ранние версии платформы не очень часто портируются исправления. Можете проверить на 8.3.24+?

**Comment by agibalovsa** [comment]
@vadimeg да, на 24 все работает. Спасибо.
