### ISSUE TITLE
Не запускается EDT после обновления его версии

### ISSUE THREAD

**Issue by stolya** [1C-Company/1c-edt-issues#1399]
### Описание ошибки

При повышении версии EDT у проекта практически всегда EDT зависает. В большинстве случаев проблема решается принудительной остановкой EDT и повторным запуском проекта.
Сейчас при повышении версии EDT c 2023.3.3 на 2023.3.4 процесс запуска на одном проекте завис и не отвисает (простоял в попытке запуститься всю ночь). Принудительная остановка EDT не помогает.

### Как воспроизвести

1. В 1C:EDT Start выполнил обновление EDT с версии 2023.3.3 на 2023.3.4
2. Запускаю проект EDT
3. Зависание запуска

### Скриншоты

![image](https://github.com/1C-Company/1c-edt-issues/assets/30523530/1df9ec05-84ac-4e45-9356-88ad17f00a0c)
![image](https://github.com/1C-Company/1c-edt-issues/assets/30523530/c45a39e9-43a1-4295-9c0f-206f3db2ed1e)

### Ожидаемое поведение

Процесс повышения версии EDT не приводит к зависанию

### Лог рабочей области

[.metadata.zip](https://github.com/1C-Company/1c-edt-issues/files/14954490/default.metadata.zip)

### Версия 1С:EDT

Ruby 2023.3.4

### Операционная система

Windows

### Установленные плагины

1C:Code style V8, 1C:SSL-support

**Comment by adminimusRU** [comment]
В логе EDT ругается на нехватку памяти, попробуйте размер кучи увеличить.

**Comment by agibalovsa** [comment]
@adminimusRU при каждом обновлении на любой машине EDT не запускается после перезапуска после обновления. Он висит минут 30 без признаков жизни, потом вываливает ошибку timeout 1000 и зависает. Если после этого снять процессы и запустить снова - то все ок.  При это зависает вне зависимости от размера проекта.
Такая проблему уже лет 5 наблюдается - детская болячка.

**Comment by adminimusRU** [comment]
> при каждом обновлении на любой машине EDT не запускается после перезапуска после обновления.

ни разу такое не ловил за несколько лет. Возможно, специфика версии со стартером (у меня оффлайн всегда).

**Comment by grigmily** [comment]
[threaddump.txt](https://github.com/1C-Company/1c-edt-issues/files/14971421/threaddump.txt)

**Comment by a2080016** [comment]
* Всегда после обновления висит минут 40.
* Принудительно завершаем.
* Следующие запуски Ок.

**Comment by LesN1ck** [comment]
Встречал похожую проблему. Пока для себя сделал вывод, что это антивирус проверяет новую инсталляцию. Взял за правило после обновления среды полчаса не запускать рабочие области на новой версии. Вроде стало работать корректно, без зависаний на первом запуске.

**Comment by tretyakevich** [comment]
Данная проблема будет решена с выходом 2024.1

**Comment by a2080016** [comment]
> Данная проблема будет решена с выходом 2024.1

**Респект!**

**Comment by agibalovsa** [comment]
Добрый день. 
@tretyakevich 
Теперь оболочка не зависает, а зависают фоновые задания пересчета контекста проекта. Зафиксировал ошибку #1541
