### ISSUE TITLE
Молча не выполняется активации контекста проекта если установлена JAVA 19 Orcale

### ISSUE THREAD

**Issue by tormozit** [1C-Company/1c-edt-issues#1402]
### Описание ошибки

Активация проектного контекста не запустилась если используется JAVA 19.

### Как воспроизвести

Установить JAVA 11 Bellsoft. Затем установить JAVA 19 Orcale (пропишется в переменные среды).
Создать рабочую область и клонировать проект конфигурации из гит репозитория.
Активация проектного контекста не запустилась.
(картинку взял из другой ситуации, поэтому в ней в заголовке проекта не указана связанная ветка)

![изображение](https://github.com/1C-Company/1c-edt-issues/assets/11896251/56b591e4-d151-4fbd-b8d9-79bbfcc0a4cf)

### Ожидаемое поведение

Выдать понятную пользователю ошибку типа "Некорректная версия JAVA" при старте приложения EDT или хотя бы при открытии проекта

### Лог рабочей области

[Clip_578520.txt](https://github.com/1C-Company/1c-edt-issues/files/14996139/Clip_578520.txt)

### Версия 1С:EDT

2023.2.4

### Операционная система

Windows

### Установленные плагины

Нет плагинов

**Comment by Erik773** [comment]
Здравствуйте Сергей!
Критический приоритет убран, так как java 19 пока не поддерживается, информация есть на [странице с требованиями к программному обеспечению](https://edt.1c.ru/docs/intro/requirements.php), а также проблема не соответствует критической по [критериям критичности ошибок](https://github.com/1C-Company/1c-edt-issues/blob/main/TASK_CLASSIFICATION.md)

**Comment by tormozit** [comment]
Аргументация смены критичности странная. Я ведь указал четко ожидаемое поведение. Там я НЕ ждал поддержки 19-й JAVA. 
На многопользовательском сервере с JAVA 11 кто то установил JAVA 19 без уведомления нас. У нас внезапно перестал работать EDT. Мы потеряли много времени на поиске причины этой проблемы. Поэтому и был выставлен такой приоритет, т.к. приложение могло бы **значительно** сократить время решения блокирующей его работу проблемы.

**Comment by Erik773** [comment]
> Там я НЕ ждал поддержки 19-й JAVA.
спасибо за уточнение, смысл задачи понятен

> На многопользовательском сервере с JAVA 11 кто то установил JAVA 19 без уведомления нас.
кажется, это частный и специфичный сценарий, не носящий массового или постоянного характера.

> Выдать понятную пользователю ошибку типа "Некорректная версия JAVA" при старте приложения EDT или хотя бы при открытии проекта
не является критической ошибкой в соответствии с опубликованными критериями.

**Comment by tormozit** [comment]
С критичного до низкого - это сильный ход. Можно еще написать, что сам пользователь виноват в том сразу не проверил версию JAVA. Тогда можно и пометку "ошибка" убрать и переквалифицировать в пожелание.

> не носящий массового или постоянного характера
Хотите сказать, что EDT используют только в средах, где JAVA не используют для других приложений, которым нужна более высокая версия?

**Comment by tretyakevich** [comment]
Исправлено в 2024.1
