### ISSUE TITLE
Запуск EDT в английском исполнении интерфейса, но иметь возможность видеть объекты метаданных на русском языке

### ISSUE THREAD

**Issue by fullstack1c** [1C-Company/1c-edt-issues#141]
### Описание проблемы

Хочу запускать EDT в английском исполнении интерфейса, но иметь возможность видеть объекты метаданных на русском языке

### Описание решения проблемы

Предлагаю сделать так, чтобы был некий параметр в настройках рабочей области, где я могу отдельно выбрать язык оболочки и отдельно язык подсистем 1С

**Comment by marmyshev** [comment]
Такой переключатель есть на панели - выпадающий список языков вашей конфигурации - если вы метаданные пишете на русском - будут русские (синонимы).

**Comment by fullstack1c** [comment]
Синонимы, но я имел ввиду, именования метаданных в навигации Documents - Документы, Catalogs - Справочники

**Comment by marmyshev** [comment]
> я имел ввиду, именования метаданных в навигации Documents - Документы, Catalogs - Справочники

Это часть интерфейса ЕДТ (точно так как и в Конфигураторе!), к метаданным и их именам это не имеет никакого отношения.  

Если считаете, что есть практический смысл чтобы команда ЕДТ занялась таким пожеланием и резала интерфейс "тут хочу видеть русский, а тут хочу видеть английский" - пожалуйста опишите подробно с примерами все-все места где требуется оставить русский,  аргументируйте почему это следует сделать и пере-открывайте пожелание.
