### ISSUE TITLE
Переименование локальной переменной портит комментарии по всей конфигурации

### ISSUE THREAD

**Issue by DmitryShvaika** [1C-Company/1c-edt-issues#1412]
### Описание ошибки

Переименование локальной переменной портит комментарии по всей конфигурации

![РефакторингПереименованиеПеременной](https://github.com/1C-Company/1c-edt-issues/assets/54451084/c995bc44-fe51-4091-8448-9cc7522990ba)

### Как воспроизвести

1. Набрать текст модуля:

```
// @strict-types - директива для edt - проверка модуля в строгих типах

#Область ПрограммныйИнтерфейс

// Конструктор1.
// 
// Параметры:
//  ИсходнаяСтруктура - Число
// 
// Возвращаемое значение:
//  Число
//
Функция Конструктор1(ИсходнаяСтруктура) Экспорт
	
	ИсходнаяСтруктура = 34;
	
	Возврат ИсходнаяСтруктура;
	
КонецФункции

Функция Конструктор2() Экспорт
	
	ИсходнаяСтруктура.Вставить("Поле1", 0);
	
	Возврат ИсходнаяСтруктура;
	
КонецФункции

#КонецОбласти

```

2. Выполнить переименование переменной как на видео

### Ожидаемое поведение

Переименование локальной переменной не должно затрагивать другие функции

### Лог рабочей области

не требуется

### Версия 1С:EDT

Ruby 2023.3.4

### Операционная система

Windows

**Comment by DmitryShvaika** [comment]
Есть еще вариант, когда не только комментарии портит, но и сами переменные переименовывает по всем модулям (наверное думает, что глобальная). Но пока не воспроизвел

**Comment by DmitryShvaika** [comment]
А так еще переименовывается и ключевое слово Параметры.

![РефакторингПереименованиеПеременной](https://github.com/1C-Company/1c-edt-issues/assets/54451084/4ee4c2c5-665b-4bd8-a8be-d1612f4cee99)

**Comment by MaksimDzyuba** [comment]
Здравствуйте, исправил, исправление будет в 2024.1
