### ISSUE TITLE
Зависло при работе

### ISSUE THREAD

**Issue by Jimmo910** [1C-Company/1c-edt-issues#1425]
### Описание ошибки

Писал код. и оно зависло. (пир это не работала кнопка delete)

Ждал минут 10. Потом снял дамп потоков. После запустил Дамп памяти.
И как ток снял их так все отвисло. Но часть кода не сохранилась.

**Если по дампам и логам причина не понятна. Тогда закройте задачу.**

### Как воспроизвести

Не знаю =)

### Ожидаемое поведение

что бы Не зависало

### Лог рабочей области

[log.txt](https://github.com/1C-Company/1c-edt-issues/files/15292948/log.txt)
[trace.txt](https://github.com/1C-Company/1c-edt-issues/files/15292949/trace.txt)

### Версия 1С:EDT

2023.2.4

### Операционная система

Windows

### Версия платформы 1С:Предприятие 8

8.3.23.2137

### Дополнительная информация

Дамп памяти https://disk.yandex.ru/d/1f1haaVvZCY6rw
дамп потоков https://disk.yandex.ru/d/nNIE_ItKup-ABg

**Comment by Erik773** [comment]
Здравствуйте @Jimmo910!
К сожалению, по логам пока не удалось понять причины проблемы.
Подскажите, пожалуйста, у вас 4К монитор?

**Comment by Jimmo910** [comment]
@Erik773 у меня 2к монитор.

**Comment by Erik773** [comment]
Благодарим за предоставленную информацию.
Но, к сожалению, причины возникновения проблемы по дампу определить не удалось.
Пока закрываем задачу, можно её переоткрыть, если появится дополнительная информация по проблеме.
