### ISSUE TITLE
Зависание EDT 2023.2.4 при запуске отладки 

### ISSUE THREAD

**Issue by ElchinGasanov** [1C-Company/1c-edt-issues#1427]
### Описание ошибки

EDT просто зависла  при начале отладки . 
Интерфейс заблокировался.

### Как воспроизвести

1) В конфигурации удалили регзадание. 
2) Добавили обработку 
3) Запустили отладку 
4) EDT завис.

### Скриншоты

![image](https://github.com/1C-Company/1c-edt-issues/assets/94464246/3dfeddda-1518-4b2e-b896-7c51876cd21a)

### Ожидаемое поведение

Корректный запуск отладки 

### Лог рабочей области

[log (2).txt](https://github.com/1C-Company/1c-edt-issues/files/15318053/log.2.txt)
[threaddump (4).txt](https://github.com/1C-Company/1c-edt-issues/files/15318057/threaddump.4.txt)
дамп памяти https://disk.yandex.ru/d/Ri0z2YMKzgMWkQ

### Версия 1С:EDT

Ruby 2023.2.4

### Операционная система

Windows

### Версия платформы 1С:Предприятие 8

8.3.22.2411

**Comment by Erik773** [comment]
Здравствуйте, @ElchinGasanov !
Могли бы вы, пожалуйста, предоставить все лог файлы из рабочей области EDT на момент возникновения проблемы (.log и trace.log).
И еще, пожалуйста, переснимите дамп потоков, потому что тот, который прикреплен к задаче был снят либо не с edt, либо с edt в момент старта (до того, как отладку можно вообще запустить).

**Comment by ElchinGasanov** [comment]
Добрый день, при повторном возникновении ошибки, я сниму информацию. 
Если ошибка не повториться на этой неделе, то  закрою issue.

**Comment by tretyakevich** [comment]
Закрыта по причине невозможности воспроизведения
