### ISSUE TITLE
Не создается приложение в панели Приложения при импорте проекта из информационной базы с расширением.

### ISSUE THREAD

**Issue by DmitryShvaika** [1C-Company/1c-edt-issues#1430]
### Описание ошибки

Если проект импортируется из информационной базы, в которой есть расширения (импорт вместе с расширением). То по окончании импорта не создается Приложение в панели Приложения. При запуске отладки такого проекта выдается диалог создания приложения с предложением повторной загрузки проекта из информационной базы

![image](https://github.com/1C-Company/1c-edt-issues/assets/54451084/dc458b24-2556-44f9-a8cd-7deb51eea682)

### Как воспроизвести

1. Создать пустую информационную базу
2. Создать в ней расширение
3. Создать проект
4. Создать общий модуль
5. Импортировать проект из информационной базы вместе с расширением 
6. Наблюдать отсутствие Приложения в панели Приложения

### Ожидаемое поведение

Приложение должно создаваться как если бы импортировали проект из информационной базы без расширения

### Лог рабочей области

не требуется

### Версия 1С:EDT

Ruby 2023.3.5

### Операционная система

Windows

### Версия платформы 1С:Предприятие 8

8.3.21.1644

### Дополнительная информация

Если попытаться создать приложение без полной загрузки - создается, но при старте отладки пишет:
![image](https://github.com/1C-Company/1c-edt-issues/assets/54451084/ed5e39ed-a282-4c11-bc9b-b61485f82a7b)

Дополнительно прилагаю архив с выгрузкой информационной базы и расширения:
[Тест.zip](https://github.com/1C-Company/1c-edt-issues/files/15360841/default.zip)

**Comment by DmitryShvaika** [comment]
Дополнительно, если попытаться создать приложение без полной загрузки - создается, но при старте отладки пишет:
![image](https://github.com/1C-Company/1c-edt-issues/assets/54451084/bcc8a677-dd09-4b2e-ae8e-8243b17f48fd)

**Comment by Erik773** [comment]
Удалось воспроизвести проблему по следующему сценарию:

1. Создать новую информационную базу;
2. Загрузить в неё dt файл из архива в описании задачи;
3. Импортировать конфигурацию из информационной базы в ЕДТ, вызвав для неё команду контекстного меню;

Возникает такая ошибка:

![error](https://github.com/1C-Company/1c-edt-issues/assets/93516265/1fb9c28a-24ab-4326-a649-890ff680825c)
[log.txt](https://github.com/1C-Company/1c-edt-issues/files/15378094/log.txt)
[trace.log](https://github.com/1C-Company/1c-edt-issues/files/15378095/trace.log)

**Comment by DmitryShvaika** [comment]
Можете еще просто сами создать пустую базу с одним модулем и повторить сценарий. Думаю, результат будет тем  же...

**Comment by Erik773** [comment]
> Можете еще просто сами создать пустую базу с одним модулем и повторить сценарий. Думаю, результат будет тем же...
По этому сценарию воспроизвести проблему не удалось.

**Comment by Erik773** [comment]
Видимо, в описании шагов воспроизведения ошибка, на шаге 3 вместо "Создать проект" должно быть "Создать модуль".

**Comment by DmitryShvaika** [comment]
> Видимо, в описании шагов воспроизведения ошибка, на шаге 3 вместо "Создать проект" должно быть "Создать модуль".

поправил

**Comment by nikolay-martynov** [comment]
Здравствуйте, Дмитрий. Чтобы не сталкиваться с данной проблемой, вам необходимо установить обновления для платформы 1С:Предприятие:
- 8.3.21.1661 от 14.12.2022
- 8.3.22.1750 от 07.12.2022
- 8.3.23.1294 от 17.11.2022
- 8.3.24.493 от 02.12.2022

**Comment by DmitryShvaika** [comment]
Спасибо
