### ISSUE TITLE
Вылетает EDT при работе с контекстным меню

### ISSUE THREAD

**Issue by shcherbakov-vadim** [1C-Company/1c-edt-issues#1435]
### Описание ошибки

При работе с контекстным меню в редакторе модуля EDT вылетает

### Как воспроизвести

1. Создать новый проект на версии платформы 8.3.24
2. Сбросить все настройки проекта
3. Добавить общий модуль с процедурой
```bsl
// Проверка.
// 
// Параметры:
//  Объекты - Массив
Процедура Проверка(Объекты)
КонецПроцедуры
```
4. Написать в внутри процедуры Объекты., дождаться появления контекстного меню, затем нажать и удерживать кнопку курсор вниз
5. Приложение завершается

### Ожидаемое поведение

Корректная работа

### Лог рабочей области

!SESSION 2024-05-22 22:16:59.817 -----------------------------------------------
eclipse.buildId=2023.3.5.10
java.version=11.0.20
java.vendor=BellSoft
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=ru
Command-line arguments:  -os linux -ws gtk -arch x86_64 -data /home/vadim/edt/test

!ENTRY com.company1c.link.ide.edt 1 0 2024-05-22 22:17:03.257
!MESSAGE iLOG: 1C:Link addon is initializing. Web config state is in /home/vadim/edt/test/.metadata/.plugins/com.company1c.link.ide.edt

!ENTRY com._1c.g5.v8.dt.core 1 0 2024-05-22 22:17:04.745
!MESSAGE java.vm.name=OpenJDK 64-Bit Server VM

!ENTRY com._1c.g5.v8.dt.core 1 0 2024-05-22 22:17:04.766
!MESSAGE java.vm.info=mixed mode

!ENTRY com._1c.g5.v8.dt.platform.services.core 1 0 2024-05-22 22:17:04.776
!MESSAGE Trying to re-establish all non-closed SSH connecton...

!ENTRY org.eclipse.ui.navigator 4 0 2024-05-22 22:17:06.823
!MESSAGE An extension already exists with id "org.eclipse.wst.server.ui.ServersView.content.root".

!ENTRY org.eclipse.ui.navigator.resources 4 0 2024-05-22 22:17:09.002
!MESSAGE Required filter org.eclipse.ui.navigator.resources.filters.workingSet is not present. Working set support will not function correctly.

!ENTRY org.eclipse.ui.navigator.resources 4 0 2024-05-22 22:17:09.002
!MESSAGE 

!ENTRY com._1c.g5.v8.dt.md.ui 1 0 2024-05-22 22:17:30.672
!MESSAGE Создается новый проект кофигурации Конфигурация

!ENTRY com._1c.g5.v8.dt.core 1 0 2024-05-22 22:17:30.702
!MESSAGE Project context is being started: Конфигурация (NEW_PROJECT)

!ENTRY com._1c.g5.v8.dt.lifecycle 1 0 2024-05-22 22:17:31.845
!MESSAGE Starting phase LINKING of context ProjectContext: Конфигурация

!ENTRY com._1c.g5.v8.dt.lifecycle 1 0 2024-05-22 22:17:31.845
!MESSAGE Starting phase INITIALIZATION of context ProjectContext: Конфигурация

!ENTRY com._1c.g5.v8.dt.lifecycle 1 0 2024-05-22 22:17:32.197
!MESSAGE Starting phase CHECKING of context ProjectContext: Конфигурация

!ENTRY com._1c.g5.v8.dt.lifecycle 1 0 2024-05-22 22:17:32.200
!MESSAGE Starting phase STORAGE_INITIALIZATION of context ProjectContext: Конфигурация

!ENTRY com._1c.g5.v8.dt.lifecycle 1 0 2024-05-22 22:17:32.444
!MESSAGE Starting phase RESOURCE_LOADING of context ProjectContext: Конфигурация

!ENTRY com._1c.g5.v8.dt.lifecycle 1 0 2024-05-22 22:17:32.599
!MESSAGE Starting phase POST_RESOURCE_LOADING of context ProjectContext: Конфигурация

!ENTRY com._1c.g5.v8.dt.core 1 0 2024-05-22 22:17:32.785
!MESSAGE Project context is started: Конфигурация

!ENTRY org.eclipse.equinox.security 1 0 2024-05-22 22:17:34.407
!MESSAGE New secure storage master password was generated (Linux libsecret integration module). 

!ENTRY com._1c.g5.v8.dt.platform.services.core 1 0 2024-05-22 22:17:34.666
!MESSAGE SSH connecton with infobase Тест (файловая) established.

!ENTRY com._1c.g5.v8.dt.platform.services.core 1 0 2024-05-22 22:17:34.760
!MESSAGE Waiting for synchronization completed.

!ENTRY com._1c.g5.v8.dt.platform.services.core 1 0 2024-05-22 22:17:34.761
!MESSAGE Infobase synchronization tracking BM model Конфигурация started

### Версия 1С:EDT

Ruby 2023.3.5, Ruby 2023.2.4

### Операционная система

Linux

### Версия платформы 1С:Предприятие 8

8.3.22.2175

### Дополнительная информация

Kubuntu 24.04

**Comment by Erik773** [comment]
Здравствуйте @shcherbakov-vadim!
Могли бы вы, пожалуйста, предоставить файлы формата hs_err_pid*.

**Comment by shcherbakov-vadim** [comment]
[hs_err_pid253084.log](https://github.com/1C-Company/1c-edt-issues/files/15420504/hs_err_pid253084.log)

**Comment by Erik773** [comment]
Благодарим за предоставленные данные.
Проблема на стороне Eclipse.
На версии 1C:EDT 2024.1 мы переходим на новую версию Eclipse 2023-12, возможно, проблема будет исправлена.
Попробуйте, пожалуйста, посмотреть на новой версии, актуальна ли проблема.
К сожалению, на данный момент, можем только порекомендовать не использовать синтаксис помощник и не вызывать всплывающие подсказки.

**Comment by shcherbakov-vadim** [comment]
@Erik773 
>Проблема на стороне Eclipse.

Вы правы, удалось воспроизвести проблему в Eclipse 2022-03
>На версии 1C:EDT 2024.1 мы переходим на новую версию Eclipse 2023-12, возможно, проблема будет исправлена. ?>Попробуйте, пожалуйста, посмотреть на новой версии, актуальна ли проблема. 

В Eclipse 2023-12 проблема не воспроизводится

>К сожалению, на данный момент, можем только порекомендовать не использовать синтаксис помощник и не вызывать всплывающие подсказки.

Решение проблемы найдено в этом сообщении https://github.com/adoptium/adoptium-support/issues/785#issuecomment-1585740194. Правда не отображается онлайн-помощь, но по крайней мере можно работать, пока 1C:EDT 2024.1 не выйдет

**Comment by Erik773** [comment]
> Решение проблемы найдено в этом сообщении https://github.com/adoptium/adoptium-support/issues/785#issuecomment-1585740194.

Спасибо за ссылку на решение проблемы.

**Comment by OIegZolotarev** [comment]
Мне помогло помимо папки "/tmp/SWT-GDBusServer" создать еще папку "/tmp/SWT-WebExtensionGDBusServer" - со второй папкой заработали подсказка, онлайн-помощь и все остальное что завязано на webkit.
Проверил на 2023.3.6 и РедОС 8

**Comment by Mikhail0806** [comment]
просто в tmp добавить вручную эти папки?
