### ISSUE TITLE
Не удается выполнить импорт после переключения на другую ветку

### ISSUE THREAD

**Issue by LesN1ck** [1C-Company/1c-edt-issues#1436]
### Описание ошибки

Если в проекте переключиться с одной ветки на другую, то при попытке импортировать конфигурацию возникает ошибка:

> Во время импорта произошла ошибка
> 
> java.lang.IllegalArgumentException
> 	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:128)
> 	at com._1c.g5.v8.dt.internal.platform.services.core.infobases.sync.strategies.AbstractSynchronizationStrategy.getLock(AbstractSynchronizationStrategy.java:831)
> 	at com._1c.g5.v8.dt.internal.platform.services.core.infobases.sync.strategies.OnDemandSynchronizationStrategy.infobasePullChangesRequested(OnDemandSynchronizationStrategy.java:185)
> 	at com._1c.g5.v8.dt.internal.platform.services.core.infobases.sync.InfobaseSynchronization.pullConnectedInfobaseChanges(InfobaseSynchronization.java:661)
> 	at com._1c.g5.v8.dt.internal.platform.services.core.infobases.sync.InfobaseSynchronizationManager.lambda$4(InfobaseSynchronizationManager.java:392)
> 	at com._1c.g5.v8.dt.common.runtime.ProgressMonitors.computeWithSubMonitor(ProgressMonitors.java:278)
> 	at com._1c.g5.v8.dt.internal.platform.services.core.infobases.sync.InfobaseSynchronizationManager.pullInfobaseChanges(InfobaseSynchronizationManager.java:379)
> 	at com._1c.g5.v8.dt.platform.services.core.infobases.sync.IInfobaseSynchronizationManager$pbryglu.pullInfobaseChanges(Unknown Source)
> 	at com._1c.g5.v8.dt.internal.platform.services.ui.infobases._import.ImportConfigurationWizard.importChangesFromInfobase(ImportConfigurationWizard.java:589)
> 	at com._1c.g5.v8.dt.internal.platform.services.ui.infobases._import.ImportConfigurationWizard.importInfobaseChangesToExistingProject(ImportConfigurationWizard.java:529)
> 	at com._1c.g5.v8.dt.internal.platform.services.ui.infobases._import.ImportConfigurationWizard.lambda$2(ImportConfigurationWizard.java:209)
> 	at com._1c.g5.v8.dt.common.runtime.ProgressMonitors.runAsTask(ProgressMonitors.java:191)
> 	at com._1c.g5.v8.dt.internal.platform.services.ui.infobases._import.ImportConfigurationWizard.lambda$1(ImportConfigurationWizard.java:200)
> 	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)

Возможно, это важно - переключение происходит с ветки, к которой не привязано ни одно приложение, на ветку, к которой приложение привязано. Если закрыть рабочее пространство и открыть его обратно - импорт выполняется успешно.

### Как воспроизвести

1. Зайти в рабочую область. При этом в репозитории должна быть открыта ветка, не привязанная ни к одному приложению.
2. Переключиться на другую ветку, которая привязана к приложению.
3. Запустить импорт конфигурации из приложения.
4. Получить ошибку.

### Ожидаемое поведение

После переключения на новую ветку импорт выполняется сразу, без необходимости перезапуска рабочей области.

### Лог рабочей области

[log.log](https://github.com/1C-Company/1c-edt-issues/files/15416708/log.log)
[trace.log](https://github.com/1C-Company/1c-edt-issues/files/15416710/trace.log)

### Версия 1С:EDT

2023.3.5

### Операционная система

Windows

### Версия платформы 1С:Предприятие 8

8.3.22.2239

### Установленные плагины

1C:Code style V8, 1C:SSL-support

**Comment by nikolay-martynov** [comment]
@LesN1ck Здравствуйте, Денис. Скажите пожалуйста, это была разовая ошибка или она у вас повторяется? Мне не удаётся воспроизвести по указанному вами сценарию. Возможно, есть какие-то дополнительные шаги или условия? Сильно поможет, если вы снимите и приложите видео воспроизведения проблемы.

**Comment by LesN1ck** [comment]
> @LesN1ck Здравствуйте, Денис. Скажите пожалуйста, это была разовая ошибка или она у вас повторяется? Мне не удаётся воспроизвести по указанному вами сценарию. Возможно, есть какие-то дополнительные шаги или условия? Сильно поможет, если вы снимите и приложите видео воспроизведения проблемы.

Добрый день. Сценарий стабильно воспроизводится на двух разных рабочих областях. Видео сделаю.

**Comment by nikolay-martynov** [comment]
Здравствуйте, Денис. Исправление будет доступно в версии 2024.1.
