### ISSUE TITLE
При импорте конфигурации из информационной базы в проект edt в карте маршрута бизнес-процесса, который не изменялся,  меняются служебные теги.

### ISSUE THREAD

**Issue by kschkn** [1C-Company/1c-edt-issues#1440]
### Описание ошибки

При импорте конфигурации из информационной базы в проект edt в карте маршрута бизнес-процесса меняются служебные теги у точек действия бизнес-процесса, хотя карта маршрута совсем не менялась, либо менялось свойство одной точки действия.

Меняется в конфигураторе один бизнес-процесс, обновляется база:
![image](https://github.com/1C-Company/1c-edt-issues/assets/16169345/5c25cc0d-70f5-46b3-bf32-be944fe6789c)

EDT не может определить изменения:
![image](https://github.com/1C-Company/1c-edt-issues/assets/16169345/ca25bac9-732f-4e9c-b48b-4ee3c7921651)

В окне сравнения видит изменения не только в измененном БП:
![image](https://github.com/1C-Company/1c-edt-issues/assets/16169345/33927b69-9513-427b-8469-c13fa198c9e3)

Смотрим изменения бизнес-процесса, который не должен был измениться:
![image](https://github.com/1C-Company/1c-edt-issues/assets/16169345/f6d64062-618e-48a7-aba0-93299ff1acf5)

### Как воспроизвести

1. В существующем проекте (при наличии в нем бизнес-процессов) добавьте приложение, обновите ИБ из проекта, либо создайте новый проект и воспользуйтесь базой из вложения: 
[ОшибкаИмпортаВEDT.zip](https://github.com/1C-Company/1c-edt-issues/files/15456821/EDT.zip)

2. Запустите конфигуратор:
![image](https://github.com/1C-Company/1c-edt-issues/assets/16169345/9f57dcd9-7baf-4f50-b431-8b9660456e53)

3. Внесите измение в карту маршрута бизнес-процесса, например, измените заголовок точки действия, либо измените значение реквизита адресации.

4. Сохраните изменения, обновите конфигурацию базы данных, закройте конфигуратор.

5. В EDT импортируйте конфигурацию из ИБ:
![image](https://github.com/1C-Company/1c-edt-issues/assets/16169345/3f24eafb-8fd6-4f2a-9f72-0f76e5504572)

6. В окне сравнения наблюдайте изменения тегов в картах маршрута:
![image](https://github.com/1C-Company/1c-edt-issues/assets/16169345/c4d152e5-d98a-4089-bf58-bd9a1747a110)
![image](https://github.com/1C-Company/1c-edt-issues/assets/16169345/f3ad615b-a5b3-46a8-9b2b-98d822c28ac4)

### Ожидаемое поведение

Должны быть только те изменения, которые реально вносились.

### Лог рабочей области

Не требуется

### Версия 1С:EDT

Ruby 2023.3.5

### Операционная система

Windows

### Версия платформы 1С:Предприятие 8

8.3.23.2157

### Установленные плагины

1C:Language Tool

**Comment by wolfandw** [comment]
Спасибо. Исправлено. Войдет в 2024.2
