### ISSUE TITLE
Лишние команды в составе команд элемента формы реквизита с типом Динамический список

### ISSUE THREAD

**Issue by AKazakov1C** [1C-Company/1c-edt-issues#1442]
### Описание ошибки

При установленных признаках "ИзменятьСоставСтрок", "ИзменятьПорядокСтрок"  наблюдаем лишние команды
 
видим разницу в отображаемых командах 
![image](https://github.com/1C-Company/1c-edt-issues/assets/116161950/680503c7-8c24-493a-9b2e-941bf79d8d1d)

отключаем лишние команды и получаем ошибку

```
com._1c.g5.v8.dt.platform.services.core.runtimes.execution.RuntimeCoreException: Ошибка взаимодействия с платформой 1С:Предприятия 8.3.24.1467:
Операция конфигурирования завершена неуспешно
Операция невозможна: при выполнении импорта конфигурации из XML обнаружены критичные ошибки
Журнал процесса выполнения:
Импорт конфигурации из XML...
Неверное имя команды элемента формы. - MoveItem
``` 

### Как воспроизвести

1. Создайте проект внешней обработки
2. Добавьте реквизит "Динамический список", где основная таблица иерархический справочник с группами и элементами
3. Уберите признаки "ИзменятьСоставСтрок", "ИзменятьПорядокСтрок" 
4. Отредактируйте состав команд, убрав команды "Создать группу", "Переместить в группу"
5. Смотрите ошибку в Журнале ошибок

### Ожидаемое поведение

соответствие состава команд конфигуратору, для исключения недоразумений, что при отключенных признаках можно создавать группы и их перемещать
платформа такой проект не соберет, если разработчик отключит команды для ожидаемого поведения 

https://its.1c.ru/db/metod8dev/content/2811/hdoc 

### Лог рабочей области

не требуется

### Версия 1С:EDT

2023.3.5

### Операционная система

Windows

### Версия платформы 1С:Предприятие 8

 8.3.24.1467

### Установленные плагины

1C:Code style V8, 1C:SSL-support

### Дополнительная информация

[ВнешняяОбработка.zip](https://github.com/1C-Company/1c-edt-issues/files/15483554/default.zip)

проект внешней обработки edt c ошибкой для конфигурации ЗУП

**Comment by vadimeg** [comment]
Исправлено в 2024.1
