### ISSUE TITLE
Поддержка GitHub Copilot в EDT

### ISSUE THREAD

**Issue by zipzip332** [1C-Company/1c-edt-issues#1444]
### Описание проблемы

В Eclipse Marketplace есть такой плагин как Copilot4Eclipse
![image](https://github.com/1C-Company/1c-edt-issues/assets/138719279/dcffd0c1-76d5-46a0-97eb-44330f47369f)
 но при попытке установить его получаю следующее:
![image](https://github.com/1C-Company/1c-edt-issues/assets/138719279/0148b9cb-d10c-435c-a963-f3f365032df6)

### Описание решения проблемы

Хотелось бы чтобы разработчики EDT рассмотрели возможность поддержки этого плагина, т.к. плагин очень полезный, и облегчает процесс разработки

**Comment by tretyakevich** [comment]
Проблема в том, что вы устанавливаете последнюю версию данного плагина, который, очевидно, рассчитан на более актуальную версию Eclipse по сравнению с той, которая используется в EDT 2023.3.

Чисто технически EDT 2024.1 переходит на Eclipse 2023.12, на который (опять же чисто технически) 1.2.0.EA2 ставится.
Какие у них есть предыдущие версии (а у них есть 1.0.0 как минимум) и для каких версий платформ Eclipse они предназначены - можно спросить у них на саппорт-форуме.

**Comment by zipzip332** [comment]
> Проблема в том, что вы устанавливаете последнюю версию данного плагина, который, очевидно, рассчитан на более актуальную версию Eclipse по сравнению с той, которая используется в EDT 2023.3.
> 
> Чисто технически EDT 2024.1 переходит на Eclipse 2023.12, на который (опять же чисто технически) 1.2.0.EA2 ставится. Какие у них есть предыдущие версии (а у них есть 1.0.0 как минимум) и для каких версий платформ Eclipse они предназначены - можно спросить у них на саппорт-форуме.

Я пробовал ставить 1.1, (хотя не узнавал для какой версии она предназначена), все равно не устанавливается

**Comment by tretyakevich** [comment]
Проверил 2024.1 и последний на этот момент Copilot - 1.2.1
Результаты:
- Они зачем-то перешли на использование JS-х библиотек, которые требуют 21-й Java. Поэтому просто так работать не будет. Зачем - это вопрос к авторам Copilot-а.
- Поэтому, если нужен копайлот - то только запуск EDT на 21-й Java, который тестировался внутри, но неофициально, и никаких гарантий полной работоспособности нет.
- С 21-й Java Copilot ставится (если нет - можно добавить в доступные сайты для обновления https://download.eclipse.org/releases/2024-03/)

На этом, собственно, пока этот issue закрывается - переходить на 21-ю версию в ближайших релизах не сможет.

**Comment by Jimmo910** [comment]
Установил я 21 java
Проект с конфигурацией ЕРП.

Если закрыть проект и снова Открыть то проект заного начинает собираться. и так каждый раз Даже если дождаться его сборки, то в следующий раз поновой будет.

сам Copilot4Eclipse не знает языка 1С и bsl
![image](https://github.com/user-attachments/assets/61014a68-7664-40a9-b4ca-c6dd031b7673)

поэтому не вижу смысла =(
