### ISSUE TITLE
Существующая функция глобального контекста CopyFile() помечается как ошибочная

### ISSUE THREAD

**Issue by Bayselonarrend** [1C-Company/1c-edt-issues#1445]
### Описание ошибки

Ошибка в том, что функция КопироватьФайл, записанная в EN варианте как CopyFile, помечается как несуществующая

### Как воспроизвести

1. Написать CopyFile в любом модуле

### Скриншоты

![изображение](https://github.com/1C-Company/1c-edt-issues/assets/105596284/76df57ca-80fc-4459-a1d6-7078f1af3051)
![изображение](https://github.com/1C-Company/1c-edt-issues/assets/105596284/546a4506-fa22-467d-a8bc-d9ae13477d12)

### Ожидаемое поведение

CopyFile не помечается как ошибка

### Лог рабочей области

...

### Версия 1С:EDT

Ruby 2023.2.4

### Операционная система

Windows

### Версия платформы 1С:Предприятие 8

На любой версии

### Установленные плагины

1C:Code style V8

**Comment by tretyakevich** [comment]
Добрый день. Можете предоставить исходник данного модуля? Мы видим выше тоже интересные ошибки

**Comment by Bayselonarrend** [comment]
>Добрый день. Можете предоставить исходник данного модуля? Мы видим выше тоже интересные ошибки

Второе это не ошибка: я просто пытался через ChatGPT перевести модуль и там действительно неправильная лексема) Когда модуль был приведен в порядок, осталась проблема только с CopyFile

Если все таки нужен модуль, то [тут](https://github.com/Bayselonarrend/OpenIntegrations/blob/main/src/en/OPI/src/CommonModules/OPI_TypeConversion/Module.bsl)

**Comment by MaksimDzyuba** [comment]
Здравствуйте, дело в том, что до версии 8.3.18 КопироватьФайл переводилось как FileCopy, а вот с 8.3.18 продолжило жить 2 англоязычных названия CopyFile и FileCopy - https://dl05.1c.ru/content/Platform/8_3_18_1957/1cv8upd_8_3_18_1957.htm#cfd09ff9-5899-11ea-8371-0050569f678a
