### ISSUE TITLE
Скачивать android tools с google

### ISSUE THREAD

**Issue by DitriXNew** [1C-Company/1c-edt-issues#145]
### Описание проблемы

Есть такая настрйока - путь к SDK, хочу чтобы рядом была кнопочка, которая или вела на сайт Google - https://developer.android.com/studio/releases/platform-tools, где я могу скачать и распаковать нужный мне комплект, или, чтобы ЕДТ сама скачивала нужный мне архив и подключала его.
Путь так в принципе не меняется https://dl.google.com/android/repository/platform-tools-latest-windows.zip

### Описание решения проблемы

Надо делать вручную, искать эти ссылки, а действия то по сути очень просто автоматизировать.

**Comment by DmitryBelov-e1c** [comment]
В настройки добавлен диалог скачивания Andoid SDK без поддержки эмулятора. Будет в версии 2024.2.
