### ISSUE TITLE
ИдентификаторРасшифровкиКомпоновкиДанных: Ложная ошибка

### ISSUE THREAD

**Issue by DoublesunRUS** [1C-Company/1c-edt-issues#1451]
### Описание ошибки

Проверка конфигурации ошибочно сообщает:
Нельзя передавать объект типа 'ИдентификаторРасшифровкиКомпоновкиДанных' между клиентом и сервером [Тонкий клиент, Толстый клиент (управляемое приложение), Web-клиент]

Указанный тип можно передавать с клиента на сервер

### Как воспроизвести

Вернуть данный тип в методе, который вызвать в другом контексте исполнения

### Ожидаемое поведение

Ожидаю, что указанный тип не будет регистрироваться как ошибочный при передачи с клиента на сервер

### Лог рабочей области

-

### Версия 1С:EDT

2023.3.5

### Операционная система

Windows

### Версия платформы 1С:Предприятие 8

8.3.23.1997

### Установленные плагины

1C:Code style V8

**Comment by MaksimDzyuba** [comment]
Привет, исправление войдут в 2024.1
