### ISSUE TITLE
Ошибка при обновлении ИБ. Расширенные стандартные команды командной панели.

### ISSUE THREAD

**Issue by johnmacmilan69** [1C-Company/1c-edt-issues#1453]
### Описание ошибки

Конфигурация: Зарплата и управление персоналом КОРП, редакция 3.1 (3.1.27.193) 

Для базы дорабатывается расширение, в котором заимствованы формы (справочники, документы и т.д)
В некоторых заимствованных формах отключены стандартные команды (Записать, ЗаписатьИЗакрыть, Провести, ПровестиИЗакрыть) также как и в основных.

При обновлении ИБ EDT показывает список ошибок из-за которых, дальнейшее обновление ИБ невозможно.

**Операция конфигурирования завершена неуспешно
Ошибка загрузки/выгрузки конфигурации
Неверное имя команды элемента формы.**

### Как воспроизвести

1. В основной конфигурации расширить форму документа "График отпусков".
2. Обновить информационную базу
3. Появится 6 ошибок:

Неверное имя команды элемента формы. - Post
Неверное имя команды элемента формы. - PostAndClose
Неверное имя команды элемента формы. - Write
Неверное имя команды элемента формы. - Post
Неверное имя команды элемента формы. - PostAndClose
Неверное имя команды элемента формы. - Write

### Скриншоты

<img width="654" alt="image" src="https://github.com/1C-Company/1c-edt-issues/assets/36008312/5b13f8c7-ef6a-41f7-9079-834b0a846928">
<img width="425" alt="image" src="https://github.com/1C-Company/1c-edt-issues/assets/36008312/2c7126d1-6a01-4c5e-abb4-f53a7359d6f8">
<img width="593" alt="image" src="https://github.com/1C-Company/1c-edt-issues/assets/36008312/83b42c9b-8888-48bc-a0d8-e8bd054aa27a">

### Ожидаемое поведение

Обновление ИБ должно выполняться без ошибок.
На версии Ruby 2023.2.4 такой проблемы не замечено.

### Лог рабочей области

[log.txt](https://github.com/user-attachments/files/15614272/log.txt)

### Версия 1С:EDT

Ruby 2023.3.5

### Операционная система

Windows

### Версия платформы 1С:Предприятие 8

8.3.22.2239

### Установленные плагины

Нет плагинов

### Дополнительная информация

Перед обновлением была выполнена очистка проекта

**Comment by Erik773** [comment]
Здравствуйте @johnmacmilan69!
Могли бы Вы, пожалуйста, попробовать включить все команды в составе команд расширения, произвести очистку проект-расширения, а потом снова пробовать экспорт в ИБ.

**Comment by johnmacmilan69** [comment]
Здравствуйте @Erik773!

**Comment by johnmacmilan69** [comment]
Здравствуйте @Erik773 !
Да, включил все команды с очисткой проект-расширения. Количество ошибок стало в два раза меньше.
Вторая половина ошибок оставалась, ради эксперимента зашел в BaseForm тех форм, что были с ошибками и удалил строки с excludedCommands, которые падали с ошибкой.
Обновить конфигурацию получилось. На формах документов теперь вылазят лишние кнопки. При нажатии на кнопку "Обновление расширения формы" - система возвращается к старому варианту и обновить конфигурацию уже не получается.

**Comment by Kirill** [comment]
Ошибка продолжается из года в год: #428, #615, #949

**Comment by vadimeg** [comment]
Исправлено в 2024.1

**Comment by Dionisious** [comment]
Ошибка повторяется и на 2024.1.3

![image](https://github.com/user-attachments/assets/ffdfd7f8-8bff-4d0a-b0f5-3fc970552473)

**Comment by vadimeg** [comment]
@Dionisious Это другая ошибка. Это форма журнала документов, в котором зарегистрировано больше одного документа? И команда таблицы формы "Создать по параметру" исключена из состава команд?
Если так, то попробуйте сделать очистку проекта.

В 2024.2 для этого кейса очистку делать не надо, там будет сразу перестраиваться список из состава команд.

**Comment by vadimeg** [comment]
> @vadimeg 2024.2 - будет подарком на НГ ? =))))

Делаем все возможное, чтобы это произошло)

**Comment by Dionisious** [comment]
К сожалению очистка не помогла.

![image](https://github.com/user-attachments/assets/f1a2356e-e03d-47cd-a9f3-caf12adf4646)

Это форма обработки ПодборТоваровВДокументПродажи из УТ.

**Comment by vadimeg** [comment]
@Dionisious 
> Это форма обработки ПодборТоваровВДокументПродажи из УТ. Удаление в xml тега конечно помогает, но это же не дело. Да и искать сложно. Это в данном случае я знаю какая форма, а если много форм изменено то и не понятно в какой именно ошибка.

В формах этой обработки не нашел исключенной команды CreateByParameter. Но она есть в других обработках -
УправлениеОтгрузкой и УправлениеПоступлением. Возможно у нас разные конфигурации УТ.

Насколько я понял, речь идет о расширении. В любом случае, в 2024.2 ошибки экспорта не будет.
Чтобы исправить проблему сейчас, попробуйте следующее. В основной конфигурации (не в расширении) таблица формы, на которой исключена команда CreateByParameter, должна ссылаться на динамический список, у которого основная таблица указывает га журнал документа. В этом журнале документа зарегистрировано больше одного документа.
После того, как форма была добавлена в расширение, а также в форме был заимствован динамический список, то не все зависимости были добавлены в расширение, а свойство журнала документа "Регистрируемые документы" не было поставлено на контроль.
Если вы добавите в расширение зарегистрированные в ЖД документы, а также у ЖД в расширении добавите в свойство "Регистрируемые документы" эти заимствованные документы, а затем сделаете очистку проекта расширения, то команда CreateByParameter должна стать доступной у таблицы и тогда не придется удалять ее из xml.

На самом деле, конфигуратор похоже тоже делает не совсем правильно.
Провел вот такой эксперимент.
- Новая пустая конфигурация
- В ней ЖД, два документа. Оба документа добавлены в ЖД в свойство "Регистрируемые документы"
- Создана обработка и форма обработки, в которой есть динамический список с главной таблицей, указывающей на ЖД. Список добавлен на форму (таблица). У таблицы исключаем команду CreateByParameter.
- Добавляем форму в расширение. Заимствуем динамический список.
- При этом автоматически в расширение добавляется ЖД и только первый документ из списка "Регистрируемые документы"!
- Свойство ЖД "Регистрируемые документы" в расширении ставится на контроль, а в список добавляется только первый документ.
- Таким образом команда CreateByParameter становится недоступной в расширении, т.к. для ее наличия необходимо, чтобы было 2 и более документов.

Заведем баг на платформу.

**Comment by Dionisious** [comment]
@vadimeg , спасибо большое за информацию.
