### ISSUE TITLE
Edt не видит экспортные клиентские переменные формы.

### ISSUE THREAD

**Issue by DmitryShvaika** [1C-Company/1c-edt-issues#1456]
### Описание ошибки

Edt не видит экспортные клиентские переменные формы.

![image](https://github.com/1C-Company/1c-edt-issues/assets/54451084/de0b8abd-3c23-4dd2-9922-575a4d2b9a0c)

![image](https://github.com/1C-Company/1c-edt-issues/assets/54451084/fe750daa-8248-4dbf-80ff-6c7118a2b2a3)

### Как воспроизвести

1. Загрузить информационную базу из приложенного файла архива
[test.zip](https://github.com/user-attachments/files/15864475/test.zip)

2. Загрузить проект из информационной базы
3. Наблюдать ошибку

### Ожидаемое поведение

Ошибка не должна диагностироваться

### Лог рабочей области

не требуется

### Версия 1С:EDT

Ruby 2023.3.5

### Операционная система

Windows

### Версия платформы 1С:Предприятие 8

8.3.21.1644

**Comment by adminimusRU** [comment]
Дубль #792
