### ISSUE TITLE
Ошибка загрузки формы отчета расширения

### ISSUE THREAD

**Issue by Kirill** [1C-Company/1c-edt-issues#1460]
### Описание ошибки

При экспорте формы отчета в расширении возникает ошибка загрузки в базу 1С
![image](https://github.com/1C-Company/1c-edt-issues/assets/302940/dbaa40d9-a855-4f1d-9aa5-efe2f2c55ae5)
Ругается на каждое дополнительное значение формы отчета:
- Результат
- ДанныеРасшифровки
- НаименованиеТекущегоВарианта
- НазваниеВарианта   

### Как воспроизвести

1. Загружаем demo_dt (от платформы) в базу.
2. В конфигураторе добавляем новое расширение с типом Дополнение
3. В EDT импортируем конфигурацию и расширение с именем demo.*
4. Создаем отдельную папку demo (инициализуем там git) с такой структурой:
- cfg
- exts
  - ВесТоваров
  - Дополнение
  - Колонтитулы
5. Переносим из проекта в demo (в соответствующие папки)
6. Далее импортируем проект из git 
![image](https://github.com/1C-Company/1c-edt-issues/assets/302940/f48fd22b-059e-4c96-845c-d2617afd68cc)
7. Добавляем форму ФормаОтчета отчета ОстаткиТоваровНаСкладах в расширение Дополнение
8. Экспортируем Дополнение в файлы XML из EDT или с помощью edtcli.
9. Пытаемся загрузить в расширение 1С из файлов XML и получаем ошибку.

На всякий случай само demo из пункта 5
[demo.zip](https://github.com/user-attachments/files/16011521/demo.zip)
и расширение Дополнение в форме XML (из EDT и из EDTCli)
[demo_xml.zip](https://github.com/user-attachments/files/16011539/demo_xml.zip)

### Ожидаемое поведение

Необходимо чтобы 1С собрало расширение с формой отчета

### Лог рабочей области

[log.log](https://github.com/user-attachments/files/16011504/log.log)

### Версия 1С:EDT

Ruby 2023.2.4

### Операционная система

Windows, Linux

### Версия платформы 1С:Предприятие 8

8.3.23.2040

### Установленные плагины

Нет плагинов

**Comment by MaksimDzyuba** [comment]
Ошибка на 2023.3.5 не воспроизводится, лично обсуждали, стало все как хорошо
