### ISSUE TITLE
При импорте расширения в EDT, происходит смена видов галок способа расширения у некоторых свойств.

### ISSUE THREAD

**Issue by TkachenkoPI** [1C-Company/1c-edt-issues#1462]
### Описание ошибки

При импорте расширения в EDT, происходит смена видов галок способа расширения у некоторых свойств. Обнаружено у свойств "Code length", "Description length". Когда работаем с одним из свойств указанных выше, если в расширении был тип "Checked the value when an extension is applied", то в расширении в EDT будет "Change value upon enabling extension".

У свойства "Predefined" в конфигураторе есть только "Change value upon enabling extension", но в расширении EDT такого типа у свойства вообще нет. Есть "Checked the value when an extension is applied", которое и ставится + "Notify of discrepancy when an extension is applied".

### Как воспроизвести

Создайте расширение.
Добавьте в него объект. 
Проставьте у свойств "Code length", "Description length" тип "Checked the value when an extension is applied".
Импортируйте расширение в EDT.
У свойств будет флаг с типом "Change value upon enabling extension".

### Скриншоты

![image](https://github.com/1C-Company/1c-edt-issues/assets/24578477/a38256e5-6814-466e-a259-8d8e626f5e3a)
![image](https://github.com/1C-Company/1c-edt-issues/assets/24578477/eac22a1a-66ba-4891-a578-44353b52c906)

### Ожидаемое поведение

Галочки будут одинаковых типов.

### Лог рабочей области

[.log](https://github.com/user-attachments/files/16062905/default.log)

### Версия 1С:EDT

2023.2.4

### Операционная система

Windows

### Версия платформы 1С:Предприятие 8

8.3.23.1865

**Comment by Erik773** [comment]
Здравствуйте @TkachenkoPI!
Проблема исправлена в версии 1C:EDT 2024.1
