### ISSUE TITLE
Неизвестны элементы коллекции ДетальныеРасписанияДня для расписания регламентного задания

### ISSUE THREAD

**Issue by d-hurricane** [1C-Company/1c-edt-issues#1466]
### Описание ошибки

EDT никак не вычисляет тип элементов коллекции `ДетальныеРасписанияДня` для объекта встроенного языка `РасписаниеРегламентногоЗадания`.

### Как воспроизвести

1. Создать пустую конфигурацию. Добавить общий модуль.
2. Написать код:
```bsl
// @strict-types

Процедура МояПроцедура()
	
	Расписание = Новый РасписаниеРегламентногоЗадания();
	РасписаниеДня = Расписание.ДетальныеРасписанияДня[0];
	Результат = РасписаниеДня.ВремяНачала;
	
КонецПроцедуры
```
3. Убедиться, что EDT не может вычислить тип переменной `РасписаниеДня`, а как следствие и не распознает поле `ВремяНачала`.

### Скриншоты

![image](https://github.com/1C-Company/1c-edt-issues/assets/59051827/cc8cbbba-ff60-4de6-9005-0fe7bb7beecf)
![image](https://github.com/1C-Company/1c-edt-issues/assets/59051827/abc000f5-b176-408e-b11d-0aace6e6166b)

### Ожидаемое поведение

EDT должно вычислять тип переменной РасписаниеДня как `РасписаниеРегламентногоЗадания`. Дополнительно EDT должно предупреждать разработчика о проблеме, если код в дальнейшем содержит некорректную установку свойств расписания.

### Лог рабочей области

[test.log](https://github.com/user-attachments/files/16133770/test.log)

### Версия 1С:EDT

Ruby 2023.3.5

### Операционная система

Windows

### Версия платформы 1С:Предприятие 8

8.3.22.2501

### Установленные плагины

1C:Code style V8, 1C:SSL-support

**Comment by MaksimDzyuba** [comment]
Здравствуйте, дополнил типизацию.
![image](https://github.com/user-attachments/assets/760bc88d-b4f0-417e-87a3-ce900addda1c)
