### ISSUE TITLE
Неизвестны элементы коллекции Месяцы для расписания регламентного задания

### ISSUE THREAD

**Issue by d-hurricane** [1C-Company/1c-edt-issues#1467]
### Описание ошибки

EDT никак не вычисляет тип элементов коллекции `Месяцы` для объекта встроенного языка `РасписаниеРегламентногоЗадания`.

### Как воспроизвести

1. Создать пустую конфигурацию. Добавить общий модуль.
2. Написать код:
```bsl
// @strict-types

Процедура МояПроцедура()
	
	Расписание = Новый РасписаниеРегламентногоЗадания();
	НомерМесяца = Расписание.Месяцы[0];
	Результат = Дата(2024, НомерМесяца, 1);
	
КонецПроцедуры
```
Убедиться, что EDT не может вычислить тип переменной `НомерМесяца`, а как следствие считает, что в функцию `Дата` передан аргумент некорректного типа.

### Скриншоты

![image](https://github.com/1C-Company/1c-edt-issues/assets/59051827/a156d50a-a6fd-4604-873f-741f034fdeb2)
![image](https://github.com/1C-Company/1c-edt-issues/assets/59051827/814d656a-56f3-4fd2-81a3-eac4bccf8bc8)

### Ожидаемое поведение

EDT должно вычислять тип переменной `НомерМесяца` как `Число`.

### Лог рабочей области

[test.log](https://github.com/user-attachments/files/16133943/test.log)

### Версия 1С:EDT

Ruby 2023.3.5

### Операционная система

Windows

### Версия платформы 1С:Предприятие 8

8.3.22.2501

### Установленные плагины

1C:Code style V8, 1C:SSL-support

**Comment by MaksimDzyuba** [comment]
Здравствуйте, дополнил типизацию.
![image](https://github.com/user-attachments/assets/8e5049a6-cd71-4f37-8416-f9dc7dc29db7)
