### ISSUE TITLE
Git: Конфигуратор не понимает ЕДТ

### ISSUE THREAD

**Issue by Roffild** [1C-Company/1c-edt-issues#1470]
1С 8.3.24.1624
ЕДТ 2023.3.6

Пора уже разобраться с форматами хранения Конфигурации!

ЕДТ создает .git по умолчанию в `conf/.git` вместо `conf/src/.git`.
Зачем мне внутренности ЕДТ пихать в Git?
Ну, если приспичило настройки проекта расшарить (осуждаю такое), то нормальные IDE создадут папку `conf/src/.1cedt`.

При попытки загрузить из репы ЕДТ в Конфигураторе получаю:
> Файл объекта не существует - Configuration.xml

**КРИТИЧЕСКИЙ БАГ!!!**
1Сники не договорились о формате хранения Конфигурации :D

ЕДТ хранит папку `Configuration/`.

Конфигуратор:
```
Ext/ManagedApplicationModule.bsl
Languages/
ConfigDumpInfo.xml
Configuration.xml
```

`ConfigDumpInfo.xml` лучше в `.gitignore` запихать, потому что меняется часто, но для Загрузки не нужен.

Нужно ещё разработать правила `.gitattributes` - сейчас CRLF скачет.

Сейчас в Конфигураторе делайте Выгрузку в репу - Загрузите везде ;)

**Comment by aashtv** [comment]
Если репозиторий будет создаваться внутри `./src`, то не получится в одном репозитории держать все компоненты проекта (конфа поставщика, расширения, внешние обработки, документацию, тесты). Настройки ненужные можно в игнор закинуть.

А вот при создании репозитория из EDT сразу добавлять в игнор всякие `./Configuration/ParentConfigurations` и т. п. было бы неплохо. Можно и настройки проекта, но найдутся команды которым, хотя бы опционально, надо чтобы настройки были общие на всех.

**Comment by Roffild** [comment]
> Если репозиторий будет создаваться внутри `./src`, то не получится в одном репозитории держать все компоненты проекта (конфа поставщика, расширения, внешние обработки, документацию, тесты). Настройки ненужные можно в игнор закинуть.

Ничего из перечисленного в ЕДТ сейчас не хранится в этой папке. Там другая структура папок:
```
.settings\
DT-INF\
src\
.project
```

**Comment by Roffild** [comment]
> А вот при создании репозитория из EDT сразу добавлять в игнор всякие `./Configuration/ParentConfigurations` и т. п. было бы неплохо.

В `ParentConfigurations` находится оригинальная Конфигурация на поддержке. Плохая идея хранить это в Git, но сейчас приходится...

Расширения избавлены от этих МБайтов.

**Comment by aashtv** [comment]
Вы неправильно структуру каталогов указываете. Там, для сферической БП в вакууме будет:
```
./Accounting/.settings/
./Accounting/DT-INF/
./Accounting/src/
./Accounting/.project
```

Когда к этому добавится расширение с адаптациями под заказчика, станет:
```
./Accounting/.settings/
./Accounting/DT-INF/
./Accounting/src/
./Accounting/.project
./Accounting.MyOrganisation/.settings/
./Accounting.MyOrganisation/DT-INF/
./Accounting.MyOrganisation/src/
./Accounting.MyOrganisation/.project
```

А когда вы документацию писать будете, вы туда же, вероятно, и `./doc` положите, если она не настолько большая, что отдельным проектом в отдельном репозитории существует. 

И средства для сборки и тестирования туда же. Учитывая, что оно согласовано с проектом должно быть, будет странным это держать в отдельном репозитории.

>Плохая идея хранить это в Git, но сейчас приходится...

А `.gitignore` для кого?

**Comment by aashtv** [comment]
> А в чём проблема хранения дополнительных папок в `./src`? Конфигуратор проигнорирует неизвестные папки при Загрузке.

В том, что мух от котлет надо отдельно держать.

**Comment by Roffild** [comment]
Я хочу Загружать проект в Конфигураторе, поэтому структура такая:
```
./Accounting/**/
./Accounting/Configuration.xml
./Accounting.MyOrganisation/**/
./Accounting.MyOrganisation/Configuration.xml

./doc/
./builder/
./tester/
```

Конфигуратор **БЕЗ** ЕДТ принимает эту структуру папок. Со структурой ЕДТ сам Конфигуратор вас пошлёт с ошибкой.

Вообще, сам факт спора о структуре папок - признак, что разработчики ЕДТ накосячили.

>> Плохая идея хранить это в Git, но сейчас приходится...
>
> А .gitignore для кого?

Не удивляйтесь, когда Конфигуратор откажет при отсутствии "Конфигурация поставщика".

**Comment by tretyakevich** [comment]
Добрый день. Из описания проблемы непонятна сама суть проблемы.
EDT не хранит конфигурацию в формате XML Платформы. Поэтому каким образом src проекта в формате EDT относится к заявленной проблеме (отсутствие Configuration.xml) - непонятно.

Можете предоставить пошаговый сценарий воспроизведения проблемы?

**Comment by Roffild** [comment]
Подтвердите официально:
Формат EDT НЕ совместим с Платформой. Так задумано и изменений в этом не будет. Два разных формата.

**Comment by vadimeg** [comment]
1. Формат EDT НЕ совместим с Платформой
Да

2. Так задумано 
Да

3. и изменений в этом не будет. 
По крайней мере, в ближайших планах нет

4. Два разных формата.
Да. При этом из формата EDT есть экспорт в формат платформы и наоборот.
