### ISSUE TITLE
Разработка в расширении. Невозможность вставки в запрос в аннотации &ИзменениеИКонтроль

### ISSUE THREAD

**Issue by Xelgo** [1C-Company/1c-edt-issues#1472]
### Описание ошибки

В случае если инъекции в типовой код делаются непосредственно в текст запроса - ЕДТ начинает сходить с ума.

### Как воспроизвести

1. Взять типовой модуль, где описан запрос. 
2. Написать инъекцию #Вставка #КонецВставки в середину текста запроса. 
3. Увидеть ошибки в этом месте, а так же несуществующие ошибки в последующем коде модуля.

Синтаксическая ошибка. Неверный ввод "'#Вставка'" - ожидается
   """
### Скриншоты

![image](https://github.com/user-attachments/assets/75c4dd2e-c4b9-4344-b095-9b9d5bddf994)

### Ожидаемое поведение

Поведение как в конфигураторе. Конфигуратор понимает такой принцип доработок и не выводит ошибок при проверке модуля. 

### Лог рабочей области

Лог не нужен.

### Версия 1С:EDT

Ruby 2023.3.6

### Операционная система

Windows

### Версия платформы 1С:Предприятие 8

8.3.24

**Comment by NikitaMikhaylovSB** [comment]
Это вопрос много раз обсуждался... 
Правильно: менять весь текст (удобно или нет - другой вопрос :) )

**Comment by Xelgo** [comment]
Да, нашёл старую переписку. Одно дело, когда это не по стандартам и есть какое-то правило, которое можно отключить. Другое дело, когда ЕДТ не умеет в контекст таких доработок и сыпит хард ошибки, которые никак не подавить( Не работает: //@skip-check org.eclipse.xtext.diagnostics.Dagnostic.Syntax):
![image](https://github.com/user-attachments/assets/3ff5286e-5ba4-45b1-8e9f-ff90a6dd4ee5)
![image](https://github.com/user-attachments/assets/5e616f3e-2e06-4a48-b089-8d1cf80c0614). 

Я даже не представляю ситуацию, когда есть какой-то огромнейший типовой запрос или куча лесенок Если в типовом коде, где надо просто сделать небольшую инъекцию посередине для удобства читаемости, что первостепенным является на мой взгляд, тут же предлагается полностью #Удалить #КонецУдаления. В общем, хотелось бы чтобы было "как в конфигураторе".

**Comment by NikitaMikhaylovSB** [comment]
Пример с разрывом синтаксических конструкция иной, чем про запросы

**Comment by goodwinvu** [comment]
> Да, нашёл старую переписку. Одно дело, когда это не по стандартам и есть какое-то правило, которое можно отключить. Другое дело, когда ЕДТ не умеет в контекст таких доработок и сыпит хард ошибки, которые никак не подавить( Не работает: //@skip-check org.eclipse.xtext.diagnostics.Dagnostic.Syntax):
> ![image](https://github.com/user-attachments/assets/3ff5286e-5ba4-45b1-8e9f-ff90a6dd4ee5)
> ![image](https://github.com/user-attachments/assets/5e616f3e-2e06-4a48-b089-8d1cf80c0614). 
> 
> Я даже не представляю ситуацию, когда есть какой-то огромнейший типовой запрос или куча лесенок Если в типовом коде, где надо просто сделать небольшую инъекцию посередине для удобства читаемости, что первостепенным является на мой взгляд, тут же предлагается полностью #Удалить #КонецУдаления. В общем, хотелось бы чтобы было "как в конфигураторе". 
> 
> 
> 

Этот случай как раз и есть - не по стандарту

**Comment by aashtv** [comment]
Если подобный прием - ошибка, почему разрыв строки в данном случае не считается ошибкой?
![photo_2024-07-24_20-56-40](https://github.com/user-attachments/assets/2bba5cca-2e16-4943-8790-38509570d080)

Код что с разрывом комментарием, что инструкцией #Вставка / #Удаление платформой корректно интерпретируется.

**Comment by Erik773** [comment]
Критический приоритет убран так как проблема не соответствует критериям критичности https://github.com/1C-Company/1c-edt-issues/blob/main/TASK_CLASSIFICATION.md

**Comment by Roffild** [comment]
Мнение ЕДТ можно игнорировать, если Конфигуратор позволяет ;)

Код будет работать, но авто-дополнение в ЕДТ будет чудить.

**Comment by tretyakevich** [comment]
Дубликат https://github.com/1C-Company/1c-edt-issues/issues/1475
