### ISSUE TITLE
Разработка в расширении из конфигуратора не подтягивается в EDT

### ISSUE THREAD

**Issue by Xelgo** [1C-Company/1c-edt-issues#1473]
### Описание ошибки

Ошибка в том что: При добавлении изменений в расширение cfe из конфигуратора, ЕДТ их к себе не подтягивает во время обновления БД. 
Пример: 
![image](https://github.com/user-attachments/assets/01e8cf03-6b95-46aa-9472-c8d01ff20b28)
Добавили новый общий модуль. 

EDT при обновлении не видит эти изменения сделанные в расширении: 
![image](https://github.com/user-attachments/assets/0e9b9a4b-fc4d-40ba-a5ea-ef92de6822fc)

Общий модуль не появился:
![image](https://github.com/user-attachments/assets/74f64298-936d-4808-b637-13d2544cb880)

### Как воспроизвести

1. Перейдите в конфигуратор.
2. Создайте новый объект\измените старый.
3. Вернитесь в EDT - получите рассинхрон.

### Ожидаемое поведение

EDT должен предлагать синхронизацию с результатом работы в конфигураторе когда речь идёт про расширения.

### Лог рабочей области

[trace.txt](https://github.com/user-attachments/files/16362048/trace.txt)

### Версия 1С:EDT

Ruby 2023.3.6

### Операционная система

Windows

### Версия платформы 1С:Предприятие 8

8.3.24.1368

### Установленные плагины

Нет плагинов

**Comment by Erik773** [comment]
Здравствуйте @Xelgo!
Подскажите, пожалуйста, после внесения изменений в конфигурацию информационной базы, вы производили импорт изменений в проект конфигурации ЕДТ?

**Comment by Erik773** [comment]
Задача закрывается по причине непредоставления запрошенных данных. В случае предоставления необходимой для воспроизведения проблемы информации задачу рекомендуется переоткрыть.
