### ISSUE TITLE
Жалуется на недопустимые права в роли расширения.

### ISSUE THREAD

**Issue by Xelgo** [1C-Company/1c-edt-issues#1474]
### Описание ошибки

Есть роль в расширении: система проверок жалуется, что в рамках этой роли выданы недопустимые права:
![image](https://github.com/user-attachments/assets/e06fadca-4d3d-4c8e-beba-9aec36e9ef3a)

### Как воспроизвести

Создать роль в расширении, проверить на ошибки. 

### Ожидаемое поведение

В расширении невозможно для роли установить подобного рода права. По этому EDT не должен писать эти ошибки.

### Лог рабочей области

Не требуется.

### Версия 1С:EDT

Ruby 2023.3.6

### Операционная система

Windows

### Версия платформы 1С:Предприятие 8

8.3.24

### Установленные плагины

Нет плагинов

**Comment by Erik773** [comment]
Здравствуйте @Xelgo!
Могли бы вы, пожалуйста, предоставить проект расширения конфигурации для воспроизведения проблемы?
Вы используете типовую конфигурацию? Если да, укажите пожалуйста, какую, если нет, то есть ли возможность предоставить её для воспроизведения?
В случае невозможности предоставить расширение и родительскую конфигурацию, могли бы Вы, пожалуйста, подробно описать сценарий воспроизведения на новой чистой конфигурации?

**Comment by Erik773** [comment]
Задача закрывается по причине непредоставления запрошенных данных. В случае предоставления необходимой для воспроизведения проблемы информации задачу рекомендуется переоткрыть.
