### ISSUE TITLE
После заимствования формы отчета в расширение приложение не собирается

### ISSUE THREAD

**Issue by petypen** [1C-Company/1c-edt-issues#1479]
### Описание ошибки

Ошибка в том что, после заимствования в расширение формы отчета приложение перестает запускаться. При сборке приложения сообщение об ошибке: Неверное имя команды элемента формы. - ChangeSettingsStructure и другие сообщения.

### Как воспроизвести

На примере приложения 1С:Комплексная автоматизация 2 (2.5.18.54)
Приложение развернуто на файловой базе и подключено через автономный сервер.

Создаю новый проект расширения и в него заимствую форму отчета "АнализСчета". Никаких дополнительных действий в расширении не произвожу.
![2024-07-31_19-54-14](https://github.com/user-attachments/assets/911751c4-cc91-44de-92be-c059081b012c)

Далее запускаю приложение в тонком клиенте. В процессе сборки получаю ошибку: Неверное имя команды элемента формы. - ChangeSettingsStructure и еще несколько подобных.
![2024-07-31_19-57-55](https://github.com/user-attachments/assets/a64b0802-d8da-483f-be71-93fbe0ba1842)

Приложение не запускается. Поведение повторяется на платформе 8.3.24.1586 и на последней версии 8.3.24.1667

### Ожидаемое поведение

При заимствовании формы любого объекта приложение должно собираться

### Лог рабочей области

[metadata.zip](https://github.com/user-attachments/files/16444995/metadata.zip)

### Версия 1С:EDT

Ruby 2023.3.6

### Операционная система

Windows

### Версия платформы 1С:Предприятие 8

8.3.24.1667

### Дополнительная информация

Приложение подключено через автономный сервер.

**Comment by vadimeg** [comment]
Добрый день, а пробовали делать полную выгрузку не через автономный сервер?

**Comment by petypen** [comment]
Добрый день. Нет не пробовал.

**Comment by vadimeg** [comment]
Вопрос был связан вот с чем. Скорее всего проблема - в поддержке автономного сервера на стороне платформы, поэтому исправление вероятно будет не скоро. В связи с этим, на текущий момент для данной конфигурации неиспользование автономного сервера, при условии, что в этом случае сборка пройдет без ошибок, это единственный вариант решения проблемы.

**Comment by petypen** [comment]
Я проверил. Действительно, без автономного сервера приложение собирается.

**Comment by vadimeg** [comment]
Завели ошибку на АС:

[60016580](https://clio.dept07/Tasks006/#e1cib/data/%D0%A1%D0%BF%D1%80%D0%B0%D0%B2%D0%BE%D1%87%D0%BD%D0%B8%D0%BA.%D0%9E%D1%88%D0%B8%D0%B1%D0%BA%D0%B8?ref=8cd3005056bea45e11ef5a59fd2d6892)

**Comment by nikolay-martynov** [comment]
@petypen Здравствуйте. Да, к сожалению есть такая известная проблема. Мы ждём исправления платформы для задачи 60010684. О доступности исправления мы сообщим вам дополнительно. Пожалуйста имейте в виду, что также самая проблема может проявляться как следующая последовательность сообщений:

```
[INFO] Импорт конфигурации из XML...
[ERROR] Операция невозможна: при выполнении импорта конфигурации из XML обнаружены критичные ошибки
[ERROR] Неверное имя команды элемента формы. - Post
[ERROR] Неверное имя команды элемента формы. - PostAndClose
[ERROR] Неверное имя команды элемента формы. - Write
[ERROR] Неверное имя команды элемента формы. - Post
[ERROR] Неверное имя команды элемента формы. - PostAndClose
[ERROR] Неверное имя команды элемента формы. - Write
[ERROR] Неверное имя команды элемента формы. - Write
[ERROR] Импорт конфигурации из XML завершен с ошибкой
```

**Comment by nikolay-martynov** [comment]
@petypen Здравствуйте. Проблема частично исправлена в 1С:Предприятие 8.3.25.1526. Для полного исправления требуется использовать версии 8.3.26.1515, 8.3.27.1314 или выше. В EDT 2024.2 требования к версиям платформы будут повышены соответствующим образом.
