### ISSUE TITLE
Ошибка при импорте конфигурации в проект EDT

### ISSUE THREAD

**Issue by AlexandrRS** [1C-Company/1c-edt-issues#148]
### Описание ошибки

При импортировании конфигурации, содержащей доработки, возникает много различающихся объектов, в основном Отображение подсказки.

### Как воспроизвести

1. Перейдите в `...`
2. Кликните по `....`
3. Прокрутите вниз до `....`
4. Смотрите ошибку в `....`

### Скриншоты

![Скриншот 01-12-2021 105927](https://user-images.githubusercontent.com/95341591/144200042-7dcd86e6-b741-4e77-a194-206292356c8c.jpg)

### Ожидаемое поведение

Показать только измененные объекты.

### Лог рабочей области

[bak.2021-11-30.0.log](https://github.com/1C-Company/1c-edt-issues/files/7632239/bak.2021-11-30.0.log)

### Версия 1С:EDT

Ruby 2021.2.10

### Операционная система

Windows

### Дополнительная информация

1С:Предприятие 8.3 (8.3.19.1264)

**Comment by vadimeg** [comment]
Исправлено в 2021.3
