### ISSUE TITLE
Не ругаться на недокументированный тип "ОсновнойЭлементФормы"

### ISSUE THREAD

**Issue by SeiOkami** [1C-Company/1c-edt-issues#1482]
### Описание ошибки

Регается на тип "ОсновнойЭлементФормы"
Этот тип хоть и недокументирован, но его приходится использовать в коде при обработке открытых окон. 

https://seiokami.github.io/posts/vot-takoy-zapros-otroetsa/

### Как воспроизвести

Сообщить(Тип("ОсновнойЭлементФормы"));

### Скриншоты

![image](https://github.com/user-attachments/assets/92267ef5-dd24-41ce-a426-f2bb5eed0aef)

### Ожидаемое поведение

На тип хотя бы не ругается

### Лог рабочей области

[log.txt](https://github.com/user-attachments/files/16500102/log.txt)

### Версия 1С:EDT

Ruby 2023.3.6

### Операционная система

Windows

### Версия платформы 1С:Предприятие 8

8.3.24.1342

**Comment by MaksimDzyuba** [comment]
Здравствуйте, да, ошибка, поправим. А к чему ссылка в описании ошибки - https://seiokami.github.io/posts/vot-takoy-zapros-otroetsa/?

**Comment by MaksimDzyuba** [comment]
Здравствуйте, исправим в 2024.2
![image](https://github.com/user-attachments/assets/b3fab0c1-7536-4ee3-98f7-f886594be310)
