### ISSUE TITLE
Снятие флага "Произвольный запрос" в свойствах динамического списка не удаляет текст запроса из XML исходника

### ISSUE THREAD

**Issue by tormozit** [1C-Company/1c-edt-issues#1486]
### Описание ошибки

Снятие флага "Произвольный запрос" в свойствах динамического списка не удаляет текст запроса из XML исходника. А должно удалять. XML файл после снятия флажка приложен
[Clip_617170.txt](https://github.com/user-attachments/files/16549638/Clip_617170.txt)

Это приводит к тому, что при некорректном тексте клиентское приложение выдает непонятные ошибки. Например при программной установке флажка ПроизвольныйЗапрос этот невидимый в среде разработки текст активируется и вызывает ошибки.

### Как воспроизвести

1. Создать форму любого списка БД
2. У ее динамического списка включить флажок ПроизвольныйЗапрос и установить некорректный текст запроса.
3. Убрать флажок ПроизвольныйЗапрос 
4. В ПриСозданииНаСервере добавить код 
```
&НаСервере
Процедура ПриСозданииНаСервере(Отказ, СтандартнаяОбработка)
	Список.ПроизвольныйЗапрос = Истина;
	ИсполняемаяСхема = Элементы.Список.ПолучитьИсполняемуюСхемуКомпоновкиДанных();
КонецПроцедуры
```
5. Обновить базу 1С.
6. Запустить клиентское приложение в базе 1С.
7. Открыть эту форму

Возникает внесенная в текст запроса ошибка

Ошибка при выполнении запроса.
по причине:
{(8, 15)}: Поле не найдено "ОчередиЗадач.НаименованиеEn"
ОчередиЗадач.<<?>>НаименованиеEn КАК НаименованиеEn,

![изображение](https://github.com/user-attachments/assets/3df5bd15-5797-4a33-b196-6d0dc352ed72)

### Скриншоты

![изображение](https://github.com/user-attachments/assets/cf87b25e-9629-40db-aa91-6f463d7f90ff)

![изображение](https://github.com/user-attachments/assets/96e8010e-a93c-4177-afc1-36f2f6dd704a)

### Ожидаемое поведение

Снятие флага "Произвольный запрос" в свойствах динамического списка в среде разработки
1. Запрашивает подтверждение пользователя
2. Сразу удаляет текст запроса из XML исходника
 
Так же изначально делает конфигуратор.

![изображение](https://github.com/user-attachments/assets/3295fc08-8b8e-4656-9ccb-2ce17cd2d96b)

### Лог рабочей области

я

### Версия 1С:EDT

2023.3.5

### Операционная система

Windows

### Версия платформы 1С:Предприятие 8

8.3.24

### Установленные плагины

Нет плагинов

**Comment by vadimeg** [comment]
В 2024.1 исправлена проблема с неудаляемым запросом. Что касается подтверждения пользователя, то пожелание записали, но если будет сделано, то не в рамках данной задачи. Реализация такого же поведения как в конфигураторе (с подтверждением) потребует переделки модели UI в EDT. Сейчас есть 3 возможности по отмене действия с отключением произвольного запроса:
1. Сделать отмену выключения флажка (Undo) - Ctrl+Z
2. При закрытии не сохранять редактор формы, который будет находиться в состоянии dirty.
3. Отменить изменения в файле формы в индексе git
