### ISSUE TITLE
Две вкладки форм в окне внешнего отчета(см comment)

### ISSUE THREAD

**Issue by vovan58** [1C-Company/1c-edt-issues#1487]
### Описание ошибки

Ошибка в том что... в окне объекта внешнего отчета отображается две вкладки **Формы**
![Снимок экрана 2024-05-14 193640](https://github.com/user-attachments/assets/d18be7ac-b8f9-48b2-8d09-2cdedc249c17)

### Как воспроизвести

1. Перейдите в переспективу 1С Проекты
2. Кликните по контекстное меню Новы - Проект внешнего отчета - задать имя
3.  Кликните на иконке получившегося внешнего отчета
4. Смотрите ошибку в окне объекта см Скриншот

### Скриншоты

![Снимок экрана 2024-05-14 193640](https://github.com/user-attachments/assets/a8e65383-bfaa-4ba9-ab71-abc6787b21b4)

### Ожидаемое поведение

Вкладка должна быть одна

### Лог рабочей области

[.log](https://github.com/user-attachments/files/16557720/default.log)
[trace.log](https://github.com/user-attachments/files/16557723/trace.log)

### Версия 1С:EDT

Ruby 2023.3.6

### Операционная система

Windows

### Версия платформы 1С:Предприятие 8

1С:Предприятие 8.3 (8.3.23.2236)

### Установленные плагины

Нет плагинов

**Comment by vovan58** [comment]
![ВнешнийОтчетФормы1 2024-08-09 101609](https://github.com/user-attachments/assets/c538b0cc-3fac-40dd-9b75-544f3c94243e)

Правильный скриншот!!!

**Comment by Erik773** [comment]
Здравствуйте @vovan58!
Критический приоритет убран в соответствии с критериями критичности https://github.com/1C-Company/1c-edt-issues/blob/main/TASK_CLASSIFICATION.md
Удалось воспроизвести описанное поведение по следующему сценарию:
1. Создать два проекта с внешними отчетами в навигаторе, с помощью команды контекстного меню Новый → Проект внешнего отчета;
2. Открыть свойства внешнего отчета, с помощью команды контекстного меню Открыть или сделав двойной клик по нему в панели "Навигатор";

**Comment by wolfandw** [comment]
Исправлено в 2024.1
