### ISSUE TITLE
Поиск в дереве элементов формы не ищет в элементах контекстного меню

### ISSUE THREAD

**Issue by maxx1818** [1C-Company/1c-edt-issues#149]
### Описание ошибки

При поиске в дереве формы, не анализируются элементы контекстного меню.

### Как воспроизвести

1. Открыть форму Обработки-УдалениеПомеченныхОбъектов-ОсновнаяФорма
2. Активировать дерево элементов формы
3. Активировать поиск в дереве элементов формы Ctrl+F3
4. Ввести в окне поиска "дерево"
5. Нажимать далее, пока не найдется элемент "ДеревоПомеченныхНаУдаление"
6. При следующем нажатии на кнопку "Далее" ожидается, что активируется элемент "ДеревоПомеченныхНаУдалениеСнятьВсеИзМеню", тк в нем есть вхождение текста "дерево", но активируется элемент "ДеревоПомеченныхНаУдалениеПометка". Скорее всего при поиске элементы контекстного меню игнорируются.

### Скриншоты

![image](https://user-images.githubusercontent.com/95372729/144283240-930646b9-e026-47a1-be39-43969d89d743.png)

### Ожидаемое поведение

Поиск в дереве элементов формы должен анализировать все элементы

### Лог рабочей области

[.log](https://github.com/1C-Company/1c-edt-issues/files/7636011/default.log)

### Версия 1С:EDT

Ruby 2021.2.7

### Операционная система

Windows

### Установленные плагины

1C:Language Tool

**Comment by vadimeg** [comment]
Исправлено в 2021.3
