### ISSUE TITLE
Не удалось установить среду разработки

### ISSUE THREAD

**Issue by veshus** [1C-Company/1c-edt-issues#1494]
### Описание ошибки

Невозможно установить среду разработки при выборе любой среды

### Как воспроизвести

1. Запустить 1С EDT Start
2. Новый проект
3. Прикладное решение 1С Предприятие
4. 1С EDT 2023.3.6
5. Название проекта test

### Скриншоты

![image](https://github.com/user-attachments/assets/1d9e1164-f2f8-46bd-8d1e-b8fcedfc05ba)

### Ожидаемое поведение

Установка проходит без ошибок

### Лог рабочей области

2024-08-21 11:20:00 [Oomph installation thread] ERROR c.e.g.d.c.l.a.utils.FileUtils - C:\Users\svv\AppData\Local\1C\1cedtstart\installations\1C_EDT 2023.3_ (1)\1cedt\configuration\org.eclipse.oomph.setup\setup.log: Процесс не может получить доступ к файлу, так как этот файл занят другим процессом.

java.nio.file.FileSystemException: C:\Users\svv\AppData\Local\1C\1cedtstart\installations\1C_EDT 2023.3_ (1)\1cedt\configuration\org.eclipse.oomph.setup\setup.log: Процесс не может получить доступ к файлу, так как этот файл занят другим процессом.

### Версия 1С:EDT

0.7.0.180

### Операционная система

Windows

### Версия платформы 1С:Предприятие 8

8.3.24.1586

**Comment by airaketa** [comment]
@veshus добрый день, есть ли возможность приложить логи?
- папку с логами стартера можно открыть в настройках стратера - оттуда нужен файл 1cedtstart.log
- и файл C:\Users\svv\AppData\Local\1C\1cedtstart\installations\1C_EDT 2023.3_(1)\1cedt\configuration\org.eclipse.oomph.setup\setup.log

**Comment by veshus** [comment]
Логи во вложении
[setup.log](https://github.com/user-attachments/files/16698095/setup.log)
[1cedtstart.log](https://github.com/user-attachments/files/16698100/1cedtstart.log)

**Comment by airaketa** [comment]
@veshus предположительно должно помочь удаление папки .p2 в домашней директории (C:\Users\<имя пользователя>)
важный минус решения, что это сломает все среды разработки, установленные ранее через стартер

в грядущей версии стартера рассчитываем пофиксить такого рода ошибки

**Comment by veshus** [comment]
Предполагаю, что это сломает все установленные среды eclipse, они используются без привязки к EDT 
Есть ли какое-то еще решение?

**Comment by airaketa** [comment]
@veshus
можно попробовать стартеру указать отдельную от eclipse папку, для этого надо в файле 1cedtstart.ini (должен лежать рядом с .exe в папке установки) в самом низу прописать строчку вида:
`-De1c.dt.cloud.oomph.cli.extraArgs=oomph.p2.pool=C:\Users\<имя пользователя>\.p2-starter\pool`
путь привел для примера, можно указать любой удобный (желательно последний сегмент \pool все же сохранить, чтобы он в папку пользователя ничего не писал)

**Comment by veshus** [comment]
Так тоже не работает
![image](https://github.com/user-attachments/assets/7a8f02ac-010e-4c05-a856-4a3e66cb5aa7)

**Comment by airaketa** [comment]
@veshus подумал - можно еще вот так попробовать в .ini указать (вместо предыдущего варианта):
`-De1c.dt.cloud.oomph.cli.extraArgs=user.home=C:\Users\svv\.p2-onec`
путь может быть любой, главное, чтобы отличался от домашней папки пользователя

от предыдущего варианта отличается тем, что по указанному пути создастся не только pool с плагинами, а вообще заново все содержимое папки .p2 (что по идее должно решить проблему без удаления .p2)

**Comment by veshus** [comment]
Да, в таком варианте установка прошла

```
-startup
plugins/org.eclipse.equinox.launcher_1.6.400.v20210924-0641.jar
--launcher.library
plugins/org.eclipse.equinox.launcher.win32.win32.x86_64_1.2.400.v20211117-0650
-clean
-nosplash
-eclipse.keyring
@user.home/.eclipse/com.e1c.g5.dt.cloud.start/secure_storage
-vmargs
-Dosgi.requiredJavaVersion=11
-Declipse.log.level=ALL
-Dlogback.configurationFile=platform:/plugin/com.e1c.g5.dt.cloud.launcher.application/logback.xml
-Dorg.osgi.framework.bundle.parent=ext
-XX:+UseStringDeduplication
-XX:+HeapDumpOnOutOfMemoryError
-XX:+ExitOnOutOfMemoryError
-Xms70M
-Xss512k
-XX:MaxMetaspaceSize=84M
-XX:CompressedClassSpaceSize=32m
-XX:MaxDirectMemorySize=16m
-XX:ReservedCodeCacheSize=32m
-XX:MinHeapFreeRatio=5
-XX:MaxHeapFreeRatio=5
-Declipse.p2.MD5Check=false
-Doomph.p2.disable.offline=true
-De1c.dt.cloud.launcher.auth.useOAuth=true
-De1c.dt.monitoring.host=https://pult.1c.ru/
-Dbinary.css=true
-Dosgi.configuration.area=@user.home/.eclipse
-Dprism.order=sw
-Djavafx.animation.pulse=30
-Xmx150M
-Djava.net.useSystemProxies=true
-Djdk.http.auth.tunneling.disabledSchemes=
-De1c.dt.cloud.oomph.cli.extraArgs=user.home=c:/Users/svv/.edt
```

Думаю, как временное обходное решение можно использовать, но в будущем надо что-то решить, потому что указывать явным видом путь в профиль - неправильно, на 1 пк могут работать несколько пользователей, в этом случае - все ломается.

**Comment by airaketa** [comment]
@veshus да, это и позиционировалось как временное решение.
в грядущей 2024.1 постарались вылечить такого рода ошибки.
