### ISSUE TITLE
Метод НайтиПредопределенное менеджера регламентных заданий не работает с метаданными

### ISSUE THREAD

**Issue by d-hurricane** [1C-Company/1c-edt-issues#1496]
### Описание ошибки

Метод менеджера регламентных заданий `НайтиПредопределенное` в платформе поддерживает параметр двух типов: строка и объект метаданных. Однако в EDT сообщает об ошибке в случае использования объекта метаданных.

### Как воспроизвести

1. Создать новую конфигурацию. Добавить `РегламентноеЗадание` и серверный `ОбщийМодуль`.
2. Добавить в общий модуль код:
```bsl
// @strict-types

#Область СлужебныеПроцедурыИФункции

Процедура ПолучитьЗадание()
	
	Задание1 = РегламентныеЗадания.НайтиПредопределенное(Метаданные.РегламентныеЗадания.МоеЗадание.Имя);
	Задание2 = РегламентныеЗадания.НайтиПредопределенное(Метаданные.РегламентныеЗадания.МоеЗадание);
	
КонецПроцедуры

#КонецОбласти
```
3. Убедиться, что в первой строке вызова метода НайтиПредопределенное с аргументом-строкой EDT предупреждений не выводит, а во второй строке метода с аргументом-метаданными - ошибочно выводит предупреждение.

### Скриншоты

![image](https://github.com/user-attachments/assets/21e0d249-affb-4331-a3fc-7bff3328a4c9)

### Ожидаемое поведение

Предупреждений быть не должно.

### Лог рабочей области

[tmp.log](https://github.com/user-attachments/files/16752416/tmp.log)

### Версия 1С:EDT

Ruby 2023.3.5

### Операционная система

Windows

### Версия платформы 1С:Предприятие 8

8.3.22.2501

**Comment by MaksimDzyuba** [comment]
Здравствуйте, будет решено в 2024.2
![image](https://github.com/user-attachments/assets/64508791-cc41-4c0b-b830-ead725690576)
