### ISSUE TITLE
Лишнее окно "Выражения встроенного языка"

### ISSUE THREAD

**Issue by Roffild** [1C-Company/1c-edt-issues#1498]
Ruby 2023.3.6

У меня уже открыто окно "Выражения" верхние.
Но Наблюдение открывает окно "Выражения встроенного языка" нижние.

![bug](https://github.com/user-attachments/assets/535d5cc8-445c-44a1-9515-a8af7def9e45)

**Comment by DmitryBelov-e1c** [comment]
Добрый день. В соответствии с пожеланиями пользователей вид "Выражения" был полностью переработан с целью поддержки клавиатуры, удобства кликов для редактирования - в результате чего появился вид "Выражения встроенного языка", в настоящий момент являющийся основным для перспективы "Отладка" в EDT. В данной версии он ещё не полнофункционален (например, нет добавления переменных в "Значения"), и некоторые меню по "Наблюдению" открывают старые "Выражения". Тем не менее, в данный момент идёт работа по исправлению данного поведения, и в дальнейшем "Значения встроенного языка" будут иметь реализацию всех необходимых функций для замены стандартных "Выражений".
Вид "Значения" же как стандартная панель, имплементированная внутри Eclipse, останется при этом доступной, и оба вида возможно будет разместить рядом как и сейчас - это запланированное поведение.

**Comment by Roffild** [comment]
Да исправьте уже эти окна! Открываются они из разных мест - замену кода нормально не провели.

А ещё "Выражения встроенного языка" не умеет копировать и т.д.

<img width="397" height="329" alt="Image" src="https://github.com/user-attachments/assets/d81f7bb8-d55f-4d4f-bb39-c68af7a135aa" />

ВЕРНИТЕ "Выражения"  ВЕЗДЕ!

**Comment by DmitryBelov-e1c** [comment]
> Да исправьте уже эти окна! Открываются они из разных мест - замену кода нормально не провели.
> ВЕРНИТЕ "Выражения" ВЕЗДЕ!

Добрый день. Понимаю причины раздражения, вызванные медленной интеграцией и развитием "Выражений встроенного языка". Тем не менее, работу продолжаем, и в 2026.1 будет обновление данного функционала. Планов о возврате панели "Выражения" нет, цель - в перспективе обеспечить удобство работы в обновлённых "Выражения встроенного языка".

**Comment by Roffild** [comment]
@DmitryBelov-e1c зачем вообще включать недоделанное окно по-умолчанию?
Копирую данные часто из "Выражения".
Разницу с "Выражения встроенного языка" не вижу.
