### ISSUE TITLE
Не открывается окно "Строки на разных языках" у заголовка элементов формы типа "Декорация-надпись"

### ISSUE THREAD

**Issue by maxx1818** [1C-Company/1c-edt-issues#150]
### Описание ошибки

Ошибка в том что не открывается окно "Строки на разных языках" у заголовка элементов формы типа "Декорация-надпись"

### Как воспроизвести

1. Активировать любой элемент форы типа "Декорация-надпись"
2. Нажать на значок лупы у заголовка

### Скриншоты

![image](https://user-images.githubusercontent.com/95372729/144286688-583be393-bc0b-4b09-b28e-e5582c0db390.png)

### Ожидаемое поведение

Должно открываться окно "Строки на разных языках"

### Лог рабочей области

[.log](https://github.com/1C-Company/1c-edt-issues/files/7636122/default.log)

### Версия 1С:EDT

Ruby 2021.2.7

### Операционная система

Windows

### Установленные плагины

1C:Language Tool

**Comment by vadimeg** [comment]
Судя по ошибкам в логе это проблема окружения - JDK, JavaFX, EDT. Можно попробовать снести java, EDT. Затем установить последнюю рекомендованную **Full** JDK - https://releases.1c.ru/version_files?nick=Liberica11FullJDK&ver=11.0.12%2b7
Потом установить EDT.

**Comment by maxx1818** [comment]
Да, после установки Full JDK и последней EDT такое поведение не наблюдается. Спасибо.
