### ISSUE TITLE
Для элемента Поле флажка таблицы формы не отображается свойство ЦветФона. В конфигураторе оно есть.

### ISSUE THREAD

**Issue by DmitryShvaika** [1C-Company/1c-edt-issues#1502]
### Описание ошибки

Для элемента Поле флажка таблицы формы не отображается свойство ЦветФона. В конфигураторе оно есть.

![image](https://github.com/user-attachments/assets/a1fd5f16-a869-4daa-99ac-de8f429a2ba0)

![image](https://github.com/user-attachments/assets/8abede37-d22c-408c-b15c-1e5cc74b07cf)

### Как воспроизвести

1. Создать реквизит табличной части с типом Булево
2. Добавить его на форму (выбрать вид элемента Поле флажка)
3. Открыть панель свойств этого элемента формы. Наблюдать ошибку.

### Ожидаемое поведение

Свойство ЦветФона для поля флажка должно отображаться.

### Лог рабочей области

не требуется

### Версия 1С:EDT

Ruby 2023.3.6

### Операционная система

Windows

### Версия платформы 1С:Предприятие 8

8.3.21.1644

**Comment by vadimeg** [comment]
Исправлено в 2024.2
