### ISSUE TITLE
При слиянии веток расширения добавляются реквизиты формы

### ISSUE THREAD

**Issue by Dionisious** [1C-Company/1c-edt-issues#1504]
### Описание ошибки

Ведется разработка расширения конфигурации.
Если в расширение добавить форму из конфигурации в ветку test, а затем ветку test слить в ветку master, то в ветке master в добавленной форме реквизиты становятся такими как будто их добавили в расширение. Это происходит из-за того что при слиянии в xml формы добавляются теги <attributes>. То есть слияние форм расширения добавляет строки в файл описания формы.

### Как воспроизвести

1. Добавить форму справочника в расширение.
![image](https://github.com/user-attachments/assets/56e497b3-5664-489c-a31a-d3ea3841ae3f)
2. Зафиксировать изменения в ветке расширения.
3. В ветке test в файле формы нет тегов <attributes>
![image](https://github.com/user-attachments/assets/260fdf9c-2547-4a2a-afeb-381667b6f63e)
4. Переключиться на ветку master
5. Слить изменения из ветки test. При слиянии поставить режим "Создать коммит слияния даже если возможна перемотка вперед"
6. В файле формы появился тег <attributes>
![image](https://github.com/user-attachments/assets/f2e98792-0cc7-4920-86a8-e861c67ffc8a)

### Ожидаемое поведение

При слиянии веток не должно добавляться то чего не было в исходной ветке.

### Лог рабочей области

Архив проекта с примером.
[TEST.zip](https://github.com/user-attachments/files/16908270/TEST.zip)

### Версия 1С:EDT

2023.3.6

### Операционная система

Windows

### Версия платформы 1С:Предприятие 8

8.3.24

**Comment by vadimeg** [comment]
Исправлено в 2024.2
