### ISSUE TITLE
Не переносятся изображения в формате svg при сравнении/объединении.

### ISSUE THREAD

**Issue by senja006** [1C-Company/1c-edt-issues#1506]
### Описание ошибки

После процедуры сравнения/объединения общие картинки, которые заменены в новой конфигурации на формат svg, не переносятся, то есть старые наборы изображений с форматом png, упакованные в zip, удаляются, а новые svg на их место не переносятся.

### Как воспроизвести

1.	В ветку main помещаем типовую конфигурацию СППР версии 2.0.3.9 – коммит «Типовая конфигурация 2.0.3.9».
2.	От этого коммита создаем ветку vendor, в которую помещаем типовую конфигурацию СППР версии 2.0.7.3 – коммит «Типовая конфигурация 2.0.7.3».
3.	Переключаемся на ветку main. Запускаем слияние с веткой vendor. Настройки сравнения/объединения на скрине 1.
4.	Видим отличия вот в этих Общих картинках – скрин 2. Возле них флаг был поставлен EDT автоматически. Значит, все хорошо. Запускаем объединение.
5.	После объединения видим, что указанные изображения перестали отображаться – скрин 3. Файловая система  до обновления – скрин 4, после – скрин 5.

### Скрин 1
![Скрин 1](https://github.com/user-attachments/assets/d7ccb5ed-a96c-43bc-9acd-9fb82cc2125d)

### Скрин 2
![Скрин 2](https://github.com/user-attachments/assets/44207715-3eab-455a-bd02-5e3623a7324f)

### Скрин 3
![Скрин 3](https://github.com/user-attachments/assets/bb0c6932-d22f-401c-b20e-b0719fd11beb)

### Скрин 4
![Скрин 4](https://github.com/user-attachments/assets/f430bad1-3f4b-4265-962a-b5236658937b)

### Скрин 5
![Скрин 5](https://github.com/user-attachments/assets/a5a456bb-3336-415a-a354-e12948005d59)

### Скрин 6
![Скрин 6](https://github.com/user-attachments/assets/5fb7d928-9c27-4125-98fa-870458b80c19)

### Ожидаемое поведение

Новые изображения должны были быть перенесены при сравнении/объединении из ветки источника – скрин 6 (скрин сделан из ветки источника).

### Лог рабочей области

[log.txt](https://github.com/user-attachments/files/16927103/log.txt)

### Версия 1С:EDT

Ruby 2023.3.6

### Операционная система

Windows

### Версия платформы 1С:Предприятие 8

8.3.24.1667

### Установленные плагины

Нет плагинов

**Comment by Valarrus** [comment]
fatal: LF would be replaced by CRLF in cfg/src/CommonPictures/ВертикальноеПоложениеВерх/Picture.svg
ЕДТ в файлах картинок некорректно проставляет концы строк. Поместить в Gitlab не смог из-за таких ошибок. Пока правлю вручную Notepad++

**Comment by Valarrus** [comment]
Та же ошибка на ЕРПУХ.

Индексировать 97346 файлов

fatal: LF would be replaced by CRLF in cfg/src/Catalogs/ВидыВложенийДляАктированияЕИС/Templates/ВидыВложенийЕИС_ru/Template.bin

Done

**Comment by Valarrus** [comment]
Скорее всего причина ошибки - в типовых конфигурациях в макетах есть данные в которых указан не правильный символ перевода строки. Завышенные ожидания - ЕДТ выгрузит с корректным символом перевода в соответствии с настройками GIT рекомендованными вендором.

**Comment by AlmazNasibullin** [comment]
Ошибка исправлена в версии 2024.1.0.
