### ISSUE TITLE
Внезапное закрытие ЕДТ при открытии контекстной подсказки метода

### ISSUE THREAD

**Issue by Kibibu** [1C-Company/1c-edt-issues#1512]
### Описание ошибки

Если навести курсор на любой вызванный метод в любом модуле происходит и дождаться вызова окна подсказки метода происходит внезаное закрытие ЕДТ. 
Внезапное закрытие исчезает (правда не всегда) после создания нового проекта с добавлением общего модуля с 2я процедурами и вызовом справки по одному из этих методов. Но возникает после переоткрытия ЕДТ   
Подсказка ctrl+Пробел работает.
При наведении на ошибки в модуле, описание открыается

### Как воспроизвести

Несколько раз удалось открыть справку следующим образом, но после перезапуска ЕДТ при вызове справки перезапускалась.

Создается новый проект в чистой рабочей области.
Добавляется серверный общий модуль "ОбщийМодуль".
Добавляется следующий код

```
Процедура ТестПроцедуры()
	А = 1+1;
КонецПроцедуры

Процедура имяПроцедуры()
	ТестПроцедуры();
КонецПроцедуры
```
Наводится курсор на вызов ТестПроцедуры(). Контекстная подсказка отображается.
Закрываем ЕДТ. Открываем заново. Открываем ОбщийМодуль. Так же наводим курсор на ТестПроцедуры(). ЕДТ закрывается.

### Ожидаемое поведение

Открытие окна подсказки метода, а не закрытие ЕДТ

### Лог рабочей области

[ЖурналEDT.log](https://github.com/user-attachments/files/17025216/EDT.log)
[hs_err_pid48611.log](https://github.com/user-attachments/files/17025218/hs_err_pid48611.log)

### Версия 1С:EDT

2024.1.0+706

### Операционная система

Linux

### Версия платформы 1С:Предприятие 8

8.3.24.1586

### Установленные плагины

Нет плагинов

### Дополнительная информация

Похожее поведение было на 2023.3.5.+10 но там это решалось созданием папки "/tmp/SWT-GDBusServer" и вроде как должно было исправится с переходом на новую версию Eclips [https://github.com/1C-Company/1c-edt-issues/issues/1435](url),
Операционная система ALT Starterkit 11 (Salvia)

**Comment by Erik773** [comment]
Здравствуйте @Kibibu .
Могли бы Вы, пожалуйста, попробовать установить эту версию [java](https://dl03.1c.ru/content/DevelopmentTools/2024_1_0/runningedt.html#i076__%D1%83%D1%81%D1%82%D0%B0%D0%BD%D0%BE%D0%B2%D0%BA%D0%B0-%D0%B4%D0%B6%D0%B0%D0%B2%D0%B0-17) и проверить останется ли проблема?

**Comment by Kibibu** [comment]
[hs_err_pid4824.log](https://github.com/user-attachments/files/17039494/hs_err_pid4824.log)
[ЖурналEDT.log](https://github.com/user-attachments/files/17039495/EDT.log)

Поставил Zulu. Проблему не решило.

**Comment by Kibibu** [comment]
Нашел похожую проблему в форуме ArchLinux
[https://bbs.archlinux.org/viewtopic.php?id=294345](url)
Судя по всему проблема в совместимости Eclipse 4.30 и пакета webkit2gtk 2.44
Может знаете, есть ли возможность подсунуть эклипсу используемому в ЕДТ старую библиотеку. Не хотелось бы делать даунгрейд пакетов по всей системе.

**Comment by Kibibu** [comment]
После обновления библиотеки libwebkit2gtk ЕДТ перестала внезапно закрываться.
