### ISSUE TITLE
Перестал работать рефакторинг переименование функции / процедуры если в вызывающей функции есть директива #Если. В версии 2023 работало.

### ISSUE THREAD

**Issue by DmitryShvaika** [1C-Company/1c-edt-issues#1520]
### Описание ошибки

Перестал работать рефакторинг переименование функции / процедуры если в вызывающей функции есть директива #Если. В версии 2023 работало.

Дополнительно если из рефакторинга выходить по Esc, то переименованные функции останутся, а диалог ссылок выводится не будет. По идее должна быть отмена переименования.

### Как воспроизвести

Повторить пример с видео.
![РефакторингПереименованиеФункции](https://github.com/user-attachments/assets/a1cb0080-d61d-46bc-a3b9-40f935612c16)

Пример кода с видео:

// @strict-types - директива для edt - проверка модуля в строгих типах

#Область ПрограммныйИнтерфейс

// Тест1.
Процедура Тест1() Экспорт
	
	#Если ВебКлиент Тогда
	#КонецЕсли
	
	Тест2();
	
КонецПроцедуры

// Тест7.
Процедура Тест7() Экспорт
	
	Тест3();
	
КонецПроцедуры

#КонецОбласти

#Область СлужебныеПроцедурыИФункции

Процедура Тест3()

	Ааа = "";
	Ааа = Ааа;
	
КонецПроцедуры

#КонецОбласти

### Ожидаемое поведение

Рефакторинг переименование должно работать

### Лог рабочей области

Прилагаю архив тестового проекта целиком
[test.zip](https://github.com/user-attachments/files/17054911/test.zip)

### Версия 1С:EDT

Ruby 2024.1.0

### Операционная система

Windows

### Версия платформы 1С:Предприятие 8

8.3.21.1644

**Comment by MaksimDzyuba** [comment]
Здравствуйте, не получилось воспроизвести на 2024.1, может еще какие-то нюансы были.
![bandicam 2024-09-24 19-24-01-191](https://github.com/user-attachments/assets/32511d91-e3b8-4318-99de-f02697c70ccc)

**Comment by DmitryShvaika** [comment]
Извиняюсь. Случайно закрыл / открыл задачу.
Вот повторил ошибку. Даже создал базу и проект заново пустыми. Все дело в последовательностях действий. Первый раз переименовывает нормально, но если попробовать переименовать обратно - ошибка воспроизводится.
![Рефакторинг переименование](https://github.com/user-attachments/assets/6ae242e6-2805-4156-acab-0e30f2e415c9)

**Comment by MaksimDzyuba** [comment]
Понял, спасибо за уточнение, верну критичный статус

**Comment by MaksimDzyuba** [comment]
Да, удалось исправить, войдет в фикс к 2024.1.
![bandicam-2024-09-25-13-48-54-107](https://github.com/user-attachments/assets/d2ed9fa3-a41b-47fa-b60f-d770352008eb)
