### ISSUE TITLE
Edt повис при применении настроек валидации

### ISSUE THREAD

**Issue by DmitryShvaika** [1C-Company/1c-edt-issues#1521]
### Описание ошибки

Edt повис при применении настроек валидации

дамп потоков:
[threaddump.zip](https://github.com/user-attachments/files/17058623/threaddump.zip)

![image](https://github.com/user-attachments/assets/59b2b25e-e4c6-4892-823e-49153882845a)
и так уже 20 мин

### Как воспроизвести

не воспроизводится - разовая ошибка

### Ожидаемое поведение

Зависаний не должно быть

### Лог рабочей области

[trace.log.zip](https://github.com/user-attachments/files/17058637/trace.log.zip)

### Версия 1С:EDT

Ruby 2024.1.0

### Операционная система

Windows

### Версия платформы 1С:Предприятие 8

8.3.21.1644

**Comment by vadimeg** [comment]
@DmitryShvaika Исправлено, будет доступно в 2024.1.1
