### ISSUE TITLE
[1CEDT] Ошибка отображения ролей в редакторе прав EDT 2024.1

### ISSUE THREAD

**Issue by EChudnovsky** [1C-Company/1c-edt-issues#1523]
```
В новом релизе EDT Ruby 2024.1.0 продолжает наблюдаться ошибочное поведение редактора прав для объектов.
(см. #1038 предыдущее обращение для версии Ruby 2023.1.0).
Если в предыдущей версии, можно было открыть файл Rights.rights произвольным редактором, изменить содержание (например добавить перенос) и запись.
Это приводило к перечитывания файла edt и отображением в редакторе форм.
В текущей редакции данные не отражаются, любые обходные действия результат не приносят.


Product name: 1C:Enterprise Development Tools
Product version: 1.31.0.706
Java home: C:\Program Files\Zulu\zulu-17
Java vm name: OpenJDK 64-Bit Server VM
Java vm info: mixed mode, sharing
Java version: 17.0.12
Java vendor: Azul Systems, Inc.
OS: win32
Total mem: 7 440
Free mem: 3 512
Cores: 16
***********************************
*	Файлы, приложенные к задаче, отправлены разработчикам. Ссылка в задаче не отображается./t*
***********************************
```
log1: [log.zip](https://github.com/user-attachments/files/17075726/log.zip)
log2: [log2.zip](https://github.com/user-attachments/files/17075967/log2.zip)

![изображение](https://github.com/user-attachments/assets/f60f69df-aebe-470c-bb3b-ba67a2d35133)

**Comment by EChudnovsky** [comment]
Релиз финальная сборка 2024.1.2 продолжается некорректное поведение с редактором ролей.

Сейчас при открытии формы редактирования выдает ошибку "Unhandled event loop exceptio".
[log.log](https://github.com/user-attachments/files/17658877/log.log)

![изображение](https://github.com/user-attachments/assets/ca918d16-2850-4a14-a32f-495e40aa6534)

**Comment by EChudnovsky** [comment]
@vadimeg Добрый день, Вадим.
Просьба обратить внимание на данное обращение.
Проблема редактора тянется с релиза 2023, но никак не решается.
Хотя является стоп фактором для корректного внесения изменений в конфигурацию.
Так же прошу для данной задачи установить метку ошибки, т.к. для задач созданных из edt, метка не устанавливается и  управления ими у автора задачи нет.

**Comment by vadimeg** [comment]
@EChudnovsky Добрый день, добавили в список на рассмотрение

**Comment by EChudnovsky** [comment]
Добрый день.
По текущей ошибке: 
входе анализа удалось выяснить, что ошибку при открытии формы редактора ролей "java.lang.NullPointerException: Cannot invoke "org.eclipse.swt.graphics.RGB.toString()" because "rgb" is null", начиная с версии 2024, вызывает плагин DevStyle.

После удаления плагина (ставился с первых версий edt 😢 ) ошибка уходит.

В некоторых случаях остается плавающее поведение релиза 2023  (см. #1038) - отображение не неактуального состояния роли в редакторе (открывается пустой список). Решение проблемы - очистка проектов или перезапись файла роли, который приведет к реимпорту роли и корректному отображению в редакторе.
