### ISSUE TITLE
Автогенерация документирующего комментария неверно определяет тип СсылкаНаОбъектИнформационнойБазы для функций, возвращающих ссылку на узел плана обмена

### ISSUE THREAD

**Issue by DmitryShvaika** [1C-Company/1c-edt-issues#1526]
### Описание ошибки

Автогенерация документирующего комментария неверно определяет тип СсылкаНаОбъектИнформационнойБазы для функций, возвращающих ссылку на узел плана обмена.

![image](https://github.com/user-attachments/assets/366f5916-27e6-42d7-919c-0eac93d24304)

### Как воспроизвести

1. Создать функцию, возвращающую ссылку на узел плана обмена, например:

```
Функция Тест() Экспорт
	
	Возврат ПредопределенноеЗначение("ПланОбмена.ПланОбмена1.ПустаяСсылка");
	
КонецФункции

```
2. По Ctrl+Alt+D сгенерировать документирующий комментарий к ней
3. Наблюдать ошибку

### Ожидаемое поведение

должен определяться тип ссылка на узел план обмена. А тип СсылкаНаОбъектИнформационнойБазы в платформе не определен.

### Лог рабочей области

Не требуется

### Версия 1С:EDT

Ruby 2024.1.0

### Операционная система

Windows

### Версия платформы 1С:Предприятие 8

8.3.21.1644

**Comment by MaksimDzyuba** [comment]
Да, ошибка, причем именно для плана обмена, для справочника все корректно будет, исправим обязательно, спасибо!

**Comment by MaksimDzyuba** [comment]
удалось исправить, попробуем включить в 2024.1
![Uploading bandicam-2024-09-25-13-48-54-107.gif…]()
