### ISSUE TITLE
Не обновляется база при использовании автономного сервера

### ISSUE THREAD

**Issue by denisewitch** [1C-Company/1c-edt-issues#1529]
### Описание ошибки

Если используется автономный сервер, то при попытке обновить конфигурацию базы, EDT выдает сообщение: Ошибка исключительной блокировки информационной базы. 
Если попытаться нажать "Завершить сеансы и повторить" или "Повторить" опять появляется тоже самое окно с ошибкой исключительной блокировки.
В итоге невозможно обновить конфигурацию базы.

### Как воспроизвести

1. Создать базу с конфигурацией, например БСП. Включить возможность изменений
2. Добавить новый воркспейс в EDT
3. Импортировать конфигурацию из информационной базы в новый проект. Указать использование автономного сервера и начать разработку после импорта
4. Добавить новый справочник
5. Нажать Обновить конфигурацию

### Скриншоты

![image](https://github.com/user-attachments/assets/1fb1a02d-273d-471d-8118-2facc8680113)

### Ожидаемое поведение

Не должно быть ошибок блокировки базы, т.к. кроме EDT с базой никто не работает.
Должно выполниться обновление конфигурации информационной базы

### Лог рабочей области

[logs.zip](https://github.com/user-attachments/files/17134416/logs.zip)

### Версия 1С:EDT

2024.1.0

### Операционная система

Windows

### Версия платформы 1С:Предприятие 8

8.3.25.1419, 8.3.24.1707, 8.3.24.1624

### Дополнительная информация

При работе с расширениями, также возникает эта ошибка

Если воспроизвести на пустой базе без конфигурации, то все работает.

**Comment by Erik773** [comment]
Здравствуйте @denisewitch.
Могли бы Вы, пожалуйста, предоставить папку Servers из рабочей области, на которой возникла ошибка?

**Comment by denisewitch** [comment]
> Здравствуйте @denisewitch. Могли бы Вы, пожалуйста, предоставить папку Servers из рабочей области, на которой возникла ошибка?

[Servers.zip](https://github.com/user-attachments/files/17145287/Servers.zip)

**Comment by Erik773** [comment]
Еще, пожалуйста, могли бы Вы, после возникновения ошибки переключиться на перспективу отладки, раскрыть там элементы в панели отладки и сделать скриншот, это нужно чтобы понять какие процессы запущены.

**Comment by denisewitch** [comment]
Только я сразу на перспективу отладки переключился, т.к. там модальное окно

![image](https://github.com/user-attachments/assets/6ade441a-c255-416c-b0cf-764ee6a54a46)

**Comment by Erik773** [comment]
Благодарю за оперативный ответ и предоставленную информацию, будем исследовать проблему.

**Comment by denisewitch** [comment]
Проблему удалось решить после перехода на LibericaJDK, до этого была установлена Azul Zulu
