### ISSUE TITLE
При установке галок "Автоматически добавлять аннотацию строгой типизации модуля" и "Автоматически создавать структуру модуля" в свойствах проекта запускает расширенную проверку проекта, хотя флажки влияют только на новые модули.

### ISSUE THREAD

**Issue by DmitryShvaika** [1C-Company/1c-edt-issues#1530]
### Описание ошибки

При установке флажков "Автоматически добавлять аннотацию строгой типизации модуля" и "Автоматически создавать структуру модуля" в свойствах проекта запускает расширенную проверку проекта, хотя флажки влияют только на новые модули.

![image](https://github.com/user-attachments/assets/094c040b-42a4-4f77-a89a-497d21a49ac0)

### Как воспроизвести

1. Установить указанные флажки проекта.
2. Наблюдать запуск расширенной проверки

### Ожидаемое поведение

Расширенная проверка при установке флажков "Автоматически добавлять аннотацию строгой типизации модуля" и "Автоматически создавать структуру модуля" не должна запускаться. Они влияют только на новые модули.

### Лог рабочей области

не требуется

### Версия 1С:EDT

Ruby 2024.1.0

### Операционная система

Windows

### Версия платформы 1С:Предприятие 8

8.3.21

**Comment by tretyakevich** [comment]
Не повторяется в 2024.2 (как для дефолтной настройки всего WS, так и для конкретного проекта, в любой комбинации включения/выключения). В случае повторного появления - просьба предоставить логи сразу после возникновения проблемы.
