### ISSUE TITLE
Скрытие ошибок из базовой ветки не работает для репозитория внутри папки проекта

### ISSUE THREAD

**Issue by alxint** [1C-Company/1c-edt-issues#1535]
### Описание ошибки

Если репозиторий расположен внутри папки проекта, вот таким образом

![image](https://github.com/user-attachments/assets/7d32e596-c3ec-40b1-8a6f-fcd0c16c7d46)

то скрытие ошибок из базовой ветки так же скрывает ошибки в текущей ветке

### Как воспроизвести

Создать проект, выбрать Групповая разработка, Общий проект, установить флажок Создать в родительском каталоге, создать репозиторий (можно в эклипсе, можно нативно git)

![image](https://github.com/user-attachments/assets/0a1ce1af-2ec6-4dfc-9037-78a1847a8734)

Создать ветку мастер и dev по инструкции, настроить скрытие ошибок из мастер, скрыть ошибки, будут скрыты в том числе ошибки из текущей ветки

### Ожидаемое поведение

Скрытие работает вне зависимости от организации репозитория

### Лог рабочей области

[.log](https://github.com/user-attachments/files/17187522/default.log)

### Версия 1С:EDT

Ruby 2024.1.0

### Операционная система

Linux

### Версия платформы 1С:Предприятие 8

8.3.25.1394

### Установленные плагины

1C:Language Tool

### Дополнительная информация

Используемый для тестов проект

[hide_error.tar.gz](https://github.com/user-attachments/files/17187581/hide_error.tar.gz)

**Comment by vadimeg** [comment]
Исправлено в 2024.1.2 и 2024.2
