### ISSUE TITLE
Пишет что Метод устарел, хотя это не так.

### ISSUE THREAD

**Issue by Jimmo910** [1C-Company/1c-edt-issues#1537]
### Описание ошибки

Ошибка в том что метод `ОбработкаОшибок.ПодробноеПредставлениеОшибки` подчеркивается как Устаревший.

### Как воспроизвести

```
&НаКлиенте
Процедура СообщитьSOS(Команда)
	Попытка
	 в = 1;
	Исключение
		Информация= ИнформацияОбОшибке();
		ОбработкаОшибок.ПодробноеПредставлениеОшибки(Информация);
	КонецПопытки;
КонецПроцедуры
```

### Скриншоты

![image](https://github.com/user-attachments/assets/5f180248-c9c3-4de5-8622-b4466557d2d6)

### Ожидаемое поведение

метод не устарел, а как раз токи новый. замечания быть недолжно

### Лог рабочей области

не требуется

### Версия 1С:EDT

2024.1.0

### Операционная система

Windows

### Версия платформы 1С:Предприятие 8

8.3.25

**Comment by KrivickyA** [comment]
Кстати было бы неплохо, если бы при этой ошибке была возможность перейти к соответствующей странице справки, где описано, чем же теперь нужно пользоваться вместо устаревшего метода.

**Comment by Jimmo910** [comment]
Обнаружил что еще на вот этот метод ругается `НайтиНедопустимыеСимволыXML`

**Comment by Jimmo910** [comment]
Обнаружил что проблема только НаКлиенте.
Хотя согласно СП, на клиенте не должно работать.
Но оно работает....

![image](https://github.com/user-attachments/assets/dd8e4e53-d2a6-40ce-b8aa-360a09d6fd3b)

**Comment by DmitryShvaika** [comment]
По стандартам вроде запрещено методы называть так же как платформенные функции.

**Comment by NikitaMikhaylovSB** [comment]
> По стандартам вроде запрещено методы называть так же как платформенные функции.
Так это новый порядок от платформы, а вот НайтиНедопустимыеСимволыXML - теперь через МенеджерОбработкиСтрокиXML

**Comment by MaksimDzyuba** [comment]
Здравствуйте, ошибку исправил, войдет в 2024.2. 
![image](https://github.com/user-attachments/assets/02b4190e-1705-463a-a717-4378f4318a17)

**Comment by MaksimDzyuba** [comment]
> НайтиНедопустимыеСимволыXML

Здравствуйте, вроде как с 8.3.20 к этому методу надоб обращаться через свойство глобального контекста "ОбработкаСтрокиXML"

**Comment by Jimmo910** [comment]
а с КопироватьФайл() - что не так? не нашёл что бы он был устаревшим.
![image](https://github.com/user-attachments/assets/d615883f-ecdc-4f5c-8686-9b9a4d5fc543)

**Comment by MaksimDzyuba** [comment]
Здравствуйте, дело в том, что до версии 8.3.18 КопироватьФайл переводилось как FileCopy, а вот с 8.3.18 продолжило жить 2 англоязычных названия CopyFile и FileCopy. Но Вы правы, что на русское название ругани быть не должно, поправлю, спасибо
