### ISSUE TITLE
Ошибка java.net.MalformedURLException: Illegal character found in host: '/' в журнале ошибок

### ISSUE THREAD

**Issue by karneichik** [1C-Company/1c-edt-issues#1538]
### Описание ошибки

В организации используется IIS веб сервер, который имеет 2 привязки: по порту 80 для любых запросов (локальных) и для порта 443 для своего домена (внешних).
При этом в EDT в журнале ошибок многократно появляется сообщение с ошибкой "java.net.MalformedURLException: Illegal character found in host: '/'". 
Не возможно запустить отладку если в отладке выбрано приложение "Тонкий клиент" ( при выборе "Выбрать автоматически" запускается отладка в толстом клиенте )
на команду "C:\Windows\system32\inetsrv\AppCmd.exe list site "Default Web Site" /text:bin" получается след. результат : "https/*:443:<домен>,http/*:80:"

### Как воспроизвести

IIS веб сервер с 2-мя привязками.

### Ожидаемое поведение

Запуск тонкого клиента для отладки без ошибок

### Лог рабочей области

[trace.log](https://github.com/user-attachments/files/17203993/trace.log)
[log.log](https://github.com/user-attachments/files/17203996/log.log)

### Версия 1С:EDT

Ruby 2024.1.0

### Операционная система

Windows

### Версия платформы 1С:Предприятие 8

8.3.24.1691

### Установленные плагины

1C:Code style V8, 1C:SSL-support, 1C:Language Tool

**Comment by DmitryBelov-e1c** [comment]
Исправлено; войдёт в 2024.2
