### ISSUE TITLE
ЕДТ не видит Ошибку в вызове Процедуры как функции.

### ISSUE THREAD

**Issue by Jimmo910** [1C-Company/1c-edt-issues#1540]
### Описание ошибки

Если из одного Общего модуля, вызывать Процедуру другова общего модуля, при этом обращаться к не существующесу возвращаемому свойству. То EDT не выдает ошибку, о том что "Вы обращается к процедуре как к функции" - это вызывает Ошибку в Рантайме...

### Как воспроизвести

1. Создайте два Клиенских модуля.
2. Пусть и там и там будет по одной экспортной процедуре.
3. Одна вызывает другу, и пытается поместить результат в переменную.

### Скриншоты

![image](https://github.com/user-attachments/assets/b7b95a78-36a1-442a-a52f-22ecb5475a42)

### Ожидаемое поведение

Должно отображаться ошибка. На мой взгляд Блокирующая. но хоть какая нибудь

### Лог рабочей области

не думаю что надо.

### Версия 1С:EDT

2024.1.0

### Операционная система

Windows

### Версия платформы 1С:Предприятие 8

8.3.251394

### Дополнительная информация

Понимаю что как бы проблема не критичная - но на самом деле критичная... у нас клиенты словили проблемы...

**Comment by MaksimDzyuba** [comment]
Здравствуйте, да, ошибка, исправим в 2024.1, но возможно не успеем в первую исправительную. Ошибку я исправил - 
![image](https://github.com/user-attachments/assets/c66ba19a-c12e-4384-9c2e-85b191c129d9)
