### ISSUE TITLE
Запускается лишнее обновление области проекта

### ISSUE THREAD

**Issue by DmitryShvaika** [1C-Company/1c-edt-issues#1544]
### Описание ошибки

Запускается лишнее обновление области проекта

### Как воспроизвести

1. Нажимаю свойства проекта
2. На вкладке Валидация Импортирую профиль, но не применяю его
3. Нажимаю Отменить
4. И наблюдаю как запускается обновление области проекта. Зачем?

### Ожидаемое поведение

Обновление области проекта в данном случае запускать не должно. В свойствах проекта ничего не поменялось.

### Лог рабочей области

Не требуется

### Версия 1С:EDT

Ruby 2024.1.0

### Операционная система

Windows

### Версия платформы 1С:Предприятие 8

8.3.21.1644

### Дополнительная информация

Edt еще и повис на этом
Вот дамп потоков:
[threaddump.zip](https://github.com/user-attachments/files/17254394/threaddump.zip)

**Comment by tretyakevich** [comment]
Зависание устранено в 2024.1.1
Что касается остального:
1. Процедура импорта копирует файл профиля в WS
2. Соответственно запускается процесс обновления WS, без прочих процессов (в т.ч. причин устраненного зависания) - это обычное быстрое обновление
3. Операция по сути своей не является изменением текущих настроек проверок - поэтому она неотменяемая (файл импортруемого профиля не будет удален cancel-ом).
