### ISSUE TITLE
При Импорте / экспорте Расширения в конфигурацию, пропадают расширенные события

### ISSUE THREAD

**Issue by Jimmo910** [1C-Company/1c-edt-issues#1545]
### Описание ошибки

Ошибка в том что, При расширении формы, если расширить какое то либо событие," например событие Выбора на списке", то привязка события не сохраняется при Импорте из конфигурации в EDT или при Экспорте из EDT.

### Как воспроизвести

1. Создать пустую конфигурацию 1С.
2. Добавить там справочник, с формой списка.
3. Добавить расширение.
4. Расширить Форму списка добавленного справочника.
5. В Расширении на форме списка Расширить Событие таблицы, Например Событие "Выбор". 
6. Применить изменения в базе. Закрыть конфигуратор
7. Создать проект EDT
8. Импортировать Конфигурацию и Расширение в проект EDT.
9. Открыть в расширении Форму списка и не обнаружить Расширенное событие.

### Скриншоты

![image](https://github.com/user-attachments/assets/76c65508-2e1f-4605-b463-a0afec9b53a7)

### Ожидаемое поведение

Подписки на события не должны слетать, как при Импорте из конфигурации так и при Экспорте в конфигурацию.

### Лог рабочей области

[metadata.zip](https://github.com/user-attachments/files/17257744/metadata.zip)

### Версия 1С:EDT

2024.1.0

### Операционная система

Windows

### Версия платформы 1С:Предприятие 8

8.3.25.1394

**Comment by vadimeg** [comment]
Дубликат https://github.com/1C-Company/1c-edt-issues/issues/1517
