### ISSUE TITLE
Не открывается окно "Export Configuration to File"

### ISSUE THREAD

**Issue by denisewitch** [1C-Company/1c-edt-issues#1546]
### Описание ошибки

При попытке выгрузить cf или cfe через операцию "Export Configuration to File" - EDT сначало висит около минуты, а потом просто ничего не приосходит.
Пробовал вызывать команду, как через панель"Application" так и через "Infobase". 
Также одинаковый результат при использовании приложения через автономный сервер и просто через информационную базу.

### Как воспроизвести

1. Перейдите в панель "Application"
2. Кликните пкм по приложению
3. Выбираете пункт меню "Export Configuration to File"

### Скриншоты

![Снимок экрана 2024-10-04 163445](https://github.com/user-attachments/assets/7eff06dc-9ab5-4adc-9bd8-9fcb4fee0dfd)

### Ожидаемое поведение

Должно открыться окно с параметрами экспорта

### Лог рабочей области

[logs.zip](https://github.com/user-attachments/files/17258810/logs.zip)

### Версия 1С:EDT

2024.1.0

### Операционная система

Windows

### Версия платформы 1С:Предприятие 8

8.3.24.1707, 8.3.25.1419

**Comment by denisewitch** [comment]
На версии 2024.1.1 все работает

**Comment by nikolay-martynov** [comment]
@denisewitch Здравствуйте, Денис. Да, к сожалению в тестовую сборку 2024.1.0 закралась досадная ошибка. Она была исправлена в версии [2024.1.1](https://releases.1c.ru/version_files?nick=DevelopmentTools10&ver=2024.1.1). Благодарю за помощь в улучшении продукта.
