### ISSUE TITLE
Не открываются предопределенные данные плана счетов

### ISSUE THREAD

**Issue by AKazakov1C** [1C-Company/1c-edt-issues#1550]
### Описание ошибки

При попытке открыть предопределенные данные плана счетов - приложение визуально зависает. Работать становится невозможно.
При этом, в диспетчере задач видится активность по процессу.

![image](https://github.com/user-attachments/assets/2463c830-7c59-4119-87c3-24dd6861eda5)
![image](https://github.com/user-attachments/assets/6150d029-3ba4-4e44-ba1f-181dc2553bbd)

### Как воспроизвести

1. Разверните проект типовой конфигурации Бухгалтерия предприятия КОРП, редакция 3.0 (3.0.160.22)
2. Откройте план счетов Хозрасчетный
3. Кликните по вкладке "Предопределенные данные"

### Ожидаемое поведение

Данные должны отображаться

### Лог рабочей области

[.log](https://github.com/user-attachments/files/17327354/default.log)
[trace.log](https://github.com/user-attachments/files/17327357/trace.log)

### Версия 1С:EDT

2024.1.1

### Операционная система

Windows

### Версия платформы 1С:Предприятие 8

8.3.25.1394

### Установленные плагины

1C:Code style V8, 1C:SSL-support, Другие сторонние плагины `Название плагина...`

**Comment by goodwinvu** [comment]
У меня тоже воспроизводится ЕДТ 2024.1.1

**Comment by VAGoncharov** [comment]
У нас на самописке аналогично. Не проблема конкретной конфы.

**Comment by AKazakov1C** [comment]
![image](https://github.com/user-attachments/assets/4f324866-bc1b-44b2-89b7-563a0da5cc9f)
открылось, но ... через час

[.log](https://github.com/user-attachments/files/17328345/default.log)

**Comment by tretyakevich** [comment]
Исправлено, будет доступно в 2024.1.2
