### ISSUE TITLE
Обновление формы в расширении ломает сборку проекта и возможность обновить приложение

### ISSUE THREAD

**Issue by solventru** [1C-Company/1c-edt-issues#1558]
### Описание ошибки

EDT версий 2023.3.6, 2024.1.0 и 2024.1.1 на платформах 24 и 25 при добавлении в расширение  формы в которой есть таблица значений отображенная как строка некорректно формирует XML  файлы выгрузки и соответственно конфигуратор не может загрузить такой проект и применить обновления.
Проверял на чистых установках платформы/edt без плагинов без всего.

Обнаружено на типовой Бухгалтерии 3.0.161.22 на форме элемента справочника "Контрагенты"
Обновленная через EDT форма даже если в ней ничего не менять не загружается в 1С - проект не обновляется.

![image](https://github.com/user-attachments/assets/1c6503bf-9a74-4a63-94a2-5d0487669e9b)

При этом, расширение сделанное через конфигуратор работает без проблем.

Если сравнить файлы XML выгруженные в расширении сделанном через конфигуратор и в расширении сделанном или обновленном через EDT  показывают разницу вот в этих строках:

![image](https://github.com/user-attachments/assets/72db7bac-3c39-4803-aaef-2a575063915a)

EDT добавляет строки:

   <multipleValueDataPath xsi:type="form:DataPath">
            <segments>ОтборМетки.Свойство</segments>
          </multipleValueDataPath>
          <multipleValuePresentDataPath xsi:type="form:DataPath">
            <segments>ОтборМетки.Наименование</segments>
          </multipleValuePresentDataPath>

и удаление оных через xml редактор или visual studio позволяет собрать проект и обновить конфигурацию.

### Как воспроизвести

1. Берем типовую БП3, релиза 161.22 например.
2. Загружаем ее в ЕДТ как новый проект.
3. Создаем расширение, например в конфигураторе, в расширение захватываем форму элемента справочника "Контрагенты".
4. сохраняем в конфигураторе открываем базу все ок.
5. Импортируем расширение в EDT
6. При открытии формы EDT просит обновить форму, обновляем.
7. При попытке после этого обновить базу из EDT - получаем ошибку

### Скриншоты

![image](https://github.com/user-attachments/assets/c656febf-feed-4bbe-9c40-5e9baff6e573)
![image](https://github.com/user-attachments/assets/65bc0c7e-1587-4d97-b4a5-f87230701e18)

### Ожидаемое поведение

Создали расширение в EDT и оно не ломает обновление конфигурации.
Если расширение создано в конфигураторе то обновление формы в EDT не добавляет паразитные стркои.

### Лог рабочей области

[metadata.zip](https://github.com/user-attachments/files/17376945/metadata.zip)

### Версия 1С:EDT

Ruby 2024.1.1

### Операционная система

Windows

### Версия платформы 1С:Предприятие 8

8.3.24.1732

### Установленные плагины

Нет плагинов

**Comment by solventru** [comment]
Решение проблемы.
Работает для Бухгалтерии 3.0
Если в заимствованной форме явно добавить в расширение реквизиты на которые ругается система то ошибка уходит.
![image](https://github.com/user-attachments/assets/f652713f-9f31-43dc-8a49-bba712cd88cd)
![image](https://github.com/user-attachments/assets/acfe162a-f3e6-4ff8-a459-878b65e5abbb)

**Comment by vadimeg** [comment]
Исправлено в 2024.1.2
