### ISSUE TITLE
Не сохраняется форматированная строка в макете

### ISSUE THREAD

**Issue by f-leet** [1C-Company/1c-edt-issues#1563]
### Описание ошибки

Если редактировать текст ячейки табличного документа в виде форматированной строки, то изменения не сохраняются.

Если смотреть через текстовый редактор, то изменений форматной строки тоже нет. Приходится из другого макета копировать через текстовый редактор, чтобы что-то заработало.

### Как воспроизвести

1. Нажмите правой кнопкой на ячейку, выберите `Свойства`
2. В поле текст нажмите кнопку `Открыть`
3. Выберите вид `Форматированная строка`
4. Введите текст
5. Сделайте часть текста подчеркнутым
6. Смотрите под предприятием или откройте макет в текстовом редакторе, изменений нет.

### Ожидаемое поведение

Корректное сохранение форматированной строки.

### Лог рабочей области

Логи содержат личную информацию, поэтому не прикладываю.

### Версия 1С:EDT

Ruby 2023.3.5

### Операционная система

Windows

### Версия платформы 1С:Предприятие 8

8.3.24.1586

**Comment by wolfandw** [comment]
В макете СКД форматированная строка не поддерживается платформой, несмотря на то, что можно указать форматированную строку в редакторе теста ячейки макета СКД.
В обычном табличном документе в ЕДТ 2023.3 поддерживается частично (модельно), т.е. задать можно, но отображение будет в виде строки с тегами. На сборке 2023.3.5 и 6 воспроизвести указанную проблему не удалось.
В ЕДТ 2024.1 уже поддерживается и отображение.
