### ISSUE TITLE
Не удается добавить в настройки автономного сервера секцию debug

### ISSUE THREAD

**Issue by maxxxx1980** [1C-Company/1c-edt-issues#1571]
### Описание ошибки

Добавляю в файл конфигурации автономного сервера секцию про отладку
debug:
  port:8418
  
После сохранения настроек из EDT она удаляется

### Как воспроизвести

1. Создать приложение на автономном сервере
2. Открыть настройки
3. Добавить секцию Debug
4. Сохранить настройки
5. Закрыть окно настроек и открыть снова
6. Секции Debug в файле настроек нет

### Ожидаемое поведение

Не удалять секцию Debug, чтобы я мог настроить порт и адрес отладки

### Лог рабочей области

[.log](https://github.com/user-attachments/files/17606332/default.log)
[trace.log](https://github.com/user-attachments/files/17606334/trace.log)

### Версия 1С:EDT

Ruby 2023.3.6

### Операционная система

Windows

### Версия платформы 1С:Предприятие 8

8.3.24.1586

### Установленные плагины

Нет плагинов

**Comment by MaksimDzyuba** [comment]
Здравствуйте, а можно не много подробностей, зачем Вам понадобилась такая потребность, ведь с версии 2024.1 автономный сервер всегда запускается в режиме отладки.

**Comment by maxxxx1980** [comment]
Мы хотим на одном сервере терминалов использовать несколько экземпляров ЕДТ разными разработчиками
В этом случае возникает проблема, что порт отладчика уже используется

**Comment by MaksimDzyuba** [comment]
Здравствуйте, после вот этого сообщения Николая, понятно как действовать - https://github.com/1C-Company/1c-edt-issues/issues/1572#issuecomment-2459025560?

**Comment by nikolay-martynov** [comment]
@maxxxx1980 Здравствуйте. Секция debug пропадает из-за того, что в 2023.3.6 она не поддерживается. Сервер отладки встроенный в автономный сервер и соответствующие настройки поддерживаются начиная с версии 2024.1.

**Comment by MaksimDzyuba** [comment]
Считаю, что Николай все прояснил, если будут проблемы на 2024.1 предлагаю просто переоткрыть данную проблему
