### ISSUE TITLE
Проблема запуска файловой базы на автономном сервере для нескольких разработчиков

### ISSUE THREAD

**Issue by maxxxx1980** [1C-Company/1c-edt-issues#1572]
### Описание ошибки

Есть терминальный сервер для разработки
Для каждого разработчика выделена рабочая область EDT
Настройками автономного сервера порты разведены (в приложении три файла конфигурации).
Первые два приложения на автономном сервере запускаются нормально.
При запуске базы из третьего приложения выдается ошибка:
Ошибка взаимодействия с платформой 1С:Предприятия 8.3.24.1586:
Соединение с агентом конфигуратора 1С:Предприятия не было установлено. Журнал процесса:
Error establishing SSH session with Designer agent at localhost:1544
java.net.ConnectException: Connection refused: connect

### Как воспроизвести

1. Открыть три экземпляра EDT на одном сервере
2. Установить настройки портов для них
Первый:
server:
  address: "localhost"
  port: 8317
gates:
  ssh:
    admin:
      address: "localhost"
      port: 1547
debug:
  port:8417

Второй:
- server:
  address: "localhost"
  port: 8318
gates:
  ssh:
    admin:
      address: "localhost"
      port: 1548
debug:
  port:8418
  
Третий:
server:
  address: "localhost"
  port: 8319
gates:
  ssh:
    admin:
      address: "localhost"
      port: 1549
debug:
  port:8419

3. Запустить все три автономных сервера
4. Запустить все три приложения на файловые базы
5. При запуске третьего приложения выдается ошибка:
Ошибка взаимодействия с платформой 1С:Предприятия 8.3.24.1586:
Соединение с агентом конфигуратора 1С:Предприятия не было установлено. Журнал процесса:
Error establishing SSH session with Designer agent at localhost:1 544

При том, что в указанных экземплярах EDT этот порт для автономного сервера не используется

### Ожидаемое поведение

Независимая работа автономных серверов на одном сервере на разных портах

### Лог рабочей области

[.log](https://github.com/user-attachments/files/17606605/default.log)

### Версия 1С:EDT

Ruby 2023.3.6

### Операционная система

Windows

### Версия платформы 1С:Предприятие 8

8.3.24.1586

### Установленные плагины

Нет плагинов

**Comment by MaksimDzyuba** [comment]
Здравствуйте, а не могли бы Вы еще приложить, пожалуйста, файлы trace.log с той EDT, на которой не срабатывает подключение к информационной базе

**Comment by nikolay-martynov** [comment]
@maxxxx1980 Здравствуйте. Пожалуйста приложите файл журнала (.log) и трассировки (trace.log) для каждого из экземпляров EDT, а также файл настроек для каждого из экземпляров автономного сервера. Пожалуйста, запакуйте файлы в три разных каталога или переименуйте их с цифрами 1/2/3 в названии, чтобы можно было сопоставить файлы от одного экземпляра.

**Comment by maxxxx1980** [comment]
Добрый день. Ошибка проявилась на двух экземплярах
Прикрепляю архив с соответствующими папками
[Порт 1544 уже используется.zip](https://github.com/user-attachments/files/17627251/1544.zip)
Для Конф1 приложение запустилось
При запуске Конф3 потребовалось полное обновление конфигурации и была получена ошибка

**Comment by nikolay-martynov** [comment]
@maxxxx1980 Здравствуйте. По предоставленной вами информации можно сказать следующее:

- Конфигурационные файлы автономного сервера являются не совсем корректными. Например, нарушены правила, описанные в разделе 7.4.2 спецификации YAML: https://yaml.org/spec/1.2.2/#742-flow-mappings В частности "Normally, YAML insists the “:” mapping value indicator be [separated](https://yaml.org/spec/1.2.2/#separation-spaces) from the [value](https://yaml.org/spec/1.2.2/#nodes) by [white space](https://yaml.org/spec/1.2.2/#white-space-characters)."
- Правильно ли я понимаю, что вы настраиваете автономный сервер не из EDT, а в стороннем редакторе просто меняя YAML файл? Помимо YAML файла, используемого самим автономным сервером, ещё есть и настройки, хранящиеся внутри EDT. Если вы просто редактируете YAML файл, то во-первых, EDT может и не отследить, когда изменение было сделано, а во-вторых, внутренняя реплика настроек останется неизменной. Для настройки автономного сервера следует воспользоваться редактором, предоставляемым EDT. Для этого надо воспользоваться контекстным меню автономного сервера на панели приложений:
![image](https://github.com/user-attachments/assets/058b481f-1414-4293-b37f-8d456e3e4cde)
- Похоже, что вы пытаетесь настроить использование встроенного сервера отладки. Эта функция поддерживается в EDT начиная с версии 2024.1.
- В EDT 2024.2 улучшено создание экземпляров автономного сервера для минимизации конфликта портов. А если конфликт портов всё же случится, то система предложит произвести автоматическую перенастройку для разрешения проблемной ситуации.
- В версии 2023.3.6 иногда изменение настроек автономного сервера могло применяться не всегда. Эта ситуация была улучшена в 2024.1 и не проявляется в 2024.2.

**Comment by maxxxx1980** [comment]
Да, я полез в файл напрямую, так как ЕДТ не сохраняла секцию debug

Понятно, спасибо
Проверю на новой версии
Считаю инцидент исчерпанным
