### ISSUE TITLE
Не применяется настройка автономного сервера server:port

### ISSUE THREAD

**Issue by maxxxx1980** [1C-Company/1c-edt-issues#1573]
### Описание ошибки

У меня есть три рабочих области с минимальным проектом
В первой настройка применилась, в двух других - остался порт 8315
Во вложении архив с файлом настроек, скриншотом автономного сервера из ЕДТ, логом и трейсом по каждой рабочей области в отдельной папке
Ошибка выдавалась в Conf3

В итоге автономные серверы из областей Conf2 и Conf3 совместно не запускаются.
Ошибка - занят порт 8315

### Как воспроизвести

Создать рабочую область
В ней пустой проект
Поменять на диске файл в папке серверы\Автономный сервер...\config.yaml
После перезапуска порт из настроек автономного сервера остался по умолчанию

### Ожидаемое поведение

Порт автономного сервера должен применяться из настроек

### Лог рабочей области

[Порт 8315 уже используется.zip](https://github.com/user-attachments/files/17627085/8315.zip)

### Версия 1С:EDT

Ruby 2023.3.6

### Операционная система

Windows

### Версия платформы 1С:Предприятие 8

8.3.24.1586

### Установленные плагины

Нет плагинов

**Comment by maxxxx1980** [comment]
Хочу дополнить, что ошибка плавающая
Когда я тестировал на том же сервере и тех же рабочих областях в субботу (2.11) - у меня нормально применялся порт во всех трех экземплярах автономного сервера

**Comment by nikolay-martynov** [comment]
@maxxxx1980 Здравствуйте. На сколько я могу судить по приложенным файлам, ситуация повторяет #1572. Для работы со встроенным сервером отладки пожалуйста используйте версию не ниже 2024.1.

https://github.com/user-attachments/assets/2df5f053-b291-45ff-9d05-ba6d7970587c

В версии 2024.2 вероятность конфликта портов значительно снижена. Но если даже она возникнет, достаточно нажать одну кнопку и система автоматически подберёт новые порты.

**Comment by MaksimDzyuba** [comment]
Предлагаю закрыть проблему, так как повторение от https://github.com/1C-Company/1c-edt-issues/issues/1572, если считаете иначе, просьба переоткрыть
