### ISSUE TITLE
Ошибка конвертации проекта для информационной базы

### ISSUE THREAD

**Issue by febfora** [1C-Company/1c-edt-issues#1576]
### Описание ошибки

Конфигурация: 1C Производственная безопасность: Комплексная

Я создаю новую ветку, выбираю для нее информационную базу, то при обновлении этой базы всегда получаю ошибку:
com._1c.g5.v8.dt.platform.services.core.runtimes.execution.RuntimeCoreException: Ошибка взаимодействия с платформой 1С:Предприятия 8.3.24.1758:
Ошибка загрузки/выгрузки конфигурации
Ссылка на неизвестное поле или поля не существует - BusinessProcess.пбМероприятие.TabularSection.ДополнительныеРеквизиты.StandardAttribute.Ref
Ссылка на неизвестное поле или поля не существует - BusinessProcess.пбМероприятие.TabularSection.ДополнительныеРеквизиты.Attribute.Свойство
Ссылка на неизвестное поле или поля не существует - BusinessProcess.пбМероприятие.TabularSection.ДополнительныеРеквизиты.Attribute.Значение
Ссылка на неизвестное поле или поля не существует - Task.ЗадачаИсполнителя.TabularSection.ДополнительныеРеквизиты.StandardAttribute.Ref
Ссылка на неизвестное поле или поля не существует - Task.ЗадачаИсполнителя.TabularSection.ДополнительныеРеквизиты.Attribute.Свойство
Ссылка на неизвестное поле или поля не существует - Task.ЗадачаИсполнителя.TabularSection.ДополнительныеРеквизиты.Attribute.Значение

Эти табличные части не удалены.

При полном обновлении такой ошибки нет. 
Эта же ошибка воспроизводилась на версии EDT 2023.3.6 

Похожее описание ошибки - https://github.com/1C-Company/1c-edt-issues/issues/207

### Как воспроизвести

1. Создать проект Производственная безопасность: Комплексная
2. Создать новую ветку, указав иб
3. Произвести НЕ полное обновление

### Ожидаемое поведение

Не полное обновление происходит без ошибок

### Лог рабочей области

[log.txt](https://github.com/user-attachments/files/17672386/log.txt)
[trace.log](https://github.com/user-attachments/files/17672383/trace.log)

### Версия 1С:EDT

Ruby 2024.1.2

### Операционная система

Windows

### Версия платформы 1С:Предприятие 8

8.3.24.1758

**Comment by MaksimDzyuba** [comment]
Здравствуйте, а не могли бы указать версию конфигурации - Производственная безопасность: Комплексная, пожалуйста, чтобы четче проверить присланный сценарий

**Comment by febfora** [comment]
Версия 1.1.6.209. Такая же проблема, если переключить ветку и начать обновление иб

**Comment by tretyakevich** [comment]
Возникли следующие дополнительные вопросы:

- Как создается первичный проект (у вас в описании пункт 1) - импортом из существующей ИБ, импортом из исходников в формате платформы, импортом из исходников в формате EDT?
- Ассоциирована ли ИБ с первичным проектом?
- Как именно вы указываете ИБ при создании ветки (поскольку создание ветки с тестовой ИБ подразумевает полную загрузку в эту ИБ)

**Comment by febfora** [comment]
1. Проект создается импортом проекта из гита.
2. Не совсем понимаю вопрос, конфигурация проекта и конфигурация ИБ одинаковые. Эта ошибка воспроизводится даже если произвести полное обновление, переключить на другую ветку, вернуться, и попытаться произвести не полное обновление.
3. Тип создания я указываю "Создать новую ИБ и загрузить ее содержание из фала базы данных (1Cv8.1CD)", и указываю ИБ, например, текущий ветки, или какую нибудь из другой ветки. Если не указать что конфигурация иб совпадает с конфигурацией проекта в указанной ветке, то потом при не полном обновлении происходит ошибка

**Comment by tretyakevich** [comment]
Проблема связана с потерей внутренних данных EDT (поля, контексты и т.п.), используемых при публикации/импорте данных в/из ИБ

Проверили  на "Производственная безопасность: Комплексная", симуляционные сценарии включали изменения объектов метаданных, общих типов и т.п. В версии 2024.2 повторить проблему не удалось. Учитывая, что в ней был исправлен ряд проблем, связанных с потерей внутренних данных (в т.ч. связанных с табличными частями) - надеемся, что ваш конкретный сценарий тоже исправлен.

В случае возникновения подобной проблемы на 2024.2, переоткройте задачу. Для воспроизведения потребуются конкретные коммиты/ветки, переключение между которыми вызывает проблему.
