### ISSUE TITLE
Не работает синтакс контроль по количеству параметров локального метода

### ISSUE THREAD

**Issue by unichkin** [1C-Company/1c-edt-issues#1578]
### Описание ошибки

Не работает синтакс контроль по количеству параметров локального метода

### Как воспроизвести

В любом модуле написать примерно такой код:

Процедура Моя1()
    Моя2(); // вызван без параметров, но синтакс контроль не работает
КонецПроцедуры

Процедура Моя2(Раз, Два, Три)
КонецПроцедуры

### Скриншоты

![image](https://github.com/user-attachments/assets/8e00ad51-373e-4828-8629-730041332b75)

### Ожидаемое поведение

Должна быть ошибка синтакс контроля. Хотя-бы как в конфигураторе добавить кнопку ручного контроля.

### Лог рабочей области

-

### Версия 1С:EDT

Ruby 2024.1.2

### Операционная система

Windows

### Версия платформы 1С:Предприятие 8

8.3.22.2577x64

### Установленные плагины

Другие сторонние плагины `Название плагина...`

### Дополнительная информация

Стоит AnyEdit, EDTEditing. Наблюдал неоднократно и предыдущей версии EDT - думал глюк воруспейса, руки не доходили пересоздать. Но вчера поставил свежий релиз EDT, в новый воркспейс, и увидел то же самое.

**Comment by MaksimDzyuba** [comment]
Здравствуйте, что-то быстрая проба пера не показало проблему - 
![image](https://github.com/user-attachments/assets/f48232e6-9c02-4b21-8bc2-95250670047d)
Может есть еще какие-то детали важные, ну или просто попробуйте, в общем модулей, как у меня. Если у Вас там будет все ок, то можно тогда хотя бы просто Ваш модуль, который на скриншоте

**Comment by unichkin** [comment]
@MaksimDzyuba  вероятно дело в настройках проекта. Если создаю новый проект - там ошибки не наблюдается. Но в уже существующих она есть. Сделал так - скопировал и переименовал существующий проект внешних отчетов / обработок, удалил из него всего отчеты / обработки, и ввел новую обработку "Тест". Воспроизвелось:
![image](https://github.com/user-attachments/assets/311f2863-7fe8-4bee-b16d-9d64e22cd3a8)

Свойства из редактора проекта:
![image](https://github.com/user-attachments/assets/6ede8370-a93c-4db2-ba7c-47fa67e74124)

Передаю ее в архиве:
[Тест.zip](https://github.com/user-attachments/files/17690276/default.zip)

**Comment by MaksimDzyuba** [comment]
Здравствуйте, у Вас в списке проверок отключена вот эта валидация, что на скриншоте - 
![image](https://github.com/user-attachments/assets/abd09e38-4e9c-40a6-9bec-f801ad07601a), если Вы ее включите, то ошибки начнут показываться

**Comment by unichkin** [comment]
Доброе утро. Да, так заработало, спасибо.

**Comment by unichkin** [comment]
@MaksimDzyuba выяснил каким образом настройка была отключена.
Проект после очередного обновления стал ругаться на "ПодробноеПредставлениеОшибки(ИнформацияОбОшибке());":
![image](https://github.com/user-attachments/assets/1016c895-744e-484c-bfe8-86ee23c239b8)

Я это сокрыл. А оказывается оно еще и на проверку параметров метода работает? Как-то неоднозначно, мягко говоря...

**Comment by MaksimDzyuba** [comment]
да, такое влияние - это текущее ограничение, мы от него избавимся, про ошибку на скриншоте, я ее правил в 2024.2
