### ISSUE TITLE
При иморте конфигурации некорректно импортируются форматные строки в макетах

### ISSUE THREAD

**Issue by f-leet** [1C-Company/1c-edt-issues#1585]
### Описание ошибки

Если в ячейке используется форматная строка, будь то выделение жирным шрифтом или подчеркивание, эти изменения не импортируются при импорте из конфигурации.

### Как воспроизвести

1. Откройте базу под конфигуратором.
2. Измените любой макет, переключите ячейку в режим форматной строки, выделите часть цвета жирным.
3. Импортируйте изменения в EDT.
4. Ячейка не имеет установленного формата.

### Ожидаемое поведение

Корректный импорт

### Лог рабочей области

Не требуется

### Версия 1С:EDT

Ruby 2023.3.5

### Операционная система

Windows

### Версия платформы 1С:Предприятие 8

8.3.24.1586

**Comment by RedMammoth** [comment]
А какой режим совместимости?

**Comment by f-leet** [comment]
> А какой режим совместимости?

Версия 8.3.21

Про это я, пожалуй, не подумал.
