### ISSUE TITLE
Сломался диалог сравнения/объединения расширений конфигурации

### ISSUE THREAD

**Issue by Migele** [1C-Company/1c-edt-issues#1590]
### Описание ошибки

Сломался диалог сравнения/объединения расширений конфигурации, если во втором источнике нет объектов метаданных (например документов), которые есть в главном источнике.
В версии 2023.3.6 работал

### Как воспроизвести

Создать два пустых расширения
В первом создать документ
при сравнении первого со вторым - ошибка
При смене порядка расширения (второе с первым) ошибки нет

### Скриншоты

![изображение](https://github.com/user-attachments/assets/ff41b236-b013-4ef7-84c0-9b1261710a67)
![изображение](https://github.com/user-attachments/assets/2c3ff6ef-b3dd-4a84-be55-fba31112355d)
при смене порядка диалог открывается
![изображение](https://github.com/user-attachments/assets/2cf6efc5-e41a-4b4a-9b35-bdba2877a8bf)
![изображение](https://github.com/user-attachments/assets/c4677793-f64f-4cf4-9c54-d1d2e7762121)

### Ожидаемое поведение

Окно сравнения-объединения

### Лог рабочей области

[trace.log](https://github.com/user-attachments/files/17799827/trace.log)
[log.txt](https://github.com/user-attachments/files/17799838/log.txt)

### Версия 1С:EDT

Ruby 2024.1.2

### Операционная система

Windows

### Версия платформы 1С:Предприятие 8

8.3.24.1738

**Comment by vadimeg** [comment]
Дубликат https://github.com/1C-Company/1c-edt-issues/issues/1579
