### ISSUE TITLE
Language tool. Зависает команда "Convert to translation language"

### ISSUE THREAD

**Issue by tormozit** [1C-Company/1c-edt-issues#1591]
### Описание ошибки

Запускаю команду "Convert to translation language" плагина "Language tool". Она зависает каждый раз в разных местах. Процесс java.exe перестает нагружать процессор. Уже попробовал около 10 раз. Очистку проекта пробовал.

### Как воспроизвести

я

### Скриншоты

![изображение](https://github.com/user-attachments/assets/d197ead3-e117-445f-9b45-a0c954a70112)

### Ожидаемое поведение

я

### Лог рабочей области

пустой

### Версия 1С:EDT

2024.1.2

### Операционная система

Windows

### Версия платформы 1С:Предприятие 8

3.23

### Установленные плагины

1C:Language Tool

**Comment by Erik773** [comment]
Здравствуйте @tormozit.
Могли бы Вы, пожалуйста, снять дамп потоков EDT в момент зависания. Как делать описано тут в разделе "Если 1C:EDT зависла": https://its.1c.ru/db/edtdoc/content/153/hdoc
Также исследовании причин проблемы помогут логи  .log, .bak.log и trace.log рабочей области ЕДТ.

**Comment by tormozit** [comment]
Дамп потоков 
[threaddump.txt](https://github.com/user-attachments/files/17866677/threaddump.txt)

**Comment by tormozit** [comment]
[Новый текстовый документ.txt](https://github.com/user-attachments/files/17866833/default.txt)

**Comment by Erik773** [comment]
Подскажите, пожалуйста, выполняются ли еще какие-либо процессы в этот момент, в частности расширенная проверка?

**Comment by tormozit** [comment]
Нет

**Comment by tormozit** [comment]
Проверил на другом проекте с версией платформы 8.3.25 после оптимизации формата хранения. Такая же проблема. 
Есть новости?

**Comment by babinnikolay** [comment]
Есть возможность для проверки запустить операцию в консольном варианте? convert-languages --project-name --languages ["Английский"] --language-project "D:\tmp\LangProject"

**Comment by tormozit** [comment]
@babinnikolay не знаю как "запустить операцию в консольном варианте"

**Comment by babinnikolay** [comment]
https://its.1c.ru/db/edtdoc/content/10608/hdoc

**Comment by babinnikolay** [comment]
1cedtcli -data D:\projects\МойПроект -vmargs -Xmx8g -command convert-languages --project-name "MyProject" --languages ["Английский"] --language-project "D:\tmp\LangProject" 
Вот пример команды целиком

**Comment by tormozit** [comment]
Мне надо конвертировать в существующий проект. 

![изображение](https://github.com/user-attachments/assets/3be221d7-7b38-4407-9ae8-3d81c39c32de)

Поэтому я запускал такую команду 
1cedtcli -data c:\EDTTMS5 -vmargs -Xmx8g -command convert-languages --project-name "Перевод" --languages ["Английский"] --language-project "c:\EDTTMS5\Перевод"
Status ERROR: com.e1c.langtool.v8.dt.cli.api.impl code=0 Other project exists in workspace with the same name: TMS_GIT
