### ISSUE TITLE
Настройки валидации расширения не подхватываю изменения настроек из основного проекта

### ISSUE THREAD

**Issue by VAGoncharov** [1C-Company/1c-edt-issues#1592]
### Описание ошибки

Создаем проект EDT, импортируем из него конфигурацию с расширением. В настройках валидации проекта отключаем все проверки. В основной конфигурации результаты проверок пропадают, в расширении - остаются. Открываем свойства валидации расширения, видим, что там сохранились настройки основного проекта до их изменения, из профиля Default. Отключаем все проверки - результаты валидации пропадают. При этом, файл настроек валидации расширения не меняется, его видимо и нет, судя по гиту.

Если независимые настройки валидации для расширения были предусмотрены, то такое поведение - это недоработка, настройки должны сохраняться в отдельном файле.
Если независимые настройки валидации для расширения не были предусмотрены и не нужны по мнению разработчика, то их стоит убрать для проекта расширения, а настройки всегда тянуть из основного проекта.

### Как воспроизвести

-

### Ожидаемое поведение

-

### Лог рабочей области

-

### Версия 1С:EDT

2024.1.2

### Операционная система

Windows

### Версия платформы 1С:Предприятие 8

8.3.22.2557

### Установленные плагины

1C:Code style V8, 1C:SSL-support

**Comment by Erik773** [comment]
Здравствуйте @VAGoncharov 
К сожалению, не удалось воспроизвести описанную ошибку. Настройка проверок производится независимо от того, какого типа проект - обычный или расширение. Default.cset создается и на уровне проекта расширения. При отключении проверок в профиль попадают соответствующие изменения. 
Могли бы Вы, пожалуйста, предоставить логи (.log, .bak.log и trace.log)  рабочей области ЕДТ.
Если возможно, то приложите видео или скриншоты. 
Есть ли у Вас, возможность, предоставить проект конфигурации с расширением, на которых проблема воспроизводится?

**Comment by VAGoncharov** [comment]
> Здравствуйте @VAGoncharov К сожалению, не удалось воспроизвести описанную ошибку. Настройка проверок производится независимо от того, какого типа проект - обычный или расширение. Default.cset создается и на уровне проекта расширения. При отключении проверок в профиль попадают соответствующие изменения. Могли бы Вы, пожалуйста, предоставить логи (.log, .bak.log и trace.log) рабочей области ЕДТ. Если возможно, то приложите видео или скриншоты. Есть ли у Вас, возможность, предоставить проект конфигурации с расширением, на которых проблема воспроизводится?

Если независимая настройка предусмотрена разработчиками, тогда вопрос снят.
Настройки перепроверил, была проблема с гитовским окружением. Извиняюсь.

Тогда есть пожелание - по-умолчанию синхронизировать настройки валидации основного проекта и проекта расширения. Лично мне это кажется более логичным поведением.

**Comment by Erik773** [comment]
> Тогда есть пожелание - по-умолчанию синхронизировать настройки валидации основного проекта и проекта расширения. Лично мне это кажется более логичным поведением.

Могли бы Вы, пожалуйста, создать отдельную задачу с лейблом enhancement.
