### ISSUE TITLE
#Вставка посреди многострокового литерала ломает схему модуля

### ISSUE THREAD

**Issue by VAGoncharov** [1C-Company/1c-edt-issues#1593]
### Описание ошибки

Добавляем в расширение метод с директивой &ИзменениеИКонтроль. В методе есть текст запроса. Дорабатываем его в средине через #Вставка |... #КонецВставки. EDT выдает диагностики:
1. На директиву #Вставка: "Синтаксическая ошибка. Неверный ввод "'#Вставка'" - ожидается """	- org.eclipse.xtext.diagnostics.Diagnostic.Syntax. 
2. На строку запросу между #Вставка и #КонецВставки: "Синтаксическая ошибка. Неверный ввод "'|\tВЫБОР'" - ожидается "RULE_END_INSERT"" - org.eclipse.xtext.diagnostics.Diagnostic.Syntax

После этого схема модуля ломается, быстрая навигация по Ctrl+O невозможа.

### Как воспроизвести

-

### Скриншоты

![image](https://github.com/user-attachments/assets/2e61ba1a-c62a-42c0-bce6-0d4e7d77f3d7)
![image](https://github.com/user-attachments/assets/9b2dec24-2d1d-41a7-ac25-ed92be647c6a)

### Ожидаемое поведение

Такая констукция считается допустимой с т.з. конфигуратора и работает без ошибок. Привести в соответствие с поведением конфигуратора.

### Лог рабочей области

-

### Версия 1С:EDT

2024.1.2

### Операционная система

Windows

### Версия платформы 1С:Предприятие 8

8.3.22.2557

### Установленные плагины

1C:Code style V8, 1C:SSL-support

**Comment by VAGoncharov** [comment]
P.S. Аналогичная проблема внутри конструкции Если ... ИначеЕсли... КонецЕсли.

**Comment by adminimusRU** [comment]
Проблема старая, см. #695, #29, #897

**Comment by Roffild** [comment]
https://github.com/1C-Company/1c-edt-issues/issues/1475

**Comment by tretyakevich** [comment]
Проблема известна. Закрываем как дубль, новой информации не несет
