### ISSUE TITLE
Ошибка при импорте конфигурации

### ISSUE THREAD

**Issue by ElenaMikhey** [1C-Company/1c-edt-issues#160]
### Описание ошибки

Ошибка при импорте конфигурации КА для Беларуси 2.4.13.244 из информационной базы. Загружает файлы проекта, но не проходит сборка проекта. Скрин журнала ошибок и лог прилагаются. Такая же проблема при импорте типовой КА РФ 2.4.13.243.
![1](https://user-images.githubusercontent.com/95411636/144420425-f72b9a38-d5f1-48ca-ac97-b2b898a1228f.jpg)

### Как воспроизвести

Просто импорт из базы в новый проект. Проблема явно в нашей конфигурации, но как понять в чем конкретно проблема? Работа остановилась совсем.

### Скриншоты

![1](https://user-images.githubusercontent.com/95411636/144421867-13b00106-132e-4ff9-a1f1-113011c9017f.jpg)

### Ожидаемое поведение

Хотелось бы по описанию хоть немного понять в чем причина провала сборки. 

### Лог рабочей области

[.log](https://github.com/1C-Company/1c-edt-issues/files/7641769/default.log
[trace.log](https://github.com/1C-Company/1c-edt-issues/files/7641787/trace.log)
)

### Версия 1С:EDT

1C:Enterprise Development Tools Ruby 2021.2.10. 

### Операционная система

Windows

### Установленные плагины

Нет плагинов

**Comment by Keffirchik** [comment]
Добавлю, примерно в половине случаев не проходит конвертация проекта рингом (ring edt@2021.2.10:x86_64 workspace export --configuration-files {workspace}/conv_edt --workspace-location {workspace}/temp --project {workspace}/repo_clone/Project), ошибка в логе аналогичная (Failed to add commit end mark in WAL т.к. файл уже существует). Удачный и неудачный логи:
[error.log](https://github.com/1C-Company/1c-edt-issues/files/7650453/error.log)
[no error.log](https://github.com/1C-Company/1c-edt-issues/files/7650456/no.error.log)

**Comment by MaksimDzyuba** [comment]
Здравствуйте, в 2021.3 ошибку не удалось воспроизвести, все проходит корректно, проверял на 4ГБ
![image](https://user-images.githubusercontent.com/77277424/152849937-21b309ff-87fb-492e-bc60-d260cef4d2b9.png)
Если проблема больше не актуальна, то просьба закрыть обращение.
Извините за долгу реакцию, упустили проблему(

**Comment by vadimeg** [comment]
Закрываю, т.к. не воспроизводится. Если воспроизведется, то просьба переоткрыть
