### ISSUE TITLE
Ошибка при выгрузке проекта в ИБ. "Несоответствие свойства и элемента данных XDTO: Свойство: 'RowsPicture'"

### ISSUE THREAD

**Issue by VAGoncharov** [1C-Company/1c-edt-issues#1609]
### Описание ошибки

Конфигурация 1С:ERP Управление предприятием 2. БИТ.ФИНАНС 3.2, версия 2.5.8.254/3.2.34.7.

При выгрузке проекта в ИБ EDT выдает ошибку:
com._1c.g5.v8.dt.platform.services.core.runtimes.execution.RuntimeCoreException: Ошибка взаимодействия с платформой 1С:Предприятия 8.3.22.2557:
Ошибка загрузки/выгрузки конфигурации
по причине:
Исключение XDTO произошло при чтении файла- zip:///DataProcessors/ОтражениеДокументовВРеглУчете/Forms/ПроводкиРегламентированногоУчета/Ext/Form.xml.
по причине:
Несоответствие свойства и элемента данных XDTO:
Свойство: 'RowsPicture'

Ошибка указывает на элемент формы НаборЗаписей (таблица), путь к данным - реквизит формы НаборЗаписей типа РегистрБухгалтерииНаборЗаписей.Хозрасчетный. У элемента стоит свойство ПутьКДаннымКартинкиСтроки и КартинкаСтрок, картинка строк ссылает на картинку конфигурации АктивностьПоРБ.

До выгрузку этот объект метаданных и связанные с ним не менялись!

### Как воспроизвести

см. описание ошибки

### Ожидаемое поведение

-

### Лог рабочей области

[.log](https://github.com/user-attachments/files/17975051/default.log)

### Версия 1С:EDT

2024.1.2

### Операционная система

Windows

### Версия платформы 1С:Предприятие 8

8.3.22.2557

### Установленные плагины

1C:Code style V8, 1C:SSL-support

**Comment by Roffild** [comment]
https://github.com/1C-Company/1c-edt-issues/issues/1527#issuecomment-2368248601

**Comment by vadimeg** [comment]
Не воспроизводится на 2024.2. Ранее в 2024.2 были исправлены ошибки, связанные с копированием картинок при экспорте. Если проблема будет воспроизводиться на 2024.2, просьба переоткрыть баг.
