### ISSUE TITLE
Удаление реквизита объекта создает битую ссылку, если у реквизита формы установлен признак "Сохранение" и создан элемент формы

### ISSUE THREAD

**Issue by DmitryShvaika** [1C-Company/1c-edt-issues#161]
### Описание ошибки

Удаление реквизита объекта создает битую ссылку, если у реквизита формы установлен признак "Сохранение" и создан элемент формы

### Как воспроизвести

1. Создайте обработку
2. Создайте реквизит объекта обработки
3. Создайте форму обработки
4. У формы установите свойство "Автоматическое сохранение данных в настройках" = "Сохранять"
5. У реквизита формы установите Сохранение
![image](https://user-images.githubusercontent.com/54451084/144436465-e8a77439-c1c7-416f-9d6b-aee52a3b7be0.png)
6. Перетащите реквизит на форму (создайте элемент формы с этим реквизитом)
7. Удалите реквизит объекта обработки.
8. Удалите элемент формы 
9. Наблюдайте ошибку
![image](https://user-images.githubusercontent.com/54451084/144437899-f58d0c1e-df37-40a8-86e5-ded3d4fda60a.png)

### Ожидаемое поведение

1. При рефакторинге предлагать удалять элементы формы, у которых реквизит является свойством пути данных
2. Удалять идентификатор сохраняемых данных при удалении реквизита

### Лог рабочей области

[логи.zip](https://github.com/1C-Company/1c-edt-issues/files/7642554/default.zip)

### Версия 1С:EDT

Ruby 2021.2.10

### Операционная система

Windows

### Установленные плагины

1C:Code style V8, 1C:SSL-support

### Дополнительная информация

[test.zip](https://github.com/1C-Company/1c-edt-issues/files/7642565/test.zip)
Прилагаю тестовый проект с готовой обработкой - достаточно удалить реквизит обработки для повторения ошибки.

**Comment by vadimeg** [comment]
В 2021.3 при удалении реквизита очищается путь к данным у элемента и ошибка не воспроизводится. Но, действительно, сейчас нет диалога с предложением удалить связанный элемент

**Comment by DmitryShvaika** [comment]
> В 2021.3 при удалении реквизита очищается путь к данным у элемента и ошибка не воспроизводится. Но, действительно, сейчас нет диалога с предложением удалить связанный элемент

Прилагаю видео как повторить ошибку на 2021.3

![БитаяСсылкаСохраняемыйРеквизит](https://user-images.githubusercontent.com/54451084/162922691-2e1d64b9-044c-4d2c-b87d-622a67beb61a.gif)

Спасибо

**Comment by vadimeg** [comment]
Исправлено в 2021.3.5
