### ISSUE TITLE
Ошибка сравнения версий DOCX файла в приложении Word 2016 

### ISSUE THREAD

**Issue by tormozit** [1C-Company/1c-edt-issues#1611]
### Описание ошибки

На компьютере установлен Word 2016 .
Добавил в гит DOCX файл. Закоммитил 2 его версии. В списке файлов коммита вызываю команду сравнения и получаю ошибку 
Failed to create Ole Client. result = -2147221164

### Как воспроизвести

я

### Скриншоты

![изображение](https://github.com/user-attachments/assets/411887f2-e80b-4e1c-ad61-15cf6cf13eba)

![изображение](https://github.com/user-attachments/assets/91a88a1f-c7ea-4e2c-a851-acc906eefb45)

### Ожидаемое поведение

Открылось сравнение версий документа в окне приложения Word 2016

### Лог рабочей области

я

### Версия 1С:EDT

2024.1.2

### Операционная система

Windows

### Версия платформы 1С:Предприятие 8

8.3.25

**Comment by tretyakevich** [comment]
Добрый день. Проверил на 2024.1.2 и 16-м Word-е. У меня сравнение работает.
![Image](https://github.com/user-attachments/assets/0d3e9c06-3fff-4417-9e34-a6d9181f215c)

Судя по ошибке - есть проблема с запуском компонент офиса, причина неизвестна. 
Подобные темы в форумах Eclipse поднимаются периодически, но практически всегда все уходит в проблемы установки компонент офиса на конкретном локальном хосте. Можно попробовать проверить через создание объекта Word.Application в VBA (в том же Excel-е), чтобы проверить. 

Чего-то более конкретного предложить не могу.

**Comment by tretyakevich** [comment]
Если будет дополнительный контекст - просьба переоткрыть.
