### ISSUE TITLE
[1CEDT] Зависание интерфейса edt 2024.1.x

### ISSUE THREAD

**Issue by EChudnovsky** [1C-Company/1c-edt-issues#1621]
### Описание ошибки

Операции связанные с редактированием ролей, интерфейсов или после принятия большого количества измененных объектов часто приводит к зависанию интерфейса на операциях:
расширенная проверка объектов или сортировка объектов.
Прошу проанализировать файлы логирования с включенным сбором "UI Freeze Monitoring".

### Как воспроизвести

1. Развернуть типовую конфигурацию ЗУП
2. Импортировать проект
3. Выполнить операции по добавлению изменению ролей и интерфейсов.

### Скриншоты

Пример зависание edt на процессе сортировки, в логировании только статус ожидания завершения процесса, сколько необходимо ждать, что бы было понятно что процесс завис (здесь завершение после 60 минут ожидания!!!)
![изображение](https://github.com/user-attachments/assets/6c1047df-18f5-4e8e-9709-d84cb9dbe51d)
![изображение](https://github.com/user-attachments/assets/2c45ceab-5e0b-40c7-9069-a37919461ae9)

Скрин с операцией редактирования права у роли. Операция - этот снятие\установка флажка  права роли. Установил флажок начинается ожидание отклика интерфейса от минуты до 2х и более.

![изображение](https://github.com/user-attachments/assets/7cfd038a-fbc6-4a50-9276-469f81719e90)

Скрин замораживание интерфейса при операции расширенной проверки:
![изображение](https://github.com/user-attachments/assets/c56c71c1-07b7-4cb6-b8e9-568af3be7ca2)

![изображение](https://github.com/user-attachments/assets/665bbb5d-ca79-49a3-b4a7-c15f17b57555)

### Ожидаемое поведение

Сократить время ожидания разработчика на отклик интерфейса до возможного минимума.
Убрать операции приводящие к зависанию интерфейса.
Сейчас время ожидания на операциях: редактирования или записи объекта может достигать от 10 с до более десятков минут,  а частым состоянием бывает зависание интерфейса.

### Лог рабочей области

рабочая область с зависание интерфейса:
[log.zip](https://github.com/user-attachments/files/18037414/log.zip)

Длительные операции при редактировании ролей:
[log.zip](https://github.com/user-attachments/files/18038196/log.zip)

Замораживание интерфейса при операции расширенной проверки:
[log.zip](https://github.com/user-attachments/files/18038602/log.zip)

Зависшая операция расширенной проверки и редакторов объектов при открытии (в этом случае необходимо только пере создавать рабочую область):
[log.zip](https://github.com/user-attachments/files/18038941/log.zip)

### Версия 1С:EDT

Ruby 2024.1.3

### Операционная система

Windows

### Версия платформы 1С:Предприятие 8

8.3.24.1758

### Установленные плагины

Нет плагинов

### Дополнительная информация

Конфигурация: Зарплата и управление персоналом КОРП, редакция 3.1 (3.1.27.208)

eclipse.buildId=2024.1.3.13
java.version=17.0.13
java.vendor=Azul Systems, Inc.
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=ru_RU
Command-line arguments:  -os win32 -ws win32 -arch x86_64
-Xmx16000m

**Comment by Erik773** [comment]
Здравствуйте @EChudnovsky.
Могли бы Вы, пожалуйста, снять и приложить дамп потоков на момент зависания. Как снять дамп описано в разделе "Если 1C:EDT зависла" https://its.1c.ru/db/edtdoc/content/153/hdoc

**Comment by EChudnovsky** [comment]
> Здравствуйте @EChudnovsky. Могли бы Вы, пожалуйста, снять и приложить дамп потоков на момент зависания. Как снять дамп описано в разделе "Если 1C:EDT зависла" https://its.1c.ru/db/edtdoc/content/153/hdoc

Добрый день.
Очередное зависание дамп [здесь](https://1cksu-my.sharepoint.com/:u:/g/personal/e_chudnovsky_1c-ksu_ru/EVrYxpwLV1lKkFLj6ujadTEBTRq8TYZ5rdnOCuwql_FcWw?e=qMt31R)

**Comment by tretyakevich** [comment]
В 2024.2 провели большую работу по устранению зависаний и нарушения целостности данных при редактировании прав.
Также изменили стратегию импорт и экспорта, теперь все операции прерываемы и возобновляемы в случае перегрузок и т.п.
