### ISSUE TITLE
При отборе в дереве метаданных порядок объектов не соответствует порядку объектов без отбора

### ISSUE THREAD

**Issue by shcherbakov-vadim** [1C-Company/1c-edt-issues#1624]
### Описание ошибки

При отборе в дереве метаданных порядок объектов не соответствует порядку объектов без отбора

### Как воспроизвести

1. Открыть дерево метаданных
2. Ввести значение отбора

### Ожидаемое поведение

При отборе порядок объектов не должен отличаться от порядка объектов без отбора

### Лог рабочей области

нет

### Версия 1С:EDT

2024.1.2

### Операционная система

Linux

### Версия платформы 1С:Предприятие 8

8.3.22.2557

### Дополнительная информация

Kubuntu 24.04

**Comment by Erik773** [comment]
@shcherbakov-vadim, здравствуйте.
Могли бы Вы, пожалуйста, приложить скриншоты с объяснением проблемы и уточнить какое значение отбора нужно ввести?
Приложите, пожалуйста логи рабочей области ЕДТ (.log, .bak.log и trace.log), можно найти в рабочей области в папке .metadata, и файлы из директории с клиентом ЕДТ формата hs_err_pid.

**Comment by shcherbakov-vadim** [comment]
В версии 2024.1.3 проблема не воспроизводится
