### ISSUE TITLE
Не могу добавить проект в EDT: START

### ISSUE THREAD

**Issue by unichkin** [1C-Company/1c-edt-issues#1639]
### Описание ошибки

Есть ранее созданный проект, который я убирал из общего списка, пока он не был нужен. Сегодня он понадобился - добавляю его в список, он не добавляется. По нажатию на кнопку "Добавить" ничего не происходит, хотя анимация кнопки работает.

### Как воспроизвести

-

### Скриншоты

![unich-23-12-2024-10-36-22](https://github.com/user-attachments/assets/aa4e002f-1db5-49d5-92a8-5ec5bb35e4f3)

### Ожидаемое поведение

Должен добавиться проект, еще позавчера это прекрасно работало

### Лог рабочей области

Нет логов

### Версия 1С:EDT

2024.1.3

### Операционная система

Windows

### Версия платформы 1С:Предприятие 8

8.3.25.1445

**Comment by unichkin** [comment]
Методом научного тыка решил - оказалось что в списке проектов был зарегистрирован несуществующий каталог.  После того как я удалил этот проект из списка - кнопка заработала, новый проект добавился. Очень странное поведение..

**Comment by Erik773** [comment]
Здравствуйте @unichkin.
Могли бы Вы, пожалуйста, приложить логи стартера (%USERPROFILE%\AppData\Local\1C\1cedtstart\logs).

**Comment by unichkin** [comment]
@Erik773 
[1cedtstart — копия.zip](https://github.com/user-attachments/files/18229886/1cedtstart.zip)
