### ISSUE TITLE
Исключение 0xC0000005 по адресу 0x4C780D42 ( mngbase.dll ) при вызове функции "IConfigMngr::getMDCont"

### ISSUE THREAD

**Issue by leonvlas** [1C-Company/1c-edt-issues#166]
### Описание ошибки

**При запуске конфигуратора.** 
1С:Предприятие 8.3 (8.3.19.1417)

>>> Исключение AngelScript.
        Процесс: 1cv8.exe ( 8.03.0019.1417 )
        Core.As: 1.0.2.1
         Модуль: Snegopat (  ) 
           Файл: C:\t\core-as-1-0-2-01\modules\snegopat\engine\com_metadata.as
         Строка: 783
        Функция: IMDContainer@ getIBMDCont()
         Строка: 783
       Описание: Исключение 0xC0000005 по адресу 0x4C780D42 ( mngbase.dll ) при вызове функции "IConfigMngr::getMDCont"
                 Стек вызовов:
                   C:\t\core-as-1-0-2-01\modules\snegopat\engine\com_metadata.as : IV8MetaData::IV8MetaData(int), строка 18,9
                   C:\t\core-as-1-0-2-01\modules\snegopat\engine\com_metadata.as : IV8MetaData@ IV8MetaData(int), строка 0,0
>>> Bad AngelScript result code in entranceToGateToAngelScript

**при попытке открыть пункт о программе и другие пункты меню.**
1С:Предприятие 8.3 (8.3.19.1417)

>>> Исключение AngelScript.
        Процесс: 1cv8.exe ( 8.03.0019.1417 )
        Core.As: 1.0.2.1
         Модуль: Snegopat (  ) 
           Файл: C:\t\core-as-1-0-2-01\modules\snegopat\engine\com_events.as
         Строка: 196
        Функция: void transmitCommandTrap(ICommandReceiver&inout, const CommandRef@, bool)
         Строка: 196
       Описание: Null pointer access
>>> Bad AngelScript result code in entranceToGateToAngelScript

### Как воспроизвести

1. При открытии конфигуратора
2. при  открытии пунктов меню

### Ожидаемое поведение

Ошибок не должно быть

### Лог рабочей области

>>> Исключение AngelScript.
        Процесс: 1cv8.exe ( 8.03.0019.1417 )
        Core.As: 1.0.2.1
         Модуль: Snegopat (  ) 
           Файл: C:\t\core-as-1-0-2-01\modules\snegopat\engine\com_events.as
         Строка: 196
        Функция: void transmitCommandTrap(ICommandReceiver&inout, const CommandRef@, bool)
         Строка: 196
       Описание: Null pointer access
>>> Bad AngelScript result code in entranceToGateToAngelScript

### Версия 1С:EDT

Конфигуратор

### Операционная система

Windows

**Comment by KovAlexey** [comment]
А вы точно туда написали?
Это же про снегопат

**Comment by marmyshev** [comment]
@leonvlas нелицензионный взлом Платформы наказывается по закону РФ.

**Comment by leonvlas** [comment]
Сори не туда написал ошибся сайтом. К взлому отношение не имеет, читайте внимательнее  соглашение о лицензии 1С.
Что такое Snegopat можно почитать на официальном сайте разработчика. https://snegopat.ru/

**Comment by marmyshev** [comment]
На всякий случай осталвлю тут инфу из лицензии 1С:Предприятия 8:

>    4. Лицензиат обязуется не допускать нарушений исключительных прав Правообладателя на ПРОГРАММНЫЙ ПРОДУКТ, в частности, не совершать и не допускать совершения третьими лицами следующих действий без специального письменного разрешения Правообладателя:
>     * распространять ПРОГРАММНЫЙ ПРОДУКТ или отдельные его компоненты;
>     * вносить какие-либо изменения в код ПРОГРАММНОГО ПРОДУКТА, содержимое баз данных и других наборов данных, в которых система хранит информацию, за исключением тех изменений, которые вносятся штатными средствами, входящими в состав ПРОГРАММНОГО ПРОДУКТА и описанными в сопроводительной документации;
>     * осуществлять доступ к информационной базе ПРОГРАММНОГО ПРОДУКТА и построение систем на основе ПРОГРАММНОГО ПРОДУКТА с помощью средств и технологических решений, не предусмотренных в сопроводительной документации;
>     * совершать действия, результатом которых является устранение или снижение эффективности технических средств защиты авторских прав, применяемых Правообладателем, включая применение программных и технических средств "мультиплексирования", средств, изменяющих алгоритм работы программных или аппаратных средств защиты ПРОГРАММНОГО ПРОДУКТА, а также использовать ПРОГРАММНЫЙ ПРОДУКТ с устраненными или измененными без разрешения Правообладателя средствами защиты;

Вот текст с сайта Снегопата:

> Снегопат работает, **внедряясь в процесс 1С**!!! и взаимодействуя напрямую с функциями движка 1С, **не документируемыми производителем**!!!!. Поэтому он должен уметь работать с разными версиями 1С, учитывая изменения в этих недокументируемых функциях от релиза к релизу. Это достигается путём создания "на лету" при запуске снегопата **"прослойки" между основным кодом снегопата и конкретным релизом 1С**!!!, которая учитывает эти изменения

Если я правильно понимаю лицензию 1С и описание Снегопата, любой кто устанавливает и использует Снегопат -  нарушает п.4 (второй и третий подпункты). Но подозреваю, что вопрос нужно финально задавать юристам по лицензиям. М.б. я не прав (имхо).
