### ISSUE TITLE
Не выдается ошибка на метод Количество() для объекта РолиПользователя.

### ISSUE THREAD

**Issue by DmitryShvaika** [1C-Company/1c-edt-issues#167]
### Описание ошибки

Edt не выдает ошибку при использовании метода Количество() для объекта РолиПользователя в следующем фрагменте:

![image](https://user-images.githubusercontent.com/54451084/144557906-18123cb2-6a87-4911-9e81-c4bc3d744d06.png)

Конфигуратор же "видит" ошибку при расширенной проверке 

![image](https://user-images.githubusercontent.com/54451084/144557976-baecf556-ae28-4781-8384-5224e75bf246.png)

Справка так же правильно показывает, что метода нет

![image](https://user-images.githubusercontent.com/54451084/144558069-bbdba9b0-b42b-422d-9ef5-77efab5dca45.png)

### Как воспроизвести

1. Набрать код

		ПользовательИБ = ПользователиИнформационнойБазы.НайтиПоУникальномуИдентификатору(
			Новый УникальныйИдентификатор);
		Количество = ПользовательИБ.Роли.Количество();
               Количество  = Количество ;

2. Наблюдать отсутствие ошибки

### Ожидаемое поведение

Должна выдаваться ошибка аналогично конфигуратору.

### Лог рабочей области

[логи.zip](https://github.com/1C-Company/1c-edt-issues/files/7647353/default.zip)

### Версия 1С:EDT

Ruby 2021.2.10

### Операционная система

Windows

### Установленные плагины

1C:Code style V8, 1C:SSL-support

**Comment by marmyshev** [comment]
EDT и не подсказывает этот метод. Его явно нет и ввести в ЕДТ через помощник не возможно.

При включении строгой типизации - такое показывается. 

Какие аргументы за то, чтобы сигнализировать вот именно этот метод, а другие не сигнализировать?

**Comment by DmitryShvaika** [comment]
Согласен, что надо сигнализировать на все отсутствующие методы.
Тогда это в пожелание.
Однако не понятно, почему это доступно только в строгой типизации.
Хотелось бы видеть и при обычной проверке то же. 
Если тип однозначно определен, список его методов как и свойств в большей части случаев известен.

**Comment by marmyshev** [comment]
> Хотелось бы видеть и при обычной проверке то же.

Это уже сейчас можно - включайте в настройках для любой проверки из "строгой типизации" возможность валидировать без аннотации `// @strict-types` (настраивается для каждой проверки отдельно!)

> Если тип однозначно определен, список его методов как и свойств в большей части случаев известен.

В этом-то и проблема - то, что ЕДТ определила тип - это еще ничего не значит, и там в реальности в рантайме 1С может быть другой тип у которого есть метод/свойство. Предлагаете на такое тоже всегда сигнализировать?

Даже Конфигуратор выдает это всего лишь как предупреждение что "Возможно ошибочный метод",  а возможно и нет... Рантайм его знает...

**Comment by KovAlexey** [comment]
> Даже Конфигуратор выдает это всего лишь как предупреждение что "Возможно ошибочный метод", а возможно и нет... Рантайм его знает...

А откуда там может вообще взяться что-то другое?
Тип пользователя ИБ известен.
Тип поля пользователя ИБ известен.
Набор его методов известен.

Откуда в рантайме там взяться чему-то другому в примере выше? Там всегда будет одно и то же,  как не извернись.

**Comment by DmitryShvaika** [comment]
Имелся ввиду общий подход к проблеме, а не частный случай. Хотя, согласен, что есть варианту, где тип жестко определен. Например, если метод Новый Структура, то это будет всегда Структура как не верти. А вот Обработки.ИмяОбработки.Создать() вернет объект с нефиксированными для 1с свойствами и методами. Давайте закрою проблему. Этот частный случай все равно не решит ее.

**Comment by marmyshev** [comment]
> А откуда там может вообще взяться что-то другое?

Мы говорим о валидации в конкретном месте - есть есть просто тип таблицы из пользователей. 
С т.з. вызова - там просто тип. В ЕДТ нет понятия "Жесткий тип" или "мягкий тип"

Вариант 1:


```bsl
ПользовательИБ = ПользователиИнформационнойБазы.НайтиПоУникальномуИдентификатору(
 	Новый УникальныйИдентификатор);
 Количество = ПользовательИБ.Роли.Количество();
        Количество  = Количество ;
```

и Вариант 2

```bsl
ПользовательИБ = Неопределенно; // ПользовательИнформационнойБазы - зуб даю, тут такой тип!
 Количество = ПользовательИБ.Роли.Количество();
        Количество  = Количество ;
```

С точки зрения типов в  `ПользовательИБ.Роли` - в свойстве "Роли" типы таблицы - одинаковые. Но разделить тут тип "достоверно-определенный" или тип "возможно недостоверно определенный" - в ЕДТ можно, но сейчас такого нет, не известно на сколько это дорого будет еще хранить такую инфу везде в миллионах объектов...
