### ISSUE TITLE
Не формируется модуль внешней обработки.

### ISSUE THREAD

**Issue by Jimmi910** [1C-Company/1c-edt-issues#18]
## Опишите ошибку

При создании внешней обработки, когда формируется файл .epf, модуль обработки остается пустым.

## Как воспроизвести

1. Создаете проект "внешняя обработка"
2. Открываете ее модуль. (Модуль объекта)
3. Пишите любую процедуру.
4. Нажимаете Сохранить.
5. Открываете редактор Проекта внешней обработки.
6. Там в пункте "настройки выгрузки" указан путь где должна лежать сформированная обработка формата .epf
7. Открываете эту обработку через Конфигуратор, и видите что модуль объекта пустой.

## Ожидаемое поведение

В модуле объекта обработки должен находиться написанный код

## Скриншоты

Видео - https://disk.yandex.ru/d/hhxcDGEt4wnOWg

## Лог рабочей области
 
Весь проект, в нем и лог есть - https://disk.yandex.ru/d/UOabmnMOinw0AQ

## Окружение (пожалуйста укажите информацию):

 - OS: 'Windows 11'
 - Версия 1C:EDT Ruby 2021.2.7
 - Платформа 1С 8.3.20.1590

## Дополнительная информация
[ВнешняяОбработка.zip](https://github.com/1C-Company/1c-edt-issues/files/7444472/default.zip)
[test.zip](https://github.com/1C-Company/1c-edt-issues/files/7444474/test.zip)

https://user-images.githubusercontent.com/26252130/139491537-addbdff5-e177-4809-8352-7e7438e966f2.mp4

**Comment by kssashurik** [comment]
OS: 'Windows 11'
Версия 1C:EDT Ruby 2021.2.8
Платформа 1С 8.3.20.1590

Ошибка также присутствует.

**Comment by Daemonold** [comment]
Win 10 64
Версия 1C:EDT Ruby 2021.2.9
Версия 1C:EDT Ruby 2021.2.10
Платформа 1С 8.3.20.1549
Ошибка сохраняется

**Comment by yukon39** [comment]
В 8.3.20.1674 x64 не воспроизводится

**Comment by B2etle** [comment]
> В 8.3.20.1674 x64 не воспроизводится

Подтверждаю, на 8.3.20.1674 (x64) проблема отсутсвует.

**Comment by fullstack1c** [comment]
Windows 11 Pro 21H2
1c-edt-2021.2.12+2-x86_64
1С:Предприятие 8.3 (8.3.20.1590)

Ошибка присутствует. Модуль объекта пустой, хотя в файле ObjectModule.bsl код есть.
