### ISSUE TITLE
Edt некорректно определяет тип переменной в конструкции Для Каждого Элемент Из Новый Структура(ИменаПолей), если ИменаПолей не описана

### ISSUE THREAD

**Issue by DmitryShvaika** [1C-Company/1c-edt-issues#180]
### Описание ошибки

Edt некорректно определяет тип переменной в конструкции Для Каждого Элемент Из Новый Структура(ИменаПолей), если ИменаПолей не описана

![image](https://user-images.githubusercontent.com/54451084/144983474-bb723368-e79c-4f52-a833-f65d0126470a.png)

### Как воспроизвести

1. Ввести код

Процедура проц1(ИменаПолей) Экспорт
	
	Для Каждого эл из Новый Структура(ИменаПолей) Цикл
		
		а = эл;
		а = а;
		
	КонецЦикла;  
	
КонецПроцедуры

2. Наблюдать ошибку

### Ожидаемое поведение

Переменная эл должна определяться как КлючИЗначение

### Лог рабочей области

[логи.zip](https://github.com/1C-Company/1c-edt-issues/files/7666259/default.zip)

### Версия 1С:EDT

Ruby 2021.2.10

### Операционная система

Windows

### Установленные плагины

1C:Code style V8

**Comment by MaksimDzyuba** [comment]
Здравствуйте, воспроизвел, поправил в 2023.3, возможно будет перенос в 2023.2, спасибо!
![image](https://github.com/1C-Company/1c-edt-issues/assets/77277424/deaea879-f717-4773-9d66-c1c60438d1a9)
