### ISSUE TITLE
Сужать тип поля Ключ у переменной КлючИЗначение при выходе из переменной Структура. Т.к. в структуре ключом может быть только строка

### ISSUE THREAD

**Issue by DmitryShvaika** [1C-Company/1c-edt-issues#181]
### Описание проблемы

Код ниже выдает ошибку, хотя вроде все правильно Ключ имеет строковый тип, а Найти принимает строку - имя элемента для поиска.

![image](https://user-images.githubusercontent.com/54451084/144984132-87ac09ab-54ee-488d-936b-aea30ba354f1.png)

Проблема в поле Ключ - его тип определяется как Произвольный. 

![image](https://user-images.githubusercontent.com/54451084/144984244-64886f51-1e34-4495-b537-3f697d15ca51.png)

### Описание решения проблемы

Предлагаю сужать тип поля Ключ до Строка, если он получен от структуры.

**Comment by RedMammoth** [comment]
Также предалагаю для объекта КлючИЗначение определять тип и для поля Значение. Как минимум для фиксированной структуры.

**Comment by marmyshev** [comment]
@RedMammoth 

> Также предалагаю для объекта КлючИЗначение определять тип и для поля Значение. Как минимум для фиксированной структуры.

Не понятное предложение. При создании фиксированной структуры - все поля и их типы (значения) копируются из базовой структуры. Вероятно, есть пример при котором что-то не работает как ожидается? Нужно написать его.

**Comment by RedMammoth** [comment]
![image](https://user-images.githubusercontent.com/64589646/149834216-32556128-cb20-41af-aecc-8a7486350ac5.png)

```bsl
// @strict-types
#Область ПрограммныйИнтерфейс

// Фиксированная структура со значениями одного типа.
// 
// Возвращаемое значение:
//  ФиксированнаяСтруктура -- Фиксированная структура со значениями одного типа::
// * Ключ1 - Число -
// * Ключ2 - Число -
// * Ключ3 - Число -
Функция ФиксированнаяСтруктураСоЗначениямиОдногоТипа() Экспорт

	ОписаниеСтруктуры = Новый Структура;
	ОписаниеСтруктуры.Вставить("Ключ1", 1);
	ОписаниеСтруктуры.Вставить("Ключ2", 2);
	ОписаниеСтруктуры.Вставить("Ключ3", 3);
	Возврат Новый ФиксированнаяСтруктура(ОписаниеСтруктуры);

КонецФункции

// Фиксированная структура со значениями одного типа.
// 
// Возвращаемое значение:
//  ФиксированнаяСтруктура -- Фиксированная структура со значениями одного типа::
// * Ключ1 - Число -
// * Ключ2 - Строка -
// * Ключ3 - Дата -
Функция ФиксированнаяСтруктураСоЗначениямиРазногоТипа() Экспорт

	ОписаниеСтруктуры = Новый Структура;
	ОписаниеСтруктуры.Вставить("Ключ1", 1);
	ОписаниеСтруктуры.Вставить("Ключ2", "Строка");
	ОписаниеСтруктуры.Вставить("Ключ3", ТекущаяДатаСеанса());
	Возврат Новый ФиксированнаяСтруктура(ОписаниеСтруктуры);

КонецФункции

#КонецОбласти

#Область СлужебныйПрограммныйИнтерфейс

Процедура Тест1() Экспорт

	Индекс = 0;
	// обращение по ключу норм:
	Индекс = ФиксированнаяСтруктураСоЗначениямиОдногоТипа().Ключ1;
	
	// Если я хочу в цикле пройтись - тип не известен
	Для Каждого КлючИЗначение Из ФиксированнаяСтруктураСоЗначениямиОдногоТипа() Цикл
		Индекс = КлючИЗначение.Значение; // Тут хотелось бы, чтобы Значение определялось однозначно как Число
	КонецЦикла;

КонецПроцедуры

Процедура Тест2() Экспорт

	Индекс = 0;
	Имя = "";
	Дата = ТекущаяДатаСеанса();
	
	// обращение по ключу норм:
	Индекс = ФиксированнаяСтруктураСоЗначениямиРазногоТипа().Ключ1;
	Имя = ФиксированнаяСтруктураСоЗначениямиРазногоТипа().Ключ2;
	Дата = ФиксированнаяСтруктураСоЗначениямиРазногоТипа().Ключ3;
	
	// Если я хочу в цикле пройтись - тип не известен
	Для Каждого КлючИЗначение Из ФиксированнаяСтруктураСоЗначениямиОдногоТипа() Цикл
		Индекс = КлючИЗначение.Значение;
		// В случае с разными типами так и так проверять в условиях тип знч,
		// но возможно неплохо было бы чтобы в типе Значение было не Произвольный, а множество типов значений полей
	КонецЦикла;

КонецПроцедуры

#КонецОбласти
```

**Comment by RedMammoth** [comment]
С полями разных типов сложно подобрать пример, ну допустим я поместил в поля ОбработкаОбъект.Обработка1, ОбработкаОбъект.Обработка2, ОбработкаОбъект.Обработка3 и хочу в цикле пройтись по полям структуры и у каждого значения вызвать экмпортный метод.

**Comment by RedMammoth** [comment]
Если всегда структуру обходить в цикле, то можно обойтись док комментом:
ФиксированнаяСтруктура из КлючИЗначение - описание:
*Ключ - Строка -
*Значение - Число -

А вот как описать что бы и в цикле обходить и по именам ключей обращаться не знаю

**Comment by marmyshev** [comment]
@RedMammoth у меня сомнения, что эта ситуация выше может быть решена "легко и быстро".

Кажется не правильно требовать от "Структуры" авто-вычисления всех значений всех ключей - ведь нет гарантии что какой-то код не добавит туда другое значение?

А если есть гарантия - так и запиши эту "гарантию" в документирующем комментарии:

//  ФиксированнаяСтруктура из КлючИЗначение - где:
// * Ключ - Строка
// * Значение - Число

Это будет более честно - все значения одного типа. Клиентский код не будет пытаться работать с ключами напрямую и не будет анализа типов значений для ключей.
