### ISSUE TITLE
Добавить в контекстное меню точки останова команду Удалить точку останова

### ISSUE THREAD

**Issue by DmitryShvaika** [1C-Company/1c-edt-issues#194]
### Описание проблемы

Сейчас нет возможности удалить точку останова через контекстное меню. Надо догадаться второй раз щелкнуть по ней мышью. Было бы удобно дополнительно видеть эту команду в контекстном меню.

![image](https://user-images.githubusercontent.com/54451084/145767883-6fc2f879-4fb1-477a-bc65-72125e78adc1.png)

### Описание решения проблемы

Добавить в контекстное меню точки останова команду Удалить точку останова

**Comment by KovAlexey** [comment]
ИМХО. Вторая кнопка - бессмыслица.
Должна надпись меняться в зависимости от контекста

**Comment by KovAlexey** [comment]
Или просто переименовать в Toggle Breakpoint (Переключить точку остановы)

**Comment by DmitryShvaika** [comment]
Да, наверное так - менять пункт в меню. Иначе не понятно что такое "Точка останова"

**Comment by DmitryShvaika** [comment]
Закрою задачу, напишу новую.
