### ISSUE TITLE
Ошибка при обновлении конфигурации

### ISSUE THREAD

**Issue by shcherbakov-vadim** [1C-Company/1c-edt-issues#197]
### Описание ошибки

При выполнении обновления конфигурации возникает ошибка
Файл объекта не существует - /Catalogs/Справочник2.xml

### Как воспроизвести

1. Восстановить приложенный архив в каталог c:\temp\
2. Добавить в список ИБ c:\temp\test.update\base с идентификатором 6b2811e4-05fc-4c48-9be6-26c58876d7ae
3. Открыть рабочую область в каталоге c:\temp\test.update\edt
4. Переключиться на ветку master
5. Получить и слить изменения из удаленной ветки c:\temp\test.update\repo
6. Переключиться на ветку task
7. Переключиться на ветку master
8. Запустить применение изменений

### Скриншоты

![2021-12-14_11-37-59](https://user-images.githubusercontent.com/52153345/145962911-28f99a34-87f0-4b31-9c23-50f7c66acb19.png)

### Ожидаемое поведение

Обновление ИБ должно пройти без ошибок

### Лог рабочей области

нет

### Версия 1С:EDT

2021.2.10

### Операционная система

Windows

### Дополнительная информация

[test.update.zip](https://github.com/1C-Company/1c-edt-issues/files/7709991/test.update.zip)

**Comment by pchurbanov** [comment]
Данная ошибка исправлена в 2021.3
