### ISSUE TITLE
Ошибка при экспорте проекта в информационную базу

### ISSUE THREAD

**Issue by hamec** [1C-Company/1c-edt-issues#20]
## Опишите ошибку

После импорта расширения, провожу обновление базы. Появляется ошибка.
Помогло решить импорт всех элементов стиля в расширение
![image](https://user-images.githubusercontent.com/25643488/139494783-aefef175-5c93-4179-9268-123998efbb8c.png)

## Лог рабочей области
 
[log.txt](https://github.com/1C-Company/1c-edt-issues/files/7444684/log.txt)
[trace.log](https://github.com/1C-Company/1c-edt-issues/files/7444686/trace.log)

## Окружение:

 - OS:'Windows 10'
 - Версия 1C:EDT '2021.2.8'

**Comment by tretyakevich** [comment]
Для воспроизведения необходимы:
1. Код расширения (можно урезанного до мин. количества объектов, на котором проблема воспроизводится)
2. Либо демо-пример, если есть понимание того, как воспроизвести эту проблему на 2021.2.8

**Comment by Fedorov-Ivan** [comment]
Архив с проектом (конфигурация + расширение)
[ISSUE20-21.zip](https://github.com/1C-Company/1c-edt-issues/files/7451567/ISSUE20-21.zip)

**Comment by vadimeg** [comment]
@hamec Была такая ошибка, что стиль не заимствовался в расширение при заимствовании формы, если на нее была ссылка из элементов формы. Затем она была исправлена, как минимум в 2021.2.6 фикс есть. Т.е. если с нуля заимствовать форму, то проблем не будет, стиль будет заимствован и экспорт в ИБ пройдет без ошибок.
Насколько я понимаю, приложенный тест был создан в старой версии EDT, до 2021.2.6, так?

Чтобы исправить проблему можно просто обновить форму расширения:
![image](https://user-images.githubusercontent.com/17178862/139690820-e1bdd152-8767-4947-9ef5-708e7b69ccd8.png)

Стиль при этом будет заимствован. Можно, конечно, сделать задачу на написание валидационной проверки, которая бы добавляла ошибку в окно ошибок конфигурации, чтобы было понятно из-за чего произошла проблема.

Достаточно этой информации чтобы закрыть баг?

**Comment by Fedorov-Ivan** [comment]
Тест был сделан на 2021.2.8(правда для воспроизведения ошибки пришлось зайти в конфигуратор, удалить элемент стиля из расширения, удалить проект и снова импортировать из ИБ)
а нельзя сделать проверки во время импорта проекта из ИБ? У нас просто воспроизводится на проекте с которым работаем через конфигуратор. (В основной конфигурации есть элемент стиля, в расширении нет, при этом есть заимствованная форма в расширении, которая использует этот элемент стиля)

**Comment by vadimeg** [comment]
@hamec 
> а нельзя сделать проверки во время импорта проекта из ИБ?
В смысле, не давать импортировать такой проект и выдавать ошибку в окне импорта? Не уверен, что это хороший вариант. Предлагается сделать проверку, которая сработает автоматически сразу после импорта, на построение проекта. В этом случае можно будет по проверке спозиционироваться на проблемной форме или элементе стиля в базовой конфигурации (зависит от того, как будет реализована проверка) и исправить ситуацию (либо обновив форму, либо заимствовав недостающий стиль).

**Comment by hamec** [comment]
Извините за долгий ответ.
Воспроизвел ошибку на 2021.2.8 удалив все элементы стиля из расширения, проект расширения прилагаю
[ext_test.zip](https://github.com/1C-Company/1c-edt-issues/files/7491259/ext_test.zip)
.

**Comment by hamec** [comment]
> Была такая ошибка, что стиль не заимствовался в расширение при заимствовании формы, если на нее была ссылка из элементов формы. Затем она была исправлена, как минимум в 2021.2.6 фикс есть. Т.е. если с нуля заимствовать форму, то проблем не будет, стиль будет заимствован и экспорт в ИБ пройдет без ошибок.
> Насколько я понимаю, приложенный тест был создан в старой версии EDT, до 2021.2.6, так?

Да проект был сделал на 2021.1.7, указанный способ проблему не решал. Решалось только импортом всех элементов стиля в расширение.

По поводу закрытия не знаю, если не делать импорт всех элементов стиля то проблемы остается.

**Comment by vadimeg** [comment]
Исправлено в 2021.2.9
