### ISSUE TITLE
Ошибка конвертации проекта для информационной базы

### ISSUE THREAD

**Issue by Pticelov** [1C-Company/1c-edt-issues#207]
### Описание ошибки

Я конвертировал конфигурацию ДО КОРП 2.1.11.5.69.0 для edt 2021.2.10+2 все прошло нормально. Я могу запускать приложение, вносить изменения.

Но, если я например создаю новую ветку, и для этой новой ветки выбираю новую пустую базу, то при попытке обновить эту базу, получаю ошибку

Ссылка на неизвестное поле или поля не существует - BusinessProcess.Исполнение.TabularSection.ДополнительныеРеквизиты.StandardAttribute.Ref

Ссылка на неизвестное поле или поля не существует - BusinessProcess.Исполнение.TabularSection.ДополнительныеРеквизиты.Attribute.Свойство

Ссылка на неизвестное поле или поля не существует - BusinessProcess.Исполнение.TabularSection.ДополнительныеРеквизиты.Attribute.Значение

и так для каждого бизнесс процесса

Если я пытаюсь выгрузить файлы из проекта командой ring edt workspace export, то выгрузка проходит успешно, но при загрузке в новую конфигурацию та же ошибка.

Таким образом, проект в edt нормально работает только с той базой, из которой он и был сконвертирован

### Как воспроизвести

1. Взять базу ДО КОРП 2.1.11.5.69.0
2. Создать новый проект edt
3. импортировать проект в edt из этой базы
4. Создать новую ветку, указать для нее чистую базу, попробовать обнвить эту базу данными проекта
5. Или попробовать конвертировать проект ring edt workspace export в заданный каталог, и попробовать полученные файлы загрузить в новую конфигурацию

### Ожидаемое поведение

Конвертация будет проходить без ошибок

### Лог рабочей области

[log.txt](https://github.com/1C-Company/1c-edt-issues/files/7737002/log.txt)
[trace.log](https://github.com/1C-Company/1c-edt-issues/files/7737003/trace.log)

### Версия 1С:EDT

Ruby 2021.2.10

### Операционная система

Windows

**Comment by tretyakevich** [comment]
Добрый день. В релизной версии ДО КОРП 2.1.11.5 в выгрузке XML присутствуют указанные реквизиты табличных частей. 
Соответственно наша попытка повторить эту проблему не увенчалась успехом.

Для повторения проблемы нем необходима дополнительная информация:
1. Версия платформы, которую вы используете (в конфигурации режим совместимости 8.3.8, поэтому набор подходящих платформ очень широк при том, что в них много уникальных ошибок в протоколе XML)
2. Крайне желательно - полную XML выгрузку вашей конфигурации (в формате платформы или EDT - не важно) для анализа.

По причинам ошибки, наиболее вероятные:
1. Были удалены (каким-то образом) табличная часть BusinessProcess.Исполнение.TabularSection.ДополнительныеРеквизиты и/или некоторые из ее реквизитов (Свойство, Значение)
2. При этом остались ссылки на эти данные, например релизная версия 2.1.11.5 содержит подобные ссылки в роли РаботаСПротоколомРаботыПользователей 

В зависимости от того, желаемое это было удаление или нет - нужно либо восстновить реквизиты/табличную часть, либо удалить ссылки из роли.

В настоящий момент мы разрабатываем проверку на подобные "потерянные" ссылки, которая позволит легко находить аффектированные объекты до публикации в ИБ. К сожалению в 2021.2.10 она еще не успела войти.

**Comment by Pticelov** [comment]
Добрый день.
Платформа 8.3.19.1264
Для примера взяли Документооборот 8 КОРП, редакция 2.1 (2.1.14.4) выгрузили конфигурацию поставщика. Загрузили ее в пустую базу. Создали проект edt импортировали данные проекта из этой базы. Создали репозиторий. Таким образом есть ветка мастер и привязанная к ней информационная база, из которой и загрузили проект. Можно запустить приложение из этой ветки, все работает. Создаем новую ветку и привязываем к ней пустую базу. Запускаем приложение тонкий клиент, edt предлагает выполнить полную загрузку проекта, соглашаемся, в ходе загрузки происходит ошибка. Файлы подготовили, небольшая сложность с передачей, как только получится дадим ссылку.

**Comment by Pticelov** [comment]
http://filetrance.tander.ru/3cf5495bdf28d1a6af62eb5d6ea02876 ссылка на архив, там же в корне файлы логов edt

**Comment by tretyakevich** [comment]
Переоткрыл issue, пока еще работа по ней не завершена

**Comment by tretyakevich** [comment]
Протестировали указанный сценарий, и вот он уже воспроизвелся. 
Проблема именно в 19-й платформе, потому что 20-я платформа эту конфигурацию загружает без ошибок. 
Продолжаем исследование и сравнение для того, чтобы выяснить, что именно вызывает ошибку (неверная поддержка 19-го формата в EDT, ошибка платформы или что-то еще)

**Comment by tretyakevich** [comment]
К сожалению, это ошибка 19-й платформы. Даже на 1С:Предприятие 8.3 (8.3.19.1467) платформа сама не принимает свою же XML-выгрузку (создать ИБ - выгрузить в XML из конфигуратора - загрузить в конфигураторе в новую ИБ -> те же самые ошибки).

Критическую ошибку коллегам из платформы заведем/передадим. Сейчас смотрим - есть ли какой-то воркэраунд (кроме очевидного - перейти на 20-ю платформу, в ней, похоже, эту ошибку уже поправили).

**Comment by tretyakevich** [comment]
Ошибка исправлена в платформе 8.3.20
