### ISSUE TITLE
Отображение ошибок конфигурации

### ISSUE THREAD

**Issue by alex7six** [1C-Company/1c-edt-issues#209]
### Описание проблемы

В настройках проекта можно указывать в каких режимах выполнять проверку, например, у меня стоят режимы "Сервер, Тонкий клиент и Web-клиент".
Но при выполнении проверок проекта в окне "Ошибки конфигурации" выдаются и ошибки других режимов, например, режима "Толстый клиент (управляемое приложение)", что вводит меня в заблуждение и отвлекает мои ресурсы на поиск действительно тех ошибок среди этого списка, на которые стоит обратить внимание. 

### Описание решения проблемы

Предлагаю сделать, чтобы в окне "Ошибки конфигурации" отображались ошибки с учетом тех режимов проверки, которые выбраны для проекта.

### Дополнительная информация

Версия 1С:EDT
Ruby 2021.2.10
Платформа 8.3.19.1264

**Comment by RedMammoth** [comment]
А есть пример ошибок Толстого клиента?  У меня тоже настроен сервер, тонкий и веб и лишних ошибок не выводит

**Comment by RedMammoth** [comment]
Файл .settings/ManagedEnvironment.prefs есть? После очистки проекта лишние ошибки не уходят? 
В чате был как-то похожий случай, не было файлов prefs: https://t.me/e1c_edt/32828

**Comment by alex7six** [comment]
Очистка проекта не помогла. Указанный вами файл не появился. Менять режим запуск на файловый вариант это вообще не решение.
Вот скрин ошибок 
![image](https://user-images.githubusercontent.com/48689795/146970656-b56f06c0-ca6e-4733-8752-e4aee453fc30.png)

**Comment by RedMammoth** [comment]
Не знаю почему файлов нет, не ловил такого поведения. Если получится создать воспроизводимый случай будет полезно, т.к. видимо не только у вас такое случается. Я бы попробовал переключить временно на файл-сервер, применить, и вернуть на клиент-сервер, м.б. сработает условие и файлы настроек создадутся.

На всякий случай прилагаю файлы с настройками
[settings.zip](https://github.com/1C-Company/1c-edt-issues/files/7757120/settings.zip)

**Comment by alex7six** [comment]
Нажатие  команды "Применить и закрыть" с подтверждением действий помогло решить проблему и файл settings/ManagedEnvironment.prefs создался.
Спасибо за помощь!
