### ISSUE TITLE
Ошибка при экспорте проекта в базу

### ISSUE THREAD

**Issue by hamec** [1C-Company/1c-edt-issues#21]
## Опишите ошибку

После импорта расширения при попытке экспорта в информационную базу появляется ошибка.
Обходится добавлением значения перечисления в расширение.

## Скриншоты

![image](https://user-images.githubusercontent.com/25643488/139496713-47302644-74aa-4f6d-9565-bfaa4a6d8de8.png)

## Лог рабочей области

[log.txt](https://github.com/1C-Company/1c-edt-issues/files/7444700/log.txt)
[trace.log](https://github.com/1C-Company/1c-edt-issues/files/7444702/trace.log)

## Окружение:

- OS: 'Windows 10'
- Версия 1C:Code-Style-V8 '0.1.0.130'
- Версия 1C:EDT '2021.2.8'
- конфигурация ERP 2.4
- платформа 8.3.17.

**Comment by tretyakevich** [comment]
Для воспроизведения необходимы:
1. Расширение (можно урезанное до целевого перечисления и/или зависимых объектов так, чтобы ошибка повторялась).
2. В случае невозможности передачи но понимания процесса воспроизведения на отдельном расширении - шаги для создания/воспроизведения и/или короткую демо-конфигурацию + расширение или только расширение)

**Comment by vadimeg** [comment]
@hamec Нужен репродьюсер! Конфигурацию (или ссылку на нее) и расширение. Конфигурация из #20 ISSUE20-21.zip, хоть и содержит в имени номера 20 и 21, но по факту там форма только для задачи #20.
Enum отсутствует

**Comment by Fedorov-Ivan** [comment]
@vadimeg не получается там воспроизвести это. Основную конфигурацию + расширение(там где и воспроизводится) не могу предоставить.

**Comment by Fedorov-Ivan** [comment]
+ эта ошибка встречается и в отношении предопределенных ПВХ (которые не добавлены в расширение)

**Comment by vadimeg** [comment]
Требуется доп.информация. См. https://github.com/1C-Company/1c-edt-issues/issues/21#issuecomment-955883165

**Comment by hamec** [comment]
Извините за долгий ответ. Прилагаю расширение, в теории наверное можно взять конфигурацию ERP 2.4. Для воспроизведения пришлось из расширения удалить значения перечисления "ТипыКомиссийЗаБанковскийПеревод"
![image](https://user-images.githubusercontent.com/25643488/140624253-b5a8dc7e-eadf-4738-b196-21cb485e6f2a.png)
[ext_test.zip](https://github.com/1C-Company/1c-edt-issues/files/7491268/ext_test.zip)

**Comment by vadimeg** [comment]
Исправлено в мастере 2021.3
