### ISSUE TITLE
Ошибки при работе с типом СтрокиДинамическогоСписка

### ISSUE THREAD

**Issue by DmitryShvaika** [1C-Company/1c-edt-issues#233]
### Описание ошибки

Edt рассматривает переменную этого типа как коллекцию переменных типа СтрокаДинамическогоСписка. Однако в действительности это не так. Как и написано в справочной информации (из конфигуратора):
```
При обходе выбираются значения типа КлючИЗначение, где Ключ - ключ строки, Значение - СтрокаДинамическогоСписка.
Возможно обращение к значению элемента коллекции посредством оператора [...]. В качестве аргумента передается ключ строки.

```
Справочная информация в edt имеет неточное описание типа. Просьба исправить - сделать как в конфигураторе.
Справочная информация конфигуратора:
![image](https://user-images.githubusercontent.com/54451084/147979269-2d826de1-15b8-4e6c-a38c-e02d20b4bffd.png)

Справочная информация edt:
![image](https://user-images.githubusercontent.com/54451084/147979310-bc3a84b5-be73-47a9-b790-7a4da7c92f44.png)

Однако некорректная не только справка. Сам тип в Edt интерпретируется так же неправильно.
![image](https://user-images.githubusercontent.com/54451084/147979407-6bbcd545-696e-46bb-aad7-adeae374939e.png)
Но при инспектировании переменной во время отладки показывает совсем другое (правильное значение):
![image](https://user-images.githubusercontent.com/54451084/147979961-87175821-8ef7-48d9-a6a0-cde7135cd77e.png)
Контекстная подсказка так же выдается ошибочная
![image](https://user-images.githubusercontent.com/54451084/147980860-d1059566-85f6-4589-b22f-0ace093e7a0b.png)

### Как воспроизвести

1. Создайте событие ПриПолученииДанныхНаСервере для любого Динамического списка
2. Введите код
```
	Для Каждого КлючИЗначение Из Строки Цикл
		
		а = КлючИЗначение.Значение;
		
	КонецЦикла
```
3. Наблюдайте ошибку

### Ожидаемое поведение

КлючИЗначение в данном примере должна распознаваться как описано в справке конфигуратора как КлючИЗначение.

### Лог рабочей области

[лог.zip](https://github.com/1C-Company/1c-edt-issues/files/7804002/default.zip)

### Версия 1С:EDT

Ruby 2021.3.0

### Операционная система

Windows

### Установленные плагины

1C:Code style V8

### Дополнительная информация

SSL плагин деинсталлирован
Дополнительно прилагаю:
Архив рабочей области проекта с примером
[EDT-test.zip](https://github.com/1C-Company/1c-edt-issues/files/7804007/EDT-test.zip)
архив выгрузки информационной базы с примером
[test.zip](https://github.com/1C-Company/1c-edt-issues/files/7804012/test.zip)

**Comment by MaksimDzyuba** [comment]
Здравствуйте, решено в 2023.3, в рамках ошибки https://github.com/1C-Company/1c-edt-issues/issues/869.
