### ISSUE TITLE
Зависание процесса слияния веток

### ISSUE THREAD

**Issue by shcherbakov-vadim** [1C-Company/1c-edt-issues#234]
### Описание ошибки

Процесс слиятия веток зависает на этапе "Проверка настроек объединения"

### Как воспроизвести

Сценария нет. Выполнялось слияние с несколькими удаленными ветками и на очередной зависание.
![2022-01-04_12-29-02](https://user-images.githubusercontent.com/52153345/148038092-42e44868-9ee5-47e6-8e0e-92c8d85c66f7.png)
Перезапуск EDT не помогает
В EDT 2021.2.10 проблема не воспроизводится

### Ожидаемое поведение

Слияние должно завершаться без проблем

### Лог рабочей области

[log.log](https://github.com/1C-Company/1c-edt-issues/files/7815983/log.log)
[trace.log](https://github.com/1C-Company/1c-edt-issues/files/7815984/trace.log)

### Версия 1С:EDT

2021.3.0

### Операционная система

Windows

### Дополнительная информация

[jstack.txt](https://github.com/1C-Company/1c-edt-issues/files/7806656/jstack.txt)

**Comment by vadimeg** [comment]
Сделал critical по просьбе автора

**Comment by AlmazNasibullin** [comment]
@shcherbakov-vadim Можете полный лог добавить, пожалуйста?
Проблема стабильно воспроизводится на одних и тех же коммитах?
При выполнении слиянии открывался редактор сравнения/объединения?
В момент запуска объединения какие-то активные процессы отображались в прогресс-баре?
Какие Вы делали действия непосредственно до запуска объединения?

**Comment by dimjmur** [comment]
Аналогичная ситуация при выполнении объединения веток
- Стабильно воспроизводится при на одних и тех же коммитах.
- редактор сравнения/объединения не открывался
- см. скрин
- запустил ЕДТ и начал объединение. После нескольких неудачных попыток.
![src_merge](https://user-images.githubusercontent.com/47595842/148231304-b3c1cf75-9ed9-408c-963b-725fd2306d59.png)
Версия 1С:EDT
2021.3.0

Операционная система
Windows

Установленные плагины
No response

Дополнительная информация
[log.txt](https://github.com/1C-Company/1c-edt-issues/files/7815458/log.txt)
[threaddump.txt](https://github.com/1C-Company/1c-edt-issues/files/7815460/threaddump.txt)

Дамп памяти, при необходимости, выложу

**Comment by shcherbakov-vadim** [comment]
> @shcherbakov-vadim Можете полный лог добавить, пожалуйста? 

Добавил
> Проблема стабильно воспроизводится на одних и тех же коммитах? 

Да
> При выполнении слиянии открывался редактор сравнения/объединения? 

Нет
> В момент запуска объединения какие-то активные процессы отображались в прогресс-баре? 

Не было никаких процессов
> Какие Вы делали действия непосредственно до запуска объединения?

Никаких

**Comment by Desar14** [comment]
Подтверждаю, так же словил на операции "Слить" с другой веткой. 2021.3.0, редактор не открывался (и в параметрах не стоит, чтобы открывался).
[log.log](https://github.com/1C-Company/1c-edt-issues/files/7837142/log.log)
[threaddump.txt](https://github.com/1C-Company/1c-edt-issues/files/7837143/threaddump.txt)
[trace.log](https://github.com/1C-Company/1c-edt-issues/files/7837144/trace.log)

**Comment by AlmazNasibullin** [comment]
@shcherbakov-vadim , @dimjmur , @Desar14 Коллеги, всем спасибо! Проблему воспроизвели, постараемся оперативно исправить ее.

**Comment by tormozit** [comment]
Столкнулся сегодня с этой бедой 
![изображение](https://user-images.githubusercontent.com/11896251/148898941-bfc8e176-cf01-4bd2-a28b-5a7bb3bb55b0.png)

**Comment by Dajigin** [comment]
> 

Спасибо! Установка флажка помогла.

**Comment by AlmazNasibullin** [comment]
Исправлена в 2021.3.1.
