### ISSUE TITLE
Зависает расширенная проверка языковых данных 

### ISSUE THREAD

**Issue by unichkin** [1C-Company/1c-edt-issues#235]
### Описание ошибки

После сборки конфигурации начинается эта проверка. Всякий раз зависает на предпоследнем элементе, см. скриншт
![image](https://user-images.githubusercontent.com/10799597/148389169-db5ddd6a-8f59-4cfe-afc7-75cea9986bf4.png)

### Как воспроизвести

Возникает после сборки проекта, Ruby 2021.2.12, 8.3.17.2306

### Ожидаемое поведение

Не понимаю, зачем эта проверка нужна в принципе, что она делает. Если это про мультиязычность - возможно стоит научить систему ее отключать, для конфигураций только на русском языке.

### Лог рабочей области

[doc_2022-01-06_16-24-22.metadata.zip](https://github.com/1C-Company/1c-edt-issues/files/7822076/doc_2022-01-06_16-24-22.metadata.zip)

### Версия 1С:EDT

2021.2.12

### Операционная система

Windows

### Установленные плагины

Другие сторонние плагины `Название плагина...`

**Comment by marmyshev** [comment]
@vadimeg  @tretyakevich  тут у пользователей не понимание - "проверка языковых данных" - никак не ассоциируется с тем что это "проверка кода модулей" - предлагаю переименовать 😁

**Comment by tretyakevich** [comment]
Данная проверка не зависает, есть несколько модулей в типовых конфигурациях повышенной связности, которые требуют значительного (порядка 10 минут) времени проверки. Работа над оптимизацией процесса проверки ведется.
Проверка может быть прервана в любой момент при начале работы пользователя с UI EDT, никаких специфичных действий/проблем длительная проверка "последнего" модуля не приносит.

**Comment by unichkin** [comment]
Это не типовая конфигурация, и все библиотеки на замке
