### ISSUE TITLE
Очистка обработчиков событий в элементах формы расширения при загрузке в ИБ

### ISSUE THREAD

**Issue by EChudnovsky** [1C-Company/1c-edt-issues#243]
### Описание ошибки

Назначенные обработчики элементов формы в проекте EDT расширения при синхронизации с ИБ не передаются или очищаются если были ранее назначены в конфигураторе.

### Скриншоты

![изображение](https://user-images.githubusercontent.com/5530435/148841777-f9f7c0f4-fb6d-4ed1-b05d-f512f29df0cf.png)

### Ожидаемое поведение

Назначенные обработчики в EDT должны корректно синхронизироваться с конфигурацией ИБ.

### Лог рабочей области

[log.log](https://github.com/1C-Company/1c-edt-issues/files/7841981/log.log)

### Версия 1С:EDT

Ruby 2021.3.0

### Операционная система

Windows

### Установленные плагины

1C:Code style V8, 1C:SSL-support

### Дополнительная информация

Платформа 1С x86_64 8.3.19.1417

**Comment by vadimeg** [comment]
Исправлено в 2021.3.2

**Comment by antonchev** [comment]
Ошибка актуальна на версии 1CEDT (2021.3.4+10), после обновления ИБ в расширениях слетели обработчики событий.
Так же, при выгрузке проекта утилитой ring, в исходниках пропадают события
