### ISSUE TITLE
Ошибка при открытии макета табличного документа после восстановления из снимка метаданных

### ISSUE THREAD

**Issue by shcherbakov-vadim** [1C-Company/1c-edt-issues#249]
### Описание ошибки

При восстановлении макета из снимка метаданных перестают открываться все макеты табличных документов конфигурации.
Перезапуск EDT не помогает. Помогает либо модификация файла макета в текстовом редакторе либо очистка проекта.

### Как воспроизвести

1. Создать новый проект версии 8.3.18
2. Загрузить в него типовую конфигурацию 1С:ERP
3. Создать репозитарий и настроить сохранение снимков для всех веток
4. Создать ветку task
5. Добиться того чтобы создался снимок для ветки master и переключиться на восстановленную из снимка модель данных для нее.
6. Попробовать открыть общий макет ПФ_MXL_Т1

### Скриншоты

![2022-01-12_09-49-38](https://user-images.githubusercontent.com/52153345/149078205-3815e6cc-66f3-4960-a300-ec2ee19270fe.png)

### Ожидаемое поведение

Макеты должны открываться

### Лог рабочей области

[log.zip](https://github.com/1C-Company/1c-edt-issues/files/7852316/log.zip)

### Версия 1С:EDT

2021.3.0

### Операционная система

Windows

**Comment by MaksimDzyuba** [comment]
Здравствуйте, да, удалось воспроизвести, спасибо!

**Comment by sergeysuvorov** [comment]
Исправление войдет в 2021.3.3.

**Comment by MaksimDzyuba** [comment]
исправление вышло, если продолжает воспроизводится, то просьба переоткрыть ошибку
