### ISSUE TITLE
Edt не видит битые ссылки в общих реквизитах

### ISSUE THREAD

**Issue by DmitryShvaika** [1C-Company/1c-edt-issues#250]
### Описание ошибки

Есть битая ссылка в общем реквизите и проверка в конфигураторе на некорректные ссылки ее видит. Выдается ошибка:
ОбщийРеквизит.ОбщийРеквизит1.Состав Неразрешимые ссылки на объекты метаданных (1)
Однако Edt не видит никаких проблем в проекте.

### Как воспроизвести

1. Создайте новую конфигурацию в конфигураторе
2. Создайте новый общий реквизит
3. Создайте регистр сведений
4. Добавьте регистр сведений в состав общего реквизита
5. Сохраните конфигурацию, если она изменена
6. Удалите регистр сведений
7. Выполните проверку конфигурации с флажком Поиск некорректных ссылок, чтобы убедится, что ошибка в наличии
8. Загрузите проект из этой информационной базы - Edt не увидит ошибки

### Ожидаемое поведение

Edt должен видеть некорректную ссылку и давать возможность удалить ее

### Лог рабочей области

[логи.zip](https://github.com/1C-Company/1c-edt-issues/files/7852691/default.zip)

### Версия 1С:EDT

Ruby 2021.2.12

### Операционная система

Windows

### Установленные плагины

1C:Code style V8

### Дополнительная информация

проект с битой ссылкой
[EDT-test.zip](https://github.com/1C-Company/1c-edt-issues/files/7852694/EDT-test.zip)

выгрузка информационной базы с тестовым примером
[test.zip](https://github.com/1C-Company/1c-edt-issues/files/7852699/test.zip)

**Comment by RedMammoth** [comment]
Это таже самая задача? https://github.com/1C-Company/dt-project-checks/issues/1

**Comment by DmitryShvaika** [comment]
Да, та же. Все думал - вроде писал - куда делась :) Спасибо. Оказывается новый проект завели.
Закрываю тогда эту задачу
