### ISSUE TITLE
При завершении очистки проекта все вызовы функций из других модулей отображаются как ошибочные и не работает переход к ним

### ISSUE THREAD

**Issue by shcherbakov-vadim** [1C-Company/1c-edt-issues#251]
### Описание ошибки

Является продолжением #249
При завершении очистки проекта все вызовы функций из других модулей отображаются как ошибочные и не работает переход к ним.
Помогает только удаление содержимого каталога .metadata\.plugins\com._1c.g5.v8.dt.bsl и повторная очистка проекта.

### Как воспроизвести

1. Создать новый проект версии 8.3.18
2. Загрузить в него типовую конфигурацию 1С:ERP
3. Создать репозитарий и настроить сохранение снимков для всех веток
4. Создать ветку task
5. Добиться того чтобы создался снимок для ветки master и переключиться на восстановленную из снимка модель данных для нее.
6. Запустить очистку проекта

### Скриншоты

![2022-01-12_11-24-27](https://user-images.githubusercontent.com/52153345/149090937-17da02d9-34a4-4675-bafe-46e05d964d50.png)

### Ожидаемое поведение

Корректное отображение ошибок и корректный переход по ссылкам

### Лог рабочей области

нет

### Версия 1С:EDT

2021.3.0

### Операционная система

Windows

**Comment by MaksimDzyuba** [comment]
Здравствуйте, воспроизвел, вроде нашел проблему, поправил, спасибо, как будет фикс, напишу в какую версию войдет, надеюсь, что в ближайшую

**Comment by RedMammoth** [comment]
@MaksimDzyuba вчера обновил плагин code-style, на версию 0.2.0.v20220214-1824. Массово посыпались ошибки dynamic-access-method-not-found, удаление каталога и переочистка не помогает, помогает зайти в модуль добавить/удалить строку и сохранить
(EDT Ruby 2021.3.1)

**Comment by MaksimDzyuba** [comment]
@RedMammoth а можно пример, ну то есть на каких свойствах или методах, на общих модулях? если на них, то это продолжение похоже вот этой ошибки

**Comment by RedMammoth** [comment]
> @RedMammoth а можно пример, ну то есть на каких свойствах или методах, на общих модулях? если на них, то это продолжение похоже вот этой ошибки

Пробежался бегло, вижу модуль менеджера документа, общие модули, модуль менеджера перечисления, модуль менеджера регистра сведений. На свойствах вроде не ругается, пока не видел. А вот на методы везде

**Comment by RedMammoth** [comment]
Еще нашел модуль объекта (справочник) с экспортной переменной. Создал СправочникОбъект - реквизиты видны, а переменная нет

**Comment by MaksimDzyuba** [comment]
да, это описываемая проблема

**Comment by motivix** [comment]
Что делать-то теперь? Всё поломалось.

**Comment by Desar14** [comment]
> Что делать-то теперь? Всё поломалось.

Реимпорт конфы, либо удаление файлика из описания ошибки и повторная очистка.

**Comment by motivix** [comment]
> > Что делать-то теперь? Всё поломалось.
> 
> Реимпорт конфы, либо удаление файлика из описания ошибки и повторная очистка.

А если версию EDT понизить без удаления проекта? Возможно такое вообще?  А то все закладки и задачи слетят.

**Comment by Desar14** [comment]
в 2021.3.2 проблема актуальна.

**Comment by MaksimDzyuba** [comment]
Здравствуйте, скажите, а Вы используете снимки объектов метаданных, потому что в описанном сценарии, при работе с ними, нам не удается воспроизвести

**Comment by Desar14** [comment]
Нет, снимки метаданных отключены. Собственно, и на предыдущих версиях я работал без них, т.к. переключение веток без них быстрее происходит.

**Comment by MaksimDzyuba** [comment]
Тогда это что-то другое, можете чуть подробностей рассказать, просто делаете очистку проекта, или в какой момент пропадают типы, сколько проектов в рабочей области и какие они

**Comment by Desar14** [comment]
Добрый день. 2021.3.2, проекты были в нормальном состоянии, никаких переключений веток. Выполнил очистку всех проектов - вызовы методов сломались.
[trace.log](https://github.com/1C-Company/1c-edt-issues/files/8122729/trace.log)
[log.log](https://github.com/1C-Company/1c-edt-issues/files/8122730/log.log)

**Comment by MaksimDzyuba** [comment]
Здравствуйте, воспроизвели, поправили, фикс будет только в 2022.1, к сожалению. Пока можно просто чистить только основные проекты по одному, зависимые дочерние проекты автоматически почистятся. Извините за неудобства.

**Comment by MaksimDzyuba** [comment]
Здравствуйте, актуальна ли еще ошибка,вроде должна уйти проблема, просьба подтвердить

**Comment by Desar14** [comment]
Добрый день, да, починилось и очистка нескольких проектов сразу работает корректно.

**Comment by MaksimDzyuba** [comment]
Спасибо за быстрый ответ!
Ошибку закрываю
