### ISSUE TITLE
В сложной форме, при добавлении / изменении реквизита, моментально съедается вся память и EDT зависает

### ISSUE THREAD

**Issue by OlegKnysh1977** [1C-Company/1c-edt-issues#254]
### Описание ошибки

В сложной форме, при добавлении / изменении реквизита, моментально съедается вся память, причем, все ядра процессора загружены на 100%. Очистка проекта ничего не дает: форма открывается - меняю реквизит - съедается вся память - снимаю едт - форма открывается пустой - очищаю проект - форма открывается... (по кругу)

---------
!ENTRY com._1c.g5.v8.internal.resourcemanagement.ResourceManagementPlugin 2 0 2022-01-12 15:03:02.393
!MESSAGE System overload (cpu and/or memory): memory 4292674384 used of 4294967296

!ENTRY org.eclipse.core.jobs 4 2 2022-01-12 15:03:02.393
!MESSAGE Unhandled error
!STACK 0
java.lang.OutOfMemoryError: Java heap space
	at java.base/java.util.HashMap.newNode(HashMap.java:1815)
---------

Увеличение памяти с ключом -Xmx8g (с 4 Гб до 8 Гб) ничего не дает - 8 Гб так же моментально съедаются (видимо, идут какие-то утечки памяти).

### Как воспроизвести

1. Открываю форму
2. Добавляю какой-нибудь элемент на форму
3. EDT зависла

### Ожидаемое поведение

Редактор форм должен нормально работать

### Лог рабочей области

[log.zip](https://github.com/1C-Company/1c-edt-issues/files/7855785/log.zip)

### Версия 1С:EDT

1CEDT (2021.3.0+582)

### Операционная система

Windows

### Дополнительная информация

[Form.zip](https://github.com/1C-Company/1c-edt-issues/files/7855779/Form.zip)

**Comment by vadimeg** [comment]
Виртуальная машина Java работает в клиентском режиме. Это может быть причиной. Переключитесь в рекомендованный серверный режим.
https://its.1c.ru/db/edtdoc#content:40:hdoc

**Comment by vadimeg** [comment]
С учетом рекомендаций выше, актуальна ли еще проблема или можно закрывать?

**Comment by OlegKnysh1977** [comment]
Спасибо. Проблема не актуальна. В серверный режим переключаться бесполезно, т.к. на сервере оперативной памяти еще меньше, чем на моей машине.

**Comment by RedMammoth** [comment]
> Спасибо. Проблема не актуальна. В серверный режим переключаться бесполезно, т.к. на сервере оперативной памяти еще меньше, чем на моей машине.

Серверный режим для Java включается на вашей же машине
