### ISSUE TITLE
Реквизиты с типом Характеристика.<имя характеристики> не добавляются на форму

### ISSUE THREAD

**Issue by shcherbakov-vadim** [1C-Company/1c-edt-issues#255]
### Описание ошибки

Если на форме есть реквизит с типом Характеристика.<имя характеристики>, он не добавляется на форму.
В версии 2021.2.10 проблемы нет.

### Как воспроизвести

1. Создать реквизит формы с типом Характерстика.<имя характеристики>
2. Убедиться, что его нельзя добавить на форму

### Скриншоты

![2022-01-13_13-28-28](https://user-images.githubusercontent.com/52153345/149313170-3da1ed0c-8006-4b5c-a029-f55dafa7f1c1.png)

### Ожидаемое поведение

Реквизит должен добавляться на форму

### Лог рабочей области

нет

### Версия 1С:EDT

2021.3.0

### Операционная система

Windows

**Comment by vadimeg** [comment]
Исправлено в исправительном релизе 2021.3
