### ISSUE TITLE
Не пропадает ошибка "метод с таким именем отсутствует в модуле формы" 

### ISSUE THREAD

**Issue by SeiOkami** [1C-Company/1c-edt-issues#264]
### Описание ошибки

В форме добавляем обработчик события. И вырезаем процедуру этого обработчика. Появляется ошибка. Пример:
_Для события "ПриИзменении" элемента формы "Пользователь" назначен обработчик "ПользовательПриИзменении", но метод с таким именем отсутствует в модуле формы_
Но если вернуть процедуру, то ошибка не пропадает. При этом, при переходе в конструкторе формы на это событие процедура позиционируется корректно, а значит определяется. Но ошибка не пропадает, пока не удалить привязку в списке событий и не добавить заново.

### Как воспроизвести

1. В редакторе формы создать обработчик события
2. Вырезать код процедуры обработчика. Появится ошибка
3. Вставить код процедуры обработчика. Ошибка не пропадает.
4. Сохранить форму, переоткрыть. Ошибка не пропадает

### Скриншоты

https://youtu.be/XOAnCCIj_OY

### Ожидаемое поведение

Ошибка должна пропадать

### Лог рабочей области

[log.txt](https://github.com/1C-Company/1c-edt-issues/files/7875570/log.txt)
[trace.log](https://github.com/1C-Company/1c-edt-issues/files/7875571/trace.log)

### Версия 1С:EDT

Ruby 2021.2.10

### Операционная система

Windows

### Установленные плагины

1C:Code style V8

**Comment by SeiOkami** [comment]
Сейчас работаю и просто при каждом создании обработчика сразу же выпадает ошибка, что метод не назначен.
И нужно каждый раз делать так:
1. Создал обработчик
2. Отключил от события
3. Подключил заново

**Comment by vadimeg** [comment]
Исправлено в 2022.1
