### ISSUE TITLE
Проверка на пустые области и V8CodeStyle

### ISSUE THREAD

**Issue by SeiOkami** [1C-Company/1c-edt-issues#277]
### Описание проблемы

При наличии плагина [V8CodeStyle](https://its.1c.ru/db/edtplugins#bookmark:v8codestyle:V8CodeStyle) при каждом создании нового объекта метаданных (или формы) автоматически генерируются пустые стандартные области.
И сразу же EDT выводит их в списке предупреждений с описанием "Область пустая"
В итоге нужно либо сразу наполнять все области кодом, либо чистить их.
Работаешь, создаешь объекты и формы. А потом ходишь по всем областям и чистишь их)

### Описание решения проблемы

Не создавать области автоматически. 
Предлагать их создание в интерфейсе. 
Когда пишешь какой-то метод вне областей предлагать перенести его в одну из созданных (или сгенерировать стандартную).
Тогда можно просто писать метод, а потом в несколько кликов переложить в его в одну из созданных областей. Или же выбрать предложенный вариант стандартной области. Которая автоматически сгенерируется и в неё перенесётся метод.

**Comment by RedMammoth** [comment]
Настройка есть, если она у вас выключена и области создаются, возможно она не всегда работает
![image](https://user-images.githubusercontent.com/64589646/149769701-9e33c234-a3d2-4529-a291-bd2b874f9b5c.png)

У плагина v8 code-style отдельный [репозиторий](https://github.com/1C-Company/v8-code-style), думаю лучше ошибку регистрировать там, если очевидно, что к нему относится

**Comment by SeiOkami** [comment]
Спасибо, отправлю на отдельный репозиторий
