### ISSUE TITLE
Редактор формы не задает вопрос об удалении связанных элементов

### ISSUE THREAD

**Issue by SeiOkami** [1C-Company/1c-edt-issues#281]
### Описание ошибки

В ряде случаем редактор формы при удалении реквизита не задает вопрос об удалении связанных элементов. Элементы остаются на форме и разработчик может даже не заметить этого.

На видео демонстрация

### Как воспроизвести

1. Добавить реквизит с ссылкой на справочник
2. Вынести на форму реквизит "Наименование" этого реквизита
3. Удалить реквизит формы
4. Вопрос не будет задан и элемент так и останется на форме

### Скриншоты

https://www.youtube.com/watch?v=K3AJb-yr29I

### Ожидаемое поведение

Задается вопрос о удалении связанных элементов

### Лог рабочей области

[trace.log](https://github.com/1C-Company/1c-edt-issues/files/7882050/trace.log)
[log.txt](https://github.com/1C-Company/1c-edt-issues/files/7882052/log.txt)

### Версия 1С:EDT

Ruby 2021.2.10

### Операционная система

Windows

### Установленные плагины

1C:Code style V8

**Comment by vadimeg** [comment]
Исправлено в 2022.2

**Comment by vadimeg** [comment]
> Задача в майлстоуне 2022.1, исправление все-таки будет в 22.1 или 22.2?

Поменял майлстоун. Исправление сейчас в 2022.2. Если будет принято решение о переносе в 2022.1, то войдет в следующий исправительный релиз 2022.1
