### ISSUE TITLE
Не задан синоним стандартного реквизита Родитель

### ISSUE THREAD

**Issue by SeiOkami** [1C-Company/1c-edt-issues#283]
### Описание ошибки

Если сделать справочник иерархическим, то после очистки проекта появляется новое предупредждение, что "Не задан синоним у стандартного реквизита Родитель"

### Как воспроизвести

1. Добавить новый справочник
2. Сделать его иерархическим
3. Очистить проект
4. Лицезреть ошибку

### Скриншоты

https://www.youtube.com/watch?v=OnvzdrJGjIA

### Ожидаемое поведение

Выходит сразу две ошибки.
1. Предупреждение должно появляться сразу, а не после очистки.
2. Синоним должен автоматически заполняться самой EDT или же не должно быть вообще такой проверки (для 1С это не ошибка, а обычная практика)

### Лог рабочей области

[trace.log](https://github.com/1C-Company/1c-edt-issues/files/7882638/trace.log)
[log.txt](https://github.com/1C-Company/1c-edt-issues/files/7882639/log.txt)

### Версия 1С:EDT

Ruby 2021.2.10

### Операционная система

Windows

### Установленные плагины

1C:Code style V8

**Comment by RedMammoth** [comment]
https://its.1c.ru/db/v8std#content:474:hdoc

Это тоже к v8 code style относится

**Comment by marmyshev** [comment]
> Предупреждение должно появляться сразу, а не после очистки.

Это в v8 code style - это ошибка проверки.

> Синоним должен автоматически заполняться самой EDT или же не должно быть вообще такой проверки 

А чем он должен заполняться? (если вы читали и поняли смысл стандарта) Вы предлагаете чтобы EDT за вас догадалась что в вашем случае означает техногенный термин "родитель" и прописала его объяснение (например: каталог, группа товаров, и т.д.). 

Можно тут сразу писать нейросеть типа Tab-Nine 😁 только для 1С синонимов))

> (для 1С это не ошибка, а обычная практика)

Да, это порочная практика, и стандарт призван её искоренять))

**Comment by SeiOkami** [comment]
Да, согласен. Если есть такой стандарт, тот вполне логично, что синоним задавать должен разработчик вручную. 

Странно тогда только то, что ошибка появляется только после очистки проекта. Но это тогда отдельный ишуиз
