### ISSUE TITLE
Не работает подавление проверок

### ISSUE THREAD

**Issue by SeiOkami** [1C-Company/1c-edt-issues#284]
### Описание ошибки

Не работает подавление ошибок (или не полностью работает)

### Как воспроизвести

1. Добавить новую обработку
2. В модуле объекта написать `А = Новый Структура("А,Б,В,Г,Д")`
3. Появится ошибка по количеству ключей в конструкторе структуры
4. Установить правила подавления
5. Ошибка не пропадает
6. Очистить проект
7. Ошибка не пропадает
8. Очистить все проекты
9. Ошибка не пропадает
10. Перезайти
11. Ошибка не пропадает

### Скриншоты

https://www.youtube.com/watch?v=Eu-SiOzg8RY

### Ожидаемое поведение

Корректная работа подавления ошибок

### Лог рабочей области

[log.txt](https://github.com/1C-Company/1c-edt-issues/files/7882751/log.txt)
[trace.log](https://github.com/1C-Company/1c-edt-issues/files/7882752/trace.log)

### Версия 1С:EDT

Ruby 2021.2.10

### Операционная система

Windows

### Установленные плагины

1C:Code style V8

**Comment by vadimeg** [comment]
Исправлено в 2022.1
