### ISSUE TITLE
Перестает открываться окно редактирования типа реквизита формы

### ISSUE THREAD

**Issue by shcherbakov-vadim** [1C-Company/1c-edt-issues#290]
### Описание ошибки

В определенный момент перестает открываться окно редактирования типа реквизита формы.
Перезапуск EDT не помогает. Помогает очистка проекта.

### Как воспроизвести

Примера воспроизведения нет. Просто в определенный момент перестает работать.

### Ожидаемое поведение

Окно редактирования типа реквизита формы должно открываться

### Лог рабочей области

[error.log](https://github.com/1C-Company/1c-edt-issues/files/7896818/error.log)

### Версия 1С:EDT

2021.3.0

### Операционная система

Windows

**Comment by RedMammoth** [comment]
Здесь нет вашей ситуации? https://github.com/1C-Company/1c-edt-issues/issues/260

**Comment by shcherbakov-vadim** [comment]
> Здесь нет вашей ситуации? #260

В исключении есть фраза PROPERTY_PALETTE_ENGINE, но стек и комментарий совсем другой

**Comment by vadimeg** [comment]
Не удалось повторить. Нужны шаги для воспроизведения.

**Comment by vadimeg** [comment]
В 2022.2 была исправлена похожая ошибка с палитрой. Когда выйдет релиз, хорошо бы на нем проверить есть ли эта ошибка

**Comment by Erik773** [comment]
Задача закрыта из-за невозможности воспроизведения.
Если появится дополнительная информация, которая может способствовать воспроизведению проблемы, задачу можно переоткрыть.
