### ISSUE TITLE
Ошибочная валидация методов "ПолучитьЗаголовокКлиентскогоПриложения" и "УстановитьЗаголовокКлиентскогоПриложения" - 

### ISSUE THREAD

**Issue by tretyakevich** [1C-Company/1c-edt-issues#3]
Версия EDT: 2021.2.6
Версия платформы: 8.3.17

Методы "ПолучитьЗаголовокКлиентскогоПриложения" и "УстановитьЗаголовокКлиентскогоПриложения" - подсвечиваются красным "Процедура или функция не определена", хотя они есть и работают

**Comment by theshadowco** [comment]
Так вы не скрывайте их, а оформляйте зачеркнутым и добавляйте ошибку в лог с пояснением, что метод устарел. Для старых конфигураций чувствуешь себя идиотом - видишь код, он работает, но едт пишет, что метода нет!

**Comment by MaksimDzyuba** [comment]
Здравствуйте, поправил, войдет в 2023.3, постараюсь перенести в 2023.2. Спасибо!
![image](https://github.com/1C-Company/1c-edt-issues/assets/77277424/73a122c6-08fa-49be-bb67-0861923023b3)
