### ISSUE TITLE
Невозможно экспортировать проект в файлы с помощью утилиты ring

### ISSUE THREAD

**Issue by shcherbakov-vadim** [1C-Company/1c-edt-issues#30]
## Опишите ошибку

Для реализации CI проект обновляется из внешнего репозитария с помощью git pull, затем запускается следующая команда:

call ring edt@2021.1.7 workspace export --workspace-location %EDTWS% --project-name erpuh --configuration-files %EDTWS%\temp\export

Если было большое количество изменений - происходит обновление служебных данных рабочей области и процесс завершается с ошибкой:
[ERROR ] Системная ошибка: Timeout waiting for the state changing of the project: erpuh
Ошибка выполнения процесса 1C:Enterprise Development Tools.
По причине: Ошибка выполнения дочернего процесса.

В логе есть следующий фрагмент:
```
!ENTRY com._1c.g5.v8.dt.core 2 0 2021-10-22 11:19:05.733
!MESSAGE BM was not closed correctly

!ENTRY com._1c.g5.v8.dt.core 4 0 2021-10-22 11:26:05.747
!MESSAGE The state of the project 'erpuh' was not changed within 420 seconds.
1[IMPORT(complete)] 2[AFTER_SYNC_DD(waiting)] 3[BEFORE_BUILD_DD(waiting)] 4[BUILD(waiting) NORMAL_DD(waiting)] 5[AFTER_BUILD_DD(waiting)] Waiting operations: 'Export'
```
Приходится открывать рабочую область в EDT, дожидаться обновления служебных данных и запускать команду повторно.

## Ожидаемое поведение

Должна быть возможность изменить таймаут ожидания перестоения рабочей области при использовании утилиты ring

## Лог рабочей области

[timeout_error.log](https://github.com/1C-Company/1c-edt-issues/files/7451381/timeout_error.log)

## Окружение (пожалуйста укажите информацию):

- Версия 1C:EDT 2021.1.7
- ОС: Windows Server 2019 Standard 1809
- Процессор: 2 x E5-2690 v3, 128 Гб памяти

**Comment by tretyakevich** [comment]
1.  Нужны полные логи из рабочего пространства
2. Почему в информации edt@2021.1.7 1C:EDT 2021.2.6?
3. Также нужна конфигурация вашей рабочей машины (процессор, память, выделенная память под JVM данного процесса, диски).

**Comment by shcherbakov-vadim** [comment]
Добавил логи, исправил версию, добавил информацию об окружении
В edt.ini -Xmx4096m

**Comment by tretyakevich** [comment]
!ENTRY com._1c.g5.v8.dt.core 2 0 2021-11-01 13:16:53.677
!MESSAGE Waiting for permission to close project 'ЗУП' for already 5851 seconds.
Pipeline: 1[IMPORT(complete)] 2[AFTER_SYNC_DD(complete)] 3[BEFORE_BUILD_DD(complete)] 4[BUILD(complete) NORMAL_DD(complete)] 5[AFTER_BUILD_DD(running)]

Возможно связанная проблема - при повторном запуске (поочередном) - проблемы с закрытием проекта, идет полная проверка.

**Comment by shcherbakov-vadim** [comment]
Возникла новая ошибка на том же окружении, только в edt.ini -Xmx12g
[error_20211111.log](https://github.com/1C-Company/1c-edt-issues/files/7518420/error_20211111.log)
Вкупе с ошибкой https://github.com/1C-Company/1c-edt-issues/issues/31 это приводит к еще большим проблемам
