### ISSUE TITLE
Открывать файлы форм с помощью редактора

### ISSUE THREAD

**Issue by ilya2184** [1C-Company/1c-edt-issues#308]
### Описание проблемы

Некоторые ошибки, которые пока не понятно как появляются, хочется исправить с помощью текстового редактора

### Описание решения проблемы

Из контекстного меню - пункт Open with открывать:
Для форм объектов - файл формы (сейчас открывается файл родительского объекта)
Для схем компоновки - файл схемы компоновки (напр. для отчетов сейчас открывается файл отчета)

### Дополнительная информация

![image](https://user-images.githubusercontent.com/14931660/151055002-6d0a69ee-7e5a-465f-acfd-32908119af1c.png)

**Comment by marmyshev** [comment]
А чем не нравится из редактора формы ПКМ по заголовку - и также - Open with… открыть редактор xml формы?

при клике ПКМ по метаданному формы - открывается файл метаданного в xml (не удобно, но логично)

**Comment by RedMammoth** [comment]
> А чем не нравится из редактора формы ПКМ по заголовку - и также - Open with… открыть редактор xml формы?
> 
> при клике ПКМ по метаданному формы - открывается файл метаданного в xml (не удобно, но логично)

У меня там только закрыть и отсоединить, вроде всё перекликал. Это "обычная" едт, или запущенная в отладке?

**Comment by ilya2184** [comment]
> А чем не нравится из редактора формы ПКМ по заголовку - и также - Open with… открыть редактор xml формы?
Можно снимок экрана где? В заголовке окна редактора формы - нет.
![image](https://user-images.githubusercontent.com/14931660/151113592-bf756694-c424-41f1-a3e2-16264da8462a.png)
В подзаголовке окна редактора формы (1) - нет действия на ПКМ, в корневом элементе формы (2) и на заголовке формы (2) в редакторе - одинаковое меню - там нет Open with
![image](https://user-images.githubusercontent.com/14931660/151113884-04df5021-4ce3-4d90-ae91-197fab8e9006.png)

> при клике ПКМ по метаданному формы - открывается файл метаданного в xml (не удобно, но логично)
При ПКМ по метаданному - например документу - открывается редактор объекта - тот файл проекта описывающий метаданные документа - логично; при ПКМ по форме или по макету - открывается тот  же редактор объекта - метаданные документа;
На мой взгляд было бы логичным открывать другой файл проекта - для формы есть отдельный файл, для макета есть отдельный файл.

**Comment by marmyshev** [comment]
> А чем не нравится из редактора формы ПКМ по заголовку - и также - Open with… открыть редактор xml формы?

Не, какую-то дичь написал.  Если раньше и было такое (хотя может путаю?), то щас этого нет.

**Comment by tormozit** [comment]
Пока я пользуюсь следующей хитростью. Открываю файл в системном редакторе Notepad++. Затем сразу нажимаю кнопку открыть файл и выбор файла уже открывается в папке открытого в редакторе файла. 

![изображение](https://user-images.githubusercontent.com/11896251/177773079-a3737499-3962-456c-a448-710bbb6b12b8.png)

**Comment by NikitaMikhaylovSB** [comment]
> Пока я пользуюсь следующей хитростью. Открываю файл в системном редакторе Notepad++. Затем сразу нажимаю кнопку открыть файл и выбор файла уже открывается в папке открытого в редакторе файла.
Можно вызывать File- Open containing folder - Folder as Workspace
Тогда появляется панель с быстрым переходом между файлами.

Но хотелось бы реализации в EDT открытия файла по контексту, а не "главного"...

**Comment by tormozit** [comment]
@NikitaMikhaylovSB Не понял.

**Comment by vadimeg** [comment]
Исправлено в 2023.1
