### ISSUE TITLE
Не дает удалить элемент формы ТаблицаФормы ни через меню, ни кнопкой Del. Так же недоступны команды Переместить вверх, Переместить Вниз для ТаблицаФормы.

### ISSUE THREAD

**Issue by DmitryShvaika** [1C-Company/1c-edt-issues#316]
### Описание ошибки

Не дает удалить элемент формы ТаблицаФормы ни через меню, ни кнопкой Del. Так же недоступны команды Переместить вверх, Перемстить Вниз для ТаблицыФормы.

### Как воспроизвести

1. Создать таблицу формы на форме
2. Наблюдать ошибку

### Скриншоты

![image](https://user-images.githubusercontent.com/54451084/151131576-d0310dd4-3cbc-48d6-bc8d-f241f3ab28d3.png)

### Ожидаемое поведение

Должна быть возможность удалять и перемещать элемент.

### Лог рабочей области

[логи.zip](https://github.com/1C-Company/1c-edt-issues/files/7940171/default.zip)

### Версия 1С:EDT

Ruby 2021.3.1

### Операционная система

Windows

### Установленные плагины

1C:Code style V8

### Дополнительная информация

[EDT-test.zip](https://github.com/1C-Company/1c-edt-issues/files/7940179/EDT-test.zip)
прилагаю архив рабочей области вместе с тестовым проектом

**Comment by vadimeg** [comment]
Исправлено в 2021.3.2
