### ISSUE TITLE
При изменении расширения в конфигураторе EDT не предлагает синхронизировать изменения с проектом

### ISSUE THREAD

**Issue by RedMammoth** [1C-Company/1c-edt-issues#321]
### Описание ошибки

Если после синхронизации проектов с ИБ (статус ОК), открыть конфигуратор и внести изменения в расширении, а затем вернуться в EDT и запустить приложение/импортировать конфигурацию, то edt не видит изменений и запускает приложение/или (при импорте) говорит, что изменений нет.

Если в таком состоянии внести изменение в расширении в edt, то предложению по импорту изменений/перезаписи нет, а просто затираются изменения, сделанные в конфигураторе.

### Как воспроизвести

1. Импортировать проекты конфигурации и расширения в edt
2. Внести в edt изменения, обновить конфигурацию
3. Открыть конфигуратор, внести изменения в расширении, например, добавить новый справочник
4. Вернуться в EDT и запустить обновление конфигурации или запустить приложение в отладке - **EDT не сообщает об изменениях, не предлагает ничего импортировать**
5. Внести изменения в расширение в EDT и снова запустить обновление конфигурации или запустить отладку - **EDT не предлагает импортировать или перезаписать изменения, а просто затирает изменения. Например, если был добавлен справочник, то появляется окно об изменении структуры базы (удаление добавленного справочника), с кнопками принять/отменить**

### Ожидаемое поведение

Отслеживание внешних изменений в расширении работает аналогично с отслеживанием изменений проекта конфигурации

### Лог рабочей области

[log_and_trace.zip](https://github.com/1C-Company/1c-edt-issues/files/7945259/log_and_trace.zip)

### Версия 1С:EDT

2021.3.1

### Операционная система

Windows

### Установленные плагины

1C:Code style V8, 1C:SSL-support

**Comment by mrshadow300373** [comment]
А почему этот баг не помечен как критичный?
Я вот обновил конфигурацию поставщика, после этого открыл конфигуратор и проверил на применимость все расширения, так как в EDT такой возможности не нашёл. Привел в соответствие все методы "ИзменениеИКонтроль" Закрыл конфигуратор, попытался импортировать, получил вместо изменений "ничто". И как мне их как теперь переносить в проект?
Выгружать расширение в XML, конвертировать в EDT, затем сравнивать/объединять я уже даже и методов, которые правил не помню, чтобы копипастом их перенести из конфигуратора.

**Comment by RedMammoth** [comment]
@Erik773, добрый день! Есть возможность отметить данную ошибку как критическую? Она может привести к потере кода и в чате сообщества периодически встречаются упоминанию о данной проблеме

**Comment by nikolay-martynov** [comment]
Здравствуйте. Ожидаем завершения работ в платформе по следующим задачам:

- 60011499
- 60013092
- 60013093

**Comment by Xelgo** [comment]
Баг разве исправили? Точно такая же проблема на версии: Ruby 2023.3.6
1C 8.3.24.1368

**Comment by Erik773** [comment]
Здравствуйте @Xelgo!
Исправление бага будет доступно в версии 1C:EDT 2024.1 и версии платформы 8.3.24.1624.
