### ISSUE TITLE
Показывать более одного результата поиска в глобальном поиске

### ISSUE THREAD

**Issue by KovAlexey** [1C-Company/1c-edt-issues#327]
### Описание проблемы

Сейчас новый результат поиска замещается предыдущим.
Невозможно посмотреть два результата поиска вместе.

### Описание решения проблемы

Каждый поиск открывать в новой вкладке (Сделать это поведение настраиваемым).
![изображение](https://user-images.githubusercontent.com/16429518/151734575-79e21017-573d-413f-8a9b-17c7080233a5.png)

![изображение](https://user-images.githubusercontent.com/16429518/151734419-3b59974b-4df2-45cb-a85e-c418cfabcd27.png)

**Comment by marmyshev** [comment]
Сценарий работы немного по-другому, но при этом решает задачу:

1. Выполняете первый поиск чего бы то ни было...
2. Если результат хочется сохранить - "прикалываете" 📌 результат на доску (как пробковая доска, только виртуально 😁)
3. Запускаете новый поиск - в отдельном окне открывается.

Такая функция есть на многих панелях которые как-то зависят от какого-то контекста/действия.
