### ISSUE TITLE
Свойство "Только во "Все действия"" не влияет на отображение кнопки командной панели в редакторе форм.

### ISSUE THREAD

**Issue by DmitryShvaika** [1C-Company/1c-edt-issues#329]
### Описание ошибки

Свойство "Только во "Все действия"" не влияет на отображение кнопки командной панели в редакторе форм. В конфигураторе же работает правильно - при установке признака в значение "Да", кнопка исчезает с командной панели. 

### Как воспроизвести

1. Создать кнопку командной панели для любой команды
2. Установить свойство "Только во "Все действия"" в значение Да
3. Наблюдать ошибку

### Скриншоты

![image](https://user-images.githubusercontent.com/54451084/151769668-a2cee096-43f3-4d18-bdd4-a68b60db44f5.png)

### Ожидаемое поведение

Кнопка должна пропадать с командной панели и отображаться только во Все действия.

### Лог рабочей области

[лог.zip](https://github.com/1C-Company/1c-edt-issues/files/7969641/default.zip)

### Версия 1С:EDT

Ruby 2021.2.12

### Операционная система

Windows

### Установленные плагины

1C:Code style V8

### Дополнительная информация

архив рабочей области с тестовым проектом
[EDT-test.zip](https://github.com/1C-Company/1c-edt-issues/files/7969646/EDT-test.zip)

**Comment by vadimeg** [comment]
Такое поведение только для платформ 8.3.12 и старше. Для более новых платформ вообще нет такого свойства. Вместо него используется ПоложениеВКоманднойПанели, которое есть и в 12-й платформе, но не работает (в том числе и в конфигураторе). Чтобы исправить поведение свойства "Во все действия" для 12-й платформы может потребоваться достаточно много времени. Насколько это необходимо для проекта? Есть ли возможность перейти на более новую версию платформы?
Если наберется достаточное количество голосов, то можно будет поднять важность задачи для критической. Тогда вернемся к ней и попробуем исправить.

**Comment by DmitryShvaika** [comment]
> Такое поведение только для платформ 8.3.12 и старше. Для более новых платформ вообще нет такого свойства. Вместо него используется ПоложениеВКоманднойПанели, которое есть и в 12-й платформе, но не работает (в том числе и в конфигураторе). Чтобы исправить поведение свойства "Во все действия" для 12-й платформы может потребоваться достаточно много времени. Насколько это необходимо для проекта? Есть ли возможность перейти на более новую версию платформы? Если наберется достаточное количество голосов, то можно будет поднять важность задачи для критической. Тогда вернемся к ней и попробуем исправить.

Не критично - сие просто удобство.... можно даже закрыть задачу.

**Comment by vadimeg** [comment]
> можно даже закрыть задачу.

ок
