### ISSUE TITLE
Табличный документ. У добавляемой картинки не хватает свойств

### ISSUE THREAD

**Issue by AndreyDanilov-nn** [1C-Company/1c-edt-issues#334]
### Описание ошибки

В табличном документе у добавляемой картинки не хватает свойств `Картинка` и `РазмерКартинки`.

### Как воспроизвести

1. Создать табличный документ
2. Добавить картинку `Таблица - Рисунки - Картинка...`
3. Открыть свойства

### Скриншоты

![image](https://user-images.githubusercontent.com/53249626/151816783-6cb1d3b8-481d-4191-b09c-8bc87ed9d004.png)
![image](https://user-images.githubusercontent.com/53249626/151816802-0951d2a4-220f-4eb1-8fda-4ff7cccb15b5.png)

### Ожидаемое поведение

Состав свойств в edt аналогичен составу свойств в конфигураторе

### Лог рабочей области

[log.zip](https://github.com/1C-Company/1c-edt-issues/files/7971758/log.zip)

### Версия 1С:EDT

Ruby 2021.3.1 и предыдущие

### Операционная система

Windows

**Comment by wolfandw** [comment]
Исправлено в 2022.2.5
