### ISSUE TITLE
Во вложенном запросе не отображаются временные таблицы

### ISSUE THREAD

**Issue by AndreyDanilov-nn** [1C-Company/1c-edt-issues#335]
### Описание ошибки

Во вложенном запросе не отображаются временные таблицы

### Как воспроизвести

1. Создать пакет запроса, добавить во временную таблицу
2. Создать новый пакет запроса
3. Попытаться сделать отбор вложенным запросом в секции `ГДЕ` по данным временной таблицы из п.1

### Скриншоты

![image](https://user-images.githubusercontent.com/53249626/151820292-0b3af500-fa44-4329-a040-fbac5bd6a88b.png)
![image](https://user-images.githubusercontent.com/53249626/151820406-e125a52f-ac71-4900-a078-e2c6b60d4bf0.png)

### Ожидаемое поведение

Временные таблицы доступны во вложенных запросах

### Лог рабочей области

[log.zip](https://github.com/1C-Company/1c-edt-issues/files/7971931/log.zip)

### Версия 1С:EDT

Ruby 2021.3.1 и предыдущие

### Операционная система

Windows

**Comment by RedMammoth** [comment]
По-моему дубль #270
