### ISSUE TITLE
Внутренняя ошибка при слиянии веток.

### ISSUE THREAD

**Issue by EChudnovsky** [1C-Company/1c-edt-issues#345]
### Описание ошибки

При попытке слияния веток, в логах появляется сообщение "Произошла внутренняя ошибка: "Объединение веток"."
и слияние прерывается. 
Если это не является ошибкой хотелось получить развернутую информацию (не просто выброшенное исключение в лог журнале) о причине прерывания процесса слияния.

### Как воспроизвести

Выполнить действия по слиянию веток с установленным флагом "Открыть редактор сравнения\объединения (даже при отсутствии потенциальных проблем)".

### Скриншоты

![2022-02-03_09h06_25](https://user-images.githubusercontent.com/5530435/152290196-d316a0b9-1bd0-435f-a356-018de617201f.png)

### Ожидаемое поведение

1. Открытия окна сравнения объедения
2. Создание коммита слияния
3. Развернутое сообщение о поведении системы.

### Лог рабочей области

[Untitled.log](https://github.com/1C-Company/1c-edt-issues/files/7992172/Untitled.log)

### Версия 1С:EDT

Ruby 2021.3.1

### Операционная система

Linux

### Установленные плагины

1C:Code style V8, 1C:SSL-support, 1C:Language Tool

**Comment by EChudnovsky** [comment]
С аналогичной ошибкой падает и операция Навигатор - Сравнить - Ветка, метка или ссылка
Проверил на версии 2021.2.12 Слияние и Сравнение все работает корректно

**Comment by UGureev** [comment]
Та же проблема с версией 2021.3.2 и 2021.3.4
[edt.log](https://github.com/1C-Company/1c-edt-issues/files/8579915/edt.log)

**Comment by AlmazNasibullin** [comment]
@EChudnovsky @UGureev Коллеги, добрый день!
Ошибки слияния, подобные вашим, были исправлены в версии 1C:EDT 2022.1.0. Прошу проверить ваши сценарии на версии 2022.1.0 и отписаться по результатам проверки.

**Comment by EChudnovsky** [comment]
На версии 2022.1.0 несколько раз была ошибка слияния, но эта сейчас очень редкое поведение.
Помогает очистка проекта, т.е. существуют ситуации, когда состояние проекта при котором слияние будет приводить к падению. Из-за редкого поведения приложить пример пока не могу.
Это обращение закрою в случае появление ошибки создам новое.
