### ISSUE TITLE
Нагрузка процессора на 100% без видимых причин

### ISSUE THREAD

**Issue by KovAlexey** [1C-Company/1c-edt-issues#348]
### Описание ошибки

EDT была запущена в фоне, непосредственно в ней работы на момент начала проблемы не велась уже несколько минут как. 

Вдруг резко процесс EDT начал грузить все ядра на полную.
Ничего не предвещало, ничего до этого не происходило.
В состоянии пусто. 

### Как воспроизвести

К сожалению, способа не имею.

### Ожидаемое поведение

Отсутствие такого поведения.

### Лог рабочей области

[freeze.log.zip](https://github.com/1C-Company/1c-edt-issues/files/8000466/freeze.log.zip)

[bak_0.zip](https://github.com/1C-Company/1c-edt-issues/files/8001032/bak_0.zip)

### Версия 1С:EDT

2021.2.10

### Операционная система

Windows

### Установленные плагины

SSL, v8-code-style, Darkest Dark Theme, Disable Editing

**Comment by KovAlexey** [comment]
После перезапуска работа продолжилась в штатном режиме.
Без пересборок и тд

**Comment by vadimeg** [comment]
Возможно запускался сборщик мусора

**Comment by KovAlexey** [comment]
>Возможно запускался сборщик мусора

При ручном запуске это не занимает минуты.
Тем более память бесконтрольно сжиралась и очищалась

**Comment by KovAlexey** [comment]
Добавил еще один лог. В котором есть начало.

**Comment by tretyakevich** [comment]
Потребление памяти во время проверок, а также при работе с большим количеством маркеров ошибок значительно улучшено в 2023.1
