### ISSUE TITLE
Заполнять поле Подсказка автоматически аналогично конфигуратору

### ISSUE THREAD

**Issue by DmitryShvaika** [1C-Company/1c-edt-issues#349]
### Описание проблемы

Сейчас при изменении имени элемента, например Группы формы поле Подсказка не меняется. При создании элемента оно так же не заполняется. В конфигураторе это поле заполняется и меняется аналогично правилам для синонимов.

### Описание решения проблемы

Было бы удобный поведение как в конфигураторе.

**Comment by AndreyDanilov-nn** [comment]
![image](https://user-images.githubusercontent.com/53249626/152756062-4d1f0f70-3435-4b59-b108-4611928d579f.png)
https://its.1c.ru/db/v8std/content/478/hdoc

**Comment by DmitryShvaika** [comment]
Ок, тогда закрываю.
