### ISSUE TITLE
Ошибка запуска отладки

### ISSUE THREAD

**Issue by EChudnovsky** [1C-Company/1c-edt-issues#352]
### Описание ошибки

1. При попытке запуска отладки (кнопка отладки в панели "Приложения") стало появляться сообщение:
"Не удалось получить URL отладки выбранного приложения. Возможно оно запущено не в режиме отладки.".
Анализ журнала логирования, не дает представление о причинах подобного поведение.

2. Такая же ошибка "Не удалось получить URL отладки ...." происходит и при попытке создания Конфигурации отладки (см. скриншот ниже)
![2022-02-07_13h45_22](https://user-images.githubusercontent.com/5530435/152802371-36abf2a0-1354-4b88-9c14-b9bda2adb362.png)

### Как воспроизвести

Момент начало возникновения ошибки установить не удалось.
Просто в какой-то момент перестала запускаться конфигурация для отладки.

### Ожидаемое поведение

1. Иметь возможность выполнять отладку из EDT.
2. Получать развернутые сообщения о причинах и возможных действия по устранению поведения EDT останавливающие или затрудняющие разработку.

### Лог рабочей области

[Untitled.log](https://github.com/1C-Company/1c-edt-issues/files/8015885/Untitled.log)

### Версия 1С:EDT

Ruby 2021.3.1

### Операционная система

Linux

### Установленные плагины

1C:Code style V8, 1C:SSL-support, 1C:Language Tool

**Comment by JokerRoot666** [comment]
Наблюдается аналогичная проблема

**Comment by MaksimDzyuba** [comment]
Здравствуйте, скажите, пожалуйста, наблюдается ли на 2022.1?

У нас есть предположение, что  у Вас серверная ИБ,  и возможно в сервере не настроена отладка по HTTP, в 2022.1 мы сделали понятнее сообщение в этом случае

**Comment by EChudnovsky** [comment]
На всех серверных базах для разработки EDT http-отладка включена (работает команда разработчиков с сервером 1с).
Текущая ситуация: отладка выполнялась на файловой версии ИБ. 
На текущий момент описанная проблема начиная с версии 2021.3.4 не проявляется.

**Повторю главную мысль: ** 
Если бы разработчик получал развернутые сообщения о причинах и возможных действия по устранению поведения EDT останавливающие или затрудняющие разработку, то он мог бы сам разобраться в их устранении.
