### ISSUE TITLE
У Табличного документа нет события "ОбработкаДополнительнойРасшифровки"

### ISSUE THREAD

**Issue by AlexsandrSavinov** [1C-Company/1c-edt-issues#353]
### Описание ошибки

В Панели свойства табличного документа не отображается событие "ОбработкаДополнительнойРасшифровки".
Плюс идет дублирование события "ОбработкаРасшифровки"

### Как воспроизвести

1. Перейдите в любую форму где есть табличный документ, и посмотрите панель свойств.

### Скриншоты

![изображение](https://user-images.githubusercontent.com/46520831/152963416-e8e67ad5-7664-4b63-a883-ed2b2a2b2fa5.png)

### Ожидаемое поведение

Должно быть корректное событие.

### Лог рабочей области

[лог.zip](https://github.com/1C-Company/1c-edt-issues/files/8022716/default.zip)

### Версия 1С:EDT

Ruby 2021.3.1

### Операционная система

Windows, Linux

### Установленные плагины

1C:Code style V8, 1C:SSL-support

**Comment by vadimeg** [comment]
Исправлено в 2022.1
