### ISSUE TITLE
Поиск по конфигурации не ищет в модуле команды обработки после загрузки проекта из информационной базы.

### ISSUE THREAD

**Issue by DmitryShvaika** [1C-Company/1c-edt-issues#355]
### Описание ошибки

Загружаю проект из информационной базы. Делаю поиск процедуры и обнаруживаю, что поиск не находит использование процедуры в модуле команды обработки. Однако Ctrl+Alt+H (Иерархия вызовов) показывает использование процедуры.

### Как воспроизвести

1. Загрузите информационную базу из dt-файла
[test.zip](https://github.com/1C-Company/1c-edt-issues/files/8025893/test.zip)
2. Загрузите проект из указанной информационной базы
3. Выполните поиск по конфигурации фразы "МояПроцедура"
4. Убедитесь, что вызов процедуры из модуля команды обработки не найден

### Скриншоты

![image](https://user-images.githubusercontent.com/54451084/153037284-72b3fc4e-dbfb-4a78-977c-83770b8318d2.png)

![image](https://user-images.githubusercontent.com/54451084/153037394-dab81328-0f19-424f-a110-50759f948658.png)

### Ожидаемое поведение

Вызовы из модуля команды обработки должны отображаться в результатах поиска по конфигурации то же

### Лог рабочей области

[логи.zip](https://github.com/1C-Company/1c-edt-issues/files/8025925/default.zip)

### Версия 1С:EDT

Ruby 2021.2.12

### Операционная система

Windows

### Установленные плагины

1C:Code style V8

**Comment by tretyakevich** [comment]
Исправлено в 2022.2
