### ISSUE TITLE
Сделать поддержку новой версии оптимизированной реструктуризации v2 (поддерживается платформой с версии 8.3.11)

### ISSUE THREAD

**Issue by DmitryShvaika** [1C-Company/1c-edt-issues#363]
### Описание проблемы

Для больших баз хотелось бы использовать новую версию реструктуризации v2. 

### Описание решения проблемы

Было бы здорово, если бы Edt ее поддерживал.

**Comment by Desar14** [comment]
так что мешает включить поддержку в conf.cfg платформы? пользуюсь уже давно, это не зависит от едт.

**Comment by DmitryShvaika** [comment]
спасибо
