### ISSUE TITLE
Ошибка определеия типа СтандартнаяОбработка - думает что строка, но там булево должно быть

### ISSUE THREAD

**Issue by DitriXNew** [1C-Company/1c-edt-issues#365]
### Описание ошибки

Ошибка в определении типа, в частности в этом обработчике:
```bsl
// Обработка получения навигационной ссылки.
// 
// Параметры:
//  Ключ - Произвольный - Ключ
//  Представление - Строка - Представление
//  НавигационнаяСсылка - Строка - Навигационная ссылка
//  СтандартнаяОбработка - Строка - Стандартная обработка
&НаКлиенте
Процедура ОбработкаПолученияНавигационнойСсылки(
	Ключ,
	Представление,
	НавигационнаяСсылка,
	СтандартнаяОбработка)
```
В документации тоже считает что строка.

### Как воспроизвести

Просто вызвать окно подсказки или сгенерировать метод

### Скриншоты

![изображение](https://user-images.githubusercontent.com/11927866/153774713-d3f73616-0f9f-499f-86bf-bfef93f7bd3d.png)

### Ожидаемое поведение

Должно быть правильное определение типа

### Лог рабочей области

-

### Версия 1С:EDT

2021,3,1

### Операционная система

Windows

### Установленные плагины

1C:Code style V8, 1C:SSL-support

**Comment by MaksimDzyuba** [comment]
Здравствуйте, ошибку исправили, войдет в 2023.3, постараюсь перенести в 2023.2.
![image](https://github.com/1C-Company/1c-edt-issues/assets/77277424/486bde7e-d411-4bff-a182-fedd03e18d66)
