### ISSUE TITLE
Общее торможение и загрузка процессора 100 % 

### ISSUE THREAD

**Issue by ElchinGasanov** [1C-Company/1c-edt-issues#369]
### Описание ошибки

Наблюдается постоянная 100 % загрузка процессора  вызывающая торможение всей системы . 
Тормозит на операциях открытия проекта , на операциях очистки , 
при обновлении базы . 

Работал в проекте на версии 2021.2.10 - все работало великолепно .
Перешел на 2021.3.1 - EDT начал грузить процессор на 100 % процентов . 

Удалил все EDT , поставил чистую  [2021.3.1] заново , заново создал проект, импортировал данные из локально репозитория  , EDT начал тормозить . 

Плагины никакие не ставил сам, все стандартное из поставки.

До этого пробовал 2021.3.0

### Как воспроизвести

Просто поставил EDT и оно начало тормозить 

### Скриншоты

![image](https://user-images.githubusercontent.com/94464246/154334643-66395829-5d99-40ec-b059-2525bc48423b.png)

### Ожидаемое поведение

Ожидаю такого же поведения как от 2021.2.10 - стабильная работа

### Лог рабочей области

[version.txt](https://github.com/1C-Company/1c-edt-issues/files/8082635/version.txt)
[trace.txt](https://github.com/1C-Company/1c-edt-issues/files/8082636/trace.txt)
[1cedtstart.txt](https://github.com/1C-Company/1c-edt-issues/files/8082637/1cedtstart.txt)
[1cedt.txt](https://github.com/1C-Company/1c-edt-issues/files/8082638/1cedt.txt)

### Версия 1С:EDT

2021.3.1

### Операционная система

Windows

### Установленные плагины

1C:Code style V8, 1C:SSL-support

### Дополнительная информация

Использовал на проекте - https://github.com/i-neti/tools_ui_1c_international
Контакты для связи в telegram @Gasanov_Elchin

**Comment by tretyakevich** [comment]
Добрый день. Необходимы полные логи из рабочего пространства, приложенные файлы, к сожалению, не содержат информации об ошибках/процессах системы, которые были на момент возникших замедлений.

**Comment by ElchinGasanov** [comment]
> Добрый день. Необходимы полные логи из рабочего пространства, приложенные файлы, к сожалению, не содержат информации об ошибках/процессах системы, которые были на момент возникших замедлений.
> 
> Также показатели расхода памяти (на скриншоте) не соответствуют указанным в приложенном 1cedt.txt (в приложенном файле указано 4Gb heap, а на скриншоте - явно что-то около 8Gb). Поэтому просьба убедиться, что приложены именно те настройки, которые были использованы при запуске.
> 
> Проекты в WS - только те, которые указаны в https://github.com/i-neti/tools_ui_1c_international, или были еще какие-то?

Добрый день , пробовал ставить разный расход памяти , и 4gb и 8 gb . поэтому и различия 
Снимок потоков  снять не смог , из за тормозов . 
Как найти логи полные рабочего пространства , пожайлуста дайте ссылку на документацию где описана операция 

Проект только этот и 2 бсп импортированные , чтобы тестировать

**Comment by tretyakevich** [comment]
Пути к каталогу с данными проектов можно посмотреть в стартере: https://its.1c.ru/db/edtdoc#content:10524:hdoc
Вот здесь, собственно, описана процедура сбора логов: https://its.1c.ru/db/edtdoc#content:153:hdoc@2a13f2b3

**Comment by ElchinGasanov** [comment]
> Пути к каталогу с данными проектов можно посмотреть в стартере: https://its.1c.ru/db/edtdoc#content:10524:hdoc Вот здесь, собственно, описана процедура сбора логов: https://its.1c.ru/db/edtdoc#content:153:hdoc@2a13f2b3

Поймал ошибку такую же в 2021.2.12 ( до этого использовал 2021.2.**10**) 

1) в 2021.2.10 - удалил плагин Code Style 
2) Перезапустил EDT - выполнил очистку проекта ( 2 раза ) 
3) Указал в стартере что хочу использовать 2021.2.12
4) Убедился что плагина Code Style нет в списке 
5) EDT сам начал перестроение проекта , начал подтормаживать , совсем плохо стало когда началась операция Extended Language Validation , было 4 прогресс бара , 2 прошло на 2 намертво зависло . 
Устав ждать я завершил задачу через - диспетчер задач. ( на скрине , что вернул EDT при завершении ) 
![image](https://user-images.githubusercontent.com/94464246/154449520-cde888fa-c3fd-450b-adb5-20f66c430b41.png)

6) Открыл EDT заново - процедуру Extended Language Validation - отменил в прогресс окне , он начал тормозить просто так , без причин загружая процессор на 100 процентов . 

По адресу : https://disk.yandex.ru/d/a94eWxpOn3xHTw 
 доступны для скачивания логи   

Вот скриншот как распределяется место в папке MetaData проекта . 
![image](https://user-images.githubusercontent.com/94464246/154453600-05e168cf-c19e-4249-97ac-874df969f2f0.png)

**Comment by ElchinGasanov** [comment]
> Пути к каталогу с данными проектов можно посмотреть в стартере: https://its.1c.ru/db/edtdoc#content:10524:hdoc Вот здесь, собственно, описана процедура сбора логов: https://its.1c.ru/db/edtdoc#content:153:hdoc@2a13f2b3

Почистил папку Metadata в проекте , 
Запустил EDT 2021.2.12 - он стал нагружать процессор на 100 % при старте .
После активации проектного контектса ( процедура Extended Language validation не запустилась )  открыл модуль .
EDT так же потреблял 100 % процессора , и притормаживал .

**Comment by tretyakevich** [comment]
Спасибо большое. 
По последним предоставленым логам первое - система влетела в постоянный цикл сбора мусора, поэтому и загрузка процессора и неотзывчивость. 
(в логе - сообщения типа !ENTRY com._1c.g5.v8.internal.resourcemanagement.ResourceManagementPlugin 2 0 2022-02-17 23:39:06.363
!MESSAGE Critical system overload (cpu and/or memory): memory 4284269832 used of 4294967296
)
И дальше она влетела в !MESSAGE Unhandled event loop exception
!STACK 0
java.lang.OutOfMemoryError: Java heap space

4Гб хипа ей оказалось мало, нехорошо. Проверю на представленном наборе конфигураций, посомтрим, что там во время расширенной языковой валидации съело память.

**Comment by MaksimDzyuba** [comment]
Здравствуйте, а проверяли ли импорт на 2022.1, я сейчас попробовал построить все эти 4 проекта из указанного Вами репоизтория все прошло штатно, ничего не зависло и не затупило

**Comment by tretyakevich** [comment]
В версии 2022.2 и далее в версии 2023.1 внесен значительный объем изменений для работы с меньшим объемом памяти (особенно в 2023.1)
