### ISSUE TITLE
Оператор [] не имеет типа возвращаемого значения для объекта ВременныеТаблицыЗапроса

### ISSUE THREAD

**Issue by RedMammoth** [1C-Company/1c-edt-issues#371]
### Описание ошибки

Если я получаю таблицу с помощью функции Найти объект ВременныеТаблицыЗапроса, то тип переменной правильно определяется и в code assist доступны свойства и методы типа ВременнаяТаблицаЗапроса.
Если же я получаю с помощью оператора [], то у переменной нет типа (косвенно проверил с помощью генерации автоматичекого комментария - в секции возвращаемое значение пусто

### Как воспроизвести

```bsl
// @strict-types
#Область ПрограммныйИнтерфейс

// В т тест.
// 
// Возвращаемое значение:
//  
Функция ВТ_Тест() Экспорт

	Запрос = Новый Запрос;
	МенеджерТаблиц = Новый МенеджерВременныхТаблиц;
	Запрос.МенеджерВременныхТаблиц = МенеджерТаблиц;
	Запрос.Текст = "ВЫБРАТЬ
				   |	1 КАК Поле1
				   |ПОМЕСТИТЬ ВТ_Тест
				   |
				   |ИНДЕКСИРОВАТЬ ПО
				   |	Поле1
				   |";
	Запрос.Выполнить();

	Возврат МенеджерТаблиц.Таблицы["ВТ_Тест"];

КонецФункции

#КонецОбласти
```

### Скриншоты

![image](https://user-images.githubusercontent.com/64589646/154515547-17425a4a-76f3-4c89-b1d9-cdcb13a13c15.png)

### Ожидаемое поведение

Оператор [] возвращает объект типа ВременнаяТаблицаЗапроса

### Лог рабочей области

-

### Версия 1С:EDT

2021.3.1

### Операционная система

Windows, Linux

### Установленные плагины

1C:Code style V8, 1C:SSL-support, 1C:Language Tool

**Comment by marmyshev** [comment]
@MaksimDzyuba  это именованные коллекции

**Comment by MaksimDzyuba** [comment]
Здрравствуйте, исправил в 2023.3, постараюсь перенести в 2023.2, но не обещаю.
![image](https://github.com/1C-Company/1c-edt-issues/assets/77277424/246c6268-f7d3-4d62-bcf4-f6a73a3d24a6)
