### ISSUE TITLE
В отладке Не отображаются Значения Соответствий

### ISSUE THREAD

**Issue by asosnoviy** [1C-Company/1c-edt-issues#374]
### Описание ошибки

В отладке не показывается состав Соответствий

### Как воспроизвести

В отладке посмотреть значение соответствия

### Скриншоты

![image](https://user-images.githubusercontent.com/15638529/154627225-8d4c8009-55bf-48d3-9854-779a16a33972.png)

### Ожидаемое поведение

В элементах видно ключ-значение
На вкладке значения отображается состав соответствия

### Лог рабочей области

Логов нет

### Версия 1С:EDT

Ruby 2021.3.1

### Операционная система

Windows, Linux

### Дополнительная информация

1С:Предприятия 8.3.21.1140

**Comment by asosnoviy** [comment]
в 2021.3.2 8.3.21.1197 также не отображается

**Comment by adminimusRU** [comment]
В 2021.3.4 кажется уже работает:
![image](https://user-images.githubusercontent.com/28653631/173552153-43d368ea-01b5-46b5-a98b-391bc776fdbe.png)
![image](https://user-images.githubusercontent.com/28653631/173552336-0198f88b-0098-4d85-b0f3-b53fad7c3a5b.png)

**Comment by REset49** [comment]
Не работает 2021.3.4 и 8.3.21.1302...
![image](https://user-images.githubusercontent.com/92163852/177915037-e84bd14d-41bb-478e-a548-96a77f99a180.png)
