### ISSUE TITLE
При редактировании настроек СКД ошибка редактор значения  для типа не найден

### ISSUE THREAD

**Issue by awk-kazmin** [1C-Company/1c-edt-issues#375]
### Описание ошибки

При редактировании макета СКД при попытке изменения "Расположение реквизитов", происходит ошибка:

![image](https://user-images.githubusercontent.com/4029681/154643313-5abeb620-efb4-4cb3-8072-67bfcdba2421.png)

### Как воспроизвести

1. Перейдите в `Макет схемы компоновки данных на закладку настройки`
2. Кликните по `Расположение реквизитов на закладке Другие настройки`
4. Смотрите ошибку в `....`
![image](https://user-images.githubusercontent.com/4029681/154643586-c7fbc3cf-0804-4ffb-bef2-f0f7fba9bf77.png)

### Скриншоты

![image](https://user-images.githubusercontent.com/4029681/154643808-94f33529-4c29-4a49-ade9-77359be272d3.png)

### Ожидаемое поведение

Дать выбор из N параметров.

### Лог рабочей области

--

### Версия 1С:EDT

2021.2.12

### Операционная система

Windows

**Comment by MaksimDzyuba** [comment]
Здравствуйте, ошибка в 2021.3 не воспроизводится, 
![image](https://user-images.githubusercontent.com/77277424/157635409-57c16b6d-6f93-4e76-a432-0de35b4a019c.png)

**Comment by vadimeg** [comment]
Больше не воспроизводится
