### ISSUE TITLE
Для проверки "Not allowed transfer object of type between client and server" не работает подавление ошибки

### ISSUE THREAD

**Issue by DmitryShvaika** [1C-Company/1c-edt-issues#377]
### Описание ошибки

Ошибка в том что...
Для проверки "Not allowed transfer object of type between client and server" не работает подавление ошибки
Есть подозрения что в наименовании проверки есть пробелы

### Как воспроизвести

1. Распаковать и подключить приложенный проект ниже
[test.zip](https://github.com/1C-Company/1c-edt-issues/files/8097660/test.zip)

2. Попытаться подавить ошибку

(для генерации данной ошибки можно так же создать функцию на сервере, которая возвращает ссылку внешнего источника и вызвать эту функцию на клиенте)

### Скриншоты

![image](https://user-images.githubusercontent.com/54451084/154694209-6f6ae8b5-ed1f-4a2e-ad38-46210272574c.png)

### Ожидаемое поведение

Подавление ошибки должно работать

### Лог рабочей области

[log.zip](https://github.com/1C-Company/1c-edt-issues/files/8097669/log.zip)

### Версия 1С:EDT

Ruby 2021.3.2

### Операционная система

Windows

### Установленные плагины

1C:Code style V8

### Дополнительная информация

В этом же примере ошибка "Нельзя передавать значение между сервером и клиентом" для ссылки таблицы внешнего источника https://github.com/1C-Company/1c-edt-issues/issues/364

**Comment by vadimeg** [comment]
Хотелось бы уточнить. Т.е. добавили комментарий
**//@skip-check transfer-object-between-client-server**
над строкой 
**а = ПолучитьСсылкуВнешнегоИсточника();**

Потом сохранили модуль и после этого предупреждение не исчезло? У меня подавление сработало.

![image](https://user-images.githubusercontent.com/17178862/162973779-f619d048-add0-48f5-88d9-031ece7f9755.png)

**Comment by DmitryShvaika** [comment]
Вроде раньше строка @skip-check появлялась, но ошибка не подавлялась. Сейчас (в 2021.3.3) даже строка не появляется - не работает.
![ПодавлениеПередачиМеждуКлиентомИСервером](https://user-images.githubusercontent.com/54451084/162998967-2cb5075a-91c1-4f68-9d61-5206ef36b29c.gif)
проект прилагаю
[test.zip](https://github.com/1C-Company/1c-edt-issues/files/8474369/test.zip)
