### ISSUE TITLE
Ошибки при редактировании расширения в EDT

### ISSUE THREAD

**Issue by EChudnovsky** [1C-Company/1c-edt-issues#378]
### Описание ошибки

При работе с расширениями в EDT возникают ситуации которые критически влияют на скорость разработки (фактически останавливающие процесс разработки), отнимающие много сил и времени на восстановление работоспособности проекта расширения.

На текущий момент выявлены следующие ошибки.
1. Периодически слетают типы реквизитов, помогает только их пере выбор 
![изображение](https://user-images.githubusercontent.com/5530435/154836621-0fa7864c-6d49-463d-acdb-30ab3112214a.png)

2. Периодически слетает привязка к заимствованному объекту  поле extendedConfigurationObject

![изображение](https://user-images.githubusercontent.com/5530435/154836721-1827e15e-ebb4-4c54-b4d7-3b7e773f8d53.png)

3. (Пожелание) В случае наличия в расширении ошибки заимствования:
* объекта
* реквизита
* форм
не существует  инструмента (в виде сравнения\объединения) для восстановления работоспособности объекта в расширении, путем переноса сведений из объекта основной. Единственный сейчас вариант:
* прямое редактирование исходных файлов 
* или новый импорт расширения из конфигурации, восстановление выполненной доработки. Оба пути громоздки и ресурса затратны.

4. В некоторых ситуация EDT самостоятельно добавляет пустые объекты (на 2021.3.2 это происходило при загрузке в базу ) .
При наличии таких объектов удалить их средствами EDT Невозможно, необходимо править файл Configuration.mdo

![изображение](https://user-images.githubusercontent.com/5530435/154837399-2e9ad9f7-c2a1-4f40-939b-c3279b9144e3.png)

5. Часто происходит отвязка приложения от проекта, что приводит к невозможности выполнить загрузку проекта в базу. Помогает только пересоздание приложения. Обычно данная ситуация сопровождается сообщением ниже
![изображение](https://user-images.githubusercontent.com/5530435/154837915-970b68bb-2410-4797-8f17-b86e8f371878.png)

6. Частая ситуация с расширением: Расширение загружается в конфигурацию без ошибок (загрузка выполняется ПОЛНАЯ). Результат фиксируется и передается другому разработчику. При попытке другого разработчика применить у себя новую разработку при загрузке в конфигуратор выдается сообщение о нехватке объектов (КАК!?).

7. При разборе ситуаций встречаются ошибки, когда невозможно получить информацию о месте и причинах падения загрузки конфигурации в базу. Единственное решение долгий поиск и эксперименты с исходными файлами. Хотелось бы интуитивно-понятное логирование с указанием хотя бы места падения. 

![изображение](https://user-images.githubusercontent.com/5530435/154839565-9f021d3f-a360-4d05-8629-55f6bc38973e.png)

![изображение](https://user-images.githubusercontent.com/5530435/154839669-a876f9ad-f902-484e-a04a-48bfa7bb1ad1.png)

7. Редакторы событий элементов, не понятна за чем изменена концепция типового редактирования обработчиков. Из-за этого:
* Утеряна функциональность и удобство. Например удаление не используемых обработчиков не происходит, приходиться постоянно следить и вычищать руками;
* Невозможно очистить назначенный обработчик (часто возникает после слияния). Светиться ошибка что назначен обработчик для события, но в поле редактирования он пустой, только кнопка перехода. выход из ситуации прямое редактирование файла формы.

8. Часто у расширения слетает базовый проект. Из-за этого появляются многочисленные сообщения об ошибках. Из-за не выбранного проекта не обновляется расширение. Помогает пере выбор, в некоторых случаях требуется очистка проекта расширения, если и это не помогает приходиться пере создавать приложение.
 9. После слияния разработок (часто) не происходит обновление конфигурации расширения. Помогает пересоздание приложения. Предположу что это связано с кэшами.

### Как воспроизвести

Развернуть типовую конфигурацию и выполнить действия по добавлению объектов в расширение, обновления базы конфигурации (полная, частичная загрузка), выполнить слияния разработок по расширению для разработчиков работавших например над  одним объектом расширения.

### Ожидаемое поведение

Быстрая стабильная разработка в EDT, не отнимающая до 90% времени на ожиданиях процессов пере сборки проектов, не адекватного поведения интерфейсов 

### Лог рабочей области

[.log1.zip](https://github.com/1C-Company/1c-edt-issues/files/8103806/default.log1.zip)
[.log2.zip](https://github.com/1C-Company/1c-edt-issues/files/8103809/default.log2.zip)

### Версия 1С:EDT

Ruby 2021.3.2

### Операционная система

Windows, Linux

### Установленные плагины

1C:Code style V8, 1C:SSL-support, 1C:Language Tool

### Дополнительная информация

Платформа 8.3.19.1417 и 8.3.19.1229
Конфигурация Зарплата и управление персоналом КОРП, редакция 3.1

**Comment by EChudnovsky** [comment]
8. Часто у расширения слетает базовый проект. Из-за этого появляются многочисленные сообщения об ошибках. Не обновляется расширение. Помогает пере выбор, в некоторых случаях требуется очистка проекта расширения, если и это не помогает приходиться пере создавать приложение.
9.  После слияния разработок (часто) не происходит обновление конфигурации. Помогает пересоздание приложения.

**Comment by EChudnovsky** [comment]
10  В расширении невозможно указать тип у заимствованного объекта Определяемый Тип

https://user-images.githubusercontent.com/5530435/155065769-396d661c-2315-401a-80ef-4b11de0e98ae.mp4

**Comment by ViktorErmakov** [comment]
+

**Comment by Dionisious** [comment]
Ошибка появляется после добавления в расширение формы у которой исключены некоторые стандартные комманды или после обновления расширения формы.

![image](https://user-images.githubusercontent.com/42739787/155129557-766b46ea-53bb-4190-b0cc-e504eb7f4b09.png)

**Comment by EChudnovsky** [comment]
> Ошибка появляется после добавления в расширение формы у которой исключены некоторые стандартные комманды или после обновления расширения формы.

По каким волшебным звездам разработчик должен это понять?
Где можно об этом прочитать? Получить справку?
Почему исследование подобных поведение требует потери ОГРОМНОГО количества времени. На исследование источников, пересоздания приложений, очистки рабочих областей и все это  ОЖИДАНИЯ процессов EDT для завершения все это не минуты, а часы.

**Comment by Dionisious** [comment]
> > Ошибка появляется после добавления в расширение формы у которой исключены некоторые стандартные комманды или после обновления расширения формы.
> 
> По каким волшебным звездам разработчик должен это понять? Где можно об этом прочитать? Получить справку? Почему исследование подобного поведение требует потери ОГРОМНОГО количества времени. На исследование источников, пересоздания приложений, очистки рабочих областей и все это ОЖИДАНИЯ процессов EDT для завершения все это не минуты, а часы.

Я всего лишь разработчикам EDT показал как повторить ошибку.

**Comment by vadimeg** [comment]
> > > Ошибка появляется после добавления в расширение формы у которой исключены некоторые стандартные комманды или после обновления расширения формы.
> > 
> > 
> > По каким волшебным звездам разработчик должен это понять? Где можно об этом прочитать? Получить справку? Почему исследование подобного поведение требует потери ОГРОМНОГО количества времени. На исследование источников, пересоздания приложений, очистки рабочих областей и все это ОЖИДАНИЯ процессов EDT для завершения все это не минуты, а часы.
> 
> Я всего лишь разработчикам EDT показал как повторить ошибку.

Приложите лог, пожалуйста. А еще лучше, если создадите отдельный баг с указанием шагов, версий и т.д., т.к. к изначальной задаче это не имеет отношения и в приложенных логах про эту ошибку ничего нет

**Comment by vadimeg** [comment]
По картинке из пункта 7, там где ClassCastException. В приложенных логах по ошибке ничего нет, по картинке сложно воспроизвести проблему.

**Comment by vadimeg** [comment]
> №10. В расширении невозможно указать (отредактировать) тип у заимствованного объекта Определяемый Тип
Тип не выбирается т.к. нет привязки проекта расширения к основной конфигурации

**Comment by EChudnovsky** [comment]
> И если навести мышь на ошибку в редакторе, то будет подсказка:

Т.е.  Вы хотите сказать, что редактирование Определяемых типов в EDT не поддерживается?

В конфигураторе (для 19 платформы) я могу легко отредактировать типы и с этим никаких никаких проблем.

Вот на картинке импортированные из конфигураци настройки,  только проверка всегда выдает ошибку на составных типах, а редактирование не доступна (в случае что-то изменить). 

![изображение](https://user-images.githubusercontent.com/5530435/157617705-5b1e7e00-4150-417e-878b-7acc1c8a662b.png)

При
[log.txt](https://github.com/1C-Company/1c-edt-issues/files/8221552/log.txt)
 этом в логах появляется сообщение об ошибках

**Comment by vadimeg** [comment]
> Т.е. Вы хотите сказать, что редактирование Определяемых типов в EDT не поддерживается?

Нет, просто проект расширения не связан с базовой конфигурацией. Связь восстановить можно через редактор проекта у конфигурации-расширении

**Comment by vadimeg** [comment]
По №8 подтверждаю, что есть такая проблема - видел у пользователей, что после каких-то действий привязка слетает. Шагов для воспроизведения, к сожалению, пока нет. Завел на это отдельный баг.

**Comment by vadimeg** [comment]
№1, №3, №10 насколько я понял это следствие №8

**Comment by EChudnovsky** [comment]
> Нет, просто проект расширения не связан с базовой конфигурацией. Связь восстановить можно через редактор проекта у конфигурации-расширении

Не соглашусь проблема редактирования есть.
Связь с базовым проектом так же есть и это подтверждается тем, что при заимствовании из основной конфигурации объектов не выдается сообщение о наличии расширения и объекты успешно добавляются.

**Comment by vadimeg** [comment]
> Не соглашусь проблема редактирования есть.
Ок, тогда нужна конфигурация, на которой это воспроизводится. На тестовом проекте все работает

**Comment by EChudnovsky** [comment]
> Ок, тогда нужна конфигурация, на которой это воспроизводится. На тестовом проекте все работает

Слабенький какой-то у вас тест :).
Проект только начали так что ничего ценного пока нет, как я могу передать проект для анализа?

**Comment by vadimeg** [comment]
Если не сильно большой, то можно сюда или в телеграм. Либо в любое облако

**Comment by vadimeg** [comment]
Проблему воспроизвели и поправили. Исправление войдет в ближайший релиз (2021.3.3)

**Comment by vadimeg** [comment]
Большая часть проблем была исправлена. Оставшиеся либо не удалось воспроизвести, либо на них уже есть открытые баги. Если что-то еще осталось, то просьба создать отдельные реквесты.

**Comment by EChudnovsky** [comment]
По срокам выхода релиза edt  с сориентируете?

**Comment by vadimeg** [comment]
> По срокам выхода релиза edt с сориентируете?

Уже скоро, точную дату не подскажу, к сожалению
