### ISSUE TITLE
В диалог фильтра ошибок добавить фильтр по коду проверки

### ISSUE THREAD

**Issue by DmitryShvaika** [1C-Company/1c-edt-issues#388]
### Описание проблемы

Сейчас нельзя отобрать ошибки с выбранным(и) кодом проверки. 

![image](https://user-images.githubusercontent.com/54451084/155458976-39df53e8-24fc-4c5c-8cc6-42c449946125.png)

### Описание решения проблемы

Добавить поле кода проверки или список с флажками для выбора проверок.

**Comment by marmyshev** [comment]
А почем не возможно использовать фильтр в панели ошибок? туда можно вставить код проверки

**Comment by RedMammoth** [comment]
> А почем не возможно использовать фильтр в панели ошибок? туда можно вставить код проверки

речь про поиск? в нем можно найти несколько проверок?

**Comment by DmitryShvaika** [comment]
> А почем не возможно использовать фильтр в панели ошибок? туда можно вставить код проверки

а где этот фильтр в панели ошибок ... в задаче приведен диалог отбора - думал это и есть фильтр как раз из панели ошибок

![image](https://user-images.githubusercontent.com/54451084/194647147-d9447f5c-5170-4ce4-8c39-ac0ad63af73e.png)

**Comment by marmyshev** [comment]
> > А почем не возможно использовать фильтр в панели ошибок? туда можно вставить код проверки
> 
> 
> 
> а где этот фильтр в панели ошибок ... в задаче приведен диалог отбора - думал это и есть фильтр как раз из панели ошибок
> 

Прям вот под кнопкой - поле ввода для поиска (отбор ведь!?), вставляешь туда код проверки и всё.

Да, нельзя, наверное, ввести много разных кодов для отбора. Но зачем много - пока не понял :)

**Comment by RedMammoth** [comment]
@DmitryShvaika может все таки оставим пожелания на отбор по коду? 4 лайка уже есть.

**Comment by RedMammoth** [comment]
> Но зачем много - пока не понял :)

Сходу не скажу, но может появится задача на исправление легаси по нескольким типам или похожих или связанных ошибок. Там чтобы просто примерно оценить масштаб нужно будет выгружать в эксель, там накладывать фильтры и смотреть сколько строк. А потом при исправлении работать только по одному коду-ошибки единомоментно или постоянно перещелкивать. 

В общем мне кажется, что неплохое пожелание. Фильтр по подсистемам есть, туда еще фильтр по ошибкам и удобно отрабатывать получившийся список

**Comment by DmitryShvaika** [comment]
я думаю если есть уже возможность - не надо дублировать функционал. В параметрах + в панели уже достаточно.

**Comment by RedMammoth** [comment]
> я думаю если есть уже возможность - не надо дублировать функционал. В параметрах + в панели уже достаточно.

Мне кажется это не дублирование. Если я в параметрах уберу - проверки очистятся, поставлю - начнут заново рассчитываться. Зачем мне заново запускать перерасчет, когда я просто хочу поиграться отборами и собрать нужные мне в текущий момент данные.

**Comment by DmitryShvaika** [comment]
> > я думаю если есть уже возможность - не надо дублировать функционал. В параметрах + в панели уже достаточно.
> 
> Мне кажется это не дублирование. Если я в параметрах уберу - проверки очистятся, поставлю - начнут заново рассчитываться. Зачем мне заново запускать перерасчет, когда я просто хочу поиграться отборами и собрать нужные мне в текущий момент данные.

Они не очищаются а фильтруются, скрываются (возможно я не прав - точно Дмитрий скажет). Пересчет заново запускать вроде не надо.

**Comment by RedMammoth** [comment]
> > > я думаю если есть уже возможность - не надо дублировать функционал. В параметрах + в панели уже достаточно.
> > 
> > 
> > Мне кажется это не дублирование. Если я в параметрах уберу - проверки очистятся, поставлю - начнут заново рассчитываться. Зачем мне заново запускать перерасчет, когда я просто хочу поиграться отборами и собрать нужные мне в текущий момент данные.
> 
> Они не очищаются а фильтруются, скрываются (возможно я не прав - точно Дмитрий скажет). Пересчет заново запускать вроде не надо.

Я сейчас попробовал выключить/отключить жирную проверку в настройках валидации (проверка на неиспользуемые экспортные процедуры) - у меня запустилась расширенная проверка языковых данных.

@marmyshev, подскажи свое мнение, оставить ли данное пожелание открытым

**Comment by marmyshev** [comment]
Включение-выключение в параметрах проекта - это:
1. удаление маркеров полностью по отключенной проверке
2. запуск проверок заново при включении проверок по всему проекту
3. Изменение профиля валидации - что должно приводить к коммиту в репу или откату изменений

т.е. для функций отбора каждого разработчика команды у себя в панели какой-то части ошибок - эта функциональность не подходит.

**Comment by marmyshev** [comment]
> > Но зачем много - пока не понял :)
> 
> Сходу не скажу, но может появится задача на исправление легаси по нескольким типам или похожих или связанных ошибок. Там чтобы просто примерно оценить масштаб нужно будет выгружать в эксель, там накладывать фильтры и смотреть сколько строк. А потом при исправлении работать только по одному коду-ошибки единомоментно или постоянно перещелкивать.
> 
> В общем мне кажется, что неплохое пожелание. Фильтр по подсистемам есть, туда еще фильтр по ошибкам и удобно отрабатывать получившийся список

Давайте, если нет сценария зачем это надо (не по одной, а именно по нескольким смотреть в панели одновременно!!!) - если никто не понимает зачем это нужно - давайте не плодить никому-ненужных пожеланий.
