### ISSUE TITLE
ring validate переделать формат

### ISSUE THREAD

**Issue by DitriXNew** [1C-Company/1c-edt-issues#39]
## Описание проблемы
 Есть контур, хочу сделать так, чтобы система брала ошибки из некоего лога, шаблона, где были ошибки на некий момент времени и выводила только новые ошибки. Для этого есть скрипт, который сравнивает файлы, и с онфигуратором - все ок.
В случае ЕДТ - туда лезет дата, номер строки и т.д., т.е. заведомо динамическая информация.

## Описание решения проблемы
Хочу, чтобы ринг умел выгрузать без этих полей, чтобы я могу задать это параметром
Идеально, если бы я еще мог задать сонара, чтобы ошибки выгружать туда. Тогда он бы сам это контролировал

**Comment by shcherbakov-vadim** [comment]
Там ведь формат tsv, что позволяет обращаться только к колонке с ошибкой. Номер строки тоже можно выделить по начальным символам

**Comment by DitriXNew** [comment]
Проблема в том, что если не сравнивать строки, то не понятно где ошибка.
А если сравнивать, то любое изменение в коде - сдвигает строки и вылазят якобы новые ошибки.
Но, наверное закрою задачу, так как вопрос решил скриптом, а с номерами строк - это наверное больше задача сонара, чем едт.
