### ISSUE TITLE
Рефакторинг - Переименовать - Переменная в секции Перем

### ISSUE THREAD

**Issue by petypen** [1C-Company/1c-edt-issues#390]
### Описание ошибки

Ошибка в том что...
Если воспользоваться рефакторинг - переименование и переименовать переменную в секции `Перем`, то в методе переменная останется с прежним наименованием (не будет переименована)

### Как воспроизвести

1. Перейдите в модуль с кодом. Откройте метод в котором есть секция `Перем`
Пример метода:
```bsl
Функция ПолучитьГоризонтальноеПоложение(ШифрПоложения)
	Перем ГоризонтальноеПоложение;
	
	Если ШифрПоложения = 1 Тогда
		ГоризонтальноеПоложение = ГоризонтальноеПоложениеЭлемента.Лево;
	ИначеЕсли ШифрПоложения = 2 Тогда
		ГоризонтальноеПоложение = ГоризонтальноеПоложениеЭлемента.Центр;
	ИначеЕсли ШифрПоложения = 3 Тогда
		ГоризонтальноеПоложение = ГоризонтальноеПоложениеЭлемента.Право;
	Иначе
		ГоризонтальноеПоложение = ГоризонтальноеПоложениеЭлемента.Авто;
	КонецЕсли;
	
	Возврат ГоризонтальноеПоложение;
КонецФункции
```
2. На переменной ГоризонтальноеПоложение вызовите действие рефакторинга - Переименовать. __Важно__, рефакторинг нужно делать на переменной, которая объявлена в строке 2 (Перем ГоризонтальноеПоложение;)
3. После подтверждения действия Переименование будет переименована только переменная во второй строке. Остальные переменные модуля переименованы не будут.

### Скриншоты

![2022-02-25 15-11-36 Conversion3 - Конвертация_данных_31 КонвертацияДанныхПлюс→Общие→Общие модули→PEN007_ПФИВызовСервера - 1](https://user-images.githubusercontent.com/6500075/155713256-137a56ae-817e-4981-8c20-0355e6a8ac20.png)
![2022-02-25 15-11-23 Переименовать элемент](https://user-images.githubusercontent.com/6500075/155713260-1877909b-b9f9-419d-a53b-db8ca72dc859.png)

### Ожидаемое поведение

При переименовании переменной в секции Перем я ожидаю переименование всех соответствующих переменных метода.

### Лог рабочей области

[журнал.log](https://github.com/1C-Company/1c-edt-issues/files/8141049/default.log)

### Версия 1С:EDT

Ruby 2021.3.2

### Операционная система

Windows

### Установленные плагины

1C:Code style V8

**Comment by MaksimDzyuba** [comment]
![bandicam 2024-01-19 21-24-02-079 (1)](https://github.com/1C-Company/1c-edt-issues/assets/77277424/6cbdcf22-6023-416b-94c4-1e4e0349b0fa)
Здравствуйте, удалось исправить, постараемся включить в 2023.3
