### ISSUE TITLE
Ошибка при вычислении типа системного перечисления ГоризонтальноеПоложениеЭлемента

### ISSUE THREAD

**Issue by petypen** [1C-Company/1c-edt-issues#393]
### Описание ошибки

Ошибка в том что, EDT не может вычислить тип переменной, которой присваивается значение системного перечисления. При этом появляется сообщение об ошибке `Переменная "ПоложениеЭлемента" не имеет типа`

### Как воспроизвести

В методе инициализируется переменная ПоложениеЭлемента значением системного перечисления ГоризонтальноеПоложениеЭлемента

```bsl
// Горизонтальное положение элемента.
// 
// Параметры:
//  Положение - Число - код положения элемента, где значение:
//    1 - Лево
//    2 - Центр
//    3 - Право
//    0 - Авто
// 
// Возвращаемое значение:
//  ГоризонтальноеПоложениеЭлемента - положение элемента формы по горизонтали
Функция ГоризонтальноеПоложениеЭлемента(Положение)
	
	ПоложениеЭлемента = ГоризонтальноеПоложениеЭлемента.Авто;
	
	Если Положение = 1 Тогда
		ПоложениеЭлемента = ГоризонтальноеПоложениеЭлемента.Лево;
	ИначеЕсли Положение = 2 Тогда
		ПоложениеЭлемента = ГоризонтальноеПоложениеЭлемента.Центр;
	ИначеЕсли Положение = 3 Тогда
		ПоложениеЭлемента = ГоризонтальноеПоложениеЭлемента.Право;
	КонецЕсли;
	
	Возврат ПоложениеЭлемента;
КонецФункции
```

EDT для строки `ПоложениеЭлемента = ГоризонтальноеПоложениеЭлемента.Авто;` выводит сообщение об ошибке: "Переменная "ПоложениеЭлемента" не имеет типа"

Причем, если в строке инициализации переменной дополнительно уточнить тип через комментарий
`ПоложениеЭлемента = ГоризонтальноеПоложениеЭлемента.Авто; // ГоризонтальноеПоложениеЭлемента -`
то сообщение об ошибке пропадает.

### Скриншоты

![2022-03-05 11-05-00 Conversion3 - Конвертация_данных_31 КонвертацияДанныхПлюс→Общие→Общие модули→PEN007_ПФИВызовСервера - 1](https://user-images.githubusercontent.com/6500075/156874583-ab9851eb-ffa8-4e5c-9077-cc7979d45e0f.png)
![2022-03-05 11-04-15 Conversion3 - Конвертация_данных_31 КонвертацияДанныхПлюс→Общие→Общие модули→PEN007_ПФИВызовСервера - 1](https://user-images.githubusercontent.com/6500075/156874585-633977e4-13dd-416e-8a14-00d14f706b42.png)

### Ожидаемое поведение

Ожидалось, что EDT вычислит тип переменной при инициализации системным перечислением

### Лог рабочей области

[edt.log](https://github.com/1C-Company/1c-edt-issues/files/8190275/edt.log)

### Версия 1С:EDT

Ruby 2021.3.2

### Операционная система

Windows

### Установленные плагины

1C:Code style V8

**Comment by RedMammoth** [comment]
Думаю дубль, https://github.com/1C-Company/1c-edt-issues/issues/379
