### ISSUE TITLE
Зависание расширенной проверки языковых данных

### ISSUE THREAD

**Issue by goodwinvu** [1C-Company/1c-edt-issues#399]
### Описание ошибки

При попытке перехода на версию 21.3.3 сделал реимпорт конфигурации в проект.
В какой то момент заметил сильные тормоза, понял что зависает процедура "Расширенная проверка языковых данных", ожидал более получаса - нагрузка на процессор максимальная при этом прогресс стоит на месте

### Как воспроизвести

Реимпорт проекта в версии 21.3.3

### Ожидаемое поведение

отсутствие зависаний

### Лог рабочей области

[LogAndDump.zip](https://github.com/1C-Company/1c-edt-issues/files/8260564/LogAndDump.zip)

### Версия 1С:EDT

2021.3.3

### Операционная система

Windows

### Установленные плагины

1C:Code style V8, 1C:SSL-support, Другие сторонние плагины `Название плагина...`

### Дополнительная информация

Установлен плагин edt-editing https://github.com/marmyshev/edt-editing

**Comment by goodwinvu** [comment]
выделил 24 гига опертивной памяти под проект - зависание не случилось

**Comment by mrshadow300373** [comment]
В любом случае, неотключаемая / непрерываемая расширенная проверка это зло. Писал об этом здесь [https://partners.v8.1c.ru/forum/topic/2048060](https://partners.v8.1c.ru/forum/topic/2048060) но похоже не был услышан.

**Comment by goodwinvu** [comment]
в 21.3.4 проблема решена похоже

**Comment by mrshadow300373** [comment]
> в 21.3.4 проблема решена похоже
Да нет, шла расширенная проверка, записал модуль с изменениями и всё повисло, а в логе шпарит сообщениями:
!MESSAGE Critical system overload (cpu and/or memory): memory 16150466464 used of 25769803776, отвисло где то через 5 минут только.
