### ISSUE TITLE
Ошибка авторизации при импорте

### ISSUE THREAD

**Issue by 7OH** [1C-Company/1c-edt-issues#401]
### Описание ошибки

При импорте конфигурации из базы:
1. Всегда старается использовать х86 платформу, если нужной платформы х86 нету, но есть х64 - используется версия выше.
2. Ошибка авторизации пользователя - дальше не идёт. В Конфигуратор входит отлично.

### Как воспроизвести

1. Ставлю начисто ЕДТ
2. После запуска - выбираю базу в списке, в которую 100% вхожу через конфигуратор - Импорт
3. Автоматически выбрана ПОСЛЕДНЯЯ версия платформы - автоматический поиск расширений выдаёт ошибку
4. Выбираю нужную платформу - ошибка авторизации. 
При этом в диспетчере задач видно, что запускается или версия выше (если нужной х86 версии не оказалось).

### Ожидаемое поведение

1. Версию платформы следовало бы брать из свойств подключения - там уже указана нужная.
2. Если не указано - СНАЧАЛА спрашивать версию, потом что-то искать
3. Использовать указанную разрядность платформы.
4. Искать и х64 версии платформы для использования тоже.
5. Таки импорт должен работать.

### Лог рабочей области

[log.txt](https://github.com/1C-Company/1c-edt-issues/files/8288103/log.txt)
[trace.log](https://github.com/1C-Company/1c-edt-issues/files/8288104/trace.log)

### Версия 1С:EDT

Ruby 2021.3.3 +4

### Операционная система

Windows

### Дополнительная информация

Установлены сервера с 17 по 21. Запущен только 20-й, на котором и крутится база.

**Comment by wolfandw** [comment]
1. В редакторе информационной базы можно настроить как предпочитаемую версию платформы, так и вариант подбора архитектуры.
2. Судя по логам, есть проблемы с доступом к Secure storage Eclipse. Его можно пересоздать, удалив файл C:\Users\профиль_пользователя\.eclipse\org.eclipse.equinox.security\secure_storage. При создании нового хранилища задавать мастер-пароль не обязательно.

**Comment by 7OH** [comment]
1. Да - нашёл до вопроса такую возможность, но согласитесь - поведение некорректное - платформа есть, но её не видит программа.
2. Спасибо - помогло. Может в стартер добавить кнопки очисток вот таких ?

**Comment by vadimeg** [comment]
Предлагаю снять метку Critical, т.к. решение найдено. Либо вообще закрыть баг и создать задачу на улучшение стартера
