### ISSUE TITLE
Методы вида ВопросАсинх ошибочное диагностируются ошибкой доступности в веб-клиенте

### ISSUE THREAD

**Issue by NikitaMikhaylovSB** [1C-Company/1c-edt-issues#406]
### Описание ошибки

Ранее в СП платформы было ошибочное описание доступности на разных клиентах методов вида ВопросАсинх.
В актуальных версиях (8.3.20.1710+) описание исправлено, но EDT не учитывает этого (2021.3.3)

### Как воспроизвести

Добавить в код метод вида ВопросАсинх, убедиться в ошибочной диагностики отсутствия метода на веб-клиенте

### Скриншоты

![изображение](https://user-images.githubusercontent.com/37539066/159228986-d94ff44d-13f0-4c9c-a27f-a46d47cd67a3.png)

### Ожидаемое поведение

Не выполняется ошибочная диагностика ошибки доступности методов

### Версия 1С:EDT

2021.3.3

### Операционная система

Windows

### Установленные плагины

1C:Code style V8, 1C:SSL-support

**Comment by MaksimDzyuba** [comment]
Здравствуйте, видимо проблема решена нами ранее, сейчас не воспроизводится, на версии 2023.2 точно все впорядке
![Снимок1](https://github.com/1C-Company/1c-edt-issues/assets/77277424/c1aaf851-f2cc-4887-b2de-00a90fae6c54)
