### ISSUE TITLE
Частичная загрузка обработчиков расширения при обновлении конфигурации

### ISSUE THREAD

**Issue by EChudnovsky** [1C-Company/1c-edt-issues#410]
### Описание ошибки

При обновлении конфигурации из EDT, обработчики  назначенные в заимствованной форме документапереносятся частично. 
Например:
В расширении для формы документа назначен обработчик "ПередЗаписьюНаСервереПосле". 
После обновления конфигурации загружены были все обработчики, кроме этого.
Сообщений об ошибках в лог-файле не обнаружено.

При попытке исправить ситуацию делались попытки: 
* Полной и частичной очистки проекта
* Удаления приложения и расширения в конфигураторе с последующей полной загрузкой
* Пробовали назначать обработчик в конфигураторе и обратно обновлять конфигурацию из EDT. Все обработчики загружаются кроме "ПередЗаписьюНаСервере" он удаляет назначенное событие.

### Как воспроизвести

1. Заимствовать форму документа в расширение.
2. Назначить обработчик "ПередЗаписьюНаСервереПосле".
3. Обновить конфигурацию.
4. Убедится что обработчик загружен в форме расширения в конфигураторе.

### Скриншоты

![изображение](https://user-images.githubusercontent.com/5530435/160980649-7e5f8833-6657-4e2b-b8ea-4d24867bce26.png)

### Ожидаемое поведение

Реализованный в EDT функционал полностью переносится и применяется в разрабатываемой конфигурации 1С.

### Лог рабочей области

[log.txt](https://github.com/1C-Company/1c-edt-issues/files/8386175/log.txt)

### Версия 1С:EDT

Ruby 2021.3.3

### Операционная система

Linux

### Установленные плагины

1C:Code style V8, 1C:SSL-support, 1C:Language Tool

### Дополнительная информация

1С 8.3.19.1417

**Comment by vadimeg** [comment]
Пока это работать не будет, создали баг на платформу (10238411). В EDT тоже есть проблема с реимпортом событий форм расширений, т.е. работает так же ошибочно, как и в конфигураторе.

Выгрузите в конфигураторе ваше расширение в xml, а затем снова загрузите его. Часть событий из формы пропадет.
Обхода пока тоже не нашли, к сожалению.

**Comment by vadimeg** [comment]
Текущий статус - ждем исправления бага в платформе. По результатам будет принято решение о том, что делать в EDT.

**Comment by vadimeg** [comment]
Исправлено в 8.3.22.1075 (пока не проверял в EDT). Насчет переноса в младшие версии пока нет информации. Сообщу, как что-то будет известно

**Comment by vadimeg** [comment]
Исправлено в 2022.2
