### ISSUE TITLE
Заимствование формы в расширение. Ошибка "Неизвестный объект метаданных" при обновлении разрабатываемого приложения.

### ISSUE THREAD

**Issue by petypen** [1C-Company/1c-edt-issues#416]
### Описание ошибки

Ошибка в том что, при обновлении разрабатываемого приложения (Shift-F7) получаю ошибку:
_Операция конфигурирования завершена неуспешно
Ошибка загрузки/выгрузки конфигурации
Неизвестный объект метаданных - Catalog.Склады.Form.ФормаВыбораГруппы
Неизвестный объект метаданных - Catalog.Склады.Form.ФормаВыбораГруппы_
![2022-04-03 18-00-31 TestExtensions2 - 1C Enterprise Development Tools](https://user-images.githubusercontent.com/6500075/161434185-5ec5a0a8-d813-4515-b822-e500b4f16f41.png)

### Как воспроизвести

Тестирование проводилось на свежей конфигурации "1С Бухгалтерия 8". Конфигурация полностью типовая, на поддержке.

1. Открыл новую рабочую область EDT
2. Из файловой ИБ импортировал конфигурацию в новый (первый в рабочем пространстве) проект
3. Создал новый (второй) проект **Расширения** конфигурации. Форму мастера создания нового расширения оставляю без изменений, как есть по умолчанию.
4. Из основной конфигурации заимствовал ФормуЭлемента справочника Склады
5. В расширении в модуле заимствованной формы добавил пустую процедуру ПриСозданииНаСервере
6. Сохраняю проект и пробую его запустить.

### Скриншоты

![2022-04-03 18-06-14 TestExtensions2 - 1C Enterprise Development Tools (2)](https://user-images.githubusercontent.com/6500075/161434849-6a374354-caf6-4c8c-b1a3-9639e1c735bf.png)

![2022-04-03 18-19-12 TestExtensions2 - TESTACC30 Расширение→Справочники→Склады→Формы→ФормаЭлемента - 1C Enterprise Developme](https://user-images.githubusercontent.com/6500075/161434985-ce63239e-98a2-49e2-bb95-8f4d81f71148.png)

### Ожидаемое поведение

Ожидал, что после заимствования формы справочника в расширение запуск конфигурации будет проходить штатно

### Лог рабочей области

[metadata.zip](https://github.com/1C-Company/1c-edt-issues/files/8404828/metadata.zip)

### Версия 1С:EDT

Ruby 2021.2.12

### Операционная система

Windows

### Установленные плагины

Нет плагинов

### Дополнительная информация

1С:Предприятие 8.3 (8.3.20.1789)
Бухгалтерия предприятия, редакция 3.0 (3.0.109.61)

**Comment by petypen** [comment]
Продолжил наблюдение за проблемой.

Исходя из текста сообщения об ошибки, я сделал предположение, что в расширении не хватает заимствованной формы ФормаВыбораГруппы справочника Склады. 

Добавил форму ФормаВыбораГруппы в расширение. Теперь в расширении две формы.
Опять пробую запустить конфигурацию или обновить разрабатываемое приложение. И получаю новую ошибку:

_Операция конфигурирования завершена неуспешно
Ошибка загрузки/выгрузки конфигурации
Неверное имя команды элемента формы. - Create
Неверное имя команды элемента формы. - Create_

Прикладываю новые скриншоты и лог рабочей области после этой новой ошибки.
![2022-04-03 18-34-31 TestExtensions2 - 1C Enterprise Development Tools](https://user-images.githubusercontent.com/6500075/161435745-ffcd26e1-856c-43c3-89e7-8cfd7189d425.png)
![2022-04-03 18-31-49 TestExtensions2 - 1C Enterprise Development Tools](https://user-images.githubusercontent.com/6500075/161435750-8ad2ef58-e146-42fe-9f26-3ffeae430154.png)
![2022-04-03 18-30-41 TestExtensions2 - 1C Enterprise Development Tools](https://user-images.githubusercontent.com/6500075/161435751-f5191eaf-a80e-4654-80ce-7955bb998802.png)
[metadata.zip](https://github.com/1C-Company/1c-edt-issues/files/8404886/metadata.zip)

**Comment by petypen** [comment]
Уважаемые разработчики, я предполагаю, что проблема заключается в том, что при заимствовании формы объекта EDT не выполняет заимствование объектов от которых зависит эта форма.

Уважаемые разработчики, мне нужно от вас решение или рекомендация по обходу данной ситуации. Я боюсь, что эта проблема может стать блокирующей для моего проекта и придется с EDT возвращаться в конфигуратор.

Готов дать дополнительную информацию для решения этой проблемы.

**Comment by petypen** [comment]
B вот еще что обнаружил с этими ранее заимствованными формами.

Я пытаюсь удалить из расширения заимствованную форму ФормаВыбораГруппы справочника Склады. Форма в расширении совершенно не изменялась. Однако при попытке удалить получаю ошибку, см. скриншот:

_Найдены неполадки:
Редактирование объекта Родитель запрещено_

Если на форме удаления нажать на кнопку "Далее", то на следующем шаге удаления недоступна кнопка "Готово"

При этом, удаление формы элемента не приводит к ошибкам. См. скриншот.

То, что добавленную (заимствованную) в расширение форму нельзя удалить, это как то неправильно. Это ломает сценарии нормальной работы в EDT 

![2022-04-03 18-34-31 TestExtensions2 - 1C Enterprise Development Tools](https://user-images.githubusercontent.com/6500075/161437519-cd67e284-ecfa-42cb-b417-46296d49804f.png)
![2022-04-03 19-13-26 TestExtensions2 - 1C Enterprise Development Tools](https://user-images.githubusercontent.com/6500075/161437521-f12c955e-ad18-4d56-9673-3d8c8cf4d859.png)
![2022-04-03 19-15-57 TestExtensions2 - 1C Enterprise Development Tools](https://user-images.githubusercontent.com/6500075/161437523-a4244db0-a472-4285-8e44-abb2c211c6eb.png)

**Comment by vadimeg** [comment]
@petypen Попробуйте сделать полную загрузку в информационную базу после того, как добавили форму выбора группы в расширение. В 2021.3 это работает.

**Comment by vadimeg** [comment]
С удалением формы выбора проблему не смог воспроизвести в новой версии.

**Comment by petypen** [comment]
@vadimeg Вадим, добрый день
По вашей рекомендации сделал: 
1. Вызвал команду Приложения - Обновить конфигурацию. 
2. В окне Загрузка конфигурации устанавливаю галочку "Загрузить конфигурацию полностью"
3. Спустя 30 минут появилось окно со списком объектов, которые будут загружены в информационную базу. Соглашаюсь со списком.
4. Появляется око с ошибкой "Неверное имя команды элемента формы. - Create" См. скриншот.

Так же прикладываю лог рабочей области после проделанных операций
images.githubusercontent.com/6500075/161587571-c85615d4-6159-48dd-9ed3-3a48211e107f.png)
[metadata.zip](https://github.com/1C-Company/1c-edt-issues/files/8411386/metadata.zip)


![2022-04-04 19-10-55 TestExtensions2 - 1C Enterprise Development Tools](https://user-images.githubusercontent.com/6500075/161587562-95a28f14-4835-4d57-8d9d-a269d37a69e3.png)
![2022-04-04 18-41-04 TestExtensions2 - 1C Enterprise Development Tools](https://user-

**Comment by petypen** [comment]
@vadimeg попытался повторить ваш сценарий https://github.com/1C-Company/1c-edt-issues/issues/416#issuecomment-1087703952 на версии EDT 2021.3.3

И так, у меня конфигурация и расширение в которое заимствовано две формы справочника Склады.

1. Запускаю режим "Загрузить конфигурацию полностью"
![2022-04-04 20-18-03 TestExtensions3 - 1C Enterprise Development Tools](https://user-images.githubusercontent.com/6500075/161602737-94def132-74da-4df3-85fe-e77fa8af9ded.png)

2. В диалоге "Реорганизация информации" нажимаю "Принять"
![2022-04-04 20-32-57 TestExtensions3 - 1C Enterprise Development Tools](https://user-images.githubusercontent.com/6500075/161602860-29d3500f-0d85-4c65-b68b-15fa0eb4a981.png)

3. Получаю Ошибка исполнения 1С Предприятие
![2022-04-04 20-36-43 TestExtensions3 - 1C Enterprise Development Tools](https://user-images.githubusercontent.com/6500075/161602983-e408a324-f363-481d-82ad-f5b29ad57127.png)

Решил посмотреть, а что же в конфигураторе. А там ужас. Несмотря на то, что процесс обновления разрабатываемого приложения ни разу не был доведен до конца штатно (без ошибок) в конфигураторе вижу аж ДВЕ конфигурации расширения. Просто руки опус
![2022-04-04 20-48-13 Конфигуратор - Бухгалтерия предприятия, редакция 3 0](https://user-images.githubusercontent.com/6500075/161603471-c1950c6d-bb71-49a7-91f2-d2564254b326.png)
каются.

Лог рабочей области после всех операций
[metadata.zip](https://github.com/1C-Company/1c-edt-issues/files/8412045/metadata.zip)

**Comment by petypen** [comment]
Попробовал сценарий из предыдущего сообщения прогнать еще раз.
Предварительно в конфигураторе удалил оба расширения, которые я разрабатываю в EDT

При запуске полной загрузки конфигурации получил ту же ошибку.
Однако в конфигураторе появилось расширение и оно пустое
![2022-04-04 21-18-34 Конфигуратор - Бухгалтерия предприятия, редакция 3 0](https://user-images.githubusercontent.com/6500075/161607069-688fcca4-d808-4cd6-accc-cc302ed20d22.png)

Лог рабочей области после этой операции
[metadata.zip](https://github.com/1C-Company/1c-edt-issues/files/8412163/metadata.zip)

**Comment by vadimeg** [comment]
Видимо после экспериментов наплодились расширения. Попробуйте удалить в конфигураторе лишние расширения, потом в EDT заимпортировать информационную базу, создать расширение, добавить 2 формы (форму элемента и выбора) в расширение, а затем полную выгрузку конфигурации в базу.

Нашлись 2 проблемы - одна в платформе (форма выбора, которая автоматически была заимствована, оказалась не до конца скопирована) и одна в EDT (нет автоматического заимствования формы выбора при наличии ссылок на нее в заимствуемой форме). На платформу завели баг, в EDT баг исправим.

**Comment by petypen** [comment]
Перепроверил проблему на Ruby 2021.3.4, к сожалению она не решена

Выполнил:
1. Из основной конфигурации заимствовал ФормуЭлемента справочника Склады
2. Сохраняю проект и пробую его запустить.

Получаю ту же ошибку Неизвестный объект метаданных - Catalog.Склады.Form.ФормаВыбораГруппы
![2022-04-16 23-01-32 ACC30_WS - ACC30 EPF1_PROJECT→Справочники→Склады→Формы→ФормаЭлемента - 1C Enterprise Development Tools](https://user-images.githubusercontent.com/6500075/163689773-c1fc0fa3-faa5-4e23-b3ff-bd6bb4cd04d5.png)

Лог рабочей области
[metadata.zip](https://github.com/1C-Company/1c-edt-issues/files/8500567/metadata.zip)

**Comment by vadimeg** [comment]
В 2021.3.4 исправление не попало, т.к. не успело пройти тестирование, а релиз уже готовился к выпуску. Попадет в следующий.

**Comment by vadimeg** [comment]
Исправлена в 2022.1

**Comment by konininvv** [comment]
2023.3.3 наблюдаю такую проблему: 
![изображение](https://github.com/1C-Company/1c-edt-issues/assets/102820591/7fcefd99-d801-4acc-baf3-6fdadaddaf37)
