### ISSUE TITLE
Зависание процесса запуска EDT после установки плагинов

### ISSUE THREAD

**Issue by Desar14** [1C-Company/1c-edt-issues#42]
## Опишите ошибку

При установке плагинов EDT предлагает сделать перезапуск для окончания установки ПО. 
После этого ЕДТ не запускается и висит на сплэше, необходимо срубать через диспетчер задач и запускать заново. 
На версиях до 2021.2.8 хватало одного раза, на 2021.2.8 ЕДТ таки запускается только спустя несколько десятков раз - это очень раздражает.

## Как воспроизвести

Установить новый плагин в рабочую облатсь (v8 ssl support, v8-code-style) и согласиться с предложением EDT перезапуститься.

## Ожидаемое поведение

После установки плагинов ЕДТ запускается корректно и сразу.

## Лог рабочей области
 
В лог при этом новых записей не добавляется.

## Окружение (пожалуйста укажите информацию):

 - OS: Windows 10
 - Версия 1C:EDT 2021.2.8
 - Версия платформы 1С '8.3.19.1351'

**Comment by Daabramov** [comment]
Постоянная история на всех компьютерах
у меня и коллег

**Comment by Desar14** [comment]
Оказывается, если проявить терпение и подождать минут 5-10, то едт всё же запускается. Однако, хотелось бы иметь какое-то понимание, что она не висит. И ускорить запуск в таких ситуациях.

**Comment by IvanMaslikov** [comment]
Аналогичная проблема и при обновлении самой EDT. Первый запуск после обновления всегда долго думает и в результате падает по таймауту. Со второго раза запускается моментально.

**Comment by Valarrus** [comment]
Поддержу. 2021.2.12 проблема актуальна.

**Comment by Erik773** [comment]
Задача закрывается из-за непредоставления запрошенных данных.
Задачу можно переоткрыть, если данные будут предоставлены.

**Comment by Erik773** [comment]
Уточнение: 
Дамп не требуется, проблема подтверждена, но по техническим причинам в обозримое время исправление не планируется.
При появлении технической возможности, данная задача будет внесена в планы, с соответствующим уведомлением/переоткрытием.

**Comment by fedoseenkoff** [comment]
@tretyakevich @Erik773 Отсутствие времени/желания/технической возможности не отменяет сам факт наличия данной ошибки.  Не понимаю, почему закрыта?

**Comment by Erik773** [comment]
@fedoseenkoff  задача зарегистрирована во внутреннем трэкере, признана важной, как только будет техническая возможность ее реализации - задачу в гитхабе переоткроем, 
Оставлять задачу открытой, не имея возможности ее исправить - кажется неэффективным с точки зрения оперативного реагирования на вновь возникающие проблемы 
Но как вариант мы можем добавить статус типа "Не планируется в ближайшее время по техническим причинам", переоткрыть задачу и поместить туда, это будет более приемлемо?

**Comment by ilya2184** [comment]
Не зависает в прямом смысле: почти не потребляет ресурсы и если подождать, а потом ещё подождать (не знаю сколько, просто ушел чай попить - может минут 10) в результате запуск будет произведен.
