### ISSUE TITLE
В расширениях для основных форм, возникает ошибка: Свойство "Имя свойства" имеет некорректное значение

### ISSUE THREAD

**Issue by agibalovsa** [1C-Company/1c-edt-issues#423]
### Описание ошибки

Весь журнал ошибок засыпан исключениями:
Свойство "Данные картинки строки" имеет некорректное значение "Список.DefaultPicture": 1 сегмент "Список" ссылается на неизвестный объект form-data-path

### Как воспроизвести

Не знаю, у меня воспроизвелось после обновления EDT на релиз кандидат.

### Скриншоты

![image](https://user-images.githubusercontent.com/14235747/162036148-4e106e1d-b62e-489c-9330-b457448d7bf4.png)

### Ожидаемое поведение

Устранить вывод данных сообщений.

### Лог рабочей области

[log.zip](https://github.com/1C-Company/1c-edt-issues/files/8429208/log.zip)

### Версия 1С:EDT

Ruby 2021.3.3

### Операционная система

Windows

### Установленные плагины

1C:Code style V8, 1C:SSL-support

**Comment by agibalovsa** [comment]
1С:Предприятие 8.3 (8.3.18.1616)
Версию проекта не менял. Произошло после обновления EDT на релиз кандидат. Ни на что не влияет, просто выходят такие сообщения.

**Comment by vadimeg** [comment]
> Можно расширение пришлю на почту куда-нибудь?

Можно в телеграм в личку или в облако

**Comment by Kellendros007** [comment]
У меня аналогичная проблема на последнем релизе EDT. Расширение изначально делалось в конфигураторе.

**Comment by vadimeg** [comment]
Исправлено в
https://github.com/1C-Company/v8-code-style/issues/1037
https://github.com/1C-Company/dt-project-checks/issues/27
