### ISSUE TITLE
Заимствование формы в расширение. Некорректный перенос метаданных.

### ISSUE THREAD

**Issue by petypen** [1C-Company/1c-edt-issues#428]
### Описание ошибки

Ошибка в том что, при заимствовании формы в расширение происходит потеря метаданных. Расширение с заимствованной формой становится нерабочим и EDT не может обновить разрабатываемое приложение после заимствования формы. 

### Как воспроизвести

Тестирование и изучение проблемы производилось на конфигурации 
Демонстрационная конфигурация "Библиотека стандартных подсистем", редакция 3.1 версия: 3.1.6.180
Разрабатываемое приложение размещено в файловой информационной базе
Платформа 8.3.20.1789 64бит

### Вводная:
Создано два рабочих пространства:
* PEN007_WS - рабочее пространство в котором есть проект конфигурации и проект расширения __который создан в EDT__ Это проблемное рабочее пространство.
* PEN008_WS - рабочее пространство в котором есть проект конфигурации и проект расширения, причем **расширение создано в конфигураторе** и потом импортировано в EDT одновременно с основной конфигурацией.

В расширении, которое создано в EDT и в расширении, которое создано в конфигураторе было выполнено только одно действие, а именно заимствована ФормаЭлемента справочника Пользователи. Пример на скриншоте.
![2022-04-09 22-03-11 PEN007_WS - 1C Enterprise Development Tools](https://user-images.githubusercontent.com/6500075/162588247-8dd7814a-d6a1-46cb-b56e-0fb0f10a77bd.png)

### Наблюдение 1
В рабочем пространстве PEN007_WS, где расширение было создано в EDT есть отличия в метаданных Базовой формы и Заимствованной формы. Важно то, что в расширении над формой никаких действий после заимствования не производилось. Проблема видна на скриншоте:
![2022-04-09 22-11-51 PEN007_WS - Двухстороннее сравнение 'PEN007_PFI_PROJECT src Catalogs Пользователи Forms ФормаЭлемента B](https://user-images.githubusercontent.com/6500075/162588500-04918e6f-161a-4970-98ce-efd5cd91ab5a.png)

при этом, в рабочем пространстве PEN008_WS, где расширение было создано в конфигураторе такого отличия нет. Базовая форма в точности равна заимствованной форме. Это видно на скриншоте:
![2022-04-09 22-16-47 PEN008_WS - Двухстороннее сравнение 'SSL_31_PROJECT PEN008_PFI_CONF src Catalogs Пользователи Forms Фор](https://user-images.githubusercontent.com/6500075/162588615-6b7ed55a-463a-49f5-b020-b1c6e8b06bb3.png)

### Наблюдение 2
В рабочем пространстве PEN007_WS, где форма была заимствована в EDT происходит некорректная обработка команд формы, а именно для команд, которые не были заимствованы в расширение существует возможность установить связь с методами команды. см. скриншот.
![2022-04-09 22-54-15 Скриншот экрана](https://user-images.githubusercontent.com/6500075/162589845-919c8100-126c-4dc6-9d03-bef00b5d7003.png)

В рабочем пространстве PEN008_WS, где форма была заимствована в конфигураторе  EDT  не разрешает добавлять метод для незаимствованных элементов форм. 
![2022-04-09 23-12-33 Скриншот экрана](https://user-images.githubusercontent.com/6500075/162590213-18c0c952-36dd-42e6-90fd-be881d08e0e8.png)

### Наблюдение 3
При обновлении разрабатываемого приложения в рабочем пространстве PEN007_WS (где расширение было создано в EDT) получаем ошибку 
Неверное имя команды элемента формы. - WriteAndClose
![2022-04-09 23-30-15 PEN007_WS - 1C Enterprise Development Tools](https://user-images.githubusercontent.com/6500075/162590667-1b6627ea-b9d5-467f-a160-153bbc7ff643.png)

При сравнении метаданных формы элемента справочника Пользователи через VSCode в узле 
```xml
<items xsi:type="form:Button">
      <name>ФормаЗаписатьИЗакрыть</name>
```
обнаружено:
1.  в расширении, которое создано в конфигураторе отсутствует значение узла commandName
![2022-04-09 23-38-15 PEN007_Form form ↔ PEN008_Form form - EDT - Visual Studio Code](https://user-images.githubusercontent.com/6500075/162590902-cae0a2ba-6ec6-441d-8b9e-9fbedb81a5a9.png)

2. в расширении, которое создано в конфигураторе отсутствуют узел excludedCommands
![2022-04-09 23-40-31 PEN007_Form form ↔ PEN008_Form form - EDT - Visual Studio Code](https://user-images.githubusercontent.com/6500075/162590992-39bbae50-5ebd-4396-a2c5-7456bd97ada2.png)

Что я попробовал

Закомментировать узел  commandName
```xml
      <!--
      <commandName>Form.Command.ЗаписатьИЗакрыть</commandName>
      -->
```

Закомментировать узел excludedCommands
```xml
  <!--
  <excludedCommands>WriteAndClose</excludedCommands>
  -->
```
однако, это не привело к желаемому результату. Обновить конфигурацию так же не получается, однако ошибок на одну меньше.
![2022-04-10 00-05-04 PEN007_WS - 1C Enterprise Development Tools](https://user-images.githubusercontent.com/6500075/162591627-894775a6-873f-4248-a3a9-beaa8587c2d1.png)

### Ожидаемое поведение

После заимствования формы она работает и позволяет обновить приложение.

### Лог рабочей области

1. Лог области, где расширение создавалось в EDT  и где есть проблемы
[metadata_PEN007.zip](https://github.com/1C-Company/1c-edt-issues/files/8457770/metadata_PEN007.zip)

2. Лог области, где расширение создавалось в Конфигуратор
[metadata_PEN008.zip](https://github.com/1C-Company/1c-edt-issues/files/8457775/metadata_PEN008.zip)
е

### Версия 1С:EDT

Ruby 2021.2.12

### Операционная система

Windows

### Установленные плагины

Нет плагинов

**Comment by petypen** [comment]
@vadimeg Вадим, проблему с командой WriteAndClose я решил анализируя различия в файлах Form.form, которые взяты из расширения созданного в EDT и из расширения созданного в конфигураторе.

На скриншоте видно как много отличий между формами заимствованными в EDT и в Конфигураторе.
![2022-04-11 21-39-20 PEN007_Form form ↔ PEN008_Form form - EDT - Visual Studio Code](https://user-images.githubusercontent.com/6500075/162808627-0171c454-1aa9-4f83-99d5-c36eb899d612.png)

Во вложении XML файлы форм:
PEN007_Form.form - форма, которая была заимствована в EDT
PEN008_Form.form - форма, которая была заимствована в конфигураторе

[EDT.zip](https://github.com/1C-Company/1c-edt-issues/files/8466908/EDT.zip)

**Comment by JasonT57** [comment]
Версия Ruby 2021.3.4 Проблема не исправлена:
Неверное имя команды элемента формы. - WriteAndClose
Неверное имя команды элемента формы. - Post
Помогает удаление строчек ExcludedCommands
