### ISSUE TITLE
Сделать настройки проверок для версии edt. Использовать их как шаблон при создании нового проекта.

### ISSUE THREAD

**Issue by DmitryShvaika** [1C-Company/1c-edt-issues#43]
## Описание проблемы

Сейчас  приходится загружать проект, ждать когда пройдет валидация. Только затем доступным становится изменение настроек валидации для проекта. При завершении редактирования запускается проверка повторно.

 
 
## Описание решения проблемы
 
Сделать настройки "по умолчанию" для версии Edt. Чтобы при создании проекта они копировались в проект и валидация выполнялась сразу с этими настройками.

**Comment by tretyakevich** [comment]
Что означает для версии edt? В составе определенной сборки EDT? Если так - то для всех сторонних провайдеров проверок этот механизм будет неиспользуемым. На уровне каждого бандла, поставляющего проверки? Это уже есть, настройки каждой проверки по умолчанию. Правда, непонятно, почему они должны быть разные для разных версий EDt.

Или мы обсуждаем просто механизм дефолтов на уровне воркспейса.
Для подобного решения нужен некий механизм создания преконфигурированного workspace-а, нативный в EDT (в составе некоторого средства автоматизации по созданию воркспейсов, которого пока нет), который сможет установить некий набор библиотек с проверками + профили настроек для них. 
Пока слишком неопределено и в обозримом будущем в планах такого не планировалось.

В случае, если такого механизма нет - то все сводится к тому, что кто-то в настройках WS (каждый раз при создании WS, но не проекта) указывает некий внешний файл настроек, который потом уже используется при создании/импорте проектов.
Это да, понятно как реализовать.

Но у этого решения есть определенная жестко очерченная область применения. Его можно использовать на WS, в котором ведут разработку только родственных проектов (например от одного базового решения). В противном случае часть фильтров по объектам, исключения и т.п. будут просто невалидны.  Если именно такой сценарий является целевым - тогда тоже понятно.

Также прошу учесть тот факт, что настройки самих проверок таким образом можно будет переносить/клонировать. Однако подавления - принципиально нет.

**Comment by DoublesunRUS** [comment]
Лично мне надо при импорте проекта из ИБ указать для него настройки валидации по умолчанию.
Иначе после импорта сразу запускается ненужная мне проверка. Или нужная, но без исключений которые я настроил.
Про настройки подавления, я как-то устно говорил что текущий механизм хранения подавления проверок неудобен.
Мне надо для всех проектов ЗУП одинаковые настройки подавления. Или очень похожие. А сейчас эти настройки подавления закопаны глубоко вместе с метаданными и их неудобно копировать из проекта в проект.

**Comment by DmitryShvaika** [comment]
Проверки, я заметил всегда выполняются полностью с версии 2021.5 вроде. А отключением проверок просто фильтруются выводимые.

**Comment by tretyakevich** [comment]
>>Пока только проект внешних обработок использую в одной рабочей области вместе с основным

В этом случае тут применим только вариант "шаблон на тип проекта (расширение, внешние объекты и т.п.)". Реализуемо, но насчет реальной применимости сказать ничего не могу, опыта не хватает

**Comment by tretyakevich** [comment]
>Лично мне надо при импорте проекта из ИБ указать для него настройки валидации по умолчанию.
Иначе после импорта сразу запускается ненужная мне проверка. Или нужная, но без исключений которые я настроил.

Да, это похоже на то, что выше обсуждали - просто набор настроек на уровне WS и ручной выбор. Ок, понятно.

**Comment by tretyakevich** [comment]
>Проверки, я заметил всегда выполняются полностью с версии 2021.5 вроде. А отключением проверок просто фильтруются выводимые.

Это не так. Были ошибки в RC, которые вызывали перестроение, в 2021.2.8 должны быть исправлены.

**Comment by tretyakevich** [comment]
>Мне надо для всех проектов ЗУП одинаковые настройки подавления. Или очень похожие. А сейчас эти настройки подавления закопаны глубоко вместе с метаданными и их неудобно копировать из проекта в проект.
Да, у меня отмечено, если нужно - заводи в виде запроса )
Пока есть граничные мнения об этой фиче, поэтому тут, скорее всего, нужен какой-то выбор либо расширяемость поведения. Пока непонятно.

**Comment by DoublesunRUS** [comment]
> > Мне надо для всех проектов ЗУП одинаковые настройки подавления. Или очень похожие. А сейчас эти настройки подавления закопаны глубоко вместе с метаданными и их неудобно копировать из проекта в проект.
> 
> Пока есть граничные мнения об этой фиче, поэтому тут, скорее всего, нужен какой-то выбор либо расширяемость поведения. Пока непонятно.

Лично у меня мнение что все настройки должны храниться в папке .settings.
И тогда проблем бы не было никаких. :)

**Comment by tretyakevich** [comment]
> Лично у меня мнение что все настройки должны храниться в папке .settings.
> И тогда проблем бы не было никаких. :)

Да, я помню ) Но я не готов там держать БЕЗУСЛОВНО дерево каталогов со сложностью ~ основной конфигурации, или дикие планарные имена для всех исключений, или один большой файл, который будет уходить в конфликт при любом изменении (в Git-е). 

Вот и получается,  что тут либо нужна возможность кастомизации, либо выбор варианта, либо вариант портабельных подавлений (в виде какого-то переносимого артефакта), либо вообще альтернативное решение (например копировщик исключений, хорошо интегрированный с продуктом).

**Comment by DmitryShvaika** [comment]
Вариант реализации: В параметры программы добавить профили валидации, дать возможность выбирать свой профиль валидации как профиль по умолчанию, который должен применяться при импорте проекта из информационной базы.

**Comment by DmitryShvaika** [comment]
Еще вариант реализации: при импорте проекта из информационной базы спрашивать - проверять ли проект... Или оставить как есть. Чтобы в промежутке между импортом и проверкой проекта была возможность выбрать профиль проверок. Цель - проверка проекта сразу с заданным профилем. Сейчас при импорте проект проверяется с профилем по умолчанию, затем повторно с заданным профилем.

**Comment by DmitryShvaika** [comment]
Все придумал как красиво сделать... напишу отдельную задачу - эта не совсем внятная
