### ISSUE TITLE
Не обновляются пути элементов форм

### ISSUE THREAD

**Issue by agibalovsa** [1C-Company/1c-edt-issues#436]
### Описание ошибки

Не обновляются пути в элементах расширенной формы, если они были изменены в основной форме.

### Как воспроизвести

1) Была таблица в форме с путем к табличной части объекта "Объект.ВключаемыеПроекты".
2) Форма была расширена.
3) В основной конфигурации поменяли путь к таблице реквизита формы "ВключаемыеПроекты". Названи все те же самые.
4) После обновления формы, путь в таблице в расширенной форме не меняется

### Скриншоты

![image](https://user-images.githubusercontent.com/14235747/163560497-f028dbf9-8395-465f-b918-25fcced7c28e.png)

![image](https://user-images.githubusercontent.com/14235747/163560647-1ff8ffba-9268-47f3-99b1-24fe735d89b0.png)

![image](https://user-images.githubusercontent.com/14235747/163560702-2510adec-846e-4069-b6ee-7ca199c71a3b.png)

### Ожидаемое поведение

Необходимо исправить ошибку.

### Лог рабочей области

[metadata.zip](https://github.com/1C-Company/1c-edt-issues/files/8495457/metadata.zip)

### Версия 1С:EDT

Ruby 2021.3.3

### Операционная система

Windows

### Установленные плагины

1C:Code style V8, 1C:SSL-support

**Comment by vadimeg** [comment]
Исправлено в 2022.2
