### ISSUE TITLE
Во время выполнения операции экспорта произошла ошибока

### ISSUE THREAD

**Issue by SerGeoSik** [1C-Company/1c-edt-issues#443]
### Описание ошибки

Ошибка в том что невозможно запустить режим 1С:Предприятие (в т.ч. отладку) из EDT.

### Как воспроизвести

Контекст:
Windows server 2019 Datacenter
Платформа: 1С:Предприятие 8.3 (8.3.20.1674)
Конфигурация: 1С:ERP Управление предприятием 2 (2.5.7.336)

При попытке запустить отладку EDT пишет, что "приложение требует полной загрузки обновления", запускаешь процесс, далее получаешь сообщение: "Во время выполнения операции экспорта произошла ошибка" (см. скриншот).

### Скриншоты

![ОшибкаЕДТ1](https://user-images.githubusercontent.com/13977857/164480988-2868525c-0cad-4cef-b381-ba785fc20316.png)
![ОшибкаЕДТ2](https://user-images.githubusercontent.com/13977857/164482936-e2082f2d-ac67-411f-bd20-26eea4a8b730.jpg)

### Ожидаемое поведение

Должен корректно запускаться режим 1С:Предприятие (отладка).

### Лог рабочей области

[1cedtstart.log](https://github.com/1C-Company/1c-edt-issues/files/8531972/1cedtstart.log)

### Версия 1С:EDT

Ruby 2021.3.4

### Операционная система

Windows

**Comment by vadimeg** [comment]
Пришлите, пожалуйста, ссылку на ERP, адаптированную под 20-ю платформу

**Comment by vadimeg** [comment]
@SerGeoSik ?
