### ISSUE TITLE
В форму журнала невозможно добавить команду создания документа, а импорт такого журнала из конфигуратора, удаляет эти команды

### ISSUE THREAD

**Issue by grumagargler** [1C-Company/1c-edt-issues#447]
### Описание ошибки

Если в журнал документов, на командную панель добавить команду создания документа, то импорт такой конфигурации в проект едт приведет к очистке свойств этой команды, и ее неработоспособности в пользовательком интерфейсе. Создать в едт такую команду возможности нет.

### Как воспроизвести

Импортируйте вложенную мини-базу в едт, затем выполнине полное обновление приложения и запустите программу. В результате, команда Document1, отмеченная на картинке стрелкой, исчезнет из пользовательского интерфейса.
![092055-0425](https://user-images.githubusercontent.com/15623029/165099704-3819c9bf-b59f-438f-aaa5-249b0ce46271.png)

А добавить такую команду, через едт возможности нет.

[1Cv8.dt.zip](https://github.com/1C-Company/1c-edt-issues/files/8554939/1Cv8.dt.zip)

### Ожидаемое поведение

Среда должна предоставлять возможность создания команды указанного типа.

### Лог рабочей области

[Untitled.log](https://github.com/1C-Company/1c-edt-issues/files/8555017/Untitled.log)
[trace.log](https://github.com/1C-Company/1c-edt-issues/files/8555019/trace.log)

### Версия 1С:EDT

Ruby 2021.3.4

### Операционная система

Linux

### Установленные плагины

Нет плагинов

**Comment by vadimeg** [comment]
@grumagargler А какая версия платформы использовалась?

В логе полезной информации нет. Кроме этой: Linux Mint 20.3 Una (una) is unsupported operation system.

**Comment by grumagargler** [comment]
@vadimeg
> А какая версия платформы использовалась?
8.3.20.1710, 8.3.20.1789
> В логе полезной информации нет. Кроме этой: Linux Mint 20.3 Una (una) is unsupported operation system.
Полагал, что едт может работать под любой версией убунту и ей производных. Так или иначе, проблема воспроизводится и под windows. Судя по вопросам и требованию оформления запроса, вы выполнили дейсвтвия из раздела "Как воспроизвести" и вас все получилось?
Спасибо.

**Comment by grumagargler** [comment]
@vadimeg 

> А какая версия платформы использовалась?

Версию платформы вы также можете найти в приложенном к изначальному сообщению, файле trace.log

**Comment by vadimeg** [comment]
Воспроизвел на windows

**Comment by vadimeg** [comment]
Исправлено в 2022.1
