### ISSUE TITLE
Некорректное сообщение об ошибке

### ISSUE THREAD

**Issue by Desar14** [1C-Company/1c-edt-issues#45]
## Опишите ошибку

Для переменной с именем "СтатусСообщения" в любом контексте вылазит системная ошибка. 
![image](https://user-images.githubusercontent.com/66671103/139678433-a20b1fae-8e29-4a06-a75e-1f3b47e3fcc8.png)

## Как воспроизвести

В общем модуле или модуле формы ввести 

`СтатусСообщения = "";`

## Ожидаемое поведение

Отсутствие данной ошибки.

## Лог рабочей области
 
[log.log](https://github.com/1C-Company/1c-edt-issues/files/7453525/log.log)

[trace.log](https://github.com/1C-Company/1c-edt-issues/files/7453517/trace.log)

## Окружение (пожалуйста укажите информацию):

 - OS:  Windows 10
 - Версия 1C:EDT 2021.2.8
 - Версия платформы 1С 8.3.19.1351

**Comment by MaksimDzyuba** [comment]
Здравствуйте, повторил Ваш сценарий, платформа в отладке сообщает о ошибке, так как есть такое системное перечисление, как "СтатусСообщения". Ошибку закрываю, если есть какие-то другие доводы, то просьба переоткрыть и пояснить, спасибо!
![bandicam-2023-11-15-13-46-09-074](https://github.com/1C-Company/1c-edt-issues/assets/77277424/f05ea8ff-6ce1-4c84-a041-1bb57353f25d)
