### ISSUE TITLE
Панель выражения. Улучшить редактирование ввода полей.

### ISSUE THREAD

**Issue by KovAlexey** [1C-Company/1c-edt-issues#453]
### Описание проблемы

Есть такая проблема...
![изображение](https://user-images.githubusercontent.com/16429518/165883111-744c5523-dcfd-4ee6-8c3b-308cae1d5c8c.png)
Клик мышкой сразу начинает редактирование и выделяет весь текст (а это не нужно)
Второй же клик мышкой редактирование отменяет.
Работать неудобно, каретку по тексту переставлять неудобно, что-то отредактировать - неудобно.

### Описание решения проблемы

Предлагаю сделать так...

Первый клик переводит поле в режим редактирования.
А все дальнейшие - только двигают каретку, выделяют и так далее.
Выделить текст - тройным щелчком можно было бы в таком варианте.

**Comment by DmitryBelov-e1c** [comment]
@KovAlexey Добрый день, а как посмотрите на внедрение классического редактирования по двойному нажатию с кареткой в конце имени и соответственно следующий дабл клик - выделение всего?

**Comment by KovAlexey** [comment]
> @KovAlexey Добрый день, а как посмотрите на внедрение классического редактирования по двойному нажатию с кареткой в конце имени и соответственно следующий дабл клик - выделение всего?

Да, тоже отличный вариант.
Главное, чтоб можно было удобно работать с полем ввода, была поддержка клавиш, возможность выделять, редактировать, переключаться на другое окно (в идеале, в т.ч. в редактор кода, т.к. иногда нужно просто скопировать некоторые значения)
Совсем идеально, если бы панель выражений содержала контекстную подсказку.

И просьба обратите внимание на фокус. Окошко не должно само закрываться. Потеря какого-нибудь сложного выражения очень расстраивает

**Comment by DmitryBelov-e1c** [comment]
>> Но на самом деле без параллельного закрытия этого #454 работа будет по прежнему не очень удобна.
@KovAlexey Это не совсем верное использование обозначенного в задаче по ссылке hover-окна - длинные выражения не должны теряться, так как предполагаются для обработки в окне перспективы (из этой задачи).
По контекстной подсказке - пока не в приоритете, но планируем. Переключение окна без закрытия поля для редактирования вряд ли будет реализовано - можно заполнить с copy-paste в несколько заходов без потери ввода.

**Comment by KovAlexey** [comment]
>Это не совсем верное использование обозначенного в задаче по ссылке hover-окна - длинные выражения не должны теряться, так как предполагаются для обработки в окне перспективы (из этой задачи).

В реальной практике длинные выражения используются для снятия дампов, разового выполнения функций и изменения значений. Из окна перспективы - это значит после добавления выражения мне его тут же надо будет удалить. Или у меня будет столько дампов запроса, сколько я строк в отладке пройду. Это кажется очень неудобным

**Comment by KovAlexey** [comment]
>  Переключение окна без закрытия поля для редактирования вряд ли будет реализовано - можно заполнить с copy-paste в несколько заходов без потери ввода.

Ну это и вполне нормально.
Я по запаре имел ввиду именно всплывающее окошко вычислить, когда писал это. Так что здесь я зря про это упомянул

**Comment by DmitryBelov-e1c** [comment]
@KovAlexey Добрый день, в тестовой сборке 2023.3 произошла замена Выражения -> Выражения встроенного языка. Хотелось бы по возможности получить обратную связь о работе с обновлённой панелью. Спасибо!

**Comment by KovAlexey** [comment]
Основную проблему так и не решили.
Невозможность работы с редакторами текста, пока панель открыта.
Любой клик мимо закрывает панель. Это неудобно
