### ISSUE TITLE
НастройкиСериализацииJSON.ФорматСериализацииДат - ошибка в контекстной подсказке

### ISSUE THREAD

**Issue by AndreiSevostyanov** [1C-Company/1c-edt-issues#458]
### Описание ошибки

Для свойства "ФорматСериализацииДаты" объекта НастройкиСериализацииJSON в контектсной подсказке выводится не правильное имя свойства
![err-edt_1](https://user-images.githubusercontent.com/11883224/166317730-d19a745d-c3f3-477b-829d-cd6f4a574809.png)
.

### Как воспроизвести

Создать объект НастройкиСериализацииJSON вызвать контекстную подсказку (Ctrl + space)

### Скриншоты

![err-edt_1](https://user-images.githubusercontent.com/11883224/166318498-318f8a0d-5f20-4c8e-be61-af15f6abe5db.png)

### Ожидаемое поведение

В контекстной подсказке должно выводится правильное имя свойства "ФорматСериализацииДаты"

### Лог рабочей области

Не требуется

### Версия 1С:EDT

2021.3.4

### Операционная система

Windows

### Установленные плагины

1C:Code style V8, 1C:SSL-support

### Дополнительная информация

Платформа 8.3.21.1302

**Comment by MaksimDzyuba** [comment]
Здравствуйте, данной проблемы уже нет, я, к сожалению, точно не могу быстро вспомнить в какой версии исправили, но давно, закрываю ошибку
![Снимок экрана 2023-11-15 в 0 44 37](https://github.com/1C-Company/1c-edt-issues/assets/77277424/eaa9da25-31cc-4265-a6a4-005539246bd2)
