### ISSUE TITLE
В списке реквизитов обработки отсутствует колонка с флажком "Сохранение"

### ISSUE THREAD

**Issue by mrshadow300373** [1C-Company/1c-edt-issues#468]
### Описание ошибки

Не мог понять, почему не сохраняются настройки (значения реквизитов обработки и формы) внешней обработки, несмотря на то, что корня формы необходимые реквизиты настроены и включены:
![1652896938136](https://user-images.githubusercontent.com/34220218/169112701-ad2c7b88-f1fe-4331-9e2d-e023a0300751.jpg)
Сложилось ощущение что чего то не хватает:
![1652897000851](https://user-images.githubusercontent.com/34220218/169112872-353ef81b-232c-4498-a70b-9800a1ca8994.jpg)
В конфигураторе вот она:
![1652897025847](https://user-images.githubusercontent.com/34220218/169112976-c72afa01-65e3-4b1b-8055-b5343562f6ce.jpg)

### Как воспроизвести

Создать в проекте с версией платформы 8.3.20 внешнюю обработку добавить в ней реквизит или реквизит формы с типом строка (Н), (подозреваю от типа не зависит) попытаться настроить сохранение как на скринах. 
**_Важный момент_**, колонка не появляется в момент включения возможности сохранения в форме, если форму переоткрыть то колонка появляется. При выключении возможности сохранять, колонка исчезает. Т.е. если в какой то форме уже было включено, и колонка отображается - убрать возможность сохранения данных формы, записать форму и попробовать включить заново.

### Ожидаемое поведение

Должна быть возможность проставить флаги сохранения у реквизитов обработки и формы

### Лог рабочей области

[Logs.zip](https://github.com/1C-Company/1c-edt-issues/files/8719094/Logs.zip)

### Версия 1С:EDT

2021.3.4

### Операционная система

Windows

### Дополнительная информация

Версия манифеста 8.3.20, используемая платформа 8.3.20.1476
Выгрузка обработки. Обработка независимая от конфигурации
[ExternalDataProcessors.zip](https://github.com/1C-Company/1c-edt-issues/files/8719106/ExternalDataProcessors.zip)

**Comment by RedMammoth** [comment]
Мб какой-то локальный глюк? Попробовал на двух машинах (под windows и под linux) на едт 3.4 открыть пример обработки или создать новую. С базовым проектом не добавляю - поле есть:
![image](https://user-images.githubusercontent.com/64589646/169127216-855a5e86-dbde-4681-b1e3-d3da671df5dd.png)

Мб по какой-то причине размер колонки нулевой, спряталась за другими колонками?

**Comment by mrshadow300373** [comment]
Мистика какая то. два раза EDT перезапускал, и форму новую создавал и одно и тоже, поэтому и зарегистрировал. В третий раз невод закинул (перезапустил EDT) - Приплыла рыбка:
![1652900103988](https://user-images.githubusercontent.com/34220218/169131923-5d7220d5-2881-49d8-84bc-070e96422134.jpg)

**Comment by mrshadow300373** [comment]
@RedMammoth , сегодня опят тоже самое, после включения возможности сохранения в форме - колонка не появилась. И лишь только после переоткрытия формы вожделенная колонка появилась где ей нужно. При отключении возможности сохранять колонка сразу исчезает, но при включении не появляется. Поэтому и не получилось воспроизвести. Дополняю и открываю ишу.

**Comment by vadimeg** [comment]
По всякому пробовал, все работает, ошибка не воспроизводится. Сохранение поддерживается не для всех типов, для динамического списка, например, не поддерживается. Но колонка появляется в любом случае.

**Comment by mrshadow300373** [comment]
> По всякому пробовал, все работает, ошибка не воспроизводится. Сохранение поддерживается не для всех типов, для динамического списка, например, не поддерживается. Но колонка появляется в любом случае.

Закон подлости в действии. В новых проектах действительно всё создаётся.
