### ISSUE TITLE
Часть методов имеют не верное описание типов в справке, что делает не возможным применять строгую типизацию

### ISSUE THREAD

**Issue by KigBan** [1C-Company/1c-edt-issues#470]
### Описание ошибки

Методы ЗаблокироватьДанныеДляРедактирования и РазблокироватьДанныеДляРедактирования в описании справки и синтаксис помощника не имеют тип "Любая ссылка на объект информационной базы", который имеется в локальной справке.
Как следствие при передаче переменной с типом объекта получаю ошибку:
Вызываемый тип выражения не пересекается с типом "Ключ" параметра: "РегистрСведенийКлючЗаписиИмяРегистраСведений, ВнешнийИсточникДанныхТаблицаСсылкаИмяВнешнегоИсточникаИмяТаблицыВнешнегоИсточникаДанных, ВнешнийИсточникДанныхТаблицаКлючЗаписиИмяВнешнегоИсточникаИмяТаблицыВнешнегоИсточникаДанных"		строка 339	invocation-parameter-type-intersect

Как пожелание: такие ошибки хотелось бы регистрировать прямо из EDT.

### Как воспроизвести

Ошибка в следующем коде:
// @strict-types

// Заблокировать физическое лицо при редактировании на сервере.
// 
// Параметры:
//  ФизическоеЛицо - СправочникСсылка._ДемоФизическиеЛица - Физическое лицо
//  ФормаУникальныйИдентификатор - УникальныйИдентификатор - Форма уникальный идентификатор
// 
// Возвращаемое значение:
//  Булево - Заблокировать физическое лицо при редактировании на сервере
&НаСервереБезКонтекста
Функция ЗаблокироватьФизическоеЛицоПриРедактированииНаСервере(ФизическоеЛицо, ФормаУникальныйИдентификатор)
	
	Попытка
		ЗаблокироватьДанныеДляРедактирования(ФизическоеЛицо, ФизическоеЛицо.ВерсияДанных, ФормаУникальныйИдентификатор);
	Исключение
		Возврат Ложь;
	КонецПопытки;
	
	Возврат Истина;
	
КонецФункции

### Ожидаемое поведение

Ошибка расширением "1С:Стандарты разработки V8" не идентифицируется.
Показывается правильная справка по методу.
Система показывает правильные подсказки.

### Лог рабочей области

Нет

### Версия 1С:EDT

2021.3.4

### Операционная система

Windows

**Comment by MaksimDzyuba** [comment]
Здравствуйте, проблему воспроизвести не смог, сейчас у нас там везде прописан произвольный тип, видимо мы ее когда-то исправили раньше
![Снимок](https://github.com/1C-Company/1c-edt-issues/assets/77277424/2d590e9b-21f9-4326-8f82-800cfb9aca1a)

**Comment by antongladyshevskiy** [comment]
В РазблокироватьДанныеДляРедактирования так и не исправили (версия 2024.2.6)

**Comment by MaksimDzyuba** [comment]
@antongladyshevskiy подтверждаю, очень извиняюсь, я видимо не проверил метод "РазблокироватьДанныеДляРедактирования", у него реально параметр имеет не тот тип. исправлю и скину сразу с обоими методами. Еще раз очень извиняюсь

**Comment by MaksimDzyuba** [comment]
<img width="1920" height="1048" alt="Image" src="https://github.com/user-attachments/assets/ae9f72d4-e645-4501-b328-cefb629f0d65" />
