### ISSUE TITLE
Пункт меню в проекте "Импорт конфигурации" для импорта в текущий проект изменений из конфигурации, привязанной к проекту

### ISSUE THREAD

**Issue by mazzz-igor** [1C-Company/1c-edt-issues#472]
### Описание проблемы

Для плавного перехода из конфигуратора в EDT очень хорошо подходит способ перехода, когда EDT используется как git-клиент, а разработка ведется разработчиком в конфигураторе. 

Но после изменений в конфы именно в конфигураторе нет возможности сделать импорт отдельной командой изменений в проект. Надо обязательно нажимать обновить конфигурацию и только потом импорт, если EDT находит отличия. 
При такой схеме возникают проблемы при смене версии EDT и бывает, что конфигурация из проекта затирает конфигурацию в базе.

### Описание решения проблемы

Поэтому очень хотелось бы, чтобы появилась команда "Импорт конфигурации" в проекте, которая будет выполнять импорт изменений из базы, которая привязана к проекту, принудительно.

**Comment by NikitaMikhaylovSB** [comment]
Не совсем понятна проблема, такой пункт есть, см. скриншот

![изображение](https://user-images.githubusercontent.com/37539066/169762329-668d1741-7d99-456a-b692-bf10b0f017a5.png)

**Comment by mazzz-igor** [comment]
Проверил работу. Действительно импорт выполняется. Видимо, раньше была проблема. Извините, что не разобрался сразу
