### ISSUE TITLE
На форме объекта не происходит очистка ссылок в пользовательской видимости на роль при ее удалении

### ISSUE THREAD

**Issue by XbreyMaxim** [1C-Company/1c-edt-issues#473]
### Описание ошибки

Поле удалении роли (например: «Тестовая роль») из конфигурации, если на форме объекта (например справочника) была установлена пользовательская видимость. Не происходит очистка ссылок на удаляемую роль. В следствии чего, при попытке обновить информационную базу из проекта будет получена следующая ошибка:  Неизвестный объект метаданных - Role.ТестоваяРоль

### Как воспроизвести

1. Создаем новую роль, например: «ТестоваяРоль».
2. Заходим в форму элемента справочника.
3. На каком либо элементе формы устанавливаем пользовательскую видимость, выбираем тестовую роль.
4. Сохраняем.
5. Удаляем созданную роль «ТестоваяРоль» из метаданных
6. Обновляем информационную базу из проекта.
7. При обновлении получаем ошибку «Неизвестный объект метаданных - Role.ТестоваяРоль»

### Ожидаемое поведение

После удалении роли из проекта (конфигурации) произойдет очистка ссылок в пользовательской видимости элементов формы. Там где была указана эта роль.

### Лог рабочей области

[.log](https://github.com/1C-Company/1c-edt-issues/files/8753184/default.log)

### Версия 1С:EDT

Ruby 2021.3.4.10

### Операционная система

Windows

### Установленные плагины

Нет плагинов

### Дополнительная информация

Если перейти в форму объекта, где была установлена пользовательская видимость и затем открыть форму с помощью текстового редактора.  То можно в соответствующем разделе увидеть наличие ссылки на роль, которую удалили.

**Comment by KhlupinDenis** [comment]
У меня ошибка повторяется

**Comment by vadimeg** [comment]
Исправлено в 2022.1.4
