### ISSUE TITLE
Не все файлы удаляются при удаление проекта из рабочего места

### ISSUE THREAD

**Issue by vkarelin** [1C-Company/1c-edt-issues#474]
### Описание ошибки

При удалении проекта из рабочего места не удаляются временные файлы, связанные с проектом. Например, .metadata\.plugins\com._1c.g5.v8.bm.core\store.  
Эти файлы могут занимать значительный объем на диске и висеть мертвым грузом.

### Как воспроизвести

1. Добавить любой проект в рабочее место.
2. Удалить проект из рабочего места.
3. Проверить, что в директории .metadata\.plugins\com._1c.g5.v8.bm.core\store остались файлы, связанные с проектом.

### Ожидаемое поведение

Все временные файлы, связанные с проектом, должны удаляться при удалении проекта из рабочего места.

### Лог рабочей области

Не требуется.

### Версия 1С:EDT

2021.3.4

### Операционная система

Windows

**Comment by airaketa** [comment]
Будет исправлена в 2024.1
