### ISSUE TITLE
Очистка обработчиков событий в элементах формы расширения при загрузке в ИБ №2

### ISSUE THREAD

**Issue by antonchev** [1C-Company/1c-edt-issues#475]
### Описание ошибки

Ошибка в точности повторяется в #243 

### Как воспроизвести

Обновить конфигурацию ИБ

### Ожидаемое поведение

Ожидается что при обновлении ИБ не пропадут обработчики событий в формах расширения

### Лог рабочей области

[log.log](https://github.com/1C-Company/1c-edt-issues/files/8754561/default.log)

### Версия 1С:EDT

2021.3.4+10

### Операционная система

Windows

**Comment by vadimeg** [comment]
Добрый день, возможно это какой-то другой кейс. К сожалению, в логе нет полезной информации. Чтобы воспроизвести проблему нужна доп. информация - конфигурация, расширение и шаги воспроизведения.

**Comment by antonchev** [comment]
Конфигурация Финансовый Менеджмент 3, ПСБ
![Screenshot_2](https://user-images.githubusercontent.com/22775316/169828097-9a26cebe-4577-4c70-8eb5-167fd0a225c0.png)
 Другие события не исчезают, в этом примере исчезает только ПередЗаписью
![Screenshot_3](https://user-images.githubusercontent.com/22775316/169828301-d636af3c-3957-40dd-9bf1-8f03a6ad0e3a.png)

**Comment by antonchev** [comment]
Если выгрузить расширение в исходники, со всеми событиями, и снова загрузить из исходников, событие исчезает, тут даже EDT не причём.

Если выгрузить cfe и загрузить снова, таких проблем нет, есть ли идеи ?

**Comment by vadimeg** [comment]
> Если выгрузить cfe и загрузить снова, таких проблем нет, есть ли идеи ?

В EDT не поддерживается формат cfe. Могу предположить, что с cfe платформа работает по-другому и там нет ошибки.
Для экспорта из EDT в базу используется тот же механизм, что и для экспорта в xml. Так что, ждем правку в платформе.

**Comment by vadimeg** [comment]
Появилась новая информация по багу. См. комментарий к https://github.com/1C-Company/1c-edt-issues/issues/410

**Comment by vadimeg** [comment]
Исправлено в 2022.2
