### ISSUE TITLE
Желаю в окне "Выбор реквизита" редактора формы чтобы двойной клик закрывал форму

### ISSUE THREAD

**Issue by tormozit** [1C-Company/1c-edt-issues#486]
### Описание проблемы

При двойном клике по реквизиту в окне "Выбор реквизита"" происходит ничего. Приходится каждый раз нажимать кнопку ОК или переносить правую руку не клаивиатуру и нажимать клавиши CTRL+ENTER.

![изображение](https://user-images.githubusercontent.com/11896251/171408588-7c0f73b1-3cd1-4a65-896f-519422c99f92.png)

### Описание решения проблемы

При двойном клике по реквизиту в окне "Выбор реквизита"" закрывать форму в передачей выбранного реквизита.
Аналогично работает и конфигуратор.

**Comment by vadimeg** [comment]
Исправлено в 2022.2

**Comment by vadimeg** [comment]
Фикс перенесен в релиз 2022.1
