### ISSUE TITLE
Добавить возможность добавления в стартер проекта с уже существующей папкой

### ISSUE THREAD

**Issue by DmitryShvaika** [1C-Company/1c-edt-issues#492]
### Описание проблемы

У меня есть папка с проектом - хочу "подключить" его в стартер. Как это сделать?

### Описание решения проблемы

Предлагаю при добавлении проекта возможность указания папки. Если ее нет - пусть создается новая, иначе подключается папка с уже существующим проектом.

**Comment by RedMammoth** [comment]
При добавлении проекта можно выбрать каталог с существующим проектом (если в списке проектов нет проекта по такому пути)
![image](https://user-images.githubusercontent.com/64589646/171922039-9cf90545-f2e5-4d19-800d-045e5ef85b9e.png)
В папке ничего не затерлось, открылся существующий:
![image](https://user-images.githubusercontent.com/64589646/171922247-0f429e20-f228-46d5-b946-9c407c2ccc69.png)

**Comment by DmitryShvaika** [comment]
да все работает - извиняюсь
