### ISSUE TITLE
Общих реквизитов нет в контекстной подсказке

### ISSUE THREAD

**Issue by DmitryShvaika** [1C-Company/1c-edt-issues#50]
## Опишите ошибку

Общие реквизиты не выводятся в список реквизитов контекстной подсказки.
Определил для документа ПоступлениеБезналичныхДенежныхСредств общий реквизит ДокументОснование,
однако он не выводится в контекстной подсказке

![image](https://user-images.githubusercontent.com/54451084/139832066-9ef8adff-3990-4971-8d7d-b0f80e9bb1ca.png)

## Окружение (пожалуйста укажите информацию):

 - OS: Windows 10
 - Версия 1C:EDT 2021.2.8
 - Версия платформы 1С 8.3.12

**Comment by RedMammoth** [comment]
Там что-то еще, мб есть какие то особенности в свойствах или в самой конфигурации.. У меня общие реквизиты отображаются. B попробовал накидать пустую конфигурацию - тоже показывает (edt 2021.2.8, Ubuntu 20.04, 8.3.16):
![image](https://user-images.githubusercontent.com/64589646/139834212-eb40b66e-7976-47a3-87b4-b6f50a97c2a2.png)

**Comment by DmitryShvaika** [comment]
Сначала то же сделал пустой проект и в нем воспроизвел вашу ситуацию, действительно реквизит есть. 
Однако если код расположить в Модуле объекта обработки, то ошибка повторяется.
Сделал тестовый пример: папка с проектом в архиве.

[Тест.zip](https://github.com/1C-Company/1c-edt-issues/files/7470813/default.zip)

![image](https://user-images.githubusercontent.com/54451084/140196639-3c3ed623-13e8-4ab5-9b67-a9d8066f55e5.png)

**Comment by DmitryShvaika** [comment]
Извиняюсь, забыл про указание использования на вкладке состав. По умолчанию стоит Авто а у реквизита Автоиспользование = Не использовать.
