### ISSUE TITLE
Окно "Все роли" отображает бесконечный прогресс открытия если проект быз закрыт с открытым окном "Все роли"

### ISSUE THREAD

**Issue by DmitryShvaika** [1C-Company/1c-edt-issues#515]
### Описание ошибки

Если открыть окно Все роли, затем закрыть проект на крестик (не закрывая отдельно этого окна), то при следующем запуске проекта автоматически восстановленное окно Все роли показывает бесконечный прогресс бар.

![image](https://user-images.githubusercontent.com/54451084/174085319-c80b285d-7050-4dca-960b-564f1faa197a.png)

### Как воспроизвести

1. Открыт окно "Все роли"
2. Закрыть проект на крестик
3. Открыть проект
4. Наблюдать бесконечный прогресс бар окна "Все роли"

### Ожидаемое поведение

Окно все роли должно корректно восстанавливаться при старте проекта.

### Лог рабочей области

[лог.zip](https://github.com/1C-Company/1c-edt-issues/files/8919428/default.zip)

### Версия 1С:EDT

2021.3.4

### Операционная система

Windows

### Дополнительная информация

Прилагаю тестовый проект на котором воспроизводил ошибку (кстати просто пустой проект который только что заново создал).
[test.zip](https://github.com/1C-Company/1c-edt-issues/files/8919437/test.zip)

**Comment by vadimeg** [comment]
Исправлено в релизной 2022.1
