### ISSUE TITLE
Ошибка реквизитов "Должна быть задана сущность 'type', необходимая для 'com._1c.g5.v8.dt.metadata"

### ISSUE THREAD

**Issue by agibalovsa** [1C-Company/1c-edt-issues#519]
### Описание ошибки

Возникает при очистке проекта расширения, или после обновления EDT. И не уходит, пока не пересоздашь проект полностью, или не очистишь метаданные проекта. Просто замучила эта ошибка. Память есть, кучу назначил, проект - конфигурация СППР. Не понятно, что ей не хватает.

Самое что плохое, похоже она влияет на функционирование других ошибок. Могу предоставить доступ к репозиторию. где данная ошибка имеет место быть.

### Как воспроизвести

1. Открыть проект с расширениями
2. Очистить проект
3. Во время переинициализации проекта в списке ошибок возникает описанная ошибка.
4. Все реквизиты метаданных помечаются красным.

### Скриншоты

![image](https://user-images.githubusercontent.com/14235747/174781096-3e47f282-377c-4257-bc3c-b34bee5af221.png)

### Ожидаемое поведение

Этой ошибки просто не должно быть.

### Лог рабочей области

[log проекта.zip](https://github.com/1C-Company/1c-edt-issues/files/8948087/log.zip)

### Версия 1С:EDT

Ruby 2021.3.4

### Операционная система

Windows

### Установленные плагины

1C:Code style V8, 1C:SSL-support

**Comment by MaksimDzyuba** [comment]
Здравствуйте, а проверите, пожалуйста, данную ошибку на 2022.1, должна уйти проблема. Воспроизвести ее не смог, хотя раньше мы ее тоже наблюдали

**Comment by agibalovsa** [comment]
Нет. не наблюдается. Спасибо.

**Comment by MaksimDzyuba** [comment]
Ок, спасибо за ответ
