### ISSUE TITLE
Попытка слить ветки во время расширенной проверки приводит к ошибке сравнения/объединения

### ISSUE THREAD

**Issue by mrshadow300373** [1C-Company/1c-edt-issues#528]
### Описание ошибки

Я переключился на другую ветку, ранее не переключался на неё, использовать механизм снимков нет возможности.
Много обновлений метаданных. В итоге стартует расширенная проверка, мне после переключения сразу нужно произвести операцию слияния этой ветки с другой. Я начинаю операцию слияния в итоге получаю ошибку:
"Произошла внутренняя ошибка: сравнение проектов <проект> и <проект>.
![23-06-2022 19-12-54](https://user-images.githubusercontent.com/34220218/175334227-6afdec3c-538b-4a7c-892e-a3036dc254a7.jpg)
Прервать расширенную проверку начиная с версии EDT 2021.2 возможности нет.
После перезапуска она продолжается. Приходится ждать длительное время, прежде чем начать операцию сравнения.
Я понимаю, что проверка необходима, но мне валидаторы на этом этапе НЕ НУЖНЫ. Мне нужно слить в это ветку другую, и вот только тогда они мне потребутся все проверки. Но я вынужден ждать совершенно мне ненужную сейчас расширенную проверку, а потом ждать её окончания ещё раз после слияния

### Как воспроизвести

1. Переключиться на другую ветку, желательно чтобы разрыв между ветками был большой, порядка 10000 файлов и не дожидаясь окончания расширенной проверки попытаться слить с другой веткой. Возникнет ошибка:
![23-06-2022 19-12-54](https://user-images.githubusercontent.com/34220218/175335281-340fb0e0-393e-47bf-a07b-ae24e2569b64.jpg)
2. Перезапустить EDT проверка будет продолжаться, попытаться ещё раз слить во время проверки, получим ту же ошибку.
3. Дождаться окончания проверки, перезапустит EDT и снова запустить слияние. На этот раз оно должно пройти без ошибок

### Ожидаемое поведение

Я хочу иметь возможность прервать текущую расширенную проверку, чтобы сделать более приоритетные операции (сравнение объединение, поиск и т.д.) и потом запустить её тогда, когда сочту нужным.

### Лог рабочей области
[logs.zip](https://github.com/1C-Company/1c-edt-issues/files/8968783/logs.zip)

### Версия 1С:EDT

2021.3.4

### Операционная система

Windows, Linux

**Comment by mrshadow300373** [comment]
В дополнение ко всему, позиционировали, что механизм расширенной проверки работает только в простое EDT. Однако это не так, в полосе прогресса видно, что во время процесса сравнения с веткой прогресс расширенной проверки увеличивается, т.е. остановки не происходит как было заявлено.

**Comment by NikitaMikhaylovSB** [comment]
Такая же проблема возникает, если запустить сборку.
Пока не пройдет валидация - сборка будет ждать..

**Comment by mrshadow300373** [comment]
Связанная статья с детальным описанием неудобства:
[2021.3.1 Что же это он, обманщик, делает то?](https://partners.v8.1c.ru/forum/topic/2048060)
