### ISSUE TITLE
В описании контекста платформы отсутствует тип для параметра SpreadsheetDocument.Read()

### ISSUE THREAD

**Issue by stolya** [1C-Company/1c-edt-issues#531]
## Название/код проверки

Код проверки: `invocation-parameter-type-intersect`

Версия плагина: `0.2.0.162`

## Пример кода/метаданных содержащих ошибку

```bsl
Поток = Base64Значение("...").ОткрытьПотокДляЧтения();
ТабДок = Новый ТабличныйДокумент();
ТабДок.Прочитать(Поток);
```

![image](https://user-images.githubusercontent.com/30523530/159221258-5f12f5aa-5d65-440f-bcc7-2d71c55f8664.png)

**Comment by MaksimDzyuba** [comment]
Здравствуйте, ошибка точно отсутствует в 2022.2
![image](https://user-images.githubusercontent.com/77277424/232490624-95e800ea-322f-474a-9f64-2fda720b350d.png)
