### ISSUE TITLE
В строгих типах некорректно определяется тип первого параметра для метода "Добавить" списка значений

### ISSUE THREAD

**Issue by DmitryShvaika** [1C-Company/1c-edt-issues#539]
### Описание ошибки

В строгих типах некорректно определяется тип первого параметра для метода "Добавить" списка значений

![image](https://user-images.githubusercontent.com/54451084/176604800-c63f4c80-3ba8-48d7-8cdb-72f9a46e98ad.png)

### Как воспроизвести

1. В модуле набрать код

// @strict-types

Процедура МояПроцедура() Экспорт
	Список = Новый СписокЗначений;
	Список.Добавить(3, "3");
КонецПроцедуры

2. Наблюдать ошибку

### Ожидаемое поведение

Тип должен определяться как Произвольный как указано в справочной информации и он должен пересекаться с типом Число.

### Лог рабочей области

не требуется

### Версия 1С:EDT

2021.3.4

### Операционная система

Windows

**Comment by marmyshev** [comment]
исправлено в https://github.com/1C-Company/v8-code-style/pull/1047
