### ISSUE TITLE
Ошибки получения новых метаданных через слияние с ветками с помощью внешних клиентов git

### ISSUE THREAD

**Issue by agibalovsa** [1C-Company/1c-edt-issues#549]
### Описание ошибки

Если метаданные в основную ветку пришли из другой ветки через слияние с помощью внешнего клиента git. например, VSCode. То при обновление приложения выходят ошибки: Тип не определн, все пропало.

### Как воспроизвести

У нас имеется проект в EDT.
1) Разработка ведется в EDT
2) Работа с git осуществляется через VSCode
3) Имеется 2 ветки, обе созданы в EDT: develop, feature.
4) В ветке feature добавлены метаданные.
5) EDT открыт на ветке develop
6) Одновремено с EDT открыт VSCode
7) Через VSCode осуществляется слияние 2х веток.
8) В EDT обновляется информация о произошедших изменениях, видны метаданные.
9) Пытаемся обновить ИБ - выходит ошибка.
10) Изменяем имя новых метаданных на новое и обратно на старое
11) Обновляем ИБ, ошибка не выходит.

### Скриншоты

![image](https://user-images.githubusercontent.com/14235747/177338276-2bdffa29-f010-4c70-aaf5-8c355bd08c37.png)

### Ожидаемое поведение

Результат слияние через любой git клиент должен однозначно отрабатывать в EDT.

### Лог рабочей области

[log EDT.zip](https://github.com/1C-Company/1c-edt-issues/files/9046693/log.EDT.zip)

### Версия 1С:EDT

Ruby 2021.3.4

### Операционная система

Windows

### Установленные плагины

1C:Code style V8, 1C:SSL-support

**Comment by adminimusRU** [comment]
Галка "Загрузить конфигурацию полностью" при обновлении ИБ проблему решает? Или очистка кеша проекта?

**Comment by agibalovsa** [comment]
"Загрузить полностью" точно не решает. Очистку кэша проекта не проверял.

**Comment by AlmazNasibullin** [comment]
@agibalovsa Добрый день!
У вас получится предоставить доступ к Вашему репозиторию, чтобы попробовать воспроизвести Ваш кейс?

**Comment by agibalovsa** [comment]
Да, конечно. Напешите мне в телеграмме. (89277047749)

**Comment by AlmazNasibullin** [comment]
На версии 1C:EDT 2022.1 проблема не воспроизводится.
