### ISSUE TITLE
Критично! 8.3.20 Потеря свойства "Поле пути к данным" характеристики объекта метаданных при выгрузке/загрузке

### ISSUE THREAD

**Issue by tormozit** [1C-Company/1c-edt-issues#551]
### Описание ошибки
Класс критичности - Потеря/нарушение данных (в основной конфигурации, в расширениях), обнаруженная постфактум
Платформа 1С 8.3.20.1710
Конфигурация 1С в режиме совместимости 8.3.16

Ошибка критичная, т.к. приходится восстанавливать вручную свойство в обновленных объектах метаданных после каждого обновления базы 1С из EDT. Воспроизводится в двух проектах с разными гит-репозиториями.

При загрузке метаданных из базы 1С в EDT свойство "Поле пути к данным" (DataPathField) характеристики объекта метаданных получает пустое значение, хотя в выгруженном конфигуратором файле XML оно непустое.

![изображение](https://user-images.githubusercontent.com/11896251/177714560-b52f69c7-171f-4125-8667-a56dedd2c48b.png)
```
<Characteristics>
				<xr:Characteristic>
					<xr:CharacteristicTypes from="Catalog.ВидыСтатусов">
						<xr:KeyField>Catalog.ВидыСтатусов.StandardAttribute.Ref</xr:KeyField>
						<xr:TypesFilterField>-1</xr:TypesFilterField>
						<xr:TypesFilterValue xsi:nil="true"/>
						<xr:DataPathField>Catalog.ВидыСтатусов.Attribute.ИмяПоляКомпоновки</xr:DataPathField>
					</xr:CharacteristicTypes>
					<xr:CharacteristicValues from="InformationRegister.СтатусыОбъектов">
						<xr:ObjectField>InformationRegister.СтатусыОбъектов.Dimension.Объект</xr:ObjectField>
						<xr:TypeField>InformationRegister.СтатусыОбъектов.Dimension.ВидСтатуса</xr:TypeField>
						<xr:ValueField>InformationRegister.СтатусыОбъектов.Resource.Статус</xr:ValueField>
					</xr:CharacteristicValues>
				</xr:Characteristic>
</Characteristics>
```
При загрузке такого файла в EDT в окне сравнения значение свойства отображается "-1"

![изображение](https://user-images.githubusercontent.com/11896251/177713709-297e4a9f-8dfa-4151-8e56-fdda5172216f.png)

При выгрузке из EDT похоже аналогичная ситуация. Но в выгруженном из EDT файле xml значение свойства присутствует
```
<Characteristics>
				<xr:Characteristic>
					<xr:CharacteristicTypes from="Catalog.ВидыСтатусов">
						<xr:KeyField>Catalog.ВидыСтатусов.StandardAttribute.Ref</xr:KeyField>
						<xr:TypesFilterField>-1</xr:TypesFilterField>
						<xr:TypesFilterValue xsi:nil="true"/>
						<xr:DataPathField>Catalog.ВидыСтатусов.Attribute.ИмяПоляКомпоновки</xr:DataPathField>
					</xr:CharacteristicTypes>
					<xr:CharacteristicValues from="InformationRegister.СтатусыОбъектов">
						<xr:ObjectField>InformationRegister.СтатусыОбъектов.Dimension.Объект</xr:ObjectField>
						<xr:TypeField>InformationRegister.СтатусыОбъектов.Dimension.ВидСтатуса</xr:TypeField>
						<xr:ValueField>InformationRegister.СтатусыОбъектов.Resource.Статус</xr:ValueField>
					</xr:CharacteristicValues>
				</xr:Characteristic>
```
После обновления конфигурации базы 1С из EDT, где свойство заполнено, в базе 1С свойство у всех объектов метаданных оказывается пустым.

### Как воспроизвести

я

### Скриншоты

![изображение](https://user-images.githubusercontent.com/11896251/177713313-07ec4c46-14eb-44de-abf3-bb65db28cddd.png)

### Ожидаемое поведение

Читается значение свойства

### Лог рабочей области

я

### Версия 1С:EDT

Ruby 2021.3.4

### Операционная система

Windows

### Установленные плагины

Нет плагинов

**Comment by NikitaMikhaylovSB** [comment]
Хм, у меня вот регулярно EPR туда-сюда гоняется и данные связей характеристик на месте.
Или я что-то неправильно понял из описания?

**Comment by marmyshev** [comment]
@tormozit 

> При выгрузке из EDT похоже аналогичная ситуация. Но не знаю, как отловить xml файлы в этой операции.
После обновления конфигурации базы 1С из EDT, где свойство заполнено, в базе 1С свойство у всех объектов метаданных оказывается пустым.

Чтобы получить xml Платформы по проекту - ПКМ - Экспорт - Выгрузка конфигурации в xml...

Тогда можно посмотреть в файлах что выгружается из ЕДТ.

**Comment by MaksimDzyuba** [comment]
@tormozit а есть возможность предоставить саму конфигурацию в формате edt?

**Comment by tormozit** [comment]
> @tormozit а есть возможность предоставить саму конфигурацию в формате edt?
Нет.

**Comment by tormozit** [comment]
> Чтобы получить xml Платформы по проекту - ПКМ - Экспорт - Выгрузка конфигурации в xml...
> Тогда можно посмотреть в файлах что выгружается из ЕДТ.
Сделал. Обновил описание

**Comment by tormozit** [comment]
Проблему воспроизвел в чистой конфигурации без EDT на 1C 8.3.20. При этом на 8.3.22 ее нет.

**Comment by MaksimDzyuba** [comment]
могу предложить зарегистрировать ошибку на платформу, попросить перенос в 8.3.20, но для этого мне нужен cf файл

**Comment by tormozit** [comment]
[1Cv8.zip](https://github.com/1C-Company/1c-edt-issues/files/9062170/1Cv8.zip)

**Comment by tormozit** [comment]
Ошибка НЕ воспроизводится в 8.3.19.1522

**Comment by MaksimDzyuba** [comment]
Здравствуйте платформа ошибку признала и поправила, фикс выйдет в версиях старше 8.3.20.1995

**Comment by tormozit** [comment]
Ссылку или номер бага платформы увидеть было бы здорово. Ну или хотя бы код обращения.

**Comment by tormozit** [comment]
Очень плохо, что разработчики EDT не предоставили номера обращения или ошибки платформы. Сейчас коллеги столкнулись с этой же ошибкой и я не могу им предоставить официальную информацию. Приходится давать ссылку на это описание.

**Comment by MaksimDzyuba** [comment]
у меня есть только внутренний ее код - 60001396, другой информации я никакой не получаю при регистрации

**Comment by MaksimDzyuba** [comment]
в 8.3.21 она изначально не проявлялась, в 8.3.20 я сам лично проверял на сборке 8.3.20.1996 в данном описании как она представлена тут, она не воспроизводилась

**Comment by tormozit** [comment]
@MaksimDzyuba В сборках 1914-1996 ошибки действительно нет. Но я лично 5+ раз и коллеги несколько раз с ней сталкивались на 8.3.20.2076, т.е. потом ее вернули. Думаю в воскрешении ошибки не последнюю роль сыграло отсутствие публикации ошибки.

**Comment by MaksimDzyuba** [comment]
вот это уже дико странно, публично ее нет, так как регал ее сотрудник изнутри, им обычно публикацию не ставят. я попробую завтрапроверить на 8.3.20.2076, если воспроизведется, то пойду с ними разбираться, как так может получаться вообще

**Comment by tormozit** [comment]
@MaksimDzyuba я почти сразу удалил свое предыдущее сообщение, т.к. перепутал с другой похожей проблемой этого релиза.

**Comment by MaksimDzyuba** [comment]
Здравствуйте, я проверил на 8.3.20.2248 ошибка не воспроизвелась
