### ISSUE TITLE
Ложное срабатывание проверки: invocation-parameter-type-intersect

### ISSUE THREAD

**Issue by Shuta4** [1C-Company/1c-edt-issues#554]
## Вызываемый тип выражения не пересекается с типом "Дата" параметра: "Дата"

Код проверки: `invocation-parameter-type-intersect`

Версия плагина: `0.2.0.165`

## Пример кода/метаданных содержащих ошибку

```bsl
// @strict-types

Процедура Тест() Экспорт
	ДатаОшибка = НачалоДня(ТекущаяДатаСеанса() - 86400);
КонецПроцедуры
```

![image](https://user-images.githubusercontent.com/46641512/177757407-68bdc2c5-3f03-487d-aa0d-ae94208d269a.png)

## Почему это НЕ ошибка
Код `НачалоДня(ТекущаяДатаСеанса() - 86400)` не является ошибочным потому, что при прибавлении к дате или вычитании из даты числа получается значение с типом дата.

## Дополнительные материалы

- [Документация на сайте ИТС, раздел "4.5.1. Арифметические операции"](https://its.1c.ru/db/v8320doc#bookmark:dev:TI000000143)

**Comment by MaksimDzyuba** [comment]
исправление будет в ближайшей версии 2022.1
