### ISSUE TITLE
Ошибки редактирования метаданных вида "ПланВидовРасчета"

### ISSUE THREAD

**Issue by EChudnovsky** [1C-Company/1c-edt-issues#556]
### Описание ошибки

Все ошибки связаны с типовой конфигурацией ЗУП (версия 3.1.20.96)

1. Добавлен реквизит в план видов расчета "Удержания". При попытке переименовать реквизит возникает ошибка (см. журнал ошибок log1.log):

`"Error on computation of hover information. No hover information available for com._1c.g5.v8.dt.bsl.model.impl.DynamicFeatureAccessImpl@607581ed (name: ПередЗаписьюНаСервере) at offset: 1043, length: 21".
`

2. Форма плана видов расчета удержания добавлена в расширение. При попытке заимствования реквизита Объект (типа ПланВидовРасчетаОбъект.Удержания) в расширение выдается ошибка ниже и как следствие ошибки при обращении к предопределенным реквизитам и таблицам для типа ПланВидовРасчетаОбъект (см. журнал ошибок log2.log): 

`
Ошибка во время построения модели 'FormMapping'.
Cannot find DbViewField with "Ref" name from source "Объект"
`
![изображение](https://user-images.githubusercontent.com/5530435/178299891-ac2a1b75-c293-4543-9636-9f92f0950770.png)

3. Добавлена константа в конфигурацию. При попытке удаления константы выдается ошибка на скрине. При этом в журнале ошибок сообщения отсутствуют

![изображение](https://user-images.githubusercontent.com/5530435/178297861-e2b68fcf-3ea1-45b4-8378-c5101dd4fa08.png)

### Как воспроизвести

Выполнить шаги из описания

### Ожидаемое поведение

Редактирование объектов конфигурации и форм без ошибок, блокирующие разработку.

### Лог рабочей области

[log1.log](https://github.com/1C-Company/1c-edt-issues/files/9085408/log1.log)

[log2.log](https://github.com/1C-Company/1c-edt-issues/files/9085409/log2.log)

### Версия 1С:EDT

Ruby 2021.3.4

### Операционная система

Windows, Linux

### Установленные плагины

1C:Code style V8

### Дополнительная информация

Версия платформы 1С: 8.3.19.

**Comment by vadimeg** [comment]
@EChudnovsky Можете, пожалуйста, проверить на 2022.1? Остались ли ошибки?

**Comment by EChudnovsky** [comment]
На версии 2022.1 удаление констант по прежнему не работает (см. скриншот)
Для информации: конфигурация на поддержке.

![изображение](https://user-images.githubusercontent.com/5530435/181722183-0b8e2681-f548-4127-bdca-f4a688b8f985.png)

Лог файл: 

[log.zip](https://github.com/1C-Company/1c-edt-issues/files/9218328/log.zip)

**Comment by vadimeg** [comment]
@EChudnovsky 
№1 и №2 у меня на 2022.1 не воспроизводятся.
По поводу удаления констант. Судя по картинке, конфигурация находится на поддержке, при этом в настройках у части объектов разрешено редактирование. А константы, которые вы пытаетесь удалить на какие объекты ссылаются? Есть ли на них ссылки в подсистемах, которые закрыты для редактирования или еще где-то?

**Comment by tretyakevich** [comment]
Критичность понижена из-за отсутствия конкретных данных для воспроизведения

**Comment by Erik773** [comment]
Задача закрыта из-за невозможности воспроизведения.
Если появится дополнительная информация, которая может способствовать воспроизведению проблемы, задачу можно переоткрыть.
