### ISSUE TITLE
ВопросАсинх не определен на web клиенте

### ISSUE THREAD

**Issue by Daabramov** [1C-Company/1c-edt-issues#563]
### Описание ошибки

При вызове метода ВопросАсинх ЕДТ ругается, что данный метод не определен на веб клиенте, хотя он там точно есть.

### Как воспроизвести

1. Перейдите в форму
2. Создайте асинх процедуру на клиенте
3. Введите `Результат = Ждать ВопросАсинх("Текст", РежимДиалогаВопрос.ДаНет, 0);`
4. ЕДТ выдаст ошибку, что метод не определен

### Скриншоты

![image](https://user-images.githubusercontent.com/31928832/179815109-c1e84a15-f46d-46b0-9094-168981fe9d38.png)

### Ожидаемое поведение

Метод на клиенте должен быть определен и ошибка проверки отсутствовать

### Лог рабочей области

-

### Версия 1С:EDT

2022.1

### Операционная система

Windows

### Установленные плагины

1C:Code style V8, 1C:SSL-support, Другие сторонние плагины `Название плагина...`

**Comment by grumagargler** [comment]
Это также касается и OpenValueAsync, ChooseFromListAsync и других

**Comment by MaksimDzyuba** [comment]
будет исправлено в ближайшем выпуске 2022.1
