### ISSUE TITLE
Ошибка LayoutProblem: null при заимствовании (или обновлении) формы в расширении

### ISSUE THREAD

**Issue by EChudnovsky** [1C-Company/1c-edt-issues#567]
### Описание ошибки

В типовой ЗУП версии 3.1.20.96 стабильно проявляется ошибка LayoutProblem: null при заимствования формы "ФормаДокументаАльтернативная" для документа "ТабельУчетаРабочегоВремени" и как результат ее не  работоспособное состояние (см. скриншот).
На текущий момент все операции по доработке данной формы приходится выполнять в конфигураторе, а результат импортировать в edt.
Данное поведение воспроизводится на версиях

**EDT:**

- 1c-edt-2021.3.4
- 1c-edt-2022.1.0

- ОС:

- Windows 11
- Ubuntu 20.04.3 LTS

### Как воспроизвести

1. Создать проект EDT для типового ЗУП (конфигурация на поддержке)
2. Создать расширение 
3. Импортировать в расширение форму "ФормаДокументаАльтернативная" из документа "ТабельУчетаРабочегоВремени"

### Скриншоты

![изображение](https://user-images.githubusercontent.com/5530435/179921566-544debb8-3e85-4e63-9786-1a1b63cd247f.png)

### Ожидаемое поведение

Корректное редактирование любой формы (поддерживаемых типов) с минимальными усилиями со стороны разработчика.

### Лог рабочей области

[log.log](https://github.com/1C-Company/1c-edt-issues/files/9147501/log.log)

### Версия 1С:EDT

Ruby 1c-edt-2021.3.4, Ruby 1c-edt-2022.1.0

### Операционная система

Windows, Linux

### Установленные плагины

1C:Code style V8, 1C:Language Tool

### Дополнительная информация

Проект edt под версию платформы: 8.319
Версия платформы: 8.3.19.1522
Типовая конфигурация: "ЗарплатаИУправлениеПерсоналомКОРП" 3.1.20.96

**Comment by MaksimDzyuba** [comment]
Ошибка будет исправлена в ближайшей исправительной 2022.1

**Comment by EChudnovsky** [comment]
Добрый день, ошибка по прежнему воспроизводится на EDT 2022.1

![изображение](https://user-images.githubusercontent.com/5530435/185865391-05d9f98b-4ba9-4ce3-99f8-25af6a15fb53.png)

Прикладываю
1. Журнал логов
[log.log](https://github.com/1C-Company/1c-edt-issues/files/9392243/log.log)

2. Состояние объектов до момента обновления формы из основной конфигурации
Документ основной конфигурации:
[ТабельУчетаРабочегоВремени.zip](https://github.com/1C-Company/1c-edt-issues/files/9392208/default.zip)

Документ расширения:
[ТабельУчетаРабочегоВремени_расширение.zip](https://github.com/1C-Company/1c-edt-issues/files/9392221/_.zip)

**Comment by MaksimDzyuba** [comment]
Да, нужно ждать исправительную к 2022.1, я же вроде так и написал, @vadimeg, я же прав?

**Comment by vadimeg** [comment]
@MaksimDzyuba Да, все верно. Исправление само по себе не появится, ждем выхода исправительной версии. В логах стэктрейс на неисправленной версии.

**Comment by vadimeg** [comment]
Исправлено в 2022.2. Выпуск скоро ожидается
