### ISSUE TITLE
[1CEDT] Нет маркера ошибки/предупреждения при обращении к несуществующему полю ТаблицыЗначений

### ISSUE THREAD

**Issue by RedMammoth** [1C-Company/1c-edt-issues#571]
```
// @strict-types

// Таблица значений созданная в функции.
// 
// Возвращаемое значение:
//  СтрокаТаблицыЗначений - Таблица значений созданная в функции:
// * поле1 - Число -
Функция ТаблицаЗначенийСозданнаяВФункции() Экспорт
	тз = Новый ТаблицаЗначений;
	тз.Колонки.Добавить("поле1", Новый ОписаниеТипов("Число"));

	новаяСтрока = тз.Добавить();
	новаяСтрока.Котлетка = 5;

	Возврат новаяСтрока;

КонецФункции

// Таблица значений переданная в функцию.
// 
// Параметры:
//  тз - ТаблицаЗначений Из СтрокаТаблицыЗначений:
//  * поле1 - Число -
// 
// Возвращаемое значение:
//  СтрокаТаблицыЗначений - Таблица значений переданная в функцию:
// * поле1 - Число -
Функция ТаблицаЗначенийПереданнаяВФункцию(тз) Экспорт
	новаяСтрока = тз.Добавить();
	новаяСтрока.Котлетка = 5;
	Возврат новаяСтрока;
КонецФункции
```
```
Product name: 1C:Enterprise Development Tools
Product version: 1.26.0.437
Java home: /usr/lib/jvm/bellsoft-java11-full-amd64
Java vm name: OpenJDK 64-Bit Server VM
Java vm info: mixed mode
Java version: 11.0.15
Java vendor: BellSoft
OS: linux
Total mem: 519
Free mem: 98
Cores: 8
```

**Comment by vadimeg** [comment]
Это, наверное, в кодстайл?
https://github.com/1C-Company/v8-code-style/issues

**Comment by RedMammoth** [comment]
Обычно в таких случаях ругается с кодом unknown-method-property. Я не нашел в код стайле эту проверку, мне кажется она встроенная в едт?
Или на этот случай отдельную проверку делать?

**Comment by vadimeg** [comment]
Да, я имел в виду, что в кодстайле нужно баг на новую проверку создавать, не в EDT

**Comment by marmyshev** [comment]
Такая ситуация только для типа `СтрокаТаблицыЗначений` - у любого поля к которому обращаешься - есть тип "Произвольный" всегда. 

```bsl
// @strict-types

// Параметры:
//  Параметр - СтрокаТаблицыЗначений -
Процедура ТестСтрогихтипов(Параметр) Экспорт
	
	Параметр.Поле = 1;
	
	МояПерем = Параметр.Поле;
	Если МояПерем = Неопределено Тогда
	КонецЕсли;
	
КонецПроцедуры
```

@MaksimDzyuba Что посоветуешь тут делать? захадкодить для этого типа специфичное поведение, например проверять что у `Параметр.Поле` нет source? Но всё-таки непонятно почему тут тип `Arbitrary` выдается?

Такой вариант (с другим типом) - корректно показывает отсутствие типа:

```bsl
// @strict-types

// Параметры:
//  Параметр - Структура -
Процедура ТестСтрогихтипов(Параметр) Экспорт
	
	Параметр.Поле = 1;
	
	МояПерем = Параметр.Поле;
	Если МояПерем = Неопределено Тогда
	КонецЕсли;
	
КонецПроцедуры
```

**Comment by MaksimDzyuba** [comment]
Привет, сложная ситуация, тип "СтрокаТаблицыЗначений" является именованной коллекцией, то есть у нее есть свойства того же типа, что отмечено у нее как тип элемента коллекции. Тут это похоже играет злую шутку, так как там тип произвольный. Что не показывается предупреждение, что такого поля нет - это ограничение edt, которое мы ввели еще очень давно, что из-за того, что мы не можем гарантировать полноту вычисления всех типов, мы валидацию эту не показываем, возможно, если есть указание strict-types, то ограничение надо снимать, но это надо отдельно проанализировать

**Comment by marmyshev** [comment]
Обсудили, решили: коллекции в которых доступ по к элементам по имени возвращает произвольные типы - нужно исключить из списка, т.к. смысла не имеет.

**Comment by MaksimDzyuba** [comment]
> Обсудили, решили: коллекции в которых доступ по к элементам по имени возвращает произвольные типы - нужно исключить из списка, т.к. смысла не имеет.

@marmyshev  фикс сделал, появится в 2022.2, но вопрос с валидацией не решен - я выше объяснял почему нет на это валидации, но возможно, если указан тип strictTypes, то ее следует включить. но это надо анализировать и делать там, где про strictTypes

**Comment by marmyshev** [comment]
@MaksimDzyuba  да, здесь речь только про `@stict-types`
