### ISSUE TITLE
В строгих типах "системные значения" с типом Произвольный вызывают ошибку "не имеет типа возвращаемого значения"

### ISSUE THREAD

**Issue by DmitryShvaika** [1C-Company/1c-edt-issues#573]
### Описание ошибки

В строгих типах платформенные значения с типом Произвольный вызывают ошибку "не имеет типа возвращаемого значения". Например поле Значение в условном оформлении или отборе уловного оформления.

![image](https://user-images.githubusercontent.com/54451084/180391586-9bb8f99c-6bc9-4a05-bad3-1744a6032dd2.png)

### Как воспроизвести

1. Создать произвольную форму
2. Создать событие ПриСозданииНаСервере
3. Ввести код:

```

// @strict-types

&НаСервере
Процедура ПриСозданииНаСервере(Отказ, СтандартнаяОбработка)
	
	СтрокаУсловногоОформления = УсловноеОформление.Элементы.Добавить();

	СтрокаОтбора = СтрокаУсловногоОформления.Отбор.Элементы.Добавить(Тип("ЭлементОтбораКомпоновкиДанных"));
	СтрокаОтбора.ПравоеЗначение = 1;

	СтрокаОформления = СтрокаУсловногоОформления.Оформление.НайтиЗначениеПараметра(
		Новый ПараметрКомпоновкиДанных("ТолькоПросмотр"));
	СтрокаОформления.Значение = Истина;
	
КонецПроцедуры

```

4. Наблюдать ошибку

### Ожидаемое поведение

Ошибка не должна детектироваться для платформенных значений. 

### Лог рабочей области

не требуется

### Версия 1С:EDT

2022.1

### Операционная система

Windows

**Comment by akhoroshilov** [comment]
Up

**Comment by RedMammoth** [comment]
По-моему в 2022.2.1 исправлено. 
![image](https://user-images.githubusercontent.com/64589646/208626010-e2d46134-598d-4766-9e7c-8b0e2dd6d13a.png)

**Comment by DmitryShvaika** [comment]
Да, исправлена. Спасибо
