### ISSUE TITLE
Некорректно детектируется ошибка "Возвращается недекларируемый тип: Произвольный"

### ISSUE THREAD

**Issue by DmitryShvaika** [1C-Company/1c-edt-issues#577]
### Описание ошибки

Некорректно детектируется ошибка "Возвращается недекларируемый тип: Произвольный"

![image](https://user-images.githubusercontent.com/54451084/180719620-0abfdfe2-ab75-40e3-8166-1ae0ac313871.png)

В то время, если указать что возвращается Число, то ошибки нет

![image](https://user-images.githubusercontent.com/54451084/180719688-9a984fc4-703a-42d0-bd3c-1aa548b551e7.png)

Как будто edt считает что тип Число входит в тип Произвольный, Структура - нет

### Как воспроизвести

1. В модуле набрать текст 

```
// Моя функция.
// 
// Возвращаемое значение:
//  Структура
//
Функция МояФункция() Экспорт
	
	б = Новый Структура;
	Ключ = "Мойключ";
	
	а = Новый Соответствие;
	а[Ключ] = б;
	
	б = а[Ключ]; // Структура
	
	Возврат б;
	
КонецФункции

```
2. Наблюдать ошибку

### Ожидаемое поведение

Думаю, проще всего сделать комментарий, которым можно указать Edt какой тип в данном случае возвращается.

Т.к. данная ситуация иллюстрирует множество проблем типизации в 1с:
Тип Произвольный считается неопределенным, но фигурирует в  типах аргументов процедур и функций в том числе и системных. В этом случае он должен быть строго определен.
Вторая проблема - в разных местах тип Произвольный включает в себя разный набор типов. Например в соответствии можно указать Элемент управления формы, а в реквизите справочника - этого сделать нельзя, хотя оба значения описаны как "Произвольный".
Тут возможно стоит менять и справочную систему и подсказки, вводить типы в сам язык и т.п.
Как вариант, пока склоняюсь с определением типа через комментарий.

### Лог рабочей области

не требуется

### Версия 1С:EDT

2022.1

### Операционная система

Windows

**Comment by marmyshev** [comment]
Это проверка из "строгой типизации", к ЕДТ не имеет отношения.

**Comment by marmyshev** [comment]
> Тип Произвольный считается неопределенным, но фигурирует в типах аргументов процедур и функций в том числе и системных. В этом случае он должен быть строго определен.

Тут либо непонимание, либо нужно уточнить что имелось ввиду? 

`Произвольный` - это один тип, а `Неопределено` - это другой тип. Два разных типа, с разным смыслом.

**Comment by marmyshev** [comment]
> Вторая проблема - в разных местах тип Произвольный включает в себя разный набор типов. Например в соответствии можно указать Элемент управления формы, а в реквизите справочника - этого сделать нельзя, хотя оба значения описаны как "Произвольный".

Просьба уточнить, в чем именно проблема? "везде всё разное" - это констатация факта, а не пояснение почему это является проблемой.

Да, в Платформе разные допустимые типы в разных местах - при чем есть прям очень понятный и строгий смысл почему так сделано. 
- Понятно ведь что в реквизитах таблиц БД нельзя хранить объект "Элемент управления формы" - тут ясно почему ограничение на типы в реквизитах. 
- Реквизиты формы - это другой объект, не связанный с БД. 
- А в коде - вообще третий уровень типизации объектов

А где проблема - предлагаю прямо написать: "вот в этом случае не так как надо..."

**Comment by DmitryShvaika** [comment]
Предлагаю в параметрах проверки установить галку проверять "strict-types" по умолчанию просто.
Тема очень сложная. Но сейчас в модуле нет строгой типизации и по умолчанию "из коробки" edt выдает эту ошибку. 

Дальше можно добавить символ, например воскл. знак "!" (или другой символ) чтобы при определении типа через комментарий edt не добавляла свои вычисленные типы 

например

б = а[Ключ]; // !Структура

чтобы б детектировалась как структура.
Или это приведет к коллапсу и "переопределению" типа?
Тогда можно разрешить выбрать "уточнение" из уже определенных, а на другие - пусть ругается

**Comment by DmitryShvaika** [comment]
> > Тип Произвольный считается неопределенным, но фигурирует в типах аргументов процедур и функций в том числе и системных. В этом случае он должен быть строго определен.
> 
> Тут либо непонимание, либо нужно уточнить что имелось ввиду?
> 
> `Произвольный` - это один тип, а `Неопределено` - это другой тип. Два разных типа, с разным смыслом.

Если произвольный - это "тип" и он включает в себя число, строку и даже полеформы, то почему он не включает в себя структуру... Почему надо в типах писать Произвольный, Число, когда Произвольный и так включает в себя число.
Т.е. Произвольный в понимании edt некий нетипизированный тип, неопределенный тип.

**Comment by DmitryShvaika** [comment]
> 

Проблема, что для всех трех уровней в использовании типа Произвольный. И он будет разный по составу. Получается один Произвольный совсем не равен другому Произвольному. Возникает проблема с пониманием - входит ли в этом месте какой-то конкретный тип в указанный Произвольный или нет.

**Comment by DmitryShvaika** [comment]
Ну вот как раз пример на "Пересечение типов":

![image](https://user-images.githubusercontent.com/54451084/181440846-5a1fe4bb-6ba7-41fc-b5ff-816a29dc19f5.png)

Параметр МояТаблица имеет тип произвольный, параметр функции - ТаблицаЗначений, Массив из Структура и они вуаля - не пересекаются. Хотя я передаю Массив из структура. В параметре формы типа Массив нет, хотя его легко можно задать - выбрал произвольный.
Вопрос - как в строгих типах через параметр формы тогда передать массив структур чтобы не ругалось?
[test.zip](https://github.com/1C-Company/1c-edt-issues/files/9206306/test.zip)
проектик приложил с примером
