### ISSUE TITLE
2022.1 Не обновляется конфигурация ИБ

### ISSUE THREAD

**Issue by a2080016** [1C-Company/1c-edt-issues#578]
### Описание ошибки

EDT 2022.1 разучилась обновлять конфигурацию информационной базы размещенной на сервере с установленной блокировкой начала сеансов

### Как воспроизвести

1. Разместите ИБ на сервере 1С:Предприятие, установите блокировку начала сеансов, и установите код разрешения
![image](https://user-images.githubusercontent.com/24942027/180889747-aa39d2e8-a340-4681-8085-337e89fb56a1.png)

2. Сконфигурируйте доступ к ИБ
![image](https://user-images.githubusercontent.com/24942027/180890044-62943a89-5e7c-40c9-97a8-f0b14c35d962.png)

3. Запускайте приложение или запускайте отладку или вызывайте "Обновить конфигурацию..."

4. Смотрите ошибку: 
![image](https://user-images.githubusercontent.com/24942027/180891284-4477b21d-5d51-4872-ac15-1b29d95eceb0.png)

PS На 2021.3.4 ошибка не воспроизводится

### Ожидаемое поведение

Конфигурация ИБ обновляется.

### Лог рабочей области

[trace.log](https://github.com/1C-Company/1c-edt-issues/files/9185405/trace.log)

[.log](https://github.com/1C-Company/1c-edt-issues/files/9185411/default.log)

### Версия 1С:EDT

2022.1

### Операционная система

Windows

### Установленные плагины

1C:Code style V8

### Дополнительная информация

8.3.20.

**Comment by wolfandw** [comment]
исправление будет в 2022.1.1, изменения перенесены в релизную ветку, ошибку закрываю

**Comment by wolfandw** [comment]
исправление будет в 2022.1.1, изменения перенесены в релизную ветку, ошибку закрываю

**Comment by a2080016** [comment]
> исправление будет в 2022.1.1, изменения перенесены в релизную ветку, ошибку закрываю

Огонь! Спасибо!
