### ISSUE TITLE
Командный интерфейс расширения конфигурации не отображает дерево разделов

### ISSUE THREAD

**Issue by petypen** [1C-Company/1c-edt-issues#581]
### Описание ошибки

Ошибка в том что, на панели командного интерфейса расширения конфигурации в окне Раздел не отображается дерево разделов из списка подсистем.

Правильное поведение панели "Командный интерфейс" в основной конфигурации:
![2022-07-26_20-27-59](https://user-images.githubusercontent.com/6500075/181073115-28caf2ec-8f3e-42c9-b06b-6edbaea20c19.png)

Например, сейчас на скриншоте в окне "Разделы" выбран раздел "Префиксация объектов" и при этом в окне "Команды раздела" отображается настройка командного интерфейса для выделенного раздела.

А теперь неправильное поведение панели "Командный интерфейс" в расширении конфигурации.
![2022-07-26_20-37-51](https://user-images.githubusercontent.com/6500075/181075220-72eb452f-8fac-412a-9a7d-7716f5d3340f.png)

Например, я из основной конфигурации заимствовал две подсистемы и одну подсистему "Расш1_НоваяПодсистема" добавил непосредственно в расширение. Однако, в панели командного интерфейса ни одна подсистема не отображается.

### Как воспроизвести

Основная конфигурация - Демонстрационная конфигурация "Библиотека стандартных подсистем", редакция 3.1
Создано новое расширение. В расширении выполнено:
1. Заимствована подсистема "_ДемоНастройкаСинхронизации" вместе со своим родителем "_ДемоСинхронизацияДанных"
2. Заимствована подсистема "_ДемоПользователи" вместе со своим родителем "_ДемоУправлениеДоступом"
3. В заимствованной подсистеме "_ДемоУправлениеДоступом" создана __новая__ подсистема "Расш1_НоваяПодсистема"
4. В расширении создана новая общая команда "Расш1_ОбщаяКоманда". Эта общая команда связана с новой подсистемой "Расш1_НоваяПодсистема"
Схема метаданных на скриншоте:
![2022-07-26_20-56-46](https://user-images.githubusercontent.com/6500075/181078008-50c171b0-7e4a-4be9-b00f-a25ed8e208cd.png)

Расширение конфигурации готово. Если нужно, готов передать архив проекта.

Что бы увидеть проблему нужно на корне расширения конфигурации щелкнуть ПКМ и выбрать пункт меню "Открыть командный интерфейс". Будет открыта панель "Командный интерфейс", которая работает неправильно.

### Ожидаемое поведение

При открытии панели "Командный интерфейс" в конфигурации расширения я ожидаю: 
-- в окне "Разделы" видеть древовидный список разделов, который соответствует заимствованным и новым подсистемам расширения
-- в окне "Команды раздела" видеть настройку командного интерфейса соответствующую разделу, который выбран в окне "Разделы"

### Лог рабочей области

[metadata.zip](https://github.com/1C-Company/1c-edt-issues/files/9192261/metadata.zip)

### Версия 1С:EDT

Ruby 2022.1.0

### Операционная система

Windows

### Дополнительная информация

Версия платформы 1С 8.3.21.1393

**Comment by vadimeg** [comment]
Исправлено в 2022.2
