### ISSUE TITLE
Не работает типизация в ПриЧтенииНаСервере формы набора констант

### ISSUE THREAD

**Issue by sovaenga** [1C-Company/1c-edt-issues#582]
### Описание ошибки

Добавил константу, нарисовал форму редактирования, хочу получить значение в ПриЧтенииНаСервере
Контроль типов ругается, что ТекущийОбъект.ИмяНовойКонстанты не имеет типа

### Как воспроизвести

![image](https://user-images.githubusercontent.com/96619785/181262237-53b2132e-b8a8-461c-8a27-41e7a96fc5a1.png)

### Ожидаемое поведение

По точке после ТекущийОбъект должен появиться список констант

### Лог рабочей области

[лог.log](https://github.com/1C-Company/1c-edt-issues/files/9199456/default.log)

### Версия 1С:EDT

2021.3.4

### Операционная система

Windows

**Comment by MaksimDzyuba** [comment]
Здравствуйте, поправил, исправления войдут в 2022.2

**Comment by AlmazNasibullin** [comment]
@sovaenga Добрый день. В логе увидел ошибку, которая возникает при сравнении mdo-файла. Вы запускали какое-то сравнение mdo-файла? Например, при просмотре изменений в mdo-файле из панели индексирования Git.

**Comment by sovaenga** [comment]
> Вы запускали какое-то сравнение mdo-файла?
Возможно и запускал. Сейчас уже не припомню
