### ISSUE TITLE
Реквизиту формы не устанавливается тип "Произвольный", если делать это через выпадающий список

### ISSUE THREAD

**Issue by SeiOkami** [1C-Company/1c-edt-issues#588]
### Описание ошибки

Реквизиту формы не устанавливается тип "Произвольный", если делать это через выпадающий список

### Как воспроизвести

1. Перейдите в ректор формы
2. Добавить реквизит
3. Из списка выбора типа выбрать "Произвольный"
4. Переключиться на другой реквизит
5. Тип реквизита не применился

### Скриншоты

https://youtu.be/1_6wF5TgRD4

### Ожидаемое поведение

Тип устанавливается как нужно

### Лог рабочей области

[log.log](https://github.com/1C-Company/1c-edt-issues/files/9217582/log.log)

### Версия 1С:EDT

Ruby 2021.3.4

### Операционная система

Windows

### Установленные плагины

Нет плагинов

**Comment by RedMammoth** [comment]
дубль https://github.com/1C-Company/1c-edt-issues/issues/529

**Comment by vadimeg** [comment]
Проблема исправлена в 2022.1, к тому же дубль
