### ISSUE TITLE
Не работает типизация конструктора ХешированиеДанных

### ISSUE THREAD

**Issue by sovaenga** [1C-Company/1c-edt-issues#589]
### Описание ошибки

Конструктор позволяет добавлять не только двоичные данные, но и строки. А едт ругается, если добавляется строка
![image](https://user-images.githubusercontent.com/96619785/181708765-ce5bea20-50a2-4ccc-a96e-3c059f011116.png)

### Как воспроизвести

Напишите кусочек кода как на картинке с указанием // @strict-types в начале модуля

### Ожидаемое поведение

Поведение будет соответствовать описанию
![image](https://user-images.githubusercontent.com/96619785/181709102-3228643a-9b25-493f-8602-761cb030f5cd.png)

### Лог рабочей области

[лог.log](https://github.com/1C-Company/1c-edt-issues/files/9217658/default.log)

### Версия 1С:EDT

2021.3.4

### Операционная система

Windows

**Comment by RedMammoth** [comment]
дубль https://github.com/1C-Company/1c-edt-issues/issues/367 ?

**Comment by marmyshev** [comment]
@sovaenga просьба проверить на 2022.1 - там как раз чинилось в этом месте проверка, когда у метода есть несколько вариантов типов параметров.

**Comment by RedMammoth** [comment]
> @sovaenga просьба проверить на 2022.1 - там как раз чинилось в этом месте проверка, когда у метода есть несколько вариантов типов параметров.

у меня в 2022.1 ошибка пропала, закрою свою задачу

**Comment by marmyshev** [comment]
ошибки идентичные
