### ISSUE TITLE
Потеря картинок при импорте макетов типа "Графическая схема"

### ISSUE THREAD

**Issue by ilya2184** [1C-Company/1c-edt-issues#592]
### Описание ошибки

Если в конфигурации присутствуют макеты Графическая схема с "вложенными" картинками. При импорте конфигурации картинки могут отсутствовать в проекте или не имет картинок, полная загрузка конфигурации при обновлении становится невозможна с ошибками вида:
`Файл не найден - zip:///CommonTemplates/Макет/Ext/Template/Items/Декорация1/Picture.png` 
или
`Ошибка добавления объекта CommonTemplate uuid="ee04350e-c1ff-4a98-94b4-179dca3b19bc" : нельзя добавлять объекты метаданных без загрузки родительского объекта.`

### Как воспроизвести

1. Создайте новую конфигурацию в EDT
2. Привяжите её к пустой базе
3. Обновите конфигурацию из  EDT
4. Запустите конфигуратор из EDT для этой базы
5. Создайте новый общий макет типа графическая схема на основе файла
[Отчет АнализСостоянияНалоговогоУчетаПоНалогуНаПрибыль_ РасходыРаспределяемые.zip](https://github.com/1C-Company/1c-edt-issues/files/9231856/_.zip)
(этот файл я не сам придумал - это из типовой Бухгалтерии)
6. Обновите конфигурацию базы данных и закройте конфигуратор
7. Импортируйте конфигурацию в EDT
8. Удивляйтесь отсутствию картинок (1), а некоторых случаях и отсутствию макета (2)

### Скриншоты

![image](https://user-images.githubusercontent.com/14931660/182097782-c7bb22f0-2942-4504-befa-17eb4c6ca457.png)

### Ожидаемое поведение

Макеты с вложенными картинками импортируются с картинками
или
без картинок и без ссылок на эти картинки.

### Лог рабочей области

[log and trace log.zip](https://github.com/1C-Company/1c-edt-issues/files/9231892/log.and.trace.log.zip)

### Версия 1С:EDT

Ruby 2022.1.0

### Операционная система

Windows

### Установленные плагины

1C:Code style V8

**Comment by beg7** [comment]
Проблему воспроизвел. Критичность подтверждаю. Будем исправлять

**Comment by beg7** [comment]
Исправлена в 2022.1.1

**Comment by ilya2184** [comment]
Когда примерно публичная сборка будет доступна?

**Comment by beg7** [comment]
ориентировочно на следующей недели

**Comment by dab85** [comment]
тоже самое наблюдаю в 2023.3.6
