### ISSUE TITLE
Удаление реквизита справочника не убирает его из состава блокировочных полей

### ISSUE THREAD

**Issue by Daabramov** [1C-Company/1c-edt-issues#596]
### Описание ошибки

Если есть реквизит справочника, который входит в состав "Полей блокировки" для этого справочника, то при его удалении он из состава не убирается, что не позволяет  обновить конфигурацию БД

### Как воспроизвести

1. Создайте новый справочник
2. Создай в нем новый реквизит (типа строка)
3. Внести этот реквизит в состав "Поля блокировки данных" для этого справочника
4. Удалить этот реквизит
5. Проверить, что в составе полей блокировки появилось пустое поле
6. Попробовать обновить конфигурацию БД и получить ошибку

Путь обхода: Удалить это поле вручную
![image](https://user-images.githubusercontent.com/31928832/182816834-c3c707bc-ddfd-4a75-8a7b-b64b9b8f31d5.png)

### Ожидаемое поведение

Удаление реквизита должно убирать его из состава полей блокировки

### Лог рабочей области

[delete-block-field.log](https://github.com/1C-Company/1c-edt-issues/files/9258592/delete-block-field.log)

### Версия 1С:EDT

2021.1.0

### Операционная система

Windows

### Установленные плагины

1C:Code style V8, 1C:SSL-support

**Comment by beg7** [comment]
Исправлена в 2022.1.2
