### ISSUE TITLE
Ошибка отображается дважды

### ISSUE THREAD

**Issue by DmitryShvaika** [1C-Company/1c-edt-issues#6]
## Опишите ошибку

Если у документа не заполнены представление объекта и представление списка на форме отображается ошибка "Не заполнено ни представление объекта, ни представление списка". Но ошибка отображается дважды. 

## Как воспроизвести

Очистить представление объекта и представление списка. Дождаться ошибки.

## Ожидаемое поведение

Ошибка должна выводиться одна

## Скриншоты

![image](https://user-images.githubusercontent.com/54451084/134766576-58994743-5a84-411e-858a-dbc5e6bb4f45.png)

Странно, что Представление списка не помечено как ошибочное место, хотя оно упоминается в ошибке. Полагаю, как вариант, 2 ошибки выводятся как раз одна для представления объекта, вторая для представления списка. Но тогда Представление списка должно быть так же помечено как ошибочное и при заполнении представления объекта должна исчезать только одна ошибка, а не 2.
Вообще из текста ошибки не понятно - требуется оба представления заполнить или только одно из....

## Окружение (пожалуйста укажите информацию):

 - OS: Windows
 - Версия 1C:Code-Style-V8 0.1.0.119
 - Версия 1C:EDT Ruby 2021.2.5

**Comment by tretyakevich** [comment]
@marmyshev Это ошибка legacy-проверки или ошибка проверки code-style?
Если из code-style - был ли в рамках code-style был проведен анализ проблемы или нет?

**Comment by marmyshev** [comment]
> Это ошибка legacy-проверки или ошибка проверки code-style?

Это новые проверки из код-стайла (не легаси).

> был ли в рамках code-style был проведен анализ проблемы или нет?

В код-стайле проверил что есть единственное место регистрации issue в коде класса проверке, поэтому дублирование - явно не из-за код-стайла. Дальше не разбирался.

**Comment by tretyakevich** [comment]
Исправлена в 2021.2.3
