### ISSUE TITLE
Новый серверный модуль создавать по умолчанию сразу с правильными флажками области компиляции по стандартам 1с

### ISSUE THREAD

**Issue by DmitryShvaika** [1C-Company/1c-edt-issues#60]
## Описание проблемы
 
Создаю новый серверный модуль, он создается с флажком только Сервер, когда по стандартам должны еще стоять флажки Внешнее соединение и Клиент (обычное приложение). Было удобней, если бы флажки по умолчанию сразу ставились в соответствии со стандартами 1с.

![image](https://user-images.githubusercontent.com/54451084/140320547-35e4b62e-e252-42bc-b983-89d417d64a8d.png)

![image](https://user-images.githubusercontent.com/54451084/140320705-67fd3232-9504-496b-8332-3f27c15f441e.png)

 
 
## Описание решения проблемы

По умолчанию при создании общего модуля должны быть установлены флажки Серверный, Внешнее соединение и Клиент (обычное приложение).

Желательно, чтобы алгоритм парсил название модуля, и по суффиксу определял один из 4-х типов. А так же определял признаки Глобальный и Повторного использования.

![image](https://user-images.githubusercontent.com/54451084/140514728-9a3a1637-c52e-46f8-bf9e-d928a6c03bea.png)

**Comment by RedMammoth** [comment]
Через мастер (по кнопке далее) ставит галки:
![image](https://user-images.githubusercontent.com/64589646/140736798-76bd54db-5028-4f31-b05f-8791a6a5a1e8.png)
![image](https://user-images.githubusercontent.com/64589646/140736858-9fd75290-edee-43b9-a6e9-e3b077deb888.png)
![image](https://user-images.githubusercontent.com/64589646/140736920-7c894138-4aca-456a-bc8c-5eaff62bf568.png)

**Comment by marmyshev** [comment]
> Желательно, чтобы алгоритм парсил название модуля, и по суффиксу определял один из 4-х типов. А так же определял признаки Глобальный и Повторного использования.

Ровно так и делается.  Но типов несколько больше...

"По стандартам 1С" - это в проект по поддержке стандартов... А там оно уже сделано.
