### ISSUE TITLE
Не отображаются страницы группы страниц с вариантом отображения "Авто"

### ISSUE THREAD

**Issue by unichkin** [1C-Company/1c-edt-issues#603]
### Описание ошибки

Не работает отображение страниц, замечено для внешней обработки и документа

### Как воспроизвести

1. Создать форму внешней обработки
2. Добавить группу страниц с отображением закладок "Авто"
3. Добавить подчиненные страницы, поместить в них любые реквизиты
4. При позиционировании на группу страниц нет закладок
5. При выборе иного варианта отображения закладок они появляются
6. Само по себе отображение работает довольно криво

### Скриншоты

![image](https://user-images.githubusercontent.com/10799597/184852996-6983b3b7-93b8-4091-b39e-104ef4768289.png)
![image](https://user-images.githubusercontent.com/10799597/184853099-d81137f8-bf86-47cb-875a-1eb7a4eafaf8.png)

### Ожидаемое поведение

В варианте "Авто" страницы должны отображаться сверху

### Лог рабочей области

[Логи.zip](https://github.com/1C-Company/1c-edt-issues/files/9349688/default.zip)

### Версия 1С:EDT

Ruby 2021.3.4

### Операционная система

Windows

### Дополнительная информация

Платформа 8.3.21, воспроизводится у нескольких разработчиков

**Comment by vadimeg** [comment]
Исправлено в 2022.1.2
