### ISSUE TITLE
Не отображаются элементы соответствия в отладке

### ISSUE THREAD

**Issue by unichkin** [1C-Company/1c-edt-issues#606]
### Описание ошибки

Перешли недавно на платформу 8.3.21.1393. Проект был переведен реимпортом конфигурации на формат 8.3.21.
Сегодня заметили, что не отображаются элементы соответствия в отладке.

### Как воспроизвести

Создать элемент соответствия, вставить в него пару элементов, в отладке - навести мышь, поместить в окно выражений, коллекция будет отображаться как пустая.

### Скриншоты
![image](https://user-images.githubusercontent.com/10799597/185410420-ad1b447a-6723-48ea-9193-5a420371c4ff.png)

### Ожидаемое поведение

Должно работать, хотя-бы как было... А лучше - как работало отображение коллекций в конфигураторе. С возможностью вывести список в таб. док, и прочим.

### Лог рабочей области

[Лог.zip](https://github.com/1C-Company/1c-edt-issues/files/9374308/default.zip)

### Версия 1С:EDT

Ruby 2021.3.4

### Операционная система

Windows

**Comment by DmitryBelov-e1c** [comment]
@unichkin Здравствуйте, подскажите, пожалуйста, на какой версии в данный момент ведётся разработка и наблюдается ли подобное поведение? Спасибо.

**Comment by RedMammoth** [comment]
От себя могу добавить, что на 2023.2.3 все еще есть такое поведение наблюдается

**Comment by a2080016** [comment]
> От себя могу добавить, что на 2023.2.3 все еще есть такое поведение
> 
> ![image](https://private-user-images.githubusercontent.com/64589646/293105419-ea35537e-7634-4a6c-a1de-eb1d49ab51a8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM3NTU3NjQsIm5iZiI6MTcwMzc1NTQ2NCwicGF0aCI6Ii82NDU4OTY0Ni8yOTMxMDU0MTktZWEzNTUzN2UtNzYzNC00YTZjLWExZGUtZWIxZDQ5YWI1MWE4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI4VDA5MjQyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ4OTVjMWFkMjFlZGY4N2ViZTY0NmNjNmFmZTc1ZDk2NjJmODlmMTU1YjcwYzk2YTBlMTAxOWMzMDAwYTM3ODcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.JrdNkgGtCgg9kF963YqFdt0rXsYVgz6vHA-i5Mb8_jo) ![image](https://private-user-images.githubusercontent.com/64589646/293105448-2c5d5969-cf1f-462d-bf15-3bb744baf87d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM3NTU3NjQsIm5iZiI6MTcwMzc1NTQ2NCwicGF0aCI6Ii82NDU4OTY0Ni8yOTMxMDU0NDgtMmM1ZDU5NjktY2YxZi00NjJkLWJmMTUtM2JiNzQ0YmFmODdkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI4VDA5MjQyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdkODJkYzk5OTBmZGJhMjMxOWUyYWVjZDk3ZTlhNDMwNmJkOGUxMDM0Yzg0NDJmMjhmYmRjZDg3NDJjOTE1YTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.gL-lsTg2DbZR0fEEZAVmFGrsge76AK79eAx2naPgzU0)

А платформа? 
https://github.com/1C-Company/1c-edt-issues/issues/1134#issuecomment-1870601071

**Comment by RedMammoth** [comment]
> А платформа?
В проекте 8.3.21, отладка запускается на 8.3.21.1890

**Comment by DmitryBelov-e1c** [comment]
> В проекте 8.3.21, отладка запускается на 8.3.21.1890

Добрый день, Константин. На момент 2021.3.4 было 2 проблемы (одна EDT, вторая Платформы), которые в дальнейшем были независимо и в разное время исправлены. С Платформой версии 8.3.21 вышла накладка - исправление так и не пересобрали, и это, видимо, будет в дальнейшем ограничением при работе с EDT. Тем не менее, официальные декабрьские выпуски 22-24 содержат исправления, поэтому проверять надо на них.

**Comment by RedMammoth** [comment]
Добрый день! Понял, спасибо за информацию. В ближайших планах будет скорей всего переход на 24 версию, по итогам перехода дополню комментарий.

**Comment by RedMammoth** [comment]
@DmitryBelov-e1c , добрый день! 
Попробовал на 2023.3.0, на платформе 8.3.24.1368. У меня ошибка больше не воспроизводится. Попробовал несколько больших структур с несколькими соответствиями, где раньше практически всегда ловил ошибку - сейчас все хорошо.

**Comment by DmitryBelov-e1c** [comment]
Закрыто в связи с отсутствием обратной связи от автора обращения и работоспособности изменений у других пользователей.
