### ISSUE TITLE
Отключать запрос о реструктуризации информации

### ISSUE THREAD

**Issue by ilya2184** [1C-Company/1c-edt-issues#607]
### Описание проблемы

Не получается обновить конфигурацию информационной базы без участия пользователя: после нажатия на кнопку обновления приходится следить когда же появится запрос о реструктуризации информации.
![image](https://user-images.githubusercontent.com/14931660/185761987-c9345da2-1213-4383-b363-3b68f5da9b5b.png)

### Описание решения проблемы

Хочется флаг: не спрашивать о реструктуризации (например рядом с "загрузить конфигурацию полностью" в меню обновления), нажать на кнопку и идти по своим делам.

**Comment by adminimusRU** [comment]
В идеале хочется вариант настройки "Показывать диалог реструктуризации только при наличии ошибок/предупреждений".

**Comment by ilya2184** [comment]
@adminimusRU согласен: поле ввода со списком выбора подойдёт бОльшему количеству людей:
показывать предупреждения:
 - не показывать
 - ошибки
 - ошибки/предупреждения
 - ошибки/предупреждения/информацию
(похоже на настройку журнала регистрации в Конфигураторе)

**Comment by nikolay-martynov** [comment]
Здравствуйте. Начиная с версии 2023.2 вы можете отключить запрос на подтверждение реструктуризации информационной базы. В этом случае информационная база будет реструктуризироваться автоматически, когда в этом будет возникать необходимость.
![image](https://github.com/user-attachments/assets/fd9f885b-bdf3-41b0-82e4-443ec5368767)
Вы можете предварительно открыть свойства информационной базы используя её контекстное меню в панели "Информационные базы" и установить переключатель в выключенное положение. При дальнейшем обновлении данной информационной базы запросы выдаваться не будут. Настройку можно выполнить индивидуально для каждой информационной базы в отдельности.
![image](https://github.com/user-attachments/assets/bddac35d-ebad-4f7c-ab08-893afccac415)
Если вы привыкли обновлять конфигурацию информационной базы через контекстное меню панели "Навигатор", то при обновлении одновременно нескольких баз можете выставить им различные режимы подтверждения.
![image](https://github.com/user-attachments/assets/1ce94759-2b51-49cf-ad05-6be24ef78d87)
