### ISSUE TITLE
[1CEDT] Ошибка LayoutProblem: null при заимствовании (или обновлении) формы в расширении

### ISSUE THREAD

**Issue by EChudnovsky** [1C-Company/1c-edt-issues#608]
Добрый день, ошибка по прежнему воспроизводится на EDT 2022.1
продолжение [задачи 567](https://github.com/1C-Company/1c-edt-issues/issues/567)

![изображение](https://user-images.githubusercontent.com/5530435/185865391-05d9f98b-4ba9-4ce3-99f8-25af6a15fb53.png)

Прикладываю
1. Журнал логов
[log.log](https://github.com/1C-Company/1c-edt-issues/files/9392243/log.log)

2. Состояние объектов до момента обновления формы из основной конфигурации
Документ основной конфигурации:
[ТабельУчетаРабочегоВремени.zip](https://github.com/1C-Company/1c-edt-issues/files/9392208/default.zip)

Документ расширения:
[ТабельУчетаРабочегоВремени_расширение.zip](https://github.com/1C-Company/1c-edt-issues/files/9392221/_.zip)

Product name: 1C:Enterprise Development Tools
Product version: 1.26.0.437
Java home: C:\Program Files\BellSoft\LibericaJDK-11-Full
Java vm name: OpenJDK 64-Bit Server VM
Java vm info: mixed mode
Java version: 11.0.12
Java vendor: BellSoft
OS: win32
Total mem: 17 179
Free mem: 9 974
Cores: 16

**Comment by vadimeg** [comment]
Добрый день, ошибка исправлена в исправительной версии релиз-кандидата, которая еще не вышла.
