### ISSUE TITLE
Поиск по конфигурации не находит имени общего модуля в обработчике подписки на событие

### ISSUE THREAD

**Issue by DmitryShvaika** [1C-Company/1c-edt-issues#61]
## Опишите ошибку

Выполняю поиск по конфигурации по имени общего модуля. Поиск выдает только имя общего модуля, хотя модуль используется в обработчике подписки на событие. Подписку на событие поиск не видит.

![image](https://user-images.githubusercontent.com/54451084/140324396-11d67457-b358-41d7-9aa2-01e8ab72aa44.png)

Архив проекта тестового примера прилагаю

[Тест.zip](https://github.com/1C-Company/1c-edt-issues/files/7475202/default.zip)

## Как воспроизвести

1. Выполнить поиск по конфигурации с выражением "ОбщийМодульСервер".

## Ожидаемое поведение

Поиск должен отобразить в результатах поиска подписку на событие "ПодпискаНаСобытие".

## Окружение (пожалуйста укажите информацию):

 - OS: Windows 10
 - Версия 1C:EDT 2021.2.8
 - Версия платформы 1С 8.3.12

**Comment by tretyakevich** [comment]
Исправлено в 2022.2
