### ISSUE TITLE
[1CEDT] Ошибка назначения основных форм объекта в расширении конфигурации.

### ISSUE THREAD

**Issue by EChudnovsky** [1C-Company/1c-edt-issues#612]
```
Назначенные в EDT формы объекта в расширении не применяются к конфигурации.

Описание ситуации:
1. Имеется типовая конфигурация ЗУП
2. Справочнику "ПрограммыМедицинскогоСтрахования" необходимо назначить форму списка (типовая форма списка отсутствует)
3. Создается форма списка (в основной конфигураци или в расширении тестировали два варианта поведение одинаковое)
4. В расширении для справочника назначается форма списка.
5. Применяем изменения к конфигурации (способ применения полная загрузка\частичная не влияет)
6. Открываем конфигуратор поле списка для справочника в расширении остается не  заполненым.
Product name: 1C:Enterprise Development Tools
Product version: 1.26.1.27
Java home: C:\Program Files\BellSoft\LibericaJDK-11-Full
Java vm name: OpenJDK 64-Bit Server VM
Java vm info: mixed mode
Java version: 11.0.12
Java vendor: BellSoft
OS: win32
Total mem: 17 179
Free mem: 12 790
Cores: 16
1С:Предприятие 8.3 (8.3.19.1417)
```

**Comment by EChudnovsky** [comment]
Обращаю внимание в версии 2022.1.1 ( как и в предыдущей ) при создании задачи github, не работает передача скриншота и прикрепленных файлов. Не понятен, тогда смысл этого функционала.

![изображение](https://user-images.githubusercontent.com/5530435/186652927-4912168f-afb6-4e86-aa17-f6cd6c1a1a7c.png)

**Comment by EChudnovsky** [comment]
Файл картинки по основной задаче:

![изображение](https://user-images.githubusercontent.com/5530435/186653177-4e5f46bc-4e4f-4888-bbce-fafc4f6ae91d.png)

**Comment by vadimeg** [comment]
Свойства установки основных форм в расширении - управляемые. Если делать это не в редакторе справочника, а через палитру, то для того, чтобы добавить основную форму, придется включить контроль. В редакторе есть ошибка - свойства всегда доступны для редактирования, даже без включенного контроля. Эту ошибку исправим.

![image](https://user-images.githubusercontent.com/17178862/215053871-87f40677-7c86-4359-8e11-ecfef8f5d071.png)

**Comment by tretyakevich** [comment]
Исправлено в 2023.2
