### ISSUE TITLE
Формирование файла описания формы (сегменты notDefaultUseAlwaysAttributes)

### ISSUE THREAD

**Issue by ilya2184** [1C-Company/1c-edt-issues#619]
### Описание ошибки

Если в реквизите формы типа Динамический список, основанном на произвольном запросе, на одном из полей установить флаг "Использовать всегда", а затем изменить запрос таким образом что поле перестает существовать, проверка form-data-path регистрирует ошибку
Свойство "Не установлено "Использовать всегда"" имеет некорректное значение "Список.поле1": 2 сегмент "поле1" ссылается на неизвестный объект
вероятно это происходит из-за того что при обновлении файла описания формы при изменении запроса списка узлы notDefaultUseAlwaysAttributes не проверяются на существование (сохраняются в форме без возможности исправления штатными средствами)

### Как воспроизвести

1. Создайте форму списка справочника, документа или другого объекта
2. Измените сфойство "Произвольный запрос" реквизита "Список" на Истина
3. Установите флаг "Использовать всегда" на любом из реквизитов Список, например Номер или Код
4. Сохраните форму
5. Измените запрос таким способом чтобы поля п.3 - небыло в запросе
6. Наблюдайте ошибку на панели Ошибки конфигурации

### Скриншоты

Отображение ошибки на панели ошибок
![image](https://user-images.githubusercontent.com/14931660/187270807-41d07246-ea88-4356-b50f-a4d6435db195.png)

Призрак в файле форме
![image](https://user-images.githubusercontent.com/14931660/187271119-61a1a05a-f212-4b88-9a90-57fda92b1512.png)

### Ожидаемое поведение

При изменении сохранении формы сегменты notDefaultUseAlwaysAttributes которых нет в полях схемы списка - не сохраняются

### Лог рабочей области

[ — копия.log](https://github.com/1C-Company/1c-edt-issues/files/9447024/default.log)

### Версия 1С:EDT

2022.1.1

### Операционная система

Windows

### Установленные плагины

Другие сторонние плагины `Название плагина...`

**Comment by vadimeg** [comment]
EDT повторяет поведение конфигуратора. Но в EDT, в отличие от конфигуратора, есть проверка на "битые пути".
Если повторить описанный сценарий в конфигураторе, а затем выгрузить конфигурацию в платформенный xml, то в нем можно увидеть секцию:

			<UseAlways>
				<Field>~Список.Code</Field>
			</UseAlways>

Или так:
			<UseAlways>
				<Field>~Список.Code~Список.Код</Field>
			</UseAlways>

Т.е. битый путь не удаляется, а выгружается. После импорта этого xml в EDT сработает проверка и в списке ошибок появится соответствующая запись. На ошибку есть квик-фикс. При желании можно его применить и удалить секцию.
А можно оставить на случай, если переход к произвольному запросу (или исключение поля из запроса) был временным.

**Comment by tretyakevich** [comment]
Добавлена автоматическая очистка при изменении динамического списка.
