### ISSUE TITLE
"Поиск в конфигурациях" не ищет в макетах с типом макета "Табличный документ"

### ISSUE THREAD

**Issue by aekrendelev** [1C-Company/1c-edt-issues#624]
### Описание ошибки

Ошибка в том что при поиске по строке не находятся макеты с типом "Табличный документ" содержащие искомую строку.

### Как воспроизвести

1. Разверните проект из приложенной выгрузки (демо конфигурация платформы 1с).
2. В панели "Навигатор" перейдите на объект Обработки.АдминистративныйСервис, в контекстном меню выберите "Создать - Макет".
3. Тип макета оставляем "Табличный документ" и нажимаем кнопку "Готово".
4. Открывается табличный документ, в ячейку 1:1 пишем текст Тестовая строка .
5. Нажимаем в командной панели сверху кнопку "Сохранить все".
6. Закрываем все формы.
7. Нажимаем в командной панели сверху кнопку "Поиск".
8. Активизируем вкладку "Поиск в конфигурациях".
9. В строку поиска вводим Тестовая строка .
10. Ставим галку "Макеты" и нажимаем кнопку "Поиск".
11. В результатах поиска получаем 0 совпадений.

### Скриншоты

![Снимок экрана в 2022-08-30 13-55-36](https://user-images.githubusercontent.com/91385485/187419937-d90e636b-6c5b-48e7-9b93-1f955f92e9c7.png)
![Снимок экрана в 2022-08-30 14-06-44](https://user-images.githubusercontent.com/91385485/187421412-ecb55a7b-4df8-41e5-a9ad-db2e8339c825.png)

### Ожидаемое поведение

Правильно отобразить добавленный ранее макет в результатах поиска.

### Лог рабочей области

[logs.zip](https://github.com/1C-Company/1c-edt-issues/files/9452243/logs.zip)

### Версия 1С:EDT

Ruby 2022.1.1

### Операционная система

Linux

### Установленные плагины

1C:Code style V8, 1C:SSL-support

### Дополнительная информация

[1Cv8.dt.zip](https://github.com/1C-Company/1c-edt-issues/files/9452248/1Cv8.dt.zip)

1С:Предприятие 8.3 (8.3.20.1789)

**Comment by tretyakevich** [comment]
Исправлено в 2022.2
