### ISSUE TITLE
В расширении не отображается назначенный обработчик события формы после импорта расширения из ИБ

### ISSUE THREAD

**Issue by aekrendelev** [1C-Company/1c-edt-issues#626]
### Описание ошибки

Ошибка в том что не отображаются в палитре свойств формы назначенные обработчики событий после импорта проекта расширения из ИБ.

### Как воспроизвести

1. Разверните проект из приложенной выгрузки (демо конфигурация платформы 1с), без расширений.
2. В панели "Приложения" выделите строку приложения и в контекстном меню "Импортировать расширения..."
3. Отметьте Расширение1 и нажмите кнопку "Готово".
4. Появится проект расширения.
5. Выделите в панели "Навигатор" в расширении объект Справочники.Организации.Формы.ФормаЭлемента и контекстном меню нажмите "Открыть".
6. Откроется форма, в которой в палитре свойств не отображается обработчик Расш1_ПередЗаписьюНаСервереПосле и Расш1_ПослеЗаписиПосле, хотя они отображаются в конфигураторе.

### Скриншоты

![Снимок экрана в 2022-08-31 16-48-26](https://user-images.githubusercontent.com/91385485/187696047-b904c359-b8ae-42a4-b9d1-71dabf1aef18.png)
![Снимок экрана в 2022-08-31 16-54-26](https://user-images.githubusercontent.com/91385485/187696077-d4011e17-f8da-4b88-b68c-16b7372c17af.png)

### Ожидаемое поведение

Отображаются назначенные обработчики событий, как в конфигураторе.

### Лог рабочей области

[logs.zip](https://github.com/1C-Company/1c-edt-issues/files/9462079/logs.zip)

### Версия 1С:EDT

Ruby 2022.1.1

### Операционная система

Linux

### Установленные плагины

1C:Code style V8, 1C:SSL-support

### Дополнительная информация

1С:Предприятие 8.3 (8.3.20.1789)

[1Cv8.dt.zip](https://github.com/1C-Company/1c-edt-issues/files/9462153/1Cv8.dt.zip)

**Comment by vadimeg** [comment]
То же, что и
https://github.com/1C-Company/1c-edt-issues/issues/410
https://github.com/1C-Company/1c-edt-issues/issues/475
