### ISSUE TITLE
Ложные срабатывания идентификации расширенных элементов формы

### ISSUE THREAD

**Issue by agibalovsa** [1C-Company/1c-edt-issues#642]
### Описание ошибки

1. После расширения некоторых форм, некоторые элементы отображаются как измененные, хотя их ни кто не менял.
Эти элементы отображаются, если фильтр нажат.
И цвет у этих элементов не серый.

При всем этом в некоторых формах, можно расширить какой-нибудь элемент, и удалить его из расширения снова. И описанные выше проблемы частично уходят. Но при этом изменений в гит хранилище не наблюдается. От куда можно заключить, что подглючивает само отображение.

2. Часть элементов, такие как "Контекстное меню", "Командная панель", отображаются не серым цветом, хотя их не меняли. Но при фильтрации они не отображаются.

3. Также, если есть добавленные кнопки в командной панели, то они не отображаются при фильтрации.

### Как воспроизвести

Могу дать доступ в свой проект EDT, чтобы такие случаи можно было отловить.

### Скриншоты

![image](https://user-images.githubusercontent.com/14235747/190430567-178a9114-7532-4bd6-900c-4aff1c8a1ace.png)

![image](https://user-images.githubusercontent.com/14235747/190431386-7f3eff9c-0d91-45bd-a9a9-9c5d2870526a.png)

![image](https://user-images.githubusercontent.com/14235747/190645612-310838bd-f076-41a9-98fd-7ffaf2bc3bbc.png)

### Ожидаемое поведение

В форме при фильтрации должны отображаться только измененные элементы.
Все не измененные элементы должны иметь серый цвет текса.

### Лог рабочей области

[log.zip](https://github.com/1C-Company/1c-edt-issues/files/9576153/log.zip)

### Версия 1С:EDT

Ruby 2022.1.1

### Операционная система

Windows

### Установленные плагины

1C:Code style V8, 1C:SSL-support

**Comment by vadimeg** [comment]
Исправлено в 2024.2
