### ISSUE TITLE
Не верный идентификатор объекта формы при его расширении

### ISSUE THREAD

**Issue by agibalovsa** [1C-Company/1c-edt-issues#644]
### Описание ошибки

Если в расширенной форме создано несколько реквизитов расширения, а потом расширяется объект, то один из реквизитов помечается как ошибочный из-за того, что объект принимает его идентифиактор.

### Как воспроизвести

1. Расширяется форма и вней создается несколько реквизитов формы.
2. Удаляется проект, создаетсяновый и импортируется туда ранее созданное расширение. (Чтобы уж наверняка)
3. Расширяется объект в  расширенной формы , первый за ним созданный ранее реквизит формы расширения помечается как ошибочный.
4. Удаляется объект из расширения, ошибка пропадает.
5.  Добавляется снова. Второй по очередности созданный ранее реквизит формы расширения  помечается как ошибочный.
И т.д. пока не счетчик не пройдет по идентификаторам всех созданных в расширенной форме реквизитов.
П.С. Такое происходит не только с объектом формы, но и с любым реквизитом, который расширяется.

### Скриншоты

![image](https://user-images.githubusercontent.com/14235747/190484929-1c79f597-ed9e-43dd-9f7a-745587a56d49.png)

![image](https://user-images.githubusercontent.com/14235747/190485201-2b4390a9-20fa-45c8-9a77-33ad67314f8b.png)

### Ожидаемое поведение

При расширении какого либо реквизита в форме, должны учитываться идентификаторы созданных ранее реквизитов.

### Лог рабочей области

[log.zip](https://github.com/1C-Company/1c-edt-issues/files/9578162/log.zip)

### Версия 1С:EDT

Ruby 2022.1.1

### Операционная система

Windows

### Установленные плагины

1C:Code style V8, 1C:SSL-support

**Comment by vadimeg** [comment]
Исправлено в 2023.1

**Comment by agibalovsa** [comment]
@vadimeg, добрый день. Такой момент еще наблюдается: если выполнять слияние форм с помощью VScode, например, и в каждой ветке был создан свое поле на форме, то в итоге получаем, что идентификаторы реквизитов, полей, дублируются. EDT на это ни как не реагирует, не исправляет, не сообщает. В рамках исправления этой ошибки, был предусмотрен такой сценарий слияния, или стоит написать новую "ишузу"?

**Comment by vadimeg** [comment]
Добрый день, по дублированию идов есть задача - https://github.com/1C-Company/1c-edt-issues/issues/885
Можно либо дописать туда сценарий или создать новый баг

**Comment by agibalovsa** [comment]
ОК

**Comment by vadimeg** [comment]
> @vadimeg Спасибо. Ошибка зарегистрирована несколько раз. [1C-Company/dt-project-checks#7](https://github.com/1C-Company/dt-project-checks/issues/7)
> 
> Я правильно понимаю, данную задачу реализовали?

Да. Исправлено в 2023.1
