### ISSUE TITLE
Не верно открывается файл формы, при выборе пункта меню "Open with"

### ISSUE THREAD

**Issue by agibalovsa** [1C-Company/1c-edt-issues#651]
### Описание ошибки

Когда я хочу открыть файл формы с помощью текстового редактора, чтобы подправить ошибки формата, о которых сигнализирует EDT. То открывается файл справочника.

### Как воспроизвести

1. Выделить форму справочника
2. Выбрать пункт меню "Open with" и какой-нибудь редактор
3. В редакторе открывается файл справоника mdo

### Скриншоты

![image](https://user-images.githubusercontent.com/14235747/190646369-110917a0-74c4-4ef3-918d-58a297b1bb41.png)

### Ожидаемое поведение

При нажатии на форму справочника открывать файл формы справочника.

### Лог рабочей области

[log.zip](https://github.com/1C-Company/1c-edt-issues/files/9584281/log.zip)

### Версия 1С:EDT

Ruby 2022.1.1

### Операционная система

Windows

### Установленные плагины

1C:Code style V8, 1C:SSL-support

**Comment by RedMammoth** [comment]
дубль https://github.com/1C-Company/1c-edt-issues/issues/308 ?

**Comment by agibalovsa** [comment]
Да, оно.

**Comment by vadimeg** [comment]
Исправлено в 2023.1
