### ISSUE TITLE
Разрушение формы расширения. Failed to resolve container by its ID=142936511611083

### ISSUE THREAD

**Issue by agibalovsa** [1C-Company/1c-edt-issues#656]
### Описание ошибки

После обновление конфигурации форма в расширении потеряла часть эементов. А когда я стал обновлять форму, она разрушилась и перестала отображаться.
Возникла ошибка: 
Failed to resolve container by its ID=142936511611083

### Как воспроизвести

1) В форме расширения нет элементов из новой формы.
2) при этом в форме не выходит статус об обновлении.
3) Жму, обновить форму из конфигурации
4) Форма разрушается.
Воспроизводится в моей ИБ. Могу предоставить доступ.

### Скриншоты

![image](https://user-images.githubusercontent.com/14235747/191013302-2cdf20f0-4525-44fc-936c-1cb816705412.png)

### Ожидаемое поведение

При обновлении формы расширения не должно происходить ее разрушения.

### Лог рабочей области

[log.zip](https://github.com/1C-Company/1c-edt-issues/files/9598691/log.zip)

### Версия 1С:EDT

Ruby 2022.1.1

### Операционная система

Windows

### Установленные плагины

1C:Code style V8, 1C:SSL-support

**Comment by vadimeg** [comment]
Добрый день, можете прислать форму (каталог исходников формы) в том виде, какой она была на первом шаге воспроизведения?

**Comment by Erik773** [comment]
Закрываем задачу, так как недостаточно информации для воспроизведения. при предоставлении данных, просьба открыть повторно.
