### ISSUE TITLE
Ложные ошибки  в редакторе запроса отсутсвия "Стандартных реквизитов" для расширений

### ISSUE THREAD

**Issue by agibalovsa** [1C-Company/1c-edt-issues#657]
### Описание ошибки

В расширении в редакторе запроса возникают ложные ошибки для реквизитов составного типа, 
Например, ругается, если обращаться из реквизитов составного типа к таким полям как "Владелец", "Код", "Наименование".
Хотя все эти поля расширены, и в конфигураторе запрос спокойно открывается.

### Как воспроизвести

1. Расширить объект с реквизитом составного типа
2. Обратиться в запросе к стандартному реквизиту из реквизита составного типа. (см. скриншот)

### Скриншоты

![image](https://user-images.githubusercontent.com/14235747/191028450-4829f4b6-e589-444c-afb9-66d8ed345dd9.png)

![image](https://user-images.githubusercontent.com/14235747/191028757-7249b6ab-032a-46b7-8412-948614589382.png)

![image](https://user-images.githubusercontent.com/14235747/191030397-f03a50d3-2c78-478e-af2a-a570470f543a.png)

### Ожидаемое поведение

Ошибок не должно никаких отображаться, т.к. в конфигураторе все нормально открывается.

### Лог рабочей области

[log.zip](https://github.com/1C-Company/1c-edt-issues/files/9599331/log.zip)

### Версия 1С:EDT

Ruby 2022.1.1

### Операционная система

Windows

### Установленные плагины

1C:Code style V8, 1C:SSL-support

**Comment by MaksimDzyuba** [comment]
Здравствуйте, я видимо из описания не понял как воспроизводить, не получается никак воспроизвести, не могли бы прислать демо пример с проблемой, ну или реальные данные. Прикладываю скрин своих попыток

![image](https://user-images.githubusercontent.com/77277424/192538999-9e36397d-7bd1-4591-938b-275e132cd1db.png)

**Comment by agibalovsa** [comment]
Здравствуйте. Давайте спишимся в телеграм, я вам, наверное, лучше открою доступ к git репозиторию. Так быстрее будет.
Моя ссылка https://t.me/agibse.

**Comment by MaksimDzyuba** [comment]
удалось поправить, войдет в 2022.2

![image](https://user-images.githubusercontent.com/77277424/192807912-1dbac20b-26de-4382-9933-2b661129b992.png)
