### ISSUE TITLE
Постоянно сворачиваются раскрытые области в панели Схема по мере набора кода

### ISSUE THREAD

**Issue by adminimusRU** [1C-Company/1c-edt-issues#661]
### Описание ошибки

При любом вводе или удалении текста в редакторе модуля панель Схема постоянно перестраивается, раскрытые области сворачиваются. Это делает навигацию по схеме крайне неудобной, особенно на больших модулях с вложенными областями.

### Как воспроизвести

1. Ввести в редактор кода текст модуля:
```
#Область Область1

Процедура Процедура1()
	
	// код процедуры
	
КонецПроцедуры

#КонецОбласти

#Область Область2

Процедура Процедура2()
	
	
	
КонецПроцедуры

#КонецОбласти
```
2. Раскрыть область `Область1 ` в панели Схема;
4. Установить курсор в тело метода `Процедура2` и набрать произвольную строку кода;
5. Схема в панели перестроится и `Область1 ` окажется снова свернутой.

### Скриншоты

![edt-module-scheme-bug](https://user-images.githubusercontent.com/28653631/191521484-2aa71436-9147-4b66-9e62-7b51e338bfea.gif)

### Ожидаемое поведение

Вручную раскрытые области должны оставаться раскрытыми.

### Лог рабочей области

Не требуется.

### Версия 1С:EDT

2022.1.2

### Операционная система

Windows

### Дополнительная информация

На версии 2021.3.4 поведение было корректное. Ошибка воспроизводится на 2022.1.0 и 2022.1.2.
Стабильно срабатывает при любом изменении кода, вводе или удалении строк.

**Comment by adminimusRU** [comment]
На 2022.2.2 проблема всё еще актуальна.

**Comment by MaksimDzyuba** [comment]
Исправление войдет в 2023.1, если будет еще один выпуск 2022.2, то постараемся включить и в нее.
![bandicam 2023-03-17 13-18-45-688](https://user-images.githubusercontent.com/77277424/225878334-5715d30c-fb10-43ed-b176-40c71ccb2590.gif)
