### ISSUE TITLE
Не работает сравнение объединение для WS-ссылок содержащих директивы импорта

### ISSUE THREAD

**Issue by shcherbakov-vadim** [1C-Company/1c-edt-issues#663]
### Описание ошибки

Не работает сравнение объединение для WS-ссылок содержащих директивы импорта

### Как воспроизвести

1. Развернуть вложенный архив с проектом EDT
2. Импортровать проект в рабочую область
3. Выполнить слияние ветки master в ветку test
4. Попробовать обновить конфигурацию ИБ и получить ошибку
5. Переключиться на ветку master и убедиться, что обновление конфигурации ИБ проходит без ошибок

### Скриншоты

![2022-09-22_00-54-59](https://user-images.githubusercontent.com/52153345/191617655-7306824d-198f-4b53-9c20-a4ea960325c3.jpg)

### Ожидаемое поведение

При сравнении объединении импортированные схемы должны попасть в результирующую конфигурацию

### Лог рабочей области

нет

### Версия 1С:EDT

2021.3.4, 2022.1.2

### Операционная система

Windows

### Дополнительная информация

8.3.18.1779
[config.zip](https://github.com/1C-Company/1c-edt-issues/files/9623537/config.zip)

**Comment by AlmazNasibullin** [comment]
@shcherbakov-vadim 
Добрый день, прикрепите, пожалуйста, архив проекта.

**Comment by shcherbakov-vadim** [comment]
> @shcherbakov-vadim Добрый день, прикрепите, пожалуйста, архив проекта.

Добавил
