### ISSUE TITLE
Зависание EDT при поиске в макете табличного документа

### ISSUE THREAD

**Issue by shcherbakov-vadim** [1C-Company/1c-edt-issues#67]
## Опишите ошибку

При выполнении поиска в табличном документе EDT зависает полностью

## Как воспроизвести

1. Создать общий макет табличного документа
2. В ячейке R22C7 ввести Валюта
3. В ячейке R41C19 ввести что нибудь и удалить (это необходимо для изменения размеров табличного документа)
4. Находясь в ячейке R2C1 вызвать окно поиска по Ctrl+F, ввести Валюта в поле Искать и нажать Enter

## Окружение:

- OS: Windows 11
- Версия 1C:EDT 2021.2.8

**Comment by vadimeg** [comment]
Проблему воспроизвел

**Comment by vadimeg** [comment]
Зависание вызвано некорректной реализацией поиска в мокселе. Не дэдлок, просто зацикливание процедуры поиска, которая работает в основном потоке, что приводит к зависанию EDT.
