### ISSUE TITLE
2022.1.2 Глобальный поиск в конфигурации выдает несуществующие результаты

### ISSUE THREAD

**Issue by tormozit** [1C-Company/1c-edt-issues#672]
### Описание ошибки

Проблема встречалась и в 2021.3.4 https://github.com/1C-Company/1c-edt-issues/issues/599 . Там заявитель видимо ошибочно решил, что ее исправили, т.к. она самоустранилась.
Глобальный поиск в конфигурации выдает несуществующие результаты. У меня в модуле формы, который всегда был пустым, нашлась строка.

### Как воспроизвести

Не знаю

### Скриншоты

![изображение](https://user-images.githubusercontent.com/11896251/191908260-8ed7ab22-91fb-44dc-b434-95d0f295ad2e.png)

### Ожидаемое поведение

я

### Лог рабочей области

я

### Версия 1С:EDT

Ruby 2022.1.2

### Операционная система

Windows

**Comment by tretyakevich** [comment]
Подсистема полнотекстового поиска была полностью переработана в 2022.2. Анализ изменений для реиндексации переведен на события ресурсной подсистемы, что значительно уменьшает вероятность появления неактуальных данных (допускается временная неактуальность до момента завершения процесса реиндексации после внесения изменения)

**Comment by tormozit** [comment]
После перехода на 2022.2 действительно не замечал таких проблем. Но пользовался функцией редко.
