### ISSUE TITLE
EDT не понимает добавленный в табличную часть реквизит формы

### ISSUE THREAD

**Issue by grumagargler** [1C-Company/1c-edt-issues#683]
### Описание ошибки

Ошибка в том, что если в конфигураторе добавить реквизит в состав колонок табличной части формы, edt такой реквизит не видит и диагностирует ошибку.

### Как воспроизвести

Импортировать в edt приложенную базу, открыть форму единственного там вида расчёта и убедиться, что реквизита Picture в составе колонок лидирующих видов расчета нет.
[1Cv8.dt.zip](https://github.com/1C-Company/1c-edt-issues/files/9666335/1Cv8.dt.zip)

### Скриншоты

Сверху edt, снизу конфигуратор. В edt реквизита Picture нет.

![image](https://user-images.githubusercontent.com/15623029/192811250-fbadbb91-cbc2-4c8e-a414-bacb9b52fd98.png)

### Ожидаемое поведение

Реквизит Picture в составе колонок лидирующих видов расчета должен быть.

### Лог рабочей области

[Untitled.log](https://github.com/1C-Company/1c-edt-issues/files/9666326/Untitled.log)

### Версия 1С:EDT

Ruby 2022.1.2

### Операционная система

Linux

### Установленные плагины

Нет плагинов

### Дополнительная информация

8.3.20.1789, без режима совместимости.

**Comment by vadimeg** [comment]
Исправлено в 2023.1
