### ISSUE TITLE
Не подавляется проверка scheduled-job-periodicity-too-short

### ISSUE THREAD

**Issue by sovaenga** [1C-Company/1c-edt-issues#694]
### Описание ошибки

Не получается подавить проверку для одного конкретного рег. задания scheduled-job-periodicity-too-short
![image](https://user-images.githubusercontent.com/96619785/193309722-17a23e68-2129-49e7-a813-453e1caf6a0c.png)
После команды "Подавить ошибку" строчка исчезает, но при повторном открытии ошибка на месте

### Как воспроизвести

1. Создайте рег. задание с расписанием чаще, чем раз в минуту
2. Попробуйте подавить ошибку
3. Повторно откройте ошибки
Наблюдайте, что она не подавилось

### Ожидаемое поведение

Ошибка на этом рег. задании не должна снова отображаться

### Лог рабочей области

[лог.log](https://github.com/1C-Company/1c-edt-issues/files/9686031/default.log)

### Версия 1С:EDT

Ruby 2022.1.2

### Операционная система

Windows

**Comment by vadimeg** [comment]
Исправлено в 2023.1
