### ISSUE TITLE
Ложное срабатывание проверки "Метод Заблокировать() вне блока Попытка-Исключение"

### ISSUE THREAD

**Issue by unichkin** [1C-Company/1c-edt-issues#700]
### Описание ошибки

Проверка распознает транзакцию только в том случае, если вызов блокирования находится непосредственно в обработке проведения. Здесь нужен анализ стека..
Создал простенькую конфу (прикрепил проект ниже), проводим документ "Продажа".

Блокировка объявлена внутри проведения - нет ошибки:
![image](https://user-images.githubusercontent.com/10799597/193887819-3f1456ec-324d-473b-9fbf-6128ff3670dd.png)

Блокировка вынесена в метод, есть ложное срабатывание:
![image](https://user-images.githubusercontent.com/10799597/193888052-853bdb2f-ca64-46bd-9ed1-822717290db4.png)

### Как воспроизвести

1. Перейдите в модуль объекта документа "Продажа"
2. Увидите ошибку как на скринште

### Ожидаемое поведение

Надо анализировать стек, и не выдавать ошибку в том случае если не-экспортный метод использующий установку блокировки вызывается только из события проведения.

### Лог рабочей области

[Тест.zip](https://github.com/1C-Company/1c-edt-issues/files/9709375/default.zip)

- здесь полностью проект

### Версия 1С:EDT

Ruby 2021.3.4

### Операционная система

Windows

### Установленные плагины

1C:Code style V8, 1C:SSL-support, Другие сторонние плагины `Название плагина...`

**Comment by RedMammoth** [comment]
Дубль https://github.com/1C-Company/v8-code-style/issues/1158 ?

**Comment by unichkin** [comment]
Предлагаю считать дополнением. Здесь есть прозрачное воспроизведение, и более четкая на мой взгляд формулировка ожидаемого поведения. Только прочие события я не подумал проверить на этот момент, но там ожидаемо будет то-же самое.

**Comment by unichkin** [comment]
К слову - стоит ли дополнять проверку анализом экспортных методов такого рода - мне кажется нет. Это слишком глубокая проверка, которая нецелесообразно будет подвешивать систему через проход по стекам вызовов.. В случае наличия подобных экспортных методов я бы предложил оставить срабатывание, и выключать его при нужде. Возможно неправ, не понимаю текущих возможностей проверки, и не могу свободно об этом рассуждать.

**Comment by marmyshev** [comment]
Дубль
