### ISSUE TITLE
Отсутствует cтандартная команда "Установить период" у формы списка регистра бухгалтерии 

### ISSUE THREAD

**Issue by mazzz-igor** [1C-Company/1c-edt-issues#704]
### Описание ошибки

В форму списка регистра бухгалтерии невозможно для кнопки установить стандартаную команду "Установить период". 
Также в настройке стандартных команд формы списка отстуствует команда "Установить период". 

### Как воспроизвести

1. Перейдите в форму списка регистра бухгалтерии
2. Добавить кнопку
3. В свойствах кнопки нажать "Команда"
4. В открывшемся окне перейти в стандартны команды списка
5. Необходимая команда "Установить период" отсутствует.

### Скриншоты

![image](https://user-images.githubusercontent.com/53305585/194053017-4013f545-0c10-43bf-8537-edd7e8e3e049.png)

### Ожидаемое поведение

1. Перейдите в форму списка регистра бухгалтерии
2. Добавить кнопку
3. В свойствах кнопки нажать "Команда"
4. В открывшемся окне перейти в стандартны команды списка
5. Выбрать команду "Установить период"

### Лог рабочей области

[.log](https://github.com/1C-Company/1c-edt-issues/files/9715251/default.log)
[trace.log](https://github.com/1C-Company/1c-edt-issues/files/9715252/trace.log)

### Версия 1С:EDT

Ruby 2022.1.2

### Операционная система

Windows

### Дополнительная информация

Конфигурация на английском
Используемая версия платформы 8.3.21.1393

**Comment by vadimeg** [comment]
Исправлено в 2022.2

![image](https://user-images.githubusercontent.com/17178862/212042894-d206be3b-b87a-44b8-9b9e-f0e417db7a6b.png)
