### ISSUE TITLE
[1CEDT] Ложное срабатываение module-structure-init-code-in-region

### ISSUE THREAD

**Issue by unichkin** [1C-Company/1c-edt-issues#705]
```
В БСП-шном справочнике "ИдентификаторыОбъектовМетаданных"
Product name: 1C:Enterprise Development Tools
Product version: 1.26.2.30
Java home: C:\Program Files\BellSoft\LibericaJDK-11-Full
Java vm name: OpenJDK 64-Bit Server VM
Java vm info: mixed mode
Java version: 11.0.12
Java vendor: BellSoft
OS: win32
Total mem: 2 718
Free mem: 278
Cores: 8
```
![image](https://user-images.githubusercontent.com/10799597/194202382-0e492fc3-d9ca-471d-986f-5a3570863bf6.png)

**Comment by unichkin** [comment]
Сообщение создано после перехода на EDT Ruby 2022.1.2, через кнопку "Сообщить о проблеме".
Флаг того что надо приложить скриншот в окне стоял, скриншот не приложен.
Проблема не оформлена как баг.

**Comment by unichkin** [comment]
Задача создана из EDT, ошибку о некорректном автоматическом оформление создал https://github.com/1C-Company/1c-edt-issues/issues/706

**Comment by unichkin** [comment]
По самой ошибке - технически да, это верная проверка. Но есть плагин SSL-Support, наверное его надо научить это опознавать.

**Comment by RedMammoth** [comment]
По-моему уже исправлена https://github.com/1C-Company/v8-code-style/issues/1155

**Comment by unichkin** [comment]
Обнаружено на новой EDT:
1C:Enterprise Development Tools
Ruby 2022.1.2

OS: Windows 10, v.10.0, x86_64 / win32
Java vendor: BellSoft
Java runtime version: 11.0.12+7-LTS
Java version: 11.0.12

Эта задача создана из окна "Сообщить о проблеме", поэтому не оформлена должным образом..
