### ISSUE TITLE
Некорректная работа окна "Сообщить о проблеме"

### ISSUE THREAD

**Issue by unichkin** [1C-Company/1c-edt-issues#706]
### Описание ошибки

Заметил в EDT Ruby 2022.1.2 новую кнопку "Сообщить о проблеме". Создал с ее помощью задачу https://github.com/1C-Company/v8-code-style/issues/1165

Флаг того что надо приложить скриншот в окне стоял, скриншот не приложен.
Проблема не оформлена как баг, также ожидал что лог рабочей области автоматически загрузится.

### Как воспроизвести

Сообщить о проблеме из EDT c включенным флагом скриншота

### Ожидаемое поведение

При сообщении о *проблеме* ожидаешь что задача должна быть оформлена как баг.  Но лучше бы в том окне давать выбирать тип issue, также как это происходит здесь при создании задачи, также автоматически прикладывать лог рабочей области - или галку такую в это окно добавить.

### Лог рабочей области

[metadata.zip](https://github.com/1C-Company/1c-edt-issues/files/9720741/metadata.zip)

### Версия 1С:EDT

2022.1.2

### Операционная система

Windows

### Установленные плагины

1C:Code style V8, 1C:SSL-support, 1C:Language Tool

**Comment by sanaroff** [comment]
Приложенная информация, а именно лог рабочей области, трейс, скриншот и файлы, которые вы прикрепили, отправляется к нам напрямую. Прикрепление к задаче не происходит из-за ограничения официального api github. Информирование об этом добавлено на этапе создания задачи.
