### ISSUE TITLE
Зацикливание в форме плана счетов

### ISSUE THREAD

**Issue by RedMammoth** [1C-Company/1c-edt-issues#711]
### Описание ошибки

При работе с иерархическим планом счетов происходит циклическая смена/установки текущей строки, что не позволяет с ним работать. Подробнее в сообщениях из чата:
https://t.me/e1c_edt/56467
https://t.me/e1c_edt/45393

### Как воспроизвести

Воспроизведение в сообщениях, упомянутых выше

### Ожидаемое поведение

Форма не зацикливается

### Лог рабочей области

-

### Версия 1С:EDT

2022.1.2, 2021.3.4

### Операционная система

Windows, Linux

### Установленные плагины

1C:Code style V8, 1C:SSL-support

**Comment by vadimeg** [comment]
Исправлено в 2022.2. Выход релиза скоро ожидается
