### ISSUE TITLE
Некорректно работает отбор по ошибкам конфигурации

### ISSUE THREAD

**Issue by unichkin** [1C-Company/1c-edt-issues#715]
### Описание ошибки

Открываю панель "Ошибки конфигурации", ставлю отбор по подсистеме. В списке ошибок почему-то светятся внешние проекты...

![image](https://user-images.githubusercontent.com/10799597/194330504-f5a5e2ac-edb8-46ac-a6be-e5579a729938.png)

### Как воспроизвести

Воспроизведение в описании

### Ожидаемое поведение

При таком отборе должны оставаться только объекты выбранных подсистем, внешних проектов быть не должно.

### Лог рабочей области

[metadata.zip](https://github.com/1C-Company/1c-edt-issues/files/9725366/metadata.zip)

### Версия 1С:EDT

Ruby 2022.1.2

### Операционная система

Windows

### Установленные плагины

1C:Code style V8, 1C:SSL-support, Другие сторонние плагины `Название плагина...`

### Дополнительная информация

Стоит плагин BSL http://capralow.ru/edt/bslls.validator/latest/

**Comment by tretyakevich** [comment]
Не воспроизводится в текущей версии 2022.2
