### ISSUE TITLE
Некорректная работа проверки doc-comment-field-type

### ISSUE THREAD

**Issue by unichkin** [1C-Company/1c-edt-issues#717]
### Описание ошибки

Есть корректное описание параметра, EDT ругается:
![image](https://user-images.githubusercontent.com/10799597/194420918-3e7eb7d2-74fa-4327-90bd-beffce005ccc.png)

При этом сообщение пропадает, если в конце описания поставить тире..
![image](https://user-images.githubusercontent.com/10799597/194421026-32cbb1bd-7b5a-4900-b51a-ae6fea00f54e.png)

Поведение очень похоже на ранее регистрированную ошибку #356

### Как воспроизвести

Воспроизведение описано

### Ожидаемое поведение

Парсер должен нормально распознавать конструкции с несколькими типами, и не требовать ставить в конце доп. знаков. В данном случае параметр сам себя документирует, и описания не требует.

### Лог рабочей области

-

### Версия 1С:EDT

Ruby 2022.1.2

### Операционная система

Windows

### Установленные плагины

1C:Code style V8, 1C:SSL-support

**Comment by marmyshev** [comment]
Ошибку закрываю. Так как к проверке это не имеет отношения - проверка проверяет модель данных, а в примере она написано то что не попадает в модель данных как тип. Предложение на переделку есть.

Откройте панель "документирующий комментарий" - он покажет структуру данных.
