### ISSUE TITLE
Ошибка синхронизации ИБ при редактировании во время запуска приложения

### ISSUE THREAD

**Issue by shcherbakov-vadim** [1C-Company/1c-edt-issues#72]
### Описание ошибки

Если в процессе запуска или отладки достаточно большой конфигурации внести изменения в текст модуля, рабочая область окажется в некорректном состоянии - приложение будет запускаться без обновления ИБ, при этом приложения не будет содержать последнюю версию модуля.

### Как воспроизвести

1. Импортировать проект из файловой ИБ содержащую конфигурацию ЕРП-УХ
2. Создать новую обработку в которую добавить обработчик единственного события
```bsl
&НаКлиенте
Процедура ПриОткрытии(Отказ)
	Сообщить(1);
КонецПроцедуры
```
3. Запустить приложение с обновлением ИБ
4. Заменить 1 на 2 в тексте модуля
5. Запустить приложение с обновлением ИБ и продолжать редактировать модуль, увеличивая число на 1 каждые несколько секунд
6. После запуска приложения сравнить вывод сообщения в приложении со значением в модуле, при этом повторный запуск приложения не увидит никаких изменений и будет запускаться без обновления ИБ

### Скриншоты

![2021-11-08_23-09-35](https://user-images.githubusercontent.com/52153345/140810902-a1326f1a-1138-471a-8217-3c0fea4c9364.png)

### Ожидаемое поведение

При очередном запуске приложения система должна обнаружить изменение и обновить ИБ

### Лог рабочей области

!ENTRY com._1c.g5.v8.dt.platform.services.core 1 0 2021-11-08 22:54:11.383
!MESSAGE Updating connections up to associations...

!ENTRY com._1c.g5.v8.dt.platform.services.core 1 0 2021-11-08 22:55:12.010
!MESSAGE ConfigDumpInfo.xml is stored for "erp-uh"

### Версия 1С:EDT

2021.2.8

### Операционаня система

Windows

**Comment by NikitaMikhaylovSB** [comment]
Известная ошибка ((((
Сколько уже починить обещают.

**Comment by DmitryShvaika** [comment]
надо ставить палец вверх... чтобы быстрее исправили

**Comment by MaksimDzyuba** [comment]
Здравствуйте, правили в 2021.3, просьба отписаться, все ли корректно работает, как перейдете на 2021.3

**Comment by shcherbakov-vadim** [comment]
> Здравствуйте, правили в 2021.3, просьба отписаться, все ли корректно работает, как перейдете на 2021.3

Имея опыт с задачей #142 вынужден спросить, на какой версии проекта проверять? Я работал на версии 2021.3 больше месяца на проекте версии 8.3.18 и проблема была.

**Comment by MaksimDzyuba** [comment]
> 

Здравствуйте, по поводу #142 мы ее к сожалению еще не чинили, там реально есть проблема, мы ее воспроизвели. По поводу же данной ошибки, версия платформы, на которой идет разработка, тут не причем, мне не удалось повторить описанное поведение ни на платформе 8.318, ни на платформе 8.3.20

**Comment by marmyshev** [comment]
Ошибка исправлена в 2023.1 - объекты, модифицированные во время синхронизация с ИБ (после запуска, но до завершения) - будут отправляться в ИБ повторно.

Так же, исправлена ошибка если во время синхронизации срубить процесс ЕДТ - все данные будут сохранены и оправлены повторно.
