### ISSUE TITLE
Зависает на "Проверка xText"

### ISSUE THREAD

**Issue by unichkin** [1C-Company/1c-edt-issues#720]
### Описание ошибки

В одной из прошлых версий EDT была такая же проблема - начинаешь редактировать модуль, он зависает. В момент рассмотрения той задачи выяснилось что виной тому использование сторонних плагинов, у меня установлен вот этот 
http://capralow.ru/edt/bslls.validator/latest/
Окно EDT недоступно, не реагирует на попытки изменить размер, в правом нижнем углу:
![image](https://user-images.githubusercontent.com/10799597/194746466-d6947766-b28f-4543-820a-2b41c176e7fd.png)

### Как воспроизвести

Я редактировал модуль формы внешней обработки, зависание внезапное, триггеры выявить не могу.

### Ожидаемое поведение

Зависать не должно

### Лог рабочей области

Лог рабочей области: [metadata.zip](https://github.com/1C-Company/1c-edt-issues/files/9741088/metadata.zip)
Дамп потоков: [threaddump.txt](https://github.com/1C-Company/1c-edt-issues/files/9741098/threaddump.txt)
Дамп памяти (архив 227mb, исходный файл весит 2,3 гб): https://drive.google.com/file/d/1zxCtoZlL-9AltPNy-SB8d42ml0rQR7MC/view?usp=sharing

### Версия 1С:EDT

Ruby 2022.1.2

### Операционная система

Windows

### Установленные плагины

1C:Code style V8, 1C:SSL-support, Другие сторонние плагины `Название плагина...`

### Дополнительная информация

Установлены плагины:
http://capralow.ru/edt/bslls.validator/latest/
https://marmyshev.gitlab.io/edt-editing/update

**Comment by MaksimDzyuba** [comment]
@unichkin здравствуйте, а если зависания воспроизводятся еще раз, то не могли бы Вы снять несколько дампов подряд, скажем с интервалом в 30 секунд

**Comment by unichkin** [comment]
Добрый день, уже нет такой возможности - пришлось откатиться с версии 2021.1.2, работать с ней оказалось слишком проблематично.

**Comment by MaksimDzyuba** [comment]
из-за этой ошибки?

**Comment by unichkin** [comment]
В том числе. Также были непобедимые проблемы при слиянии у нескольких программистов, и в целом по мнению команды стало сильнее тормозить, приняли решение откатываться.

**Comment by MaksimDzyuba** [comment]
будет исправлено в ближайшем выпуске 2022.1
