### ISSUE TITLE
Возможность добавить объект в подсистему поставщика

### ISSUE THREAD

**Issue by REset49** [1C-Company/1c-edt-issues#721]
### Описание ошибки

Если добавить новый объект, то есть возможность включить его в подсистему поставщика, которая "Не редактируется" и записать изменения.
Дальнейшая работа с этим объектом будет заблокирована. 

### Как воспроизвести

на примере БСП
1. Добавить в свою конфигурацию подсистемы БСП. Объекты БСП "не редактируются"
2. Создать новый справочник, перейти на вкладку подсистемы, выбрать одну из подсистем БСП (на замке)
3. Нажать сохранить (через файл-сохранить, или "дискету")
4. Дальнейшая работа с этим объектом (переименование, удаление и т.д.) будет невозможна (что логично), ругается 
"Редактирование объекта [имя подсистемы] запрещено."

### Скриншоты

![image](https://user-images.githubusercontent.com/92163852/194748093-45d61057-1b6e-45a8-af3d-58a293f239c8.png)
![image](https://user-images.githubusercontent.com/92163852/194748177-898e5538-3054-4f78-8c7e-c518f84cc5aa.png)

### Ожидаемое поведение

Запретить выбирать подсистемы "на замке", или сохранять объект с подсистемами "на замке".

### Лог рабочей области

Не требуется

### Версия 1С:EDT

Ruby 2022.1.2

### Операционная система

Windows

### Дополнительная информация

Версия платформы 8.3.21.1393

**Comment by wolfandw** [comment]
Исправлено в 2022.2
