### ISSUE TITLE
Ошибка запуска процесса сервера отладки

### ISSUE THREAD

**Issue by unichkin** [1C-Company/1c-edt-issues#722]
### Описание ошибки

Одновременно работают две версии EDT, из двух разных спейсов, две разные базы.
При этом если запускать 1С то из одной, то из другой получаю ошибку:
![image](https://user-images.githubusercontent.com/10799597/194749046-4d085ad8-a97a-4bdc-831d-e5b066a04799.png)

В настройках отладки все стоит по-умолчанию, никаких портов самостоятельно не прописывал. На ранней версии EDT 2021.1 это работало.

### Как воспроизвести

Создать два спейса, запустить две EDT, подключить две разные базы. Модифицировать и запускать - то одну, то другую, возможно выстрелит. У меня так это произошло.

### Ожидаемое поведение

Должно работать как раньше, очень желательно без необходимости доп. настроек.

### Лог рабочей области

[metadata.zip](https://github.com/1C-Company/1c-edt-issues/files/9741208/metadata.zip)

### Версия 1С:EDT

Ruby 2022.1.2

### Операционная система

Windows

### Установленные плагины

1C:Code style V8, 1C:SSL-support, Другие сторонние плагины `Название плагина...`

### Дополнительная информация

Установлены плагины:
https://marmyshev.gitlab.io/edt-editing/update

**Comment by RedMammoth** [comment]
Дубль https://github.com/1C-Company/1c-edt-issues/issues/546 ?

**Comment by unichkin** [comment]
Да, закрыл
