### ISSUE TITLE
При отладке показывать всплывающие подсказки со значениями переменных вместо ошибок валидации кода 

### ISSUE THREAD

**Issue by adminimusRU** [1C-Company/1c-edt-issues#732]
### Описание проблемы

При отладке иногда бывает удобно смотреть значения переменной во всплывающем окне при наведении указателя, особенно если локальных переменных очень много. К сожалению сейчас в перспективе отладка в редакторе кода так же отображаются и ошибки/предупреждения, и именно они сейчас отображаются вместо значений переменных:
![image](https://user-images.githubusercontent.com/28653631/195529702-0de1ad6a-902d-42c5-8b15-ce127bd29377.png)

Отключение отображения маркеров предупреждений в настройках редактора ситуацию не меняет:
![image](https://user-images.githubusercontent.com/28653631/195529933-4206c4b8-e205-4bd1-a766-6a935c61cb91.png)

### Описание решения проблемы

Сделать всплывающим окнам со значениями переменных более высокий приоритет, чем подсказкам об ошибках. Или показывать разные окна в зависимости от зажатых клавиш-модификаторов (shift например).
В идеале еще реализовать опциональное скрытие пометок валидации кода в перспективе отладка. Кажется сейчас такой возможности нет, настройки глобальные.

**Comment by DmitryBelov-e1c** [comment]
Пожелание уже было реализовано в рамках внутренней разработки.
