### ISSUE TITLE
При отладке в панелях Переменные и Выражения показывать количество элементов в коллекциях

### ISSUE THREAD

**Issue by adminimusRU** [1C-Company/1c-edt-issues#733]
### Описание проблемы

По умолчанию все коллекции (массивы, таблицы, деревья, структуры, списки и т.п.) отображаются в свернутом виде. Сейчас чтобы увидеть содержимое коллекции в этих панелях приходится их разворачивать, иногда на несколько уровней (узел Элементы) и прокручивать до конца в случае больших коллекций:
![image](https://user-images.githubusercontent.com/28653631/195533562-0d2e8c5f-0250-4d2b-aa2d-9a59e92d571f.png)

Часто при отладке бывают ситуации, когда для диагностики проблемы достаточно только определить, пустая ли коллекция (например это выгруженная из результата запроса таблица). Или примерно оценить порядок размера коллекции: например ожидали выбрать запросом 100 записей, выбралось 10000 - возможно допущена всего ошибка в условиях соединений. При этом конкретные значения элементов коллекции бывают уже не важны.

### Описание решения проблемы

Добавить отображение количества элементов в коллекциях на первом уровне. Например так:
![image](https://user-images.githubusercontent.com/28653631/195532859-ecc12d2d-5231-4adc-8fa6-0087ef017688.png)

**Comment by tormozit** [comment]
Почему только для коллекции "Элементы"? Я бы хотел видеть количество для всех коллекций, т.е. и для "Колонки" и "Индексы".
По оформлению меня устраивает.

**Comment by adminimusRU** [comment]
> Предлагаемая реализация - на скриншоте.

Замечательно. Но есть один недостаток - всё равно придется разворачивать первый уровень коллекции, чтобы добраться до элементов. Когда в панели таких коллекций больше десятка, лишние действия начнут утомлять.

**Comment by DmitryBelov-e1c** [comment]
> > Предлагаемая реализация - на скриншоте.
> 
> Замечательно. Но есть один недостаток - всё равно придется разворачивать первый уровень коллекции, чтобы добраться до элементов. Когда в панели таких коллекций больше десятка, лишние действия начнут утомлять.

Предложение разумно, внешний вид возможной реализации ниже.

> Почему только для коллекции "Элементы"? Я бы хотел видеть количество для всех коллекций, т.е. и для "Колонки" и "Индексы". По оформлению меня устраивает.

Существуют некоторые ограничения API Платформы, в результате которых не всегда возможно узнать размер без получения полного состояния объекта. Для ТаблицыЗначений отображается именно размер списка элементов коллекции.
![изображение](https://user-images.githubusercontent.com/109139509/233186975-8619bbe8-0a6d-498e-a61c-cfe546f84b26.png)

Хочется обратить внимание на ещё один момент при работе с размерами коллекций - API Платформы поддерживает данный функционал только с версии 21 включительно.

**Comment by tormozit** [comment]
Теперь у "Табл.Элементы" пропал индикатор количества

**Comment by DmitryBelov-e1c** [comment]
> Теперь у "Табл.Элементы" пропал индикатор количества

Я правил комментарий в процессе, чтобы разъяснить; размер в заголовке ТаблицыЗначений = размеру коллекции элементов.

**Comment by tormozit** [comment]
Понял. Тогда вроде все отлично.

**Comment by tormozit** [comment]
@DmitryBelov-e1c 
> не всегда возможно узнать размер без получения полного состояния объекта

Тут желательно подробнее описать. Если для того, чтобы видеть количество элементов форма будет запрашивать от сервера отладки всю тз на 500000 строк и 20 колонок, то это будет очень плохо.

**Comment by DmitryBelov-e1c** [comment]
@tormozit 

>Тут желательно подробнее описать. Если для того, чтобы показать количество элементов форма будет сразу запрашивать от сервера отладки все 500000 строк и 20 колонок, то это будет очень плохо.

Именно поэтому реализации для старых Платформ не будет. В текущей версии будет показан ? вместо размера объекта, если где-то будет невозможно рассчитать без раскрытия коллекции.

**Comment by tormozit** [comment]
Ну я надеюсь при наличии у коллекции метода "Количество()", зовется именно он. А вот если его нет, то тогда уже получается полностью коллекция для подсчета ее элементов путем обхода. Так?

**Comment by tormozit** [comment]
Ждать эту доработку в версии EDT 2023?

**Comment by DmitryBelov-e1c** [comment]
@tormozit 
Нечто среднее между двумя тезисами по факту; не уполномочен настолько углубляться в технические детали, если можно. Поскольку мы сейчас пытаемся улучшить производительности отладки, всегда рассматриваем много сценариев, чтобы ненароком не навредить.

Да - скорее всего туда попадёт.

**Comment by tretyakevich** [comment]
Исправлено в 2023.1.2
