### ISSUE TITLE
Зависание при переходе в список точек останова

### ISSUE THREAD

**Issue by GitHub-ViGo** [1C-Company/1c-edt-issues#735]
### Описание ошибки

Ошибка в том, что при переходе в окно со списком точек останова EDT зависает:
![image](https://user-images.githubusercontent.com/112264187/195561608-215b4de5-5743-46c7-b9ff-4f456b64c803.png)

### Как воспроизвести

1. Перейдите в окно списка точек останова

### Скриншоты

![image](https://user-images.githubusercontent.com/112264187/195561733-57fa3194-bb83-4d31-b954-918651608b5b.png)

### Ожидаемое поведение

EDT не зависает)))

### Лог рабочей области

[threaddump.txt](https://github.com/1C-Company/1c-edt-issues/files/9775186/threaddump.txt)

### Версия 1С:EDT

Ruby 2022.1.2

### Операционная система

Windows

### Установленные плагины

1C:Code style V8, 1C:Language Tool

**Comment by DmitryBelov-e1c** [comment]
Добрый день @GitHub-ViGo , помогите, пожалуйста, с воспроизведением проблемы - не наблюдается. Предоставьте, пожалуйста, следующие данные:
1) Обновлялась ли EDT из Starter-a - с более ранней 2022.1 на обновлённую.
2) Зависает ли только во время отладки или при переходе в данный View в обычном состоянии тоже.
3) Происходит ли зависание если нет точек останова (можно удалить в коде) - при запущенной отладке и без.
3а) Существует ли код, в котором были установлены точки (это состояние иногда вызывает проблемы).
4) Зависает ли если рядом создать другой проект и поставить точки останова в нём.
5) Будет ли зависать при переходе в новую рабочую область.

**Comment by GitHub-ViGo** [comment]
Добрый день
1. Да, обновлял
2. Зависает при переходе в данный View в обычном состоянии тоже
3. Вчера пару раз зависло при простом редактировании кода, но мне казалось что эти вещи не связаны. Есть дамп с того зависания тоже, прикладываю:
[threaddump_1.txt](https://github.com/1C-Company/1c-edt-issues/files/9784450/threaddump_1.txt)
4. Не пробовал, сделаю - отпишусь
5. Тоже не пробовал, не было необходимости

**Comment by DmitryBelov-e1c** [comment]
@GitHub-ViGo ,
3. Да - во втором случае очень похоже, что просто не дождались конца проверки языковых средств; она длительная - понимаю :) Пожалуйста, уточните по наличию/отсутствию проблемы, если точки останова полностью удалить.

**Comment by DmitryBelov-e1c** [comment]
Сделаны исправления на основе имеющихся thread-dump-ов, появятся в 2022.2
