### ISSUE TITLE
Макркеры по проверка на объекты формы должны везде отображаться в редакторе формы

### ISSUE THREAD

**Issue by popoffvg** [1C-Company/1c-edt-issues#74]
## Описание проблемы

Описание проверки с кодом form-data-path не содержит места возникновения ошибки и не содержит способа устранения.

Т.е. из описания не ясно:
- Где поправить
- Как поправить

Пример:
```
Свойство "Сохраняемые данные" имеет некоректное значение "1/0:5562ee6c-aff6-4df9-a6e7-3f3bbd9e7014": 1 сегмент "1/0:5562ee6c-aff6-4df9-a6e7-3f3bbd9e7014" ссылается на неизвестный объект
```

**Comment by marmyshev** [comment]
Обсудили с @vadimeg - если маркер проверки нигде в редакторе не отображается - это ошибка. Такие ситуации надо все отлавливать и испрвалять.

**Comment by vadimeg** [comment]
> Обсудили с @vadimeg - если маркер проверки нигде в редакторе не отображается - это ошибка. Такие ситуации надо все отлавливать и испрвалять.

При условии, что проверка связана с отображаемыми на UI данными

**Comment by vadimeg** [comment]
Исправлено в 2023.3
