### ISSUE TITLE
Edt повис при сохранении общего модуля - белесый экран - приложение 10 мин не откликается

### ISSUE THREAD

**Issue by DmitryShvaika** [1C-Company/1c-edt-issues#744]
### Описание ошибки

Edt повис при сохранении общего модуля - белесый экран - приложение 10 мин не откликается
Памяти достаточно - куча отъела 3 Гб из 6 Гб отведенных

[threaddump.zip](https://github.com/1C-Company/1c-edt-issues/files/9851492/threaddump.zip)

### Как воспроизвести

1. первый раз такое за долгое время - воспроизвести не получится

### Ожидаемое поведение

Edt не должен зависать

### Лог рабочей области

стек вызовов приложен выше

### Версия 1С:EDT

2022.1.3

### Операционная система

Windows

**Comment by MaksimDzyuba** [comment]
Добрый день, подобный случай уже был исправлен, войдет в 2022.2

**Comment by MaksimDzyuba** [comment]
будет исправлено в ближайшем выпуске 2022.1
