### ISSUE TITLE
Оптимизация формата хранения приводит к невозможности загрузки конфигурации к БД

### ISSUE THREAD

**Issue by Daabramov** [1C-Company/1c-edt-issues#752]
### Описание ошибки

При выполнении оптимизации формата хранения исходников проекта выполняется замена префикса 0: на v8ui, что в дальнейшем не позволяет загрузить конфигурацию в базу данных.

### Как воспроизвести

1. В исходниках текущего проекта в макете отчете должны быть строки вида

```
<dcscor:item>
							<dcscor:parameter>Картинка</dcscor:parameter>
							<dcscor:value xsi:type="0:Picture" ref="0:042245ef-3a30-46fb-b3e3-6599d5426cbd"/>
</dcscor:item>
```

Такой пример есть в БСП в отчете ПраваРолей

2. Выполните оптимизацию формата исходников проект
3. Подтвердите, что ссылки вида 0:042245ef-3a30-46fb-b3e3-6599d5426cbd были изменены на **v8ui**:042245ef-3a30-46fb-b3e3-6599d5426cbd
4. Выполнить полную загрузку проекта в базу
5. Получить ошибку невозможности загрузки

### Скриншоты

![image](https://user-images.githubusercontent.com/31928832/199005185-6dd43548-c419-43f6-8a75-9a95954ee371.png)
![image](https://user-images.githubusercontent.com/31928832/199005198-b8981cdf-9384-4fef-a7fe-c5c7f4ecac27.png)

### Ожидаемое поведение

Отсутствие ошибки

### Лог рабочей области

[edt-logs-v8ui.log](https://github.com/1C-Company/1c-edt-issues/files/9901021/edt-logs-v8ui.log)

### Версия 1С:EDT

2022.1.3

### Операционная система

Windows

### Дополнительная информация

Версия платформы: 8.3.20.1996
Режим совместимости: 8.3.20

**Comment by beg7** [comment]
Тут проблема не в оптимизации формата хранения. А в сериализации СКД которая в принципе не умеет записывать картинки из битой ссылки в виде UUID.

**Comment by beg7** [comment]
Исправление будет в ближайшее время, но на данный момент рекомендую удалить либо заменить картинку на существующую в оформлении в СКД.

**Comment by Daabramov** [comment]
Это код из типовой БСП, тут тогда вопрос в импорте.
В конфигураторе эта картинка вроде как есть, а вот при импорте такая ссылка.
Проверю и отпишусь.

**Comment by beg7** [comment]
По поводу типа "0:Picture" такой тип не может корректно обрабатываться не Конфигуратором, не EDT. 
Ошибку нужно устранить в XML. Советую перейти на более свежую БСП. Там нет такой проблемы.
