### ISSUE TITLE
Нет возможности делать поля шаблоны в макетах СКД, они не сохраняются

### ISSUE THREAD

**Issue by mrshadow300373** [1C-Company/1c-edt-issues#765]
### Описание ошибки

Ошибка в том что... после записи макета схемы компоновки отчёта/обработки поля - макеты в шаблонах СКД теряются, а новые не сохраняются. Если были существующие (например СКД было загружено из XML) они тоже пропадают.

### Как воспроизвести

1. Создать пустой отчёт, создать основную схему компоновки данных
2. Загрузить СКД из приложенной схемы 
[ТестСхемы.zip](https://github.com/1C-Company/1c-edt-issues/files/9996711/default.zip)
3. Открыть макеты должно выглядеть так:
![1668326378161](https://user-images.githubusercontent.com/34220218/201512120-0683e280-4618-42bf-b954-7cf66f12413a.png)
4. Изменить что либо в макете, например, отредактировать поле
![1668326838613](https://user-images.githubusercontent.com/34220218/201512198-ae335480-c927-47be-86e1-ebea4d705219.png)
5. Сохранить СКД, закрыть, открыть заново, будет как на картинке
![1668326935674](https://user-images.githubusercontent.com/34220218/201512247-f2dddad6-65ab-4d0f-968c-12d3abb81682.png)
6. Если изменения связаны с реструктуризацией порядка в макете, например добавили новую группировку или удалили существующую (не удалось воспроизвести в этом примере) то могут слететь все шаблону, и те которые были с момента загрузки.

### Скриншоты
Первоначальное создание съемы которая в архиве:
![1668328320562](https://user-images.githubusercontent.com/34220218/201512985-9e0384d8-cb89-4089-8639-d9015e7dc975.png)
Сохраняем, не закрывая в EDT открываем в конфигураторе:
![1668325664659](https://user-images.githubusercontent.com/34220218/201513008-a7e14fd2-92c2-4615-a5b0-eb40f67591bc.png)
Копируем поля из EDT  to 1C
![1668326063418](https://user-images.githubusercontent.com/34220218/201513027-e3a467e7-ad3c-42e8-b17c-9d2cdd902bc6.png)
![1668326116077](https://user-images.githubusercontent.com/34220218/201513046-ee4a6bbf-8c12-44b8-9b84-4c53e0b4c38e.png)
Сохраняем схему в XML из конфигуратора
Переоткрываем в EDT:
![1668326179381](https://user-images.githubusercontent.com/34220218/201513074-36bcd4ae-7706-44b5-afb3-de4ba96ee417.png)

### Ожидаемое поведение

При любом изменении изменения не только записываются, но и не исчезают вовсе, как это происходит сейчас.

### Лог рабочей области

[logs.zip](https://github.com/1C-Company/1c-edt-issues/files/9996740/logs.zip)

### Версия 1С:EDT

2022.1.3

### Операционная система

Windows, Linux

### Дополнительная информация

Версия проекта 8.3.17

**Comment by wolfandw** [comment]
И правлено в 2022.2 RC1
