### ISSUE TITLE
Изменения в составе команд формы бизнес-процесса не переносятся в конфигурацию при обновлении

### ISSUE THREAD

**Issue by mihailmaksakov** [1C-Company/1c-edt-issues#767]
### Описание ошибки

Добрый день!

Обнаружена проблема, в следствие которой не удается скрыть стандартные команды в форме бизнес-процесса.

### Как воспроизвести

Если проверка выполняется на MDM, то:
1. Установить демо-базу;
2. Открыть демо-базу в режиме конфигуратора и снять с поддержки;
3. Создать новый проект EDT и импортировать конфигурацию из базы.

В EDT (для MDM пункты 1-8 можно пропустить, просто сразу после импорта обновить конфигурацию приложения, но обновить нужно обязательно в режиме **Загрузить конфигурацию полностью**):
1. Откройте проект содержащий прикладные бизнес-процессы с формами, импортированный из базы данных (Бизнес-процесс нсиЗаявкаНаИзменение в MDM);
4. Откройте форму объекта бизнес-процесса;
5. Откройте состав команд формы;
6. Прокрутите вниз до команды "Старт" (либо другую, не скрытую ранее, у меня воспроизводится на командах "Старт" и "Активировать");
7. Снимите флаг с команды "Старт" и нажмите "Ок"
8. Сохраните изменение формы Ctrl+S;
9. Обновите конфигурацию приложения.

В конфигураторе:
1. Откройте форму бизнес-процесса аналогичную п.2;
2. Откройте состав команд формы;
3. Прокрутите до команды, выбранной в п.4 выше;
4. Убедитесь, что флаг видимости команды не снят.

### Скриншоты

EDT:
![javaw_5SFFsGJqtd](https://user-images.githubusercontent.com/51732624/202657076-6a5abace-36df-4a1e-a5b8-0bc7a8bf1d8d.png)

![javaw_KLYeRQYwCw](https://user-images.githubusercontent.com/51732624/202657118-4aaee3a7-8193-403d-88c0-e5417ca9a541.png)

Конфигуратор после обновления:

![1cv8_UAAXOU6bjm](https://user-images.githubusercontent.com/51732624/202657215-d2ec0e9e-e14a-453c-995a-c8ae6c9e3f37.png)

### Ожидаемое поведение

Видимость команд в конфигурации должна соответствовать, настроенной в EDT.

### Лог рабочей области

[edt_MDM_2_0_5_4_20221118.log](https://github.com/1C-Company/1c-edt-issues/files/10039959/edt_MDM_2_0_5_4_20221118.log)

### Версия 1С:EDT

Ruby 2022.1.2

### Операционная система

Windows

### Установленные плагины

Нет плагинов

### Дополнительная информация

Воспроизводится на 1С:MDM 2.0.5.4 : https://releases.1c.ru/version_files?nick=MDM20&ver=2.0.5.4
Версия платформы 1С 8.3.21.1624 x64

**Comment by Dumsik** [comment]
Это ошибка платформы 8.3.21.1624. Я проверил на чистом конфигураторе. Создал пустую конфу в конфигураторе. Создал форму документа и в ней отключил несколько стандартных команд. Выгрузил конфигурацию в xml файлы и загрузил выгруженную в файлы конфу в новые файлы, в этой новой конфе команды снова включились кроме одной. Завтра хочу написать в 1С и отправить им пример.

**Comment by mihailmaksakov** [comment]
Спасибо! Это будет как-то отображаться в https://bugboard.v8.1c.ru/version/plt8gen/000032474 ?

**Comment by VinichenkoE** [comment]
> Это ошибка платформы 8.3.21.1624. Я проверил на чистом конфигураторе. Создал пустую конфу в конфигураторе. Создал форму документа и в ней отключил несколько стандартных команд. Выгрузил конфигурацию в xml файлы и загрузил выгруженную в файлы конфу в новую конфу, в этой новой конфе команды снова включились кроме одной. Завтра хочу написать в 1С и отправить им пример.

Приветствую! Столкнулся с аналогичной проблемой только с составом команд на форме документа. Так же не выгружаются отключенные команды. Проверил на платформе 8.3.23.1865, в пустой конфе при выгрузке\загрузке конфигурации в xml файлы проблема не воспроизводится. Следовательно проблема актуальна, есть какая либо инфа по исправлению?
