### ISSUE TITLE
Объект метаданных создался в конфигурации, заблокированной к редактированию правилами поддержки

### ISSUE THREAD

**Issue by bapho-bush** [1C-Company/1c-edt-issues#773]
### Описание ошибки

Проект - расширение и родительская конфигурация ЗУП. 
Путём непонятных манипуляций в основной конфигурации создался объект ВнешняяОбработка, который невозможно удалить из дерева метаданных.

### Как воспроизвести

![image](https://user-images.githubusercontent.com/30332279/203964619-011c8386-ae2b-4491-bd4c-16d15206d4a7.png)

### Скриншоты

![image](https://user-images.githubusercontent.com/30332279/203935875-5cc4ae90-6e8a-4ee4-a791-a1cd06d75994.png)

### Ожидаемое поведение

Когда конфигурация находится на поддержке без возможности изменения, не должно быть ни единого способа создать новый объект метаданных.

### Лог рабочей области

[trace.log](https://github.com/1C-Company/1c-edt-issues/files/10090081/trace.log)
[log.log](https://github.com/1C-Company/1c-edt-issues/files/10090082/log.log)

### Версия 1С:EDT

Ruby 2022.1.3.14

### Операционная система

Windows

### Установленные плагины

1C:Code style V8, 1C:SSL-support

**Comment by wolfandw** [comment]
Не воспроизводится. В визарде список таргет-конфигураций пуст, в коде присутствует проверка на возможность редактирования конфигурации.

**Comment by MaksimDzyuba** [comment]
Здравствуйте, воспроизвелось. поправил, должно войти в 2023.2. Спасибо!
