### ISSUE TITLE
После закрытия диалога редактирования свойства элемента формы фокус ошибочно устанавливается в поле "Сочетание клавиш"

### ISSUE THREAD

**Issue by adminimusRU** [1C-Company/1c-edt-issues#774]
### Описание ошибки

После закрытия диалога редактирования свойства элемента формы фокус устанавливается в поле "Сочетание клавиш". После этого при попытке применить любое сочетание клавиш EDT оно будет вместо этого назначено редактируемому элементу формы. Это приводит к нежелательным изменениям в коде проекта.
Самое частое - при попытке сохранить измененную форму хоткеем Ctrl+S вместо этого назначается хоткей на поле формы.

### Как воспроизвести

1. Открыть редактор формы, выбрать поле ввода
2. В панели Свойства открыть через "..." любой диалог, например у свойства "Список выбора" или "Связи параметров выбора"
3. Закрыть диалог редактирования свойства
4. Попытаться сохранить форму хоткеем Ctrl+S
5. Форма не сохраняется, вместо этого хоткей назначается полю ввода

### Ожидаемое поведение

После закрытия диалога редактирования свойства фокус не переводится в поле "Сочетание клавиш". При редактировании свойств через выпадающие списки поведение корректное.

### Лог рабочей области

не требуется

### Версия 1С:EDT

2022.1.2

### Операционная система

Windows

**Comment by vadimeg** [comment]
Исправлено в 2023.1
