### ISSUE TITLE
Edt не понимает описание колонок для ДанныеФормыКоллекция если строка коллекции получается в цикле по идентификатору.

### ISSUE THREAD

**Issue by DmitryShvaika** [1C-Company/1c-edt-issues#775]
### Описание ошибки

Edt не понимает описание колонок для ДанныеФормыКоллекция если строка коллекции получается в цикле по идентификатору. В данном случае не понимает описание колонки Пометка. Примечательно, что если раскомментировать строки команды, то тип определится. После повторного комментирования тип останется определенным, однако если в последней строке модуля поставить например 1 сохранить потом удалить 1 и снова сохранить, тип опять станет неопределенным. Но это другая ошибка - напишу отдельной задачей с видео. https://github.com/1C-Company/1c-edt-issues/issues/776

![image](https://user-images.githubusercontent.com/54451084/204545546-b2204a14-1600-4721-bfc4-32cf62d5d2da.png)

### Как воспроизвести

1. Загрузите внешнюю обработку в проект внешних обработок

[test.zip](https://github.com/1C-Company/1c-edt-issues/files/10113552/test.zip)

2. Наблюдайте ошибку

### Ожидаемое поведение

Типы колонок ДанныеФормаКоллекции должны определяться

### Лог рабочей области

не требуется

### Версия 1С:EDT

2022.1.4

### Операционная система

Windows

**Comment by RedMammoth** [comment]
> Примечательно, что если раскомментировать строки команды, то тип определится
Потому что есть два способа выведения типа, на описании и автоматическое. Если раскомментировать строки, то сработает автоматическое. ЕДТ увидит, какая именно таблица форму ушла в процедуру

**Comment by DmitryShvaika** [comment]
> > Примечательно, что если раскомментировать строки команды, то тип определится
> 
> Потому что есть два способа выведения типа, на описании и автоматическое. Если раскомментировать строки, то сработает автоматическое. ЕДТ увидит, какая именно таблица форму ушла в процедуру

А для ДанныеФормаКоллекция нельзя описать колонки в документирующем комментарии? Edt не будет их понимать? Ведь до раскомментрирования есть комментарий и в нем все указано...

**Comment by RedMammoth** [comment]
> > > Примечательно, что если раскомментировать строки команды, то тип определится
> > 
> > 
> > Потому что есть два способа выведения типа, на описании и автоматическое. Если раскомментировать строки, то сработает автоматическое. ЕДТ увидит, какая именно таблица форму ушла в процедуру
> 
> А для ДанныеФормаКоллекция нельзя описать колонки в документирующем комментарии? Edt не будет их понимать? Ведь до раскомментрирования есть комментарий и в нем все указано...


Я привел пример, как написать док. комментарий. Там аналогчино с таблицей значений. Как таблица состоит из СтрокаТаблицыЗначений, у которой уже описываются колонки. Так и ДанныеФормыКоллекция состоит из ДанныеФормыЭлементКоллекции, у которого уже описываются колонки.

**Comment by RedMammoth** [comment]
Вот пример из документации https://github.com/1C-Company/v8-code-style/blob/master/docs/checks/code_typification.md#ограничение-на-использование-в-документирующих-описаниях-массивов-тз-структур

![image](https://user-images.githubusercontent.com/64589646/204730017-2bffc837-e4bf-4917-b44f-5c996227ad32.png)

**Comment by DmitryShvaika** [comment]
> Вот пример из документации [https://github.com/1C-Company/v8-code-style/blob/master/docs/checks/code_typification.md#ограничение-на-использование-в-документирующих-описаниях-массивов-тз-структур](https://github.com/1C-Company/v8-code-style/blob/master/docs/checks/code_typification.md#%D0%BE%D0%B3%D1%80%D0%B0%D0%BD%D0%B8%D1%87%D0%B5%D0%BD%D0%B8%D0%B5-%D0%BD%D0%B0-%D0%B8%D1%81%D0%BF%D0%BE%D0%BB%D1%8C%D0%B7%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D0%B5-%D0%B2-%D0%B4%D0%BE%D0%BA%D1%83%D0%BC%D0%B5%D0%BD%D1%82%D0%B8%D1%80%D1%83%D1%8E%D1%89%D0%B8%D1%85-%D0%BE%D0%BF%D0%B8%D1%81%D0%B0%D0%BD%D0%B8%D1%8F%D1%85-%D0%BC%D0%B0%D1%81%D1%81%D0%B8%D0%B2%D0%BE%D0%B2-%D1%82%D0%B7-%D1%81%D1%82%D1%80%D1%83%D0%BA%D1%82%D1%83%D1%80)
> 
> ![image](https://user-images.githubusercontent.com/64589646/204730017-2bffc837-e4bf-4917-b44f-5c996227ad32.png)

Спасибо, извиняюсь - тема закрыта
