### ISSUE TITLE
В расширении не работает переопределение обработчиков событий формы документов ПередЗаписью

### ISSUE THREAD

**Issue by iljyxa** [1C-Company/1c-edt-issues#778]
### Описание ошибки

При переопределении обработчика события ПередЗаписью формы документа (вместо, перед, после) вручную или с помощью команды "Добавить в расширение", код обработчика не выполняется.
Если открыть ИБ с помощью конфигуратора, то можно увидеть, что обработчик вовсе не назначен для данного события.

### Как воспроизвести

1. Берем проект любой конфигурации
2. Добавляем проект расширения конфигурации
3. Добавляем в расширение форму документа
4. В расширенной форме документа переопределяем событие ПередЗаписью
5. Открываем ИБ, записываем документ и видим, что код в расширении не выполняется.
6. Открываем в конфигуратор и наблюдаем, что процедура не привязана к событию.

### Скриншоты

![image](https://user-images.githubusercontent.com/5513508/205003747-3e6d21d5-5524-4db6-9c5a-b68919b345f6.png)
![image](https://user-images.githubusercontent.com/5513508/205003894-98852659-6333-4b4a-b989-5319b6baebae.png)

### Ожидаемое поведение

Процедура, переопределяющая поведение события формы ПередЗаписью, должна быть привязана к данному событию

### Лог рабочей области

[log.txt](https://github.com/1C-Company/1c-edt-issues/files/10130762/log.txt)
[trace.log](https://github.com/1C-Company/1c-edt-issues/files/10130764/trace.log)

### Версия 1С:EDT

Ruby 2022.1.3

### Операционная система

Windows

### Установленные плагины

1C:Code style V8, 1C:SSL-support, 1C:Language Tool

### Дополнительная информация

Версия платформы 1С 8.3.20.1789

**Comment by vadimeg** [comment]
То же, что и
https://github.com/1C-Company/1c-edt-issues/issues/410
https://github.com/1C-Company/1c-edt-issues/issues/475
https://github.com/1C-Company/1c-edt-issues/issues/626

Исправлено в 2022.2
