### ISSUE TITLE
Не импортируется конфигурация с внешним источником данных, который содержит таблицу с признаком незаполненного родителя NULL

### ISSUE THREAD

**Issue by ovcharenko-di** [1C-Company/1c-edt-issues#780]
### Описание ошибки

Платформа 8.3.21.1393
Процесс импорта конфигурации из исходников завершается с ошибкой (см. скрин 1)

Таблица внешнего источника данных иерархическая, признак незаполненного родителя указан в конфигураторе как "NULL".

### Как воспроизвести

1. Импортировать в EDT 2022.1.3 конфигурацию из EDT_bug.zip
2. Увидеть сообщение об ошибке

[EDT_bug.zip](https://github.com/1C-Company/1c-edt-issues/files/10134442/EDT_bug.zip)

### Скриншоты

скрин 1
![image](https://user-images.githubusercontent.com/24920942/205112674-2a4a24c8-2275-4aa3-ba1a-7772cac4f390.png)

### Ожидаемое поведение

Импорт конфигурации завершается без ошибок.

### Лог рабочей области

[log.txt](https://github.com/1C-Company/1c-edt-issues/files/10134638/log.txt)

### Версия 1С:EDT

Ruby 2022.1.4

### Операционная система

Windows

### Установленные плагины

Нет плагинов

### Дополнительная информация

- после возникновения ошибки EDT позволяет открыть свойства таблицы и вручную установить признак незаполненного родителя NULL, однако это изменение **не сохраняется**, всегда сбрасывается
- воспроизводится и на 2022.1.3

**Comment by vadimeg** [comment]
Исправлено в 2023.1
