### ISSUE TITLE
[1CEDT] Долгие проверки

### ISSUE THREAD

**Issue by TimurDD** [1C-Company/1c-edt-issues#801]
```
После перехода на версию 2022.1.3 периодически запускаются проверки, которые выполняются не оправдано долго (от 30 минут до нескольких часов).
При этом нет возможности ни сливать ветки, ни открыть какой-нибудь объект (см. скрин).
Иногда в панели состояния отображается прогресс проверки (в данном случае не отображается), и по прогрессу
остается последняя проверка (например 999 из 1000) которая выполняется также долго. Подозреваю в обоих случаях
разница только в отображении прогресса.
Конфигурация ЕРП.
Очистка, пересоздание проекта и пр. не помогает (точнее пересоздание проекта помогает не надолго). При этом проверка(и) проходят до конца и после можно работать.
Upd: Сильно растет размер рабочей области (.metadata).
![22](https://user-images.githubusercontent.com/109646994/208234971-eb175264-b835-4c17-88b2-a49e6954be90.png)


Product name: 1C:Enterprise Development Tools
Product version: 1.26.3.14
Java home: C:\Program Files\BellSoft\LibericaJDK-11-Full
Java vm name: OpenJDK 64-Bit Server VM
Java vm info: mixed mode
Java version: 11.0.9
Java vendor: BellSoft
OS: win32
Total mem: 21 474
Free mem: 8 943
Cores: 12
```

**Comment by TimurDD** [comment]
Теперь уже и пересоздание проекта не помогает. Попробовал 2022.2.1, сначало вроде норм было. Потом стало как прежде. 35499 из 35500 выполняется бесконечно.

**Comment by NikitaMikhaylovSB** [comment]
@TimurDD ERP? Там огромный модуль менджера обмена, проблема в нем. Только ждать завершения работы, тут требуется изменение на уровне конфигуции и эта проблема известна.

**Comment by TimurDD** [comment]
Странно. Видимо проблема редкая, в сообществе (в тг) помочь не смогли. Я попробовал отключить проверки BSL и пр. из плагина - заработало. Проверки проходят как и раньше, примерно.

**Comment by TimurDD** [comment]
@NikitaMikhaylovSB Как я понял, речь идет про общий модуль МенеджерОбменаЧерезУниверсальныйФормат. Как тогда исключить его из проверок или что нужно в нем сделать, чтобы проверки выполнялись штатно?

**Comment by NikitaMikhaylovSB** [comment]
Да, верно - проблема в этом модуле. Способов отключить - не знаю. Пока только надеяться, что проблему с таким модулей исправят в ERP (шансы есть)

**Comment by TimurDD** [comment]
Есть ли описание, в чем заключается проблема? Могу ли я ее решить (попытаться) самостоятельно?

**Comment by TimurDD** [comment]
Для информации: Отключил все проверки по проекту, ЕДТ стала работать нормально, но без части проверок.

**Comment by pravets** [comment]
> @NikitaMikhaylovSB Как я понял, речь идет про общий модуль МенеджерОбменаЧерезУниверсальныйФормат. Как тогда исключить его из проверок или что нужно в нем сделать, чтобы проверки выполнялись штатно?

Если этот модуль не дорабатывается, то исключить его из проверки можно с помощью плагина [Disable Editing plugin for 1C:EDT](https://github.com/marmyshev/edt-editing)/ Плагин позволяет запретить редактировать объекты и бонусом отключает их проверку, так как нет нужды проверять то, что мы не правим. Возможно костыль в вашей ситуации, но рабочий.
