### ISSUE TITLE
Реквизит формы с типом "РегистрНакопленияНаборЗаписей.%ИмяРегистра%" некорректно работает при выгрузке проекта в .cf

### ISSUE THREAD

**Issue by VAGoncharov** [1C-Company/1c-edt-issues#802]
### Описание ошибки

В некоторых случаях реквизит формы с типом "РегистрНакопленияНаборЗаписей.%ИмяРегистра%" экспортируется из EDT в ИБ некорректно: конфигуратор правильно определяет типа реквизита, но не позволяет работать с ним как с реквизитом набора записей, в пользовательском режиме возникает ошибка.

Такая проблема возникает только на формах, созданных в старых версиях платформы (предположительно, 8.2). На формах, созданных изначально в EDT, ошибка не возникает.

Различий в xml-атрибутах реквизита на старой и новой формы не обнаружено:
Старая форма:
```
<attributes>
    <name>Реквизит1</name>
     <id>1000003</id>
    <valueType>
       <types>AccumulationRegisterRecordSet.УчетЦеновогоРасхождения</types>
     </valueType>
    <view>
      <common>true</common>
    </view>
    <edit>
       <common>true</common>
    </edit>
</attributes>
```
Новая форма, созданная в EDT:
```
  <attributes>
    <name>Реквизит1</name>
    <id>5</id>
    <valueType>
      <types>AccumulationRegisterRecordSet.УчетЦеновогоРасхождения</types>
    </valueType>
    <view>
      <common>true</common>
    </view>
    <edit>
      <common>true</common>
    </edit>
  </attributes>
```

Нашли только один способ обойти проблему: создать реквизит формы в конфигураторе и импортировать конфигурацию в EDT.

### Как воспроизвести

1. Открыть в EDT форму объекта, созданного в старых версиях платформы (предположительно 8.2) до перехода разработки в EDT. На форме объекта создать реквизит типа "РегистрСведенийНаборЗаписей.%ИмяРегистра%". Убедиться, что реквизит отображается корректно и с ним можно работать программно в модуле формы.
![EDT_есть проблема](https://user-images.githubusercontent.com/1153965/208242797-9e628887-fe4a-47ea-81a5-7e0bd167e93f.png)

2. Выгрузить проект в информационную базу, запустить конфигуратор, открыть форму объекта. Убедиться, что реквизит отображается некорректно и при работе с ним в пользовательском режиме возникает ошибка.
![Конфигуратор_есть проблема](https://user-images.githubusercontent.com/1153965/208242833-9f92d594-56a6-4b01-bb4e-99fa0e7d980e.png)

Проблема **не воспроизводится**, если создать такой реквизит в объекте, изначально созданным в EDT.

### Ожидаемое поведение

Реквизиты формы с типом "РегистрНакопленияНаборЗаписей" корректно выгружаются в cf.

### Лог рабочей области

-

### Версия 1С:EDT

2022.1.3

### Операционная система

Windows

### Установленные плагины

1C:Code style V8, 1C:SSL-support, 1C:Language Tool

**Comment by VAGoncharov** [comment]
Опытным путем установлено, что конфигуратор не умеет читать атрибуты xml с большим id. Заменил <id> из примера с 1000003 на 41 и импортировал проект в конфигуратор, конфигуратор начал читать реквизит корректно.

В прочих реквизитах формы найден такой реквизит, у него есть дополнительная колонка c id 1000000.
  <attributes>
    <name>РасчетыПоНДФЛоборотыСоСчетами</name>
    <title>
      <key>ru</key>
      <value>Расчеты по НДФЛобороты со счетами</value>
    </title>
    <id>37</id>
    <valueType>
      <types>AccumulationRegisterRecordSet.РасчетыПоНДФЛоборотыСоСчетами</types>
    </valueType>
    <view>
      <common>true</common>
    </view>
    <edit>
      <common>true</common>
    </edit>
    <columns>
      <name>ИндексКартинки</name>
      <title>
        <key>ru</key>
        <value>Индекс картинки</value>
      </title>
      <id>1000000</id>
      <valueType>
        <types>Number</types>
        <numberQualifiers>
          <precision>1</precision>
          <nonNegative>true</nonNegative>
        </numberQualifiers>
      </valueType>
      <view>
        <common>true</common>
      </view>
      <edit>
        <common>true</common>
      </edit>
    </columns>
  </attributes>
  
  От id этой колонки продолжаются нумероваться новый реквизиты формы, хотя конфигуратор новые реквизиты нумерует от id последнего реквизита.

**Comment by vadimeg** [comment]
Вот выгрузка созданного в конфигураторе формы расширения:

	<Attributes>
		<Attribute name="Реквизит1" id="1000001">
			<Type>
				<v8:Type>v8:ValueTable</v8:Type>
			</Type>
			<Columns>
				<Column name="Реквизит1" id="1000000">
					<Type>
						<v8:Type>xs:string</v8:Type>
						<v8:StringQualifiers>
							<v8:Length>0</v8:Length>
							<v8:AllowedLength>Variable</v8:AllowedLength>
						</v8:StringQualifiers>
					</Type>
				</Column>
				<Column name="Реквизит2" id="1000001">
					<Type>
						<v8:Type>xs:string</v8:Type>
						<v8:StringQualifiers>
							<v8:Length>0</v8:Length>
							<v8:AllowedLength>Variable</v8:AllowedLength>
						</v8:StringQualifiers>
					</Type>
				</Column>
			</Columns>
		</Attribute>
	</Attributes>


Именно из конфигуратора и было перенесено нумерование собственных реквизитов, команд и параметров в EDT.
И начинаются они с 1000000. В обычных конфигурациях нумерация идет с 1.
Это необходимо, чтобы исключить коллизии в виде появления дублей в заимствуемом объекте базовой конфигурации.
Тут дело в чем-то другом. Возможно действительно есть дубли в идентификаторах. Тогда должна сработать проверка на некорректность ID, у нее есть квик-фикс.
Без конфигурации сложно сказать.

**Comment by vadimeg** [comment]
Добрый день, можете, пожалуйста, проверить, есть ли дубли в идентификаторах формы - должна сработать проверка.
Если нет, то пришлите конфигурацию, если возможно

**Comment by VAGoncharov** [comment]
@vadimeg Добрый день. Ранее через @AlmazNasibullin передавал вам xml формы, где была проблема. Удалось разобраться или закрываем ишуз?

**Comment by vadimeg** [comment]
@VAGoncharov Добрый день, пока не удалось. По xml-выгрузке отдельной формы воспроизвести проблему проблематично. Если есть возможность прислать конфигурацию (в любом виде), то это могло бы помочь. А почему предлагаете закрыть? Больше не актуально?

**Comment by VAGoncharov** [comment]
Конфигурацию отослать не вариант, к сожалению.
Просто поинтересовался статусом, может зря висит. У нас после ручной правки id реквизитов ошибка перестала воспроизводиться.

**Comment by vadimeg** [comment]
Тогда давайте закроем. Если что, можно будет переоткрыть
