### ISSUE TITLE
Невозможно экспортировать в XML (или выгрузить в ИБ) расширение если в нем заимствованы критерии отбора

### ISSUE THREAD

**Issue by goodwinvu** [1C-Company/1c-edt-issues#803]
### Описание ошибки

Ошибка возникает при экспорте в XML расширения с заимствованными критериями отбора.

### Как воспроизвести

- Создать расширение конфигурации
- Заимствовать в него критерий отбора 
- Запустить экспорт расширения в XML 

при этом в лог ошибка попадает не всегда, на некоторых расширениях она была только в окне сообщения, а в логе при этом ошибок не было, (во вложении привожу лог, где удалось увидеть сообщение об ошибке)
ошибка вида (это две разных)
```
java.lang.IllegalStateException: Cannot find appropriate extension property for the original object com._1c.g5.v8.dt.metadata.mdclass.impl.FilterCriterionImpl@5c941158 according to original property org.eclipse.emf.ecore.impl.EAttributeImpl@6ec32389 (name: useStandardCommands) (ordered: true, unique: false, lowerBound: 0, upperBound: 1) (changeable: true, volatile: false, transient: false, defaultValueLiteral: null, unsettable: false, derived: false) (iD: false)

java.lang.IllegalStateException: Cannot find appropriate extension property for the original object com._1c.g5.v8.dt.metadata.mdclass.impl.FilterCriterionImpl@faa03843 according to original property org.eclipse.emf.ecore.impl.EAttributeImpl@583aeb96 (name: useStandardCommands) (ordered: true, unique: false, lowerBound: 0, upperBound: 1) (changeable: true, volatile: false, transient: false, defaultValueLiteral: null, unsettable: false, derived: false) (iD: false)

```

### Ожидаемое поведение

Расришение должно выгружаться в ИБ или в XML без ошибок

### Лог рабочей области

[test.zip](https://github.com/1C-Company/1c-edt-issues/files/10252724/test.zip)

### Версия 1С:EDT

Ruby 2022.2.1

### Операционная система

Windows

### Установленные плагины

1C:Code style V8, 1C:SSL-support, Другие сторонние плагины `Название плагина...`

### Дополнительная информация

установлен плагин запрета редактирования Disable Editing plugin for 1C:EDT и темная тема DarkestDark

**Comment by vadimeg** [comment]
Исправлено в 2022.2.2
