### ISSUE TITLE
Описание приватных полей в документирующем комментарии к структурам

### ISSUE THREAD

**Issue by RedMammoth** [1C-Company/1c-edt-issues#806]
### Описание проблемы

Бывают ситуации, когда в программном интерфейсе есть функция-конструктор, в которой есть поля, которые требуются к заполнению пользователем АПИ, а так же "служебные" поля, которые пользователю АПИ не нужны, в этих полях служебные процедуры хранят необходимую им дополнительную информацию.
Сейчас единственный способ выделить эти поля - написать комментарий для человека, что поле служебное и пользователю АПИ трогать его не нужно.
Однако хотелось бы иметь механизм, для "машинного" определения таких полей, чтобы можно было бы в дальнейшем создать проверку предупреждающую об изменении приватного поля или доработать форму контент-ассиста, чтобы она скрывала эти поля, если структура находится вне контекста той же функциональной подсистемы что и ее функция конструктор.

### Описание решения проблемы

Предлагаю расширить синтаксис документирующего комментария и добавить правило описания "служебных" (приватных) полей структуры. Например, поля начинающиеся с подчеркивания:

```bsl
#Область ПрограммныйИнтерфейс

// Возвращаемое значение:
//  Структура:
// * ПубличноеПоле - Строка
// * _ПриватноеПоле - Строка
//
Функция МояСтруктура() Экспорт
	Данные = Новый Структура;
	Данные.Вставить("ПубличноеПоле", "");
	Данные.Вставить("_ПриватноеПоле", "");
	Возврат Данные;
КонецФункции

#КонецОбласти
```

**Comment by marmyshev** [comment]
> Предлагаю расширить синтаксис документирующего комментария и добавить правило описания "служебных" (приватных) полей структуры. Например, поля начинающиеся с подчеркивания:

Так это не уровень механизма (язык док.комментов) - а уровень соглашений (стандартов). Т.е. если посмотреть на другие языки, например python - там все поля видны, включая служебные. Но каждый знает (т.е. читает стандарт) - что к служебным/внутренним полям нельзя так просто вот обращаться.

Т.о. сейчас синтаксис док.комментов не запрещает использовать служебные поля.

Закрываем задачу?

**Comment by RedMammoth** [comment]
Да
