### ISSUE TITLE
Отсутствует свойство расширения "Синоним"

### ISSUE THREAD

**Issue by petypen** [1C-Company/1c-edt-issues#813]
### Описание ошибки

Ошибка в том что, среди свойств расширения конфигурации отсутствует свойство "Синоним"

### Как воспроизвести

В проекте расширения конфигурации откройте свойства конфигурации.
На форме основных свойств отсутствует свойство "Синоним"

### Скриншоты

![2022-12-26_20-35-22](https://user-images.githubusercontent.com/6500075/209572291-0579f03f-0f95-4f81-bdfa-7c4eef1b8813.png)

![2022-12-26_20-37-36](https://user-images.githubusercontent.com/6500075/209572294-92b67925-60b3-49c6-9495-72ed4d364148.png)

### Ожидаемое поведение

В EDT у расширения конфигурации должно быть доступно свойство "Синоним" по аналогии с конфигуратором.

### Лог рабочей области

[metadata.zip](https://github.com/1C-Company/1c-edt-issues/files/10304375/metadata.zip)

### Версия 1С:EDT

Ruby 2022.2.1

### Операционная система

Windows

### Установленные плагины

Нет плагинов

### Дополнительная информация

Платформа 8.3.20

**Comment by vadimeg** [comment]
Исправлено в 2022.2.3
