### ISSUE TITLE
Нет типа для элемента ОписанияСтандартныхРеквизитов

### ISSUE THREAD

**Issue by RedMammoth** [1C-Company/1c-edt-issues#818]
### Описание ошибки

Если обратится к элементу коллекции объекта с типом ОписанияСтандартныхРеквизитов, то тип элемента рассчитывается только при получении через квадтраные скобки по имени реквизита.
При обходе коллекции в цикле или при получении по индексу тип не возвращается.

### Как воспроизвести

```bsl
Процедура Тест()
	МетаданныеТЧ = Неопределено; // ОбъектМетаданныхТабличнаяЧасть
	ТестПоИмени = МетаданныеТЧ.СтандартныеРеквизиты["НомерСтроки"];
	ТестПоИндексу = МетаданныеТЧ.СтандартныеРеквизиты[0];
	Для Каждого ТестВЦикле Из МетаданныеТЧ.СтандартныеРеквизиты Цикл

	КонецЦикла;
КонецПроцедуры
```

### Скриншоты

![image](https://user-images.githubusercontent.com/64589646/210089412-62ed24c1-c892-424f-a93c-a9c4650a5d85.png)

![image](https://user-images.githubusercontent.com/64589646/210089454-199dbed6-956c-4a3d-b141-1298cfe1f0b4.png)

![image](https://user-images.githubusercontent.com/64589646/210089508-0acb6237-4dad-4fc9-bda1-3562735fbb95.png)

![image](https://user-images.githubusercontent.com/64589646/210089554-98032fc5-bf8e-4de8-9188-2a448ceaaced.png)

### Ожидаемое поведение

Тип элемента рассчитывается во всех трех случаях

### Лог рабочей области

-

### Версия 1С:EDT

2022.2

### Операционная система

Windows

### Установленные плагины

1C:Code style V8, 1C:SSL-support, 1C:Language Tool

**Comment by LesN1ck** [comment]
А какой стандартный реквизит будет под 0-м индексом? Где это задокументировано и на что должна опираться подсказка? В цикле тот же вопрос, но еще веселее.

**Comment by RedMammoth** [comment]
> А какой стандартный реквизит будет под 0-м индексом? Где это задокументировано и на что должна опираться подсказка? В цикле тот же вопрос, но еще веселее.

Во всех трех случаях возвращается объект типа ОписаниеСтандартногоРеквизита, поля этого типа фиксированные и не зависят от того, какой именно это стандартный реквизит. На текущий момент ЕДТ правильно определяет только один из трех вариантов.

**Comment by SeiOkami** [comment]
Возможно, это связано:
![image](https://user-images.githubusercontent.com/42138875/222948644-022caae7-a2d6-419f-b390-57203ea80c40.png)

Можно обойти непосредственным указанием типа:
![image](https://user-images.githubusercontent.com/42138875/222948658-e2761634-4600-48ac-99dc-52c4e7c43e51.png)

**Comment by Jimmo910** [comment]
не видит номер строки...
Ruby 2023.1.2
![image](https://github.com/1C-Company/1c-edt-issues/assets/122779512/2c7aa866-a4c5-478f-a915-b6ade57adb00)

**Comment by MaksimDzyuba** [comment]
Здравствуйте, поправил, постараюсь перенести в 2023.2, но точно будет в 2023.3.
![image](https://github.com/1C-Company/1c-edt-issues/assets/77277424/ac26d52c-6e47-418e-9c25-d2963efc7c48)
![image](https://github.com/1C-Company/1c-edt-issues/assets/77277424/357e56b6-ab4f-483b-9329-ca7d8fd42ecc)

@Jimmo910 Здравствуйте, описанная Вами ситуация не имеет отношения к описываемой здесь проблеме и к наполнению контекстов платформы, если ситуация все еще актуально, большая просьба зарегать отдельной ошибкой.

@SeiOkami Здравствуйте, описываемая Вами проблема не воспроизвелась
![Снимок экрана 2023-11-15 в 0 30 16](https://github.com/1C-Company/1c-edt-issues/assets/77277424/d2b3bb60-716d-4451-81b3-b3a1ccd24041)
