### ISSUE TITLE
Ошибка при попытке выбора сравнения с полем типа "Число" при редактировании условного форматирования в СКД

### ISSUE THREAD

**Issue by serjevski** [1C-Company/1c-edt-issues#819]
### Описание ошибки

При выборе в правой части условия в условном форматировании типа "Число" появляется сообщение об ошибке.
![image](https://user-images.githubusercontent.com/2284313/210750674-14aed421-dd33-448d-a07d-555a337cd523.png)

### Как воспроизвести

Открываем в любом новом отчете редактор СКД, составляем простенький запрос, и на вкладке "Настройки" вверху пробуем во вкладке "Условное форматирование" внизу создать условие вида "ресурс меньше 0", ну простейшее выделение отрицательных значений.

Сначала при выделении поля "Правое значение" ЕДТ не предлагает вообще ничего. После нажатия на крестик появляется кнопочка "Т", позволяющая выбрать тип. И вот при выборе типа "Число" и возникает данная ошибка.

### Скриншоты

![image](https://user-images.githubusercontent.com/2284313/210751982-b38b1246-2908-4b39-862d-255f24edea6b.png)

### Ожидаемое поведение

Нужно позволять работать с числами в условиях, связанных с численным полем отчета.

### Лог рабочей области

[log.txt](https://github.com/1C-Company/1c-edt-issues/files/10351211/log.txt)
[trace.log](https://github.com/1C-Company/1c-edt-issues/files/10351212/trace.log)

### Версия 1С:EDT

1C:Enterprise Development Tools Ruby 2022.2.2  

### Операционная система

Windows

### Установленные плагины

Нет плагинов

**Comment by MaksimDzyuba** [comment]
Здравствуйте, исправление войдет в ближайших выход версии 2022.2
