### ISSUE TITLE
[1CEDT] Проблемы и ошибки при работе с расширением в Ruby 2022.2.2

### ISSUE THREAD

**Issue by EChudnovsky** [1C-Company/1c-edt-issues#821]
В новой версии EDT очень не стабильно  выполняются операции при работе с расширением.
1. При заимствовании реквизита формы динамического списка очень часто появляться ошибка "Свойство "Путь к данным" имеет некорректное значение 
"Список.Имяреквизтиа": <номер> сегмент (form-data-path)". Хотя ВСЕ реквизиты этого объекта заранее заимствованы из основной конфигруации. 
При этом динамический список не отражается. Если же реквизит вернуть к основной конфигурации, тогда список отражается корректно.

![изображение](https://user-images.githubusercontent.com/5530435/211347457-a45d929f-9b84-4413-9e3a-77769c8f531e.png)

2. При обновлении формы из основной конфигурации появились ситуации в ОС windows , когда элементы формы не отражаются в редакторе форм.
3. Самостоятельная или совместная с основным проектом очистка проекта расширения часто приводит к ошибке IllegalStateException.

Product name: 1C:Enterprise Development Tools
Product version: 1.27.2.10
Java home: C:\Program Files\BellSoft\LibericaJDK-11-Full
Java vm name: OpenJDK 64-Bit Server VM
Java vm info: mixed mode
Java version: 11.0.12
Java vendor: BellSoft
OS: win32
Total mem: 12 100
Free mem: 2 178
Cores: 16

log-файлы: [log.zip](https://github.com/1C-Company/1c-edt-issues/files/10374440/log.zip)

**Comment by vadimeg** [comment]
Исправлено в 2022.2.3
