### ISSUE TITLE
Добавление на начальную страницу Планировщика приводит к ошибке сервера

### ISSUE THREAD

**Issue by motivix** [1C-Company/1c-edt-issues#822]
### Описание ошибки

Добавляю на начальную страницу Планировщик, Запускаю отладку. Получаю ошибку «На сервере 1С:Предприятия произошла неисправимая ошибка. Приложение будет закрыто»

### Как воспроизвести

1. Создать пустую базу на удалённом сервере
2. Создать проект в EDT для этой базы
3. Создать общую форму 
4. Добавить на неё Планировщик и назначить её на НачальнуюСтраницу
5. Обновить конфигурацию базы
6. Получить ошибку

### Ожидаемое поведение

Отладка должна запуститься и на форме появиться пустой Планировщик

### Лог рабочей области

[.log](https://github.com/1C-Company/1c-edt-issues/files/10392884/default.log)
[trace.log](https://github.com/1C-Company/1c-edt-issues/files/10392885/trace.log)

### Версия 1С:EDT

Ruby 2022.1.2

### Операционная система

Windows

### Установленные плагины

1C:Code style V8

### Дополнительная информация

Планировщик на общих формах гючит уже несколько лет. В разных версиях по разному.
Если создавать Планировщик в Конфигураторе, а потом импортировать Конфигурацию в Проект, то всё нормально работает

**Comment by vadimeg** [comment]
Создана и запланирована внутренняя задача. Эту закрываем.
