### ISSUE TITLE
Редактор формы не отображает элементы подчиненной таблицы

### ISSUE THREAD

**Issue by SeiOkami** [1C-Company/1c-edt-issues#824]
### Описание ошибки

Если на форме добавить реквизит с типом ТаблицаЗначений, а потом ему добавить колонку с типом ТаблицаЗначений (подчиненная таблица), то при выносе его на форму, в редакторе ЕДТ элемент не отображается. В конфигураторе ок и в предприятии тоже.

### Как воспроизвести

1. Перейдите в редактор формы
2. Добавить реквизит "Таблица" с типом ТаблицаЗначений
3. Добавить в "Таблица" колонки с типом Строка и ТаблицаЗначений
4. В подчиненной таблице тоже добавить колонку с типом Строка. Строковые колонки нужны только чтобы таблица отображалась на форме. Можно добавлять любые другие.
5. Вынесите основную таблицу на форму, а затем и подчиненную
6. В результате элементы созданы, но подчиненная не отображается. 
7. Обновить базу
8. Запустить конфигуратор и проверить, что в нём элемент отображается
9. Запустить предприятие и проверить, что в нём элемент отображается

### Скриншоты

![photo_2023-01-14_13-09-57](https://user-images.githubusercontent.com/42138875/212467100-efce37a0-cf41-4844-b569-0a8883fde26d.jpg)
![photo_2023-01-14_13-09-55](https://user-images.githubusercontent.com/42138875/212467102-eb68a152-0e32-404a-bff4-16bed0b7fca3.jpg)

### Ожидаемое поведение

Элемент должен отображаться в редакторе формы

### Лог рабочей области

Приложил экспорт проекта для демонстрации
[Не отображается подчиненная таблица на форме.zip](https://github.com/1C-Company/1c-edt-issues/files/10417115/default.zip)

### Версия 1С:EDT

Ruby 2022.1.3

### Операционная система

Windows

### Установленные плагины

1C:Code style V8, 1C:SSL-support

### Дополнительная информация

Данная ошибка мешает верстке формы (приходится это делать в конфигураторе) и дальнейшей поддержки (вводит разработчика в заблуждение)

**Comment by vadimeg** [comment]
Исправлено в 2023.1

**Comment by vadimeg** [comment]
Исправление перенесено в 2022.2.4
