### ISSUE TITLE
Ошибка обновления конфигурации - Неверный путь к данным

### ISSUE THREAD

**Issue by EZabelin** [1C-Company/1c-edt-issues#831]
### Описание ошибки

При обновлении конфигурации возникает ошибка вида:
/AccountingRegisters/МСФО/Forms/ФормаСписка/Ext/Form.xml: Неверный путь к данным: "Список.AccountDr".

В EDT в форме указан источник "СчетДт": <dataPath xsi:type="form:DataPath"><segments>Список.СчетДт</segments></dataPath>, при выгрузке проекта в XML: <LabelField name="СписокСчетДт" id="12">
<DataPath>Список.AccountDr</DataPath>

### Как воспроизвести

Импортировать конфигурацию 1С в проект, создать новый проект, выполнить полное обновление.
На версии Ruby 2022.1.5 ошибка не воспроизводится.

### Скриншоты

Сравнение выгрузки проекта XML в версии 2.1.5 и 2.2.2
![image](https://user-images.githubusercontent.com/19504873/213100656-d295b610-2d6f-41c7-9bf1-700e8992ad0a.png)

### Ожидаемое поведение

Обновление выполняется без ошибок

### Лог рабочей области

[error-cpm.log](https://github.com/1C-Company/1c-edt-issues/files/10442744/error-cpm.log)

### Версия 1С:EDT

Ruby 2022.2.2

### Операционная система

Windows

### Установленные плагины

Нет плагинов

**Comment by Daabramov** [comment]
Воспроизводится на бит финансе на базе бп 3.0

**Comment by SeiOkami** [comment]
Такая же проблема при попытке вынести на форму глобальную команду с передачей параметра - Элементы.Список.ТекущиеДанные.Ссылка

![image](https://user-images.githubusercontent.com/42138875/213372393-68a512fe-0194-473c-806b-837022da59c5.png)

![image](https://user-images.githubusercontent.com/42138875/213372403-7213f28e-bbe3-4282-9166-87768e3528e9.png)

Причем если сделать изменения в конфигураторе, а затем импортировать в ЕДТ, то в путь прописывается такой адрес:
![image](https://user-images.githubusercontent.com/42138875/213372482-a3f9f0f8-1d2e-4763-aed2-9fa0851cfe3a.png)

Но в самой ЕДТ не отображается кнопка

**Comment by SeiOkami** [comment]
Нашёл прикольное решение.
1. В конфигураторе вынес кнопку
2. Импортировал в ЕДТ
3. Скопировал "английский" путь (который ставит ЕДТ)
4. Перевыбрал путь в ЕДТ на "русский"
5. Удалил Закрыл ЕДТ
6. В файлике формы вручную изменил "русский" путь на "английский"
7. Открыл ЕДТ

В результате ЕДТ кнопку видит и базу обновляет

**Comment by vadimeg** [comment]
Исправлено в 2022.2.3
