### ISSUE TITLE
Поиск по конфигурации отображает не все результаты

### ISSUE THREAD

**Issue by adminimusRU** [1C-Company/1c-edt-issues#834]
### Описание ошибки

В результатах поиска отображаются только 5 найденных мест, хотя на самом деле их 9 (видно в строке сверху):
![image](https://user-images.githubusercontent.com/28653631/213377918-19d657be-740f-4c33-a242-19ad27de07ab.png)
Не отображаются совпадения из модуля менеджера. При этом они отображаются в поиске по файлам:
![image](https://user-images.githubusercontent.com/28653631/213378995-fa3ef2f9-c654-4696-b0c4-f03e7bb346d7.png)

### Как воспроизвести

Точный сценарий воспроизведения неясен. Перезапуск EDT не помогает.

### Ожидаемое поведение

Поиск должен отображать все результаты.

### Лог рабочей области

[логи.zip](https://github.com/1C-Company/1c-edt-issues/files/10454354/default.zip)

### Версия 1С:EDT

2022.2.2

### Операционная система

Windows

**Comment by RedMammoth** [comment]
Если встать на эту строку результаты по модулю менеджера не показываются?
![image](https://user-images.githubusercontent.com/64589646/213379897-56d43fc2-21e7-45df-906a-fc7512c7b7cc.png)

4 результата на этой строки должны быть не группировочной строкой по вложенной, а отдельные 4 строки результата

**Comment by adminimusRU** [comment]
Точно, недостающие результаты именно там :)
