### ISSUE TITLE
EDT 2022.2.2 удаляет синоним из расширений

### ISSUE THREAD

**Issue by proDOOMman** [1C-Company/1c-edt-issues#843]
### Описание ошибки

При работе с расширениями в EDT пропадает поле "Синоним", а из выгрузки удаляется тег "synonym"

### Как воспроизвести

1. Откройте расширение
2. Откройте свойства расширения
3. Попытайтесь найти "Синоним"
4. Синонима нет...

### Ожидаемое поведение

В расширениях синоним есть и его можно редактировать

### Лог рабочей области

...

### Версия 1С:EDT

2022.2.2

### Операционная система

Windows

**Comment by Jimmo910** [comment]
А у нас просто Синоним не доступен становиться в последнее время.

Создал пустой проект.
Добавил туда расширение из Гита.
И все Синонимы у всех объектов пропали.
Хотя в файлах они есть.

![image](https://user-images.githubusercontent.com/122779512/215967409-84c6ecd2-a9d9-40aa-9310-296a40b2d02e.png)

![image](https://user-images.githubusercontent.com/122779512/215967527-bb4576cd-2ed3-451c-8e2c-d91cc722a4c2.png)

Могу весь проект прислать разработчикам, по запросу в телегу... [@Jimmi910](https://t.me/Jimmi910)

**Comment by Jimmo910** [comment]
Так же пробывал на и macOS с EDT версии 2022.1.5

**Comment by vadimeg** [comment]
То же, что и https://github.com/1C-Company/1c-edt-issues/issues/813
Исправлено в 2022.2.3

**Comment by Jimmo910** [comment]
[11.log](https://github.com/1C-Company/1c-edt-issues/files/10684559/11.log)
[trace.log](https://github.com/1C-Company/1c-edt-issues/files/10684562/trace.log)
<img width="551" alt="image" src="https://user-images.githubusercontent.com/122779512/217508062-4088c893-d4b0-4c67-9541-ae5817d47b92.png">
 
![image](https://user-images.githubusercontent.com/122779512/217508744-18de240c-5c53-4c92-8275-8638b2104eed.png)

**Comment by Jimmo910** [comment]
Ruby 2022.2.3
8.3.21.1674
<img width="496" alt="image" src="https://user-images.githubusercontent.com/122779512/217509071-66177b22-d588-43ab-814c-c4b4a20f5487.png">

**Comment by Jimmo910** [comment]
[vadimeg](https://github.com/vadimeg) помог решить проблему добавилив <languageCode>ru</languageCode>

возможно у меня в какой то момент удалился этот код языка. Надеюсь теперь все будет норм
