### ISSUE TITLE
Поиск по конфигурации не находит вхождений из модулей объектов - только из модулей форм

### ISSUE THREAD

**Issue by SAndreita** [1C-Company/1c-edt-issues#850]
### Описание ошибки

Поиск в конфигурации находит искомый текст только в модулях форм, но игнорирует вхождения в модулях объектов.
В конфигураторе этих проблем не было

### Как воспроизвести

1. Перейдите в `Поиск`
2. Кликните по `Найти`
3. Задайте параметры поиска

### Скриншоты

![image](https://user-images.githubusercontent.com/123439482/216062550-a5e92c0f-e9d7-42e5-837e-1d3feefaf2f1.png)

### Ожидаемое поведение

Показать вхождение искомого в модуле объекта

### Лог рабочей области

[log_01_02_2023.zip](https://github.com/1C-Company/1c-edt-issues/files/10557692/log_01_02_2023.zip)

### Версия 1С:EDT

Ruby 2022.2.2

### Операционная система

Windows

### Установленные плагины

1C:Code style V8

### Дополнительная информация

Платформа - 8.3.19

**Comment by RedMammoth** [comment]
Эта ситуация? https://github.com/1C-Company/1c-edt-issues/issues/834

**Comment by SAndreita** [comment]
> Эта ситуация? #834

Видимо, да, не нашла эту ветку, простите

**Comment by SAndreita** [comment]
> Тогда ошибки нет, только неочевидный интерфейс нового поиска)

Спасибо! Не догадалась бы
