### ISSUE TITLE
EDT не может смержить ветки при переименовании объектов метаданных

### ISSUE THREAD

**Issue by VAGoncharov** [1C-Company/1c-edt-issues#851]
### Описание ошибки

К проекту 1С подключен проект внешних обработок. В ветке X есть обработка "ЗагрузкаНачальногоСальдо_РБП". Мержим ее с веткой Y, в которой:
1. Обработка "ЗагрузкаНачальногоСальдо_РБП" переименовывается в "ЗагрузкаНачальногоСальдо_БухгалтерскийУчет".
2. Добавляется новая обработка "ЗагрузкаНачальногоСальдо_РБП".
Гуиды обработок разные. При попытке объединить ветки выскакивает ошибка:
"Объединение невозможно из-за обнаруженных ошибок. Неуникальное имя объекта метаданных."

При слиянии веток через консоль (git merge) такой проблемы не возникает.

### Как воспроизвести

См. раздел "Описание ошибки"

### Ожидаемое поведение

EDT корректно смержит 2 ветки с учетом актуальных наименований объектов метаданных.

### Лог рабочей области

-

### Версия 1С:EDT

Ruby 2022.1.5

### Операционная система

Windows

### Установленные плагины

1C:Code style V8, 1C:SSL-support

**Comment by AlmazNasibullin** [comment]
@VAGoncharov Добрый день. Подскажите, пожалуйста, uuid'ы обработки ЗагрузкаНачальногоСальдо_РБП в ветке X и обработки ЗагрузкаНачальногоСальдо_БухгалтерскийУчет в ветке Y совпадают?

**Comment by VAGoncharov** [comment]
> @VAGoncharov Добрый день. Подскажите, пожалуйста, uuid'ы обработки ЗагрузкаНачальногоСальдо_РБП в ветке X и обработки ЗагрузкаНачальногоСальдо_БухгалтерскийУчет в ветке Y совпадают?

Нет, они были разные.

**Comment by AlmazNasibullin** [comment]
> Нет, они были разные.
> При слиянии через git merge проблема не воспроизвелась и в дальнейшем edt нормально работал с этими обработками.
1. А какая стратегия сопоставления была выбрана?
2. В дереве сравнения/объединения как были сопоставлены обработки из ветки X и Y?
3. Вы меняли настройки объединения в дереве сравнения/объединения (снимали/устанавливали галки)?

**Comment by VAGoncharov** [comment]
1. Сначала по гуид, потом по наименованию.
2. В дереве сравнения/объединения обработки сопоставились корректно: EDT понимал, что это были разные обработки, при этом он так же понимал, что старая обработка "ЗагрузкаНачальногоСальдо_РБП" была переименована в "ЗагрузкаНачальногоСальдо_БухгалтерскийУчет"
3. Не менял.

Сложилось впечатление, что EDT проверил конфигурацию на уникальные наименования объектов метаданных раньше, чем сделал необходимые преобразования в процессе слияния веток.

**Comment by VAGoncharov** [comment]
Закрываю ишуз, т.к. ни у меня, ни у @AlmazNasibullin не удалось воспроизвести эту ошибку. Последний раз проверял на версии 2022.2.5.
