### ISSUE TITLE
Запущенное через стартер приложение нельзя закрепить на панели задач Windows 10

### ISSUE THREAD

**Issue by tormozit** [1C-Company/1c-edt-issues#852]
### Описание ошибки

Запущенное через стартер приложение нельзя закрепить на панели задач WINdows 10.
Закрепление нужно только для фиксации положения иконы, а не для запуска приложения.

### Как воспроизвести

Запустить стартер EDT в ОС Windows 10. Из него запустить лубую рабочую область. На панели задач ОС появится новая икона без возможность закрепления.

### Скриншоты

![изображение](https://user-images.githubusercontent.com/11896251/216254416-fe782e29-46a2-45ee-962c-a70454c0d7ca.png)

### Ожидаемое поведение

У иконы есть возможность закрепления.

### Лог рабочей области

я

### Версия 1С:EDT

Ruby 2022.2.3

### Операционная система

Windows

**Comment by airaketa** [comment]
Будет исправлена в 2024.1
