### ISSUE TITLE
Ошибка импорта любых изменений из базы 1С на объекте "Интерфейс клиентского приложения"

### ISSUE THREAD

**Issue by tormozit** [1C-Company/1c-edt-issues#854]
### Описание ошибки
Ошибка импорта любых изменений из базы 1С на объекте "Интерфейс клиентского приложения"

### Как воспроизвести
Обновить файловую базу 1С на платформе 8.3.22.1791 из проекта полностью.  В конфигураторе изменить комментарий конфигурации. В EDT выполнить импорт изменений. Возникает ошибка.

### Скриншоты

![изображение](https://user-images.githubusercontent.com/11896251/216303475-55aad26a-94c2-4040-83c0-e6daa3a098b1.png)

![изображение](https://user-images.githubusercontent.com/11896251/216303495-aea8591c-4dc3-4c9a-a02a-cebba78b4944.png)

### Ожидаемое поведение

я

### Лог рабочей области
```
Во время выполнения операции импорта произошла ошибка
	Успешно импортирован файл "Configuration.xml"
	Успешно импортирован файл "Languages\Английский.xml"
	Успешно импортирован файл "Languages\Русский.xml"
	Успешно импортирован файл "Languages\Служебный.xml"
	Успешно импортирован файл "Ext\ManagedApplicationModule.bsl"
	Успешно импортирован файл "Ext\SessionModule.bsl"
	Успешно импортирован файл "Ext\ExternalConnectionModule.bsl"
	Успешно импортирован файл "Ext\OrdinaryApplicationModule.bsl"
	Ошибка импорта файла "Ext\ClientApplicationInterface.xml"
		недопустимое значение "null" в: /ClientApplicationInterface/left/*@id
		недопустимое значение "null" в: /ClientApplicationInterface/left[1]/*@id
	Успешно импортирован файл "Ext\ParentConfigurations.bin"
	Успешно сохранен файл "Configuration.xml"
```
### Версия 1С:EDT

Ruby 2022.2.3

### Операционная система

Windows

### Дополнительная информация
Текст проблемного файла
```
<?xml version="1.0" encoding="UTF-8"?>
<ClientApplicationInterface xmlns="http://v8.1c.ru/8.2/managed-application/core" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:type="InterfaceLayouter">
	<left>
		<panel>
			<uuid>b553047f-c9aa-4157-978d-448ecad24248</uuid>
		</panel>
	</left>
	<left>
		<panel>
			<uuid>13322b22-3960-4d68-93a6-fe2dd7f28ca3</uuid>
		</panel>
	</left>
	<panelDef id="b553047f-c9aa-4157-978d-448ecad24248"/>
	<panelDef id="13322b22-3960-4d68-93a6-fe2dd7f28ca3"/>
	<panelDef id="c933ac92-92cd-459d-81cc-e0c8a83ced99"/>
	<panelDef id="cbab57f2-a0f3-4f0a-89ea-4cb19570ab75"/>
	<panelDef id="b2735bd3-d822-4430-ba59-c9e869693b24"/>
</ClientApplicationInterface>
```
### Способ обхода
После удаления всех элементов объекта "Интерфейс клиентского приложения" ошибка исчезает

**Comment by vadimeg** [comment]
Добрый день, а каким образом был получен проблемный файл?
Просто конфигуратор выгружает панели с идентификатором. Если нет привязки панелей, то им прописывается пустой ID.

Т.е. файл должен был выглядеть так:

<?xml version="1.0" encoding="UTF-8"?>
<ClientApplicationInterface xmlns="http://v8.1c.ru/8.2/managed-application/core" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:type="InterfaceLayouter">
	<left>
		<panel  id="00000000-0000-0000-0000-000000000000">
			<uuid>b553047f-c9aa-4157-978d-448ecad24248</uuid>
		</panel>
	</left>
	<left>
		<panel  id="00000000-0000-0000-0000-000000000000">
			<uuid>13322b22-3960-4d68-93a6-fe2dd7f28ca3</uuid>
		</panel>
	</left>
	<panelDef id="b553047f-c9aa-4157-978d-448ecad24248"/>
	<panelDef id="13322b22-3960-4d68-93a6-fe2dd7f28ca3"/>
	<panelDef id="c933ac92-92cd-459d-81cc-e0c8a83ced99"/>
	<panelDef id="cbab57f2-a0f3-4f0a-89ea-4cb19570ab75"/>
	<panelDef id="b2735bd3-d822-4430-ba59-c9e869693b24"/>
</ClientApplicationInterface>


И такая выгрузка загружается в EDT без ошибок.

**Comment by tormozit** [comment]
Выгружено платформой 8.3.22.1791

**Comment by demony** [comment]
Была та же проблема, тоже пришлось удалить панели и тогда смог загрузить базу в проект.
![image](https://user-images.githubusercontent.com/1720563/218954242-b6ba25a5-e37d-47da-a63d-fa91a69ea74e.png)

Панели снова вернул на место (в EDT), но даже если сейчас из конфигуратора выгрузить эту базу в файлы, то Id панелей не выгружаются, а следовательно при загрузке базы в проект из снова будет ошибка.

Сейчас EDT Ruby 2022.2.3, платформа 8.3.22.1750
В проекте ClientApplicationInterface.cai
```
<?xml version="1.0" encoding="UTF-8"?>
<cai:ClientApplicationInterface xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:cai="http://g5.1c.ru/v8/dt/cai">
  <top xsi:type="cai:CaiPanel" id="b553047f-c9aa-4157-978d-448ecad24248" name="SectionPanel" displayType="PictureAndText"/>
  <top xsi:type="cai:CaiPanel" id="cbab57f2-a0f3-4f0a-89ea-4cb19570ab75" name="OpenedPanel"/>
  <left xsi:type="cai:CaiPanel" id="b2735bd3-d822-4430-ba59-c9e869693b24" name="FunctionsPanel"/>
  <unset id="13322b22-3960-4d68-93a6-fe2dd7f28ca3" name="FavoritePanel"/>
  <unset id="c933ac92-92cd-459d-81cc-e0c8a83ced99" name="HistoryPanel"/>
</cai:ClientApplicationInterface>
```
В выгрузке из конфигуратора в файлы ClientApplicationInterface.xml
```
<?xml version="1.0" encoding="UTF-8"?>
<ClientApplicationInterface xmlns="http://v8.1c.ru/8.2/managed-application/core" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:type="InterfaceLayouter">
	<top>
		<panel>
			<uuid>b553047f-c9aa-4157-978d-448ecad24248</uuid>
		</panel>
	</top>
	<top>
		<panel>
			<uuid>cbab57f2-a0f3-4f0a-89ea-4cb19570ab75</uuid>
		</panel>
	</top>
	<left>
		<panel>
			<uuid>b2735bd3-d822-4430-ba59-c9e869693b24</uuid>
		</panel>
	</left>
	<panelDef id="b553047f-c9aa-4157-978d-448ecad24248"/>
	<panelDef id="13322b22-3960-4d68-93a6-fe2dd7f28ca3"/>
	<panelDef id="c933ac92-92cd-459d-81cc-e0c8a83ced99"/>
	<panelDef id="cbab57f2-a0f3-4f0a-89ea-4cb19570ab75"/>
	<panelDef id="b2735bd3-d822-4430-ba59-c9e869693b24"/>
</ClientApplicationInterface>
```

**Comment by MaksimDzyuba** [comment]
Здравствуйте, зарегистрировали ошибку на платформу с номером 60006248, ожидаем реакции от них. 
По сути, сейчас  в версии 8.3.22 (проверял га 8.3.22.1905), если сделать интерфейс как Вы показали, а потом выгрузить его в xml и загрузить обратно, то его внешний вид будет испорчен

**Comment by tormozit** [comment]
На публичном сервисе ошибок платформы не обнаруживается элемент 60006248. Очень плохо это.

**Comment by MaksimDzyuba** [comment]
я запросил у платформы, как это делать, как ответят, если скажут как, то сделаю, пока ошибка только признана

**Comment by tormozit** [comment]
https://bugboard.v8.1c.ru/error/000138318

**Comment by tretyakevich** [comment]
Проблема решена в 1С:Предприятие 8.3.22.2003
