### ISSUE TITLE
Аннотация подавления ошибки ломает структуру документирующего комментария

### ISSUE THREAD

**Issue by RedMammoth** [1C-Company/1c-edt-issues#856]
### Описание ошибки

Если установить аннотацию подавления ошибки, то она распознается в структуре док. комментария как часть какого-то блока, что может привести к неправильному распознаванию структуры комментария:

### Как воспроизвести

Примеры на скриншотах

### Скриншоты

![image](https://user-images.githubusercontent.com/64589646/216761055-e9da9ca3-c13f-4b48-9668-3ecd88b512dd.png)

![image](https://user-images.githubusercontent.com/64589646/216761097-7aa1b519-56f4-40ec-a6a9-aece288da2df.png)

### Ожидаемое поведение

Указание аннотации, подавляющей ошибки, не меняет структуру документирующего комментария

### Лог рабочей области

-

### Версия 1С:EDT

2022.2.3

### Операционная система

Windows, Linux

### Установленные плагины

1C:Code style V8, 1C:SSL-support, 1C:Language Tool

**Comment by vadimeg** [comment]
Исправлено в 2023.2

**Comment by Roffild** [comment]
https://github.com/1C-Company/v8-code-style/issues/1459

**Comment by ukolabrother** [comment]
Исправлено ранее, добавлен тип tag.

<img width="914" height="475" alt="Image" src="https://github.com/user-attachments/assets/af6a9db0-5b20-4874-a8c7-548a00c2ca61" />
