### ISSUE TITLE
Установка свойства "Кнопка выбора" у реквизита формы в расширении не приводит к появлению изменений для ветки

### ISSUE THREAD

**Issue by MoVled** [1C-Company/1c-edt-issues#858]
### Описание ошибки

Ошибка в том что если добавить форму в расширение и у реквизита установить свойство "Кнопка выбора", то на вкладке "Индексирование Git" эти изменения не отображаются. Соответственно, если переключиться на другую ветку, а потом вернуться обратно, свойство окажется сброшенным в Авто.
Поскольку случаев, когда изменилось только это свойство не много, то можно не заметить такого поведения в общем списке изменений

### Как воспроизвести

1. Создать новую конфигурацию
2. Добавить два справочника
3. Для одного из справочников добавить реквизит с типом ссылка на другой справочник
4. Создать форму справочника с реквизитом
5. Создать расширение, добавить форму в расширение
6. Создать локальный репозиторий
7. Создать новую ветку
8. В новой ветке установить свойство "Кнопка выбора" для реквизита формы в Да, сохранить форму
9. Наблюдать отсутствие изменений на вкладке "Индексирование Git"
10. Добавить любое изменение в модуле формы, сохранить форму
11. Наблюдать появление изменений на вкладке "Индексирование Git"
12. Зафиксировать коммит с изменениями
13. Переключиться на master
14. Переключиться на вторую ветку
15. Наблюдать сброс свойства "Кнопка выбора" у реквизита

### Ожидаемое поведение

Изменение реквизита "Кнопка выбора" должно фиксироваться как неиндексированное изменение

### Лог рабочей области

[trace.log](https://github.com/1C-Company/1c-edt-issues/files/10660936/trace.log)
[ — копия.log](https://github.com/1C-Company/1c-edt-issues/files/10660941/default.log)

### Версия 1С:EDT

2022.1.5

### Операционная система

Windows

### Установленные плагины

1C:Code style V8, 1C:SSL-support

**Comment by AlmazNasibullin** [comment]
@MoVled Добрый день. Прогнал Ваш сценарий, проблема не воспроизводится, в п. 9 сценария наблюдаю изменения в панели "Индексирование Git". А можешь, пожалуйста, прогнать Ваш сценарий на новом чистом воркспейсе?

**Comment by MoVled** [comment]
Сейчас прогнал ещё раз - изменения начали отображаться. Хотя ранее я тоже создавал новый проект..
Но это не меняет ситуации: если зафиксировать изменения, переключиться на ветку master, а потом обратно - кнопка пропадает
![кнопка ещё есть](https://user-images.githubusercontent.com/90936490/218109946-88ce9284-2bd9-4b09-84a8-e8338cc3539e.png)
![кнопка пропала](https://user-images.githubusercontent.com/90936490/218109972-35b884ae-72f1-4370-8fc6-a328a2ff2c93.png)
![свойство у реквизита](https://user-images.githubusercontent.com/90936490/218109991-724ffe77-e438-4d6a-b821-84ed20c84f04.png)

**Comment by vadimeg** [comment]
Посмотрю проблему в ближайшее время

**Comment by vadimeg** [comment]
Исправлено в 2023.1
