### ISSUE TITLE
Некорректно импортируется подпись мобильного клиента.

### ISSUE THREAD

**Issue by mrshadow300373** [1C-Company/1c-edt-issues#860]
### Описание ошибки

После импорта ИБ (ERPУХ 3.1.8.10 / 8.3.21.1674) в проект (конфигурация новая, только что созданная из шаблона) при первом запуске получил сообщение (1):
![03-02-2023 13-46-01](https://user-images.githubusercontent.com/34220218/216900252-824430cd-1f9d-4bae-9495-072ab1ad786f.jpg)
Естественно ни перезаписать не импортировать я в такой ситуации не могу. Фокус с принудительной синхронизацией https://infostart.ru/1c/articles/1197800/ тоже не прошёл. При попытке запуска/отладки всё равно получаю такое сообщение (1), о том, что подпись мобильного клиента была изменена... Ситуацию смог исправить только тогда, когда снял конфигурацию с поддержки и в конфигураторе (штатными средствами через настройку поддержки), и в EDT (удалил файл Configuration/ParentConfiguration.bin) привязал принудительно, очистил в EDT подпись мобильного клиента и при запуске, при появлении сообщения (1) выбрал перезаписать. После чего диалоговое окно более не появлялось.

### Как воспроизвести

1. Создать из шаблона ИБ ERPУХ 3.1.8.10 / 8.3.21.1674
2. Импортировать в проект. 
2.1 Я шел по своему варианту (Конфигуратор/Выгрузить в файлы/На сервере, в папку, 7 потоков) EDT импортировать проект из XML, затем привязать принудительно через подмену ComfigDumpInfo.xml и файла store, 
2.2. Однако и при штатном импорте из панели ИБ в панель Навигатора 1С поведение далее точно такое же. Проверил специально, скрин см. ниже
3. Запустить проект на выполнение/отладку увидеть сообщение (1) (см. описание ошибки)

### Скриншоты

![image](https://user-images.githubusercontent.com/34220218/216933536-a029ba0b-099a-4da4-828d-00b5a755cc33.png)

### Ожидаемое поведение

После импорта конфигурации на замке не появляется сообщение (1) см. описание ошибки, или в разделе "Скриншоты"

### Лог рабочей области

[Logs.zip](https://github.com/1C-Company/1c-edt-issues/files/10661526/Logs.zip)

### Версия 1С:EDT

2022.1.5

### Операционная система

Windows

### Дополнительная информация

При обходе через снятие с поддержки проблема полностью не снимается, а лишь переходит в иное состояние:
1. При подтверждении перезаписать подпись мобильного клиента из проекта EDT конфигурация обновляется, но конфигурация ИБ - нет <!> в заголовке дерева метаданных конфигурации. После запуска БСП периодически сообщает, о том, что конфигурация ИБ не соответствует конфигурации. 
2. Если зайти в конфигуратор, и принять изменения, затем закрыть конфигуратор, то после попытки запуска снова получаю сообщение (1)

Замкнутый круг.

Если выбираю импортировать, получаю такую картину:
![image](https://user-images.githubusercontent.com/34220218/216969043-1843d621-ba9a-4694-b6d7-bfbc2a2d4b07.png)
Ощущение, что в EDT это свойство просто пустое.

После переноса изменений в конфигурацию последующая сборка проходит корректно

**Comment by mrshadow300373** [comment]
[MobileClientSignature.zip](https://github.com/1C-Company/1c-edt-issues/files/10690455/MobileClientSignature.zip)
@MaksimDzyuba  файл, как обещал. Но он выглядит нормальным, возможно при конвертации в EDT что то происходит.

**Comment by MaksimDzyuba** [comment]
Здравствуйте, расследовал. Причина в том, что платформа меняет ConfigDumpInfo именно на подписи мобильного клиента при каждом обращении EDT. Зарегистрировал критичную ошибку на платформу. Так как воспроизвести ошибочное поведение можно и без EDT, просто переоткрывая конфигуратор и выгружая конфигурацию в xml. Каждый раз будут отличия в ConfigDumpInfo, хотя изменений не производилось. Как только платформа починит ошибку, подниму минимальную версию платформы, с которой можно работать из EDT, тогда и закрою ошибку

**Comment by mrshadow300373** [comment]
> Причина в том, что платформа меняет ConfigDumpInfo именно на подписи мобильного клиента при каждом обращении EDT.

У меня есть ещё другие конфигурации на этой же платформе (8.3.21.1674) на замке, которые импортировались без проблем. Например УХ (3.1.17.29). В обоих случаях подписи мобильного клиента нет - она пустая... 
В любом случае ждём результатов исправления по платформе.

**Comment by MaksimDzyuba** [comment]
да, я попробовал сделать малый пример, с такой пустой подписью, как в той базе, что у Вас. Не повторилось поведение , все было корректно. а вот на ЕРП УХ, что Вы привели, воспроизвелось, я платформе отправил именно эту базу для анализа, то есть там не совсем дело в файле, какое-то еще внутреннее состояние в базе похоже есть, но тут я ничего подробнее сказать не могу, так как не обладаю достаточной информацией

**Comment by MaksimDzyuba** [comment]
Здравствуйте, проверил исправление платформы, их ошибка 60005806, исправлена, исправления появятся от сборки 8.3.21.1748. Ошибку закрываю, так как на этой сборке у меня проблема не воспроизвелась больше
