### ISSUE TITLE
Невозможно удалить добавленный реквизит находящегося на поддержке объекта метаданных с возможностью редактирования

### ISSUE THREAD

**Issue by adminimusRU** [1C-Company/1c-edt-issues#867]
### Описание ошибки

Если установить объекту метаданных режим "Редактируется с сохранением поддержки" (без подчиненных объектов) и добавить новый реквизит, то удалить добавленный реквизит EDT не даст.

### Как воспроизвести

На примере справочника `ОбщиеВнешниеКомпоненты` из демо базы БСП.

1. Ставим в конфигураторе режим "Редактируется с сохранением поддержки" на корень справочника:
![image](https://user-images.githubusercontent.com/28653631/218086663-e6724ee1-f095-47bf-a9e9-980297edde4b.png)
2. Импортируем в EDT.
3. Добавляет в EDT новый реквизит в этот справочник:
![image](https://user-images.githubusercontent.com/28653631/218086680-d3b24664-2d1d-4f47-b962-9cf1c54424d9.png)
4. Пытаемся в EDT удалить добавленный реквизит, получаем ошибку "Удаление объекта запрещено":
![image](https://user-images.githubusercontent.com/28653631/218086783-d9d7cf03-88d1-44c9-b029-e914ef3183aa.png)
 Если в объекте есть формы на поддержке с запретом редактирования (на примере справочника Валюты), то получим еще вторую ошибку "Редактирование объекта FormDataStructure запрещено":
![image](https://user-images.githubusercontent.com/28653631/218087142-6b83a96d-ba8b-4226-9479-8c67b5d6490f.png)
![image](https://user-images.githubusercontent.com/28653631/218086905-7d682a07-6fd8-4f56-b277-d253e18c6496.png)

### Ожидаемое поведение

EDT должно позволять не только добавлять, но и удалять реквизиты в объекты с разрешенным редактированием. Сейчас приходится удалять через конфигуратор или править файлы проекта вручную.

### Лог рабочей области

не требуется

### Версия 1С:EDT

2022.2.3

### Операционная система

Windows

### Установленные плагины

1C:Code style V8, 1C:SSL-support

**Comment by adminimusRU** [comment]
При удалении реквизита конфигуратором, EDT потом не смогло получить список изменений (кроме реквизиты было удалено его упоминание в двух общих модулях) и решило загружать конфигурацию полностью для сравнения, вместе с кучей фантомных изменений. И потом потребовало полную загрузку конфигурации при обновлении приложения.

**Comment by vadimeg** [comment]
Исправлено в 2024.2
