### ISSUE TITLE
При переходе к найденному фрагменту из результатов поиска курсор смещается во всех открытых редакторах

### ISSUE THREAD

**Issue by adminimusRU** [1C-Company/1c-edt-issues#874]
### Описание ошибки

При выборе фрагмента в результатах поиска по конфигурации (двойным кликом или вводом) открывается редактор и в нем подсвечивается выбранный фрагмент. Но при этом во всех открытых редакторах так же подсвечивается фрагмент текста на такой же позиции (судя по всему в символах от начала).

### Как воспроизвести

1. Открыть несколько больших модулей
2. Выполнить поиск по конфигурации
3. Перейти по одному из результатов
4. Во всех открытых модулях курсор так же установится на позицию фрагмента

### Скриншоты

Переход к результату поиска:
![image](https://user-images.githubusercontent.com/28653631/218951668-14845ddb-5b8f-450f-8323-1db74ffd9ace.png)
Курсор сместился в других открытых модулях на аналогичную позицию:
![image](https://user-images.githubusercontent.com/28653631/218951764-c4048ab4-4c4b-464d-92e0-4a800d14d270.png)
![image](https://user-images.githubusercontent.com/28653631/218952021-254e9675-abe1-4e5a-85b7-18f3d199ce12.png)

### Ожидаемое поведение

Переход к найденному фрагменту не должен менять позицию курсора в других редакторах.

### Лог рабочей области

Не требуется.

### Версия 1С:EDT

2022.2.3

### Операционная система

Windows

**Comment by edkuznetsov** [comment]
Актуально для версии Ruby 2022.2.5

**Comment by adminimusRU** [comment]
И даже в 2023.1.0 то же самое, баг жив.

**Comment by tretyakevich** [comment]
Исправлено в 2023.1.2
