### ISSUE TITLE
[1CEDT] Ошибка! потеря кода при переименовании обработки расширения

### ISSUE THREAD

**Issue by EChudnovsky** [1C-Company/1c-edt-issues#875]
```
При переименовании обработки расширения добавленную копированием и проекта внешних отчетов\обработок происходит потеря кодовой базы.

Описание проблематики
1. Имеется два проекта: проект внешнних отчетов обработок и проект расширения конфигурации
2. Из проекта внешних отчетов\обработок переносится обработка. 
Копируется в одном проекте и вставляется в другом проекте
Обработка состоит из формы и модуля формы
3. В проекте расширения, согласно регламента, обработке добавляется префикс.
4. После переименования форма и модуль обработки отображаются корректно (без ошибок и наличия полного объема доработки).
5. При попытке запуска отладки появляется информация ошибка "Произошла ошибка в течение запуска 1С:Предприятия:
Incorrect owner: null"
6. После пере открытия проекта расширения модуля формы оказывается пустым.

 
Лог и скриншот результата переименования ниже

Product name: 1C:Enterprise Development Tools
Product version: 1.27.3.24
Java home: C:\Program Files\BellSoft\LibericaJDK-11-Full
Java vm name: OpenJDK 64-Bit Server VM
Java vm info: mixed mode
Java version: 11.0.12
Java vendor: BellSoft
OS: win32
Total mem: 17 179
Free mem: 12 418
Cores: 16
***********************************
*	Файлы, приложенные к задаче, отправлены разработчикам. Ссылка в задаче не отображается./t*
***********************************
```

**Comment by EChudnovsky** [comment]
Лог файл: [log.zip](https://github.com/1C-Company/1c-edt-issues/files/10755173/log.zip)

Результат переименования 

![изображение](https://user-images.githubusercontent.com/5530435/219351768-9da25046-1b6d-4cf9-8394-6824fdadfb2f.png)

**Comment by EChudnovsky** [comment]
На релизе edt Ruby 2022.2.3 при любом варианте переименования обработки теряется код разработки: не переносится модуль формы в переименованный объект. 

Ошибка является критической, т.к. происходит потеря функциональности.

**Comment by vadimeg** [comment]
Исправлено в 2022.2.4

**Comment by AndreyKors** [comment]
Ошибка ее присутствует 
Версия 2022.2.5. Проект расширения.
В дереве проекта копируем обработку. В дереве появляется новый объект - например Обработка1. Папка в src\DataProcessors\Обработка1 появилась  - тут все ок.
Теперь переименовываем обработку в Обработка2. Появляется папка src\DataProcessors\Обработка2 в которой нет модуля форм и модуля менеджера. При этом остается папка src\DataProcessors\Обработка1 в которой какраз недостающие файлы с модулями.
