### ISSUE TITLE
[1CEDT] Ошибка LayoutProblem null в редакторе форм расширения под Linux в edt Ruby 2022.2.3.

### ISSUE THREAD

**Issue by EChudnovsky** [1C-Company/1c-edt-issues#883]
```
В релизе edt Ruby 2022.2.3 вернулась ошибка LayoutProblem null при отображения форм расширения в ОС Linux.
Связанное issue: #608

**Параметры ОС Windows:**
Product name: 1C:Enterprise Development Tools
Product version: 1.27.3.24
Java home: C:\Program Files\BellSoft\LibericaJDK-11-Full
Java vm name: OpenJDK 64-Bit Server VM
Java vm info: mixed mode
Java version: 11.0.12
Java vendor: BellSoft
OS: win32
Total mem: 17 179
Free mem: 9 540
Cores: 16

**Параметры ОС Linux:**
Product name: 1C:Enterprise Development Tools
Product version: 1.27.3.24
Java vm name: OpenJDK 64-Bit Server VM
Java vm info: mixed mode
Java version: build 11.0.12+7-LTS
Java vendor: BellSoft
OS: linux Ubuntu Ubuntu 20.04.3 LTS (focal)
Total mem: 96567
Free mem: 26672
Cores: 12



***********************************
*	Файлы, приложенные к задаче, отправлены разработчикам. Ссылка в задаче не отображается./t*
***********************************
```

**Comment by EChudnovsky** [comment]
log: 
[log.zip](https://github.com/1C-Company/1c-edt-issues/files/10780135/log.zip)

Доработка выполняется для типовой конфигурации 
ЗУП КОРП 3.1 версия 3.1.23.167.

 Состояние ошибочной формы документа в расширении:
[Отпуск.zip](https://github.com/1C-Company/1c-edt-issues/files/10780206/default.zip)

![изображение](https://user-images.githubusercontent.com/5530435/220026045-5844eb7a-c1db-43bd-a9e0-55ebb442dc1b.png)

**Comment by vadimeg** [comment]
А какая версия платформы? Это ключевая информация для этого бага.

**Comment by vadimeg** [comment]
> Связанное issue: #608

В логе совсем другая ошибка, хотя и пишет то же, что в 608.
Проблема из 608 была исправлена. С этой будем разбираться

**Comment by vadimeg** [comment]
Приложите, пожалуйста, форму из основной конфигурации

**Comment by vadimeg** [comment]
[ERP2.ErpExt.zip](https://github.com/1C-Company/1c-edt-issues/files/10783393/ERP2.ErpExt.zip)
Сделал расширение ERp на основании приложенных файлов форм.
Не знаю, насколько оно соответствует оригиналу.

**Comment by vadimeg** [comment]
@EChudnovsky Можете еще файлы err_pid прислать? Должны появиться после открытия сломанной формы

**Comment by EChudnovsky** [comment]
Используемая версия 1с: 8.3.21.1622.

Документ "Отпуск" из основной конфигурации
[ДокументОсновнойКонфигурации_Отпуск.zip](https://github.com/1C-Company/1c-edt-issues/files/10786966/_.zip)

**Comment by EChudnovsky** [comment]
> 

Я правильно их нашел? 
имеются ввиду hs_err_pid*?

[err_pid.zip](https://github.com/1C-Company/1c-edt-issues/files/10786994/err_pid.zip)

**Comment by vadimeg** [comment]
> > 
> 
> Я правильно их нашел? имеются ввиду hs_err_pid*?
> 
> [err_pid.zip](https://github.com/1C-Company/1c-edt-issues/files/10786994/err_pid.zip)

Да, они, спасибо

**Comment by vadimeg** [comment]
Можете вот по этому пути
/home/e.chudnovsky@1c-ksu.ru/.local/share/1C/1cedtstart/installations/1C_EDT 2022.2/1cedt/configuration/org.eclipse.osgi/257/0/.cp/libs/v8.3.21/

положить приложенный файл (только его надо распаковать, libstdc++.so.6.debug) и еще раз открыть форму, а потом прислать новый hs_err_pid?

[libstdc++.so.6.zip](https://github.com/1C-Company/1c-edt-issues/files/10793495/libstdc%2B%2B.so.6.zip)

**Comment by EChudnovsky** [comment]
контрольный скрин :) :

![изображение](https://user-images.githubusercontent.com/5530435/220540038-6abbba65-3dbc-4199-bed9-befc2f8e56ad.png)

hs_err_pid:

[hs_err_pid1595110.zip](https://github.com/1C-Company/1c-edt-issues/files/10800613/hs_err_pid1595110.zip)

бонус последний лог:

[log.zip](https://github.com/1C-Company/1c-edt-issues/files/10800626/log.zip)
