### ISSUE TITLE
Невозможность запуска приложения из-за "ошибок" в расширении

### ISSUE THREAD

**Issue by Astakhovp** [1C-Company/1c-edt-issues#884]
### Описание ошибки

Для 1С ERP было создано расширение, которое выполняет некоторые действия.
После обновления ERP с версии 2.5.10 на 2.5.11 из EDT невозможно запустить приложение, получаю сообщение об ошибке "(!!)АП_Перемещения (23.02.07.1230): Для заимствованного документа, настройки нумерации которого модифицированы, отключать контролируемость свойства "Нумератор" недопустимо"
Из расширения были удалены все объекты, и все равно выскакивает данная ошибка.
Расширение было удалено, создано новое, пустое. 
В результате ошибка стала выскакивать на следующем расширении.

### Как воспроизвести

1. Перейдите в `...`
2. Кликните по `....`
3. Прокрутите вниз до `....`
4. Смотрите ошибку в `....`

### Ожидаемое поведение

Запуститься с расширениями

### Лог рабочей области

[metadata.zip](https://github.com/1C-Company/1c-edt-issues/files/10782558/metadata.zip)

### Версия 1С:EDT

1CEDT (2022.2.3+24)

### Операционная система

Windows

### Установленные плагины

Нет плагинов, 1C:Code style V8, 1C:SSL-support

**Comment by Astakhovp** [comment]
Как воспроизвести:
1. взять базу 1с ERP с расширениями.
2. Базу обновить до версии 2.5.11
3. Саму конфигурацию ERP можно даже снять с поддержки.
4. Создать в EDT новую рабочую область.
5. Импортировать в него конфигурацию и расширение.
6. После сборки проекта попробовать запустить проект. Получаем ошибку. 

Если надо - само расширение могу приложить.

**Comment by Erik773** [comment]
Здравствуйте, могли бы Вы, пожалуйста, приложить расширение, это позволит быстрее и точнее воспроизвести проблему и понять её причины.

**Comment by Astakhovp** [comment]
[АП_Перемещения_23.02.07.zip](https://github.com/1C-Company/1c-edt-issues/files/10785546/_._23.02.07.zip)
[ERPDevel.АП_Перемещения.zip](https://github.com/1C-Company/1c-edt-issues/files/10785606/ERPDevel._.zip)

Приложены 2 архива.
1. Собранное и работающее расширение, выгруженное из рабочей обновленной базы.
2. Импортированное из базы расширение в виде части проекта на диске. Этот проект отказывается запускаться, ругается на нумератор.

**Comment by Astakhovp** [comment]
Хм, а сегодня по новой стал делать - все заработало без проблем.

**Comment by UstinovGit** [comment]
у меня такая же ошибка, подскажите как исправили
