### ISSUE TITLE
EDT не понимает, что функция вернула ВыборкаИзРезультатаЗапроса, если функция вернула ее через Возврат Запрос.Выполнить().Выбрать()

### ISSUE THREAD

**Issue by VAGoncharov** [1C-Company/1c-edt-issues#888]
### Описание ошибки

Можно описать функцию, которая вернет выборку из результата запроса. Если вернуть выборку сразу через
`Возврат Запрос.Выполнить().Выбрать()`
то EDT не понимает, что функция вернула тип ВыборкаИзРезультатаЗапроса.

В то же время, если возврат функции оформить так
`РезультатЗапроса = Запрос.Выполнить();
Возврат РезультатЗапроса.Выбрать();`
тогда проблем с определением типа нет.

### Как воспроизвести

См. описание ошибки, там достаточно информации

### Ожидаемое поведение

EDT понимает, какой тип вернула конструкция Запрос.Выполнить().Выбрать() без промежуточного кода.

### Лог рабочей области

-

### Версия 1С:EDT

Ruby 2022.1.5

### Операционная система

Windows

### Установленные плагины

1C:Code style V8, 1C:SSL-support

**Comment by adminimusRU** [comment]
На 2022.2.3 всё работает
```bsl
Функция ВызываемаяФункция()
	
	Запрос = Новый Запрос;
	Запрос.Текст = "";
	Возврат Запрос.Выполнить().Выбрать();
	
КонецФункции

Процедура Процедура1()
	
	Выборка = ВызываемаяФункция();
	
	Пока Выборка.Следующий() Цикл
		// ...
	КонецЦикла;
	
КонецПроцедуры
```
![image](https://user-images.githubusercontent.com/28653631/220266617-5da2bee1-c9c5-41c9-8e6e-379aa513f2ac.png)

Возможно у вас какие-то дополнительные вещи в коде ломают типизацию. Например сам запрос хитро конструируется.
Либо просто парсер поймал ошибку и сломался, такое бывает, лечится перезапуском проверки или всей едт.

**Comment by VAGoncharov** [comment]
Запрос в коде предельно простой, как у вас на скриншоте. 
Проверю 2022.2.3, если там не воспроизведется, закрою ишуз.

**Comment by adminimusRU** [comment]
На 2021.3.4 тоже работает нормально. Скорее всего у вас локально что-то поломалось, обычно в таких случаях в журнале ошибок пачка записей вида `Language check thrown an exception`
