### ISSUE TITLE
Не высчитывается тип ОбработкаТабличнаяЧастьСтрока.ИмяОбработки.ИмяТЧ

### ISSUE THREAD

**Issue by RedMammoth** [1C-Company/1c-edt-issues#889]
### Описание ошибки

Если создать табличную часть обработки, то ЕДТ знает о типе ОбработкаТабличнаяЧастьСтрока.ИмяОбработки.ИмяТЧ, однако если выполнить очистку проекта или реимпорт, то выдает ошибка, что тип неизвестен (валидация в CI в таком случае генерит ложные ошибки).

Если обработку модифицировать, то типы снова рассчитаются, но основная проблема в CI, он всегда выдает ложные ошибки на этот тип.

### Как воспроизвести

Архив с проектом:
[Конфигурация.zip](https://github.com/1C-Company/1c-edt-issues/files/10790753/default.zip)

### Скриншоты

![image](https://user-images.githubusercontent.com/64589646/220276552-496875de-9444-4a60-bbcc-5687ec7c63e9.png)

### Ожидаемое поведение

Тип рассчитывается при очистке/реимпорте

### Лог рабочей области

-

### Версия 1С:EDT

2022.2.3

### Операционная система

Windows, Linux

### Установленные плагины

1C:Code style V8, 1C:SSL-support, 1C:Language Tool

**Comment by MaksimDzyuba** [comment]
Будет исправлено в  2023.1 (есть вероятность, что войдет и в 2022.2)
