### ISSUE TITLE
Не срабатывает подавление проверок с помощью комментария skip-check

### ISSUE THREAD

**Issue by maalssy** [1C-Company/1c-edt-issues#89]
### Описание ошибки

При добавлении комментария для подавления проверки, встроенная проверка по-прежнему срабатывает.

### Как воспроизвести

Добавьте в код неиспользуемую переменную и напишите комментарий для подавления ошибки:
// @skip-check module-unused-local-variable - потому что
Тест = "";

### Скриншоты

![image](https://user-images.githubusercontent.com/57713524/141420609-967d8872-a1e0-4067-9c57-0ca52c331727.png)

### Ожидаемое поведение

Ошибки проверки не должно быть.

### Лог рабочей области

[logs.zip](https://github.com/1C-Company/1c-edt-issues/files/7525324/logs.zip)

### Версия 1С:EDT

2021.2.9

### Операционаня система

Windows

### Установленые плагины

Другие сторонние плагины `Название плагина...`

### Дополнительная информация

Установлен плагин https://otymko.github.io/bslls-connector-for-edt/update/bslls-connector-for-edt/latest

**Comment by DmitryShvaika** [comment]
вроде дубль 
https://github.com/1C-Company/1c-edt-issues/issues/49

**Comment by maalssy** [comment]
> вроде дубль #49

Мне в телеге написали, что надо новую issue создавать.

**Comment by vadimeg** [comment]
Исправлено в 2021.3
