### ISSUE TITLE
У заимствованного объекта невозможно установить права на стандартные реквизиты

### ISSUE THREAD

**Issue by petypen** [1C-Company/1c-edt-issues#893]
### Описание ошибки

У объектов конфигурации, например у справочника, есть стандартные реквизиты. При конфигурировании роли, иногда нужно устанавливать права стандартными реквизитам объекта.
Если объект заимствовать в расширение, то при конфигурировании роли невозможно установить права на стандартные реквизиты, так как они отсутствуют в настройке прав.

### Как воспроизвести

На примере справочника "Пользователи".
Настройка прав на справочник в основной конфигурации. Видим, что есть стандартные реквизиты и для них можно настроить права.

![2023-02-28_21-04-11](https://user-images.githubusercontent.com/6500075/221940877-a0ce0bc9-8af8-4e04-a418-c0851153fe83.png)

Далее справочник "Пользователи" был заимствован в расширение. Так же в расширении была создана новая роль "PEN007_Роль", в которую добавлен заимствованный справочник. Видно, что в окне настройки прав отсутствует возможность указать права на стандартные реквизиты.

![2023-02-28_21-08-13](https://user-images.githubusercontent.com/6500075/221941992-4a5db399-0951-4652-b270-10c4eaf5945b.png)

Так же в самом заимствованном справочнике стандартные реквизиты так же не отображаются.

![2023-02-28_21-10-46](https://user-images.githubusercontent.com/6500075/221942562-eea1a83d-d0b0-4d03-aca3-e1c0970ad880.png)

Важно! Конфигуратор ведет себя так ка ожидается. На скриншоте открыта роль созданная в расширении. В роль добавлен заимствованный справочник "Пользователи". Конфигуратор дает возможность установить права на стандартные реквизиты.

![2023-02-28_21-21-56](https://user-images.githubusercontent.com/6500075/221944958-44ac9d6a-d5b5-46bf-b24c-123726b7d3d3.png)

### Ожидаемое поведение

У объекта, заимствованного в расширение, стандартные реквизиты должны быть доступны для установки прав

### Лог рабочей области

[metadata.zip](https://github.com/1C-Company/1c-edt-issues/files/10853652/metadata.zip)

### Версия 1С:EDT

Ruby 2022.2.3

### Операционная система

Windows

### Дополнительная информация

Платформа: 8.3.20
конфигурация: Конвертация данных 3.1

**Comment by petypen** [comment]
Если расширение конфигурации доработать в конфигураторе, а именно в новой роли установить права стандартным реквизитам и далее загрузить такое расширение в ЕДТ, то в ЕДТ в файле Rights.rights появятся необходимые узлы.

![2023-03-01 10-23-01 hrmws - ИИТ002_ЗУП src Roles ИИТ002_ДобавлениеИзменениеПереносДанных Rights rights - 1C Enterprise Deve](https://user-images.githubusercontent.com/6500075/222071911-4197679e-5574-4b64-9f5e-333158419d1e.png)

Однако, в форме установки прав стандартные реквизиты так и не появились.

![2023-03-01 10-28-41 hrmws - ИИТ002_ЗУП→Общие→Роли→ИИТ002_ДобавлениеИзменениеПереносДанных - 1C Enterprise Development Tools](https://user-images.githubusercontent.com/6500075/222072385-e6302798-67f7-4b7f-839b-6545a3122075.png)

**Comment by AlmazNasibullin** [comment]
Добрый день.
Ошибка недоступности настройки прав на стандартные реквизиты заимствованного объекта исправлена в версии 2023.1. Список стандартных реквизитов в навигаторе и редакторе заимствованного объекта не отображается по аналогии с конфигуратором.
