### ISSUE TITLE
При мерже с веткой в которой есть удаленные объекты в ветке получателе объект удаляется не полностью

### ISSUE THREAD

**Issue by Dumsik** [1C-Company/1c-edt-issues#896]
### Описание ошибки

Версия edt 2022.2.3
Операционная система windows x64
если мы мержим нашу ветку с веткой где есть удаленные объекты (справочники, документы), то мы ожидаем что у нас тоже объект удалиться при мерже, но объект удаляется не полностью.  Файл mdo удаляется, а формы и bsl объекты остаются. также остается информация об объекте в файле configuration.mdo. 
Такое поведение процедуры мержа проявляется только в случае если при мерже edt вызывает процедуру сравнения объединения. В окне сравнения веток видно, что объект должен быть удален (он отмечен галочкой и стоит пиктограмма удаления), но после мержа часть объекта остается.  
Пример состояния проекта после такого некоректного  мержа 
![image_2023-03-03_14-54-48](https://user-images.githubusercontent.com/24560572/222707669-681e096f-9b9a-489b-9d4d-1eea3be38d22.png)

### Как воспроизвести

1.Создать несколько объектов (документов справочников) в ветке мастер и сделать комит
2. Создать новую ветку test и вней сделать несколько произвольных комитов любых
3. переключиться назад на ветку мастер и сделать в ней  несколько комитов  и один комит в котором удалить документы и справорчники существущие в ветке test
4. переключиться на ветку test и сделать мерж с веткой мастер. 
5. проверить что стало с объектами удаленными в ветке мастер

### Ожидаемое поведение

При мерже ветки с веткой где есть удаленные объекты которые есть также и в ветке получателе объект корректно удаляется в ветке получателе.

### Лог рабочей области

нет

### Версия 1С:EDT

2022.2.3

### Операционная система

Windows

### Установленные плагины

1C:Code style V8, 1C:SSL-support, 1C:Language Tool

**Comment by AlmazNasibullin** [comment]
Исправление будет перенесено в версию 2022.2.
