### ISSUE TITLE
Парсер модуля падает прекращает разбор на такой конструкции и дальше показывает весь код как некорректный

### ISSUE THREAD

**Issue by tormozit** [1C-Company/1c-edt-issues#897]
### Описание ошибки

Парсер модуля падает прекращает разбор на конструкции 
```
#Если Сервер И Не Сервер Тогда
	&НаСервере
#Иначе
	&НаКлиентеНаСервереБезКонтекста
#КонецЕсли
```
Дальше показывает весь код как некорректный. В конфигураторе проблемы нет.

### Как воспроизвести

Перед любым непоследним методом модуля написать
```
#Если Сервер И Не Сервер Тогда
	&НаСервере
#Иначе
	&НаКлиентеНаСервереБезКонтекста
#КонецЕсли
```
Текущий и следующие методы станут целиком подчеркнуты красными линиями. Попробовать в начале модуля написать  
//@skip-check code-never-compilied
//@skip-check org.eclipse.xtext.diagnostics.Diagnostic.Syntax
Проблема не исчезает.

### Скриншоты

![изображение](https://user-images.githubusercontent.com/11896251/223113565-eeb01ad8-9155-4f43-942b-7e07d787f2c6.png)

### Ожидаемое поведение

Корректная обработка корректной конструкции препроцессора. Или хотя бы нужен способ подавать проверку такого модуля, а лучше такого метода/фрагмента.

### Лог рабочей области

я

### Версия 1С:EDT

Ruby 2022.2.2

### Операционная система

Windows

**Comment by adminimusRU** [comment]
Я правильно понимаю, что это написанные под конфигуратор костыли для удобства и их можно смело удалять?

**Comment by tormozit** [comment]
@adminimusRU нет. Верно только "это написанные под конфигуратор костыли для удобства"

**Comment by Erik773** [comment]
Задача закрывается, так как данное поведение является ограничением EDT и в ближайшее время не будет изменено.

**Comment by tormozit** [comment]
Отразил эту ошибку в статье https://infostart.ru/1c/articles/671436/

**Comment by marmyshev** [comment]
Дубль #29

**Comment by JaneGlass73** [comment]
Печально что закрывается... Потому что сильно актуально
https://github.com/1C-Company/1c-edt-issues/issues/1475#issuecomment-2564812112
