### ISSUE TITLE
Ложное срабатывание проверки transfer-object-between-client-server на объекте СтандартныйПериод

### ISSUE THREAD

**Issue by adminimusRU** [1C-Company/1c-edt-issues#899]
### Описание ошибки

При передаче объекта типа СтандартныйПериод с клиента на сервер ложно срабатывает проверка transfer-object-between-client-server: 
`Нельзя передавать объект типа 'СтандартныйПериод' между клиентом и сервером [Тонкий клиент, Толстый клиент (управляемое приложение), Web-клиент]`

### Как воспроизвести

```bsl
&НаКлиенте
Процедура КлиентскийМетод() Экспорт
	
	Период = Новый СтандартныйПериод();
	СерверныйМетод(Период);
	
КонецПроцедуры

&НаСервереБезКонтекста
Процедура СерверныйМетод(Период)
	
	Период.ДатаНачала = Период.ДатаОкончания;
	
КонецПроцедуры
```

### Скриншоты

![image](https://user-images.githubusercontent.com/28653631/223946150-48162c87-8938-4780-89db-a7076df5470f.png)

### Ожидаемое поведение

Ошибка не выводится - передача такого объекта между клиентом и сервером корректно работает на платформе 8.3.22.

### Лог рабочей области

не требуется

### Версия 1С:EDT

2022.2.3

### Операционная система

Windows

**Comment by MaksimDzyuba** [comment]
Исправлено, войдет в 2023.2
