### ISSUE TITLE
Добавление строки перед ключевыми словами "процедура" и "функция" работает некорректно

### ISSUE THREAD

**Issue by KovAlexey** [1C-Company/1c-edt-issues#900]
### Описание ошибки

При добавлении переноса строк в начало строки объявления функции или процедуры добавляется ненужный TAB

### Как воспроизвести

1. Открыть модуль с функциями
2. Встать в начало строки объявления функции
3. Нажать enter - т.е. добавить перенос строки

### Скриншоты

https://user-images.githubusercontent.com/16429518/223959070-08091a19-765b-4b16-8a7d-8b9250e96725.mp4

### Ожидаемое поведение

Перенос строки с сохранением текущего форматирования

### Лог рабочей области

Не нужен

### Версия 1С:EDT

2021.1.5

### Операционная система

Windows

### Установленные плагины

1C:Code style V8, 1C:SSL-support

### Дополнительная информация

Проблема наблюдается и на более свежей

**Comment by MaksimDzyuba** [comment]
Здравствуйте, поправил, спасибо!
![bandicam 2023-03-31 13-36-53-714](https://user-images.githubusercontent.com/77277424/229098353-fadf7987-2282-40e6-972e-94f0ec1c2449.gif)
