### ISSUE TITLE
Дьявольски медленная отладка в формах средняя скорость 1,25 МИНУТ/строка

### ISSUE THREAD

**Issue by mrshadow300373** [1C-Company/1c-edt-issues#904]
### Описание ошибки

Ошибка в том что просто невозможно отлаживать приложение встроенным отладчиком! По минуте висит на каждом шаге.
Видео ниже.

### Как воспроизвести

1. Импортируйте демо базу ERP Управление холдингом 3.1.10.8
2. Установить точки прерывания на строках формы документа ЗаявкаНаРасходокваниеДенежныхСредств: 3280, 3496
3. Создайте новый документ "Заявка на оплату"
4. Будет как на видео:
https://user-images.githubusercontent.com/34220218/224664098-60afc843-80de-4591-961c-a7abc449ff38.mp4

### Скриншоты

Не требуются видео проблемы выше.

### Ожидаемое поведение

Аналогично, так же база, те же точки прерывания в конфигураторе: 20 секунд! Против 4:45 в EDT:
https://user-images.githubusercontent.com/34220218/224664472-64778c49-1945-45fc-ab98-8cce53ce8c17.mp4

### Лог рабочей области

[Logs.zip](https://github.com/1C-Company/1c-edt-issues/files/10955810/Logs.zip)

### Версия 1С:EDT

2022.2.4

### Операционная система

Windows

### Дополнительная информация

Платформа: клиент - сервер 8.3.21.1674 х64 Сервер Linux Ubuntu 20.02 WSL, СУБД Postgres Pro 1c-13, Клиент Windows 10 КОРП 22H2
Настройки кучи в EDT -xmx14g
ПК Core i7, 48 Gb RAM, SSD NVRAM 1,2/0,9 Гб/с чтение/запись

**Comment by DmitryBelov-e1c** [comment]
Проблема связана с некорректной работой с файлом индекса и работой поиска в нём - приводит к "зависаниям" во время отладки. На текущий момент по плану исправление попадает в 2023.1, в случае необходимости (например, проблем с выпуском новой версии) будет перенесено в 2022.2.

**Comment by DmitryBelov-e1c** [comment]
Произведена проверка и замеры производительности в 2023.1, скорость переходов по шагам стабильно высокая.
