### ISSUE TITLE
Изменение порядка языков при редактировании синонимов

### ISSUE THREAD

**Issue by AlexeyPoltavets** [1C-Company/1c-edt-issues#906]
### Описание ошибки

Есть конфигурация с несколькими языками интерфейса.
Ошибка состоит в том, что при редактировании значения синонима на каком-то языке ЕДТ изменяет порядок языков синонимов. Это приводит к тому, что в ГИТ попадают изменения всех синонимов, при том, что фактически изменилось только одно значение. Другими словами, при редактировании значений синонимов, их порядок не должен изменяться.
Небольшой видео-комментарий по проблеме - по ссылке https://drive.google.com/file/d/1pmt4l4-TyDJEHR_yHhJXrxUpS38_nfI3/view?usp=share_link

### Как воспроизвести

1. Открываем конфигурацию, в которой есть несколько языков 
2. Открываем свойства объекта, который имеет синонимы
3. Открываем форму редактирования синонимов и изменяем синоним для одного языка
4. Сохраняем изменения
5. Смотрим изменения в локальном гите 

Проблема в том, что при изменении значения для синонима на одном языке, порядок строк синонимов на разных языках изменился

### Ожидаемое поведение

При изменении синонимов в ЕДТ порядок строк разных языков не должен изменяться или же порядок строк должен определяться чем-то, например, порядком языков в конфигурации и это правило должно быть глобальным, как для ЕДТ, так и для конфигуратора. Это необходимо, что бы избежать изменения порядка строк при загрузке из конфигуратора.

### Лог рабочей области

[trace.log](https://github.com/1C-Company/1c-edt-issues/files/10969718/trace.log)
[1.log](https://github.com/1C-Company/1c-edt-issues/files/10969753/1.log)

### Версия 1С:EDT

2022.2.4

### Операционная система

Windows

### Установленные плагины

1C:Language Tool

**Comment by beg7** [comment]
Не связано с это проблемой. из записи в логе видно что EDT не может прочитать настройки Динамического списка.
Файл: /resource/CloudOffice/src/Documents/ProductionOrder/Forms/ListForm/Attributes/List/ExtInfo/ListSettings/Schema.dcss 
Если для вас не составит труда прикрепите к комментарию этот файл или в крайнем случае первые 5 строк.
