### ISSUE TITLE
Некорректно выгружается пустая ссылка в значении списка выбора

### ISSUE THREAD

**Issue by adminimusRU** [1C-Company/1c-edt-issues#913]
### Описание ошибки

Если в списке выбора элемента формы задать пустое значение, то вместо пустой ссылки в конфигурацию будет выгружено некорректное пустое значение.

В частности это приводит к некорректной работе поля переключателя: элемент с пустой ссылкой не выделяется при выборе.

### Как воспроизвести

1. Добавить поле переключателя на форму, привязать к реквизиту ссылочного типа
2. В список выбора поля добавить элемент, заполнить синоним, значение оставить пустым
3. Добавить еще одно поле выбора, в списке значений указать любое не пустое

### Скриншоты

![image](https://user-images.githubusercontent.com/28653631/225873573-bb6f8342-ec8f-47bc-8e1e-f1ea2b304304.png)
![image](https://user-images.githubusercontent.com/28653631/225873601-62f9e855-2938-4b16-9d54-ee772e38a2d8.png)
Некорректное отображение выбранного переключателя:
![image](https://user-images.githubusercontent.com/28653631/225873809-f4499b2b-a5a9-416a-8bc4-b1a34ceb5888.png)
После исправления через конфигуратор:
![image](https://user-images.githubusercontent.com/28653631/225874314-ccf890d3-6dc2-48a3-a0a6-4cfda32c84c6.png)

### Ожидаемое поведение

Пустое значение для ссылочного реквизита должно выгружаться пустой ссылкой.
Список выбора в проекте EDT:
```xml
<extInfo xsi:type="form:RadioButtonsFieldExtInfo">
  <choiceList>
	<presentation>
	  <key>ru</key>
	  <value>пустая ссылка</value>
	</presentation>
  </choiceList>
</extInfo>
```
Список выбора в проекте EDT после исправления конфигуратором и иморта:
```xml
<extInfo xsi:type="form:RadioButtonsFieldExtInfo">
  <choiceList>
	<presentation>
	  <key>ru</key>
	  <value>пустая ссылка</value>
	</presentation>
	<value xsi:type="core:ReferenceValue">
	  <value>Enum.Перечисление1.EmptyRef</value>
	</value>
  </choiceList>
</extInfo>
```

Поле в выгрузке конфигурации из EDT:
```xml
<RadioButtonField name="Реквизит2пустоезначение" id="7">
	<DataPath>Объект.Реквизит2</DataPath>
	<TitleLocation>None</TitleLocation>
	<RadioButtonType>Auto</RadioButtonType>
	<ChoiceList>
		<xr:Item>
			<xr:Presentation/>
			<xr:CheckState>0</xr:CheckState>
			<xr:Value xsi:type="FormChoiceListDesTimeValue">
				<Presentation>
					<v8:item>
						<v8:lang>ru</v8:lang>
						<v8:content>пустая ссылка</v8:content>
					</v8:item>
				</Presentation>
			</xr:Value>
		</xr:Item>
	</ChoiceList>
	<ContextMenu name="Реквизит2пустоезначениеКонтекстноеМеню" id="8"/>
	<ExtendedTooltip name="Реквизит2пустоезначениеРасширеннаяПодсказка" id="9"/>
</RadioButtonField>
```

Поле в выгрузке конфигурации из конфигуратора:
```xml
<RadioButtonField name="Реквизит2пустоезначение" id="7">
	<DataPath>Объект.Реквизит2</DataPath>
	<TitleLocation>None</TitleLocation>
	<RadioButtonType>Auto</RadioButtonType>
	<ChoiceList>
		<xr:Item>
			<xr:Presentation/>
			<xr:CheckState>0</xr:CheckState>
			<xr:Value xsi:type="FormChoiceListDesTimeValue">
				<Presentation>
					<v8:item>
						<v8:lang>ru</v8:lang>
						<v8:content>пустая ссылка</v8:content>
					</v8:item>
				</Presentation>
				<Value xsi:type="xr:DesignTimeRef">Enum.Перечисление1.EmptyRef</Value>
			</xr:Value>
		</xr:Item>
	</ChoiceList>
	<ContextMenu name="Реквизит2пустоезначениеКонтекстноеМеню" id="8"/>
	<ExtendedTooltip name="Реквизит2пустоезначениеРасширеннаяПодсказка" id="9"/>
</RadioButtonField>
```

### Лог рабочей области

не требуется

### Версия 1С:EDT

2022.2.3

### Операционная система

Windows

### Дополнительная информация

Воспроизводится на проектах платформы 8.3.21.1709, 8.3.22.1851

**Comment by vadimeg** [comment]
Добрый день! Если не сложно, можете прикрепить к багу простой пример в виде cf или dt? Т.е. просто создать простой пример в конфигураторе. Просто в выгрузке фигурирует кастомное перечисление, про которое в баге ничего не говорится: **Перечисление1.EmptyRef**

**Comment by adminimusRU** [comment]
Воркспейс EDT с исходным проектом с ошибкой, проблемная форма в обработке `Обработка1`:
[edt proj before.zip](https://github.com/1C-Company/1c-edt-issues/files/11075405/edt.proj.before.zip)

Проект EDT после исправления формы в конфигураторе:
[edt proj after.zip](https://github.com/1C-Company/1c-edt-issues/files/11075408/edt.proj.after.zip)

Выгрузки проекта в XML файлы конфигурации из EDT и из конфигуратора:
[from edt.zip](https://github.com/1C-Company/1c-edt-issues/files/11075426/from.edt.zip)
[from cf.zip](https://github.com/1C-Company/1c-edt-issues/files/11075438/from.cf.zip)

**Comment by vadimeg** [comment]
Исправлено в 2023.1
