### ISSUE TITLE
Необоснованный запрет использования объединений в запросах динамических списков.

### ISSUE THREAD

**Issue by mrshadow300373** [1C-Company/1c-edt-issues#916]
### Описание ошибки

Ошибка в том что не получается сохранить настройку СКД динамического списка, если в ней присутствует запрос, например временная таблица, не использующая основную (главную таблицу динамического списка) с использованием конструкции ОБЪЕДИНИТЬ [ВСЕ]
В случае, если такая конструкция присутствует по возникает сообщение, которое нельзя обойти:
![image](https://user-images.githubusercontent.com/34220218/226431736-a7bb2e4c-1cd6-4597-ace0-c1a088fc88e7.png)

### Как воспроизвести

1. Открыть распаковать тестовый проект, открыть дин список справочника
[TEST.zip](https://github.com/1C-Company/1c-edt-issues/files/11021876/TEST.zip)
2. Вставить и попытаться сохранить СКД с запросом:
```sql
ВЫБРАТЬ
	1 А
ПОМЕСТИТЬ Фильтр
ОБЪЕДИНИТЬ ВСЕ
ВЫБРАТЬ
	2
ОБЪЕДИНИТЬ ВСЕ
ВЫБРАТЬ
	3
;
ВЫБРАТЬ 
       Справочник.Ссылка, 
       Справочник.ПометкаУдаления, 
       Справочник.Код, 
       Справочник.Наименование, 
       Справочник.Предопределенный, 
       Справочник.ИмяПредопределенныхДанных
 ИЗ 
       Справочник.Справочник
 КАК 
       Справочник
 ГДЕ
 	Справочник.Код В (ВЫБРАТЬ * ИЗ Фильтр)
```
3. Получить ошибку:
![image](https://user-images.githubusercontent.com/34220218/226435212-0eebaf2a-a8f5-4ca7-8440-812105b9aa36.png)

### Ожидаемое поведение

Не смотря на то, что в некоторых случаях объединения в запросах динамического списка действительно недопустимы, нужно либо точно диагностировать случаи, когда это недопустимо и может привести к фатальным ошибкам во время исполнения, либо оставить разработчику решение самостоятельно определить допустимость и корректность запроса для динамического списка. 

### Лог рабочей области

Не требуется

### Версия 1С:EDT

2022.2.4

### Операционная система

Windows, Linux

### Дополнительная информация

В конфигураторе указанный запрос без проблем вставляется и корректно работает. Инструкций по запрету использования объединения в запросах динамических списков не нашёл.
Режим совместимости 8.3.21 (отключен).

**Comment by MaksimDzyuba** [comment]
Здравствуйте, починили, войдет точно в 2023.1, может и в 2022.2, если будет еще выпуск
![bandicam-2023-03-21-09-44-55-524](https://user-images.githubusercontent.com/77277424/226536955-9270ab79-1c37-4718-b397-779c0362fef6.gif)
