### ISSUE TITLE
Служебный комментарий, отключающий форматирование блока кода

### ISSUE THREAD

**Issue by RedMammoth** [1C-Company/1c-edt-issues#917]
### Описание проблемы

При форматировании кода в различных IDE очень часто встречается сценарий, когда форматирование применяется автоматически при сохранении модуля.
Сейчас автоматического форматирования при сохранении вроде нет, но я периодически при написании кода запускаю форматирование на весь модуль, чтобы не упустить забытый участок. Но если какие-то блоки я форматирую вручную, для повышения читаемости, то после применения автоформата на весь модуль они ожидаемо слетают.

Для таких сценариев популярным решением является наличие служебных комментариев или прочих языковых конструкций, позволяющих сохранить ручное форматирование.

### Описание решения проблемы

Предлагаю создать служебные комментарии, позволяющие определить блок кода с ручным форматированием. Такие блоки должны исключаться при вызове команды форматирования.

**Comment by marmyshev** [comment]
А как на счет текущего варианта?

```bsl
// @форматирование:выкл
... 
код = без + форматирования;
// @форматирование:вкл
...
```

Английский

```bsl
// @formatting:off
... 
код = без + форматирования;
// @formatting:on
...
```

Только важно, после слешей всегда 1 пробел вставлять до `@`
