### ISSUE TITLE
После удаления ТЧ объекта, на форме которого для этой ТЧ добавлен реквизит, не обновляется ИБ

### ISSUE THREAD

**Issue by Andrewww123** [1C-Company/1c-edt-issues#918]
### Описание ошибки

Если у объекта существует табличная часть и на форме этого объекта для этой табличной части добавлен реквизит, то после удаления табличной части не может обновиться связанная информационная база.

### Как воспроизвести

1. Создаём новый проект, связываем с пустой файловой базой.
2. Создаём документ, добавляем табличную часть (можно без реквизитов).
3. Создаём форму документа, реквизиту формы "Объект" в табличную часть добавляем любой реквизит. Обновляем ИБ.
4. Удаляем добавленный реквизит табличной части у реквизита "Объект", удаляем ТЧ в дереве метаданных. При обновлении ИБ ошибка

### Скриншоты

![image_2023-03-22_15-04-07](https://user-images.githubusercontent.com/24597726/226808618-71436c3d-462c-4db4-bd10-28c3266d6271.png)

### Ожидаемое поведение

Ошибки нет

### Лог рабочей области

Не нужен

### Версия 1С:EDT

Ruby 2022.2.4

### Операционная система

Windows

**Comment by vadimeg** [comment]
Исправлено в 2023.1
