### ISSUE TITLE
Edt повис при применении настроек проекта

### ISSUE THREAD

**Issue by DmitryShvaika** [1C-Company/1c-edt-issues#920]
### Описание ошибки

Edt повис при применении настроек проекта

дамп стека
[threaddump.zip](https://github.com/1C-Company/1c-edt-issues/files/11052650/threaddump.zip)

скрин
![image](https://user-images.githubusercontent.com/54451084/227252073-bd58bee1-d641-4ba7-b4c4-60c3267f8caa.png)

### Как воспроизвести

разовая ошибка, обычно работает

### Ожидаемое поведение

настройки должны применяться

### Лог рабочей области

не требуется

### Версия 1С:EDT

Ruby 2022.2.4

### Операционная система

Windows

**Comment by tretyakevich** [comment]
Исправлено в 2023.2
