### ISSUE TITLE
EDT Editing не устанавливается на  Ruby 2022.2.4

### ISSUE THREAD

**Issue by unichkin** [1C-Company/1c-edt-issues#922]
### Описание проблемы

https://github.com/marmyshev/edt-editing
- не устанавливается ни через сайт, ни через маркет-плейс

### Описание решения проблемы

Желательно добавить возможность установки, разлоченные модули БСП теперь участвуют в проверках, их стало на несколько тысяч больше, соотв. EDT тормозит сильнее

**Comment by marmyshev** [comment]
~~Война -> Санкции -> Роскомпозор -> Блокировки -> VPN доступ~~ -> всё работает.

**Comment by unichkin** [comment]
Добрый день! Не находит:

![image](https://user-images.githubusercontent.com/10799597/232722296-b80db22e-810e-4f05-aa2b-35111ce7079f.png)

**Comment by unichkin** [comment]
@marmyshev добрый день, не устанавливается плагин, прошу переоткрыть задачу

**Comment by marmyshev** [comment]
Добрый день.
Уточните, при чем тут ЕДТ, если у вас сайт не открывается?

Какой VPN вы пользуетесь для доступа к сайту обновлений? Вы ведь в России живёте? Возможно вам стоит сменить VPN провайдера?

Смотрите, сам сайт работает, в ЕДТ 2022.2 устанавливается.
<img width="527" alt="image" src="https://user-images.githubusercontent.com/4069973/233563335-6d76cfef-1a8b-4e5f-a8f2-ae51c1316aa5.png">

Вы ведь прочитали сообщение выше, про проблемы, причины и необходимость VPN, если вы живете в России?

**Comment by marmyshev** [comment]
На всякий случай - тут https://gitlab.com/marmyshev/edt-editing/-/packages/ можно скачать зип-архив репозитория и установить локально из архива.

**Comment by unichkin** [comment]
Никаким VPN не пользовался, и не понимаю как им пользоваться - в EDT где-то надо прописать? Или на роутере, или на компе?... И его надо все время держать включенным, или только дли разовой установки?
Попробую из архива установить, спасибо
