### ISSUE TITLE
При добавлении обработчика события элемента формы создавать процедуру в относящейся к этому элементу области

### ISSUE THREAD

**Issue by Andrewww123** [1C-Company/1c-edt-issues#925]
### Описание проблемы

Если находясь в форме выбрать команду добавления обработчика какого-либо события элемента формы, то процедура-обработчик создаётся в том месте модуля формы, где сейчас находится курсор. 

### Описание решения проблемы

Можно сделать чтобы система искала область, относящуюся к элементу формы, и добавляла процедуру в ней(имена стандартных и рекомендуемых областей система знает, т. к. показывает их в подсказках).

**Comment by adminimusRU** [comment]
Дубль #638
