### ISSUE TITLE
Неправильное заполнение ограничений реквизитов в редакторе СКД для отчетов с отключенным автозаполнением

### ISSUE THREAD

**Issue by ilyatyurin** [1C-Company/1c-edt-issues#927]
### Описание ошибки

В редакторе СКД для отчета с отключенным автозаполнением, неправильно заполняются ограничения реквизитов, для полей указанных в отборе компоновки данных.

### Как воспроизвести

1. В отчете (в конфигурации) создать макет схемы компоновки данных. 
2. Добавить набор данных - запрос.
3. Добавить запрос:
```
ВЫБРАТЬ
	ТестовыйОстаткиИОбороты.Счет КАК Счет,
	ТестовыйОстаткиИОбороты.Организация КАК Организация,
	ТестовыйОстаткиИОбороты.Валюта КАК Валюта,
	ТестовыйОстаткиИОбороты.КоличествоНачальныйОстаток КАК КоличествоНачальныйОстаток,
	ТестовыйОстаткиИОбороты.КоличествоКонечныйОстаток КАК КоличествоКонечныйОстаток,
	ТестовыйОстаткиИОбороты.КоличествоОборот КАК КоличествоОборот
{ВЫБРАТЬ
	Счет.*,
	Организация.*,
	Валюта.*}
ИЗ
	РегистрБухгалтерии.Тестовый.ОстаткиИОбороты(&НачалоПериода, &ОкончаниеПериода, , , Счет В ИЕРАРХИИ (&Счет68) {(Счет).*}, &ВидыСубконто, {(Организация).*, (Валюта).*, (Субконто1).* КАК Подразделение}) КАК ТестовыйОстаткиИОбороты
{ГДЕ
	ТестовыйОстаткиИОбороты.Счет.*,
	ТестовыйОстаткиИОбороты.Организация}
```

4. После заполнения, для полей: Организация, Валюта, Подразделение получим установленные галочки Ограничения реквизитов/Условия.

### Скриншоты

Результат воспроизведения ошибки:
![Ошибка_EDT](https://user-images.githubusercontent.com/129147654/228227094-d05d5160-f806-44e0-be31-f56d54fccfd5.png)

Необходимо такое заполнение:
![БезОшибки_Конфигуратор](https://user-images.githubusercontent.com/129147654/228227204-8d3d0062-8184-4b05-8415-868dcd82615e.png)

### Ожидаемое поведение

В "ограничение реквизитов" флажки должны быть сняты (так как это происходит в конфигураторе).

### Лог рабочей области

[logs.zip](https://github.com/1C-Company/1c-edt-issues/files/11088928/logs.zip)

### Версия 1С:EDT

Ruby 2022.2.4

### Операционная система

Windows

### Установленные плагины

Нет плагинов

### Дополнительная информация

Версия платформы 1С: 8.3.22.1851.
Ошибки не возникает при работе в конфигураторе.

**Comment by Erik773** [comment]
Задача закрыта как дубликат https://github.com/1C-Company/1c-edt-issues/issues/5
