### ISSUE TITLE
Стартер 

### ISSUE THREAD

**Issue by Jimmo910** [1C-Company/1c-edt-issues#928]
### Описание ошибки

Ошибка в том что, Стартер не видит установленные версии ЕДТ.

### Как воспроизвести

1. Открыть macOS 
2. Скачать ЕДТ (Оффлайн версия)
3. Установить ЕДТ
4. Запустить стартер.
5. Увидеть проблему.

### Скриншоты

<img width="550" alt="image" src="https://user-images.githubusercontent.com/122779512/228348441-45883312-6357-4fd0-8431-c8a5fef0d106.png">
<img width="562" alt="image" src="https://user-images.githubusercontent.com/122779512/228348525-2b320c91-f11f-42ae-8d9d-422812e2cf3d.png">

### Ожидаемое поведение

Стартер без входа в ИТС должен показывать установленные версии ЕДТ на ПК. так же как он это делает на Винде.

### Лог рабочей области

не знаю где взять лог стартера на маке

### Версия 1С:EDT

2022.2.5

### Операционная система

macOS

**Comment by Jimmo910** [comment]
Логи нашел
[1cedtstart.log](https://github.com/1C-Company/1c-edt-issues/files/11093647/1cedtstart.log)

**Comment by cognak** [comment]
У меня была такая же проблема. Оказалось, что products.json было прописан путь к иконке старой версии EDT.
