### ISSUE TITLE
При удалении Элемента стиля не выполняется проверка использования.

### ISSUE THREAD

**Issue by KrivickyA** [1C-Company/1c-edt-issues#929]
### Описание ошибки

При удалении элемента стиля, который был использован с любом объекте конфигурации остается ссылка на отсутствующий элемент в описании формы. При последующей попытке обновления информационной базы получаем ошибку примерно такого вида:

Операция конфигурирования завершена неуспешно
Исключение XDTO произошло при чтении файла- C:\tmp\1cedt\ssh-55156\0\xml-inc-93364\Catalogs\Справочник1\Forms\ФормаЭлемента\Ext\Form.xml.
по причине:
Ошибка преобразования данных XDTO:
Значение: {http://v8.1c.ru/8.1/data/ui/style}ТестовыйЭлементСтиля	Тип: {http://v8.1c.ru/8.1/data/ui}Color
по причине:
Ошибка отображения типов:
Отображение лексического значения '{http://v8.1c.ru/8.1/data/ui/style}ТестовыйЭлементСтиля' в значение типа 'Цвет'

### Как воспроизвести

1. Создаем тестовый Стиль и в свойствах конфигурации его назначаем основным стилем.
2. Создаем тестовый элемент стиля, например с видом "Цвет".
3. В любой произвольной форме элемента например для группы в качестве цвета фона выбираем созданный тестовый элемент стиля.
4. Обновляем информационную базу, убеждаемся, что  база обновилась и группа отображается с учетом выбранного стиля.
5. Удаляем тестовый элемент стиля. Если используется git, то в Индексировании Git наблюдаем, что есть изменения только в  "/src/Configuration/Configuration.mdo" и удален непосредственно mdo-файл стиля. В файле формы элемента из пункта 3 изменений нет. При открытии формы группа залита черным цветом, в поле "Цвет фона" 

### Скриншоты

![image](https://user-images.githubusercontent.com/23094215/228476141-1f3f7f84-66fc-41d4-86e1-95c250997409.png)
![image](https://user-images.githubusercontent.com/23094215/228476566-351ba0b4-9559-4f67-a117-18b10b110ac4.png)
![image](https://user-images.githubusercontent.com/23094215/228486489-773b4c6b-6709-414c-937a-b5138b7e3c0a.png)

### Ожидаемое поведение

Перед удалением элемента стиля должна выполнится проверка. При нахождении использования предложить либо очистить значение, сбросив на настройки по умолчанию, либо заменить на выбранное значение или другой элемент стиля.

### Лог рабочей области

[trace.log](https://github.com/1C-Company/1c-edt-issues/files/11098655/trace.log)
[ — копия.log](https://github.com/1C-Company/1c-edt-issues/files/11098668/default.log)

### Версия 1С:EDT

Ruby 2022.2.5

### Операционная система

Windows

### Установленные плагины

Нет плагинов

**Comment by vadimeg** [comment]
Исправлено в 2023.1
