### ISSUE TITLE
После нажатия обновить на форме выгрузка расширения становится невозможна

### ISSUE THREAD

**Issue by KovAlexey** [1C-Company/1c-edt-issues#932]
### Описание ошибки

После обновления (по каким-то причинам) формы документа в расширении ломается обновление информационной базы.

![изображение](https://user-images.githubusercontent.com/16429518/228738373-1a81e4e5-d646-4f98-a4f6-6950b20536a9.png)
Обновляем
И при обновлении получаем следующее.
![изображение](https://user-images.githubusercontent.com/16429518/228738732-54577059-4486-4ab4-8efa-e1e63812cc0b.png)

Естественно никаких таких ролей в расширении нет. Они есть только в конфигурации.

### Как воспроизвести

1. Заимствовать форму документа в расширении (в моем примере форма заказа клиента конфигурации "Комплексная автоматизация 2.4"
2. Каким-то образом заставить ЕДТ вызвать обновление
3. Обновить форму
4. Попытаться обновить

### Ожидаемое поведение

Отсутствие такой проблемы

### Лог рабочей области

[log_230330_update_forms.zip](https://github.com/1C-Company/1c-edt-issues/files/11108080/log_230330_update_forms.zip)

### Версия 1С:EDT

2022.2.4

### Операционная система

Windows

### Установленные плагины

1C:Code style V8, 1C:SSL-support

### Дополнительная информация

Расширений в проекте 2.
Помогает очистка рабочей области

**Comment by KovAlexey** [comment]
Отправил конфигурацию с воспроизведением Вадиму.

**Comment by vadimeg** [comment]
На 2023.1 описанное поведение не воспроизводится. Нашлась ошибка из-за которой конфигурация не загружается в базу - дублирование идентификаторов элементов формы. У таблицы и расширенной подсказки оказались одинаковые иды, в результате платформа не смогла найти пути к элементам таблицы, т.к. по все видимости пыталась вытащить их по иду из подсказки.
Применение квик-фикса для исправления дубликатов решило проблему.
Непонятно каким образом вообще попали дубликаты т.к. при мерже формы расширения с базовой формой иды корректируются таким образом, чтобы не было дублей. Дубли можно создать либо вручную в compare tool, либо был какой-то сбой

**Comment by Erik773** [comment]
@KovAlexey здравствуйте!
Подскажите, пожалуйста, актуальна ли проблема на версии 2023.1?

**Comment by Erik773** [comment]
Закрываем задачу. 
Если проблема возникнет снова то, пожалуйста, переоткройте задачу.
