### ISSUE TITLE
Cворачиваются раскрытые области в панели Схема по мере набора кода внутри директив препроцессора

### ISSUE THREAD

**Issue by adminimusRU** [1C-Company/1c-edt-issues#935]
### Описание ошибки

Ошибка #661 в 2022.2.5 исправлена частично. При отсутствии директив препроцессора всё хорошо, но с ними схема всё так же перестраивается при наборе кода и области сворачиваются.
По стандарту в типовых конфигурациях все модули объекта, набора записей и менеджера заключаются в инструкции препроцессора (https://its.1c.ru/db/v8std#content:680:hdoc). Фактически получается, что на больше части модулей ошибка всё еще воспроизводится.

### Как воспроизвести

1. Ввести в редактор кода текст модуля:

```bsl
#Если Сервер Или ТолстыйКлиентОбычноеПриложение Или ВнешнееСоединение Тогда

#Область Область1

Процедура Процедура1()
	
	// код процедуры
	
КонецПроцедуры

#КонецОбласти

#Область Область2

Процедура Процедура2()
	
	
	
КонецПроцедуры

#КонецОбласти

#КонецЕсли
```

2. Раскрыть область `Область1` в панели Схема;
3. Установить курсор в тело метода `Процедура2` и набрать произвольную строку кода;
4. Схема в панели перестроится и `Область1` окажется снова свернутой.

### Скриншоты

![edt-module-scheme-bug](https://user-images.githubusercontent.com/28653631/228850067-3b485b2e-40b3-432f-b118-0d158cfa4356.gif)

### Ожидаемое поведение

Вручную раскрытые области должны оставаться раскрытыми.

### Лог рабочей области

не требуется

### Версия 1С:EDT

2022.2.5

### Операционная система

Windows

**Comment by MaksimDzyuba** [comment]
Здравствуйте, да, оказался еще один кейс, извиняюсь, что не с первого раза поправил.
![bandicam 2023-03-31 13-10-19-982](https://user-images.githubusercontent.com/77277424/229093127-d982feff-edab-4af5-a211-85e70f17d5b6.gif)
