### ISSUE TITLE
Удаление и повторная установка точки между переменной структуры и ее полем приводит к возникновению спонтанных ошибок по коду. Плюс некоторые ошибки возникают вообще не в области кода.

### ISSUE THREAD

**Issue by DmitryShvaika** [1C-Company/1c-edt-issues#936]
### Описание ошибки

Удаление и повторная установка точки между переменной структуры и ее полем приводит к возникновению спонтанных ошибок по коду. Плюс некоторые ошибки возникают вообще не в области кода.

Смотрите видео:
![Возникновение спонтанных ошибок](https://user-images.githubusercontent.com/54451084/229035522-8eea51f7-fb9e-4709-98b7-37a1c01d688c.gif)

### Как воспроизвести

1. Создать общий модуль
2. Перенести в него код:

```
// @strict-types

#Область ПрограммныйИнтерфейс

// Конструктор1.
// 
// Возвращаемое значение:
//  Структура - Конструктор1:
// 		* Поле - Строка -
//
Функция Конструктор1() Экспорт
	
	Данные = Новый Структура;
	Данные.Вставить("Поле", "");
	
	Возврат Данные;
	
КонецФункции

// Моя процедура.
Процедура МояПроцедура() Экспорт
	
	Данные1 = Конструктор1();

	Если 1=1 Тогда
		
	КонецЕсли;
		
	Данные1.Поле = "значение";	
	
КонецПроцедуры

#КонецОбласти

```

3. В строке Данные1.Поле = "значение";	Удалить точку через BackSpace через пару секунд добавить ее обратно. Наблюдать ошибки. (иногда возникают не сразу. возможно надо еще пару раз так  сделать с разным временным интервалом)

### Скриншоты

![image](https://user-images.githubusercontent.com/54451084/229035609-b1ce5c21-3cbf-4497-b834-58037c8d1488.png)

### Ожидаемое поведение

Ошибки не должны возникать

### Лог рабочей области

не требуется

### Версия 1С:EDT

Ruby 2022.2.5

### Операционная система

Windows

### Дополнительная информация

Лечится проблема так - в первой строке (пустой) модуля ставлю 1. Сохраняю модуль. Потом удаляю 1 и снова сохраняю модуль. Тогда ошибки исчезают. Но через некоторое время опять появляются и "лечение" снова надо повторять. Так и программируем :)

**Comment by adminimusRU** [comment]
Воспроизводится после нескольких попыток. Лечится еще через ручной запуск проверки модуля из контекстного меню. В логах ошибок нет.

**Comment by MaksimDzyuba** [comment]
Похоже, что мои исправления по-другой ошибки, когда нам просто давали конфигурацию, без регистрации тут, победила эту проблему. Если после выхода 2023.1 воспроизведется, то просьба переоткрыть.
![bandicam 2023-04-03 09-40-01-389](https://user-images.githubusercontent.com/77277424/229431659-9a347880-f220-450d-8e28-0f220ce245bc.gif)
