### ISSUE TITLE
Избыточная проверка существования информационной базы при обновлении приложения

### ISSUE THREAD

**Issue by adminimusRU** [1C-Company/1c-edt-issues#937]
### Описание ошибки

Иногда при запуске отладки с обновлением приложения EDT несколько секунд (до минуты) проводит в состоянии "Проверка существования информационной базы". При этом никаких изменений в базу вне EDT не производилось, агент конфигуратора не завершался.
В логе при этом появляется ошибка "Failed to receive session's required threads stop event".

### Как воспроизвести

Точный порядок действий не ясен, возникает случайно при запуске отладки с обновлением приложения.

### Скриншоты

![image](https://user-images.githubusercontent.com/28653631/229037385-bb981092-841f-47eb-9ba6-238d790690a9.png)

### Ожидаемое поведение

Должен сразу же появляться диалог об обновлении конфигурации приложения без лишней задержки.

### Лог рабочей области

[log.zip](https://github.com/1C-Company/1c-edt-issues/files/11118717/log.zip)

### Версия 1С:EDT

2022.2.5

### Операционная система

Windows

### Дополнительная информация

Платформа 8.3.21.1709, базы на сервере. Проявлялось и на предыдущих сборках EDT 2022.2.

**Comment by nikolay-martynov** [comment]
Здравствуйте. На самом деле ошибка в том, что отображается совсем не то, что система делает в действительности. Залипало отображение уже давно выполненных задач. Ни на какой проверке существования информационной базы у вас там не висит. Система перед запуском отладки проверяет не были ли внесены изменения в информационную базу на стороне. Вы верно заметили, что иногда этой задержки нет. Так бывает, когда система успевает в фоновом режиме проверить наличие изменений. Тогда дальнейшие запуски проходят без задержек. Однако, если пользователь успевает запустить отладку (или другие задачи требующие взаимодействия с информационной базой) до завершения фоновой проверки, то система сначала закончит её выполнение, а уже потом выполнит запрошенное действие. Подобное поведение может наблюдаться и в других случаях. Например, если система пытается выполнить повторные попытки подключения к информационной базе, с которой не удается установить связь, то действия, требующие взаимодействия с информационной базой, будут на какое-то время приостановлены.
В версии 2023.3 улучшено отображение того, чем на самом деле занимается система при взаимодействии с платформой 1С:Предприятие. Также добавлена дополнительная диагностика. Так, если действие было приостановлено на длительное время из-за ожидания готовности соединения для дальнейшего взаимодействия, то в журнал ошибок будет добавлено предупреждение об этом.
