### ISSUE TITLE
В форме обработки нельзя сослаться на описание экспортных методов модуля этой же обработки

### ISSUE THREAD

**Issue by sovaenga** [1C-Company/1c-edt-issues#945]
### Описание ошибки

В модуле обработки в составе конфигурации описана экспортная функция
// Конструктор.
// 
// Возвращаемое значение:
//  Структура - Конструктор:
// * Ключик - Строка -
Функция ЭтоКонструктор() Экспорт
	Результат = Новый Структура;
	Результат.Вставить("Ключик", "");
	Возврат Результат;
КонецФункции

Ожидается, что в док. комментарии в форме этой обработки можно на нее сослаться. Но этого не происходит
// См. Обработки.Обработка1.и дальше ничего

### Как воспроизвести

По описанию

### Ожидаемое поведение

Отобразится после точки
// См. Обработки.Обработка1.ЭтоКонструктор

### Лог рабочей области

.

### Версия 1С:EDT

2022.2.5

### Операционная система

Windows

**Comment by MaksimDzyuba** [comment]
оказалось. что можно сделать так - //  Пар1 - См. ОбработкаОбъект.ОбработкаПример.ЭтоКонструктор

**Comment by adminimusRU** [comment]
`См. Обработки.Обработка1.ЭтоКонструктор` - это ссылка на метод в модуле **менеджера** обработки.
