### ISSUE TITLE
Конструктор запроса. Произвольное выражение

### ISSUE THREAD

**Issue by Jimmi910** [1C-Company/1c-edt-issues#946]
### Описание ошибки

Ошибка в том что... Не удается нормально нормально редактировать Произвольное выражение.

### Как воспроизвести

1. Создаем пустой проект
2. Создаем пустую конфигурацию
3. Создаем общий модуль. (Это не обязательно можно в любом месте открыть конструктор)
4. Открываем Конструктор запроса.
5. Нажимаем на Плюсик, в выбранных полях. т.е. добавляем произвольное поле.
6. Открывается окно "Произвольное выражение".
7. И в нем нельзя ничего писать.
8. Точнее как оказалось оно там пишется. но не отображается.
9. И двойной клик на существующие поля не работает. (Ожидается что это поле перенесется в набираемы текст)

### Скриншоты

![image](https://user-images.githubusercontent.com/26252130/230033853-74e31502-d7ad-4efd-98f3-483679f03b90.png)

### Ожидаемое поведение

Набираемый текст должен отображаться. 

### Лог рабочей области

Вот весь проект. Логи в нем.

[ТЕМП.zip](https://github.com/1C-Company/1c-edt-issues/files/11157019/default.zip)

### Версия 1С:EDT

2022.2.5

### Операционная система

macOS

### Дополнительная информация

MacOS 12.5 (21G72)

**Comment by adminimusRU** [comment]
Похоже на очередной баг темной темы (возможно специфичный для macos). В windows на светлой теме всё ок.
![image](https://user-images.githubusercontent.com/28653631/230076870-6b107bb4-5629-44fd-9c11-5a90c30fe0bb.png)

**Comment by RedMammoth** [comment]
в ubuntu 22.04 на темной теме тоже ок
![image](https://user-images.githubusercontent.com/64589646/230092037-f9e5ba13-aed9-4299-8b27-2046fb5c0eaf.png)

**Comment by Jimmi910** [comment]
ну значит страдает только mac =(

**Comment by Erik773** [comment]
Проблема с визуальными темами известна. Есть внутренняя задача, в рамках которой будет вестись работа.
Эту задачу пока закрываем, так как данный механизм не попадает в приоритеты разработки на ближайшее время.
Когда проблема будет устранена, мы сообщим об этом в комментарии к текущей задаче.
