### ISSUE TITLE
При удалении табличной части не удаляются дополнительные колонки на формах

### ISSUE THREAD

**Issue by a2080016** [1C-Company/1c-edt-issues#947]
### Описание ошибки

Если удалить табличную часть объекта, а на форму были добавлены дополнительные колонки этой табличной части, то эти дополнительные колонки не удаляются, и конфигурация не собирается.

### Как воспроизвести

1. Создайте новый справочник
2. Добавьте табличную часть в этот справочник
3. Создайте форму элемента справочника и добавьте дополнительную колонку в табличную часть на форме

![Snag_2a48217a](https://user-images.githubusercontent.com/24942027/230078039-4d3a3fd6-3b90-498f-863c-b6b0f5e8e55b.png)

4. Удалите табличную часть справочника. Наблюдайте проблему.

![Snag_2a413189](https://user-images.githubusercontent.com/24942027/230076321-d6580615-b166-4988-bb22-33fa6b62a631.png)

5. Попробуйте обновить конфу. Наблюдайте ошибку
![Snag_2a41f0a3](https://user-images.githubusercontent.com/24942027/230076480-7e021a75-630d-49e1-a615-b0883b11b45f.png)

### Скриншоты

В исходниках видим, что после удаления табличной части справочника остались атрибуты дополнительных колонок
 
![Snag_2a48e893](https://user-images.githubusercontent.com/24942027/230078224-72631e53-8f55-484a-903c-2723bd3fd9de.png)

### Ожидаемое поведение

При удалении табличных частей объектов удаляются дополнительные колонки этих табличных частей в формах

### Лог рабочей области

Не нужен

### Версия 1С:EDT

2022.2.5

### Операционная система

Windows

### Установленные плагины

1C:Code style V8

### Дополнительная информация

Платформа 8.3.22.1750

**Comment by vadimeg** [comment]
То же, что и https://github.com/1C-Company/1c-edt-issues/issues/918
