### ISSUE TITLE
Конфигурация перестает собираться при изменении свойства документа "Проведение" на Истина и наличия типовой исключенной команды "ЗаписатьИЗакрыть"

### ISSUE THREAD

**Issue by Dumsik** [1C-Company/1c-edt-issues#949]
### Описание ошибки

Конфигурация перестает собираться при изменении свойства документа "Проведение" на Истина если ранее в форме документа была выключена типовая  команда "ЗаписатьИЗакрыть" 

### Как воспроизвести

1. Создать документ
2. Установить у документа Свойство "Проводится" = Ложь"
3. Создать форму документа.
4. В созданной форме документа выключить через "Состав команд" стандартную команду "ЗаписатьИЗакрыть"
5.Сохранить конфигурацию и обновить разрабатываемое приложение
6. Установить у документа Свойство "Проводится" = Истина"
7. Сохранить конфигурацию и попытаться обновить разрабатываемое приложение. Это завершиться ошибкой с сообщением о неправильной команде WriteAndClose.

Проблема в том что edt при не удаляет из xml описания формы документа исключенные команды которые не доступны по свойствам объекта см скрин.

Для решения проблемы нужно через текстовый редактор удалить элемент  `<excludedCommands>WriteAndClose</excludedCommands>` из файла xml описания формы документа From.form.

### Ожидаемое поведение

Элементы xml файла соответствующие отключенным командам корректно удаляются из xml согласно свойствам объекта.

### Лог рабочей области

.

### Версия 1С:EDT

2022.2.5

### Операционная система

Windows

### Дополнительная информация

Лог рабочей области [ws.log](https://github.com/1C-Company/1c-edt-issues/files/11166954/ws.log)
Скриншот 
![Screenshot_1](https://user-images.githubusercontent.com/24560572/230287250-f6e78766-06a9-46cf-aef2-32698d8e54a1.png)

**Comment by vadimeg** [comment]
Исправлено в 2023.1
