### ISSUE TITLE
EDT 2022.2.4 нельзя к внешнему отчету(проект внешних отчетов и обработок) привязать общую форму( проект конфигурации) 

### ISSUE THREAD

**Issue by AlehKuchynski** [1C-Company/1c-edt-issues#951]
### Описание ошибки

При выборе формы во внешнем отчете  форма выбора пустая , хотя в базовом проекте существуют общие формы. базовый проект привязан, но окно выбора форм пустое .
![выборформы](https://user-images.githubusercontent.com/130138026/230574028-d4ffaf45-0e94-45fa-8f9b-534bec14be01.jpg)

ФормаОтчета , ФормаНастроекОтчета, ФормаВариантаОтчета  - это общие  формы проекта конфигурации

### Как воспроизвести

ФормаОтчета , ФормаНастроекОтчета, ФормаВариантаОтчета  - это общие  формы проекта конфигурации (БСП версия 2.4.4)

### Скриншоты
![формавыбора1](https://user-images.githubusercontent.com/130138026/230606470-ccec141c-8eb4-4df4-a8a4-3229c78f33d3.jpg)

_No response_

### Ожидаемое поведение

При выборе форм в отчете проекта внешних отчетов должны быть доступны все Общие формы проекта конфигурации.

### Лог рабочей области

[bak.2023-04-06.0.log.zip](https://github.com/1C-Company/1c-edt-issues/files/11177449/bak.2023-04-06.0.log.zip)
[.log](https://github.com/1C-Company/1c-edt-issues/files/11177454/default.log)
[trace.log](https://github.com/1C-Company/1c-edt-issues/files/11177455/trace.log)

### Версия 1С:EDT

EDT 2022.2.4

### Операционная система

Windows

### Установленные плагины

Нет плагинов

**Comment by vadimeg** [comment]
Добрый день, есть баг на редактор заимствованных объектов метаданных. А через палитру тоже не выбирается форма?
В палитре, слева от селектора формы, должен быть чек-бокс, он должен быть выставлен в значение "Изменять значение..."

**Comment by AlehKuchynski** [comment]
через палитру свойств тоже не открываются формы. я добавил скриншот на гитхабе

  
>Пятница, 7 апреля 2023, 14:38 +03:00 от Vadim Geraskin ***@***.***>:
> 
> 
>Добрый день, есть баг на редактор заимствованных объектов метаданных. А через палитру тоже не выбирается форма?
>В палитре, слева от селектора формы, должен быть чек-бокс, он должен быть выставлен в значение "Изменять значение..."
>—
>Reply to this email directly,  view it on GitHub , or  unsubscribe .
>You are receiving this because you authored the thread. Message ID:  <1C-Company/1c-edt-issues/issues/951/1500209256 @ github . com> 
 
 
--
Олег Кучинский
Отправлено из Почты  Mail.ru

**Comment by vadimeg** [comment]
Исправлено в 2023.1
