### ISSUE TITLE
При активном запущенном сравнение объединении доступен контекст "виртуального" проекта

### ISSUE THREAD

**Issue by Daabramov** [1C-Company/1c-edt-issues#952]
### Описание ошибки

При выполнении операции сравнения объединения доступен контекст нового "виртуального" проекта, что мешает навигации.

![image](https://user-images.githubusercontent.com/31928832/230895525-125b5d5c-b721-4463-a9ff-c62c98b3ca2f.png)

### Как воспроизвести

1. Запустите сравнение объединение, чтобы открылось окно сравнения
2. Нажмите Ctrl + Shift + M для диалога поиска объекта проектов
3. Отметить дублирования модулей и появления нового virtual проекта

### Ожидаемое поведение

Виртуальные проект нигде появлятся не должен

### Лог рабочей области

[virtual-project-edt.log](https://github.com/1C-Company/1c-edt-issues/files/11190234/virtual-project-edt.log)

### Версия 1С:EDT

2022.2.5

### Операционная система

Windows

**Comment by traggerET** [comment]
Добрый день, можете, пожалуйста, уточнить, где выполняется пункт про "Отметить дублирования модулей и появления нового virtual проекта"?

**Comment by Daabramov** [comment]
> Добрый день, можете, пожалуйста, уточнить, где в интерфейсе выполнить пункт про "Отметить дублирования модулей и появления нового virtual проекта"?

В диалоге "открыть объект конфигурации" (ctrl shift m). Как на скриншоте

**Comment by traggerET** [comment]
Можете подробнее описать сценарий открытия сравнения? Через какое окно вы это делаете, какие параметры выбираете? У ничего лишнего не отображается

**Comment by traggerET** [comment]
Я тестировал на версии 2023.1. В ней эта ошибка исправлена

**Comment by Daabramov** [comment]
> Я тестировал на версии 2023.1. В ней эта ошибка исправлена

Ну если она там исправлена, то давайте дождемся ее выхода и я там тоже проверю, по итогам отпишусь.

**Comment by AlmazNasibullin** [comment]
> > Я тестировал на версии 2023.1. В ней эта ошибка исправлена
> 
> Ну если она там исправлена, то давайте дождемся ее выхода и я там тоже проверю, по итогам отпишусь.
Дмитрий, добрый день.
Будем благодарны, если Вы проверите эту ошибку на версии 2023.1 и отпишитесь по результатам. Сейчас эту ошибку мы закроем, поскольку в версии 2023.1 она исправлена, выпуск версии 2022.2 более не планируется.
