### ISSUE TITLE
Синоним в расширении.

### ISSUE THREAD

**Issue by Jimmi910** [1C-Company/1c-edt-issues#953]
### Описание ошибки

Ошибка в том что, пропадают коды языков расширении.

### Как воспроизвести

На вновь созданном не воспроизводится. 
Воспроизводится на моем - уже давно разрабатываемом в ЕДТ.

Слитают коды если хоть ка кто изменить структуру методанных расширени.
Изменить версию расширения или добавить новый объект.

### Скриншоты

![image](https://user-images.githubusercontent.com/26252130/230908309-14ea25a8-3ba4-4527-b76b-bdb1fb7b8472.png)

### Ожидаемое поведение

Коды языков не должны удалятся. Из-за этого блокируется изменение синонивом.

### Лог рабочей области

[log.zip](https://github.com/1C-Company/1c-edt-issues/files/11190688/log.zip)

### Версия 1С:EDT

2022.2.5

### Операционная система

macOS

### Дополнительная информация

@vadimeg  
я скидывал в феврале расширение и показывал по видео связи.
Если нужно что то еще могу все передать и показать лично. пишите в телегу @Jimmi910

**Comment by vadimeg** [comment]
Добрый день, а у вас в Configuration.mdo есть такая строчка?
<defaultLanguage>Checked</defaultLanguage>

Если есть, то похоже в какой-то момент произошла рассинхронизация. На картинке я вижу у вас:
**<extension xsi:type="mdclassExtension:LanguageExtension"/>**
<languageCode>ru</languageCode>

А должно быть:
**<extension xsi:type="mdclassExtension:LanguageExtension">
      <languageCode>Checked</languageCode>
    </extension>**
<languageCode>ru</languageCode>


Ну, и для английского языка так же. Попробуйте исправить в mdo.

**Comment by Jimmi910** [comment]
Да это помогло. Вроде как помогло. не слитает пока. Спасибо. Надеюсь больше не слетит.
