### ISSUE TITLE
Невозможно запустить отладку, если имя хоста содержит только цифры

### ISSUE THREAD

**Issue by 0semenitel** [1C-Company/1c-edt-issues#954]
### Описание ошибки

При стандартном запуске отладки через EDT возникает ошибка соединения с сервером отладки «http://0012493921:1550/» - где «0012493921» - имя клиентской машины. 
При этом сервер отладки запускается (dbgs.exe) и остается запущенным.
При повторной попытке запуска отладки появляется «Ошибка запуска процесса отладки 1С:Предприятие: Настроенный порт отладки 1550 уже используется в системе.....» - все логично ведь процесс отладки уже запущен.
Но для запуска отладки с таким стеком ошибок приходится создавать конфигурацию отладки, и прописывать в ней адрес отладки «http://localhost:1550», тогда запуститься клиент 1С, под старым, уже запущенным процессом dbgs на 1550 порту.
На текущий момент работать приходиться с помощью настроенной «Группы запуска» с адресом отладки «http://localhost:1550».
Помогите разобраться, почему запускается сервер отладки, а клиент 1С не может запуститься под именем локальной машины содержащей одни цифры?

### Как воспроизвести

https://user-images.githubusercontent.com/129940575/230925365-77a9dc30-b0ac-49ff-995e-e573a73892fc.mp4

### Ожидаемое поведение

Запуск отладки без ошибки соединения с сервером отладки.

### Лог рабочей области

[bag_dbgs_log.txt](https://github.com/1C-Company/1c-edt-issues/files/11191251/bag_dbgs_log.txt)

### Версия 1С:EDT

Ruby 2022.1.5

### Операционная система

Windows

### Установленные плагины

Нет плагинов

**Comment by DmitryBelov-e1c** [comment]
Проблема на уровне Java-core - цифровое имя хоста интерпретируется как IP-адрес, что неверно. Альтернативы используемому workaround на данный момент нет. Недавние изменения по зарегистрированной на Java-core ошибке отсутствуют. https://bugs.java.com/bugdatabase/view_bug?bug_id=8191991

**Comment by DmitryBelov-e1c** [comment]
Добрый день.

При разрешении доменных имён Java следует спецификации IETF (RFC 1123 секция 2.1 "Host Names and Numbers"), где допускаются только десятичные литералы адресов. Java не поддерживает стандарт BSD, который применяется в браузерах и сетевых утилитах. При этом Java не обращается к службе доменных имён, если установлено, что в качестве имени хоста передан ip-литерал. См. https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/net/InetAddress.html#getByName(java.lang.String). "... If a literal IP address is supplied, only the validity of the address format is checked."

Добавим ограничение в документацию и предлагаем рассмотреть возможность изменения политики назначения доменных имён в организации, либо продолжать использовать упомянутый в ошибке обход.
