### ISSUE TITLE
В редакторе запроса не работает переход к строке

### ISSUE THREAD

**Issue by LusineMkrtumian** [1C-Company/1c-edt-issues#956]
### Описание ошибки

В редакторе запроса не работает переход к строке. Уточнение - переходит только курсор, само окно не пролистывается.

### Как воспроизвести

1. Перейдите в Редактор запроса.
2. Нажмите ctrl+G и введите номер строки.
3. Окно осталось прежним.

### Ожидаемое поведение

Ожидается переход к нужной строке.

### Лог рабочей области

Не требуется.

### Версия 1С:EDT

2022.1.2

### Операционная система

Windows

**Comment by RedMammoth** [comment]
в 2022.2.5 аналогично

**Comment by MaksimDzyuba** [comment]
Здравствуйте, да, ошибка, поправил, войдет в 2023.1
![bandicam 2023-04-12 09-39-44-130](https://user-images.githubusercontent.com/77277424/231372808-c6f43fca-22e6-4e18-84d2-7f7503d9e1f1.gif)
