### ISSUE TITLE
Невозможно в динамический список добавить колонку

### ISSUE THREAD

**Issue by hamec** [1C-Company/1c-edt-issues#96]
### Описание ошибки

При попытке обновить конфигурацию после добавления колонки в динамический список возникает ошибка.
Добавляемая колонка является реквизитом объекта ссылочного типа.

### Как воспроизвести

1. Создайте динамический список
2. Добавьте в него колонку ссылочного типа. К примеру колонку Справочник.Номенклатура
3. Добавьте в динамический список колонку с реквизитом справочника номенклатура. Т.Е. Список.Номенклатура.Комментарий
4. Попытайтесь обновить конфигурацию

### Скриншоты

![image](https://user-images.githubusercontent.com/25643488/141644669-9d24959b-1521-4ca2-bb48-9eacc49721fc.png)

### Ожидаемое поведение

Данное действие не должно приводить к ошибке.

### Лог рабочей области

[log.txt](https://github.com/1C-Company/1c-edt-issues/files/7532106/log.txt)
[trace.log](https://github.com/1C-Company/1c-edt-issues/files/7532107/trace.log)

### Версия 1С:EDT

2021.2.29

### Операционаня система

Windows

### Установленые плагины

1C:Code style V8, 1C:SSL-support

### Дополнительная информация

Обходится путем добавления реквизита в запрос динамического списка

**Comment by vadimeg** [comment]
@hamec Если не сложно, то приложите, пожалуйста, конфигурацию, на которой это воспроизводится.

**Comment by vadimeg** [comment]
Не воспроизводится в 2022.1
