### ISSUE TITLE
Заимствование Регистра бухгалтерии в расширение. Не переносятся стандартные реквизиты.

### ISSUE THREAD

**Issue by petypen** [1C-Company/1c-edt-issues#960]
### Описание ошибки

Ошибка в том что, при заимствовании регистра бухгалтерии в расширение не переносятся стандартные реквизиты объекта.

### Как воспроизвести

В типовой конфигурации 1С Бухгалтерия 3.0 заимствуйте в расширение объект "Регистр бухгалтерии  - Хозрасчетный".
У заимствованного объекта отсутствуют стандартные реквизиты.

Объект основной конфигурации содержит стандартные реквизиты:

![2023-04-13 17-18-28 accws - ACC_PROJECT→Регистры бухгалтерии→Хозрасчетный - 1C Enterprise Development Tools](https://user-images.githubusercontent.com/6500075/231788388-54a109cb-ca35-4628-85dd-44fc497eaed2.png)

Объект заимствованный в расширение уже не содержит стандартных реквизитов:

![2023-04-13 17-21-18 accws - IIT003_ACC_INTEGR_PROJECT→Регистры бухгалтерии→Хозрасчетный - 1C Enterprise Development Tools](https://user-images.githubusercontent.com/6500075/231789127-8c280117-3082-46df-9325-d120c0773dbc.png)

Отсутствие стандартных реквизитов регистра бухгалтерии в расширении мешает разработке:
-- не работает подсказка по реквизитам объекта
-- неоправданные сообщения об ошибках при использовании стандартных реквизитов в расширении

### Ожидаемое поведение

При заимствовании объекта в расширении его стандартные реквизиты так же заимствоваются.

### Лог рабочей области

[metadata.zip](https://github.com/1C-Company/1c-edt-issues/files/11223193/metadata.zip)

### Версия 1С:EDT

Ruby 2022.2.5

### Операционная система

Windows

**Comment by beg7** [comment]
Поведение совпадает с поведением Конфигуратора. Не могу подтвердить что это Bug. 
Поведение действительно не удобное, надо думать можно это решить и как.

**Comment by vovan58** [comment]
Работать не возможно. В запросе, например, виртуальная таблица ОстаткиОборотыДтКт невозможно обратиться к реквизитам СчетДт, СчетКт, СубконтоДт1 и т.д. Если запрорс перенести текстом, то edt выдает ошибки и не позволяет запустить приложение.
