### ISSUE TITLE
Ошибка при поиске в панели навигатора

### ISSUE THREAD

**Issue by TimkoNZT** [1C-Company/1c-edt-issues#961]
### Описание ошибки

Происходит плавающая ошибка при наборе текста в строке поиска окна навигатора. 
В момент набора второго или третьего символа строка поиска очищается, тем самым обрезая начало текста. 
Ошибка плавающая, происходит не каждый раз, закономерностей не обнаружено.

### Как воспроизвести

1. Кликнуть по строке поиска в окне навигатора
2. Начать набор текста для поиска в конфигурации
3. Обнаружить, что первые символы набранного текста отсутствуют в строке поиска
4. Удивиться

### Скриншоты

![image](https://user-images.githubusercontent.com/3190574/231834042-2181e5a2-ddf9-4671-9537-c4b45da7c818.png)

### Ожидаемое поведение

Текст поиска не изменяется самостоятельно

### Лог рабочей области

[metadata.zip](https://github.com/1C-Company/1c-edt-issues/files/11224636/metadata.zip)

### Версия 1С:EDT

Ruby 2022.2.5

### Операционная система

Windows

**Comment by dsavenko** [comment]
Исправлено в 2023.2.
