### ISSUE TITLE
При работе с объединенными ячейками в макете отчета становится недоступна палитра свойств, после сохранения макет более не открывается

### ISSUE THREAD

**Issue by newphoenix87** [1C-Company/1c-edt-issues#963]
### Описание ошибки

Становится недоступной палитра свойств ячеек табличного документа. Ячейки не выбираются, Иногда палитра становится доступна, но все измененные на ней свойства не применяются к ячейкам. После сохранения макета, он "ломается" и более не открывается.

### Как воспроизвести

Воспроизводится не всегда.
1. Выделить область, состоящую из 1 столбца и 3 строк. Верхняя ячейка заполнена текстом, вторая и третья сверху - заполнение параметром.
2. Скопировать эту область.
3. Вставить область в другую область, которая содержит объединенные ячейки. Обычно при этом объединенные ячейки разделяются и всё корректно отрабатывает, но иногда ячейки не разделяются и получается проблема.

### Скриншоты

![image](https://user-images.githubusercontent.com/91092040/232415976-ab12964b-57c8-45d9-ad93-4736a7290e58.png)
![image](https://user-images.githubusercontent.com/91092040/232416165-ca3608b2-3e59-474c-a91e-292662fbf03d.png)

### Ожидаемое поведение

Ожидал, что объединенная область разделится

### Лог рабочей области

[log.log](https://github.com/1C-Company/1c-edt-issues/files/11247378/log.log)

### Версия 1С:EDT

Ruby 2022.2.5

### Операционная система

Windows

### Установленные плагины

Нет плагинов

**Comment by MaksimDzyuba** [comment]
![ScreenRecorderProject1](https://user-images.githubusercontent.com/77277424/232420670-b96870bd-5e3f-40bb-ae0e-bb39c1f39c6b.gif)

**Comment by wolfandw** [comment]
исправлено в 2023.2
