### ISSUE TITLE
Зависание EDT при конвертации макета типа Табличный документ с множеством картинок (2021.2.9 + 4)

### ISSUE THREAD

**Issue by yegor-novinsky** [1C-Company/1c-edt-issues#97]
### Описание ошибки

Проблема подробно описана в https://partners.v8.1c.ru/forum/t/2022283/m/2022283

### Как воспроизвести

Проблема подробно описана в https://partners.v8.1c.ru/forum/t/2022283/m/2022283

### Ожидаемое поведение

Проект конвертируется

### Лог рабочей области

[log.txt](https://github.com/1C-Company/1c-edt-issues/files/7532235/log.txt)
При выгрузке журнала по ссылке https://its.1c.ru/db/edtdoc#content:153:hdoc:_top:%D0%BB%D0%BE%D0%B3 EDT умер. Но это уже другая история...

### Версия 1С:EDT

2021.2.9 + 4

### Операционаня система

Windows

**Comment by tretyakevich** [comment]
Зависание не подтверждается, однако подтверждается очень долгое чтение из base64-кодированных полей.

**Comment by yegor-novinsky** [comment]
Описанных макетов несколько в одном из проектов. В связи с чем, дождаться завершения конвертации проекта не удается. Выделил 12 Гб памяти на EDT. Но сам по себе проект не очень большой - по рекомендациям 12 Гб памяти вполне достаточно.

**Comment by tretyakevich** [comment]
Дело не в памяти, дело в других факторах. Ошибка принята на 2021.3, комментарий в первую очередь для разработчиков EDT

**Comment by MaksimDzyuba** [comment]
@yegor-novinsky  как я понимаю, что проблема все еще актуальна. А можете, пожалуйста, примерно сказать, размер картинок, которые использовались в табличном документе и их количество штук

**Comment by marmyshev** [comment]
@tretyakevich уточни, бага исправлена полностью в 2021.3 или частично? Нужно либо перенести майлстоун или снять, либо закрыть задачу

**Comment by tretyakevich** [comment]
В данный момент в ближайших планах исправление не планируется из-за ограничений по совместимости по формату табличного документа с платформой. В дальнейшем возможен пересмотр формата с соответствующими изменениями в этом вопросе.
