### ISSUE TITLE
В расширении затираются установленные значения заимствованных элементов стиля

### ISSUE THREAD

**Issue by AndreyDanilov-nn** [1C-Company/1c-edt-issues#970]
### Описание ошибки

При сборке расширения из исходников edt затираются свойства "цвет" с заимствованными элементами стиля (например конвертация через ring в xml и сборка cfe через vanessa-runner compileexttocfe)

### Как воспроизвести

1. Загрузить расширение в базу (cfe в доп. информации)
2. Открыть общую форму `тест_Форма`, запомнить внешний вид
3. Выгрузить расширение в исходники `конфигурация - выгрузить конфигурацию в файлы - 'xml-файлы'`
4. Импортировать расширение в новый проект edt `импорт - расширение конфигурации из xml-файлов`
5. Экспортировать расширение в xml `экспорт - конфигурация в xml-файлы`
6. Загрузить исходники в базу. Открыть общую форму `тест_Форма`, сравнить с п.2
7. Сравнить исходники. edt затерла свойства TitleTextColor, BackColor и т.д. Ну и добавила других отличий в исходники.

### Скриншоты

исходная
![image](https://user-images.githubusercontent.com/53249626/232840927-ddffb849-a5af-4513-bce3-60a4dc96c79c.png)

после сборки из едт
![image](https://user-images.githubusercontent.com/53249626/232841237-3546ce04-7188-4def-8fd7-eed8f2c93689.png)

различия
![image](https://user-images.githubusercontent.com/53249626/232844506-190b6881-f7e9-482a-a2b6-3171297311cf.png)
![image](https://user-images.githubusercontent.com/53249626/232845704-321b7376-5ca4-479d-afff-f6be5ae132b5.png)

### Ожидаемое поведение

1. При экспорте в xml из edt не затираются значения свойств (TitleTextColor, BackColor и т.д.) 
2. в идеале вообще нет отличий (нет "фантомчиков")

### Лог рабочей области

.

### Версия 1С:EDT

Ruby 2022.2.4

### Операционная система

Windows

### Установленные плагины

1C:Code style V8, 1C:SSL-support

### Дополнительная информация

8.3.21.1709

[тест.zip](https://github.com/1C-Company/1c-edt-issues/files/11264235/default.zip)

**Comment by AndreyDanilov-nn** [comment]
Базовый проект делать не нужно было. В едт прогрузить только расширение из исходников.

>А после 4-го шага если открыть форму в расширении, то там нормально стили подгрузились

Значение свойства стоит правильное (ссылка на заимствованный стиль). Как визуально на форме выглядит не помню

>Причиной, по которой не выгружаются стили, может быть то, что ссылки на них оказались недостижимыми

Например ссылка на заимствованную картинку `botfather` "выгрузилась" (без базового проекта), хотя ссылка так же недостижима. Ожидаю что стиль так же выгрузится (не затрется) без базового.
![image](https://user-images.githubusercontent.com/53249626/233673377-edd32c76-bbc2-4330-9f3c-fc408b00f1b6.png)

**Comment by AndreyDanilov-nn** [comment]
> Элементы формы покрашены как ожидалось?

Нет визуально цвет слетел (что логично без базового проекта), значение свойства заполнено корректно
![image](https://user-images.githubusercontent.com/53249626/233677840-fc4d0bdd-c1fc-4329-a2ed-8b30e494896a.png)

**Comment by vadimeg** [comment]
Исправлено в 2023.1
