### ISSUE TITLE
Некорректная сортировка по полю Расположение в панели Задачи

### ISSUE THREAD

**Issue by potoyalo** [1C-Company/1c-edt-issues#976]
### Описание ошибки

Ошибка в том, что при сортировке по расположению номера строк сортируются как строки, а не как числа.

### Как воспроизвести

1. Перейдите в панель `Задачи`
2. Кликните по заголовку поля `Расположение`
3. Строки отсортированы не по порядку
![изображение](https://user-images.githubusercontent.com/1996464/234783289-0f55f915-c69c-4a48-8746-80af4bb8f455.png)

### Ожидаемое поведение

Ожидаемое поведение - при сортировке по расположению понимать номер строки как число. Пример корректной сортировки по расположению - в панели Закладки.
![изображение](https://user-images.githubusercontent.com/1996464/234783488-abd6f37d-bea1-4109-80d8-e281919b79af.png)

### Лог рабочей области

-

### Версия 1С:EDT

Ruby 2022.2.4

### Операционная система

Windows

### Установленные плагины

1C:Code style V8, 1C:SSL-support

**Comment by dsavenko** [comment]
Исправлено в 2024.1
