### ISSUE TITLE
Проблемы с типом ОписаниеОповещения

### ISSUE THREAD

**Issue by SeiOkami** [1C-Company/1c-edt-issues#978]
### Описание ошибки

В проектах на платформе 8.3.22 на строгой типизации платформенные методы ругаются на параметры ОписаниеОповещения 

### Как воспроизвести

1. Создаем проект на 8.3.22
2. Добавляем форму
3. В форме пишем код

```
&НаКлиенте
Процедура Тест()
	ПоказатьВводСтроки(Новый ОписаниеОповещения(), "");
КонецПроцедуры
```

5. Получаем ошибку _Вызываемый тип выражения не пересекается с типом: "ОписаниеОповещения" для параметра "ОписаниеОповещенияОЗавершении"_

### Ожидаемое поведение

![image](https://user-images.githubusercontent.com/42138875/234796845-d85983b4-ff11-4a2e-8342-9c76b7ebcc8e.png)

### Лог рабочей области

[log.txt](https://github.com/1C-Company/1c-edt-issues/files/11340991/log.txt)

### Версия 1С:EDT

Ruby 2022.2.5

### Операционная система

Windows

### Установленные плагины

1C:Code style V8

**Comment by marmyshev** [comment]
@MaksimDzyuba в контексте 8.3.22 остался тип NotifyDescription.type

**Comment by MaksimDzyuba** [comment]
@marmyshev он и должен был остаться для совместимости, в 8.3.22 платформа добавила новый тип CallbackDescription вместо NotifyDescription, но для совместимости нужно же сохранять оба. Но в параметрах теперь везде в выгрузке базы контекстов использует именно CallbackDescription, у которого имя тоже "ОписаниеОповещения". Я, честно, сходу не могу придумать, как выйти из ситуации, не пораждая костыли. Возможно, имеем смысл сказать, что они кастятся друг к другу

**Comment by MaksimDzyuba** [comment]
Проблему решил, результат войдет в 2023.1, не факт, что в первую тестовую
![bandicam-2023-05-03-18-36-51-955](https://user-images.githubusercontent.com/77277424/235966536-33ae4d99-26ba-488f-ac27-8e77f9b29b2c.gif)

**Comment by marmyshev** [comment]
@MaksimDzyuba  Наверное нужно пометить тип NotifyDescription как устаревший?
