### ISSUE TITLE
Ошибочно выдается сообщение Поле должно присутствовать в секции 'СГРУППИРОВАТЬ ПО' для выражений со значением перечислений, если значение отсутствует в выражении группировки.

### ISSUE THREAD

**Issue by DmitryShvaika** [1C-Company/1c-edt-issues#979]
### Описание ошибки

Ошибочно выдается сообщение Поле должно присутствовать в секции 'СГРУППИРОВАТЬ ПО' для выражений со значением перечислений, если значение отсутствует в выражении группировки.

![image](https://user-images.githubusercontent.com/54451084/234814832-3a027ead-0757-43d8-bd3a-466a0161eca6.png)

Конфигуратор на данный запрос ошибки не выдает, конструктор запросов в режиме платформы - то же.

### Как воспроизвести

1. Набрать запрос в прилагаемом тестовом проекте.

```
ВЫБРАТЬ
	Документ1.Реквизит,
	Документ1.Реквизит = ЗНАЧЕНИЕ(Перечисление.Перечисление1.Значение1) КАК Признак,
	СУММА(1)
ИЗ
	Документ.Документ1 КАК Документ1
СГРУППИРОВАТЬ ПО
	Документ1.Реквизит

```
2. Наблюдать ошибку

### Ожидаемое поведение

Ошибка в данном случае не должна выдаваться

### Лог рабочей области

не требуется

### Версия 1С:EDT

Ruby 2022.2.5

### Операционная система

Windows

### Дополнительная информация

архив проекта на котором работает пример
[test.zip](https://github.com/1C-Company/1c-edt-issues/files/11341741/test.zip)

Похожая проблема
https://github.com/1C-Company/1c-edt-issues/issues/972

**Comment by MaksimDzyuba** [comment]
Удалось исправить, исправление войдет, надеюсь в 2023.1, возможно, не в первую тестовую версию
![bandicam-2023-05-03-18-54-15-747](https://user-images.githubusercontent.com/77277424/235971340-da18460a-3fbe-4eee-ba59-ff7de63f2b3c.gif)
