### ISSUE TITLE
У поля ввода нет возможности включить расширенное редактирование

### ISSUE THREAD

**Issue by DmitryShvaika** [1C-Company/1c-edt-issues#980]
### Описание ошибки

У поля ввода нет возможности включить расширенное редактирование, хотя многострочный режим включен
В конфигураторе свойство доступно.

![image](https://user-images.githubusercontent.com/54451084/235170373-c57c2a40-b618-434b-8d00-78ee1d67466a.png)

### Как воспроизвести

1. Открыть свойства любого текстового поля ввода.
2. Установить многострочный режим = Да
3. Наблюдать ошибку

### Ожидаемое поведение

Свойство должно быть доступно

### Лог рабочей области

не требуется

### Версия 1С:EDT

Ruby 2022.2.5

### Операционная система

Windows

**Comment by vadimeg** [comment]
Исправлено в 2023.1
