### ISSUE TITLE
Внутри условия теряется описание типа

### ISSUE THREAD

**Issue by SeiOkami** [1C-Company/1c-edt-issues#982]
### Описание ошибки

Строгая типизация. Есть процедура с параметром. Параметр является структурой, описанной другой функцией. 
ЕДТ знает о ключах этой структуры.
Но когда внутри серии условий "Если" проверить параметр на Тип = Структура, то далее ЕДТ забывает про свойства структуры. И в условии нельзя обращаться к свойствам параметра. 

### Как воспроизвести

```
// @strict-types

// А.
// 
// Возвращаемое значение:
//  Структура - А:
// * А - Число -
Функция А()
	Возврат Новый Структура("А", 0);
КонецФункции

// Б.
// 
// Параметры:
//  А - см. А
Процедура Б(А)
	Если ТипЗнч(А) = Тип("Структура") 
		И А.А = 0 Тогда
	КонецЕсли;
КонецПроцедуры
```

### Скриншоты

![image](https://user-images.githubusercontent.com/42138875/235584711-f30128c2-04bd-4dcf-a916-fdc91b575d5f.png)
![image](https://user-images.githubusercontent.com/42138875/235584839-ad1e874c-8be6-4b40-9843-26a22208eb11.png)
![image](https://user-images.githubusercontent.com/42138875/235584932-4d0d6d07-44d9-46bb-8a62-2661f83b4802.png)

### Ожидаемое поведение

ЕДТ не забывает свойства

### Лог рабочей области

[log (2).txt](https://github.com/1C-Company/1c-edt-issues/files/11369968/log.2.txt)

### Версия 1С:EDT

Ruby 2022.2.5

### Операционная система

Windows

### Установленные плагины

1C:Code style V8

**Comment by MaksimDzyuba** [comment]
Здравствуйте, исправил, версия в которую войдет проставлю отдельно, как будет понятно (2023.1 или 2023.2)
![image](https://github.com/1C-Company/1c-edt-issues/assets/77277424/ab620fe5-2ba1-432f-8a6a-0129a186d2b3)
