### ISSUE TITLE
Отсутствует типизация переменной ПроверяемыеРеквизиты события объекта ОбработкаПроверкиЗаполнения

### ISSUE THREAD

**Issue by stolya** [1C-Company/1c-edt-issues#985]
### Описание ошибки

Ошибка в том что в общем модуле с включенным @strict-types выходит ошибка "Typed value is added to untyped collection" у операции добавления реквизита в массив "ПроверяемыеРеквизиты" для стандартной проверки заполненности.

### Как воспроизвести

В модуле объекта например справочника добавить следующий код:
```
// @strict-types

#Если Сервер Или ТолстыйКлиентОбычноеПриложение Или ВнешнееСоединение Тогда

#Область ОбработчикиСобытий

Процедура ОбработкаПроверкиЗаполнения(Отказ, ПроверяемыеРеквизиты)
	
	Если ПустаяСтрока(Наименование) Тогда
		ПроверяемыеРеквизиты.Добавить("ИногдаВажныйРеквизит");
	КонецЕсли;
	
КонецПроцедуры

#КонецОбласти
```

### Скриншоты

![image](https://user-images.githubusercontent.com/30523530/235732664-f31b3d02-6696-47dc-88c5-095783d4e813.png)

### Ожидаемое поведение

Отсутствие ошибки при передачи строки или переменной с типом строка.

### Лог рабочей области

[.log](https://github.com/1C-Company/1c-edt-issues/files/11375738/default.log)
[trace.log](https://github.com/1C-Company/1c-edt-issues/files/11375739/trace.log)

### Версия 1С:EDT

Ruby 2022.2.5

### Операционная система

Windows

### Установленные плагины

1C:Code style V8, 1C:SSL-support

**Comment by MaksimDzyuba** [comment]
исправлено, войдет в 2023.2
