### ISSUE TITLE
Ошибка возвращаемого типа объектом ОписаниеОповещения

### ISSUE THREAD

**Issue by stolya** [1C-Company/1c-edt-issues#986]
### Описание ошибки

Если в модуле включен @strict-types то для переменной с типом "ОписаниеОповещения" отображается ошибка при его применении: Invocation expression type is not intersect with type: "ОписаниеОповещения" for parameter "ОписаниеОповещенияОЗавершении"

### Как воспроизвести

Использовать код ниже

```
// @strict-types

#Область ОбработчикиСобытийФормы

&НаКлиенте
Процедура ПриОткрытии(Отказ)
	
	Описание = Новый ОписаниеОповещения("ПриОткрытииПродолжение", ЭтотОбъект);
	
	ПоказатьПредупреждение(Описание, "Сообщение");
	
КонецПроцедуры

#КонецОбласти

#Область СлужебныеПроцедурыИФункции

// При открытии продолжение.
//
// Параметры:
//  ДополнительныеПараметры - Произвольный
//
&НаКлиенте
Процедура ПриОткрытииПродолжение(ДополнительныеПараметры) Экспорт
	
	// Код
	
КонецПроцедуры

#КонецОбласти
```

Также ошибка появляться при использовании метода ПоказатьВопрос, ПоказатьВводДаты и т.п.

### Скриншоты

![image](https://user-images.githubusercontent.com/30523530/235802352-c77885ed-90ad-4d9f-af0f-23302e02c4cd.png)

### Ожидаемое поведение

Отсутствие ошибки

### Лог рабочей области

[.log](https://github.com/1C-Company/1c-edt-issues/files/11378190/default.log)
[trace.log](https://github.com/1C-Company/1c-edt-issues/files/11378192/trace.log)

### Версия 1С:EDT

Ruby 2022.2.5

### Операционная система

Windows

### Установленные плагины

1C:Code style V8, 1C:SSL-support

**Comment by adminimusRU** [comment]
Дубль #978

**Comment by MaksimDzyuba** [comment]
Проблему решил, исправление будет в 2023.1, правда не факт. что в первой тестовой
![bandicam-2023-05-03-18-36-51-955](https://user-images.githubusercontent.com/77277424/235966938-5ef1fd91-5bc9-497a-85d8-6875c9a1bad0.gif)
