### ISSUE TITLE
Выделяется и блокируется заголовок в панели свойств

### ISSUE THREAD

**Issue by KovAlexey** [1C-Company/1c-edt-issues#989]
### Описание ошибки

Ошибка в том что...
В редакторе формы при переходе с имени элемента на заголовок по нажатию TAB происходит "дерганье" интерфейса и поле перестает быть доступным для редактирования. Зато текст в нем почему-то выделен.
Такого не наблюдается нигде, кроме форм.

### Как воспроизвести

1. Выбрать элемент\реквизит формы
2. Выделить имя
3. Нажать TAB
4. Попробовать что-нибудь ввести
Далее для разнообразия можно попробовать перевести фокус в другое поле.
Если сначала убрать фокус с заголовка, потом вернуться обратно - все становится нормально

https://user-images.githubusercontent.com/16429518/236135107-1baa47b0-48e6-4b99-a037-085cabe12e16.mp4

### Ожидаемое поведение

Отсутствие блокировки поля заголовка

### Лог рабочей области

Не требуется

### Версия 1С:EDT

2022.2.5

### Операционная система

Windows

### Установленные плагины

Другие сторонние плагины `Название плагина...`

### Дополнительная информация

Сторонние плагины:
Darkest Dark Theme https://marketplace.eclipse.org/content/darkest-dark-theme-devstyle
edt-editing

**Comment by adminimusRU** [comment]
На стандартной светлой теме в 2022.2.5 не воспроизводится. Возможно в Darkest Dark снова что-то сломано.

**Comment by KovAlexey** [comment]
>  Эту задачу пока закрываем, так как данный механизм не попадает в приоритеты разработки на ближайшее время.

А как мне тогда отслеживать этот момент?

**Comment by Erik773** [comment]
Когда проблема будет устранена, мы сообщим об этом в комментарии к текущей задаче.

**Comment by marmyshev** [comment]
@Erik773  Это странный подход - закрывать ошибки здесь, если есть что-то внутренние. Такого в публичном регламенте нет. Тем более если планируется работа в далёком будущем это исправить.

Кажется "не планируемые в ближайшее время" лучше помечать меткой, и отключать от проекта.

**Comment by KovAlexey** [comment]
Поддерживаю.
Подход очень странный.

**Comment by KovAlexey** [comment]
Это **не завершенная** задача
