### ISSUE TITLE
EDT пытается использовать конкретную неподдерживаемую версию платформы при подключении к файловой базе

### ISSUE THREAD

**Issue by tormozit** [1C-Company/1c-edt-issues#990]
### Описание ошибки

После перехода с 2022.2.2 на 2022.2.5 столкнулся с ошибкой выполнения команды "Импортировать конфигурацию" из файловой базы. Проект на 8.3.20. Но EDT почему то упорно запускает 8.3.22. Рядом в рабочей области есть копия этого проекта и базы, где такой проблемы нет, т.е. аналогичная команда выполняется успешно.

В свойствах этой базы была прописана конкретная версия платформы 8.3.20.1914 (в файле списка баз v8i).
В свойствах приложения указано

![изображение](https://user-images.githubusercontent.com/11896251/236162857-4213afbe-8ac5-4f31-a778-b5815228e707.png)

Предполагаю что EDT пытается использовать ту конкретную версию 8.3.20.1914 . Но т.к. она не поддерживается, он берет почему то не следующую установленную 8.3.20.2290, а самую последнюю 8.3.22.

![изображение](https://user-images.githubusercontent.com/11896251/236163609-d898a994-c4d3-47a9-8a05-d83cda1a3993.png)

После очистки указания конкретной версии платформы в свойствах проблема в EDT пропала.

### Как воспроизвести

.

### Скриншоты

![изображение](https://user-images.githubusercontent.com/11896251/236161982-c6f1595d-ae78-4d1b-9c99-f4c5b95d0bc6.png)

### Ожидаемое поведение

EDT выбирает 8.3.20.2290

### Лог рабочей области

.

### Версия 1С:EDT

Ruby 2022.2.5

### Операционная система

Windows

### Установленные плагины

Нет плагинов

**Comment by Erik773** [comment]
[.log](https://github.com/1C-Company/1c-edt-issues/files/11404337/default.log)
[trace.log](https://github.com/1C-Company/1c-edt-issues/files/11404338/trace.log)

Удалось воспроизвести по следующему сценарию:

1. Установить версии платформы 8.3.21.1775, 8.3.21.1783, 8.3.22.1984;
2. Создать информационную базу на версии 8.3.21.1775;
3. Удалить версию платформы 8.3.21.1775;
4. Обновить в ЕДТ список платформ;
5. Импортировать конфигурацию из информационной базы в ЕДТ;
6. Повторно импортировать конфигурацию из информационной базы в ЕДТ;

**Comment by nikolay-martynov** [comment]
Здравствуйте. Если вы указываете номер версии платформы вплоть до номерка сборки, то могут наблюдаться различные ситуации при изменении списка доступных для EDT установок платформы 1С:Предприятие. Например, указанный вами случай обновления EDT, когда старая сборка платформы перестает поддерживаться средой и соответствующая ей установка просто перестаёт восприниматься. Для EDT такие неподдерживаемые сборки просто не существуют. И, если в настройках приложения или настройках информационной базы есть ссылки на эти более недоступные версии платформы, то возможны различные нештатные ситуации. EDT старается автоматически их обходить неявно переключаясь на другие версии, которые доступны в системе. Количество возможных сочетаний в зависимости от того, какой именно был тип привязки к версии платформы (конкретная установка, полная версия со сборкой, маска микроверсии, маска младшей версии) и того, как именно было произведено обновление (есть ли другие сборки, являются ли они доступными, есть ли другие младшие версии, какой набор компонент в этих установках, какой тип дистрибутива платформы 1С:Предприятие был использован и тому подобное) очень большое. Не во всех этих сочетаниях среда может выполнить автоматическую корректировку способом ожидаемым всеми пользователями. Пример, переключения на самую старшую версию платформы при недоступности указанной вы и наблюдали.
В соответствии с https://its.1c.ru/db/v8322doc#bookmark:adm:TI000000111 я рекомендую вам указывать не номер конкретной сборки (если только вы не тестируете работу приложения с усеченным набором компонентов), а маску вплоть до младшей версии. Тогда не придется менять версии при переходе с одной сборки платформы на другую. При этом, если вы укажете версию как маску "8.3.21", и при условии наличия в системе установок платформы 1С:Предприятие совместимых сборок, EDT не будет переключаться на установки 8.2.22, что может быть важно при работе с конфигурацией, предназначенной для работы с предыдущими версиями платформы.
Прошу обратить внимание, что привязка к версии платформы 1С:Предприятие осуществляется в двух местах:
- В редакторе свойств информационной базы
![image](https://github.com/1C-Company/1c-edt-issues/assets/13433348/65cc8cde-fce2-4521-8aef-cea47ba95d4d)
- В редакторе настроек доступа
![image](https://github.com/1C-Company/1c-edt-issues/assets/13433348/9220ce51-a5c1-41aa-9cd9-380dd64cb0d0)
Это два разных поля, которые после создания информационной базы и связи её с проектом задаются раздельно. В обоих полях следует установить идентичные значения. Это важно. Иначе возможна ситуация, когда агент конфигуратора себя автоматически перезапустит на другую версию. EDT это может воспринять как аварийное завершение агента конфигуратора. Похоже, что именно это и наблюдается в вашем случае.
В будущем мы бы хотели усовершенствовать способы привязки информационной базы к версии платформы 1С:Предприятие, упростить процесс для пользователей и сделать алгоритм подбора конкретной установки, которую должна использовать среда, более понятным. Однако, в настоящий момент я не могу поделиться с вами конкретными планами, когда эти улучшения станут доступны.

**Comment by nikolay-martynov** [comment]
Доброго дня. Сделал небольшую доработку, чтобы среда в первую очередь пыталась использовать другую сборку из той же микро версии платформы как у ранее указанной сборки, что была не найдена. Однако, всё ранее сказанное остаётся в силе, и вам по прежнему следует либо переключиться на маску микро версии (рекомендую именно этот вариант), либо на новую сборку. Сделать это надо по прежнему в двух местах: и в настройках доступа, и в свойствах информационной базы.
Улучшение будет доступно в версии 2023.2.
