### ISSUE TITLE
Сделать переключатель активного языка интерфейса как в конфигураторе

### ISSUE THREAD

**Issue by mrshadow300373** [1C-Company/1c-edt-issues#994]
### Описание проблемы

Сейчас просматривать синонимы на других языках в палитре свойств неудобно, если конфигурация "на замке" **то невозможно**. 
![image](https://user-images.githubusercontent.com/34220218/236410120-f3439b3f-a7b7-467b-92ae-d2a01fa2650f.png)

В конфигураторе этот вопрос решён, не без недостатков, описанных здесь: https://partners.v8.1c.ru/forum/topic/2129110

Но тем не менее есть возможность нажав сюда:
![image](https://user-images.githubusercontent.com/34220218/236408320-870126a1-df66-44e7-91f3-445f06ba2779.png)
Смотреть синонимы уже в другом языке:
![image](https://user-images.githubusercontent.com/34220218/236408687-ed2367ee-ae65-48e8-938e-e7c39cd27c24.png)

### Описание решения проблемы

Предлагаю сделать так же как в конфигураторе, кнопку переключения необязательно делать там же, желательно сразу избежать проблем описанных Сергеем по ссылке выше:
> Сейчас в окне сравнения конфигураций переключатель активного языка интерфейса в строке состояния не влияет на сравниваемую конфигурацию. Т.е. в палитре свойств при клике на колонке объекта сравниваемой конфигурации отображаются значения его свойств на основном языке конфигурации. Считаю такое поведение ошибочным, т.к. если просто открыть файл сравниваемой конфигурации в отдельном окне, то активный язык интерфейса учитывается при отображении значений свойств. Похоже на недоработку. Приходится много времени тратить, чтобы анализировать изменения текстовых значений на неосновном языке интерфейса. 
>
>Прошу сделать учет активного языка и при отображении свойств объектов сравниваемой конфигурации.

**Comment by tormozit** [comment]
Он есть в EDT 2022.2.5, но сверху.

![изображение](https://user-images.githubusercontent.com/11896251/236600313-ad928563-3462-42be-8823-a81b24b18e01.png)

**Comment by mrshadow300373** [comment]
> Он есть в EDT 2022.2.5, но сверху.

Стыдно то как.... Где глаза были... Спасибо!

**Comment by tormozit** [comment]
Я его тоже далеко не сразу нашел. Впрочем и в конфигураторе было так же.

**Comment by tormozit** [comment]
А проблема, описанная мной для окна сравнения в конфигураторе, тут исправлена?

**Comment by mrshadow300373** [comment]
> А проблема, описанная мной для окна сравнения в конфигураторе, тут исправлена?

Боюсь она вообще не применима, так как навигация по дереву сравнения объединения не приводит к актуализации панели свойств... А так хотелось бы.
