### ISSUE TITLE
При отмене рефакторинга началась пересборка проекта

### ISSUE THREAD

**Issue by KovAlexey** [1C-Company/1c-edt-issues#997]
### Описание ошибки

После отмены рефакторинга началась пересборка проекта

### Как воспроизвести

1. Выбрать любое пустое место модуля
2. Горячими клавишами запустить переименование
3. Отменить "Индексацию поиска"

### Ожидаемое поведение

Отсутствие пересборки

### Лог рабочей области

[20230510.zip](https://github.com/1C-Company/1c-edt-issues/files/11438468/20230510.zip)

### Версия 1С:EDT

2022.2.5

### Операционная система

Windows

**Comment by KovAlexey** [comment]
Коллеги, а как можно ошибки, приводящие к потере приличного времени и денег у бизнеса относить к "низкому приоритету"?

**Comment by MaksimDzyuba** [comment]
Здравствуйте, попробовал по-разному, но воспроизвести не удалось, приложил видео, как у меня ведет себя система на 2023.1, если ошибка все еще воспроизводится, то просьба прислать конфигурацию и видео, что надо делать.
![bandicam 2023-07-04 11-27-22-990](https://github.com/1C-Company/1c-edt-issues/assets/77277424/2fa8e2d6-2473-4cff-a614-99dd31c95dc1)

**Comment by MaksimDzyuba** [comment]
Ошибку закрываю, если еще раз повторится, то переоткроете, пожалуйста, сейчас не знаю, что в ней править, воспроизвести не могу
