### ISSUE TITLE
При поиске в навигаторе конфигурации первая часть слова поиска затирается, если вводить слово поиска быстро и поиск делать повторно (поверх предыдущего поиска)

### ISSUE THREAD

**Issue by DmitryShvaika** [1C-Company/1c-edt-issues#998]
### Описание ошибки

При поиске в навигаторе конфигурации часть слова поиска затирается, если вводить слово поиска быстро и поиск делать повторно (поверх предыдущего поиска)

Пытаюсь несколько раз ввести слово поиска "номенк"... вот что выходит в результате - см. видео Gif

![Поиск по конфигурации](https://github.com/1C-Company/1c-edt-issues/assets/54451084/e1bbf28c-0325-46a7-8ebd-9eef8b0560bd)

### Как воспроизвести

1. Повторить действия на видео:
2. Сделать первый поиск
3. Выделить слово поиска в строке поиска и поверх начать набирать (можно то же слово)
4. Вводить слово поиска надо относительно быстро, слово поиска должно быть длиннее 4-х символов

Результат: "съедается" первая часть слова

### Ожидаемое поведение

Слово должно набираться полностью и обновление навигатора не должно сбрасывать строку поиска.

### Лог рабочей области

не требуется

### Версия 1С:EDT

Ruby 2022.2.5

### Операционная система

Windows

**Comment by RedMammoth** [comment]
Дубль https://github.com/1C-Company/1c-edt-issues/issues/961 ?
