### ISSUE TITLE
Долгое блокирование интерфейса при наведении указателя на подменю "Администрирование" приложения 1С

### ISSUE THREAD

**Issue by tormozit** [1C-Company/1c-edt-issues#999]
### Описание ошибки

![изображение](https://github.com/1C-Company/1c-edt-issues/assets/11896251/362a53f1-15e0-46e1-9254-4aa139e6c784)

### Как воспроизвести

.

### Ожидаемое поведение

.

### Лог рабочей области

.

### Версия 1С:EDT

Ruby 2022.2.5

### Операционная система

Windows

### Установленные плагины

1C:Language Tool

**Comment by Erik773** [comment]
Здравствуйте, могли бы Вы, пожалуйста, чуть подробнее описать проблему и предоставить логи рабочей области ЕДТ?

**Comment by tormozit** [comment]
Навел указатель на подменю и интерфейс перестал реагировать на движение указателя на 2-5 секунд. Повторяется во всех рабочих областях моих. Подозреваю, что  может быть связано с большим файлом списка баз 1С (v8i)

**Comment by nikolay-martynov** [comment]
Здравствуйте. Дело в том, что доступность пунктов контекстного меню зависит в том числе и от характеристик платформы 1С:Предприятие. Например, от её версии и списка установленных компонент. Проблема усугубляется, когда в системе установлено много версий платформы. Данный аспект поведения системы был оптимизирован и теперь расчёт доступности пунктов контекстного меню много времени не занимает. Улучшение должно быть доступно начиная с версии 2023.3.
